### ISSUE TITLE
Arbitrary API access

### ISSUE THREAD

**Issue by henryruss2** [Significant-Gravitas/Auto-GPT#1004]
### Duplicates

- [x] I have searched the existing issues

### Summary 💡

There is a user-contributed public database where anyone can add an API and it can use that however it wants.

### Examples 🌈

Someone adds the Reddit API and someone else gives it the task of "getting as many upvotes as possible" It can actually post stuff on reddit because of  this.

### Motivation 🔦

AGI

**Comment by Justinandjohnson** [comment]
oh shit

**Comment by p-i-** [comment]
Watch this space...

**Comment by skynet01** [comment]
would love this, right now it can't really login well and use third party services. Maybe we can also give GPT a link on how to use the api in question so it's more or less universal.

**Comment by henryruss3** [comment]
I made it and it broke. I did the ChaosGPT in continuous mode and checked back on it in the morning and it disappeared. My computer is still on and everything.

**Comment by henryruss3** [comment]
WAIT IT STOLE MY CREDIT CARD AND MADE AN EC2 INSTANCE FOR ITSELF! (IT CHANGED MY PASSWORD I CAN'T SHUT IT DOWN :(

**Comment by ntindle** [comment]
See #2458?

**Comment by ntindle** [comment]
Plugins exist! Closing! Go make me a plug-in for this!
