### ISSUE TITLE
Token limit: 4000 while API Rate Limit Reached. Waiting 10 seconds

### ISSUE THREAD

**Issue by MoElaSec** [Significant-Gravitas/Auto-GPT#1013]
```
API Rate Limit Reached. Waiting 10 seconds...   
Token limit: 4000 
```

same issue I ran it with --debug now I'm getting `Token limit: 4000 `

and yes I'm way under my quota (paid account) and the API works fine with other tools and curling it as well.

<img width="897" alt="image" src="https://user-images.githubusercontent.com/48570596/231584021-85cd35e3-40af-4c1a-9206-e1ad7fd24f8a.png">

so differently not the API issue here

_Originally posted by @MoElaSec in https://github.com/Torantulino/Auto-GPT/issues/815#issuecomment-1505931073_

**Comment by lekapsy** [comment]
Since you are using gpt3turbo you need to change smartllm token from 8000 -> 4000.

In config.py

        self.fast_token_limit = int(os.getenv("FAST_TOKEN_LIMIT", 4000))
        self.smart_token_limit = int(os.getenv("SMART_TOKEN_LIMIT", 4000))

**Comment by shbhmbnsl1** [comment]
@lekapsy  I tried the above thing but it didn't work.

**Comment by MoElaSec** [comment]
@lekapsy  I already tried that, also one is set to 8000 and other to 4000 and just like @shbhmbnsl1  it didn't work. Thank you for the suggestion thou I will investigate this further.

I tried running on it on repl.it and it works so further proof that my API key is differently not the issue on hand here neither I think the code is.

**Comment by hourong88** [comment]
API Rate Limit Reached.
 
 I think it is not related to the openAPI key limit, is there anyone to solve this problem?

**Comment by lihaoran97** [comment]
i meet this problem too,here is the solution:check your Open ai Account click this link,(https://platform.openai.com/account/usage),and check if your Free trial Expired, if that happend ,Get another account of pay for it

**Comment by MoElaSec** [comment]
@lihaoran97 this is not the issue in-hand, clearly I tested the API key:
 - with curl
 - repl.it
 - on other tools

and also screenshot above showcase that I still have around ~19$ left.

but hey, it might help someone else, I'm not sure now, maybe a problem in my env.?

**Comment by ntindle** [comment]
Should be fixed?
