### ISSUE TITLE
pip install -r requirements.txt fails on Windows 10

### ISSUE THREAD

**Issue by matts8008** [Significant-Gravitas/Auto-GPT#103]
This is after a clean installation of Windows 10 and Python 3.11.2

`
PS C:\Users\Me\Auto-GPT> python.exe -m pip install --upgrade pip
Requirement already satisfied: pip in c:\users\me\appdata\local\programs\python\python311\lib\site-packages (22.3.1)
Collecting pip
  Downloading pip-23.0.1-py3-none-any.whl (2.1 MB)
     ---------------------------------------- 2.1/2.1 MB 4.2 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.3.1
    Uninstalling pip-22.3.1:
      Successfully uninstalled pip-22.3.1
Successfully installed pip-23.0.1
PS C:\Users\Me\Auto-GPT> pip install -r requirements.txt
Collecting beautifulsoup4
  Using cached beautifulsoup4-4.12.0-py3-none-any.whl (132 kB)
Collecting colorama==0.4.6
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting openai==0.27.2
  Using cached openai-0.27.2-py3-none-any.whl (70 kB)
Collecting playsound==1.3.0
  Using cached playsound-1.3.0.tar.gz (7.7 kB)
  Preparing metadata (setup.py) ... done
Collecting python-dotenv==1.0.0
  Using cached python_dotenv-1.0.0-py3-none-any.whl (19 kB)
Collecting pyyaml==6.0
  Using cached PyYAML-6.0-cp311-cp311-win_amd64.whl (143 kB)
Collecting readability-lxml==0.8.1
  Using cached readability_lxml-0.8.1-py3-none-any.whl (20 kB)
Collecting requests
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Collecting tiktoken==0.3.3
  Using cached tiktoken-0.3.3-cp311-cp311-win_amd64.whl (579 kB)
Collecting docker
  Using cached docker-6.0.1-py3-none-any.whl (147 kB)
Collecting googlesearch-python
  Using cached googlesearch-python-1.2.0.tar.gz (7.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Me\AppData\Local\Temp\pip-install-rianlxrf\googlesearch-python_a768096d81c94b52a28591c50b5b8ecf\setup.py", line 6, in <module>
          with open("requirements.txt") as fh:
               ^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
PS C:\Users\Me\Auto-GPT>`

**Comment by cliffmu** [comment]
I have the same issue

**Comment by Emilot** [comment]
I had to remove googlesearch-python from requirements (for now)

**Comment by Emilot** [comment]
https://github.com/Torantulino/Auto-GPT/issues/95#issuecomment-1494870187

this has done it

Thanx @cliffmu
