### ISSUE TITLE
Show how many auto command remaining when using y -N

### ISSUE THREAD

**Issue by TheAIAdopter** [Significant-Gravitas/Auto-GPT#1035]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Would be great to be able to see the remaining -N variable when using y -N command. 

### Motivation 🔦

Would allows us to know how many request have been made so far and how many still remaining

**Comment by Bentlybro** [comment]
hello there

**Comment by Boostrix** [comment]
To see how it's doing, it would also make sense to look at the number of errors/warnings it is processing - i.e. basically provide a number for the history of past actions

**Comment by k-boikov** [comment]
Fixed with https://github.com/Significant-Gravitas/Auto-GPT/pull/3322
