### ISSUE TITLE
An error happened when execute gol

### ISSUE THREAD

**Issue by yanjunnf** [Significant-Gravitas/Auto-GPT#1037]
### Duplicates

- [ ] I have searched the existing issues

### Steps to reproduce 🕹

Please see my actions below.

Continue (y/n): n
Welcome to Auto-GPT!  Enter the name of your AI and its role below. Entering nothing will load defaults.
Name your AI:  For example, 'Entrepreneur-GPT'
AI Name: yanjun
yanjun here! I am at your service.
Describe your AI's role:  For example, 'an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.'
yanjun is: A bot
Enter up to 5 goals for your AI:  For example: Increase net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously'
Enter nothing to load defaults, enter nothing when finished.
Goal 1: Please introduce yourself to me
Goal 2: 
Using memory of type: LocalCache
thread '<unnamed>' panicked at 'assertion failed: encoder.len() == decoder.len()', src/lib.rs:458:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/Users/creditease/workspace/projects/Auto-GPT/scripts/main.py", line 321, in <module>
    assistant_reply = chat.chat_with_ai(
                      ^^^^^^^^^^^^^^^^^^
  File "/Users/creditease/workspace/projects/Auto-GPT/scripts/chat.py", line 77, in chat_with_ai
    next_message_to_add_index, current_tokens_used, insertion_index, current_context = generate_context(
                                                                                       ^^^^^^^^^^^^^^^^^
  File "/Users/creditease/workspace/projects/Auto-GPT/scripts/chat.py", line 37, in generate_context
    current_tokens_used = token_counter.count_message_tokens(current_context, model)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/creditease/workspace/projects/Auto-GPT/scripts/token_counter.py", line 16, in count_message_tokens
    encoding = tiktoken.encoding_for_model(model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tiktoken/model.py", line 75, in encoding_for_model
    return get_encoding(encoding_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tiktoken/registry.py", line 63, in get_encoding
    enc = Encoding(**constructor())
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tiktoken/core.py", line 50, in __init__
    self._core_bpe = _tiktoken.CoreBPE(mergeable_ranks, special_tokens, pat_str)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: assertion failed: encoder.len() == decoder.len()

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by ithou** [comment]
+1

**Comment by hzhWord** [comment]
+1

**Comment by gearpart** [comment]
Have you solved it? Same question here

**Comment by zhang4014439175** [comment]
Did you solved it?

**Comment by Qoyyuum** [comment]
Closing issue. OP is using an old script way before the stable release. Please use the latest stable release and try again.

**Comment by gearpart** [comment]
> Closing issue. OP is using an old script way before the stable release. Please use the latest stable release and try again.

NO it doesnt.same issue happened  in Auto-GPT-stable-0.2.2

**Comment by PerseveranceZ** [comment]
+1
