### ISSUE TITLE
Navigating in the python console

### ISSUE THREAD

**Issue by AndresCdo** [Significant-Gravitas/Auto-GPT#104]
![image](https://user-images.githubusercontent.com/73312784/229625469-5f6e2253-3dd7-4b74-89f8-015ae15b4712.png)

It's not allowed to navigate to the beginning/end of words in the python console

**Comment by AndresCdo** [comment]
> how is it an issue with the Auto-GPT project?

How do you edit interactively your input in the project?

**Comment by Provello** [comment]
> ![image](https://user-images.githubusercontent.com/73312784/229625469-5f6e2253-3dd7-4b74-89f8-015ae15b4712.png)
> 
> It's not allowed to navigate to the beginning/end of words in the python console

I've tried this on PyCharm and Windows Powershell, and left and right arrows are not escaping when using left and right arrows or home/end

Would probably need reproduce steps to even think about trying to figure out this issue

**Comment by AndresCdo** [comment]
> > ![image](https://user-images.githubusercontent.com/73312784/229625469-5f6e2253-3dd7-4b74-89f8-015ae15b4712.png)
> > It's not allowed to navigate to the beginning/end of words in the python console
> 
> I've tried this on PyCharm and Windows Powershell, and left and right arrows are not escaping when using left and right arrows or home/end
> 
> Would probably need reproduce steps to even think about trying to figure out this issue

This happens when trying to use the Ctrl key together with the left and right arrows to jump.

**Comment by Qoyyuum** [comment]
Just press backspace and retype your inputs. This is normal when typing inputs in CLI.
