### ISSUE TITLE
access the files in my hard drive

### ISSUE THREAD

**Issue by LDY911** [Significant-Gravitas/Auto-GPT#1045]
How can I give Auto-GPT permission to access the files in my hard drive?

**Comment by LDY911** [comment]
When i let Auto-GPT to access my files, i just got:
Error: Attempted to access outside of working directory.

**Comment by murfASM** [comment]
> When i let Auto-GPT to access my files, i just got:
> 
> Error: Attempted to access outside of working directory.

How did you even manage to give it access to files to begin with? For me it tries using bash commands but won't recognize them. I'm wondering if putting a bash script on the workspace folder will fix it, I'm gonna try in the morning. Let me know if you end up fixing it before then though. Also after so many tasks mine crashes, there was a fix to the older auto version I found using the OPENAI_API_BASE in env but that variable isn't there anymore in this version.

**Comment by GrzegorzKarczewski** [comment]
Its hardcoded in file file_operations.py  that working directory=auto_gpt_workspace, few minor changes to that file and i think you can do it

**Comment by prigozhinfan** [comment]
> When i let Auto-GPT to access my files, i just got: Error: Attempted to access outside of working directory.

I had the same error, but it managed to figure it out later on by itself. Just let it keep running.

**Comment by LDY911** [comment]
> Its hardcoded in file file_operations.py that working directory=auto_gpt_workspace, few minor changes to that file and i think you can do it

This is very helpful for me. Thank you for your suggestions！

**Comment by GrzegorzKarczewski** [comment]
> > Its hardcoded in file file_operations.py that working directory=auto_gpt_workspace, few minor changes to that file and i think you can do it
> 
> This is very helpful for me. Thank you for your suggestions！

Be careful though, there are some other files that also contain that safety measure. So go, and search all the files in scripts for words like "working directory" or "auto_gpt_workspace"

**Comment by LDY911** [comment]
> > > Its hardcoded in file file_operations.py that working directory=auto_gpt_workspace, few minor changes to that file and i think you can do it
> > 
> > 
> > This is very helpful for me. Thank you for your suggestions！
> 
> Be careful though, there are some other files that also contain that safety measure. So go, and search all the files in scripts for words like "working directory" or "auto_gpt_workspace"

Thanks a lot

**Comment by Pwuts** [comment]
Keep an eye on #1875
