### ISSUE TITLE
AutoGPT and Linux Tool/File Access

### ISSUE THREAD

**Issue by murfASM** [Significant-Gravitas/Auto-GPT#1051]
I tried using auto to debug code and copy a file backup so it can protect the original but when it tried using cp it said command not found. This is probably because of the commands it had preloaded and it just wasn't recognized? I'm not sure, saw the developer on twitter using it with VS :/ Should I put a bash script in the workspace to give it access to my shell? Or is that not the way to go about it?

**Comment by Pwuts** [comment]
Please post your prompt+log and reopen.
