### ISSUE TITLE
Questions: Continuity between executions? Is it OK to update prompt.txt well after new creating a new name?

### ISSUE THREAD

**Issue by ed1g1tal** [Significant-Gravitas/Auto-GPT#1052]
It seems that between executions of Auto-GPT that it starts over from scratch with the goals, plan, etc. I am using Redis. Shouldn't that create persistent long-term memory so that the AI can pick up where it left off? 

Also, is it bad practice to update the prompt.txt well into a Auto-GPT "session" after several tasks have completed?

**Comment by ed1g1tal** [comment]
Thanks @james431987. I may try Pinecone for the long-term memory. Seems to me like AGPT should be able to pick up where it left off to some degree.

**Comment by james431987** [comment]
> Thanks @james431987. I may try Pinecone for the long-term memory. Seems to me like AGPT should be able to pick up where it left off to some degree.

from my experience pinecone has vastly improved AutoGPTs ability to stay on task. Feels a lot less broken.

Let me know if you experience it picking up where it left off.

**Comment by Pwuts** [comment]
Closing as resolved. Also related: #822
