### ISSUE TITLE
Error: search() got an unexpected keyword argument 'num_results'

### ISSUE THREAD

**Issue by SunilWarrier** [Significant-Gravitas/Auto-GPT#106]
I managed to make it work  by an alternate way to import google but 
The majority of the time, we get the following error, and it goes in the loop for a long time 
SYSTEM:  Command google returned: Error: search() got an unexpected keyword argument 'num_results'
or 
get 404 for the links it is trying to load.

**Comment by Alaa-Taieb** [comment]
Same here!

**Comment by SunilWarrier** [comment]
I have successfully added the Google API to the system today. However, I am encountering an issue where the program gets stuck in an infinite loop when attempting to use it with the following errors . 
**Error: Invalid JSON
NEXT ACTION:  COMMAND = Error: ARGUMENTS = string indices must be integers, not 'str'**
I was unable to complete a single set, and had to stop the process this morning after it hung overnight.
---------------------------
**NEXT ACTION:  COMMAND = Error: ARGUMENTS = string indices must be integers, not 'str'**
SYSTEM:  Command Error: returned: Unknown command Error:
Warning: Failed to parse AI output, attempting to fix.
 If you see this warning frequently, it's likely that your prompt is confusing the AI. Try changing it up slightly.
Failed to fix ai output, telling the AI.
Error: Invalid JSON
 I apologize for the previous errors. Here are three more commands: { "command": { "name": "memory_ovr", "args": { "key": "my_key", "string": "This is the 
updated string." } }, "thoughts": { "text": "Overwriting a memory value", "reasoning": "To update or overwrite a value in memory, we can use the 'memory_ovr' command to permanently update the specified key with the new value.", "plan": "- Use the 'memory_ovr' command to update or overwrite a value in memory.\n- Provide the key of the desired pair to be updated as the 'key' argument.\n- Provide the updated string to be saved to memory as the 'string' argument.", "criticism": "We should ensure that any key-value pair being overwritten is no longer necessary and that any necessary information or findings from the overwritten pair are properly documented or assigned elsewhere.", "speak": "Overwriting a memory value." } }, { "command": { "name": "list_agents", "args": {} }, "thoughts": { "text": "Listing active GPT agents", "reasoning": "To list all active GPT agents, we can use the 'list_agents' command to return the names and tasks of all active agents.", "plan": "Use the 'list_agents' command to list active GPT agents.", "criticism": "We should ensure that active agents 
are performing tasks efficiently and effectively, and that any necessary information or findings from the agents' output are properly documented or assigned elsewhere.", "speak": "Listing active GPT agents." } }, { "command": { "name": "evaluate_code", "args": { "code": "def multiply(a, b):\n return a * b" } 
}, "thoughts": { "text": "Evaluating Python code", "reasoning": "To evaluate a block of Python code, we can use the 'evaluate_code' command to run the code and return its output.", "plan": "- Use the 'evaluate_code' command to run Python code.\n- Provide the desired Python code as the 'code' argument.", "criticism": "We should ensure that any code evaluated is secure and that any necessary information or findings from the code's output are properly documented or assigned elsewhere.", "speak": "Evaluating Python code." } }
CHATBOTGPT THOUGHTS: 
REASONING: 
CRITICISM: 
Warning: Failed to parse AI output, attempting to fix.
 If you see this warning frequently, it's likely that your prompt is confusing the AI. Try changing it up slightly.
Failed to fix ai output, telling the AI.
**NEXT ACTION:  COMMAND = Error: ARGUMENTS = string indices must be integers, not 'str'**

**Comment by rvnikita** [comment]
I also get string indices must be integers, not 'str' error.

**Comment by Pwuts** [comment]
Closing as stale. Please reopen if still relevant.
