### ISSUE TITLE
Auto-GPT not detecting the OS. Trying to execute linux commands in Win Powershell

### ISSUE THREAD

**Issue by MayurVirkar** [Significant-Gravitas/Auto-GPT#1077]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Run Auto-GPT in windows powershell and ask it to a file. 

### Current behavior 😯

It tries to create files using touch command.

 {'command_line': 'touch test/test.js}

![image](https://user-images.githubusercontent.com/4211478/231715915-526e23e3-f5e1-4ecb-bc7d-a616bde07c56.png)

### Expected behavior 🤔

To detect that its on windows  and use ni instead of touch.

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by jnt0rrente** [comment]
Until this is implemented, did you try specifying it it is on a windows platform? What was the result? Kinda curious.

**Comment by Qoyyuum** [comment]
@MayurVirkar you have to prompt and tell it that you are on a Windows machine. The AI thinks you're on Linux by default. Please try again with the latest stable release.
