### ISSUE TITLE
Autoupdater: Auto `git pull` at startup

### ISSUE THREAD

**Issue by Artemonim** [Significant-Gravitas/Auto-GPT#1080]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

We need a script, which will check the updates, do `git pull` and restart the run

### Examples 🌈

1. `git status`
2. If there are updates - offer the user to update
3. Update and restart

### Motivation 🔦

Autoupdates are cool

**Comment by RowanFN** [comment]
I just have a .bat file that does this, so I can update it when needed. As sometimes I find this working well, other times from an update it can be a lil buggy.

If you edit any files though, sometimes the pull doesn't happen, so save or delete them and the pull should update everything

**Comment by Artemonim** [comment]
> If you edit any files though, sometimes the pull doesn't happen, so save or delete them and the pull should update everything

All or almost all of the files that can be changed during standard Auto-GPT use are listed in `.gitignore`, so this shouldn't be a problem.
It would be great if you pull request your .bat file that updates and runs the Auto-GPT

**Comment by RowanFN** [comment]
> > If you edit any files though, sometimes the pull doesn't happen, so save or delete them and the pull should update everything
> 
> All or almost all of the files that can be changed during standard Auto-GPT use are listed in `.gitignore`, so this shouldn't be a problem. It would be great if you pull request your .bat file that updates and runs the Auto-GPT

I'll send the code I have to make your own when I'm on the pc tonight. But I just did a simple run pull, wait, run requirements, wait, then whatever settings I need (I have a few .bat files for gpt3only/continuous etc)

**Comment by p-i-** [comment]
We could add some code that checks the current git branch and checks the commit hash against the remote.
- Message to console `Using branch MASTER` or `Using branch STABLE`
- If it's out of date, message (in red) `4 commits behind remote. `git pull` to pull the latest changes.

Does someone feel like taking this on?

**Comment by OannesGPT** [comment]
> I just have a .bat file that does this, so I can update it when needed. As sometimes I find this working well, other times from an update it can be a lil buggy.
> 
> If you edit any files though, sometimes the pull doesn't happen, so save or delete them and the pull should update everything

Wow, thanks that brilliant for me as a new coder. For anyone interested how-to:
Make a new file called install_requirements.bat
Add the following  code:

```
pip install -r requirements.txt
pause

```

**Comment by RowanFN** [comment]
> > I just have a .bat file that does this, so I can update it when needed. As sometimes I find this working well, other times from an update it can be a lil buggy.
> > If you edit any files though, sometimes the pull doesn't happen, so save or delete them and the pull should update everything
> 
> Wow, thanks that brilliant for me as a new coder. For anyone interested how-to: Make a new file called install_requirements.bat Add the following code:
> 
> ```
> pip install -r requirements.txt
> pause
> ```

I'm on the PC, so I can share the code if you want.

I have this with the last one changing to how I want to run AutoGPT at the time.

`start cmd /c git pull
timeout /t 5 /nobreak
start cmd /c pip install -r requirements.txt
timeout /t 5 /nobreak
start cmd /k python scripts/main.py`

I use a timeout, rather than a pause to it's more auto, and enough time to pull and then get the required files. I could use wait but unsure atm if it properly does, so for now I use a timeout. /nobreak means I can't interrupt it so I can't accidentally move onto the next section if it is updating.

Having a proper system to rename/remove files it doesn't want to overwrite and so not pull at all would be good.
