### ISSUE TITLE
Add Bing's API/Cookie support?

### ISSUE THREAD

**Issue by Sissidark** [Significant-Gravitas/Auto-GPT#1081]
### Summary 💡

support for Bing's version of ChatGPT, powered by GPT-4.

### Motivation 🔦

New Bing also using the GPT-4 model.

**Comment by Alimjan2013** [comment]
but new bing has limit with 20 times

**Comment by PeterNjeim** [comment]
You can start a new thread and dump some context in the first message, however there's a 2000 character limit per message meaning this will reach its limit. You can instead spread the context over multiple messages, telling Bing to wait until you say you're done. At some point the context will be so long that you'll use all 20 messages for context and can no longer continue. Also there's a 200 daily message limit so there's that as well

**Comment by Sissidark** [comment]
> 但新必应有 20 次限制

https://github.com/waylaidwanderer/node-chatgpt-api
this project bring Sydney back and have a jailbreak mode to make Sydney unlimited.
So I think is there one way to make AutoGPT work with Sydney.

**Comment by Sissidark** [comment]
> > but new bing has limit with 20 times
> 
> https://github.com/waylaidwanderer/node-chatgpt-api this project bring Sydney back and have a jailbreak mode to make Sydney unlimited. So I think is there one way to make AutoGPT work with Sydney.

**Comment by PeterNjeim** [comment]
Actually this wouldn't work since Sydney doesn't like it when you tell it how to respond. Since Microsoft chooses the system prompts for Bing, and has a high chance of saying "sorry I can't continue", etc., I think it would fail at Auto-GPT. This is just my opinion after thinking about it for a while

**Comment by ntindle** [comment]
Plans to support other LLMs are in place. Closing in favor of more through issues

**Comment by PeterNjeim** [comment]
Apparently the 2000 character limit is just an HTML limit, 20000 is the real limit
