### ISSUE TITLE
无法读取api

### ISSUE THREAD

**Issue by jayusnl** [Significant-Gravitas/Auto-GPT#1084]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Please set your OpenAI API key in config.py or as an environment variable.
You can get your key from https://beta.openai.com/account/api-keys

### Current behavior 😯

Please set your OpenAI API key in config.py or as an environment variable.
You can get your key from https://beta.openai.com/account/api-keys

### Expected behavior 🤔

怎么样修改

### Your prompt 📝

Please set your OpenAI API key in config.py or as an environment variable.
You can get your key from https://beta.openai.com/account/api-keys

**Comment by waffle105** [comment]
怎么才能修改呢   在代码的第几行？ 我找不到填写的地方，谢谢

**Comment by jiulun** [comment]
参考readme.md。
把文件名.env.template改成.env。
在第15行修改，OPENAI_API_KEY=
