### ISSUE TITLE
can write python code and correct by it self ? like this ai: ai.zyinfo.pro

### ISSUE THREAD

**Issue by hayooucom** [Significant-Gravitas/Auto-GPT#1088]
### Summary 💡

in this repo : 

https://github.com/hayooucom/Yet-Another-Auto-GPT

develop a method auto repair or correct generate python code by it self.

add task function ,to let AI write a whole program.

test demo:
https://ai.zyinfo.pro

has repair command:

task-repair or auto repair

### Examples 🌈

auto generate python code to finish your mission.

including screenshot of website , draw y=2x pic ,send to you ... 

helps you finish complex mission.

![](https://github.com/hayooucom/Yet-Another-Auto-GPT/blob/main/img/draw.png?raw=true)

### Motivation 🔦

write whole program ,and run it self.

**Comment by Pwuts** [comment]
Closing as already implemented
