### ISSUE TITLE
gitignore ai_settings.yaml and add template to repo

### ISSUE THREAD

**Issue by p-i-** [Significant-Gravitas/Auto-GPT#1106]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

`git pull` may delete your `ai_settings.yaml`

It may fail due to a conflict with this file.

Grateful if someone can clean this up.

### Current behavior 😯

It can fail.

### Expected behavior 🤔

It should succeed.

### Your prompt 📝

Prompt N/A here.

Issue is this:

https://github.com/Torantulino/Auto-GPT/pull/742
^ This PR removed ai_settings.yaml as the file gets autogenerated on the first run.

Current `master` does NOT have this file.
Current `stable` DOES have this file. Not sure how that happened.

One developer gets one problem (`git pull` failed due to conflict over `ai_settings.yaml`)
Another developer reports a different problem (`ai_settings.yaml` removed)

This needs to be tidied up.

My suggestion:
- A `ai_settings.yaml.example` file in the repo (but no `ai_settings.yaml`)
- When `main.py` executes, it looks for `ai_settings.yaml`
  - If found, it uses these values
  - If not, it loads the values from ai_settings.yaml.example and prompts the user whether they wish to modify these default values
  - The default `ai_role` looks suspiciously like a PaperClip Optimizer:
    ```
      ai_role: an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.
    ```
   
    How about: 
    ```
      ai_role: an AI designed to autonomously develop and operate a profitable and ethical business.
    ```

Grateful if someone takes a look. Welcome to ping me on the Discord pi#8377.

**Comment by lc0rp** [comment]
I noticed that the master now includes a .gitignore file and an ai_settings.yaml file, so part of the task is already complete. 

As for the other part, the app has changed since this PR was created. The current operation may supersede the need for ai_settings.yaml.example.
