### ISSUE TITLE
Use local GPT4all instead of openai's API

### ISSUE THREAD

**Issue by talvasconcelos** [Significant-Gravitas/Auto-GPT#1107]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Would it be possible to instead of using the OpenAI's API to access chatGPT use a local GTP, like GPT4all?

### Motivation 🔦

Reduce the cost of operation

**Comment by PlutoniaX** [comment]
i literally had this thought in the shower and you beat me to posting =D

**Comment by Wladastic** [comment]
Working on it right now.
I will finish adding Telegram first.

**Comment by Joackk** [comment]
I'm also looking forward to using local api instead of oepnAI

**Comment by LixU-Desu** [comment]
There is a way, but you would have to download the GPT4ALL program, turn it on is to use it in place of the API. But could have one that does not use the open program.

https://docs.gpt4all.io/gpt4all_chat.html#gpt4all-chat-server-mode

import openai

openai.api_base = "http://localhost:4891/v1"
#openai.api_base = "https://api.openai.com/v1"

openai.api_key = "not needed for a local LLM"

# Set up the prompt and other parameters for the API request
prompt = "Who is Michael Jordan?"

# model = "gpt-3.5-turbo"
#model = "mpt-7b-chat"
model = "gpt4all-j-v1.3-groovy"

# Make the API request
response = openai.Completion.create(
    model=model,
    prompt=prompt,
    max_tokens=50,
    temperature=0.28,
    top_p=0.95,
    n=1,
    echo=True,
    stream=False
)

# Print the generated completion
print(response)

**Comment by Joackk** [comment]
> 有一种方法，但您必须下载 GPT4ALL 程序，打开它是使用它来代替 API。但是可以有一个不使用开放程序的。
> 
> https://docs.gpt4all.io/gpt4all_chat.html#gpt4all-chat-server-mode

Does this not require the use of the GPT key? Will it work even if you lose the network?

**Comment by Wladastic** [comment]
I could add this one on top:
https://github.com/oobabooga/text-generation-webui/tree/main/extensions/openai
I Havent yet run gpt4all on my machine, but oobabooga works with a few plugins for text-gen.
