### ISSUE TITLE
D:\Anaconda\lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated   "class": algorithms.Blowfish,

### ISSUE THREAD

**Issue by huanyu233** [Significant-Gravitas/Auto-GPT#1109]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

D:\Anaconda\lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,

### Current behavior 😯

D:\Anaconda\lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,

### Expected behavior 🤔

D:\Anaconda\lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,

### Your prompt 📝

这个警告有问题嘛D:\Anaconda\lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,

**Comment by lc0rp** [comment]
This needs more information and may be obsolete. I'm closing it but please reopen it and provide more information if it's still an issue.
