### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by Leven1113** [Significant-Gravitas/Auto-GPT#1111]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14d65c9942b0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by huangjingshuai** [comment]
I'm facing the same problem too

**Comment by tycryptty** [comment]
+1

**Comment by clarck7gmailcom** [comment]
+1, but check your 'paid plan' first, if you are a trail user with the usage expired, the autogpt might not work.

**Comment by Leven1113** [comment]
> +1, but check your 'paid plan' first, if you are a trial user with the usage expired, the autogpt might not work.
Yes, I am a trial user, but the free quota has not expired. Do I need to set up a payment plan before I can use it?

**Comment by Leven1113** [comment]
> +1, but check your 'paid plan' first, if you are a trial user with the usage expired, the autogpt might not work.

Yes, I am a trial user, but the free quota has not expired. Do I need to set up a payment plan before I can use it?

**Comment by ntindle** [comment]
Try and use the #tech-support channel in discord for these issues. We don’t have the capacity to help debug in GitHub issues for problems like this
