### ISSUE TITLE
google_search command fails for some reason

### ISSUE THREAD

**Issue by Nickonomic** [Significant-Gravitas/Auto-GPT#1114]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

NEXT ACTION:  COMMAND = google_search ARGUMENTS = {'input': '***'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ***...
Input:y -10
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
SYSTEM:  Command google_search returned: Unknown command 'google_search'. Please refer to the 'COMMANDS' list for available commands and only respond in the specified JSON format.

### Current behavior 😯

Instead it suggests to use browser_search command

### Expected behavior 🤔

Using google_search

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by james431987** [comment]
Auto-GPT\scripts\data scripts.txt


1. Google Search: "google", args: "input": "<search>"
5. Browse Website: "browse_website", args: "url": "<url>", "question": "<what_you_want_to_find_on_website>"


use google not google_search

**Comment by Nickonomic** [comment]
> Auto-GPT\scripts\data scripts.txt
> 
> 1. Google Search: "google", args: "input": ""
> 2. Browse Website: "browse_website", args: "url": "", "question": "<what_you_want_to_find_on_website>"
> 
> use google not google_search
> 
> I think I've seen it come up with it's own commands before. Maybe it can't remember all of them so it tries to guess.

Yeah, you're right. Can we tell it to stick to a certain command through 'human input' tho?

**Comment by james431987** [comment]
idk if you can, but even if you can I think it would forget after a while. for case by case basis though you can correct it when it gets it wrong for example if it says it wants to do google_search you can type:

NEXT ACTION: COMMAND = google ARGUMENTS = {'input': 'whatever you wanted to search'}

**Comment by ntindle** [comment]
Sometimes it executes something unexpected or doesn’t do what you want.  Check out the #prompt-engineering channel in discord to get a better fit prompt
