### ISSUE TITLE
garbage suggestions

### ISSUE THREAD

**Issue by Passerby1011** [Significant-Gravitas/Auto-GPT#1123]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

1、Have you considered using New Bing as a search engine? Is its search effectiveness better than Google's or a combination of both?
2、Are there plans to support Chinese language?
3、Are there plans to consider using an accessToken approach to using the Chat-GPT solution? It is free and seems to provide better results than the API, although it may lead to a ban, it can be an option.

**Comment by kaqijiang** [comment]
试试这个 支持中文了
https://github.com/kaqijiang/Auto-GPT-ZH

**Comment by ntindle** [comment]
1. There are issues for it
2. There are issues for it
3. There are issues for it, and other LLMs
