### ISSUE TITLE
A solution to the inability to access the openai API. method openai. error. Timeout: Request timed out: HTTPSConnectionPool

### ISSUE THREAD

**Issue by HongJunShan** [Significant-Gravitas/Auto-GPT#1128]
打开安装的openai的库中的api_requestor.py
找到“if not hasattr(_thread_context, "session"):”方法，并在此方法上方加入代理
Example：
```
proxy={
            #'http':'127.0.0.1:10809',
            #'https':'127.0.0.1:10809',
            'socks5':'127.0.0.1:10808'
        }
```
在“result = _thread_context.session.request(”中加入代理
`proxies=proxy`

[![ppx5kTS.png](https://s1.ax1x.com/2023/04/13/ppx5kTS.png)](https://imgse.com/i/ppx5kTS)

**Comment by Jiangxuejian** [comment]
This solves my connection problem. Thanks!

**Comment by 888yyh** [comment]
需要开启vpn吗，还是报错了File "D:\SoftWare\Anaconda\envs\onnx_yolo\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

**Comment by 888yyh** [comment]
开了vpn还是报错的

**Comment by HongJunShan** [comment]
> 需要开启vpn吗，还是报错了File "D:\SoftWare\Anaconda\envs\onnx_yolo\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection sock.connect(sa) TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

如果是v2的话按照example里面的填就应该没问题，其他的话请检查下代理端口

**Comment by 888yyh** [comment]
> > 需要开启vpn吗，还是报错了File "D:\SoftWare\Anaconda\envs\onnx_yolo\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection sock.connect(sa) TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
> 
> 如果是v2的话按照example里面的填就应该没问题，其他的话请检查下代理端口

    raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))现在出现这个 怎么更新到v2呢

**Comment by HongJunShan** [comment]
> > > 需要开启vpn吗，还是报错了File "D:\SoftWare\Anaconda\envs\onnx_yolo\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection sock.connect(sa) TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
> > 
> > 
> > 如果是v2的话按照example里面的填就应该没问题，其他的话请检查下代理端口
> 
> ```
> raise error.APIConnectionError(
> ```
> 
> openai.error.APIConnectionError: Error communicating with OpenAI: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))现在出现这个 怎么更新到v2呢

ues v2rayN

**Comment by qyvlik** [comment]
#713

**Comment by ltw321** [comment]
> 

https://zhuanlan.zhihu.com/p/613833600

**Comment by JHWCoder** [comment]
我首先根据 @ltw321 的回答降低了urllib3的版本，然后又根据 @HongJunShan 的回答去添加了proxy，之后换了个代理，然后就ok了。

**Comment by zy0525** [comment]
降低urllib版本
pip install urllib3==1.25.11，我降完版本可以了

**Comment by MoohEuky** [comment]
> 降低urllib版本 pip install urllib3==1.25.11，我降完版本可以了

解决了！感恩太棒了

**Comment by ntindle** [comment]
Proxys are not well supported right now. Feel free to open a PR to add better proxy support

**Comment by Dawn-LX** [comment]
不改源代码，直接改环境变量
https://gist.github.com/dreamlu/cf7cbc0b8329ac145fa44342d6a1c01d?permalink_comment_id=3355537#gistcomment-3355537
