### ISSUE TITLE
Why PINECONE api key is listed in requirements when it uses local cache by default?

### ISSUE THREAD

**Issue by panlina** [Significant-Gravitas/Auto-GPT#1131]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Read README.

### Current behavior 😯

In `Requirements` section it lists `PINECONE API key`. However in `Setting Your Cache Type` section it says `By default Auto-GPT is going to use LocalCache instead of redis or Pinecone.`.

### Expected behavior 🤔

Confused if PINECONE API key is really a requirement. If it can run with local cache, it is NOT a requirement. Will be helpful for people to be clear about minimal requirements to run this project.

And as I tried, it still asks for PINECONE API key even I set `MEMORY_BACKEND=local`. Confused😕.

**Comment by sjnt1** [comment]
I honestly didn't notice that big a difference between localcache, pinecone and redis. Could only get it to execute python code after switching to redis, so if anything that should be a requirement, not pinecone. 

But yeah im a noob and i have been pondering the same question, why is pinecone a requirement?

**Comment by lc0rp** [comment]
Fixed.
