### ISSUE TITLE
Main.py ERROR when launching application 

### ISSUE THREAD

**Issue by JulsdL** [Significant-Gravitas/Auto-GPT#1134]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

In .env set TEMPERATURE to a float -> 0.2
Launch python scripts/main.py

### Current behavior 😯

Application crashes

![Auto-GPT temperature error](https://user-images.githubusercontent.com/64731066/231808326-f1cdab09-919b-432c-aef7-1b70ae494be5.jpg)

### Expected behavior 🤔

main.py should launch Auto-GPT in the terminal with this message:
Welcome to Auto-GPT!  Enter the name of your AI and its role below. Entering nothing will load defaults.
Name your AI:  For example, 'Entrepreneur-GPT'
AI Name:

RESOLUTION: 
In file config.py, line 47, replace
self.temperature = **int**(os.getenv("TEMPERATURE", "1"))
by
self.temperature = **float**(os.getenv("TEMPERATURE", "1"))

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by GrzegorzKarczewski** [comment]
it can only be 0, 1 or 2

**Comment by lc0rp** [comment]
Fixed
