### ISSUE TITLE
Auto-GPT excessively searches the web, even for information GPT already knows

### ISSUE THREAD

**Issue by rogeriosmorais** [Significant-Gravitas/Auto-GPT#114]
GPT already knows way too much stuff, there's no need to search the web for every little sub-task that comes up. For example, if you ask GPT what the rules for texas hold'em poker are, it knows and is able to detail it without any issues. When using Auto-GPT, instead of using this already known knowledge, Auto-GPT enters an infinite loop of searching the web and getting 404s and looking for more links, etc. All of that is unnecessary.

So, maybe you should ask GPT if the information is already known BEFORE making the decision to search the web?

**Comment by syntex01** [comment]
It can't know if it already knows something. Gpt4 should not be used as a knowledge source, because it can be wrong.

**Comment by TheWaler** [comment]
To build on @syntex01's point, GPT works best when we don't need to rely on it knowing things but just being able to understand things. It's mostly because we don't have a good understanding of how well is GPT's epistemological self-reflection (i.e. how well does it understand how well it knows something). So wherever possible, we want the agent to get its information from external sources and then be the glue between contextual knowledge and actions.
What we probably can and should do here is default more heavily (in a configurable way?) to locally storing knowledge and retrieving it instead of going out to the web - so we'll be able to reduce the number of external calls.

**Comment by stefangrotz** [comment]
Maybe an additional command: "draft from model knowledge" or something similar that can be enabled or disabled? It could be usefull in many use cases.

**Comment by st4s1k** [comment]
Basically you need some kind of caching mechanism.

**Comment by tatsu-i** [comment]
Is there any chance that these problems could be solved by modifying the PR below to allow it to read information from vectorized memory?
https://github.com/Torantulino/Auto-GPT/pull/122

**Comment by rogeriosmorais** [comment]
> To build on @syntex01's point, GPT works best when we don't need to rely on it knowing things but just being able to understand things. It's mostly because we don't have a good understanding of how well is GPT's epistemological self-reflection (i.e. how well does it understand how well it knows something). 

The same argument can be said about google searching. GPT doesn't have a good understanding on how reliable a website is. When the information you need isn't either new or complex, you are better off relying on GPT's own understanding than a shallow google search. Back to my example, a lot of searches ended up bringing up 404s or poker strategies, which are different from the game's actual set of rules. In the end is just a waste of time.

**Comment by st4s1k** [comment]
@rogeriosmorais how about limiting the search to a given set of websites? (wikipedia, reddit, stackoverflow, etc.)

**Comment by rogeriosmorais** [comment]
> @rogeriosmorais how about limiting the search to a given set of websites? (wikipedia, reddit, stackoverflow, etc.)

I tried to include that limitation as one of the 5 goals. "Get the poker game rules from wikipedia" or something like that. But it seems it was not treated as a hard rule, instead more like a light suggestion, so it ended up on other websites.

**Comment by st4s1k** [comment]
> > @rogeriosmorais how about limiting the search to a given set of websites? (wikipedia, reddit, stackoverflow, etc.)
> 
> I tried to include that limitation as one of the 5 goals. "Get the poker game rules from wikipedia" or something like that. But it seems it was not treated as a hard rule, instead more like a light suggestion, so it ended up on other websites.

I meant having a hardcoded website whitelist, or a `web_search_whitelist.txt`, or a config file, or something else, and filtering the websites that the bot can access.

https://developers.google.com/custom-search/v1/reference/rest/v1/cse/list#request

![image](https://user-images.githubusercontent.com/16061794/230090477-1cfdecf7-c4cd-47f3-bfca-e66c240cf73b.png)

**Comment by st4s1k** [comment]
> What is the goal here? GAI or a search bot that can provide references? If GPT knows the answer it shouldn't go off on Google searches.

How should it decide if it should search the web or not?
How does it know if the answer it knows is correct?
Maybe it should search the web only if the user asks?
Maybe it should search the web if the answer is "I don't know"?

**Comment by LuposX** [comment]
https://arxiv.org/abs/2207.05221 this goes in that direction.

**Comment by alreadydone** [comment]
> How should it decide if it should search the web or not?
How does it know if the answer it knows is correct?

The [Toolformer approach](https://www.shaped.ai/blog/breaking-down-toolformer) (the original paper includes two search engines):

> We only keep generated API calls if adding the API call and its result reduces the loss by at least t, compared to not doing any API call or obtaining no result from it.
We then want to fine-tune the model on a new dataset that contains our text with API calls.

**Comment by Pwuts** [comment]
Is this solved sufficiently with the long-term memory implementations we have now? (Pinecone, Redis, Milvus)

**Comment by Boostrix** [comment]
this still does happen, for instance it may repeatedly re-invoke lsb_release -a to query its environment, rather than recalling/caching previous invocations

**Comment by Pwuts** [comment]
We'll be addressing this issue in reworking the agent loop and the memory / retrieval system. For those who are interested, you can keep an eye on #3536
