### ISSUE TITLE
there is a bug in scripts/memory/base.py 

### ISSUE THREAD

**Issue by Bingordinary** [Significant-Gravitas/Auto-GPT#1154]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

if you run scripts/main.py, you will find out the "cfg" is undefined.
I have solved this bug by simply add "cfg = Config()" before get_ada_embedding function. I hope this is helpful for you.
The end, thank you for your job. This is an awsome project. Wish you all have a good day :D

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by jacobdineen** [comment]
addressed in #1156
