### ISSUE TITLE
SYSTEM:  Command message_agent returned: Error: invalid literal for int() with base 10: 'gpt_agent'

### ISSUE THREAD

**Issue by petersevera** [Significant-Gravitas/Auto-GPT#1167]
### Duplicates

- [X] I have searched the existing issues

### Your prompt 📝

```yaml
# Paste your prompt here
```
as

**Comment by estiens** [comment]
This is a new error and I get it frequently as well

**Comment by gh9st33** [comment]
I started getting this error when I switched to using redis

**Comment by Pwuts** [comment]
Closing as possibly resolved. Please reopen if not.
