### ISSUE TITLE
The AI's response was unreadable.

### ISSUE THREAD

**Issue by maminiainalaic** [Significant-Gravitas/Auto-GPT#117]
The AI's response was unreadable.
←[31mError:
 ←[0mTraceback (most recent call last): File "C:\Users\user\Desktop\Project\Auto-GPT\scripts\main.py", line 79, in print_assistant_thoughts assistant_thoughts_reasoning) UnboundLocalError: local variable 'assistant_thoughts_reasoning' referenced before assignment
Warning: Failed to parse AI output, attempting to fix.
 If you see this warning frequently, it's likely that your prompt is confusing the AI. Try changing it up slightly.
Failed to fix ai output, telling the AI.
←[36mNEXT ACTION:  ←[0mCOMMAND = ←[36mError:←[0m ARGUMENTS = ←[36mstring indices must be integers←[0m
Enter 'y' to authorise command or 'n' to exit program...
←[35mInput:←[0my
←[35m-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= ←[0m
←[33mSYSTEM:  ←[0mCommand Error: returned: Unknown command Error:
Warning: Failed to parse AI output, attempting to fix.
 If you see this warning frequently, it's likely that your prompt is confusing the AI. Try changing it up slightly.
Failed to fix ai output, telling the AI.
←[33mCAÏLBOT THOUGHTS: ←[0mThe AI's response was unreadable.
←[31mError:
 ←[0mTraceback (most recent call last): File "C:\Users\user\Desktop\Project\Auto-GPT\scripts\main.py", line 79, in print_assistant_thoughts assistant_thoughts_reasoning) UnboundLocalError: local variable 'assistant_thoughts_reasoning' referenced before assignment
Warning: Failed to parse AI output, attempting to fix.
 If you see this warning frequently, it's likely that your prompt is confusing the AI. Try changing it up slightly.
Failed to fix ai output, telling the AI.
←[36mNEXT ACTION:  ←[0mCOMMAND = ←[36mError:←[0m ARGUMENTS = ←[36mstring indices must be integers←[0m

**Comment by alomanto** [comment]
At least for me, I had this issue with both CMD and Powershell - I believe the problem is that the <--31 and other weird characters are color codes and those terminals can't display them properly. 

If you don't already have it installed, install the Windows Terminal and try running it there. Once I ran it in Windows Terminal (via the windows store), it apparently has the capability to display those colors correctly as it's working for me now.
