### ISSUE TITLE
auto-gpt.json

### ISSUE THREAD

**Issue by Shikamaru5** [Significant-Gravitas/Auto-GPT#1174]
There's probably an issue that was either closed or is currently open about this but when I run it, it automatically gives me this error:

      Warning: The file 'auto-gpt.json' does not exist. Local memory would not be saved to a file.                                                                                      
      Using memory of type: LocalCache                                                                                                                                                  
      Error:  API Rate Limit Reached. Waiting 10 seconds...

Don't really know what it's on about since I haven't used any of my credits for the month thus far, unless it believes that the tasks I'm giving it will go over the limit of what I have?? Any help would be super wizard.

**Comment by YoloerGuy** [comment]
I'm having the same issue and using the debug python scripts/main.py --debug it shows that i still have 4000 tokens, so I don't think this is API related, I could be wrong. :(

**Comment by seanmorgan7615** [comment]
I need to verify once I get back home, but a couple hours ago I believe I fixed this just by creating a file called auto-gpt.json in the root directory.

**Comment by AcroTiger** [comment]
You can create an empty file called auto-gpt.json. The system will use this file as storage.

**Comment by quatronostro** [comment]
> You can create an empty file called auto-gpt.json. The system will use this file as storage.

tried that it doesnt work :(

**Comment by Slowly-Grokking** [comment]
that works for me

**Comment by k-jiang** [comment]
Creating a file called auto-gpt.json with this content works for me:
```
{}
```

**Comment by JuroOravec** [comment]
Duplicate of https://github.com/Torantulino/Auto-GPT/issues/1189. @Shikamaru5 would you close this one issue if it indeed is the same thing?

(And me too - It's probably that we've entered API KEY for wrong kind of account - we need paid openAI account (not ChatGPT pro). The `auto-gpt.json` is a red herring - it's a last messag we see, but it's unrelated to the API limit reached. the script can work without the `auto-gpt.json`)

**Comment by Shikamaru5** [comment]
Ya sorry I didn't have time yesterday to come back and comment on this thread, it works when you create an auto-gpt.json and put it in the scripts directory. I ended up using a paid account to make it work, it's actually not as impressive as people have been talking about, not really worth the money imo.
