### ISSUE TITLE
Resuming and recording agents

### ISSUE THREAD

**Issue by r3ifi3r** [Significant-Gravitas/Auto-GPT#1176]
We should build flags and add support for multiple types of persistence layers.  i.e. —persist or —resume or —record and support for multiple databases or file storage or in memory. We need a way to gracefully resume and record agents and offer adaptive ways of doing so. Different types of persistence layers can be used for backup when it’s critical to record an agent.

_Originally posted by @r3ifi3r in https://github.com/Torantulino/Auto-GPT/discussions/724#discussioncomment-5608507_

**Comment by Pwuts** [comment]
Related to #822

**Comment by Pwuts** [comment]
Closing as a duplicate of #822
