### ISSUE TITLE
Issue w .env or config.py not recognizing OPENAI API Key -- os x 12.4

### ISSUE THREAD

**Issue by s3android** [Significant-Gravitas/Auto-GPT#1188]
**Duplicates**

 _I have searched the existing issues_

**Steps to reproduce 🕹**

_Followed installation instructions and suggestions via issue threads_

**Current behavior 😯**

_Please set your OpenAI API key in config.py or as an environment variable.
You can get your key from https://beta.openai.com/account/api-keys_

_(current fixes didn't work for me on mac)_

_I have updated my .env file and confirmed (screen shot)  
My pinecone, openai, google, etc apis info has been input_
  

Same problem as  @jennyqueenofswords although I am unable to resolve following the provided suggestions.  

- Followed the current instructions and suggestions to rename using terminal/IDE in multiple versions of Python 3.11, 3.10.11, 3.10.10 (currently) 
- Deleted and recloned each time
- Tried multiple OPENAI API KEYS 

            

<img width="502" alt="OPENAI API ISSUE" src="https://user-images.githubusercontent.com/130613649/231890925-8dfde7f9-b588-4256-8c46-d53cdc8b2fc2.png">
<img width="1247" alt="ENV details " src="https://user-images.githubusercontent.com/130613649/231890933-b6735723-f80b-4253-a2e2-3b785053065e.png">

**Comment by oliverklsov** [comment]
I'm having the exact same issue, API keys are correct

**Comment by mirrorshades** [comment]
Did you try copying the .env file directly within finder? Try this instead. `cp .env.example .env` and that did it for me.

**Comment by DrReefer** [comment]
Hello, I have having the same problem, when I edit .env.template I add my openai api and then when I rename it and save, it saves as .txt file

**Comment by swcrazyfan** [comment]
I had a problem where the file wasn't actually being renamed. Despite appearing to be called ".env" it didn't change the name from ".env.template". Once I fix this, it worked.

**Comment by jennyqueenofswords** [comment]
I got it to work by deleting the repo, re-cloning it and doing mv .env.template .env

you can't fiddle with the file name in the finder or it will mess it up.

**Comment by DrReefer** [comment]
> I had a problem where the file wasn't actually being renamed. Despite appearing to be called ".env" it didn't change the name from ".env.template". Once I fix this, it worked.

I noticed that when I changed the name, it still saved .env.template and made a .env text file, did you just delete .env.template?

**Comment by DrReefer** [comment]
![env](https://user-images.githubusercontent.com/20601270/231923475-66d12c11-5658-450a-abfa-3dccc9a256d3.jpg)
which one should I use and just delete the other?

**Comment by jurgis-printify** [comment]
> cp .env.example .env

I did this "cp .env.template .env " in terminal and it helped resolved the issue on MacOS

**Comment by suiningxys** [comment]
Delete “.template” from ".env.template" and it works.

**Comment by s3android** [comment]
> I got it to work by deleting the repo, re-cloning it and doing mv .env.template .env
> 
> you can't fiddle with the file name in the finder or it will mess it up.

Tried this --- deleted and re-cloned several times, all while trying different Python versions, rolling back to 3.10.10. Cloned directly to the directory I wanted -- did not use finder to move or rename. Only used finder to provide screen shot below 

Also tried modifying the .env.template via terminal (mv .env.template .env) and thru IDE - Visual Studio, IDLE. Screen shot shows .env is a file not template. 

<img width="769" alt="ENV finder" src="https://user-images.githubusercontent.com/130613649/232047013-c05fb836-9f02-4092-8372-ae5085f668a5.png">

**Comment by Scamdo** [comment]
> 

how did you fix it?

**Comment by Scamdo** [comment]
found my fix!!! - just put this into the cmd: rename .env.template .env
then run again and it works

**Comment by fmnighwell** [comment]
> found my fix!!! - just put this into the cmd: rename .env.template .env then run again and it works

WORKED! Thank you. Context: The file was appearing as .env without .template. For some reason using this fixed it.
