### ISSUE TITLE
RuntimeError: Failed to get response after 5 retries

### ISSUE THREAD

**Issue by luckyvictor** [Significant-Gravitas/Auto-GPT#1189]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

I am on Mac.

No problem with the installation process, very smooth. I followed the instructions and input my openai api key as well as pinecone api key and region code.

I managed to start the agent and gone as far as entering the 5 goals.

It gave me a warning of no auto-gpt.json, believe it is not a big deal.

However after a minute of waiting, it reports

RuntimeError: Failed to get response after 5 retries

what is it and why do I get it?

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by That-Guy-01** [comment]
run python scripts/main.py --debug and check the results

**Comment by GOASIWISH** [comment]
+1 I followed the same instructions from this YouTube (https://www.youtube.com/watch?v=7On7vRBGz78 ) but kept seeing this error- RuntimeError: Failed to get response after 5 retries

**Comment by ahirane** [comment]
> run python scripts/main.py --debug and check the results

  ----------- END OF CONTEXT ----------------
Error:  API Rate Limit Reached. Waiting 20 seconds...
Error:  API Rate Limit Reached. Waiting 20 seconds...
Error:  API Rate Limit Reached. Waiting 20 seconds...
Error:  API Rate Limit Reached. Waiting 20 seconds...
Error:  API Rate Limit Reached. Waiting 20 seconds...
Traceback (most recent call last):
  File "scripts/main.py", line 461, in <module>
    main()
  File "scripts/main.py", line 365, in main
    assistant_reply = chat.chat_with_ai(
  File "C:\Users\mappe\Desktop\Auto-GPT\scripts\chat.py", line 126, in chat_with_ai
    assistant_reply = create_chat_completion(
  File "C:\Users\mappe\Desktop\Auto-GPT\scripts\llm_utils.py", line 50, in create_chat_completion
    raise RuntimeError("Failed to get response after 5 retries")
RuntimeError: Failed to get response after 5 retries

**Comment by dandaka** [comment]
You need a paid account in OpenAI, fixed for me

**Comment by 0xBYTESHIFT** [comment]
I have a paid account. And I still get the same errors as people above

**Comment by dandaka** [comment]
There is a paid ChatGPT and there is a paid OpenAI API account. You need to have the second one.

**Comment by 0xBYTESHIFT** [comment]
I know, I have both of them :(

**Comment by Onnture** [comment]
Is it $5 a month?

**Comment by That-Guy-01** [comment]
If you have a paid open-ai account (not ChatGPT pro) then you’ll need to check things like your monthly token limit or your payment method on open-ai’s site.  Confirm you have available tokens.

**Comment by BlueJ-D** [comment]
> I know, I have both of them :(

Have you checked that the account has a credit / debit card added and that you havent got any limits set in your open ai playground account. You may have set a limit?

Also if you use a google account to login, i've seen comments saying this could cause a limit issue.

**Comment by BlueJ-D** [comment]
> says its $5 a month depending on usage, I understand that Auto-GPT requires a lot of that usage, is it expensive to use then?

if you use gpt4 it can get very costly yes

**Comment by tycryptty** [comment]
Same issue, I have a paid OpenAI API acc but still got the issue.

**Comment by JuroOravec** [comment]
Made a PR https://github.com/Torantulino/Auto-GPT/pull/1304 to make it clear in the README that one has to opt in to the OpenAI's paid account (and add billing info) for the OpenAI's API key to work, which seems to be a common cause for the `API Rate Limit Reached. Waiting 20 seconds` error

**Comment by vvkv** [comment]
Thank you for making the PR - however, I've had the  OpenAI paid account (with $120 usage limit) and still continue to get the same error. I have also tried to generate a new API key twice now - same issue.
.env file has been updated with the openapi key in double quotes as mentioned in the readme.

**Comment by shiuido** [comment]
Why has this happened? Yesterday I ran auto-gpt just fine without a paid account.

**Comment by lokeshaudits** [comment]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Windows\System32\Auto-GPT\autogpt\__main__.py", line 572, in <module>
    main()
  File "C:\Windows\System32\Auto-GPT\autogpt\__main__.py", line 396, in main
    agent.start_interaction_loop()
  File "C:\Windows\System32\Auto-GPT\autogpt\__main__.py", line 448, in start_interaction_loop
    assistant_reply = chat.chat_with_ai(
                      ^^^^^^^^^^^^^^^^^^
  File "C:\Windows\System32\Auto-GPT\autogpt\chat.py", line 159, in chat_with_ai
    assistant_reply = create_chat_completion(
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Windows\System32\Auto-GPT\autogpt\llm_utils.py", line 67, in create_chat_completion
    raise RuntimeError("Failed to get response after 5 retries")
RuntimeError: Failed to get response after 5 retries



The above is the Runtime error I receive. What is the solution?

**Comment by p-i-** [comment]
There's an issue of one OpenAI API key in the shell environment and a second one in the .env file, and the code is using the first one.

We should print the first few characters of the license key to console to avoid this.

**Comment by anonhostpi** [comment]
I've added _all_ of the linked issues to my rate-limit issue tracker to make them easier to track: [Gist][gist] | [Alt][source]

[gist]:https://gist.github.com/anonhostpi/97d4bb3e9535c92b8173fae704b76264#file-_topics-0005-api-0002-access-rate-limits-md
[source]:https://github.com/anonhostpi/AUTOGPT.TRACKERS/blob/main/TOPICS/0005.API/0002.ACCESS/RATE-LIMITS.md
