### ISSUE TITLE
Python terminal execution MacOS not working

### ISSUE THREAD

**Issue by FagerCrypto** [Significant-Gravitas/Auto-GPT#1195]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Hello guys,

I got following issue:

When I'm trying to run the code "python scripts/main.py" in the terminal I always get an error as you can see in the picture. 
My Mac has the latest version of python and all the requirements in the instructions sheet are as well installed.

I'd be really happy if anyone could help in order to fix this problem.
Thanks for your time .
<img width="567" alt="Bildschirm­foto 2023-04-13 um 23 26 10" src="https://user-images.githubusercontent.com/130693358/231887425-2852910d-9507-4466-bc56-3b01a5876063.png">
hanks for your time .

**Comment by MIrslinger** [comment]
> It works when I do this: python3 scripts/main.py

Not for me.

**Comment by ntindle** [comment]
Try and use the #tech-support channel in discord for these issues. We don’t have the capacity to help debug in GitHub issues for problems like this
