### ISSUE TITLE
Download fails

### ISSUE THREAD

**Issue by WKimandu** [Significant-Gravitas/Auto-GPT#1200]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

: HTTPConnectionPool(host='127.0.0.1', port=6333): Max retries exceeded with url:
I need to ensure that the download was successful and that the whitepaper is not corrupted.
NEXT ACTION:  COMMAND = evaluate_code ARGUMENTS = AttributedDict([('code', "import requests\n\nurl = 'https://www.cisco.com/c/en/us/solutions/collateral/data-center-virtualization/application-centric-infrastructure/white-paper-c11-739989.pdf'\nresponse
 = requests.get(url)\n\nif response.status_code == 200:\n # write the content to a file\n with open('Endpoint Operations in Cisco ACI Fabric.pdf', 'wb') as f:\n f.write(response.content)\n print('Whitepaper downloaded successfully')\nelse:\n print('Error: Unable to download whitepaper')")])

### Current behavior 😯

It was able to download other files 

### Expected behavior 🤔

successful download

### Your prompt 📝

```yaml
# Paste your prompt here
```
ai_goals:
- You are an AI writer and researcher, you want to write and publish book that you can sell on amozon

**Comment by Pwuts** [comment]
Please include your log and reopen if the problem is still relevant.
