### ISSUE TITLE
Pas le même fichier

### ISSUE THREAD

**Issue by Anthony-qnn** [Significant-Gravitas/Auto-GPT#1206]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

I don't have the same file when I download it. Where is .env.template ? I have only this files : azure.yaml.template 
CONTRIBUTING.md 
docker-compose.yml 
Dockerfile 
Licence 
main.py 
sorties 
README.md 
requirements.txt 
Scénarios 
Tests tests.py

### Your prompt 📝

```yaml
# 
```

**Comment by Pwuts** [comment]
Please download the latest version [here](https://github.com/Significant-Gravitas/Auto-GPT/releases/latest) and try again
