### ISSUE TITLE
Fix looking for files that aren't there

### ISSUE THREAD

**Issue by estiens** [Significant-Gravitas/Auto-GPT#1209]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

this isn't an easily reproducible issue or a bug perse, just a current limitation that seems ripe for addressing since an index of files created is not a hard one to create

### Current behavior 😯

One of Auto-GPTs most endearing but frustrating features is that it often tries to access files that it thinks it should have created already, sometimes even getting stuck in a loop looking for the file, or creating a file with placeholder text and then being like, wait that file isn't what I need.

It seems like we should be able to modify this logic pretty easily by keeping track of any files that autogpt has created and if it is trying to access a file that isn't there, prod it to create that file first with the information it is seeking. Worthwhile impulse to think that file should exist and has what it needs, just need to prod it to focus on writing the file and not reading it.

### Expected behavior 🤔

autogpt should not keep looking for files it hasn't created. It it accesses a file that it has created that doesn't have the info it needs, it should focus on writing to that file instead of reading it, as that means it needs more information

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by jrwtank** [comment]
yes it's quite endearing.  Happens for me all the time.   i love watching it look for files it hasn't even created, then realize there is no such file, "forget" what the file is or why it should create it, then put some nonsense in the file it should've created long ago, then read the file containing mostly nonsense or placeholder text, and basically lose all its progress.  

Overall, autoGPT is not writing to files nearly as frequently as it should.  Every time it makes some progress, it should at least record its results in a saved file.  Then of course keep a record of which files it saved and for what purpose...

**Comment by claytondukes** [comment]
#1208

**Comment by claytondukes** [comment]
I just started a new session and added:

```
ai_goals:
  - Do not create files with placeholder text, create them when you have actual data to put in them
  - keep track of any files that you have created. If you try to access a file that you think you created but it isn't there, create it. If you are still unable to create the file after 2 tries, log an error and discontinue your tasks.
```

I'll let you know if it helps

**Comment by mencelot** [comment]
> I just started a new session and added:
> 
> ```
> ai_goals:
>   - Do not create files with placeholder text, create them when you have actual data to put in them
>   - keep track of any files that you have created. If you try to access a file that you think you created but it isn't there, create it. If you are still unable to create the file after 2 tries, log an error and discontinue your tasks.
> ```
> 
> I'll let you know if it helps

I’m going to try this too

**Comment by claytondukes** [comment]
> I'll let you know if it helps

It did work.

**Comment by ntindle** [comment]
Sometimes it executes something unexpected or doesn’t do what you want.  Check out the #prompt-engineering channel in discord to get a better fit prompt
