### ISSUE TITLE
Consider providing API?

### ISSUE THREAD

**Issue by panlina** [Significant-Gravitas/Auto-GPT#1222]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Is it in consideration to provide an API?

### Motivation 🔦

So that people can create applications using auto-gpt.

**Comment by Pwuts** [comment]
Yes, work in progress #757

**Comment by Androbin** [comment]
@Pwuts I think this issue is about a frontend extension calling into AutoGPT via an API, not about AutoGPT calling into a backend extension.

**Comment by Pwuts** [comment]
#2458 then :)
