### ISSUE TITLE
openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002AA2E1A7DC0>: Failed to establish a new connection: [WinError 10060]

### ISSUE THREAD

**Issue by 888yyh** [Significant-Gravitas/Auto-GPT#1226]
### Duplicates

- [X] I have searched the existing issues

### Your prompt 📝

```yaml
# Paste your prompt here
```
openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002AA2E1A7DC0>: Failed to establish a new connection: [WinError 10060]
how to fix this issue, thanks

**Comment by HongJunShan** [comment]
#1128

**Comment by chenzx2** [comment]
This is the result of being restricted by openai,yuor network is not right

**Comment by 888yyh** [comment]
i have solved this issue by using another vpn

**Comment by hanxx862** [comment]
I am not using any vpn but there is same error. I follow the issue 1128

**Comment by lxxxxxxxxlx** [comment]
I have tried switching nodes in the VPN, enabling global proxies, and using other VPNs, but none of them have solved this problem. Do you have any recommendations? Or is there any solution?

**Comment by zy0525** [comment]
降低urllib版本，pip install urllib3==1.25.11，我降完版本可以了

**Comment by ntindle** [comment]
If you are using one, Proxys are not well supported right now. Feel free to open a PR to add better proxy support 


If not, you’ve been blocked from connecting to open ai. Try and use the #tech-support channel in discord for these issues. We don’t have the capacity to help debug in GitHub issues for problems like this

**Comment by glaucocustodio** [comment]
I had the same issue trying to intercept requests with [HTTP Toolkit](https://httptoolkit.com/), must be the proxy it uses under the hood..
