### ISSUE TITLE
Interrupt continuous + interactivity

### ISSUE THREAD

**Issue by DamascusGit** [Significant-Gravitas/Auto-GPT#123]
Can we add interactivity, like interruption of continuous mode for user inputs by pressing a certain key? The set of tools this project provides is super useful, and some human feedback would be great to implement as an option.

**Comment by leoodz** [comment]
Right now you can press ctrl + c to stop it

**Comment by DamascusGit** [comment]
what i meant was, the ability to interrupt temporarily so that i can add a new directive as it runs/rectify a thought/etc

**Comment by slavakurilyak** [comment]
@DamascusGit see issue https://github.com/Torantulino/Auto-GPT/issues/13

**Comment by Pwuts** [comment]
Superseded by #1472
