### ISSUE TITLE
Would it be possible to choose not to clear auto-gpt.json file when running cmd window?

### ISSUE THREAD

**Issue by 578234** [Significant-Gravitas/Auto-GPT#1246]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

hi everyone.

I'm using autogpt very happily.

But when I restart cmd window, auto-gpt.json get cleared and start from 0 again.

I think data at auto-gpt.json is like prior experience and I want to let it study on top of the prior file.

Is there would be the way to make option which doesn't clear auto-gpt.json file and use existing one?

Thank you very much.

### Examples 🌈

I'm not familiar with codes so I couldn't fix the issue. It would be so much helpful and grateful when I can study on top of prior auto-gpt.json file local.

### Motivation 🔦

.

**Comment by miaowmint** [comment]
I think this is an important issue. When I accidentally exit the command line, all of my previous chat records are lost and I have to start over again.

**Comment by 578234** [comment]
I asked gpt4 and they said

main.py

before:
def reset():
    open("auto-gpt.json", "w").close()

after:
import os

def reset():
    if os.path.exists("auto-gpt.json"):
        return
    open("auto-gpt.json", "w").close()

I'll try it later
