### ISSUE TITLE
long-term memory?

### ISSUE THREAD

**Issue by DamascusGit** [Significant-Gravitas/Auto-GPT#125]
where is the long-term memory stored? i can't seem to find it in the repo after it claims to commit information to long term memory, and don't really have any evidence it's actually being saved anywhere.

i'd like the agent to pick up where it left off, given the same previous settings, or at least maintain the info it committed to memory.

**Comment by EricFedrowisch** [comment]
Yeah, the persistent memory was more of stub code. I put in a pull request to add persistent memory in a sqlite3 database. 
https://github.com/Torantulino/Auto-GPT/pull/124

**Comment by DamascusGit** [comment]
using your PR has been great so far. ty

**Comment by amauryfischer** [comment]
Same !

**Comment by dschonholtz** [comment]
I have a pinecone PR to handle this with pinecone so you can look up relevant memories. 
Please see Pull #122 https://github.com/Torantulino/Auto-GPT/pull/122

**Comment by Pwuts** [comment]
Closing as completed
