### ISSUE TITLE
[Meta] Use Squash and Merge for a clean commit history

### ISSUE THREAD

**Issue by EwoutH** [Significant-Gravitas/Auto-GPT#1255]
Thanks for all this amazing work!

Would you consider using [Squash and merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits) method for merging PRs instead of the "Create a merge commit" method? That will result in a way cleaner, and linear git log, since for each PR not multiple commits (including a merge commit) are included but only a single one.

<img width="290" alt="Screenshot_847" src="https://user-images.githubusercontent.com/15776622/231887785-58942845-87a3-43c3-b12b-772a707a80c4.png">

**Comment by EwoutH** [comment]
@richbeales and @p-i- thanks for your hard work! Could you consider this way of merging for a cleaner commit history?

**Comment by EwoutH** [comment]
@richbeales It doesn't has to look like this! Try Squash and Merge :)

![Screenshot_107](https://user-images.githubusercontent.com/15776622/232234803-b648088c-5a6a-49e1-8a5d-c19aa3190710.png)

**Comment by ntindle** [comment]
Good idea!
