### ISSUE TITLE
Main.py fail into Docker for permissions

### ISSUE THREAD

**Issue by sansr** [Significant-Gravitas/Auto-GPT#1274]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

docker build -t autogpt:0.1.0 .
docker run -it --env-file .env autogpt:0.1.0

### Current behavior 😯

![image (1)](https://user-images.githubusercontent.com/1028398/231982116-f922a84c-8952-4e70-a0b7-71e58ebf8b91.png)

### Expected behavior 🤔

![image (3)](https://user-images.githubusercontent.com/1028398/231982594-2bf73725-e748-4288-9f88-3b0f6e89da14.png)

**Comment by ntindle** [comment]
Fixed?
