### ISSUE TITLE
 Warning: Failed to parse AI output, attempting to fix.  If you see this warning frequently, it's likely that your prompt is confusing the AI. Try changing it up slightly.

### ISSUE THREAD

**Issue by ifoundamachine** [Significant-Gravitas/Auto-GPT#1282]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Just add any human feedback into the loop. It happens 100% of the times.

### Current behavior 😯

This error is shown every time i put in human feedback, and continues to show up in all further replies, even though the agent seems to be working correctly anyway. I found one issue in the repo that had a similar thing but it was connected to JSON outputs. In my case, it happens always, and the JSON problem might be something different.

### Expected behavior 🤔

I don't know what's causing this error to pop up, but I'd like it to go away ;)

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by JoeKanaan0** [comment]
I think you're only supposed to add human feedback when autoGPT has a question. It worked for me when I did that, but if I try to give human feedback without it asking a question I get this error

**Comment by MeDott29** [comment]
Traceback (most recent call last): File "/mnt/c/Users/username/OneDrive/Documents/GitHub/Auto-GPT/scripts/main.py", line 76, in print_assistant_thoughts assistant_reply_json = fix_and_parse_json(assistant_reply) File "/mnt/c/Users/username/OneDrive/Documents/GitHub/Auto-GPT/scripts/json_parser.py", line 51, in fix_and_parse_json brace_index = json_str.index("{") ValueError: substring not found

**Comment by Pwuts** [comment]
Closing as one of many duplicates; superseded by #1407
