### ISSUE TITLE
google api not valid error returning

### ISSUE THREAD

**Issue by autoswifty** [Significant-Gravitas/Auto-GPT#1290]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Help ID cause ? .env entries

![goog](https://user-images.githubusercontent.com/130719775/232011416-9e50fd02-9b84-4b18-9cbb-a75fbc321d2d.png)

### Current behavior 😯

limited successful searches. Lots of google API troubleshooting by agent and cycle repeats

### Expected behavior 🤔

basic search

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by nicostubi** [comment]
Yes, I noticed the same problem.

Two concepts are mixed here :

1) problem solved by the autonomous agent
2) project configuration problem

I guess the original goal was not having the agent trying to solve the Google API Key issue by itself. 
The problem should probably be detected during the startup of the agent, with a message similar to "The google API key is not valid. Please fix the Google API key in the .env file before launching the agent".

This process would probably require to launch a first "Google test query" before prompting the user for any question like AI name, role and goals. So I'm not sure this is how the system has been designed.

Anyway, this could be solved by a proper error handling, apparently needed at the project level.

Exact description of the problem :

- [ ] 1. Command google returns: _Error <HttpError400..._
- [ ] 2. The agent thinks it can solve this, with the message 

![image](https://user-images.githubusercontent.com/47106274/232026693-8839eacd-fa67-428d-96b1-73855e5bbf10.png)

- [ ] 3. I did input _I entered the key_ (a wrong one, for the sake of the exercise :-) )
- [ ] 4. Command google returns: _Error <HttpError400..._ again

The sentence N_ow that I have a valid Google API Key, I can proceed [...]_ is a wrong assumption made by the agent.

![image](https://user-images.githubusercontent.com/47106274/232026261-2ffd0f74-ce48-430e-a0ee-c79f586fcd9b.png)

BR
Nicolas

**Comment by Vooooooodga** [comment]
I met the same issue. By checking the code in "./scripts/commands.py", I found:

![image](https://user-images.githubusercontent.com/57168144/232060763-1b710434-4627-4af0-9008-a93b1bb6e0aa.png)


  According to the notes, the default Google API key should be "" for using "google_search" instead of "google_official_search". So just change it in the ".env" file:

GOOGLE_API_KEY=
CUSTOM_SEARCH_ENGINE_ID=

Then it worked, I hope it could solve your issue too.

**Comment by ChessScholar** [comment]
If you did everything that was in the readme.md, the use this link to find your custom engine and its ID (this wasn't intuitive to find):

https://programmablesearchengine.google.com/controlpanel/all

**Comment by autoswifty** [comment]
.env setup as per readme and above. issue unresolved.

**Comment by selimyaman** [comment]
> I met the same issue. By checking the code in "./scripts/commands.py", I found:
> 
> ![image](https://user-images.githubusercontent.com/57168144/232060763-1b710434-4627-4af0-9008-a93b1bb6e0aa.png)
> 
> According to the notes, the default Google API key should be "" for using "google_search" instead of "google_official_search". So just change it in the ".env" file:
> 
> GOOGLE_API_KEY= CUSTOM_SEARCH_ENGINE_ID=
> 
> Then it worked, I hope it could solve your issue too.

In that case, `google_official_search` option is not a valid option since it's already the default way of searching through Google, unlike what the `readme` file says?

**Comment by ntindle** [comment]
Try and use the #tech-support channel in discord for these issues. We don’t have the capacity to help debug in GitHub issues for problems like this
