### ISSUE TITLE
Add accessToken mode to solve the problem of temporarily missing GPT4 API

### ISSUE THREAD

**Issue by MineSunshineone** [Significant-Gravitas/Auto-GPT#1305]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

I am completely a programming novice, I just saw this project and considering the application speed of the API, so I have this idea

### Examples 🌈

https://github.com/Chanzhaoyu/chatgpt-web#%E4%BB%8B%E7%BB%8D

### Motivation 🔦

Since the current GPT4 API application is not so easy and fast, we can quickly use it by subscribing to Plus and obtaining AccessToken

**Comment by ryan-zheng-teki** [comment]
Does this have legal issues?

**Comment by ntindle** [comment]
Won’t fix
