### ISSUE TITLE
API NOT WORKING PLEASE HELP

### ISSUE THREAD

**Issue by jmanhype** [Significant-Gravitas/Auto-GPT#134]

**Comment by Torantulino** [comment]
Hey @jmanhype 

> "openai.error.AuthenticationError: Incorrect API key provided"

- [ ] Have you double checked your OpenAI key is correct?

I think what else the problem could be

**Comment by jmanhype** [comment]
thank you for the quick respone yes I have checked it many times. It is finding a different api key Incorrect API key provided: <sk-JW3R*****************************************Caq>. You can find your API key at https://platform.openai.com/account/api-keys.  

this is what the .env file says

**Comment by jmanhype** [comment]
I omiiteed part of it to hide the api key but you see its finding they key somewhere else not in the .env file.

i tried to set the key using setx also i did a echo call to see if it accepted it does but still spits out same error then I tried to create myenv and activate it install depencices still same error. HELPPP

**Comment by jmanhype** [comment]
> Hey @jmanhype
> 
> > "openai.error.AuthenticationError: Incorrect API key provided"
> 
> * [ ]  Have you double checked your OpenAI key is correct?
> 
> I think what else the problem could be

openai.error.AuthenticationError: Incorrect API key provided: <sk-JW3R*****************************************Caq>. You can find your API key at https://platform.openai.com/account/api-keys.
PS C:\Users\strau\Downloads\Auto-GPT> python gs.py
PS C:\Users\strau\Downloads\Auto-GPT> python gs.py
API key found: sk-RHN*****************************************MNz
PS C:\Users\strau\Downloads\Auto-GPT> python scripts/main.py
Welcome back!  Would you like me to return to being good guy?
Continue with the last settings?
Name:  good guy
Role:  a good huy
Goals: ['Increase net worth', 'Grow Twitter Account', 'Develop and manage multiple businesses autonomously']
Continue (y/n): y
Traceback (most recent call last):
  File "C:\Users\strau\Downloads\Auto-GPT\scripts\main.py", line 279, in <module>
    assistant_reply = chat.chat_with_ai(
                      ^^^^^^^^^^^^^^^^^^
  File "C:\Users\strau\Downloads\Auto-GPT\scripts\chat.py", line 110, in chat_with_ai
    assistant_reply = create_chat_completion(
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\strau\Downloads\Auto-GPT\scripts\llm_utils.py", line 9, in create_chat_completion
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "C:\Python311\Lib\site-packages\openai\api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: Incorrect API key provided: <sk-JW3R*****************************************Caq>. You can find your API key at https://platform.openai.com/account/api-keys.
PS C:\Users\strau\Downloads\Auto-GPT>

**Comment by jmanhype** [comment]
so ass you see I set the api then i call it to make sure its set then i run the python script it still is not working no matter what something is wrong with your code. something you updated if it was working beforehand help please

**Comment by jmanhype** [comment]
so strange I just did a new instance on my laptop and its working fine without a hitch

**Comment by gillmohnish** [comment]
> thank you for the quick respone yes I have checked it many times. It is finding a different api key Incorrect API key provided: <sk-JW3R*****************************************Caq>. You can find your API key at https://platform.openai.com/account/api-keys.
> 
> this is what the .env file says
> 
> OPENAI_API_KEY='sk-RHN3tSsJh bnHNregvGQMpMNz' ELEVENLABS_API_KEY="a75c0d 8c43feec184" SMART_LLM_MODEL="gpt-4" FAST_LLM_MODEL="gpt-3.5-turbo" GOOGLE_API_KEY= CUSTOM_SEARCH_ENGINE_ID=

It seems that the OPENAI_API_KEY value in your .env file is not formatted correctly, as it contains an extra space character in the middle of the key. you can try this
OPENAI_API_KEY='sk-RHN3tSsJhbnHNregvGQMpMNz'

**Comment by amauryfischer** [comment]
you shouldn't share your api-key ! do not forget to delete it from openai and generate a new one as malicious people could use it

**Comment by beast1xy** [comment]
for me, the solution was to name the .env.template file to just .env

so i just remove the .template from the filename.

and i wrote the thing with the api key like that:
OPENAI_API_KEY=sk-1ykb......EKTL

now it works for me

**Comment by xtions66** [comment]
I have created my Google API key, made sure everything was entered, spent nearly 2 hours on it last night, and AutoGPT just rejects it as a bad API key.

At the end of my rope here.
I would love to use this tool, but can't get past this.
Any help would be appreciated.

Command google returned: Error: <HttpError 400 when requesting https://customsearch.googleapis.com/customsearch/v1?q=popular+items+to+sell+on+Etsy&cx=a289ff8cd1de54583&num=8&key=no&alt=json returned "API key not valid. Please pass a valid API key.". Details: "[{'message': 'API key not valid. Please pass a valid API key.', 'domain': 'global', 'reason': 'badRequest'}]">

**Comment by DukeChapnick** [comment]
I had the same issue on my Mac. Here is how I fixed it:
My system was automatically hiding the .env-file. I created a new .env-file with "nano .env" copied the content of the template an inserted my openAI-API-key

**Comment by Holpa** [comment]
Hello Everyone, 

I have found out if changing the KEY name in file config.py , and .env file the application can pull the GOOGLE_API_KEY properly


Line 65 in config.py: see I added 2 in the end

self.google_api_key = os.getenv("GOOGLE_API_KEY2")

Line 94 in .env:

GOOGLE_API_KEY2


now it is working

**Comment by HancoRabie** [comment]
![image](https://user-images.githubusercontent.com/35245747/231928794-d8f2cba8-8a21-49d9-919a-38dd4a435813.png)

It's broken for me, unfortunately.

I've entered the API correctly. I'm on windows.

The .env file is not incorrectly named. My API keys are valid.

**Comment by mvb11** [comment]
It's also broken for me. Doesn't matter if I change it in the .env file or config file itself. Get same error message but Key is correct.

**Comment by Al-Qudo** [comment]
Same here.

**Comment by rileycevans** [comment]
Same

**Comment by Vanomis** [comment]
Same problem here. I used VSCode and realized that the .env I renamed from the textEdit (MacOS) was still named .env.template for some reason ... Like if remaming it from textEdit didn't save the change. 
I renamed it from VSCode and it worked...

**Comment by VedalYT** [comment]
> Hello Everyone,
> 
> Do I have found out if changing the KEY name in file config.py , and .env file the application can pull the GOOGLE_API_KEY properly
> 
> OR check your OS environment variables, check your windows variables and delete GOOGLE_API_KEY, then reboot your pc
> 
> now it is working

Thank you so much! I was narrowing the issue down and my final resort was this thread. Thank you for your service

**Comment by Explorergt92** [comment]
@jmanhype is this still an issue for you or can this be closed?
