### ISSUE TITLE
openai.error.APIConnectionError

### ISSUE THREAD

**Issue by munitioner** [Significant-Gravitas/Auto-GPT#1343]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

![image](https://user-images.githubusercontent.com/14157458/232084803-da567980-2495-4e16-a400-710df58d26a2.png)

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by JoeKanaan0** [comment]
Check that you have put the correct openAI api key in the .env file

**Comment by munitioner** [comment]
> 检查您是否在 .env 文件中放置了正确的 openAI api 密钥
The openAI API key is correct

**Comment by JoeKanaan0** [comment]
Try using the stable version of autoGPT, it's linked in the readME file

**Comment by Qoyyuum** [comment]
Hi @munitioner it looks like you can't connect to OpenAI's API endpoint. Please retry with a VPN connection.

**Comment by Pwuts** [comment]
Closing as stale. Feel free to reopen if the issue persists, but please check that it is not a problem with your own internet access.
