### ISSUE TITLE
Has this project been published on Docker Hub?

### ISSUE THREAD

**Issue by Passerby1011** [Significant-Gravitas/Auto-GPT#1344]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Has this project been published on Docker Hub?
I want to deploy it on my NAS, and it would be much easier if it has been published on Docker Hub.

**Comment by stankud** [comment]
I saw one dockerhub image, but I don't know if it's "official". If you can ssh into your NAS you can just clone the repo and build the container.
