### ISSUE TITLE
Auto-GPT Broken Coding Logic

### ISSUE THREAD

**Issue by TheHypeLab** [Significant-Gravitas/Auto-GPT#1358]
### Discussed in https://github.com/Torantulino/Auto-GPT/discussions/1349

<div type='discussions-op-text'>

<sup>Originally posted by **TheHypeLab** April 14, 2023</sup>
Hello everyone! I've been experimenting with Auto-GPT for some of my coding projects, but so far I've only had success with simple demos. I find the coding approach to be somewhat frustrating, as it often defaults to searching online for solutions rather than utilizing the extensive knowledge of GPT-4. Additionally, it seems to generate code in small chunks, while I've noticed that ChatGPT can produce most of a project's files in a shorter amount of time.

Has anyone else experienced similar issues with Auto-GPT, or have you been successful in creating more complex projects using it? If so, can you share any tips or techniques for prompting it more effectively to get better code generation results? I'd appreciate any insights or suggestions you may have! Thanks in advance!</div>

**Comment by ntindle** [comment]
Off topic

**Comment by ntindle** [comment]
Make a discussion instead of issues for things like this
