### ISSUE TITLE
Ugly look on some CMD/CLI because of no escape sequences for color formatting - SOLUTION

### ISSUE THREAD

**Issue by Playerrrrr** [Significant-Gravitas/Auto-GPT#136]
Not sure how to create a PR for this. 
But basically I found problems and solved them all by myself haha.

1. [optional] Had to manually input the google search module for pip in the requirements via replacing googlesearch-python in requirements.txt, with git+https://github.com/Nv7-GitHub/googlesearch.git
2. [main issue] Had issues with the ugly CMD whenever i ran "python scripts/main.py" that would show me irrelevant meta-data, response time in ms, conjuncted with lots of other meta-data that I didnt really care much for.

Problem:
The issue I was experiencing was related to the escape sequences for color formatting in my terminal output. These sequences are intended to change the color of the text, but they are being displayed as raw text instead of being interpreted properly.

Example problem:
←[35mInput:←[0my
←[35m-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= ←[0m
←[33mSYSTEM:  ←[0mCommand write_to_file returned: File written to successfully.

Solution: 
1. Run: "REG ADD HKCU\Console /v VirtualTerminalLevel /t REG_DWORD /d 1" in your bash/cmd before running the "python scripts/main.py" and restart your cmd
2. Problem solved, now you have pretty color coded auto-gpt in your cmd!

**Comment by giuliastro** [comment]
it doesn't work on my Windows 10 machine, still have the escaping codes problem

**Comment by jdonkers** [comment]
Thank you, the escaping problem fix worked for me on Windows 10.

**Comment by Explorergt92** [comment]
@Playerrrrr ... Is this still an issue or can it be closed?
