### ISSUE TITLE
execute_python_file no such file or directory

### ISSUE THREAD

**Issue by denen99** [Significant-Gravitas/Auto-GPT#1363]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Set a goal that ends up writing a python file to take some action 

wait for auto-gpt to try that action 

### Current behavior 😯

Getting the error 

Executing file 'data_analysis.py' in workspace 'auto_gpt_workspace'
SYSTEM:  Command execute_python_file returned: Error: File 'data_analysis.py' does not exist.

### Expected behavior 🤔

The python script executes

### Your prompt 📝

```yaml
# Create a list of every museum in the UK
```

**Comment by richbeales** [comment]
does a file by that name exist in auto_gpt_workspace subfolder?

**Comment by denen99** [comment]
It does not, which was what confuses me

**Comment by Jun10ng** [comment]
+1
Does need to create a Python file by autogpt's ACTION?

**Comment by CalyxNZ** [comment]
getting the same issue.

**Comment by hatgit** [comment]
Any solution for this, I also see the autogpt  workspace folder is empty and error `SYSTEM:  Command execute_python_file  returned: Error: File expected-python-file.py missing`

**Comment by ntindle** [comment]
Fixed
