### ISSUE TITLE
Command executed by Auto-GPT requires user input

### ISSUE THREAD

**Issue by lcswillems** [Significant-Gravitas/Auto-GPT#1368]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

The agent proposes this command to execute:

```
npx create-next-app --typescript
```

However this command requires the user to confirm by inputting "y". So the agent is stuck.

What is the way of handling this case?

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Qoyyuum** [comment]
Couldn't you create the next app yourself and tell the agent to continue from there?

**Comment by lcswillems** [comment]
What's the point of Auto-GPT if I have to do part of the work? Then once I have setup the app, it will probably propose to execute a command, but this command will ask for confirmation and then same issue.

**Comment by james431987** [comment]
> What's the point of Auto-GPT if I have to do part of the work? Then once I have setup the app, it will probably propose to execute a command, but this command will ask for confirmation and then same issue.

right now you have to help it along, it's not a finished app.

**Comment by lcswillems** [comment]
The problem is that it just hangs and I don't know why. I had to manually execute the command to know why it was hanging.

If Auto-GPT told me "look it seems the command asks for your input, please input", then it would have been all good.

**Comment by Qoyyuum** [comment]
@lcswillems do you have `EXECUTE_LOCAL_COMMANDS` set to True?

**Comment by lcswillems** [comment]
Yes

**Comment by Qoyyuum** [comment]
Can you try with the latest stable release and try again?

**Comment by lcswillems** [comment]
I have `git pull` the last changes but still stuck.

This is hanging forever:

```
THOUGHTS:  I will start a new Next.js project without cloning Chakra-UI repository. To do this, I can directly install the Chakra-UI package and its dependencies in my project directory.
REASONING:  This will save time and reduce overhead, as well as ensure that I am using the most up-to-date version of Chakra-UI.
PLAN: 
-  Create new Next.js project
-  Install Chakra-UI package and its dependencies
-  Configure TypeScript
-  Integrate Chakra-UI with project
CRITICISM:  I should ensure that I am using the latest version of Chakra-UI and its dependencies to ensure compatibility and prevent errors.
NEXT ACTION:  COMMAND = execute_shell ARGUMENTS = {'command_line': 'npx create-next-app my-next-app --ts'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
Input:
Invalid input format.
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
Executing command 'npx create-next-app my-next-app --ts' in working directory '/mnt/Data/Documents/Activités/Auto-entreprise/MultiversX/Code/Auto-GPT/auto_gpt_workspace'
```

**Comment by ntindle** [comment]
Sometimes it executes something unexpected or doesn’t do what you want.  Check out the #prompt-engineering channel in discord to get a better fit prompt
