### ISSUE TITLE
Issue committing to github through shell

### ISSUE THREAD

**Issue by TheNFTDAO** [Significant-Gravitas/Auto-GPT#1376]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

SYSTEM:  Human feedback: when you start building the app, commit code to this repo: git@github.com:examplerepo with the following token: github_pat_whatever

### Current behavior 😯

 Warning: Failed to parse AI output, attempting to fix.
 If you see this warning frequently, it's likely that your prompt is confusing the AI. Try changing it up slightly.
Failed to fix AI output, telling the AI.  
Error: Invalid JSON
  Thank you for the reminder. I will be sure to commit code to the github repository once I start development.
Attempting to fix JSON by finding outermost brackets 
Error: Invalid JSON, setting it to empty JSON now.
  
AICODER THOUGHTS: 
REASONING: 
CRITICISM: 
Attempting to fix JSON by finding outermost brackets 
Error: Invalid JSON, setting it to empty JSON now.
  
NEXT ACTION:  COMMAND = Error: ARGUMENTS = 'dict' object has no attribute 'replace'

### Expected behavior 🤔

Thank you for the reminder. I will be sure to commit code to the github repository once I start development.
  
AICODER THOUGHTS:  I will need to use the git command in the shell to commit code as I write it
REASONING: whatever
CRITICISM: etc
  
NEXT ACTION:  COMMAND = EXECUTE_LOCAL_COMMANDS (whatever shell commands it needs)

### Your prompt 📝

```yaml
# when you start building the app, commit code to this repo: git@github.com:examplerepo with the following token: github_pat_whatever
```

**Comment by TheNFTDAO** [comment]
Now I occasionally get NEXT ACTION:  COMMAND = command name ARGUMENTS = {'arg name': 'value'}
SYSTEM:  Command command name returned: Unknown command 'command name'. Please refer to the 'COMMANDS' list for available commands and only respond in the specified JSON format.

**Comment by p-i-** [comment]
Community effort to sort out this JSON fail once and for all at https://github.com/Torantulino/Auto-GPT/issues/1407

We have 17 open PRs for fixing this, and the merge-team are stacked.

**Comment by Pwuts** [comment]
Closing as one of many duplicates; superseded by #1407
