### ISSUE TITLE
Add human feedback into long-term memory

### ISSUE THREAD

**Issue by FlyWieEinAirplane** [Significant-Gravitas/Auto-GPT#1377]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

It could be beneficial, if human feedback could be persisted in long term memory.
I didn't fully think this through but there could be many instances where the operator gives feedback because the model misunderstood the task. After giving feedback, the context and feedback could be stored in long term memory to help AutoGPT make the right decision immediately next time, without the need to provide feedback again.

Note that this is most beneficial, if memory is persistent - as far as I understood, that is not the case right now(?)

### Examples 🌈

I read in another issue that AutoGPT wanted to clone its own repo github.com/Torantulino/Auto-GPT but ended up finding and cloning GPT-2.
Human feedback could be: When I talk about AutoGPT i mean github.com/Torantulino/Auto-GPT.
On a future run, AutoGPt would know, that GPT-2 is not AutoGPT and would not make the same mistake again.

### Motivation 🔦

autonomous learning of AutoGPT or at least learning from mistakes.

**Comment by normanlove222** [comment]
Not a bad idea at all. I mean, we are all thinking this

**Comment by Bigrussian8** [comment]
Ask Bing to help you with prompt engineering to help you with this problem. It doesn't fix the issue but it helps.
