### ISSUE TITLE
RuntimeError: Failed to get response after 5 retries

### ISSUE THREAD

**Issue by ishaoshupai** [Significant-Gravitas/Auto-GPT#1389]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Welcome to Auto-GPT!  Enter the name of your AI and its role below. Entering nothing will load defaults.
Name your AI:  For example, 'Entrepreneur-GPT'
AI Name: student
student here!  I am at your service.
Describe your AI's role:  For example, 'an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.'
student is: improve english skills
Enter up to 5 goals for your AI:  For example: Increase net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously'
Enter nothing to load defaults, enter nothing when finished.
Goal 1: improve speaking skills
Goal 2: imporve writting skills
Goal 3: improve reading skills
Goal 4:
Using memory of type: LocalCache
Traceback (most recent call last):
  File "D:\Auto-GPT-master\scripts\main.py", line 465, in <module>
    main()
  File "D:\Auto-GPT-master\scripts\main.py", line 328, in main
    agent.start_interaction_loop()
  File "D:\Auto-GPT-master\scripts\main.py", line 369, in start_interaction_loop
    assistant_reply = chat.chat_with_ai(
                      ^^^^^^^^^^^^^^^^^^
  File "D:\Auto-GPT-master\scripts\chat.py", line 126, in chat_with_ai
    assistant_reply = create_chat_completion(
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Auto-GPT-master\scripts\llm_utils.py", line 50, in create_chat_completion
    raise RuntimeError("Failed to get response after 5 retries")
RuntimeError: Failed to get response after 5 retries

### Current behavior 😯

RuntimeError: Failed to get response after 5 retries

**Comment by rebroad** [comment]
I'm also getting this. I added the --debug option and it's telling me I'm exceeding my API rate limit, but I don't know why this is happening.

**Comment by fxlee888** [comment]
Same issue here. I added a payment to my openai account (not chatgpt plus account) and the errors messages are gone!
Need to add "paid account on openAI" in the prerequisite..

**Comment by xavier-hou** [comment]
> Same issue here. I added a payment to my openai account (not chatgpt plus account) and the errors messages are gone! Need to add "paid account on openAI" in the prerequisite..

Really??...

**Comment by viniciusarruda** [comment]
It seems it is getting from the environment variable instead from the `.env` file. Set you `OPENAI_API_KEY` environment variable to a valid variable and test it. It worked here!

**Comment by utribedi** [comment]
Tried everything, still not working

**Comment by utribedi** [comment]
> Same issue here. I added a payment to my openai account (not chatgpt plus account) and the errors messages are gone! Need to add "paid account on openAI" in the prerequisite..

Tried this, still doesn't work

**Comment by IngeniozIT** [comment]
Even though I hadn't done any request with my trial plan (and thus didn't exceed any quota), it started working once I switched to a paid plan.

**Comment by aaronjrodrigues** [comment]
I am getting this error as well

**Comment by aaronjrodrigues** [comment]
> 

How exactly do you do this?

**Comment by fxlee888** [comment]
Have you created a new API key after upgrading paid plan ?

**Comment by utribedi** [comment]
> Have you created a new API key after upgrading paid plan ?

This was precisely the issue. Works perfectly now. Thanks for pointing it out @fxlee888

**Comment by fylim** [comment]
Yeah upgrading to paid plan and creating a new API key appears to be working

**Comment by CharlieAlphaFox** [comment]
A paid plan per query is different from ChatGPT plus. Ensure the membership status under the settings has a charge per API call. I also set a hard and a soft limit in USDs per month so that it doesnt charge me more than I can pay, the default is something like $120 and $96 for hard and soft limits.
