### ISSUE TITLE
I am probably just dumb, Ingest question

### ISSUE THREAD

**Issue by Lucyan11** [Significant-Gravitas/Auto-GPT#1401]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

I ingest the data and it populates the JSON file in the root. And its confirmed good.
But then when i start the auto, it wipes the json file.  Same thing with pinecone.  I have the paid pinecone account so i was able to use another build to ingest with a name space that doesnt wipe, but I cannot get the auto to recognize its there, and if I ingest to pinecone then it just wipes as soon as i fire up auto.

I am probably just dumb.

Do i just copy the ingested json file and place it in the workspace?

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by darkcount2011** [comment]
⚠️ If you use Redis as your memory, make sure to run Auto-GPT with the WIPE_REDIS_ON_START set to False in your .env file.

⚠️For other memory backend, we currently forcefully wipe the memory when starting Auto-GPT. To ingest data with those memory backend, you can call the data_ingestion.py script anytime during an Auto-GPT run.

from the readme.md,
Maybe this is the reason?

**Comment by Lucyan11** [comment]
Ty for replying.

I figured "other" meant not the ones listed.  but this makes sense, ill try it.

Also, do you know what should be said to auto to get it to look at its memory?

**Comment by darkcount2011** [comment]
> Ty for replying.
> 
> I figured "other" meant not the ones listed. but this makes sense, ill try it.
> 
> Also, do you know what should be said to auto to get it to look at its memory?

I do not sorry, If you manage to figure it out, let me know! 😉

**Comment by Lucyan11** [comment]
Did not work, gets to like 4000kb then resets.

Anyone know if this is fixable?

**Comment by omikolaj** [comment]
Also curious how to get it to only look into memory and not try to come up with answers. I've tried:

"only use the information in memory to answer the following question : '...' "

And alikes, but nothing works.
