### ISSUE TITLE
Error:ARGUMENTS = name 'fix_and_parse_json' is not defined

### ISSUE THREAD

**Issue by lddssxy** [Significant-Gravitas/Auto-GPT#1440]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

When I start to run auto-GPT, each step when auto-GPT want to take NEXT ACTION, it gives this error:

### Current behavior 😯

 COMMAND = Error: ARGUMENTS = name 'fix_and_parse_json' is not defined

### Expected behavior 🤔

 
![image](https://user-images.githubusercontent.com/18322096/232169993-d4ecdc0a-0c38-459a-bae1-2ad4e65d6f16.png)

### Solution
Thanks to [JordenPTerrazas](https://github.com/JordenPTerrazas) provided following approach to fix this issue:
adding `from autogpt.json_parser import fix_and_parse_json` to the top of: ./autogpt/commands.py

**Comment by OSSAInc** [comment]
Same issue

**Comment by lawpass27** [comment]
Same issue

**Comment by draggingsurf** [comment]
same here 
![image](https://user-images.githubusercontent.com/125905102/232172812-c03e2adf-dd62-4581-b73b-b2bccfa22aaf.png)

**Comment by JordenPTerrazas** [comment]
You can fix this by adding "from autogpt.json_parser import fix_and_parse_json" to the top of: ./autogpt/commands.py

**Comment by disusername** [comment]
> You can fix this by adding "from autogpt.json_parser import fix_and_parse_json" to the top of: ./autogpt/commands.py

After i tried that and running autogpt I get "SyntaxError: invalid syntax" with reference to line 1 of the commands.py file

**Comment by decsters01** [comment]
eu acredito que ele nao esteja achando o arquivo jason isso ocasiona erros
em todas as execucoes


Em sáb., 15 de abr. de 2023 às 00:36, disusername ***@***.***>
escreveu:

**Comment by p-i-** [comment]
Can someone confirm if this is resolved?

**Comment by fewmatty** [comment]
I am having the same issue. adding - from autogpt.json_parser import fix_and_parse_json - does not seem to be resolving for me.

**Comment by disusername** [comment]
I had this problem when I did had installed by downloading zip instead of using “git clone”. I also had missing dependencies but got it running with the error. 
in the end I reinstalled the application again using git clone command and remaining instructions and now it’s all working

**Comment by ntindle** [comment]
Fixed?
