### ISSUE TITLE
File Not Found Error: speech.mp3

### ISSUE THREAD

**Issue by joshfranzen** [Significant-Gravitas/Auto-GPT#1465]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Run in windows CMD: `python -m autogpt --gpt3only --continuous --speak`

### Current behavior 😯

When running with the `--speech` flag, occasionally auto-gpt encounters an error stating that it cannot find 'speech.mp3' after executing 'execute_shell' functions and then the process hangs and becomes completely unresponsive. Running this in debug mode produced a single error stating that the AI encountered an improperly formatted response but in the below error its clear whats happening:

```
NEXT ACTION:  COMMAND = execute_shell ARGUMENTS = {'command_line': 'notepad readme.md'}
Executing command 'notepad readme.md' in working directory 'D:\Auto-GPT\auto_gpt_workspace'
Exception in thread Thread-14 (speak):
Traceback (most recent call last):
  File "C:\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Auto-GPT\autogpt\speak.py", line 110, in speak
    gtts_speech(text)
  File "D:\Auto-GPT\autogpt\speak.py", line 87, in gtts_speech
    os.remove("speech.mp3")
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'speech.mp3'
```

this behavior did not occur while i was using elevenlabs (at least before i hit my token limit in continuous mode), but did occur in both Brian and gTTS modes.

This seems to happen in a couple different ways but the crux seems to be that the speech.mp3 is being created and then a working directory change will happen. On one occasion the file ended up in the auto_gpt_workspace folder.

### Expected behavior 🤔

The speech.mp3 file gets created in /auto-gpt, played, and then deleted.

I'm going to try and add couple time.sleep() breaks in the execute_shell function to see if that helps.

### Your prompt 📝

```
ai_goals:
- clone the code from https://github.com/Torantulino/Auto-GPT
- analyze the code and create a mermaid diagram describing the structure and function of
  the application using windows command line
- 'create a report with suggestions to improve the code with code snippet examples '
ai_name: codeGPT
ai_role: an expert software engineer with a focus in QA and troubleshooting, specifically
  python code. it uses a windows workstation.

```

**Comment by Wladastic** [comment]
the changes went long past that already, maybe do git pull.

**Comment by Qoyyuum** [comment]
Hi @joshfranzen can you try and use the latest stable release and try again?

**Comment by joshfranzen** [comment]
> Hi @joshfranzen can you try and use the latest stable release and try again?

Will do

**Comment by joshfranzen** [comment]
Can't seem to replicate this after a pull because auto-gpt seems more unstable in other ways. will close this.
