### ISSUE TITLE
Can you add support for multi-line prompts? Or API support?

### ISSUE THREAD

**Issue by rrtt2323** [Significant-Gravitas/Auto-GPT#1469]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

When describing the role of the AI, I used a lot of lines to make sure that it understood its role accurately.
However, when typing, line breaks cause the input to break.
I can only merge them into one line via vscode, which is inconvenient.
Is there a way to support multiple rows, or there is already such a function, but I don't know yet？
Or it can let the AI read the input configuration file in a specific format, and there is no need to repeatedly enter it in the cmd, which feels that this efficiency will be very high.

### Examples 🌈

1, You are a screenwriter AI.
2, You need to help me write a story.

### Motivation 🔦

Better typing experience, and more precise description of problems.

**Comment by normanlove222** [comment]
This is a cool idea and helpful. 

I was thinking even allow it so we can provide initial prompts and tasks via a text file, this way we take our time and write it out and have it saved at the same time and then AutoGPT just imports it and reads it. should not be too much of a hassle to code.

**Comment by Cytranics** [comment]
Open notepad. Type all you want. Tell the bot its only role is to check spec.txt

**Comment by normanlove222** [comment]
Yes, of course, Eureaka! Thank you.

**Comment by gauravbrills** [comment]
Cant we just add in `ai_settings.yaml` , that also works
