### ISSUE TITLE
safe_join function in file_operation.py IS NOT SAFE

### ISSUE THREAD

**Issue by xiongsp** [Significant-Gravitas/Auto-GPT#1480]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

1. If the module unexpectedly generate a link named `'Auto-GPT'` points to `../`
2. The module tries to write `Auto-GPT/.env` and set `EXECUTE_LOCAL_COMMANDS=False` to True
3. The module tries to execute dangerous commands.

To fix this, add another check in `safe_join`
#1481 

### Current behavior 😯

/

### Expected behavior 🤔

/

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Pwuts** [comment]
Should be fixed by #1947
