### ISSUE TITLE
Browse website fails with chromedriver error

### ISSUE THREAD

**Issue by psvensson** [Significant-Gravitas/Auto-GPT#1494]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

This is from todays build (0.2.0?).
Wait until the AI searches for anything (this worked fine yesterday), and .. boom:

SYSTEM:  Command browse_website returned: Error: Message: Service /root/.wdm/drivers/chromedriver/linux64/112.0.5615.49/chromedriver unexpectedly exited. Status code was: 127

### Current behavior 😯

SYSTEM:  Command browse_website returned: Error: Message: Service /root/.wdm/drivers/chromedriver/linux64/112.0.5615.49/chromedriver unexpectedly exited. Status code was: 127

### Expected behavior 🤔

browse_website should work as expected

### Your prompt 📝

```yaml
# create a common lisp asdf project which implements the wave function collapse algorithm
```

**Comment by richbeales** [comment]
Do you have Chrome installed?

**Comment by psvensson** [comment]
Aha, that was it, thanks. I was using another repo which creates a docker sandbox of autgpt and that Dockerfile did not install chromium (of course - it was made over a week ago :) ).
Now it works after manually installing in the container, so closing this..

**Comment by lirankor** [comment]
> Aha, that was it, thanks. I was using another repo which creates a docker sandbox of autgpt and that Dockerfile did not install chromium (of course - it was made over a week ago :) ). Now it works after manually installing in the container, so closing this..

How did you do it?

**Comment by GabrielBarberini** [comment]
> Yeah please share how did you do that!

$
```
docker attach <image>
wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
sudo dnf localinstall ./google-chrome-stable_current_x86_64.rpm
```
