### ISSUE TITLE
RuntimeError: Failed to get response after 5 retries

### ISSUE THREAD

**Issue by mahmoudrabie** [Significant-Gravitas/Auto-GPT#1498]
> Using memory of type: LocalCache
> Traceback (most recent call last):
>   File "scripts/main.py", line 441, in <module>
>     main()
>   File "scripts/main.py", line 304, in main
>     agent.start_interaction_loop()
>   File "scripts/main.py", line 345, in start_interaction_loop
>     assistant_reply = chat.chat_with_ai(
>   File "/workspaces/Auto-GPT/scripts/chat.py", line 126, in chat_with_ai
>     assistant_reply = create_chat_completion(
>   File "/workspaces/Auto-GPT/scripts/llm_utils.py", line 50, in create_chat_completion
>     raise RuntimeError("Failed to get response after 5 retries")
> RuntimeError: Failed to get response after 5 retries]

Would appreciate your support

**Comment by mahmoudrabie** [comment]
When I added --debug, I discovered the root cause
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/2697012/232197238-802afdba-53d0-45e3-afe1-0aed612ae57c.png">

**Comment by EmediongFrancis** [comment]
@mahmoudrabie, what did you do to fix it?

**Comment by EmediongFrancis** [comment]
@mahmoudrabie, what did you do to fix it?

**Comment by EmediongFrancis** [comment]
@mahmoudrabie, what did you do to fix it?

**Comment by mahmoudrabie** [comment]
I just know the root cause.

As per the screenshot I think I need to upgrade my account my account to be able to exceed this limit.
