### ISSUE TITLE
有没有高手，改成用百度查找资料，用中文使用，适合中国使用

### ISSUE THREAD

**Issue by WIKI2020** [Significant-Gravitas/Auto-GPT#1508]
### Duplicates

- [X] I have searched the existing issues

**Comment by richbeales** [comment]
English only please

**Comment by nponeccop** [comment]
@WIKI2020 

有没有高手，改成用百度查找资料，用中文使用，适合中国使用

**Comment by ottocsb** [comment]
百度全是内容农场，俩字：垃圾

**Comment by nponeccop** [comment]
@WIKI2020 好的。我正在使用 ChatGPT 进行翻译。是否可以请您在“重复问题”部分提到您最初的中文问题？我正在尝试邀请更多的非英语成员，看看这是否可行。顺便问一下，我的中文怎么样？比谷歌翻译好吗？对于我的母语俄语来说，使用 ChatGPT 的翻译效果要好一些。

**Comment by WIKI2020** [comment]
感谢，你们的翻译的中文非常好，我有两个建议：
（1）用户可以选择谷歌，也可以选用百度进行搜索

**Comment by WIKI2020** [comment]
Thank you, your translation in Chinese is very good. I have two suggestions:
(1) Users can choose Google or Baidu for search (2) they can use English or Chinese for operation. Even if the target is filled in and needs to be translated into Chinese, the result is still in English. If this improvement can be made, the project star will soon reach 100K.

**Comment by youkaichao** [comment]
@WIKI2020 If you have a valid proxy, you can try my pr here: https://github.com/Significant-Gravitas/Auto-GPT/pull/1541 .

**Comment by nponeccop** [comment]
@WIKI2020 It was ChatGPT speaking Chinese on my request. Can you open an English issue for (2) so we can further discuss it there? It's an easy feature.

**Comment by 25558257** [comment]
> Thank you, your translation in Chinese is very good. I have two suggestions:谢谢，你的中文翻译很好。我有两个建议： (1) Users can choose Google or Baidu for search (2) they can use English or Chinese for operation. Even if the target is filled in and needs to be translated into Chinese, the result is still in English. If this improvement can be made, the project star will soon reach 100K.(1) 用户可以选择谷歌或百度进行搜索 (2) 可以使用英文或中文进行操作。即使填了target需要翻译成中文，结果还是英文。如果能做到这一点，project star很快就会达到100K。

在提示词最后加上一句，请使用中文就可以了。

**Comment by nponeccop** [comment]
@25558257  我猜他可能在获取它所使用的提示方面遇到了问题。虽然大部分提示信息都在ai_settings中，但是一部分提示信息可能在其他地方或是被硬编码在程序中了。您可以向他解释一下如何获取和修改原始提示信息吗？

**Comment by 25558257** [comment]
> @25558257 我猜他可能在获取它所使用的提示方面遇到了问题。虽然大部分提示信息都在ai_settings中，但是一部分提示信息可能在其他地方或是被硬编码在程序中了。您可以向他解释一下如何获取和修改原始提示信息吗？

guess he should have understood by now.

**Comment by Jun10ng** [comment]
我在https://github.com/Significant-Gravitas/Auto-GPT/issues/1629 这个需求里 实现了支持中文搜索谷歌。
没必要使用百度搜索，一些中文页面也会被谷歌收录的。你的难点应该是在于 如何使用中文搜索资料。

**Comment by gaye746560359** [comment]
> > @25558257 我猜他可能在获取它所使用的提示方面遇到了问题。虽然大部分提示信息都在ai_settings中，但是一部分提示信息可能在其他地方或是被硬编码在程序中了。您可以向他解释一下如何获取和修改原始提示信息吗？
> 
> guess he should have understood by now.

ai_settings模板我没看到。是在哪个目录下面？有参考吗

**Comment by AlexANSO** [comment]
百度的结果你也敢信？

**Comment by wuyongFF** [comment]
百度？何不让它直接爬人民日报

**Comment by qq641101978** [comment]
Looking forward to a multi-language version

**Comment by Shadow-Alex** [comment]
It seems there's a Baidu Search plugin for auto-gpt, maybe it can help you : https://github.com/Significant-Gravitas/Auto-GPT-Plugins/tree/master/src/autogpt_plugins/baidu_search

**Comment by lc0rp** [comment]
Closing based on comment https://github.com/Significant-Gravitas/Auto-GPT/issues/1508#issuecomment-1587200064

If this is still an issue please reopen or open a new issue.
