### ISSUE TITLE
Search web only for data post 2021

### ISSUE THREAD

**Issue by MayurVirkar** [Significant-Gravitas/Auto-GPT#1514]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Currently, its searching the web for everything. Old data as well, which is already part of its training dataset.
Which makes it heavy, and consume a lot of tokens.
Eg: In one research I was doing, it was referring to an article from 2013, which when I search on ChatGPT, it already had it in its training dataset.

Suggestion: Force AutoGPT to search web only for data post-2021 if it feels its dataset is outdated. Else refer to currently trained OpenAI dataset.

**Comment by lc0rp** [comment]
Thanks for your submission. 

The idea of saving time and tokens by restricting web searches is intriguing, but its applicability heavily relies on the circumstances. Searching for older information on the internet can be beneficial in some situations, for example, to minimize hallucinations. 

Furthermore, AutoGPT can be programmed to limit the usage of search commands, such as by precisely defining its goals, or by modifying its original prompts (refer to prompt_settings.yaml), or adjusting DISABLED_COMMAND_CATEGORIES in .env.
