### ISSUE TITLE
SYSTEM:  Command google returned: Error: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应 ，连接尝试失败。 MAKE A FLOWCHART THOUGHTS:  The google command failed, so I will try to browse a website related to website creation to learn more about the topic

### ISSUE THREAD

**Issue by yyx20202020** [Significant-Gravitas/Auto-GPT#1527]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

SYSTEM:  Command google returned: Error: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应
，连接尝试失败。
MAKE A FLOWCHART THOUGHTS:  The google command failed, so I will try to browse a website related to website creation to learn more about the topic

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by nponeccop** [comment]
以下是一个礼貌的中文建议，以缩短标题并将详细信息移至GitHub问题描述：

您好，我建议您将标题缩短并将详细信息添加到GitHub问题描述中。例如，您可以将标题修改为“系统错误：无法连接到谷歌”，然后在问题描述中提供更多细节，包括您的思路和尝试的解决方案。这样做可以使标题更简洁，易于理解，并确保问题描述中包含足够的信息以帮助其他用户理解问题并提供帮助。

**Comment by youkaichao** [comment]
@yyx20202020  Maybe this pr can help you: https://github.com/Significant-Gravitas/Auto-GPT/pull/1541 .

**Comment by zxcvcxz12345** [comment]
我也是啊。。。开了全局还是不行。。

**Comment by youkaichao** [comment]
@zxcvcxz12345 需要在Chrome里面也开代理，我用 #1541 是可以的。

**Comment by zxy177280210** [comment]
这个博客可以解决：https://blog.csdn.net/weixin_43744732/article/details/130190697

**Comment by andykcer** [comment]
现在怎么解决这个问题呢
