### ISSUE TITLE
support proxy 

### ISSUE THREAD

**Issue by doseralutajy** [Significant-Gravitas/Auto-GPT#1532]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Not all places can support chatgpt, so I need to use a proxy, and I want to be able to run it locally and set up a proxy instead of hosting it on a server.

### Examples 🌈

![image](https://user-images.githubusercontent.com/110469337/232208502-4277f6ae-9a02-4502-b105-92e3e3d33c52.png)

### Motivation 🔦

Not all places can support chatgpt, so I need to use a proxy, and I want to be able to run it locally and set up a proxy instead of hosting it on a server.

**Comment by ntindle** [comment]
#1275
