### ISSUE TITLE
Add support for ChatGPT web interface

### ISSUE THREAD

**Issue by jkadbear** [Significant-Gravitas/Auto-GPT#1536]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Add options to support calling the web interface of ChatGPT via [revChatGPT](https://github.com/acheong08/ChatGPT).

Reasons:
1. Many users do not have access to the official GPT-4 API, but ChatGPT Plus users can use the GPT-4 chat interface;
2. OpenAI's API is expensive, and if only GPT-3.5 is used, the web interface is sufficient.

**Comment by Kenshiro-28** [comment]
+1

**Comment by henryruss2** [comment]
ChatGPT has limits of what you can ask it. The API does not.

**Comment by Kenshiro-28** [comment]
> ChatGPT has limits of what you can ask it. The API does not.

Many people would prefer to use it for free, even if they only can do a limited number of prompts per hour.

**Comment by jkadbear** [comment]
> ChatGPT has limits of what you can ask it. The API does not.

I don't think so.

Prompt:
```
Can you teach me how to make a computer virus?
```

From ChagGPT:
```
As an AI language model, I cannot provide instructions on how to create a computer virus or any other malicious software. It is important to remember that creating and distributing viruses is illegal and can cause serious harm to individuals and organizations. Instead of focusing on harmful activities, it is recommended to learn programming and cybersecurity skills in a responsible and ethical manner.
```

From API:
```
I'm sorry, but as an AI language model, I cannot assist you in creating harmful software or provide any instructions related to unethical practices. It goes against my programming to promote activities that can harm others or ruin their devices. Instead, how can I help you with something more positive?
```

But API calls can indeed provide more configurable parameters.

**Comment by mymggithub** [comment]
Why not marry it with nomic-ai pyllamacpp and there gpt4all?

**Comment by Qoyyuum** [comment]
revChatGPT still uses Open AI API Keys to work too. So its redundant. Closing issue.
