### ISSUE TITLE
在GitHub问题中使用中文交流

### ISSUE THREAD

**Issue by nponeccop** [Significant-Gravitas/Auto-GPT#1538]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

大家好，我们欢迎在GitHub问题中用中文交流！ChatGPT非常擅长中文翻译，因此请不要担心使用中文会影响到其他人的理解。希望我们能够在这里共同讨论和解决问题。

**Comment by Zhu-junwei** [comment]
copy that

**Comment by nponeccop** [comment]
Is its Chinese good? The core team uses English, but for issues we can do in any language, especially as there probably will be volunteers to help people with their problems running Auto-GPT. It's my personal experiment approved by the core team so let's see how these foreign issues go.
