### ISSUE TITLE
Any input i give it, it crashes after a while of thinking

### ISSUE THREAD

**Issue by hmohamed1** [Significant-Gravitas/Auto-GPT#1543]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Using memory of type: LocalCache
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\H\Downloads\Auto-GPT-master\Auto-GPT-master\autogpt\__main__.py", line 572, in <module>
    main()
  File "C:\Users\H\Downloads\Auto-GPT-master\Auto-GPT-master\autogpt\__main__.py", line 396, in main
    agent.start_interaction_loop()
  File "C:\Users\H\Downloads\Auto-GPT-master\Auto-GPT-master\autogpt\__main__.py", line 448, in start_interaction_loop
    assistant_reply = chat.chat_with_ai(
                      ^^^^^^^^^^^^^^^^^^
  File "C:\Users\H\Downloads\Auto-GPT-master\Auto-GPT-master\autogpt\chat.py", line 159, in chat_with_ai
    assistant_reply = create_chat_completion(
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H\Downloads\Auto-GPT-master\Auto-GPT-master\autogpt\llm_utils.py", line 67, in create_chat_completion
    raise RuntimeError("Failed to get response after 5 retries")
RuntimeError: Failed to get response after 5 retries

C:\Users\H\Downloads\Auto-GPT-master\Auto-GPT-master>

### Current behavior 😯

Installed everything correctly but when i give it a goal, it gives me that error after a few seconds

**Comment by dmitry-mikheev** [comment]
+1

**Comment by abhigolem** [comment]
+1

**Comment by jaensen** [comment]
This is not an error with the scripts. Try e.g. the following to see if your API quota is already expired:
```
curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer <API-KEY>" -d '{"model": "text-davinci-002", "prompt": "Hello, my name is ", "temperature": 0.5, "max_tokens": 50}' https://api.openai.com/v1/completions
```

**Comment by Qoyyuum** [comment]
@hmohamed1 please run `python -m autogpt --debug`. If it shows `Error: API Rate Limited` can you confirm if you have valid and not expired tokens in your openai account?

**Comment by Brian-Webster** [comment]
> @hmohamed1 please run `python -m autogpt --debug`. If it shows `Error: API Rate Limited` can you confirm if you have valid and not expired tokens in your openai account?

I may be having a similar issue. When I run the CURL command listed above, I am notified that my quota has been reached and that I need to check my billing plan. 

When I run your debug mode, it looks like this: 

![image](https://user-images.githubusercontent.com/3356598/232251662-3167cf61-cb0f-40ba-8142-40c152b0f846.png)

I'll edit this message to confirm how I was able to fix the issue.
