### ISSUE TITLE
我如何通过修改chat.py文件来默认使autogpt在工作时要求openai api使用中文回复所有答案。

### ISSUE THREAD

**Issue by KzNight** [Significant-Gravitas/Auto-GPT#1549]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

我阅读了chat.py代码，发现通过chat_with_ai()来建立聊天提问，但我尝试添加了一些代码例如
create_chat_completion(
    model=model,
    messages=[create_chat_message("system", "后续回复全部使用中文")],
    max_tokens=50,
)
都没法让autoGPT在后续的回复中默认要求openai api全程使用中文回答问题。
我应该如何修改这部分代码呢？

### Examples 🌈

create_chat_completion(
    model=model,
    messages=[create_chat_message("system", "后续回复全部使用中文")],
    max_tokens=50,
)

### Motivation 🔦

对用使用中文的用户能更快理解autogpt的所有回答，尤其是在快速迭代的时候。

**Comment by nponeccop** [comment]
我可以指导您。您也会说英语吗？如果不会，也没问题，只是需要更多时间。

**Comment by KzNight** [comment]
> 我可以指导您。您也会说英语吗？如果不会，也没问题，只是需要更多时间。

我可以，你全程使用英文指导就行，我只是写英语很差，但我可以很快读懂英语。

**Comment by zheng10005** [comment]
> 有同样的需求，能公开指导方法吗

**Comment by zheng10005** [comment]
> ### Duplicates
> * [x]  I have searched the existing issues
> 
> ### Summary 💡
> 我阅读了chat.py代码，发现通过chat_with_ai()来建立聊天提问，但我尝试添加了一些代码例如 create_chat_completion( model=model, messages=[create_chat_message("system", "后续回复全部使用中文")], max_tokens=50, ) 都没法让autoGPT在后续的回复中默认要求openai api全程使用中文回答问题。 我应该如何修改这部分代码呢？
> 
> ### Examples 🌈
> create_chat_completion( model=model, messages=[create_chat_message("system", "后续回复全部使用中文")], max_tokens=50, )
> 
> ### Motivation 🔦
> 对用使用中文的用户能更快理解autogpt的所有回答，尤其是在快速迭代的时候。

![63fd0aa726652d81b45a8c8e9ec9e6a](https://user-images.githubusercontent.com/29821139/232224518-a5793d0c-1131-42e8-87f8-180e930afd93.png)
![9c37a4c22e4c7a971f0aa8e0314a726](https://user-images.githubusercontent.com/29821139/232224521-881171e0-8500-43b9-8282-81e9bfc5e2b5.png)
哥们，我尝试在这个位置加用中文回复，亲测有效。gpt回复的时候暂未发现其他非常规错误

**Comment by nponeccop** [comment]
#1563

我刚刚创建了一个英文的问题，供核心团队参与。请注意，我们需要的不是黑客方法，而是一个良好的架构方法，使语言特定的部分不是硬编码的，而是可配置的。我们需要这个方法，因为通过对初始提示进行完全定制可以获得很大的灵活性。

**Comment by KzNight** [comment]
QaQ，我这里找到了另外一个项目，作为有同样需求的人的另外一个参考。

**Comment by Imccccc** [comment]
建议使用英语，因为GPT英文能力更强。但是对于用户的Prompt可以支持多语言

**Comment by iT-Boyer** [comment]
@zheng10005 添加 `中文回复` 之后出现了json 无效的情况
```
 Warning: Failed to parse AI output, attempting to fix.
 If you see this warning frequently, it's likely that your prompt is confusing the AI. Try changing it up slightly.
Failed to fix AI output, telling the AI.
Error: Invalid JSON
```

**Comment by likanghai** [comment]
我认为你应该在prompt.py中，def get_prompt函数下加入 prompt_generator.add_constraint("Reply in Chinese")或者是prompt_generator.add_constraint("in Chinese")，这里建议开发者把语言做成可配置式，或者AI根据使用者问答语言应答的方式更好

**Comment by rich1e** [comment]
> 我认为你应该在prompt.py中，def get_prompt函数下加入 prompt_generator.add_constraint("Answer me in Chinese")，这里建议开发者把语言做成可配置式，或者AI根据使用者问答语言应答的方式更好

这样做是有效果的。

![image](https://user-images.githubusercontent.com/29914689/232703430-61937e28-0187-483d-bc94-e10f89adf3af.png)

**Comment by liurat** [comment]
@rich1e 可以说明一下具体怎么调整的吗？谢谢

**Comment by rich1e** [comment]
找到这段代码，在后面添加一句 `prompt_generator.add_constraint("Answer me in Chinese")`

https://github.com/Significant-Gravitas/Auto-GPT/blob/bcda3c1a3241c35caa6bcc746ee9b0441ea77939/autogpt/prompts/prompt.py#L34-L38

参考：

![image](https://user-images.githubusercontent.com/29914689/233268109-f308dd4f-d73f-4f4f-9b46-c6bb717e50bd.png)

**Comment by liurat** [comment]
@rich1e 我已经这样调整了，但是好像并没有生效
![image](https://user-images.githubusercontent.com/42959622/233270529-78401972-2247-4afa-9c88-ef504c9de174.png)
![image](https://user-images.githubusercontent.com/42959622/233270967-4d9b7cc8-44a5-44dd-9437-60c784436112.png)

**Comment by rich1e** [comment]
@liurat 建议从以下 2 点排查。

1. `env` 配置，缺少相关服务；
   - OPENAI_API_KEY
   - GOOGLE_API_KEY

2. 运行 Auto-GPT 时，需要科学上网；

> ⚠️ 注意: 
> 1. `Chat-GPT` 支持中文。
> 2. `THOUGHTS，REASONING，PLAN，CRITICISM`，这些内容是 `Chat-GPT` 输出。

**Comment by iT-Boyer** [comment]
> @rich1e 我已经这样调整了，但是好像并没有生效

遇到同样问题，解决了吗
