### ISSUE TITLE
create app and ask autogpt to create files only, don't use execute_shell to install any dependency

### ISSUE THREAD

**Issue by gaoqing** [Significant-Gravitas/Auto-GPT#1552]
### Duplicates

- [x] I have searched the existing issues

### Steps to reproduce 🕹

I ask it to create a simple website, and sets goals to create all relevant files under autogpt work space only, I explicitly command: "don't ask authorization to execute any shell script to change directory or install any package or software, I will manually install and spin up the app myself, just add steps for bringing up the app into readme file." 

but it keeps asking me permission for  "execute_shell" to install things, ie. npm install etc, or mkdir etc

### Current behavior 😯

but it keeps asking me permission for  "execute_shell" to install things, or mkdir, or npm install ect

### Expected behavior 🤔

just create static files into some dir under it workspace. I want to run 'npm install or any build step' by myself before I manually start up the app.

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Justinandjohnson** [comment]
same same same. this or the "do_nothing" command ugh so close so far

**Comment by fyhao** [comment]
I asked him to create nodejs file, python code, and execute, it failed to and always go to do_nothing

But when I asked him to create bash shell script to do something, it worked....
