### ISSUE TITLE
Consecutive execute_shell should share last working directory.

### ISSUE THREAD

**Issue by CoffeeImpliesCode** [Significant-Gravitas/Auto-GPT#1554]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Currently each execute_shell spawns a new process with directory auto_gpt_workspace. That confuses the LLM as doing cd subdirectory will be lost at next shell prompt. For me it keeps generating shell commands that do not work because it is assumed that we are in the directory we left off.

### Motivation 🔦

For Auto-GPT to create sophisticated folder structures it needs to have a persistent shell for relative commands to work.

**Comment by KernAlan** [comment]
Same problem here. It needs to retain memory of its working directory, or else it gets stuck trying to execute shell commands that don't work.

**Comment by Boostrix** [comment]
saw this, too - had to adapt ai_settings.yaml to explicitly set up the notion of a subdirectory inside the workspace and refer to that as the cwd in each subsequent line - but from then on, it just worked
