### ISSUE TITLE
 Command execute_local_command returned: Unknown command 'execute_local_command'.

### ISSUE THREAD

**Issue by xiaoqiangch** [Significant-Gravitas/Auto-GPT#1557]
I have got this feed back:

2023-04-15 15:39:14,325 INFO Apparently json was fixed.
2023-04-15 15:39:14,495 INFO NEXT ACTION:  COMMAND = execute_local_command  ARGUMENTS = {'command_line': 'mkdir -p ~/.obsidian/plugins/chatgp-plugin && touch ~/.obsidian/plugins/chatgp-plugin/main.js'}
2023-04-15 15:39:21,634 INFO -=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-=
2023-04-15 15:39:22,291 INFO SYSTEM:  Command execute_local_command returned: Unknown command 'execute_local_command'. Please refer to the 'COMMANDS' list for available commands and only respond in the specified JSON format.

and the program kind of stuck in a loop, the shell command was not executed.

any ideas for solving this issue? thanks a lot.

**Comment by Qoyyuum** [comment]
That's not one of the valid commands. If you meant to use `execute_shell`, please use that.

**Comment by Pictor13** [comment]
That's what auto-gpt decides to use by itself.
To me always suggests `execute_command` or `execute_python_command` but none of them work, they all fail.

**Comment by neodenit** [comment]
Does it make sense to add `execute_local_command ` and `execute_command` as synonyms for `execute_shell`?

https://github.com/Significant-Gravitas/Auto-GPT/blob/e9f3f9bd1d7b1e3e2152049962d993e31dcfa793/autogpt/app.py#L75

**Comment by clouderops** [comment]
I have the same issue.

SYSTEM:  Command shell returned: Unknown command 'shell'. Please refer to the 'COMMANDS' list for available commands and only respond in the specified JSON format.
/ Thinking...

**Comment by samchapman94** [comment]
anyone have any temporary solutions for this?

**Comment by tom634** [comment]
My agent is stuck on and is repeating it:
NEXT ACTION:  COMMAND = execute_command ARGUMENTS = {'command': 'mkdir something'}
SYSTEM:  Command execute_command returned: Unknown command 'execute_command'. Please refer to the 'COMMANDS' list for available commands and only respond in the specified JSON format.
I am working on Windows, VS code

**Comment by Genening** [comment]
Same problem 🤣
> SYSTEM:  Command execute_command returned: Unknown command 'execute_command'. Please refer to the 'COMMANDS' list for available commands and only respond in the specified JSON format.

**Comment by agarrubio** [comment]
Same issue:
SYSTEM: Command execute_command returned: Unknown command 'execute_command'. Please refer to the 'COMMANDS' list for available commands and only respond in the specified JSON format.

Working in Ubuntu 20.04, inside conda environment

**Comment by Boostrix** [comment]
Somehow, I find the "local" distinction rather clever actually - it's just smarter than it's supposed to be.

You could probably augment the "Please refer to ... " with "did you  mean EXECUTE_SHELL" (at the cost of using the LLM to prime itself)

**Comment by construnario** [comment]
I activated EXECUTE_LOCAL_COMMANDS=True in the .env file and now it's working.

**Comment by anonhostpi** [comment]
related: #3994

**Comment by hatgit** [comment]
is there a way to have it execute local terminal commands only within docker? Since setting both, EXECUTE_LOCAL_COMMANDS and RESTRICT_TO_WORKSPACE to =True, isn't enough (as it will still save files outside of the docker environment).

**Comment by Boostrix** [comment]
yes, you would need to apply the same code block that execute_python is currently using - if in doubt, file a proper feature request, I suggested the same thing a couple of days ago due to security reasons here: https://github.com/Significant-Gravitas/Auto-GPT/pull/3713#issuecomment-1537380759

the code exists already in a different place, so this would be a simple and logical change (also applies to supporting chroot based restrictions)
