### ISSUE TITLE
有没有中文交流群

### ISSUE THREAD

**Issue by dlaoba** [Significant-Gravitas/Auto-GPT#1561]
不怎么会用，找个群一起讨论一下

**Comment by qoo7972365** [comment]
加我TG @qoo7972365

**Comment by Yu-Linbo** [comment]
+1

**Comment by qoo7972365** [comment]
https://t.me/+MMugMAcGIBFmMGY1

**Comment by calcitem** [comment]
顺利跑完了一个任务，小结几条遇到的问题和解决方式：

* pip安装包时，出现的警告一定要消除干净，否则因为一些依赖关系没搞好所以执行出错。
* 配置文件里，执行本地command的权限需要打开；
* 涉及文件名，不能用绝对路径，所有文件需要在 workspace 的相对路径下。就是不能跑到 workspace外面执行，在workspace里面的，用绝对路径也不行。
* 一遇到问题就可以考虑在 Input:  提示符下输入 `I specifically asked you to send response in the JSON format I asked, please fix your response and send in the format I want without adding anything, my prompt was: [INSERT PREVIOUS PROMPT]`， 这样很多时候就活过来了。千万不要用 n，这就会退出，前功尽弃。
* `stable` 分支上，发现抓网页是很容易崩溃退出，前功尽弃，`master` 分支上，跳出来google chrome后还会自己翻页，master改为从chrome读取网页内容，就稳定多了。master会多装几个包。
* 不要读取太大的文件，这样 token 太大。
* auto-gpt.json 会越来越大，这个文件记录了思考的过程，很有用，建议备份。
* 尽量不用中文，用英文，生成的材料再自己翻译。
* 不建议用continuous模式启动，除非很简单的任务，复杂的任务中途经常需要纠偏。一次性不要让它跑太多，N不要设置太大，这样每隔一段时间停下来后观察出现什么问题，就在 Input: 这里输入一些提示语纠偏。有个 Input: 提示符吗？就是在那里输入提示，不用输入太多，输入太多了 AI 不认识，点到为止。

**Comment by nponeccop** [comment]
这是一篇很好的总结。我们可以把它放在某个地方吗？

**Comment by calcitem** [comment]
> 这是一篇很好的总结。我们可以把它放在某个地方吗？

Thank you for your kind words! We can certainly consider placing this summary somewhere accessible. However, please keep in mind that some of the solutions mentioned here might be temporary workarounds. My understanding of the documentation may be limited, and a more in-depth understanding could require official explanations from the author. Nonetheless, this summary can still serve as a helpful starting point for others facing similar issues.

**Comment by elvis1121** [comment]
@calcitem 你好，可以请教下这个问题吗，不是研发实在不太理解这个报错
每次运行都会提示这样的问题

```
Traceback (most recent call last):
  File "/Users/elvis/Documents/AGI/Auto-GPT/scripts/main.py", line 441, in <module>
    main()
  File "/Users/elvis/Documents/AGI/Auto-GPT/scripts/main.py", line 304, in main
    agent.start_interaction_loop()
  File "/Users/elvis/Documents/AGI/Auto-GPT/scripts/main.py", line 345, in start_interaction_loop
    assistant_reply = chat.chat_with_ai(
                      ^^^^^^^^^^^^^^^^^^
  File "/Users/elvis/Documents/AGI/Auto-GPT/scripts/chat.py", line 126, in chat_with_ai
    assistant_reply = create_chat_completion(
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/elvis/Documents/AGI/Auto-GPT/scripts/llm_utils.py", line 50, in create_chat_completion
    raise RuntimeError("Failed to get response after 5 retries")
RuntimeError: Failed to get response after 5 retries
```

是不是因为terminal没有代理网络？尝试在terminal ping chat.openai.com，也是timeout的状态

**Comment by calcitem** [comment]
> 是不是因为terminal没有代理网络？尝试在terminal ping chat.openai.com，也是timeout的状态

是的。服务器防火墙防 ping，用 ping 检测连通性意义不大。

**Comment by elvis1121** [comment]
@calcitem 十分十分感激您的回复，这是个可以解决的问题吗，可不可以耽误你的时间介绍下解决思路呀 🙏🏻🙏🏻🙏🏻

**Comment by youyongba** [comment]
调api, 是不是得给openai充值才行，不然autogpt就一直思考

**Comment by calcitem** [comment]
> @calcitem 十分十分感激您的回复，这是个可以解决的问题吗，可不可以耽误你的时间介绍下解决思路呀 🙏🏻🙏🏻🙏🏻

Thank you for your question. Unfortunately, GitHub is not an appropriate platform for discussing methods to bypass internet restrictions. Engaging in such discussions on GitHub may result in stricter scrutiny and restrictions on the platform, affecting the experience of many other users. In order to respect GitHub's community guidelines and maintain a healthy technical exchange environment, I am unable to provide any solutions related to this issue here. I kindly ask for your understanding and encourage you to seek assistance through other appropriate channels. Wishing you all the best!

**Comment by elvis1121** [comment]
> > @calcitem 十分十分感激您的回复，这是个可以解决的问题吗，可不可以耽误你的时间介绍下解决思路呀 🙏🏻🙏🏻🙏🏻
> 
> Thank you for your question. Unfortunately, GitHub is not an appropriate platform for discussing methods to bypass internet restrictions. Engaging in such discussions on GitHub may result in stricter scrutiny and restrictions on the platform, affecting the experience of many other users. In order to respect GitHub's community guidelines and maintain a healthy technical exchange environment, I am unable to provide any solutions related to this issue here. I kindly ask for your understanding and encourage you to seek assistance through other appropriate channels. Wishing you all the best!

Whatever, really thank you
Best wishes

**Comment by kaili-yang** [comment]
刚新建了一个 Discord 频道，不限于 Auto-gpt，还有其他AI技术交流，求职，面试等信息欢迎加入
https://discord.gg/CK82yNuK

**Comment by chen5211314** [comment]
> 不怎么会用，找个群一起讨论一下

有200人大群加我微信13161558658我拉你

**Comment by qq641101978** [comment]
> 刚新建了一个 Discord 频道，不限于 Auto-gpt，还有其他AI技术交流，求职，面试等信息欢迎加入 https://discord.gg/CK82yNuK



> 刚新建了一个 Discord 频道，不限于 Auto-gpt，还有其他AI技术交流，求职，面试等信息欢迎加入 https://discord.gg/CK82yNuK

过期了。能重新分享下吗，感谢

**Comment by qq641101978** [comment]
> 刚新建了一个 Discord 频道，不限于 Auto-gpt，还有其他AI技术交流，求职，面试等信息欢迎加入 https://discord.gg/CK82yNuK

过期了。能重新分享下吗，感谢

**Comment by kaili-yang** [comment]
> 
Discord 中文群新链接
https://discord.com/channels/1096872551470346372/1096872552191754272
