### ISSUE TITLE
Supporting different languages

### ISSUE THREAD

**Issue by nponeccop** [Significant-Gravitas/Auto-GPT#1563]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

A few persons asked for a guide to porting ChatGPT to speak and think in Chinese, but I guess it applies to other languages as well. I personally can supervise Spanish and Ukrainian.

Note that there is a different task of changing the UI to be in other languages. This task is only about the replacement of core prompts.

What we need is fully engineered prompts in different languages, and the ability to select between them.

So, the goal of this issue is to prepare a guide and a code framework for such porting.

### Examples 🌈

You can end your goals with "speak in Spanish", and I guess there were some language flags as well

### Motivation 🔦

ChatGPT speaks many natural and artificial languages, and it speaks popular languages speaks pretty well. So getting Chinese, Spanish, Hindi, and Arabic support is essential in order for the project to get more testers and contributors.

Or any other relatively popular languages as I guess "what do you mean by Chinese" is a valid question.

**Comment by RiteshK-611** [comment]
I would like to help.
I can help adding Hindi support.

**Comment by nponeccop** [comment]
I guess you can get us the prompt, and then we integrate it. But for now we need to extract the language-specific parts and move into configs

**Comment by Jun10ng** [comment]
https://github.com/Significant-Gravitas/Auto-GPT/issues/1629

hi. @nponeccop Here are my thinks about multi-language.
We can add search in multi-language first.

**Comment by abel9851** [comment]
could i help?
i can help korean support.

**Comment by kaiboesefeldt** [comment]
Hi there!

I would be more than happy to help you with the German language and development tasks. As I noticed that this issue has been labeled as a "good first issue," I would love to dedicate a few hours of my free time each week to working on it.

I understand that this issue also requires some discussion. Here are my thoughts on the requirements:

1. The language of the prompts and outputs should be customizable.
2. Multiple languages should be supported.
3. For each supported language, there should be a file in YAML format that contains prompt snippets and templates in the respective language.
4. These files should be stored in a designated folder.
5. The actual language used will be defined in the .env file, with English as the default.

Regarding the technical implementation, it appears that the text parts of the prompts are spread across the codebase. Therefore, it would make sense to identify them and provide them in a central location as a first step. Then, the prompt parts would be transferred to a YAML file with the language abbreviation in its name (e.g., prompt-de-de.yaml). Finally, the prompt file that corresponds to the configuration in the .env file will be read.

What do you think about my suggestions?

As for the next steps, I'm not quite sure how I can contact the active contributors to this project, aside from submitting issues and pull requests. Would it be best for me to post a PR for an implementation? Please let me know.

Thank you!

**Comment by PalAditya** [comment]
> Hi there!
> 
> I would be more than happy to help you with the German language and development tasks. As I noticed that this issue has been labeled as a "good first issue," I would love to dedicate a few hours of my free time each week to working on it.
> 
> I understand that this issue also requires some discussion. Here are my thoughts on the requirements:
> 
> 1. The language of the prompts and outputs should be customizable.
> 2. Multiple languages should be supported.
> 3. For each supported language, there should be a file in YAML format that contains prompt snippets and templates in the respective language.
> 4. These files should be stored in a designated folder.
> 5. The actual language used will be defined in the .env file, with English as the default.
> 
> Regarding the technical implementation, it appears that the text parts of the prompts are spread across the codebase. Therefore, it would make sense to identify them and provide them in a central location as a first step. Then, the prompt parts would be transferred to a YAML file with the language abbreviation in its name (e.g., prompt-de-de.yaml). Finally, the prompt file that corresponds to the configuration in the .env file will be read.
> 
> What do you think about my suggestions?
> 
> As for the next steps, I'm not quite sure how I can contact the active contributors to this project, aside from submitting issues and pull requests. Would it be best for me to post a PR for an implementation? Please let me know.
> 
> Thank you!

+1. Would like to help with the same, and if just language support is needed (customizing prompts), I can help add Bengali support 😄

**Comment by muhamrif** [comment]
I would like to help adding Urdu Language support on it, if approved. Thankyou!

**Comment by derekamsterdam** [comment]
> Hi, I can help for the french version. It would be great to have a guide of the application architecture. I think there are two main topics :
> 
> * internationalize the tool --> not very relevant
> * internationalize searches and outputs of the application --> very relevant

Hi there, I will glady help out for the french part of it also

**Comment by arthuRHD** [comment]
Hi, I'm available as a French reviewer if needed.

**Comment by minfenglu** [comment]
Hi, I would like to help adding Chinese support.

**Comment by VectorZhao** [comment]
> 中文的支持可以参考如下： 找到 `autogpt/llm/llm_utils.py` 并加入以下代码。
> 
> ```python
>     ...
>     language: Message = {
>         "role": "system",
>         "content": "Your answer must use Chinese.",
>     }
> 
>     messages.append(language)
>     
>     for plugin in cfg.plugins:
>     ....
> ```
> 
> <img alt="WechatIMG247" width="1512" src="https://user-images.githubusercontent.com/10987707/236262112-82bfa51d-b728-477c-b8d9-47b61370998a.png">

nice，但是不够优雅。可以考虑加入chinese plugin支持。

**Comment by kaiboesefeldt** [comment]
Hello there! I hope you're having a great day so far. I just wanted to let you know that I've been working on this project and I'm excited to share my progress with you. You can find my latest updates in my cloned repository at https://github.com/kaiboesefeldt/Auto-GPT/tree/1563-supporting-different-languages.

I'm facing some challenges with the prompt fragments being spread over multiple parts of the code, as well as issues with plugins having to handle i18n themselves. Additionally, I'm wondering if translating the entire prompt is really necessary or if the approach suggested by @VectorZhao (simply instructing the AI to respond in a specific language) would be simpler and just as effective.

If you have any suggestions or feedback, I would be grateful to hear it. Thank you for your time and support!

**Comment by kaiboesefeldt** [comment]
One key file is [prompts_en.yaml](https://github.com/kaiboesefeldt/Auto-GPT/blob/1563-supporting-different-languages/i18n/prompts/prompts_en.yaml), which contains all the prompt templates and snippets I collected so far. The concept is to have such a file for every supported language. So supporting another language would mean to copy prompts_en.yaml to e.g. prompts_zh.yaml and translate all prompt snippets and templates.

**Comment by pablorq** [comment]
I guess that could be more simple to dynamically select the used language from the terminal itself.

Maybe a "Language" configuration can be added to define that on every task, like:

```
Name:
Role:
Language: es
Goal:
```

Leaving empty the "Language" is set to default (en).

**Comment by Boostrix** [comment]
Please see the comments regarding a feature to support dedicate "prompt profiles" so that people can experiment with different prompt profiles without stepping on anyone's toes: https://github.com/Significant-Gravitas/Auto-GPT/pull/1874

**Comment by anonhostpi** [comment]
also see #471

**Comment by sameehj** [comment]
Arabic support is needed. I'm available as a reviewer for Arabic if needed.

**Comment by Boostrix** [comment]
- #3954

**Comment by yavuzibr** [comment]
I can help with Turkish if it needs.

**Comment by sudip550** [comment]
I need in italian, can anyone help??

**Comment by johnfelipe** [comment]
help me with spanish

**Comment by kaiboesefeldt** [comment]
I think I will stop working on this issue as my approach seems to be too complicated, because:

- Every other developer would have to remember not to simply add new prompt parts, but always also provide them through the central mechanism
- Adding a new prompt part would mean also to add new translations for that part in all supported languages
- Handling of modules is not well covered.

**Comment by ilantnt** [comment]
I can try help you with covering the missing parts + adding translation in Hebrew language. 
Do you need any help @kaiboesefeldt ?
