### ISSUE TITLE
Pinecone 

### ISSUE THREAD

**Issue by james34roberts** [Significant-Gravitas/Auto-GPT#1571]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

I’m still new. Do I have to set up money to pay to Pinecone in order to use their API? It’s saying I’ve exceeded my API limits. 

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by YifeiY** [comment]
There are limits to pinecones rates. Please see here. https://docs.pinecone.io/docs/limits
