### ISSUE TITLE
program stuck

### ISSUE THREAD

**Issue by qwe2950531** [Significant-Gravitas/Auto-GPT#1573]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

REASONING:  I need to create a new Vue.js project in order to complete my task of creating a red-themed website.
PLAN: 
-  Use the `vue create` command to create a new project with the name `my_project`.
-  Specify any necessary options or preferences when creating the project.
-  Wait for the project to be created.
CRITICISM:  I need to remember to stay organized and efficient as I work through this project.
Attempting to fix JSON by finding outermost brackets
Apparently json was fixed. 
NEXT ACTION:  COMMAND = execute_shell ARGUMENTS = {'command_line': 'vue create my_project'}
Executing command 'vue create my_project' in working directory 'D:\work\projects\ai-relate\Auto-GPT-master\Auto-GPT-master\auto_gpt_workspace'

### Current behavior 😯

i want autogpt help me to autobuild vue-project but did't work,have any ideas?

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by MrUzbek00** [comment]
Hello everyone I have the same problem 

Cannot run - python -m autogpt

And getting this error

Warning: The file 'auto-gpt.json' does not exist.Local memory would not be saved to a file.
Please set your OpenAI API key in .env or as an environment variable.
You can get your key from https://beta.openai.com/account/api-keys

But I have OpenAI API Key (not GPT-4)

Could you help me, please?

**Comment by hiteshpatwari** [comment]
Seems like a widespread problem, as it is getting stuck for my nextJS project

```
PLAN:
-  Create a new NextJS project and install Material UI.\\\\n- Set up the database schema and authentication mechanism to ensure the website is secure.
CRITICISM:  I need to ensure that I am following best practices and that the website is secure.
Attempting to fix JSON by finding outermost brackets
Apparently json was fixed.
NEXT ACTION:  COMMAND = execute_shell ARGUMENTS = {'command_line': 'npx create-next-app my-app'}
Executing command 'npx create-next-app my-app' in working directory 'C:\workspace\Auto-GPT\auto_gpt_workspace'
```

**Comment by hiteshpatwari** [comment]
Okay, seems like the issue is that nowadays, all `create-x-app` requires user prompts to select the options, and Auto-gpt is not able to display it for user input. Two ways to solve the problem:

1. If a shell command is being executed and requires user input, AUtoGPT let the user decide what to select. so Auto-gpt relenquishes control for few minutes until the process does not require user input.
2. Auto-GPT interprets shell command prompts and acts as a mediator.

**Comment by Qoyyuum** [comment]
Hi @hiteshpatwari @qwe2950531 can either of you confirm what is been set in your `.env` for `EXECUTE_LOCAL_COMMANDS`?

**Comment by hiteshpatwari** [comment]
It is set to true. Of set to `false` autogpt will error out.

**Comment by schellenbergk** [comment]
Same here.
`EXECUTE_LOCAL_COMMANDS=True`

Stuck on:
```
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
Executing command 'npx create-next-app' in working directory './auto_gpt_workspace'
```

**Comment by fysoul17** [comment]
Same here. Stuck.

`EXECUTE_LOCAL_COMMANDS=True`
```
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
Executing command 'npx create-next-app' in working directory './auto_gpt_workspace'
```

**Comment by 3265** [comment]
I encountered the same error as you did. 
In my case, I made a modification to `/Auto-GPT/autogpt/config/config.py` as follows:

```python
dotenv_path = Path(__file__).parent.parent.parent / ".env"
print("_____dotenv_path _______", dotenv_path)
load_dotenv(dotenv_path, verbose=True, override=True)
```


After making this change, the command 

```bash
$ PYTHONPATH=. python -m autogpt --gpt3only
```

worked successfully.
