### ISSUE TITLE
Auto-GPT/autogpt/json_fixes/auto_fix.py", line 24, in fix_json   CFG missing

### ISSUE THREAD

**Issue by twajothi** [Significant-Gravitas/Auto-GPT#1575]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

It occurred when json fix was cold 

### Current behavior 😯

Auto-GPT/autogpt/json_fixes/auto_fix.py", line 24, in fix_json
    function_string, args, description_string, model=cfg.fast_llm_model
NameError: name 'cfg' is not defined

### Expected behavior 🤔

simple import will solve it 

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Qoyyuum** [comment]
Hi @twajothi how did you get this error?
