### ISSUE TITLE
TypeError: 'type' object is not subscriptable when i run python -m autogpt

### ISSUE THREAD

**Issue by SpLakeb** [Significant-Gravitas/Auto-GPT#1593]
when i run “python -m autogpt” ， it occurs  TypeError: 'type' object is not subscriptable

**Comment by smendig** [comment]
> when i run “python -m autogpt” ， it occurs TypeError: 'type' object is not subscriptable

Fixed by https://github.com/Significant-Gravitas/Auto-GPT/pull/1580

**Comment by SpLakeb** [comment]
thanks， i got it
