### ISSUE TITLE
Tool that return list of Tools that could possibly be used to solve a Problem

### ISSUE THREAD

**Issue by thepok** [Significant-Gravitas/Auto-GPT#160]
Currently the list of available tools is allways in the promp, and it will grow. So let GTP make a Pre selection. The Main loop could than better concentrate on the problem at hand. Some allways goot to have tools could stay in promp, but generaly the loop should be:

GetTools("Problem description")

->tool1 tool2 tool3

Try to solve Problem with ToolX

**Comment by Pwuts** [comment]
Related: #56

**Comment by Boostrix** [comment]
> Closing as duplicate of #56

I am not sure whether that's the "same" as #56. #56 seems to be focused in discovering/exploring web APIs, whereas this one seems to be more confined to local capabilities like shell commands / CLI tools ?

I do see how the top-level heuristics might be heavily overlapping - but from a functional standpoint, it seems to be more related to exploring "local tool capabilities", which is something that I recently tinkered with as part of: https://github.com/Significant-Gravitas/Auto-GPT/issues/2987#issuecomment-1531131136

Exploring a web API has different problems/costs associated with it in comparison to exploring local tooling.

However, in the light of people tinkering with the idea of exposing a ton of functionality to Auto-GPT, there also remains the issue of cluttering up the context window with "options" - in other words, there would need be some form of "dynamic tool offerings" or at the very least categories of tools, based on local availability - as mentioned here: https://github.com/Significant-Gravitas/Auto-GPT/issues/3686#issuecomment-1531402699  

Some food for thought ...
