### ISSUE TITLE
Create cache for already browse and summarized website.

### ISSUE THREAD

**Issue by amauryfischer** [Significant-Gravitas/Auto-GPT#161]
It seems that Auto-GPT is going multiple time on same website.
Maybe we could add a system so when a website is summarize, this is added as a key : website url value : summarize content
So this cache would be use in case the AI try to fetch again the same website.

This would allow to use much less token.

**Comment by amauryfischer** [comment]
i have a first draft here : https://github.com/Torantulino/Auto-GPT/pull/163 but its work in progress

**Comment by Pwuts** [comment]
Closing as duplicate of #114
