### ISSUE TITLE
SYSTEM:  Command execute_python_file returned: Error: Invalid file type. Only .py files are allowed.

### ISSUE THREAD

**Issue by raymerjacque** [Significant-Gravitas/Auto-GPT#1622]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

STOCK-CHECK-AI THOUGHTS:  The Stock-Script-Agent has provided us with a Python script to analyze the financial data and give us a list of recommended stocks. Let's execute the script and write the recommendations to a file for future reference.
REASONING:  Executing the script and writing the recommendations to a file ensures that we can use the information later and that we don't have to run the script every time we want to access the recommendations. We can also update the script in the future if we want to change the time period being analyzed or the rolling average window used.
PLAN:
-  Use the 'execute_python_file' command to execute the Python script provided by the Stock-Script-Agent
-  Use the 'write_to_file' command to save the recommendations to a text file
CRITICISM:  We should check the output of the script to make sure it is accurately identifying the stocks that are trending upwards in the market. We also need to ensure that we only use reliable financial data when making investment decisions.
Attempting to fix JSON by finding outermost brackets
Apparently json was fixed. 
NEXT ACTION:  COMMAND = execute_python_file ARGUMENTS = {'file': '<file_path_to_python_script>'}
Executing file '<file_path_to_python_script>' in workspace 'auto_gpt_workspace'
SYSTEM:  Command execute_python_file returned: Error: Invalid file type. Only .py files are allowed.
STOCK-CHECK-AI THOUGHTS:  We need to revise our previous command, and execute the correct Python script provided by the Stock-Script-Agent. Once we have received the recommendations, we can use the 'write_to_file' command to store them for future reference.
REASONING:  By running the correct Python script and storing the output, we ensure that we can quickly refer to the recommendations and know which stocks we should consider investing in. This is crucial in ensuring that we do not waste time and that we make sound investment decisions.
PLAN:
-  Use the 'execute_python_file' command to execute the Python script provided by the Stock-Script-Agent\n- Use the 'write_to_file' command to save the recommendations to a text file
CRITICISM:  We should ensure that the financial data being used is reliable and up to date. Additionally, it is important for us to download the recommended reports periodically and evaluate the performance of the recommended stocks to confirm that the recommendations are reliable and the stocks are performing as expected.
Attempting to fix JSON by finding outermost brackets
Apparently json was fixed.
NEXT ACTION:  COMMAND = execute_python_file ARGUMENTS = {'file': '<file_path_to_correct_python_script>'}
Executing file '<file_path_to_correct_python_script>' in workspace 'auto_gpt_workspace'
SYSTEM:  Command execute_python_file returned: Error: Invalid file type. Only .py files are allowed.

### Current behavior 😯

STOCK-CHECK-AI THOUGHTS:  The Stock-Script-Agent has provided us with a Python script to analyze the financial data and give us a list of recommended stocks. Let's execute the script and write the recommendations to a file for future reference.
REASONING:  Executing the script and writing the recommendations to a file ensures that we can use the information later and that we don't have to run the script every time we want to access the recommendations. We can also update the script in the future if we want to change the time period being analyzed or the rolling average window used.
PLAN:
-  Use the 'execute_python_file' command to execute the Python script provided by the Stock-Script-Agent
-  Use the 'write_to_file' command to save the recommendations to a text file
CRITICISM:  We should check the output of the script to make sure it is accurately identifying the stocks that are trending upwards in the market. We also need to ensure that we only use reliable financial data when making investment decisions.
Attempting to fix JSON by finding outermost brackets
Apparently json was fixed. 
NEXT ACTION:  COMMAND = execute_python_file ARGUMENTS = {'file': '<file_path_to_python_script>'}
Executing file '<file_path_to_python_script>' in workspace 'auto_gpt_workspace'
SYSTEM:  Command execute_python_file returned: Error: Invalid file type. Only .py files are allowed.
STOCK-CHECK-AI THOUGHTS:  We need to revise our previous command, and execute the correct Python script provided by the Stock-Script-Agent. Once we have received the recommendations, we can use the 'write_to_file' command to store them for future reference.
REASONING:  By running the correct Python script and storing the output, we ensure that we can quickly refer to the recommendations and know which stocks we should consider investing in. This is crucial in ensuring that we do not waste time and that we make sound investment decisions.
PLAN:
-  Use the 'execute_python_file' command to execute the Python script provided by the Stock-Script-Agent\n- Use the 'write_to_file' command to save the recommendations to a text file
CRITICISM:  We should ensure that the financial data being used is reliable and up to date. Additionally, it is important for us to download the recommended reports periodically and evaluate the performance of the recommended stocks to confirm that the recommendations are reliable and the stocks are performing as expected.
Attempting to fix JSON by finding outermost brackets
Apparently json was fixed.
NEXT ACTION:  COMMAND = execute_python_file ARGUMENTS = {'file': '<file_path_to_correct_python_script>'}
Executing file '<file_path_to_correct_python_script>' in workspace 'auto_gpt_workspace'
SYSTEM:  Command execute_python_file returned: Error: Invalid file type. Only .py files are allowed.

### Expected behavior 🤔

it should be saving the python file.

### Your prompt 📝

```yaml
# Paste your prompt here
```
STOCK-CHECK-AI THOUGHTS:  The Stock-Script-Agent has provided us with a Python script to analyze the financial data and give us a list of recommended stocks. Let's execute the script and write the recommendations to a file for future reference.
REASONING:  Executing the script and writing the recommendations to a file ensures that we can use the information later and that we don't have to run the script every time we want to access the recommendations. We can also update the script in the future if we want to change the time period being analyzed or the rolling average window used.
PLAN:
-  Use the 'execute_python_file' command to execute the Python script provided by the Stock-Script-Agent
-  Use the 'write_to_file' command to save the recommendations to a text file
CRITICISM:  We should check the output of the script to make sure it is accurately identifying the stocks that are trending upwards in the market. We also need to ensure that we only use reliable financial data when making investment decisions.
Attempting to fix JSON by finding outermost brackets
Apparently json was fixed. 
NEXT ACTION:  COMMAND = execute_python_file ARGUMENTS = {'file': '<file_path_to_python_script>'}
Executing file '<file_path_to_python_script>' in workspace 'auto_gpt_workspace'
SYSTEM:  Command execute_python_file returned: Error: Invalid file type. Only .py files are allowed.
STOCK-CHECK-AI THOUGHTS:  We need to revise our previous command, and execute the correct Python script provided by the Stock-Script-Agent. Once we have received the recommendations, we can use the 'write_to_file' command to store them for future reference.
REASONING:  By running the correct Python script and storing the output, we ensure that we can quickly refer to the recommendations and know which stocks we should consider investing in. This is crucial in ensuring that we do not waste time and that we make sound investment decisions.
PLAN:
-  Use the 'execute_python_file' command to execute the Python script provided by the Stock-Script-Agent\n- Use the 'write_to_file' command to save the recommendations to a text file
CRITICISM:  We should ensure that the financial data being used is reliable and up to date. Additionally, it is important for us to download the recommended reports periodically and evaluate the performance of the recommended stocks to confirm that the recommendations are reliable and the stocks are performing as expected.
Attempting to fix JSON by finding outermost brackets
Apparently json was fixed.
NEXT ACTION:  COMMAND = execute_python_file ARGUMENTS = {'file': '<file_path_to_correct_python_script>'}
Executing file '<file_path_to_correct_python_script>' in workspace 'auto_gpt_workspace'
SYSTEM:  Command execute_python_file returned: Error: Invalid file type. Only .py files are allowed.

**Comment by aicayzer** [comment]
You need to enable the following in the `.env` file:
```
## EXECUTE_LOCAL_COMMANDS - Allow local command execution (Default: False)
## RESTRICT_TO_WORKSPACE - Restrict file operations to workspace ./auto_gpt_workspace (Default: True)
EXECUTE_LOCAL_COMMANDS=True
# RESTRICT_TO_WORKSPACE=False 
```
if you want, you can also allow commands beyond your workspace by removing that commented out line too
