### ISSUE TITLE
How can Auo-GPT read the specific file in my computer?

### ISSUE THREAD

**Issue by lorenelhuang** [Significant-Gravitas/Auto-GPT#1626]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

I wanna ask Auto-GPT to read a txt file in my computer. But it cannot read it.

How can Auto-GPT read the specific file in my computer? Shall I give it a assigned format file? Or shall I tell it specific promt?

I am using Win 10 with Git bash.

**Comment by zajerao** [comment]
Same question for MacOS. I asked it to read a given filepath but got ignored.

**Comment by MarcoV10** [comment]
Can you save it in the "auto_gpt_workspace" folder?, it will read the file directly

**Comment by z-x-x136** [comment]
> 你能把它保存在“auto_gpt_workspace”文件夹中吗？它会直接读取文件

Will it read files directly if you save them in the "auto_gpt_workspace" folder

**Comment by ntindle** [comment]
Sometimes it executes something unexpected or doesn’t do what you want.  Check out the #prompt-engineering channel in discord to get a better fit prompt
