### ISSUE TITLE
can not install success

### ISSUE THREAD

**Issue by brisk21** [Significant-Gravitas/Auto-GPT#1627]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

PS D:\temp\Auto-GPT> pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
WARNING: Ignoring invalid distribution -ip (d:\program files\python38\lib\site-packages)
Collecting beautifulsoup4 (from -r requirements.txt (line 1))
  Using cached beautifulsoup4-4.12.2-py3-none-any.whl (142 kB)
Collecting colorama==0.4.6 (from -r requirements.txt (line 2))
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting openai==0.27.2 (from -r requirements.txt (line 3))
  Using cached openai-0.27.2-py3-none-any.whl (70 kB)
Collecting playsound==1.2.2 (from -r requirements.txt (line 4))
  Using cached playsound-1.2.2-py2.py3-none-any.whl (6.0 kB)
Collecting python-dotenv==1.0.0 (from -r requirements.txt (line 5))
  Using cached python_dotenv-1.0.0-py3-none-any.whl (19 kB)
Collecting pyyaml==6.0 (from -r requirements.txt (line 6))
  Using cached PyYAML-6.0-cp38-cp38-win32.whl (140 kB)
Collecting readability-lxml==0.8.1 (from -r requirements.txt (line 7))
  Using cached readability_lxml-0.8.1-py3-none-any.whl (20 kB)
Collecting requests (from -r requirements.txt (line 8))
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Collecting tiktoken==0.3.3 (from -r requirements.txt (line 9))
  Using cached tiktoken-0.3.3.tar.gz (25 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting gTTS==2.3.1 (from -r requirements.txt (line 10))
  Using cached gTTS-2.3.1-py3-none-any.whl (28 kB)
Collecting docker (from -r requirements.txt (line 11))
  Using cached docker-6.0.1-py3-none-any.whl (147 kB)
Collecting duckduckgo-search (from -r requirements.txt (line 12))
  Using cached duckduckgo_search-2.8.6-py3-none-any.whl (30 kB)
Collecting google-api-python-client (from -r requirements.txt (line 13))
  Using cached google_api_python_client-2.85.0-py2.py3-none-any.whl (11.2 MB)
Collecting pinecone-client==2.2.1 (from -r requirements.txt (line 14))
  Using cached pinecone_client-2.2.1-py3-none-any.whl (177 kB)
Collecting redis (from -r requirements.txt (line 15))
  Using cached redis-4.5.4-py3-none-any.whl (238 kB)
Collecting orjson (from -r requirements.txt (line 16))
  Using cached orjson-3.8.10.tar.gz (836 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
          Updating crates.io index
      warning: spurious network error (2 tries remaining): failed to send request: 鎿嶄綔瓒呮椂
      ; class=Os (2)
      warning: spurious network error (1 tries remaining): failed to send request: 鎿嶄綔瓒呮椂
      ; class=Os (2)
      error: failed to get `pyo3-ffi` as a dependency of package `orjson v3.8.10 (C:\Users\wbs\AppData\Local\Temp\pip-install-bvxukw44\orjson_4505a6de786d4595805cdbd567919ee4)`

      Caused by:
        failed to load source for dependency `pyo3-ffi`

      Caused by:
        Unable to update registry `crates-io`

      Caused by:
        failed to fetch `https://github.com/rust-lang/crates.io-index`

      Caused by:
        failed to send request: 鎿嶄綔瓒呮椂
        ; class=Os (2)
      馃挜 maturin failed
        Caused by: Cargo metadata failed. Does your crate compile with `cargo build`?
        Caused by: `cargo metadata` exited with an error:
      Error running maturin: Command '['maturin', 'pep517', 'write-dist-info', '--metadata-directory', 'C:\\Users\\wbs\\AppData\\Local\\Temp\\pip-modern-metadata-t4y2s2ee', '--interpreter', 'd:\\program files\\python38\\python.exe', '--target', 'i686-pc-windows-msvc']' returned non-zero exit status 1.
      Checking for Rust toolchain....
      Running `maturin pep517 write-dist-info --metadata-directory C:\Users\wbs\AppData\Local\Temp\pip-modern-metadata-t4y2s2ee --interpreter d:\program files\python38\python.exe --target i686-pc-windows-msvc`
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

### Current behavior 😯

PS D:\temp\Auto-GPT> pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
WARNING: Ignoring invalid distribution -ip (d:\program files\python38\lib\site-packages)
Collecting beautifulsoup4 (from -r requirements.txt (line 1))
  Using cached beautifulsoup4-4.12.2-py3-none-any.whl (142 kB)
Collecting colorama==0.4.6 (from -r requirements.txt (line 2))
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting openai==0.27.2 (from -r requirements.txt (line 3))
  Using cached openai-0.27.2-py3-none-any.whl (70 kB)
Collecting playsound==1.2.2 (from -r requirements.txt (line 4))
  Using cached playsound-1.2.2-py2.py3-none-any.whl (6.0 kB)
Collecting python-dotenv==1.0.0 (from -r requirements.txt (line 5))
  Using cached python_dotenv-1.0.0-py3-none-any.whl (19 kB)
Collecting pyyaml==6.0 (from -r requirements.txt (line 6))
  Using cached PyYAML-6.0-cp38-cp38-win32.whl (140 kB)
Collecting readability-lxml==0.8.1 (from -r requirements.txt (line 7))
  Using cached readability_lxml-0.8.1-py3-none-any.whl (20 kB)
Collecting requests (from -r requirements.txt (line 8))
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Collecting tiktoken==0.3.3 (from -r requirements.txt (line 9))
  Using cached tiktoken-0.3.3.tar.gz (25 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting gTTS==2.3.1 (from -r requirements.txt (line 10))
  Using cached gTTS-2.3.1-py3-none-any.whl (28 kB)
Collecting docker (from -r requirements.txt (line 11))
  Using cached docker-6.0.1-py3-none-any.whl (147 kB)
Collecting duckduckgo-search (from -r requirements.txt (line 12))
  Using cached duckduckgo_search-2.8.6-py3-none-any.whl (30 kB)
Collecting google-api-python-client (from -r requirements.txt (line 13))
  Using cached google_api_python_client-2.85.0-py2.py3-none-any.whl (11.2 MB)
Collecting pinecone-client==2.2.1 (from -r requirements.txt (line 14))
  Using cached pinecone_client-2.2.1-py3-none-any.whl (177 kB)
Collecting redis (from -r requirements.txt (line 15))
  Using cached redis-4.5.4-py3-none-any.whl (238 kB)
Collecting orjson (from -r requirements.txt (line 16))
  Using cached orjson-3.8.10.tar.gz (836 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
          Updating crates.io index
      warning: spurious network error (2 tries remaining): failed to send request: 鎿嶄綔瓒呮椂
      ; class=Os (2)
      warning: spurious network error (1 tries remaining): failed to send request: 鎿嶄綔瓒呮椂
      ; class=Os (2)
      error: failed to get `pyo3-ffi` as a dependency of package `orjson v3.8.10 (C:\Users\wbs\AppData\Local\Temp\pip-install-bvxukw44\orjson_4505a6de786d4595805cdbd567919ee4)`

      Caused by:
        failed to load source for dependency `pyo3-ffi`

      Caused by:
        Unable to update registry `crates-io`

      Caused by:
        failed to fetch `https://github.com/rust-lang/crates.io-index`

      Caused by:
        failed to send request: 鎿嶄綔瓒呮椂
        ; class=Os (2)
      馃挜 maturin failed
        Caused by: Cargo metadata failed. Does your crate compile with `cargo build`?
        Caused by: `cargo metadata` exited with an error:
      Error running maturin: Command '['maturin', 'pep517', 'write-dist-info', '--metadata-directory', 'C:\\Users\\wbs\\AppData\\Local\\Temp\\pip-modern-metadata-t4y2s2ee', '--interpreter', 'd:\\program files\\python38\\python.exe', '--target', 'i686-pc-windows-msvc']' returned non-zero exit status 1.
      Checking for Rust toolchain....
      Running `maturin pep517 write-dist-info --metadata-directory C:\Users\wbs\AppData\Local\Temp\pip-modern-metadata-t4y2s2ee --interpreter d:\program files\python38\python.exe --target i686-pc-windows-msvc`
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Qoyyuum** [comment]
Hi @brisk21 can you try the latest stable release and try again? Also it looks like you can't access certain packages. Can you try it again with a VPN?

**Comment by ntindle** [comment]
Try and use the #tech-support channel in discord for these issues. We don’t have the capacity to help debug in GitHub issues for problems like this
