### ISSUE TITLE
[Feature] Add SEARCH_LANGUAGE_CODE env configuration, support user search google in own language.

### ISSUE THREAD

**Issue by Jun10ng** [Significant-Gravitas/Auto-GPT#1629]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Add SEARCH_LANGUAGE_CODE env configuration, support user search google in own language.

### Examples 🌈

```
# .env
language_code = zh-CN
```

I will add a google translate API call on `google_search`.
```
def google_search(query, num_results=8):
       query = translate_query(query, language_code)
       .....
``` 

### Motivation 🔦

Some information CAN NOT be searched by English on google.

**Comment by andersonlthome** [comment]
Hey @Jun10ng , I did that changing the response from AI, to work with my language. I will fork and PR soon

**Comment by Jun10ng** [comment]
@andersonlthome Hey, I have done it, you can review my PR.

And I found a discussion about the i18n feature, we can talk with masters over there.
https://github.com/Significant-Gravitas/Auto-GPT/issues/1563
