### ISSUE TITLE
Unrelated results 

### ISSUE THREAD

**Issue by UserHIJ** [Significant-Gravitas/Auto-GPT#1632]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

I asked it to help develop a workflow around a specific market and it gave me recommendations on how to ladder a CD. I'd say either I did something wrong or there's something amiss here. 

### Current behavior 😯

wrong results 

### Expected behavior 🤔

I asked for a workflow and some information on scanning websites and it gave me : 
How to Save Money on Energy Bills: Easy and Affordable Solutions

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Qoyyuum** [comment]
Hi @UserHIJ can you copy and paste exactly what your prompt was?

**Comment by UserHIJ** [comment]
autogpt % cat ai_settings.yaml 
ai_goals:
- 'develop a workflow for out important information about xxx competitors '
- 'Building documents to help yyy understand important technical implications '
- 'help predict future strengths in competitive products '
- 'help predict future weaknesses in competitive products '
- 'Help build a program to scan, parse and prioritize competitive information from
  the internet '
ai_name: Jupiter
ai_role: 'here to help me with competitive research about the xxx market '

**Comment by UserHIJ** [comment]
I did redact xxx and yyy .. in case that wasn't clear.

**Comment by UserHIJ** [comment]
Digging in I found this : 
Creating chat completion with model gpt-3.5-turbo, temperature 0.0, max_tokens 3142
Error:  API Bad gateway. Waiting 4 seconds...
Error:  API Bad gateway. Waiting 8 seconds...

I have taken the free key from openai and used it , not paying for it yet. Is that my problem?

**Comment by UserHIJ** [comment]
Closing per 
https://github.com/Significant-Gravitas/Auto-GPT/issues/1599
