### ISSUE TITLE
ERROR: Couldn't read tbsCertificate as SEQUENCE ERROR: Failed parsing Certificate

### ISSUE THREAD

**Issue by Nickonomic** [Significant-Gravitas/Auto-GPT#1636]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

NEXT ACTION:  COMMAND = browse_website ARGUMENTS = {'url': 'https://www.coindesk.com/', 'question': 'current market situation in Bitcoin and Ethereum'}

DevTools listening on ws://127.0.0.1:50539/devtools/browser/d6e426df-2944-4ae2-be46-14829038a165
[12176:6724:0415/194920.727:ERROR:cert_issuer_source_aia.cc(34)] Error parsing cert retrieved from AIA (as DER):
**ERROR: Couldn't read tbsCertificate as SEQUENCE
ERROR: Failed parsing Certificate**

[12176:11356:0415/194930.781:ERROR:device_event_log_impl.cc(222)] [19:49:30.781] USB: usb_device_handle_win.cc:1046 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[12176:11356:0415/194930.782:ERROR:device_event_log_impl.cc(222)] [19:49:30.782] USB: usb_device_handle_win.cc:1046 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by mahaniok** [comment]
Same error here.

**Comment by Vexchan** [comment]
same

**Comment by Mutuo1** [comment]
Same here

**Comment by barclayneira** [comment]
same here

**Comment by LarsHoldgaard** [comment]
Same :-)

**Comment by leobui98** [comment]
same here

**Comment by jaxblack** [comment]
same

**Comment by remivee** [comment]
same here.

**Comment by t0xicfume** [comment]
Same here. How do I get the browser to actually open when the "browse_website" command is used? It the demo video, you ssee chrome actually opens when Auto-GPT invokes the "browse_website" command

**Comment by barclayneira** [comment]
In my case, chrome does open some times but when it tries to navigate the site certificate parsing errors appear as it tries to navigate some pages.

**Comment by AdamGman** [comment]
yes

**Comment by ntindle** [comment]
#1949

**Comment by dodsont** [comment]
same here

**Comment by dauronr** [comment]
same issue running latest stable version

**Comment by azahran007** [comment]
Same

**Comment by anishrajpandey** [comment]
same

**Comment by athagar** [comment]
Same
But was able to get around it with:
`options = webdriver.ChromeOptions()
options.add_experimental_option('excludeSwitches', ['enable-logging'])`

**Comment by mcanabrava** [comment]
same, can't get a workaround with

from selenium import webdriver 
from selenium.webdriver.chrome.service import Service 
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.options import Options

chrome_options = Options()
chrome_options.add_argument("--ignore-certificate-errors")
chrome_options.add_experimental_option('excludeSwitches', ['enable-logging'])
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=chrome_options)
