### ISSUE TITLE
Getting error when trying to work with AutoGpt on Windows 11 with Python 3.10

### ISSUE THREAD

**Issue by Harshitautomation** [Significant-Gravitas/Auto-GPT#1638]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

I am getting below error when trying to execute .

AI Name: mytestgpt

mytestgpt here!  I am at your service.
Describe your AI's role:  For example, 'an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.'
mytestgpt is: Work as a worker to get the latest Automation Job for 10 years of experience in India
Enter up to 5 goals for your AI:  For example: Increase net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously'
Enter nothing to load defaults, enter nothing when finished.
Goal 1: Web scrape the naukri.com for latest JOb in Automation Test
Goal 2: Web scrape linkedln.com for the latest Job in Automation Test
Goal 3:
Using memory of type: LocalCache
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\ChatGPT\Auto-GPT\autogpt\__main__.py", line 572, in <module>
    main()
  File "D:\ChatGPT\Auto-GPT\autogpt\__main__.py", line 396, in main
    agent.start_interaction_loop()
  File "D:\ChatGPT\Auto-GPT\autogpt\__main__.py", line 448, in start_interaction_loop
    assistant_reply = chat.chat_with_ai(
  File "D:\ChatGPT\Auto-GPT\autogpt\chat.py", line 159, in chat_with_ai
    assistant_reply = create_chat_completion(
  File "D:\ChatGPT\Auto-GPT\autogpt\llm_utils.py", line 67, in create_chat_completion
    raise RuntimeError("Failed to get response after 5 retries")
RuntimeError: Failed to get response after 5 retries

Is anyone Facing same issue

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by lologrignola** [comment]
Yep, same error here.
Windows 10 & Python version 3.11.0

**Comment by Qoyyuum** [comment]
Hi @Harshitautomation if you run `python -m autogpt --debug`, does it show `Error: API Rate Limited...`? If so, please set up a paid OpenAI account, regenerate a new OpenAI key and try again.

**Comment by andersonlthome** [comment]
Here I have the Python 3.10.11
and running 
```
python scripts/main.py
```

**Comment by Harshitautomation** [comment]
I am getting Error:  API Rate Limit Reached. Waiting 20 seconds...

**Comment by ntindle** [comment]
Try and use the #tech-support channel in discord for these issues. We don’t have the capacity to help debug in GitHub issues for problems like this
