### ISSUE TITLE
Problem with requirements.txt, missing some dependencies and some bad requirements

### ISSUE THREAD

**Issue by NNTrades** [Significant-Gravitas/Auto-GPT#1652]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

try a new installation 

Windows OS

pip install -r requirements.txt

### Current behavior 😯

I had a problem where i needed a requirement for Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

After installing this and restarting many times it went further in the installation of requirements but got a new error.

`Installing collected packages: sentence_transformers
  DEPRECATION: sentence_transformers is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for sentence_transformers ... error
  error: subprocess-exited-with-error

  × Running setup.py install for sentence_transformers did not run successfully.
  │ exit code: 1
  ╰─> [97 lines of output]
      C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\dist.py:771: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      running install
      C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib
      creating build\lib\sentence_transformers
      copying sentence_transformers\LoggingHandler.py -> build\lib\sentence_transformers
      copying sentence_transformers\model_card_templates.py -> build\lib\sentence_transformers
      copying sentence_transformers\SentenceTransformer.py -> build\lib\sentence_transformers
      copying sentence_transformers\util.py -> build\lib\sentence_transformers
      copying sentence_transformers\__init__.py -> build\lib\sentence_transformers
      creating build\lib\sentence_transformers\cross_encoder
      copying sentence_transformers\cross_encoder\CrossEncoder.py -> build\lib\sentence_transformers\cross_encoder
      copying sentence_transformers\cross_encoder\__init__.py -> build\lib\sentence_transformers\cross_encoder
      creating build\lib\sentence_transformers\datasets
      copying sentence_transformers\datasets\DenoisingAutoEncoderDataset.py -> build\lib\sentence_transformers\datasets
      copying sentence_transformers\datasets\NoDuplicatesDataLoader.py -> build\lib\sentence_transformers\datasets
      copying sentence_transformers\datasets\ParallelSentencesDataset.py -> build\lib\sentence_transformers\datasets
      copying sentence_transformers\datasets\SentenceLabelDataset.py -> build\lib\sentence_transformers\datasets
      copying sentence_transformers\datasets\SentencesDataset.py -> build\lib\sentence_transformers\datasets
      copying sentence_transformers\datasets\__init__.py -> build\lib\sentence_transformers\datasets
      creating build\lib\sentence_transformers\evaluation
      copying sentence_transformers\evaluation\BinaryClassificationEvaluator.py -> build\lib\sentence_transformers\evaluation
      copying sentence_transformers\evaluation\EmbeddingSimilarityEvaluator.py -> build\lib\sentence_transformers\evaluation
      copying sentence_transformers\evaluation\InformationRetrievalEvaluator.py -> build\lib\sentence_transformers\evaluation
      copying sentence_transformers\evaluation\LabelAccuracyEvaluator.py -> build\lib\sentence_transformers\evaluation
      copying sentence_transformers\evaluation\MSEEvaluator.py -> build\lib\sentence_transformers\evaluation
      copying sentence_transformers\evaluation\MSEEvaluatorFromDataFrame.py -> build\lib\sentence_transformers\evaluation
      copying sentence_transformers\evaluation\ParaphraseMiningEvaluator.py -> build\lib\sentence_transformers\evaluation
      copying sentence_transformers\evaluation\RerankingEvaluator.py -> build\lib\sentence_transformers\evaluation
      copying sentence_transformers\evaluation\SentenceEvaluator.py -> build\lib\sentence_transformers\evaluation
      copying sentence_transformers\evaluation\SequentialEvaluator.py -> build\lib\sentence_transformers\evaluation
      copying sentence_transformers\evaluation\SimilarityFunction.py -> build\lib\sentence_transformers\evaluation
      copying sentence_transformers\evaluation\TranslationEvaluator.py -> build\lib\sentence_transformers\evaluation
      copying sentence_transformers\evaluation\TripletEvaluator.py -> build\lib\sentence_transformers\evaluation
      copying sentence_transformers\evaluation\__init__.py -> build\lib\sentence_transformers\evaluation
      creating build\lib\sentence_transformers\losses
      copying sentence_transformers\losses\BatchAllTripletLoss.py -> build\lib\sentence_transformers\losses
      copying sentence_transformers\losses\BatchHardSoftMarginTripletLoss.py -> build\lib\sentence_transformers\losses
      copying sentence_transformers\losses\BatchHardTripletLoss.py -> build\lib\sentence_transformers\losses
      copying sentence_transformers\losses\BatchSemiHardTripletLoss.py -> build\lib\sentence_transformers\losses
      copying sentence_transformers\losses\ContrastiveLoss.py -> build\lib\sentence_transformers\losses
      copying sentence_transformers\losses\ContrastiveTensionLoss.py -> build\lib\sentence_transformers\losses
      copying sentence_transformers\losses\CosineSimilarityLoss.py -> build\lib\sentence_transformers\losses
      copying sentence_transformers\losses\DenoisingAutoEncoderLoss.py -> build\lib\sentence_transformers\losses
      copying sentence_transformers\losses\MarginMSELoss.py -> build\lib\sentence_transformers\losses
      copying sentence_transformers\losses\MegaBatchMarginLoss.py -> build\lib\sentence_transformers\losses
      copying sentence_transformers\losses\MSELoss.py -> build\lib\sentence_transformers\losses
      copying sentence_transformers\losses\MultipleNegativesRankingLoss.py -> build\lib\sentence_transformers\losses
      copying sentence_transformers\losses\MultipleNegativesSymmetricRankingLoss.py -> build\lib\sentence_transformers\losses
      copying sentence_transformers\losses\OnlineContrastiveLoss.py -> build\lib\sentence_transformers\losses
      copying sentence_transformers\losses\SoftmaxLoss.py -> build\lib\sentence_transformers\losses
      copying sentence_transformers\losses\TripletLoss.py -> build\lib\sentence_transformers\losses
      copying sentence_transformers\losses\__init__.py -> build\lib\sentence_transformers\losses
      creating build\lib\sentence_transformers\models
      copying sentence_transformers\models\Asym.py -> build\lib\sentence_transformers\models
      copying sentence_transformers\models\BoW.py -> build\lib\sentence_transformers\models
      copying sentence_transformers\models\CLIPModel.py -> build\lib\sentence_transformers\models
      copying sentence_transformers\models\CNN.py -> build\lib\sentence_transformers\models
      copying sentence_transformers\models\Dense.py -> build\lib\sentence_transformers\models
      copying sentence_transformers\models\Dropout.py -> build\lib\sentence_transformers\models
      copying sentence_transformers\models\LayerNorm.py -> build\lib\sentence_transformers\models
      copying sentence_transformers\models\LSTM.py -> build\lib\sentence_transformers\models
      copying sentence_transformers\models\Normalize.py -> build\lib\sentence_transformers\models
      copying sentence_transformers\models\Pooling.py -> build\lib\sentence_transformers\models
      copying sentence_transformers\models\Transformer.py -> build\lib\sentence_transformers\models
      copying sentence_transformers\models\WeightedLayerPooling.py -> build\lib\sentence_transformers\models
      copying sentence_transformers\models\WordEmbeddings.py -> build\lib\sentence_transformers\models
      copying sentence_transformers\models\WordWeights.py -> build\lib\sentence_transformers\models
      copying sentence_transformers\models\__init__.py -> build\lib\sentence_transformers\models
      creating build\lib\sentence_transformers\readers
      copying sentence_transformers\readers\InputExample.py -> build\lib\sentence_transformers\readers
      copying sentence_transformers\readers\LabelSentenceReader.py -> build\lib\sentence_transformers\readers
      copying sentence_transformers\readers\NLIDataReader.py -> build\lib\sentence_transformers\readers
      copying sentence_transformers\readers\PairedFilesReader.py -> build\lib\sentence_transformers\readers
      copying sentence_transformers\readers\STSDataReader.py -> build\lib\sentence_transformers\readers
      copying sentence_transformers\readers\TripletReader.py -> build\lib\sentence_transformers\readers
      copying sentence_transformers\readers\__init__.py -> build\lib\sentence_transformers\readers
      creating build\lib\sentence_transformers\cross_encoder\evaluation
      copying sentence_transformers\cross_encoder\evaluation\CEBinaryAccuracyEvaluator.py -> build\lib\sentence_transformers\cross_encoder\evaluation
      copying sentence_transformers\cross_encoder\evaluation\CEBinaryClassificationEvaluator.py -> build\lib\sentence_transformers\cross_encoder\evaluation
      copying sentence_transformers\cross_encoder\evaluation\CECorrelationEvaluator.py -> build\lib\sentence_transformers\cross_encoder\evaluation
      copying sentence_transformers\cross_encoder\evaluation\CERerankingEvaluator.py -> build\lib\sentence_transformers\cross_encoder\evaluation
      copying sentence_transformers\cross_encoder\evaluation\CESoftmaxAccuracyEvaluator.py -> build\lib\sentence_transformers\cross_encoder\evaluation
      copying sentence_transformers\cross_encoder\evaluation\__init__.py -> build\lib\sentence_transformers\cross_encoder\evaluation
      creating build\lib\sentence_transformers\models\tokenizer
      copying sentence_transformers\models\tokenizer\PhraseTokenizer.py -> build\lib\sentence_transformers\models\tokenizer
      copying sentence_transformers\models\tokenizer\WhitespaceTokenizer.py -> build\lib\sentence_transformers\models\tokenizer
      copying sentence_transformers\models\tokenizer\WordTokenizer.py -> build\lib\sentence_transformers\models\tokenizer
      copying sentence_transformers\models\tokenizer\__init__.py -> build\lib\sentence_transformers\models\tokenizer
      running install_lib
      byte-compiling C:\Users\dumbtest\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sentence_transformers\cross_encoder\evaluation\CEBinaryClassificationEvaluator.py to CEBinaryClassificationEvaluator.cpython-310.pyc
      error: [Errno 2] No such file or directory: 'C:\\Users\\dumbtest\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\sentence_transformers\\cross_encoder\\evaluation\\__pycache__\\CEBinaryClassificationEvaluator.cpython-310.pyc.2220418870304'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> sentence_transformers`

### Expected behavior 🤔

installing all the requirements

### Your prompt 📝

```yaml
# Paste your prompt here
```
I didnt get to the prompts. couldnt install properly.

**Comment by royjosefsson** [comment]
Solution is to add '--user' at the end. Like this:
`pip install -r requirements.txt --user`

**Comment by Nickonomic** [comment]
> Solution is to add '--user' at the end. Like this: `pip install -r requirements.txt --user`

Doesn't work.

**Comment by Octavian01** [comment]
same problem, all cmd in txt file
[grpcio.txt](https://github.com/Significant-Gravitas/Auto-GPT/files/11240365/grpcio.txt)

**Comment by russbakr** [comment]
i had to delete every instance of microsoft visual (anything) then reinstall it

**Comment by Octavian01** [comment]
@Nickonomic i solve   :    https://github.com/Significant-Gravitas/Auto-GPT/archive/refs/tags/v0.2.0.zip     , so  git clone https://github.com/Torantulino/Auto-GPT.git       cd 'Auto-GPT'       and     pip install -r requirements.txt    for me it work

**Comment by ntindle** [comment]
Opened PR
