### ISSUE TITLE
AutoGPT/Auto-GPT/autogpt/data_ingestion.py", line 4, in <module>     from autogpt.config import Config ModuleNotFoundError: No module named 'autogpt'

### ISSUE THREAD

**Issue by twajothi** [Significant-Gravitas/Auto-GPT#1667]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

running data_ingest.py

### Current behavior 😯

AutoGPT/Auto-GPT/autogpt/data_ingestion.py", line 4, in <module>
    from autogpt.config import Config
ModuleNotFoundError: No module named 'autogpt'

### Expected behavior 🤔

memory pre seeding 

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Explorergt92** [comment]
Same error here ... 

PS C:\Users\username\Projects\Auto-GPT>
```
python autogpt/data_ingestion.py --dir seed_data --init --overlap 200 --max_length 1000

Traceback (most recent call last):
  File "C:\Users\username\Projects\Auto-GPT\autogpt\data_ingestion.py", line 4, in <module>
    from autogpt.config import Config
ModuleNotFoundError: No module named 'autogpt'
```

**Comment by Slowly-Grokking** [comment]
move data_ingestion.py from Auto-Gpt/autogpt/data_ingestion.py to Auto-GPT/data_ingestion.py

'python data_ingestion.py --dir . --init --overlap 200 --max_length 1000' to ingest everything in the auto_gpt_workspace

https://github.com/Significant-Gravitas/Auto-GPT/pull/1679

**Comment by iddelacruz** [comment]
Sorry guys but in the latest source code I couldn't find the data-ingestion.py file.

**Comment by hermanarenas** [comment]
> 

Worked perfectly thanks

**Comment by Explorergt92** [comment]
> move `data_ingestion.py` from `Auto-Gpt/autogpt/data_ingestion.py` to `Auto-GPT/data_ingestion.py`
> 
> `python data_ingestion.py --dir . --init --overlap 200 --max_length 1000` to ingest everything in the auto_gpt_workspace folder
> 
> #1679

Thanks! Worked for me.

**Comment by ivan-vilches** [comment]
> move data_ingestion.py from Auto-Gpt/autogpt/data_ingestion.py to Auto-GPT/data_ingestion.py
> 
> 'python data_ingestion.py --dir . --init --overlap 200 --max_length 1000' to ingest everything in the auto_gpt_workspace
> 
> #1679

thanks you, worked !!!!!

**Comment by ntindle** [comment]
Should be fixed
