### ISSUE TITLE
Failed to build ujson

### ISSUE THREAD

**Issue by raymerjacque** [Significant-Gravitas/Auto-GPT#1668]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Collecting h11<1,>=0.9.0
  Using cached h11-0.14.0-py3-none-any.whl (58 kB)
Building wheels for collected packages: ujson
  Building wheel for ujson (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for ujson (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      C:\Users\rayme\AppData\Local\Temp\pip-build-env-xkkzagbi\overlay\Lib\site-packages\setuptools\config\setupcfg.py:516: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      running bdist_wheel
      running build
      running build_ext
      building 'ujson' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ujson
Failed to build ujson
ERROR: Could not build wheels for ujson, which is required to install pyproject.toml-based projects
python: can't open file 'C:\\Zipped\\Auto-GPT\\scripts\\main.py': [Errno 2] No such file or directory
Press any key to continue . . .

### Current behavior 😯

Collecting h11<1,>=0.9.0
  Using cached h11-0.14.0-py3-none-any.whl (58 kB)
Building wheels for collected packages: ujson
  Building wheel for ujson (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for ujson (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      C:\Users\rayme\AppData\Local\Temp\pip-build-env-xkkzagbi\overlay\Lib\site-packages\setuptools\config\setupcfg.py:516: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      running bdist_wheel
      running build
      running build_ext
      building 'ujson' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ujson
Failed to build ujson
ERROR: Could not build wheels for ujson, which is required to install pyproject.toml-based projects
python: can't open file 'C:\\Zipped\\Auto-GPT\\scripts\\main.py': [Errno 2] No such file or directory
Press any key to continue . . .

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Aman-14** [comment]
According to the error you need to install Microsoft Visual C++ tools.

https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by Qoyyuum** [comment]
Hi @raymerjacque please install and setup Visual C++ tools and try again.
