### ISSUE TITLE
Error with creating connection to OpenAi

### ISSUE THREAD

**Issue by OmniKingOG** [Significant-Gravitas/Auto-GPT#1673]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

When I prompted the Auto GPT to evaluate all files located within its local memory (the files are an exact copy of its code). It creates a list of the files and stuff when it searches the correct directory which is good but the issue comes in hand when it reads the code from one of the files and then try’s to evaluate the code right after, the evaluate code command returns with an error that states a connection cannot be created to OpenAi API, when I then try to get auto GPT to try again using s different method or function it fails to ever prompt the code again correctly and begins to read and create blank files and says it’s still continuing its task. 

### Current behavior 😯

When trying to evaluate the code after reading code off of one of the files as it goes through all 1 by 1 it immediately is prompted with an Error connecting to OpenAI API prompt. 

### Expected behavior 🤔

Not to sure as I did not expect it to begin reading and evaluating the files correctly other then be stopped by the prompted error. Hopefully tho to be able to evaluate the files and loop through 1 by 1 improving the copy of its code placed in its directory that it can find. Then will hope to implement it into its long term memory system to see if it can try and remember the code and then hopefully try and convince the system the code is it’s actual code and so on, plan still a bit cloudy but that’s a rough sketch of its expected behavior in the end. 

### Your prompt 📝

```yaml
# Paste your prompt here
Not 100% sure as I changed it a lot throughout and I’m not on my computer right now but when I can I can update this field with the correct prompt used to trigger the process.

**Comment by Pwuts** [comment]
Please post the log and reopen.
