### ISSUE TITLE
pymilvus not installed. Skipping import.

### ISSUE THREAD

**Issue by huszarrichard** [Significant-Gravitas/Auto-GPT#1681]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

python -m autogpt

### Current behavior 😯

➜  Auto-gpt git:(master) ✗ python -m autogpt
pymilvus not installed. Skipping import.
Welcome to Auto-GPT!  Enter the name of your AI and its role below. Entering nothing will load defaults.
Name your AI:  For example, 'Entrepreneur-GPT'
AI Name: 
![CleanShot 2023-04-15 at 21 12 10](https://user-images.githubusercontent.com/17738461/232249056-04634cf0-2d64-4e24-ba2a-ae4b196cd623.png)

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by cryptidv** [comment]
That's expected behavior. Unless you want to use pymilvus.

Just run `pip install -r requirements.txt` again. You should run that command every time you update the program.

**Comment by huszarrichard** [comment]
> That's expected behavior. Unless you want to use milvus.
> 
> Just run `pip install -r requirements.txt` again. You should run that command every time you update the program, to install any new dependencies that may have been added.

Thank you! Now I got another error messages when I run `pip install -r requirements.txt`. This is a very-very long error code, but i can copy the last lines:

`  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Rolling back uninstall of grpcio
  Moving to /opt/homebrew/lib/python3.11/site-packages/grpc/
   from /opt/homebrew/lib/python3.11/site-packages/~rpc
  Moving to /opt/homebrew/lib/python3.11/site-packages/grpcio-1.53.0-py3.11.egg-info
   from /opt/homebrew/lib/python3.11/site-packages/~rpcio-1.53.0-py3.11.egg-info
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> grpcio

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.`

What can I do?

**Comment by DarkShadowG** [comment]
try pip3 install -U pymilvus

**Comment by PaulChunTHEREALONE** [comment]
I try try it,and thank thank you,

**Comment by chyezh** [comment]
I got the same problem, it seems like a environment problem.
try to use pyenv or venv to create a clean python workspace.

**Comment by ntindle** [comment]
Try and use the #tech-support channel in discord for these issues. We don’t have the capacity to help debug in GitHub issues for problems like this
