### ISSUE TITLE
error: legacy-install-failure

### ISSUE THREAD

**Issue by chen5211314** [Significant-Gravitas/Auto-GPT#1685]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

error:legacy-install-failure
x Encountered error while trying to install package.
grpcio
note:This is an issue with the package mentioned above,not pip.
hint:See above for output from the failure.
[notice]A new release of pip is available:23.0.1->23.1
[notice]To update,run:pip install --upgrade pip
(env)chenweikang@chenweikangdeMacBook-Pro Auto-GPT

### Current behavior 😯

一直循环重复无法进入autogpt

### Expected behavior 🤔

成功进入gpt（mac本）

### Your prompt 📝

```yaml
# Paste your prompt here
```error:legacy-install-failure
x Encountered error while trying to install package.
grpcio
note:This is an issue with the package mentioned above,not pip.
hint:See above for output from the failure.
[notice]A new release of pip is available:23.0.1->23.1
[notice]To update,run:pip install --upgrade pip
(env)chenweikang@chenweikangdeMacBook-Pro Auto-GPT

**Comment by ntindle** [comment]
Try and use the #tech-support channel in discord for these issues. We don’t have the capacity to help debug in GitHub issues for problems like this
