### ISSUE TITLE
Doesnt work on Firefox

### ISSUE THREAD

**Issue by neosinan** [Significant-Gravitas/Auto-GPT#1701]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Since I dont have chrome installed on my PC I changed .env to 
USE_WEB_BROWSER='firefox'
or
USE_WEB_BROWSER=firefox

I tried just in-case
then I gave a name to it, described its role and gave a goal. I tried this many times with many goals. this is my last example 

description. an AI that is designed to answer my questions.

Goal 1: give me list of 10 most populated cities?
Goal 2:

### Current behavior 😯

After I gave its goals it stucks in this screen and it does nothing and this is the only thing it says:

Using memory of type:  LocalCache
Using Browser:  firefox
| Thinking...

### Expected behavior 🤔

Answer the question

**Comment by normen** [comment]
Works for me

**Comment by neosinan** [comment]
any suggestion what can cause this?

![image](https://user-images.githubusercontent.com/19516440/232252285-36dfbdb7-6006-4965-87ae-1d8887e1beea.png)

**Comment by normen** [comment]
At that step the browser isn't involved yet, you're looking for the wrong issue.

**Comment by LeMaireBrando** [comment]
I am also having an issue with using firefox as the browser.  I made the necessary changes to the .env file but it seems to be stuck with using the default chrome.

**Comment by k-boikov** [comment]
> any suggestion what can cause this?
> 
> I also installed pymilvus, no change in behavior
> 
> ![image](https://user-images.githubusercontent.com/19516440/232252285-36dfbdb7-6006-4965-87ae-1d8887e1beea.png)

Seems like you do not have a paid openai account.
Check https://github.com/Significant-Gravitas/Auto-GPT/issues/2169

**Comment by LeMaireBrando** [comment]
> > I am also having an issue with using firefox as the browser. I made the necessary changes to the .env file but it seems to be stuck with using the default chrome.
> 
> Are you sure you are changing the write .env file? It should look like this: ![image](https://user-images.githubusercontent.com/64261260/232571473-b09a5336-7102-4ee1-8ff1-b9b531d6b499.png)

Indeed.  Confirming from your screenshot; I have those same settings determined in the .env file (not the template file).   It was working great the other day.

**Comment by k-boikov** [comment]
> Indeed. Confirming from your screenshot; I have those same settings determined in the .env file (not the template file). It was working great the other day.

And you are saying that you dont see this:
![image](https://user-images.githubusercontent.com/64261260/232639121-50257ae6-0b9a-4296-bb5b-3bb2d6f01cd7.png)
but Chrome instead?
If yes - try reinstalling the project, there must be something wrong with the files.

**Comment by LeMaireBrando** [comment]
> > Indeed. Confirming from your screenshot; I have those same settings determined in the .env file (not the template file). It was working great the other day.
> 
> And you are saying that you dont see this: ![image](https://user-images.githubusercontent.com/64261260/232639121-50257ae6-0b9a-4296-bb5b-3bb2d6f01cd7.png) but Chrome instead? If yes - try reinstalling the project, there must be something wrong with the files.

Yes.  It does not show firefox for me; and instead shows 'Using Browser:  chrome'.

I have just deleted the entire project folder and cloned the repo once more, but no luck yet as it is still the same.

**Comment by ntindle** [comment]
Needs more info
