### ISSUE TITLE
I cannt seem to find app.py in auto-gpt folder 

### ISSUE THREAD

**Issue by olmososc** [Significant-Gravitas/Auto-GPT#1705]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

-

### Current behavior 😯

-

### Expected behavior 🤔

-

### Your prompt 📝

C:\Users\oolmo\Auto-GPT>python app.py
python: can't open file 'C:\\Users\\oolmo\\Auto-GPT\\app.py': [Errno 2] No such file or directory

**Comment by olmososc** [comment]
update 
:C:\Users\oolmo\Auto-GPT>python main.py
Traceback (most recent call last):
  File "C:\Users\oolmo\Auto-GPT\main.py", line 1, in <module>
    from autogpt import main
ImportError: cannot import name 'main' from 'autogpt' (C:\Users\oolmo\Auto-GPT\autogpt\__init__.py)

**Comment by k-boikov** [comment]
The master branch is sometimes broken (or the README is just behind) because of the constant development done, in your case just use the new way to run AutoGPT:
`python -m autogpt`

**Comment by Explorergt92** [comment]
@olmososc is this issue solved? if so please close.

FYI you can also find help on the discord server at https://discord.gg/autogpt
