### ISSUE TITLE
.env problem

### ISSUE THREAD

**Issue by DrReefer** [Significant-Gravitas/Auto-GPT#1708]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

I delete AutoGPT then re-cloned it. It clones a fresh copy but the .env file is a text file. I add my openai api and pinecone api then save it as .env file as, all files It still saves it as Template file?
![env2](https://user-images.githubusercontent.com/20601270/232252447-c517fe6d-e4ec-4081-9eea-7f9aa5251e53.jpg)

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by k-boikov** [comment]
Your Windows in probably not displaying file extensions. Turn the feature on and you will see that the file is actually called ".env.template".

**Comment by DrReefer** [comment]
> Your Windows in probably not displaying file extensions. Turn the feature on and you will see that the file is actually called ".env.template".

Yes, I had to go to View Then Show then File Name Extentions

Edited .env and saved it as All Files, then delete the .env template file and then I got it working :)
![pymil](https://user-images.githubusercontent.com/20601270/232253999-867bcdea-4357-4edb-895b-bf9789218b0d.jpg)

**Comment by Explorergt92** [comment]
@DrReefer is this issue solved? if so please close.
