### ISSUE TITLE
Error in Auto-GPT script on line 448 while starting interaction loop

### ISSUE THREAD

**Issue by Sakatard** [Significant-Gravitas/Auto-GPT#1713]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

I receive this error after trying to restart the script, I've repulled I have a GPT plus subscription, I rested my computer, I've swapped from redis to local memory and also destroyed the redis db so everything should be fresh

yes this is on the stable branch

### Current behavior 😯

Continue (y/n): y
Using memory of type: RedisMemory
  Token limit: 4500
  Memory Stats: {'index_name': 'auto-gpt', 'index_options': [], 'index_definition': [b'key_type', b'HASH', b'prefixes', [b'auto-gpt:'], b'default_score', b'1'], 'attributes': [[b'identifier', b'data', b'attribute', b'data', b'type', b'TEXT', b'WEIGHT', b'1'], [b'identifier', b'embedding', b'attribute', b'embedding', b'type', b'VECTOR']], 'num_docs': '0', 'max_doc_id': '0', 'num_terms': '0', 'num_records': '0', 'inverted_sz_mb': '0', 'vector_index_sz_mb': '0', 'total_inverted_index_blocks': '0', 'offset_vectors_sz_mb': '0', 'doc_table_size_mb': '0', 'sortable_values_size_mb': '0', 'key_table_size_mb': '0', 'records_per_doc_avg': '-nan', 'bytes_per_record_avg': '-nan', 'offsets_per_term_avg': '-nan', 'offset_bits_per_record_avg': '-nan', 'hash_indexing_failures': '0', 'total_indexing_time': '0', 'indexing': '0', 'percent_indexed': '1', 'number_of_uses': 3, 'gc_stats': [b'bytes_collected', b'0', b'total_ms_run', b'0', b'total_cycles', b'0', b'average_cycle_time_ms', b'-nan', b'last_run_time_ms', b'0', b'gc_numeric_trees_missed', b'0', b'gc_blocks_denied', b'0'], 'cursor_stats': [b'global_idle', 0, b'global_total', 0, b'index_capacity', 128, b'index_total', 0], 'dialect_stats': [b'dialect_1', 0, b'dialect_2', 0, b'dialect_3', 0]}
  Token limit: 4500
  Send Token Count: 982
  Tokens remaining for response: 3518
  ------------ CONTEXT SENT TO AI ---------------
  System: The current time and date is Sun Apr 16 04:54:36 2023

  System: This reminds you of these events from your past:

  User: Determine which next command to use, and respond using the format specified above:

  ----------- END OF CONTEXT ----------------
Creating chat completion with model gpt-3.5-turbo, temperature 1.0, max_tokens 3518
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\frunk\Documents\Development\Auto-GPT\autogpt\__main__.py", line 572, in <module>
    main()
  File "C:\Users\frunk\Documents\Development\Auto-GPT\autogpt\__main__.py", line 396, in main
    agent.start_interaction_loop()
  File "C:\Users\frunk\Documents\Development\Auto-GPT\autogpt\__main__.py", line 448, in start_interaction_loop
    assistant_reply = chat.chat_with_ai(
  File "C:\Users\frunk\Documents\Development\Auto-GPT\autogpt\chat.py", line 159, in chat_with_ai
    assistant_reply = create_chat_completion(
  File "C:\Users\frunk\Documents\Development\Auto-GPT\autogpt\llm_utils.py", line 39, in create_chat_completion
    response = openai.ChatCompletion.create(
  File "C:\Users\frunk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\frunk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\frunk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Users\frunk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\frunk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens. However, you requested 4497 tokens (979 in the messages, 3518 in the completion). Please reduce the length of the messages or completion.

C:\Users\frunk\Documents\Development\Auto-GPT>

### Expected behavior 🤔

expected to run as normal

### Your prompt 📝

ai_goals:
- Figure out what cryptocurrencies will be traded on crypto.com's exchange using my
  API Key and Secret Key in the  APIKeys.txt file
- Create and Store the data in the workspace along with all the python code for the
  trading bot
- Create a python flask web app that displays the dashboard of what is going on right
  now on the trading bot and host it locally, store all the files in the workspacee
- Code everything yourself and dont rely on GPT as its knowledge is limited to september
  2021 so you will need to google
ai_name: Crypto-GPT
ai_role: an AI designed to automate crypto trades and grow net worth, all manageable
  via a Web UI

**Comment by Pegasust** [comment]
Please avoid putting the stack trace as github issues. A simple chatGPT prompt yields a reasonable title:

> Summarize this error to file a github issue Traceback (most recent call last): File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code exec(code, run_globals) File "C:\Users\frunk\Documents\Development\Auto-GPT\autogpt\__main__.py", line 572, in <module> main() File "C:\Users\frunk\Documents\Development\Auto-GPT\autogpt\__main__.py", line 396, in main agent.start_interaction_loop() File "C:\Users\frunk\Documents\Development\Auto-GPT\autogpt\__main__.py", line 448, in start_interaction_loop

There is an error occurring in a Python script located in a specific file path. The error occurs on line 448 of the __main__.py file within the autogpt package. Specifically, the start_interaction_loop() method of an agent object is causing the error. Further information about the error is not provided in this traceback.

> generate title for github issue

"Error in Auto-GPT script on line 448 while starting interaction loop"

**Comment by Sakatard** [comment]
> Please avoid putting the stack trace as github issues. A simple chatGPT prompt yields a reasonable title:
> 
> > Summarize this error to file a github issue Traceback (most recent call last): File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code exec(code, run_globals) File "C:\Users\frunk\Documents\Development\Auto-GPT\autogpt__main__.py", line 572, in  main() File "C:\Users\frunk\Documents\Development\Auto-GPT\autogpt__main__.py", line 396, in main agent.start_interaction_loop() File "C:\Users\frunk\Documents\Development\Auto-GPT\autogpt__main__.py", line 448, in start_interaction_loop
> 
> There is an error occurring in a Python script located in a specific file path. The error occurs on line 448 of the **main**.py file within the autogpt package. Specifically, the start_interaction_loop() method of an agent object is causing the error. Further information about the error is not provided in this traceback.
> 
> > generate title for github issue
> 
> "Error in Auto-GPT script on line 448 while starting interaction loop"

sorry my bad, thanks for telling me what line it was happening on also

**Comment by Sakatard** [comment]
fixed by setting token values back to default in the .env file
