### ISSUE TITLE
Custom User-Agent for Auto-GPT

### ISSUE THREAD

**Issue by bary12** [Significant-Gravitas/Auto-GPT#1724]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Auto-GPT should include a custom User-Agent field in its requests, specifying they are made using Auto-GPT.

### Examples 🌈

```
User-Agent: Auto-GPT/0.2.0 <agent name> (<agent description>)
```

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent

### Motivation 🔦

As AI agents become increasingly popular, it's important that they are easy to monitor and restrict. While this doesn't provide a real security boundary, this can help in the meanwhile as we figure out how to detect and monitor such calls, and as the world implements policies related to AI agents.

**Comment by soheil** [comment]
Have you seen `USER_AGENT` env var? https://github.com/Significant-Gravitas/Auto-GPT/blob/582c85b1402a7c28fd9305ed97bcc7dd48eb80a2/.env.template#L11

**Comment by bary12** [comment]
> Have you seen `USER_AGENT` env var?
> 
> https://github.com/Significant-Gravitas/Auto-GPT/blob/582c85b1402a7c28fd9305ed97bcc7dd48eb80a2/.env.template#L11

Yes, I have. The proposal is for changing the default value, so websites can generally detect requests made by AutoGPT agents (and not just the one running on my machine)

**Comment by Boostrix** [comment]
I suppose, given the conflict of interests, this issue can be safely closed, given debates like the following:

- https://tech.slashdot.org/story/23/04/25/2035259/an-ai-scraping-tool-is-overwhelming-websites-with-traffic
- https://www.vice.com/en/article/dy3vmx/an-ai-scraping-tool-is-overwhelming-websites-with-traffic
- https://www.searchenginejournal.com/how-to-block-chatgpt-from-using-your-website-content/478384/
- https://www.resolutiondigital.com.au/insights/seo-website-ai-content-scraping/

Anybody really bothered by this can obviously "opt in" and communicate that they're running Auto-GPT by changing the USER_AGENT env var. Other than that, this sort of RFE is probably gonna be as popular among users as BY DEFAULT restricting Auto-GPT's bandwidth to 1kb/sec and its max CPU/RAM utilization to ~10% ...
