### ISSUE TITLE
pip breakes speach then locks up program

### ISSUE THREAD

**Issue by ConTronTech** [Significant-Gravitas/Auto-GPT#1726]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

i was trying to make a face detection system for my pc and when it came down to open-cv2 it will try and execute shell to check if cv2 is installed then he error keeps appearing.

### Current behavior 😯

NEXT ACTION:  COMMAND = execute_shell ARGUMENTS = {'command_line': 'pip install opencv-python'}
Executing command 'pip install opencv-python' in working directory 'E:\Auto-GPT-0.2.0\auto_gpt_workspace'
Exception in thread Thread-12 (speak):
Traceback (most recent call last):
  File "C:\Users\succme\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\succme\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Auto-GPT-0.2.0\autogpt\speak.py", line 106, in speak
    success = brian_speech(text)
              ^^^^^^^^^^^^^^^^^^
  File "E:\Auto-GPT-0.2.0\autogpt\speak.py", line 74, in brian_speech
    os.remove("speech.mp3")
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'speech.mp3'

### Expected behavior 🤔

to continue building the program

### Your prompt 📝

ai_goals:
- make a face recognition python scriped
- that will detect my face and unlock pc
- if not my face lock pc
- sound a alarm if not my face
ai_name: testing
ai_role: make scripeds

**Comment by sirplus51** [comment]
h this and solved by uninstalling all versions of python.
reinstalled just 1 4.10

**Comment by ntindle** [comment]
Sometimes it executes something unexpected or doesn’t do what you want.  Check out the #prompt-engineering channel in discord to get a better fit prompt
