### ISSUE TITLE
400

### ISSUE THREAD

**Issue by Scorp96** [Significant-Gravitas/Auto-GPT#1758]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

python -m autogpt --speak --gpt3only

### Current behavior 😯

C:\Auto-GPT-0.2.0>python -m autogpt --speak --gpt3only
Warning: The file 'auto-gpt.json' does not exist. Local memory would not be saved to a file.
Speak Mode:  ENABLED
GPT3.5 Only Mode:  ENABLED
Welcome to Auto-GPT!  Enter the name of your AI and its role below. Entering nothing will load defaults.
Name your AI:  For example, 'Entrepreneur-GPT'
AI Name: Request failed with status code: 400
Response content: b'{"detail":{"status":"invalid_uid","message":"An invalid ID has been received: \'your-voice-id-1\'. Make sure to provide a correct one."}}'

### Expected behavior 🤔

C:\Auto-GPT-0.2.0>python -m autogpt --speak --gpt3only
Warning: The file 'auto-gpt.json' does not exist. Local memory would not be saved to a file.
Speak Mode:  ENABLED
GPT3.5 Only Mode:  ENABLED
Welcome to Auto-GPT!  Enter the name of your AI and its role below. Entering nothing will load defaults.
Name your AI:  For example, 'Entrepreneur-GPT'
AI Name: Request failed with status code: 400
Response content: b'{"detail":{"status":"invalid_uid","message":"An invalid ID has been received: \'your-voice-id-1\'. Make sure to provide a correct one."}}'

### Your prompt 📝

python -m autogpt --speak --gpt3only

**Comment by p92** [comment]
read the README file to setup correctly your voice ELEVENLABS variables in .env file  
or avoid using --speak parameter

**Comment by Bentlybro** [comment]
here you can try using this ID which will use the premade "Adam" voice
ELEVENLABS_VOICE_1_ID=pNInz6obpgDQGcFmaJgB
or here is the ID for "Rachel" 
ELEVENLABS_VOICE_1_ID=21m00Tcm4TlvDq8ikWAM

**Comment by hubertdungen** [comment]
Today, before the last update I was able to use it like this:

`ELEVENLABS_API_KEY=
ELEVENLABS_VOICE_1_ID=your-voice-id-1
ELEVENLABS_VOICE_2_ID=your-voice-id-2`

Now if I let this like this on 0.2.1 it gets the 400 error. If I write "ELEVENLABS_VOICE_1_ID=pNInz6obpgDQGcFmaJgB" or "ELEVENLABS_VOICE_1_ID=21m00Tcm4TlvDq8ikWAM" I get an 401 error.

**Comment by icelasa** [comment]
Same problem.

**Comment by baizhongying** [comment]
python -m autogpt --gpt3only

**Comment by p92** [comment]
you need the API key or dont use --speak

**Comment by zhashut** [comment]
@hubertdungen 
把 ELEVENLABS_API_KEY、ELEVENLABS_VOICE_1_ID、ELEVENLABS_VOICE_2_ID注释即可，我是注释了之后再次运行就成功了
![image](https://user-images.githubusercontent.com/96969008/232780700-9daae7a7-efd0-4787-a7e1-32add8db3ce8.png)

**Comment by coditamar** [comment]
This might be the issue:
https://github.com/Significant-Gravitas/Auto-GPT/pull/2788/files

**Comment by q909824095** [comment]
> @hubertdungen 把 ELEVENLABS_API_KEY、ELEVENLABS_VOICE_1_ID、ELEVENLABS_VOICE_2_ID注释即可，我是注释了之后再次运行就成功了 ![image](https://user-images.githubusercontent.com/96969008/232780700-9daae7a7-efd0-4787-a7e1-32add8db3ce8.png)
.env 文件里，默认就是注释的，填写了1的ID会出现401要求提供key

**Comment by ntindle** [comment]
Issue unclear. Revise and reopen
