### ISSUE TITLE
Is there a way to use this without OpenAI?

### ISSUE THREAD

**Issue by FrankDMartinez** [Significant-Gravitas/Auto-GPT#1759]
Hi.

I hope you are having a great new year so far. I am concerned about OpenAI's limits, especially since other AIs abilities might soon exceed OpenAI's. Is there a way to use this without OpenAI?

Thanks in advance.

**Comment by aalbrightpdx** [comment]
I have no idea, but I wonder if you just use a diff API key maybe that would work?

**Comment by JiangNaa** [comment]
So who do you want to talk to? Siri? lol

**Comment by xh20230222** [comment]
我太想用了，但是不会英语

**Comment by FrankDMartinez** [comment]
> I have no idea, but I wonder if you just use a diff API key maybe that would work?

How would that work since it's still OpenAI being accessed?

**Comment by FrankDMartinez** [comment]
> So who do you want to talk to? Siri? lol

A local instance of Alpaca-Lora comes to mind.

**Comment by aalbrightpdx** [comment]
> 我太想用了，但是不会英语

"I really want to use it, but I don't know English."

I used ChatGPT...I have no idea if this helps but I hope so.

我用了 ChatGPT……我不知道这是否有帮助，但我希望有。

-------

以下是 Auto-GPT 安装说明的中文翻译：

Auto-GPT
Auto-GPT 是一个使用 GPT 架构的大型语言模型，可以用于生成文本和执行其他 NLP 任务。这个项目基于 Hugging Face 的 Transformers 库，它提供了一个简单的 API，可以让用户轻松地使用预训练的 GPT 模型进行推理。

安装说明
首先，确保你已经安装了 Python 3.6 或更高版本以及 pip 包管理器。如果你还没有安装，请先安装它们。

克隆 Auto-GPT 仓库，使用以下命令：

bash
Copy code
git clone https://github.com/Significant-Gravitas/Auto-GPT.git
进入 Auto-GPT 目录，并创建一个名为 venv 的虚拟环境。使用以下命令：

bash
Copy code
cd Auto-GPT
python3 -m venv venv
激活虚拟环境。使用以下命令：

bash
Copy code
source venv/bin/activate
安装必要的依赖项。使用以下命令：

Copy code
pip install -r requirements.txt
运行 setup.sh 脚本，以下载预训练模型并将其安装到你的虚拟环境中。使用以下命令：

arduino
Copy code
./setup.sh
现在，Auto-GPT 已经安装完毕，你可以开始使用它了。如果你想了解更多关于 Auto-GPT 的使用方法，请查看 Auto-GPT 仓库中的文档。

**Comment by aalbrightpdx** [comment]
> > I have no idea, but I wonder if you just use a diff API key maybe that would work?
> 
> How would that work since it's still OpenAI being accessed?

Well mostly because that's not how APIs work.  ;)

**Comment by FrankDMartinez** [comment]
> Well mostly because that's not how APIs work. ;)

Explain.

**Comment by CeberusOne** [comment]
I think he ment Like different API Key also different Ai ,like Azure,Alpaca ,Lore, you Name it. 🤷🏻‍♀️

**Comment by gjmulder** [comment]
How about  [llama-cpp-python, which offers a web server which aims to act as a drop-in replacement for the OpenAI API](https://github.com/abetlen/llama-cpp-python)?

**Comment by drew1two** [comment]
this might be a hijack, but the title is the exact same question I'd like to ask.
Reason for using without openai key?  I find I can get better (and cheaper) results by asking chatGpt directly atm, but I find the ability of autoGpt to do google searches and collate them invaluable :)
I'd like to perform searches, write results to file, then manually select the next link to browse and save to file, then use that output to ask more definitive questions to gpt-4 directly.

is this possible at all?

**Comment by henryruss2** [comment]
> 我太想用了，但是不会英语
使用谷歌翻译

**Comment by Boostrix** [comment]
See #2158 and https://github.com/Significant-Gravitas/Auto-GPT/issues/25

**Comment by Qoyyuum** [comment]
Closing as duplicates
