### ISSUE TITLE
hi ,there is no 'main.py‘ file in scripts folder, so when i run "python scripts/main.py'. The bug "[Errno 2] No such file or directory" shows

### ISSUE THREAD

**Issue by hvacking** [Significant-Gravitas/Auto-GPT#1776]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

<img width="609" alt="image" src="https://user-images.githubusercontent.com/28031945/232264081-775c2e00-8e6d-4173-aed9-e6ee702c73ba.png">

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Explorergt92** [comment]
@hvacking there's a new command to run Auto-GPT
```
python -m autogpt
```

**Comment by estefysc** [comment]
Are you trying to run the program? Because if this is the case, you should just cd the cloned repo in your machine and either run `python -m autogpt `, which will work with chatGPT 4 or `python -m autogpt --gpt3only` for GPT3.5

**Comment by hvacking** [comment]
Yes, it works . Thanks!
