### ISSUE TITLE
Extra Characters Showing in Window 11//Powershell

### ISSUE THREAD

**Issue by jbb-kryo** [Significant-Gravitas/Auto-GPT#178]
![image](https://user-images.githubusercontent.com/61083145/229824768-1e13953b-3569-480e-9b24-f6b6399cd47f.png)

For some reason I'm getting extra characters showing on all of my menus, as can be seen in the screenshot. anyone else experiencing this? I'm running Powershell on Windows 11.

**Comment by Yattabyte** [comment]
The characters are sequences for colouring the text. Powershell must not support this mechanism, but the windows command prompt does.

**Comment by EricFedrowisch** [comment]
Not a powershell expert, but it looks like it's reading *Nix style CRLF characters and displaying them.
Possible fix:
`$PSStyle.OutputRendering = PlainText`
or
`$PSStyle.OutputRendering = Host`

**Comment by metzo007** [comment]
> The characters are sequences for colouring the text. Powershell must not support this mechanism, but the windows command prompt does.

I have the same error in the windows command prompt :-(

![image](https://user-images.githubusercontent.com/49093328/229906971-2b62ba73-262e-4086-b002-69aff6ab25f9.png)

**Comment by metzo007** [comment]
> Not a powershell expert, but it looks like it's reading *Nix style CRLF characters and displaying them. Possible fix: `$PSStyle.OutputRendering = PlainText` or `$PSStyle.OutputRendering = Host`

how do I use this?

**Comment by metzo007** [comment]
> > The characters are sequences for colouring the text. Powershell must not support this mechanism, but the windows command prompt does.
> 
> I have the same error in the windows command prompt :-(
> 
> ![image](https://user-images.githubusercontent.com/49093328/229906971-2b62ba73-262e-4086-b002-69aff6ab25f9.png)

Hi,

I did try a differend pc but got the same error. Might hat something to do with my german windows. Is there any good alternative to the commandline?

**Comment by EricFedrowisch** [comment]
Yeah, this is tough because cross platform support is a big ask for a single developer. As far as a good alternative, I've heard good things about cygwin.

**Comment by EricFedrowisch** [comment]
That's another excellent idea

**Comment by NiclasMcClymont** [comment]
I am also working on a German console with the same issue. Using the Windows Terminal fixed it. You can install the terminal from the Microsoft Store or by using choco.

To install Windows Terminal, run the following command:
`choco install microsoft-windows-terminal`

Once it is installed, simply start the Windows Terminal and run the script.

**Comment by NiclasMcClymont** [comment]
I am also working on a German console with the same issue. Using the Windows Terminal fixed it. You can install the terminal from the Microsoft Store or by using choco.

To install Windows Terminal, run the following command:
`choco install microsoft-windows-terminal`

Once it is installed, simply start the Windows Terminal and run the script.

**Comment by metzo007** [comment]
> I am also working on a German console with the same issue. Using the Windows Terminal fixed it. You can install the terminal from the Microsoft Store or by using choco.
> 
> To install Windows Terminal, run the following command: `choco install microsoft-windows-terminal`
> 
> Once it is installed, simply start the Windows Terminal and run the script.

that worked thanks :-)
