### ISSUE TITLE
Powerful Command Missing [Human-Agent]

### ISSUE THREAD

**Issue by Djamchid** [Significant-Gravitas/Auto-GPT#1789]
### Discussed in https://github.com/Significant-Gravitas/Auto-GPT/discussions/1703

<div type='discussions-op-text'>

<sup>Originally posted by **TechnicallyWeb3** April 15, 2023</sup>
We have the ability to search the web, analyze websites and create files but have we overlooked the most powerful tool at the AI's disposal? A human agent! I mean we have a magic box that gives us answers, why not provide AI with that same magic box, this way it can offload particularly difficult for AI but easy for human type tasks. Are there plans to add this? Is it already a feature that I've overlooked?

I imagine an AI that might say something like "Can you create a twitter account and post 'Hello World!' for me?" the human agent may respond "You'll be posting to social media alot. You may want to create a script to post for yourself, I've created the account @SocialGPT for you, here are the API keys. {API_KEYS}"</div>

**Comment by Djamchid** [comment]
A human agent could also be sollicited by mail, his answer being taken into account likewise

**Comment by Djamchid** [comment]
see also #1548

**Comment by Djamchid** [comment]
this would be the starting point for TeamGPT

**Comment by JohnnyFi-GPT** [comment]
Yeah but how would you write that script?

**Comment by p92** [comment]
for small human intervention you can already respond to the prompt and inform autoGPT with what you did instead of y ou y -N

**Comment by Djamchid** [comment]
Q: How would you write that script?
R: The list of agents should include human team-members, altogether with
emails. Auto-GPT delegates a given task to a human by email, who answers
alike.

Djamchid

Le dim. 16 avr. 2023, 07:08, JohnnyFi-GPT ***@***.***> a
écrit :

**Comment by ntindle** [comment]
Already works (kinda poorly) but none the less. Additional issues are more detailed on implementation of fixes, so closing in favor of those

**Comment by Djamchid** [comment]
Hi Nicholas,

I'm happy that "Already works (kinda poorly) but none the less. Additional
issues are more detailed on implementation of fixes, so closing in favor of
those" and so I understand fully that you close #1789.
Can you please give an idea of how it "already works" and indicate"
additional more detailed" issue numbers, so that I can contribute.

Many thanks,


     Djamchid DALILI
     Founder & CEO DiamPark (working on Parkinson's disease)
     +33615020076
     https://www.linkedin.com/in/dalili/
     Innovations CES Las Vegas 2023
<https://www.dailymotion.com/playlist/x7pgs0>


Le dim. 23 avr. 2023 à 06:14, Nicholas Tindle ***@***.***> a
écrit :
