### ISSUE TITLE
Issue with missing module 'autogpt' in v0.2.0 Docker image

### ISSUE THREAD

**Issue by theoohoho** [Significant-Gravitas/Auto-GPT#1797]
I built a Docker image using version v0.2.0 of the package, but when I tried to run the container, I received the following error:

```
/usr/local/bin/python: No module named autogpt
```

I noticed that the master branch has already fixed this issue in `Dockerfile`, and it works fine in my local environment.

> **So I’m not here to ask for a solution because I’ve already checked PR [#1229](https://github.com/Significant-Gravitas/Auto-GPT/pull/1229) and know how to work around this error in `v0.2.0`**.

## Would it be possible to release a patch version (like `v0.2.1`) to fix this issue sooner, in case the next release takes too long? This would be really helpful for other users who might encounter the same error in `v0.2.0`.

Thanks!

**Comment by Limsanity** [comment]
modify ./ to ./autogpt [this line](https://github.com/Significant-Gravitas/Auto-GPT/blob/v0.2.0/Dockerfile#L20), then rebuild the image and run.

**Comment by theoohoho** [comment]
> modify [this line](https://github.com/Significant-Gravitas/Auto-GPT/blob/v0.2.0/Dockerfile#L20) to `COPY --chown=appuser:appuser autogpt/ ./autogpt`, then rebuild the image and run.

Thanks for reply, I know how to fix this error 🙂

That's why I mention **master branch**, and say it work fine in my local env.

So the point is that I was wondering if it would be possible to publish a patch version to work around this error.

**Comment by hemangjoshi37a** [comment]
Hi @theoohoho, 

Thank you for reporting the issue with missing module 'autogpt' in v0.2.0 Docker image. As you mentioned, the issue has already been fixed in the master branch by modifying the Dockerfile. However, if you need a solution sooner, you can modify the following line in the Dockerfile:

FROM python:3.8-slim-buster
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
COPY autogpt/ ./autogpt   # modify this line to COPY --chown=appuser:appuser autogpt/ ./autogpt
CMD [ "python", "app.py" ]

After modifying the line, you can rebuild the image and run it.

I hope this helps. Let me know if you have any further questions.

**Comment by theoohoho** [comment]
> Hi @theoohoho,
> 
> Thank you for reporting the issue with missing module 'autogpt' in v0.2.0 Docker image. As you mentioned, the issue has already been fixed in the master branch by modifying the Dockerfile. However, if you need a solution sooner, you can modify the following line in the Dockerfile:
> 
> FROM python:3.8-slim-buster WORKDIR /app COPY requirements.txt . RUN pip install --no-cache-dir -r requirements.txt COPY . . COPY autogpt/ ./autogpt # modify this line to COPY --chown=appuser:appuser autogpt/ ./autogpt CMD [ "python", "app.py" ]
> 
> After modifying the line, you can rebuild the image and run it.
> 
> I hope this helps. Let me know if you have any further questions.

Thanks for reply! 

There must have been something unclear in my original post that caused misunderstanding.

I’ve updated it for clarity. I appreciate the time and effort you, @hemangjoshi37 @Limsanity , have taken to reply.

**Comment by hemangjoshi37a** [comment]
@theoohoho you are most welcome

**Comment by theoohoho** [comment]
I see that @richbeales released version `v0.2.1` in https://github.com/Significant-Gravitas/Auto-GPT/pull/1973. 

Thank you to all the contributors for their hard work. I am going to close this issue.
