### ISSUE TITLE
WE NEED CHINESE！！WE NEED CHINESE！！Thank you!

### ISSUE THREAD

**Issue by callmeiks** [Significant-Gravitas/Auto-GPT#1804]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Could you please include functionality that permits users to input text in Chinese or any other language? Thank you!

**Comment by weiyoubest** [comment]
hahahaha

**Comment by shenqingwangyixuan** [comment]
哈哈哈哈哈哈哈哈哈哈谷歌翻译

**Comment by screamlsj** [comment]
可以输入中文啊。。。

**Comment by callmeiks** [comment]
输入中文给我报错 UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 48-49: invalid continuation byte

**Comment by callmeiks** [comment]
> 哈哈哈哈哈哈哈哈哈哈谷歌翻译

不准确 :(

**Comment by Jun10ng** [comment]
lol, look here
https://github.com/Significant-Gravitas/Auto-GPT/issues/1879

**Comment by Jun10ng** [comment]
> 输入中文给我报错 UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 48-49: invalid continuation byte



> 输入中文给我报错 UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 48-49: invalid continuation byte

别在命令行打字输入，先在编辑器里打好字，然后粘贴复制过去，命令行打中文可能会有隐藏字符

**Comment by loseDemon** [comment]
必须支持中文！！！！！！

**Comment by ntindle** [comment]
Need a pr for it and reviewers for those PRs. Closing in favor of other issues
