### ISSUE TITLE
Selenium is always detected by web services and they denial to serve.

### ISSUE THREAD

**Issue by yurhett** [Significant-Gravitas/Auto-GPT#1807]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Selenium is an automated testing tool. The reason why many web services can detect if a browser is controlled by Selenium is because WebDriver modifies the browser environment to achieve control. autoGPT needs to do some tinkering with Selenium to achieve bypass detection to help AI get more information.

### Examples 🌈

https://fingerprint.com/products/bot-detection/
This site is a provider of a detection service used by many sites to verify that browsers are not bot traffic, and if you Google it, you can find a number of bypass detection options to choose from, so feel free to try to bypass detection.

### Motivation 🔦

Enable AI to browse the Internet unimpeded.

**Comment by ntindle** [comment]
This is expected behavior for now
