### ISSUE TITLE
 Command browse_website returned: Error: Message: unknown error: cannot connect to chrome at 127.0.0.1:33210 from chrome not reachable Stacktrace: Backtrace: GetHandleVerifier

### ISSUE THREAD

**Issue by z-x-x136** [Significant-Gravitas/Auto-GPT#1811]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 112.0.5615
[WDM] - Get LATEST chromedriver version for 112.0.5615 google-chrome
[WDM] - Driver [C:\Users\Zeng xiang xi\.wdm\drivers\chromedriver\win32\112.0.5615.49\chromedriver.exe] found in cache
SYSTEM:  Command browse_website returned: Error: Message: unknown error: cannot connect to chrome at 127.0.0.1:33210 from chrome not reachable Stacktrace: Backtrace: GetHandleVerifier 
[0x0093DCE3+50899] (No symbol) [0x008CE111] (No symbol) [0x007D5450] (No symbol) [0x007CB2B5] (No symbol) [0x007F51C8] (No symbol) [0x007EF5B1] (No symbol) [0x007EF391] (No symbol) [0x
00821FFE] (No symbol) [0x00821CEC] (No symbol) [0x0081B6F6] (No symbol) [0x007F7708] (No symbol) [0x007F886D] 
GetHandleVerifier [0x00BA3EAE+2566302] GetHandleVerifier [0x00BD92B1+27844
17] GetHandleVerifier [0x00BD327C+2759788] GetHandleVerifier [0x009D5740+672048] (No symbol) [0x008D8872] (No symbol) [0x008D41C8] (No symbol) [0x008D42AB] (No symbol) [0x008C71B7] Bas
eThreadInitThunk [0x75DC0099+25] RtlGetAppContainerNamedObjectPath [0x779C7B6E+286] RtlGetAppContainerNamedObjectPath [0x779C7B3E+238]

I changed the parameters of web.py
![微信截图_20230416152925](https://user-images.githubusercontent.com/87004536/232280540-0651b3ab-04ac-4961-91cb-cbc8e6631336.png)

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Pwuts** [comment]
Is this still an issue with the latest version of `master`?

**Comment by ntindle** [comment]
Reopen if issue persists
