### ISSUE TITLE
where is the MILVUS_ADDR at zilliz?

### ISSUE THREAD

**Issue by E7ANA** [Significant-Gravitas/Auto-GPT#1812]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

I'm trying to use milvus by zilliz due to the fact pinecone closed registration.
can't find the place to take the MILVUS_ADDR from.
thanks

**Comment by chyezh** [comment]
you can get a public cloud end-point uri in admin console at Database Details tab.

https://zilliz.com/doc/quick_start

**Comment by LeonXu72** [comment]
I also use Milvus by Zilliz and the issue seems cannot be solved by putting in the pubilc endpoint.

`File "/opt/homebrew/lib/python3.11/site-packages/pymilvus/orm/connections.py", line 159, in __get_full_address
    raise ConnectionConfigException(message=f"Illegal address: {address}, should be in form 'localhost:19530'")'
'pymilvus.exceptions.ConnectionConfigException: <ConnectionConfigException: (code=1, message=Illegal address: https://------------------4e.gcp-us-west1.vectordb.zillizcloud.com:443, should be in form 'localhost:19530')>
`

**Comment by chyezh** [comment]
I will produce a PR to support zilliz today.

**Comment by Kenneth-zh** [comment]
> 我也使用 Zilliz 的 Milvus，这个问题似乎无法通过放入 pubilc 端点来解决。
> 
> `File "/opt/homebrew/lib/python3.11/site-packages/pymilvus/orm/connections.py", line 159, in __get_full_address raise ConnectionConfigException(message=f"Illegal address: {address}, should be in form 'localhost:19530'")' 'pymilvus.exceptions.ConnectionConfigException: <ConnectionConfigException: (code=1, message=Illegal address: https://------------------4e.gcp-us-west1.vectordb.zillizcloud.com:443, should be in form 'localhost:19530')> `

I have encountered the problem, too

**Comment by Kenneth-zh** [comment]
Have you got solution?

**Comment by chyezh** [comment]
@Kenneth-zh @LeonXu72 
in autogpt/memory/milvus.py
try to change params of connect function.
change `addr=xxxx` to `uri=xxxx`

**Comment by akash9182** [comment]
changing  does not solve the problem `connections.connect(address=cfg.milvus_addr)` to `connections.connect(uri=cfg.milvus_addr)` does not solve the problem

**Comment by chyezh** [comment]
@akash9182 zilliz support PR is here #2127, try it.

**Comment by akash9182** [comment]
Thanks for the help, it works now. The issue was I did not setup a billing account with OpenAI.

**Comment by ntindle** [comment]
Fix in comments
