### ISSUE TITLE
How to use a proxy and where to configure it?（v2rayN)

### ISSUE THREAD

**Issue by xillkoi** [Significant-Gravitas/Auto-GPT#182]
raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

**Comment by CaltonRen** [comment]
I encountered the same problem. Have you solved your problem?

**Comment by xillkoi** [comment]
> 我遇到了同样的问题。你解决了你的问题吗？

no

**Comment by kjwlegend** [comment]
you just need to set v2ray proxy to run in global mode instead of PAC or whitelist

**Comment by Explorergt92** [comment]
@xillkoi is this still an issue for you or can this be closed?

**Comment by Pwuts** [comment]
Close as stale. Please reopen if still relevant.

**Comment by XIYANGYANG-ZHI** [comment]
> you just need to set v2ray proxy to run in global mode instead of PAC or whitelist

Still the same problem

**Comment by Pwuts** [comment]
@XIYANGYANG-ZHI does that work for you? ^
