### ISSUE TITLE
wrong webserver start command

### ISSUE THREAD

**Issue by louria** [Significant-Gravitas/Auto-GPT#1847]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

NEXT ACTION:  COMMAND = evaluate_code ARGUMENTS = {'code': 'python -m http.server'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
SYSTEM:  Command evaluate_code returned: Error: The model: `gpt-4` does not exist

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by louria** [comment]
Here is the prompt 

SYSTEM:  Command evaluate_code returned: Error: The model: `gpt-4` does not exist
 THOUGHTS:  Let's now start a Python HTTP server to deploy the website on a local server. We can use the command 'python -m http.server' in the same directory where the 'index.html' file is located. Once the server is running, we can open a web browser and go to 'http://localhost:8000' to see the website.
REASONING:  Deploying the website on a local server allows us to see how it looks and test its functionality.
PLAN:
-  Start a Python HTTP server using the command 'python -m http.server'
-  Open a web browser and go to 'http://localhost:8000' to see the website
CRITICISM:  None

**Comment by Qoyyuum** [comment]
Which webserver start command is right?

**Comment by ntindle** [comment]
Sometimes it executes something unexpected or doesn’t do what you want.  Check out the #prompt-engineering channel in discord to get a better fit prompt
