### ISSUE TITLE
constant errors tried many things but didnt work

### ISSUE THREAD

**Issue by AayushGoyal22** [Significant-Gravitas/Auto-GPT#1855]
### Duplicates

- [X] I have searched the existing issues

### Your prompt 📝

```yaml
![image_2023-04-16_165446806](https://user-images.githubusercontent.com/74131809/232306625-bb43bfe1-ed03-4b77-947f-1db3a2eb069a.png)

```

**Comment by Qoyyuum** [comment]
What's the problem? How do you get it not working? Did you set up correctly? What were you expecting to work?

**Comment by AayushGoyal22** [comment]
> What's the problem? How do you get it not working? Did you set up correctly? What were you expecting to work?

I think it was code I told it to write I followed all the steps and it normally works but then sometimes this happens
![16817379517596186398314888051679](https://user-images.githubusercontent.com/74131809/232497750-e3dab612-b2d1-45b8-800f-586f0b535f49.jpg)

**Comment by Qoyyuum** [comment]
It looks like it had it's connection dropped. Can you attach and send the
logs please?
