### ISSUE TITLE
Check if all the webdriver libraries are needed in the Dockerfile, optimize if possible

### ISSUE THREAD

**Issue by psvensson** [Significant-Gravitas/Auto-GPT#1861]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

This might not be the right format for this, but a recent PR by me added some quite large libraries to the dockerfile to fix a bug where browse_website was broken;

RUN apt-get install -y libglib2.0 libnss3 libgconf-2-4 libfontconfig1 chromium-driver

It would be good, when we have time, to go over these and see if all really are needed

### Current behavior 😯

The Docker image is now 1.36GB

### Expected behavior 🤔

it would be nice to make it smaller

### Your prompt 📝

```yaml
# no prompt for this
```

**Comment by Cytranics** [comment]
There is zero QA on this project. They commit typos, which means there is no regression testing. This dude has zero experience with a project this popular

**Comment by psvensson** [comment]
But @bvoo managed to fix this already and have modified my PR with the above, so the community is stepping in a bit I guess. But yes, there need to be some more structure for sure
