### ISSUE TITLE
Add option to allow access outside of working directory

### ISSUE THREAD

**Issue by Josh-XT** [Significant-Gravitas/Auto-GPT#1862]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Yeah, I know, probably not always ideal, but having this thing limited to a working directory that it can't seem to access half the time is not ideal.  It would be good to have an option to bypass this safety with an environment variable that can allow people to give it the option to read and write files anywhere it wants.

I personally run Auto-GPT in an Ubuntu VM that I set up for the sole purpose of letting it break itself if it needs to.  It isn't ideal for everyone to have this on, but it would be helpful to have as an option.

### Examples 🌈

```
Executing command 'ls ~/Agent' in working directory '/home/josh/Auto-GPT/autogpt/auto_gpt_workspace'
SYSTEM:  Command execute_shell returned: STDOUT: b'' STDERR: b"ls: cannot access '/home/josh/Agent': No such file or directory\n"
```

### Motivation 🔦

Easier to allow it to work with existing files than making duplicates in its workspace.

**Comment by Josh-XT** [comment]
It made it unusable for my use case, so I put in pull request #1875 to remove the working directory restrictions.  I still suggest making them into environment variables for people who care about restricting it to a working directory.

**Comment by Josh-XT** [comment]
Ended up adding the environment variable to my PR to make it easier to get it pushed through.

**Comment by Pwuts** [comment]
The issue in your example is with determining the path of the `auto_gpt_workspace`, not with accessing files outside the workspace. Of course it wouldn't be able to directly access ~/Agent, because it is outside of the workspace, but the `ls` command should succeed once the aforementioned issue in `execute_shell` is fixed.
