### ISSUE TITLE
The way this project is managed.... 

### ISSUE THREAD

**Issue by Cytranics** [Significant-Gravitas/Auto-GPT#1863]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

What the heck is going on. I'm starting to think that chatGPT built most of this code and OP when viral. Let's have some management and proper QA around these commits guys. Randomly commiting crap on the master while the stable is not the default. Y'all ever managed a project prior to this?

No instructions for users to install chrome, missing packages in the requirements... Yesterday someone finally started to organize the folders but this morning a who bunch of random crap in there now. 

You have quality people making good commits that go days..... Typos are getting committed..... Wtf

### Examples 🌈

Open the folder

### Motivation 🔦

Hope for the project

**Comment by p-i-** [comment]
Some excellent points here.

There is, however, no benefit in being adversarial / combative / rude. What is being served? Are you looking down upon the project from some high place with scorn? To what end?

You seem to have a high expectation of progress for a 2-week old open source project created by a single individual.

I'm closing the issue, as good content is imbued with toxicity.

Your points have, however, been noted. wip. Chill rasta. Patience.
