### ISSUE TITLE
Default to GPT-3.5

### ISSUE THREAD

**Issue by slavakurilyak** [Significant-Gravitas/Auto-GPT#187]
Given the latest [commit](https://github.com/Torantulino/Auto-GPT/commit/51e293f64cf17efbbba18965037a8004387945a6) and wider availability of GPT3.5 for most developers, it would be great to see Auto-GPT use GPT-3.5, not GPT-4, as the default model. This will help avoid `Command evaluate_code returned: Error: The model: gpt-4 does not exist` [errors](https://github.com/search?q=repo%3ATorantulino%2FAuto-GPT+The+model%3A+gpt-4+does+not+exist&type=issues).

**Comment by EricFedrowisch** [comment]
You raise interesting points. Those without GPT-4 cannot use this at all atm. However, it seems better in the short term to fix the blocking bugs and allow users a choice in models rather than setting either as default. 
On the other hand, GPT-4 does cost [more per token](https://openai.com/pricing). 3.5 Turbo is about 15 times cheaper or more atm.

**Comment by EricFedrowisch** [comment]
The difficulty, it seems to me, is that setting a default is hard. You don't know whether a user prefers "smarter" but more expensive answers or if "dumber" but cheaper answers will suffice.

**Comment by Jegorex** [comment]
You can run in GPT3.5 only mode by starting with `python scripts/main.py --gpt3only`

**Comment by kingcharlezz** [comment]
> You can run in GPT3.5 only mode by starting with `python scripts/main.py --gpt3only`

The code evaluate tool for some reason still tries to use gpt 4 while in gpt3.5 mode. Not sure if this is a mandatory intelligence decision or just a bug.

**Comment by EricFedrowisch** [comment]
@Jegorex Yes! You are correct. Changing the .env file worked.
`
OPENAI_API_KEY=your-openai-api-key
ELEVENLABS_API_KEY=your-elevenlabs-api-key
SMART_LLM_MODEL="gpt-3.5-turbo"
FAST_LLM_MODEL="gpt-3.5-turbo"
GOOGLE_API_KEY=
CUSTOM_SEARCH_ENGINE_ID=
`

**Comment by Adrien2112** [comment]
I have encountered this error while having a gpt-4 access in the account linked to my open ai api key.

**Comment by holbizmetrics** [comment]
Use python3 like this:

`python3.10.exe .\scripts\main.py`

Older versions may not know those imports.
This may immediately make your error go away.

**Comment by Explorergt92** [comment]
@slavakurilyak is this still an issue for you or can this be closed?
