### ISSUE TITLE
没有找到ai_settings.yaml

### ISSUE THREAD

**Issue by gaye746560359** [Significant-Gravitas/Auto-GPT#1871]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

下载0.2.0代码文件，目录下没有找到ai_settings.yaml。但是我发现项目需要这个文件

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Jun10ng** [comment]
这个文件是输入 ai 设定之后才会生成的，不会被git记录。
你想实现什么功能呢？

**Comment by gaye746560359** [comment]
> 这个文件是输入 ai 设定之后才会生成的，不会被git记录。
> 
> 你想实现什么功能呢？

哦，那我可能理解错了。
之前有个prompt.txt，我可以翻译为中文，使得输出都是中文，但是0.2.0版本里面没了。放在哪里了？

**Comment by kinance** [comment]
@gaye746560359 你试过输入目标吗？之后该文件将自动保存。
