### ISSUE TITLE
Support ai log in mutli language

### ISSUE THREAD

**Issue by Jun10ng** [Significant-Gravitas/Auto-GPT#1879]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Add google translate function call when ai logging.
Just translate logging text, NOT modify the origin value.

### Examples 🌈

```
Using memory of type:  LocalCache
Using Browser:  chrome
 想法：  我需要看看是否可以使用requests来请求api。我将首先在谷歌上搜索“python requests package”
推理：  我需要找出 requests 库是否可以帮助我实现我的目标，所以我需要使用互联网来研究和查找有关这是否可能的信息
计划： 
-  执行谷歌搜索'python requests package'
-  访问相关网站以了解其功能
-  判断它能否完成我需要它完成的任务
-  如果是，继续实施，如果不是，考虑其他选择
批评：  没有任何
说话：  我打算用谷歌搜索“python requests package”，看它是否能帮助我找到我要找的东西。
```

### Motivation 🔦

Peace and love.

**Comment by Jun10ng** [comment]
https://github.com/Significant-Gravitas/Auto-GPT/issues/1563

**Comment by ntindle** [comment]
Duplicate

**Comment by Jun10ng** [comment]
> Duplicate

hi master, could I ask this pr duplicates with which pr ？
