### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by tagrsize** [Significant-Gravitas/Auto-GPT#1883]
https://github.com/Significant-Gravitas/Auto-GPT/blob/master/README.md

Under Command Line Arguments:
https://github.com/Significant-Gravitas/Auto-GPT/blob/master/README.md#command-line-arguments

Update outdated references to scripts/main.py since that path no longer exists

```
View all available command line arguments
python scripts/main.py --help
```

**Comment by nponeccop** [comment]
Should be fixed now. Reopen if it isn't
