### ISSUE TITLE
Just doesn't do anything

### ISSUE THREAD

**Issue by MontyFlange** [Significant-Gravitas/Auto-GPT#1885]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Set up a search added the 5 parameters and ran it

### Current behavior 😯

All I get on every attempt is

Traceback (most recent call last):
  File "D:\AI SOFTWARE\AutoGPT\Auto-GPT\scripts\main.py", line 465, in <module>
    main()
  File "D:\AI SOFTWARE\AutoGPT\Auto-GPT\scripts\main.py", line 328, in main
    agent.start_interaction_loop()
  File "D:\AI SOFTWARE\AutoGPT\Auto-GPT\scripts\main.py", line 369, in start_interaction_loop
    assistant_reply = chat.chat_with_ai(
  File "D:\AI SOFTWARE\AutoGPT\Auto-GPT\scripts\chat.py", line 126, in chat_with_ai
    assistant_reply = create_chat_completion(
  File "D:\AI SOFTWARE\AutoGPT\Auto-GPT\scripts\llm_utils.py", line 50, in create_chat_completion
    raise RuntimeError("Failed to get response after 5 retries")
RuntimeError: Failed to get response after 5 retries

### Expected behavior 🤔

Results of the search

### Your prompt 📝

```yaml
# Paste your prompt here
```
no idea

**Comment by Qoyyuum** [comment]
@MontyFlange if you run it with `--debug`, you might see `Error: API Rate Limit...`

This can be solved with having a paid OpenAI account (note: not the same as ChatGPT plus).

**Comment by MontyFlange** [comment]
OK with a paid plan I now get this

SYSTEM:  Command Error: threw the following error: 'dict' object has no attribute 'replace'
  Warning: Failed to parse AI output, attempting to fix.
 If you see this warning frequently, it's likely that your prompt is confusing the AI. Try changing it up slightly.
Failed to fix AI output, telling the AI.
Error: Invalid JSON
  Sure, I can help you with that. Do you have any specific tasks or goals in mind that you would like me to help with?
Attempting to fix JSON by finding outermost brackets
Error: Invalid JSON, setting it to empty JSON now.

MAKE THOUGHTS:
REASONING:
CRITICISM:
Attempting to fix JSON by finding outermost brackets
Error: Invalid JSON, setting it to empty JSON now.

**Comment by Qoyyuum** [comment]
Original issue is fixed, I'll close this issue. For the new issue, please run `--debug` and pass in your prompt and attach your log files for easier reference to diagnose the problem in a new Github issue.
