### ISSUE TITLE
Auto-gpt tries to write file with invalid name and content

### ISSUE THREAD

**Issue by villesau** [Significant-Gravitas/Auto-GPT#1889]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

1. write a prompt that requires to write stuff to file
2. following command is generated: `NEXT ACTION:  COMMAND = write_to_file ARGUMENTS = {'file': '<file_name>', 'text': '<information>'}`
  - Note that the file it tries to write is actually `<file_name>` (i validated this from the disk) and the information written is actually `<information>` (i validated this from the written file)
  
Thus, no actual information is stored.

### Current behavior 😯

writing to file results in weird file name and no actual information to be stored in the file, only placeholders.

### Expected behavior 🤔

The actual information should be stored with proper file name.

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Pwuts** [comment]
The command is generated by the language model, which is supposed to fill in the blanks. If it doesn't that isn't necessarily a problem with Auto-GPT.

**Comment by villesau** [comment]
I'm not sure about the architecture of auto-gpt, but maybe that could be sorted out by adjusting the prompt to clarify things about filling in the blanks?

**Comment by wrexbe** [comment]
If you think about the way this is worded "write a prompt that requires to write stuff to file"

write a prompt -> respond to me with a template
that required -> me, the human to do something
to write stuff to file -> to fill in a prompt

So your wording choice is probably just poor

**Comment by villesau** [comment]
I actually never asked auto-gpt to write files, it decided to do so independently, probably for caching purposes or something.

I think this only happens on master, not on stable.

**Comment by wrexbe** [comment]
Okay so it gave itself a bad command then?

**Comment by villesau** [comment]
I guess that's the case. But in my case it did that every time, not just occasionally.

**Comment by omphos** [comment]
> 

LLMs don't provide clean data. Neither does anything with greater complexity than a pocket calculator. Even then half a cupcake gets wedged in the buttons somehow. Never assume you're getting a clean file name from anything or anyone. Especially your mother. It has to be checked. Everything has to be verified because this entire planet is completely diseased. From a data standpoint.

"Did You Fall Down And Smack Your Little Head On The Pavement?" - Cassandra Priestley

**Comment by Pwuts** [comment]
Closing as this is just the GPT outputting bad commands, nothing we can do about that directly. If anyone has proposals for more effective prompts, please create a separate issue or PR for that.
