### ISSUE TITLE
Why do I get this error?

### ISSUE THREAD

**Issue by Loser02** [Significant-Gravitas/Auto-GPT#189]
Why do i keep getting "API rate limit reached. Retrying in 10 seconds" error? Just a question. Never used an API key before

**Comment by stayupthetree** [comment]
Do you have an API key setup with OpenAPI? If so, do you have usage available or setup a payment account?

**Comment by doesnots** [comment]
@Loser02 it might be possible that your OpenAI API key has reached its limit(expired), you can check it here https://platform.openai.com/account/usage. In that case, you may keep on getting those errors.

**Comment by JuroOravec** [comment]
Duplicate of https://github.com/Torantulino/Auto-GPT/issues/1189. @Loser02 would you close this one issue if it indeed is the same thing?

(I had this issue too - It's that we haven't [opted into "paid account" on OpenAI's billing page](https://platform.openai.com/account/billing/overview))

I'm making an MR as we speak to update the README section on OpenAI's API key, to make this clear.

**Comment by Explorergt92** [comment]
@Loser02 is this still an issue for you or can this be closed?

**Comment by Loser02** [comment]
It's fixed now
