### ISSUE TITLE
Screwed up the installation

### ISSUE THREAD

**Issue by sjnt1** [Significant-Gravitas/Auto-GPT#1890]
I tried to delete my old autoGPT that i downloaded and updated  by zip file, and download the new version by cloning git rep, but i cant get it to work. 

When i run python -m autogpt i get this error message: 

PS C:\AutoGPT\auto-gpt> python -m autogpt
Weaviate not installed. Skipping import.
pymilvus not installed. Skipping import.
Warning: The file 'auto-gpt.json' does not exist.Local memory would not be saved to a file.
Traceback (most recent call last):
  File "C:\Users\sindr\AppData\Local\Programs\Python\Python311\Lib\site-packages\git\__init__.py", line 89, in <module>
    refresh()
  File "C:\Users\sindr\AppData\Local\Programs\Python\Python311\Lib\site-packages\git\__init__.py", line 76, in refresh
    if not Git.refresh(path=path):
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sindr\AppData\Local\Programs\Python\Python311\Lib\site-packages\git\cmd.py", line 392, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\AutoGPT\auto-gpt\autogpt\__main__.py", line 4, in <module>
    from autogpt.agent.agent import Agent
  File "C:\AutoGPT\auto-gpt\autogpt\agent\__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "C:\AutoGPT\auto-gpt\autogpt\agent\agent.py", line 2, in <module>
    from autogpt.app import execute_command, get_command
  File "C:\AutoGPT\auto-gpt\autogpt\app.py", line 26, in <module>
    from autogpt.commands.git_operations import clone_repository
  File "C:\AutoGPT\auto-gpt\autogpt\commands\git_operations.py", line 2, in <module>
    import git
  File "C:\Users\sindr\AppData\Local\Programs\Python\Python311\Lib\site-packages\git\__init__.py", line 91, in <module>
    raise ImportError("Failed to initialize: {0}".format(exc)) from exc
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

PS C:\AutoGPT\auto-gpt>

**Comment by Qoyyuum** [comment]
Hi @sjnt1 please reinstall your git and try again.

**Comment by sjnt1** [comment]
When you say reinstall do you mean to delete it and clone it again? 

Do i have to take any other steps to remove my old version that i downloaded by zip?

**Comment by sjnt1** [comment]
But yeah i just deleted it and downloaded it again, rand the instructions and ran requirements.txt again, got the same error.

**Comment by sjnt1** [comment]
For the record i installed the new version on another file path than the old one. The old one was on my desktop and got in trouble with onedrive.

**Comment by Qoyyuum** [comment]
@sjnt1 you have to download and install git. https://git-scm.com/

**Comment by sjnt1** [comment]
got it to work by setting the branch in github to stable not master. Had to do that even if i downloaded the stable.  

Will get git.

**Comment by HanyangZhong** [comment]
Sorry I have the same problem and I still cannot fix. I dont know how to reinstall git because I didn't install it before. Now I install the git but it still goes wrong. How can I fix that?

**Comment by sjnt1** [comment]
Have you tried doing what i did to fix it? In github, change master to stable.

**Comment by HanyangZhong** [comment]
Me too, after I use stable 0.2.1, the issue occurred.

**Comment by k-boikov** [comment]
Can you please verify that downloading and installing git from https://git-scm.com/ doesn't fix the issue?

**Comment by HanyangZhong** [comment]
yes, I try downloaded the git but it still not working.

**Comment by sjnt1** [comment]
@HanyangZhong did you install git from https://git-scm.com/ ? Its something different than github. 

I can confirm that installing git and restarting windows FIXED it for me. Leaving the issue open for a while until mr hanyang gets it fixed

**Comment by HanyangZhong** [comment]
Thank you @sjnt1 . You remained me that I haven't restrat my computer. Now it works. Awesome!

**Comment by Bigrussian8** [comment]
I had this issue but fixed it by reinstalling the requirements.txt file
