### ISSUE TITLE
The file 'AutoGpt.json' does not exist.

### ISSUE THREAD

**Issue by Chospo** [Significant-Gravitas/Auto-GPT#1893]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

When launching AutoGPT I get the following lines, the first 2 are expected, but the last one is confusing. How can I 'create' the file?

Weaviate not installed. Skipping import.
pymilvus not installed. Skipping import.
**Warning: The file 'AutoGpt.json' does not exist.Local memory would not be saved to a file.**

Many thanks,
Chospo

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Qoyyuum** [comment]
Hi @Chospo . It's just a warning. But if you wanna get rid of it, just create an empty `auto-gpt.json` file in the root of the AutoGPT folder. Otherwise, just ignore it.

**Comment by danielbakas** [comment]
> Hi @Chospo . It's just a warning. But if you wanna get rid of it, just create an empty `auto-gpt.json` file in the root of the AutoGPT folder. Otherwise, just ignore it.

This didn't fix the issue as the name should be `autogpt.json` and not `auto-gpt.json`. Small difference, but one works and the other doesn't. Hope this helps 😋
