### ISSUE TITLE
Get stuck in a loop

### ISSUE THREAD

**Issue by MagnusTriolith** [Significant-Gravitas/Auto-GPT#1899]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Tell the bot to create a marketing strategy for my company triolith games

### Current behavior 😯

I'm trying to create a marketing strategy for my company Triolith Games as a test to see what it could come up with. I let it run for a bit and it browses our website, checks twitter (wrong account though, even though i told it the correct one) it creates a few files etc but then it seems like it get's stuck in a loop and just redo it all again from scratch, ie checking our website and twitter. So not sure what's going on. 

I'm using the latest release and running it localy without docker.

### Expected behavior 🤔

That is should sometime stop once done and not just repeat the process. 

### Your prompt 📝

Sadly couldn't find it but it was similar to
Dave
Create a marketing strategy for my company triolith games and the engine we are building for game developers and gamers called the genesis engine.

Goals was to make competitor research
create a strategy for tiktok, twitter and other social media accounts 
and so on.

**Comment by ntindle** [comment]
Sometimes it executes something unexpected or doesn’t do what you want.  Check out the #prompt-engineering channel in discord to get a better fit prompt
