### ISSUE TITLE
apparently json is fixed

### ISSUE THREAD

**Issue by iplayfast** [Significant-Gravitas/Auto-GPT#1908]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

When using autogtp during first reponse it says
Attempting to fix JSON by finding outermost brackets 
Apparently json was fixed. 

No idea why it says this, but it looks like something that should be removed.

### Current behavior 😯

odd

### Expected behavior 🤔

not odd

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by xx255q** [comment]
It will go back to having issues

**Comment by Qoyyuum** [comment]
You can ignore it for now. Its a way of handling request and responses between AutoGPT and OpenAI to ensure that its main way of communicating is JSON format. See #1407 for more info.

Closing issue for now.
