### ISSUE TITLE
requests.exceptions.SSLError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

### ISSUE THREAD

**Issue by RaiderYi** [Significant-Gravitas/Auto-GPT#1909]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

![image](https://user-images.githubusercontent.com/30034468/232322021-ba50b2e6-fe41-4b63-b7c5-fab9a8122d0c.png)
![image](https://user-images.githubusercontent.com/30034468/232322029-782bd562-2220-4c74-bd60-91f5a5cd649a.png)
here is the problem,anybody could solve this one?
Thank you !

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by zhinengji1** [comment]
pip install urllib3==1.25.11

**Comment by ntindle** [comment]
Needs more info. Reopen with logs and `—debug`

**Comment by XudongLiu** [comment]
> pip install urllib3==1.25.11

this works for me

**Comment by xiaqu-stone** [comment]
> pip install urllib3==1.25.11
it works for me as well

**Comment by youngfreeFJS** [comment]
> pip install urllib3==1.25.11

Why lock this version? whats differents? @zhinengji1

**Comment by zhinengji1** [comment]
now exactly, but I was looking online and I saw someone talk about doing it




---Original---
From: ***@***.***&gt;
Date: Mon, May 15, 2023 10:44 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Significant-Gravitas/Auto-GPT] requests.exceptions.SSLError:HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Maxretries exceeded with url: /encodings/cl100k_base.tiktoken (Caused bySSLError(SSLEOFError(8, 'EOF occurred in violation of protocol(_ssl.c:1129)'))) (Issue #1909)




  
pip install urllib3==1.25.11
  
Why lock this version? whats differents? @zhinengji1

**Comment by Kccarr6022** [comment]
What was the solution??? URLLib3 1.25.11 does not fix this issue

**Comment by jsteinberg-rbi** [comment]
nope
