### ISSUE TITLE
We demand plugins SDK

### ISSUE THREAD

**Issue by iva-nova-e-katerina** [Significant-Gravitas/Auto-GPT#1911]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

We need a way to extend Auto-GPT for business tasks, for that we need a plugin system.

### Motivation 🔦

To employ Auto-GPT for a wide range of business tasks

**Comment by p-i-** [comment]
It's on its way. 1-2d. Watch this space.

**Comment by SargeDGz** [comment]
its already being worked on by one of the core team I believe and they already have a repo setup for when they are ready 
( https://github.com/Significant-Gravitas/Auto-GPT-Plugins )
