### ISSUE TITLE
GPT asks for root password

### ISSUE THREAD

**Issue by yahuuuuuuu** [Significant-Gravitas/Auto-GPT#1918]
### Duplicates

- [ ] I have searched the existing issues

### Steps to reproduce 🕹

After I set EXECUTE_LOCAL_COMMANDS to True in .env
The program asks me for the root password while it is running
When I type it in, the program gets stuck and does not continue
My OS is Ubuntu20.04

### Current behavior 😯

NEXT ACTION:  COMMAND = execute_shell ARGUMENTS = {'command_line': 'sudo su'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
Input:y

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Qoyyuum** [comment]
can you attach your log here as well?

**Comment by yahuuuuuuu** [comment]
SYSTEM:  Command execute_shell returned: STDOUT: b'Not running as root\n' STDERR: b''
 THOUGHTS:  I am not currently logged in as a superuser. I will switch to the superuser account so that I can clone the repository.
REASONING:  Switching to the superuser account will give me the necessary permissions to clone the repository.
PLAN: 
-  Switch to the superuser account
-  Clone the repository with sample code for ************
-  Read through the code to understand how it works
-  Modify the code to suit my needs
CRITICISM:  I need to be careful when switching to the superuser account and make sure that I only use it for tasks that require elevated permissions.
SPEAK:  I will switch to the superuser account so that I can clone the repository.
Attempting to fix JSON by finding outermost brackets 
Apparently json was fixed. 
NEXT ACTION:  COMMAND = execute_shell ARGUMENTS = {'command_line': 'sudo su'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
Input:y

**Comment by yahuuuuuuu** [comment]
^CTraceback (most recent call last):
  File "/home/***/anaconda3/envs/autogpt/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/***/anaconda3/envs/autogpt/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/***/Auto-GPT/autogpt/__main__.py", line 53, in <module>
    main()
  File "/home/***/Auto-GPT/autogpt/__main__.py", line 49, in main
    agent.start_interaction_loop()
  File "/home/***/Auto-GPT/autogpt/agent/agent.py", line 159, in start_interaction_loop
    f"{execute_command(command_name, arguments)}"
  File "/home/***/Auto-GPT/autogpt/app.py", line 178, in execute_command
    return execute_shell(arguments["command_line"])
  File "/home/***/Auto-GPT/autogpt/commands/execute_code.py", line 109, in execute_shell
    result = subprocess.run(command_line, capture_output=True, shell=True)
  File "/home/***/anaconda3/envs/autogpt/lib/python3.10/subprocess.py", line 505, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/home/***/anaconda3/envs/autogpt/lib/python3.10/subprocess.py", line 1154, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/home/***/anaconda3/envs/autogpt/lib/python3.10/subprocess.py", line 2005, in _communicate
    ready = selector.select(timeout)
  File "/home/***/anaconda3/envs/autogpt/lib/python3.10/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt

**Comment by yahuuuuuuu** [comment]
and in my notion ,it should'n ask for root in "git clone"

**Comment by sudouser777** [comment]
@yahuuuuuuu is it asking for the root password if you manually run `git clone` in terminal

**Comment by qiangziakbar** [comment]
SAME PAIN here!!! I need it to run all kinds of works, and I even tell it my root password to avoid this happen, sometimes it does work, you could see it solve this problem by using `echo XXXX  sudo apt install XXXX` most time it pumps up and let me input password, totally a pain

**Comment by qiangziakbar** [comment]
another funny STUCK!
we all know for some softwares, you need to input `y` to check agreements, that will stuck Auto-GPT too!!!

**Comment by yahuuuuuuu** [comment]
> another funny STUCK!
> we all know for some softwares, you need to input `y` to check agreements, that will stuck Auto-GPT too!!!

if you can show me the log after press ctrl+c？I guess may subprogess load Enter we pressed as ”\n”

**Comment by yahuuuuuuu** [comment]
@sudouser777 absolutely not

**Comment by zudsniper** [comment]
Seemingly having the same issue. It's doing it's trying !!

```
NEXT ACTION:  COMMAND = execute_shell ARGUMENTS = {'command_line': 'sudo apt-get install -y <dependency>'}
Executing command 'sudo apt-get install -y <dependency>' in working directory '/home/appuser/auto_gpt_workspace'
SYSTEM:  Command execute_shell returned: STDOUT: b'' STDERR: b'/bin/sh: 1: Syntax error: end of file unexpected\n'
 THOUGHTS:  Now that the CLI tool package has been generated, I will use the 'execute_shell' command to install the package and make the tool available for use.
REASONING:  Installing the CLI tool package will make the tool available for use and allow me to test its functionality.
PLAN:
-  Use the 'execute_shell' command to install the CLI tool package.
-  Test the functionality of the CLI tool to ensure that it is working properly.
CRITICISM:  I need to ensure that the installation process is successful and that the CLI tool is properly configured.
NEXT ACTION:  COMMAND = execute_shell ARGUMENTS = {'command_line': 'sudo dpkg -i /path/to/agpt-pkg.deb'}
Executing command 'sudo dpkg -i /path/to/agpt-pkg.deb' in working directory '/home/appuser/auto_gpt_workspace'
SYSTEM:  Command execute_shell returned: STDOUT: b'' STDERR: b'/bin/sh: 1: sudo: not found\n'
 THOUGHTS:  I will use the 'execute_shell' command to install the CLI tool package using the 'apt-get' package manager.
REASONING:  Using the 'apt-get' package manager will allow me to install the CLI tool package and ensure that it is properly configured.
PLAN:
-  Use the 'execute_shell' command to install the CLI tool package using the 'apt-get' package manager.
-  Test the functionality of the CLI tool to ensure that it is working properly.
CRITICISM:  I need to ensure that the installation process is successful and that the CLI tool is properly configured.
NEXT ACTION:  COMMAND = execute_shell ARGUMENTS = {'command_line': 'sudo apt-get install -y agpt-pkg'}
Executing command 'sudo apt-get install -y agpt-pkg' in working directory '/home/appuser/auto_gpt_workspace'
SYSTEM:  Command execute_shell returned: STDOUT: b'' STDERR: b'/bin/sh: 1: sudo: not found\n'
```  
---

This is the soft loop it got itself into after I was watching it get bothered by permissions for a while. Perhaps there's `commons` package missing from this docker image? 
I wrote a (fairly bad) wrapper for another better but still probably unnecessary wrapper in `AutoGPT-Package`, so I'm running this in whatever a `kurtosis enclave` is. I can't see it being anything other than a permissions issue for the account that's linked in right? Just seems like the classic "docker image doesn't have sudo" thing. 

Regardless, I'll circle back if I find a solution on my own, but it's nice to see that it's being actively looked into. 

Cheers, if I can help / someone wants to work on this issue collaboratively later please reach out to me. C:

**Comment by Boostrix** [comment]
> another funny STUCK! we all know for some softwares, you need to input `y` to check agreements, that will stuck Auto-GPT too!!!

right, there is the hard-coded requirement (constraint) to use only non-interactive apps, where "-y" might be the solution (think apt-get install), it might be necessary to pass created shell commands first to some sort of preparation stage so that those commands can be reviewed for potential changes to ensure that they don't ask questions like these

**Comment by zudsniper** [comment]
> > another funny STUCK! we all know for some softwares, you need to input `y` to check agreements, that will stuck Auto-GPT too!!!
> 
> 
> 
> right, there is the hard-coded requirement (constraint) to use only non-interactive apps, where "-y" might be the solution (think apt-get install), it might be necessary to pass created shell commands first to some sort of preparation stage so that those commands can be reviewed for potential changes to ensure that they don't ask questions like these

Well put!
I'm not sure how to go about this fully but I would think a good first step but would be wrapping package managers? Perhaps I'm missing some part of the flow but it seems like if we made wrappers (dare I posit we make... _only a single wrapper_... nay...) for `apt`, `npm`, & `pip` & then had a standard & documented way to retroactively add other package managers to the framework as necessary, it could be a step in the right direction? 

Sounds like a huge headache though -- and fwiw would love if anyone wants to share their cringe workaround in the meantime I haven't found one yet

**Comment by Boostrix** [comment]
there already is the constraint to only use non-interactive apps, so this isn't always working well  - maybe it would make sense to validate shell commands before they're executed, and one part of the validation may involve checking for interactive mode.

The "cringe workaround" might be as simple as repeating the constraint (non-interactive mode) inside the description of the shell execution function

**Comment by zudsniper** [comment]
> there already is the constraint to only use non-interactive apps, so this isn't always working well  - maybe it would make sense to validate shell commands before they're executed, and one part of the validation may involve checking for interactive mode.
> 
> 
> 
> The "cringe workaround" might be as simple as repeating the constraint (non-interactive mode) inside the description of the shell execution function 
> 
> 
> 
> To see if that's working, just copy an interactive shell command to GPT and ask it to  make it non-interactive 

Fair point tbh.  

Also sounds sort of... potentially **automated**... why do I love signing myself up for things I can't deliver on in time smh
