### ISSUE TITLE
SYSTEM:  Command browse_website returned: Error: Message:

### ISSUE THREAD

**Issue by feefee1987** [Significant-Gravitas/Auto-GPT#1929]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

NEXT ACTION:  COMMAND = browse_website ARGUMENTS = {'url': 'https://python.langchain.com/en/latest/index.html', 'question': 'How to use LangChain'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for BigT...
Input:y

### Current behavior 😯

SYSTEM:  Command browse_website returned: Error: Message:

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by k-boikov** [comment]
I suggest you prove your prompt (the answers to the questions you get in the beginning) so people can reproduce the issue.

**Comment by timeanor** [comment]
possible dupe of https://github.com/Significant-Gravitas/Auto-GPT/issues/1641

**Comment by WangPeterXF** [comment]
i met same problem, working on how to fix

**Comment by ntindle** [comment]
Sometimes it executes something unexpected or doesn’t do what you want.  Check out the #prompt-engineering channel in discord to get a better fit prompt
