### ISSUE TITLE
autoGPT cannot recognize and use the websites URL from the google returned

### ISSUE THREAD

**Issue by LeviHan999** [Significant-Gravitas/Auto-GPT#1959]
### ⚠️ Search for existing issues first ⚠️

- [x] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [x] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

When I was trying to ask chatGPT to write a news article about a famous person, The first step for it was to use google command, then it searched in google, it returned lots of information including websites url. 

`Command google returned: [ { "title": "Why did Alibaba's Jack Ma disappear for three months? - BBC News", "href": "https://www.bbc.com/news/technology-56448688", "body": "Jack Ma was about to become the richest man in China. In November 2020, on the eve of another commercial success, the outspoken billionaire suddenly went missing. Ma's company Alibaba has risen ..." }, { "title": "Jack Ma Engineered Alibaba's Breakup From Overseas - WSJ", "href": "https://www.wsj.com/articles/jack-ma-engineered-alibabas-breakup-from-overseas-91f2d574", "body": "March 30, 2023 12:37 pm ET. Text. Listen to article. (2 minutes) HONG KONG—Chinese billionaire Jack Ma orchestrated from overseas the corporate breakup of the e-commerce empire he built, Alibaba ..." }....... ]`

But, it seems that the **autogpt cannot recognized or use that websites in google returned**. Then it tried to browse website not existing, or the first page of BBC news website. 

```
NEXT ACTION:  COMMAND = browse_website ARGUMENTS = {'url': 'https://www.bbc.com/news', 'question': "Please browse the website to retrieve the news articles about Jack Ma's disappearance and reappearance."}
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
Text length: 8435 characters
Summarizing chunk 1 / 2
Summarizing chunk 2 / 2
Summarized 2 chunks.
```
`SYSTEM:  Command browse_website returned: ("Answer gathered from website: The text is a disclaimer from the BBC discussing their website's terms of use, privacy policy, and other information. It does not provide any information about Jack Ma's disappearance and reappearance, nor does it provide information on news articles about it. Therefore, the question cannot be answered using the text. \n \n Links: ['Homepage (https://www.bbc.com)', 'Skip to content (#skip-to-content-link-target)', 'Accessibility Help (https://www.bbc.co.uk/accessibility/)', 'Sign in (https://session.bbc.com/session?ptrt=https%3A%2F%2Fwww.bbc.com%2Fnews&context=news&userOrigin=news_gnl)', 'Notifications (https://www.bbc.co.uk/notifications)']", <selenium.webdriver.chrome.webdriver.WebDriver (session="fe7fc52abdb4892a6d4ebbd349c78afe")>)`

**After dozens of that cycle, it returned nothing.**

### Current behavior 😯

It seems that the **autogpt cannot recognized or use that websites in google returned**. Then it tried to browse website not existing, or the first page of BBC news website. 

**After dozens of that cycle, it returned nothing.**

### Expected behavior 🤔

AutoGPT **should use formation from google returned very efficiently**, it should **visit and summarize from the websites it googled**.
AutoGPT should not browse websites not existing or visit websites that is not relevant to task.

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by amsator** [comment]
I have a similar problem, can't read the content of websites: 
  System: Command browse_website returned: Error: Message: unknown error: net::ERR_CONNECTION_RESET
  (Session info: chrome=112.0.5615.121)
Stacktrace:
#0 0x55b3fdf0ffe3 <unknown>
#1 0x55b3fdc4ed36 <unknown>
#2 0x55b3fdc46cd8 <unknown>
#3 0x55b3fdc39862 <unknown>
#4 0x55b3fdc3af72 <unknown>
#5 0x55b3fdc39c2a <unknown>
#6 0x55b3fdc38cf8 <unknown>
#7 0x55b3fdc38b30 <unknown>
#8 0x55b3fdc37608 <unknown>
#9 0x55b3fdc37c3d <unknown>
#10 0x55b3fdc50b16 <unknown>
#11 0x55b3fdcc58c5 <unknown>
#12 0x55b3fdcac8c2 <unknown>
#13 0x55b3fdcc5232 <unknown>
#14 0x55b3fdcac693 <unknown>
#15 0x55b3fdc7f03a <unknown>
#16 0x55b3fdc8017e <unknown>
#17 0x55b3fded1dbd <unknown>
#18 0x55b3fded5c6c <unknown>
#19 0x55b3fdedf4b0 <unknown>
#20 0x55b3fded6d63 <unknown>
#21 0x55b3fdea9c35 <unknown>
#22 0x55b3fdefa138 <unknown>
#23 0x55b3fdefa2c7 <unknown>
#24 0x55b3fdf08093 <unknown>
#25 0x7f1518894b43 <unknown>

  
  User: GENERATE NEXT COMMAND JSON
