### ISSUE TITLE
NameError: name 'Config' is not defined

### ISSUE THREAD

**Issue by fewmatty** [Significant-Gravitas/Auto-GPT#1961]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [ ] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Current behavior 😯

everytime I try to launch autogpt with command 'python3 -m autogpt' I get a name error that 'Config' is not defined. I am stuck here, I saw some threads that showed #1600 resolved this, but I was not able to make sense of it. Can anyone help? I'd really like to try this out!!

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by k-boikov** [comment]
What OS are you using, what is your python version, which branch are you using? In which file is the error thrown?

**Comment by fewmatty** [comment]
I was able to resolve. I am trying my hardest to learn this. Thanks a ton.
