### ISSUE TITLE
data_ingestion does not work (for me)

### ISSUE THREAD

**Issue by MBrekhof** [Significant-Gravitas/Auto-GPT#1962]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [ ] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

basically this is my problem:
C:\Project\autogpt\Auto-GPT>**python autogpt\data_ingestion.py --file dx2311.sql**
Traceback (most recent call last):
  File "C:\Project\autogpt\Auto-GPT\autogpt\data_ingestion.py", line 4, in <module>
    from autogpt.config import Config
**ModuleNotFoundError: No module named 'autogpt'**

not sure where the problem lies but if anyone could confirm data_ingestion does work for them I can try to narrow the problem down. Running this on Windows in case it isn't obvious

### Current behavior 😯

error message instead of reading the file

### Expected behavior 🤔

read the file to prime the knowledge base

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by MBrekhof** [comment]
chatGPT provided the answer: setting the PYTHONPATH env variable was the solution (I normally do not use Python so I hadn't noticed the problem before...)

**Comment by happyhalloween13** [comment]
> chatGPT provided the answer: setting the PYTHONPATH env variable was the solution (I normally do not use Python so I hadn't noticed the problem before...)

How did you do this?

**Comment by MBrekhof** [comment]
I entered this in chatgpt:
when starting a script from autogpt with the following commandline:
python autogpt\data_ingestion.py --file dx2311.sql
it responds with:
Traceback (most recent call last):
  File "C:\Project\autogpt\Auto-GPT\autogpt\data_ingestion.py", line 4, in <module>
    from autogpt.config import Config
ModuleNotFoundError: No module named 'autogpt'

what does this mean

it responded with several options to try and remedy this, I choose this one (and rebooted my machine):
The PYTHONPATH environment variable is a system variable used by Python to determine where to search for modules and packages when importing them. It is a list of directories that Python checks when looking for modules to import. The directories specified in PYTHONPATH are in addition to the default locations where Python looks for modules, such as the standard library and site-packages.

When you want to import a module from a non-standard location, you can add the directory containing the module to the PYTHONPATH. This way, Python can find and import the module without the need for modifying the code itself.

To set or modify the PYTHONPATH environment variable, follow these platform-specific instructions:

Windows

Open the "System Properties" window by right-clicking on "Computer" or "This PC" and selecting "Properties."
Click on "Advanced system settings" on the left side.
In the "System Properties" window, go to the "Advanced" tab and click the "Environment Variables" button.
In the "Environment Variables" window, click on "New" under the "System variables" section to add a new variable.
Enter PYTHONPATH as the variable name and provide the directory paths separated by semicolons (;) as the variable value.

**Comment by Slowly-Grokking** [comment]
this error is because data_ingestion.py needs to load the autogpt module, but it is located within autogpt.
you can move data_ingestion.py to the main Auto-GPT folder, and run it from there without any changes to the code.

updated readme here:
https://github.com/Slowly-Grokking/Auto-GPT/blob/master/README.md#-memory-pre-seeding

PR:
https://github.com/Significant-Gravitas/Auto-GPT/pull/1679
