### ISSUE TITLE
stable branch vs master branch

### ISSUE THREAD

**Issue by ziliangpeng** [Significant-Gravitas/Auto-GPT#1963]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [ ] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

check out stable branch, build docker image and run AutoGPT in docker

### Current behavior 😯

many things are broken in docker image, for example
- files are not copied into the right directory `autogpt/`
- chromedriver is not installed

These issues are fixed in `master` branch, so `master` branch turns out to be more stable then `stable`.

### Expected behavior 🤔

expect `stable` branch to work better than `master`

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by richbeales** [comment]
Stable will move slower than Master, so if there's a bug, it will be fixed in Master first, before becoming a stable release.

**Comment by ngmisl** [comment]
But the chromedriver is a breaking Bug, this should be fixed in all branches asap

**Comment by nponeccop** [comment]
It is. Stable is working now.

**Comment by ziliangpeng** [comment]
@nponeccop thanks! is there a goal to add more tests to ensure quality of the `stable` branch? how is quality control done on stable branch right now?

**Comment by ngmisl** [comment]
@nponeccop not really, I still get 

![2023-04-17_07-38](https://user-images.githubusercontent.com/98217124/232392464-45f03a6d-70c5-4aa0-bacf-92784a42f0d3.png)

CRITICISM:  I need to make sure I am focusing on the latest news and not getting distracted by unrelated articles or websites.
NEXT ACTION:  COMMAND = browse_website ARGUMENTS = {'url': 'https://www.moneycrashers.com/best-stock-market-investment-news-analysis-research-sites/', 'question': 'news related to company earnings or mergers and acquisitions'}
[WDM] - Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████| 6.75M/6.75M [00:00<00:00, 59.2MB/s]
SYSTEM:  Command browse_website returned: Error: Message: unknown error: Chrome failed to start: exited normally. (unknown error: DevToolsActivePort file doesn't exist) (The process started from chrome location /snap/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.) Stacktrace: #0 0x55c1da96afe3 <unknown> #1 0x55c1da6a9d36 <unknown> #2 0x55c1da6d2b20 <unknown> #3 0x55c1da6cea9b <unknown> #4 0x55c1da710af7 <unknown> #5 0x55c1da71011f <unknown> #6 0x55c1da707693 <unknown> #7 0x55c1da6da03a <unknown> #8 0x55c1da6db17e <unknown> #9 0x55c1da92cdbd <unknown> #10 0x55c1da930c6c <unknown> #11 0x55c1da93a4b0 <unknown> #12 0x55c1da931d63 <unknown> #13 0x55c1da904c35 <unknown> #14 0x55c1da955138 <unknown> #15 0x55c1da9552c7 <unknown> #16 0x55c1da963093 <unknown> #17 0x7fef59294b43 <unknown>

**Comment by mikkorantalainen** [comment]
How about making `stable` the default branch in GitHub to allow people to get the stable code if they simply do `git clone https://github.com/Significant-Gravitas/Auto-GPT.git`? The note in README about how `stable` should be used will be lost by many for sure.

**Comment by Pwuts** [comment]
The issue should be resolved by #1473 among others. New release including these fixes should drop tomorrow morning.
