### ISSUE TITLE
execute_python_page command cannot see files

### ISSUE THREAD

**Issue by Stunspot** [Significant-Gravitas/Auto-GPT#1966]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [X] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

Every time my bot tries to use the execute_python_page command he gets this error:

`Command execute_python_file returned: Error: Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.')`

Everything I could google says this is what happens when a docker app thinks it's in a docker container but docker isn't installed. Docker is listed as an option on the front page, but nothing about it being mandatory (not like I COULD run it!). My bot's getting by using shell calls to the python executable but he's about to have a nervous breakdown and I'm constantly fighting it to keep it focused on any goal beside "fix the problem with my code". 

I completely uninstalled the bot, uninstalled Python, logged on as new user, and reinstalled everything. And got exactly the same error. ai settings don't seem to be at play here - tried a bunch of stuff,

Stable branch. Haven't had a chance to try master. I saw no other issues mention execute_python_page. 
commit-hash = 60b2b61b52c263dba25a6c33623561273e890229
pip 23.0.1 from C:\Python310\lib\site-packages\pip (python 3.10)

### Current behavior 😯

 Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.')`

### Expected behavior 🤔

Execute a python page.

### Your prompt 📝

```yaml
# Paste your prompt here
```
fresh install. no complete runs. but it was

Name: tester
Tester is: here to test his capabilities.
Goal 1: test your execute_python_page command by writing a script to disk, reading it to make sure it wrote properly then execute it with execute_python_page.
Goal 2: Provide a general systems status report. How are you functioning?

**Comment by Pwuts** [comment]
This issue is tracked further in #2006; closing as duplicate
