### ISSUE TITLE
"DevToolsActivePort file doesn't exist" in browse_website

### ISSUE THREAD

**Issue by ziliangpeng** [Significant-Gravitas/Auto-GPT#1978]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [ ] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

- run autogpt in docker (same happens to me in non-dockerized environment on ubuntu desktop)
- initiate any command that requires browsing a website.

### Current behavior 😯

  Assistant: {
    "thoughts": {
        "text": "I need to read the reviews on the Rotten Tomatoes and Roger Ebert websites to start summarizing the user reviews for Avengers: Endgame. ",
        "reasoning": "Both Rotten Tomatoes and Roger Ebert are popular review websites, which should have a variety of opinions for the movie. This will allow me to get a broad range of opinions before summarizing the reviews.",
        "plan": "- I will browse the Rotten Tomatoes website for reviews on Avengers: Endgame.\\n- I will browse the Roger Ebert website for reviews on Avengers: Endgame.  \\n- I will store the useful information in separate files for positive and negative reviews so that I can summarize the reviews more efficiently.",
        "criticism": "None",
        "speak": "I will start browsing the Rotten Tomatoes website for Avengers: Endgame reviews first. Shall I proceed with that?"
    },
    "command": {
        "name": "browse_website",
        "args": {
            "url": "https://www.rottentomatoes.com/m/avengers_endgame/reviews",
            "question": "positive and negative reviews for Avengers: Endgame on Rotten Tomatoes"
        }
    }
}

  System: Command browse_website returned: Error: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

### Expected behavior 🤔

expect it be able to correctly browse the url, and summarize content.

### Your prompt 📝

```yaml
ai_goals:
- 'summarize user reviews from both the positive side and negative side for the Movie
  "Avengers: End Game"'
```

**Comment by mihalycsaba** [comment]
same error on a headless virtual machine running rocky 8

**Comment by mihalycsaba** [comment]
some other error with firefox 

```
NEXT ACTION:  COMMAND = browse_website ARGUMENTS = {'url': 'https://www.steamgifts.com/giveaway/GBzCg/frog-detective-1-the-haunted-island', 'question': 'giveaway details'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
[WDM] - Downloading: 19.2kB [00:00, 15.2MB/s]                                                                                                                                                                                                 
[WDM] - Downloading: 19.2kB [00:00, 12.9MB/s]                                                                                                                                                                                                 
[WDM] - Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.93M/2.93M [00:00<00:00, 6.00MB/s]
SYSTEM:  Command browse_website returned: Error: Message: Process unexpectedly closed with status 1

```

**Comment by mihalycsaba** [comment]
@ziliangpeng 
add the lines with + after line 65

```
diff --git a/autogpt/commands/web_selenium.py b/autogpt/commands/web_selenium.py
index 1d078d7..dd7bcb9 100644
--- a/autogpt/commands/web_selenium.py
+++ b/autogpt/commands/web_selenium.py
@@ -65,6 +65,8 @@ def scrape_text_with_selenium(url: str) -> tuple[WebDriver, str]:
     options.add_argument(
         "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.5615.49 Safari/537.36"
     )
+    options.add_argument("--no-sandbox")
+    options.add_argument("--headless")
 
     if CFG.selenium_web_browser == "firefox":
         driver = webdriver.Firefox(

```

**Comment by johndzxu** [comment]
Still gets the error after adding the lines:
```
Command browse_website returned: Error: Message: unknown error: 
DevToolsActivePort file doesn't exist Stacktrace: #0 0x564a6c95efe3 <unknown> #1 0x564a6c69dd36 <unknown>
 #2 0x564a6c6ca459 <unknown> #3 0x564a6c6c6051 <unknown> #4 0x564a6c6c2a9b <unknown> #5 0x564a6c704af7 
<unknown> #6 0x564a6c70411f <unknown> #7 0x564a6c6fb693 <unknown> #8 0x564a6c6ce03a <unknown> #9 
0x564a6c6cf17e <unknown> #10 0x564a6c920dbd <unknown> #11 0x564a6c924c6c <unknown> #12 0x564a6c92e4b0 
<unknown> #13 0x564a6c925d63 <unknown> #14 0x564a6c8f8c35 <unknown> #15 0x564a6c949138 <unknown> #16 
0x564a6c9492c7 <unknown> #17 0x564a6c957093 <unknown> #18 0x7f1cab890402 <unknown>
```

**Comment by horazius** [comment]
Same problem here:

-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
SYSTEM:  Command browse_website returned: Error: Message: unknown error: Chrome failed to start: crashed. (unknown error: DevToolsActivePort file doesn't exist) (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.) Stacktrace: #0 0x56255f21efe3 <unknown> #1 0x56255ef5dd36 <unknown> #2 0x56255ef86b20 <unknown> #3 0x56255ef82a9b <unknown> #4 0x56255efc4af7 <unknown> #5 0x56255efc411f <unknown> #6 0x56255efbb693 <unknown> #7 0x56255ef8e03a <unknown> #8 0x56255ef8f17e <unknown> #9 0x56255f1e0dbd <unknown> #10 0x56255f1e4c6c <unknown> #11 0x56255f1ee4b0 <unknown> #12 0x56255f1e5d63 <unknown> #13 0x56255f1b8c35 <unknown> #14 0x56255f209138 <unknown> #15 0x56255f2092c7 <unknown> #16 0x56255f217093 <unknown> #17 0x7f427280cea7 start_thread

**Comment by k-boikov** [comment]
https://github.com/Significant-Gravitas/Auto-GPT/pull/2096 This should help. Try adding --disable-dev-shm-usage in your case.

**Comment by Pwuts** [comment]
Closing as resolved
