### ISSUE TITLE
Open Ai api TIME OUT

### ISSUE THREAD

**Issue by jmanhype** [Significant-Gravitas/Auto-GPT#198]
So when it times out it closes the bot when i restart bot it ask do i want to contiinue with last bot i crfeated i say yest but instead of picking up where it left off it re does the entire process which ususally entails looking up a bunch of stuff and storing it into memory before it begins. which takes alot of tokens and runs the risk of another timeout which then compounds the problem.

PLEASE HELP

**Comment by AestheticMayhem** [comment]
![autogpt](https://user-images.githubusercontent.com/111237581/229963683-4106023a-59b5-4fbb-af55-c6cb2a82f0db.png)


 i have the same problem

**Comment by MatShep** [comment]
Same, received error: "openai.error.APIError: HTTP code 502 from API." after a lengthy thread.
Potential enhancement required to add a re-try on 502 responses. https://pypi.org/project/retry/ or similar?

**Comment by illumineawake** [comment]
I receive the same error whenever it has been working through the goals for some time.

**Comment by Qoyyuum** [comment]
There have been lots of changes since this issue has opened. Please try again and if the symptoms presents itself again, please raise another issue with more details including results from `--debug`. Thank you!
