### ISSUE TITLE
Add support for SearxNG

### ISSUE THREAD

**Issue by LaloLalo1999** [Significant-Gravitas/Auto-GPT#199]
Add support for [SearxNG](https://docs.searxng.org/) as an alternative to the google api

**Comment by niallist** [comment]
I am interested in taking this on, as I already have it integrated into my (early and for now personal) Langchain project.  I'll issue a PR and look to get it finished over the weekend if that's ok with @Torantulino?

**Comment by Pwuts** [comment]
I'm pretty sure this is better as a plugin. Closing as such :)
