### ISSUE TITLE
No module named 'colorama' when running autogpt

### ISSUE THREAD

**Issue by noghartt** [Significant-Gravitas/Auto-GPT#1990]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [ ] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

1. Install the required dependencies with `pip install -r installments.txt`
2. Add the envs
3. Try to run the autogpt module using `python3 -m autogpt`.

### Current behavior 😯

When running `python3 -m autogpt`, the logs that appears is:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/noghartt/dev/Auto-GPT/autogpt/__main__.py", line 3, in <module>
    from colorama import Fore
ModuleNotFoundError: No module named 'colorama'
```

Even if I already installed `colorama` via pip. I'm running on the `stable` branch.

### Expected behavior 🤔

Should run the `autogpt` as the docs said.

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by kala-here** [comment]
I also see this locally. The way I got around it was to run in docker.

**Comment by noghartt** [comment]
> I also see this locally. The way I got around it was to run in docker.

I saw what is the error. It's on the way where `pip` handle packages. Is there a difference between `pip install` and `pip3 install`.

I fixed it running it with:

```
python3 -m pip install -r requirements.txt
```

In this way, the packages will be installed on a path that `python3` knows.

**Comment by noghartt** [comment]
> I'm also getting this error, and when I try: `python3 -m pip install -r requirements.txt` it tells me: `Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.`
> 
> I assume I'm not running the command in the correct directory in my command prompt. Where should I run it? Or if that's not the problem, what is?

Run a `which python3` and see if you have some executable called `python3`.

If not, you will need to run the same command replacing `python3` for `python`.

---

By the way, see if your `$PATH` is right and have a python executable. Apparently you running on Windows, right? See how to set up the `$PATH` to find the right python executable.

**Comment by rdrglpzcnt** [comment]
don't know why, but i get that error when i run with `python`, works fine with `python3`

**Comment by fmahmud** [comment]
Usually you get that when you have python 2 and python 3 installed. `python` gets aliased to python 2 instead of python 3.
