### ISSUE TITLE
Spinning Thinking for 1Hr+

### ISSUE THREAD

**Issue by jbb-kryo** [Significant-Gravitas/Auto-GPT#1992]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [ ] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

Run locally, using local memory default. Chrome is not installed on system. Using Brave instead.

### Current behavior 😯

![image](https://user-images.githubusercontent.com/61083145/232337965-60604802-919e-42d3-ad74-5d52167c1409.png)

### Expected behavior 🤔

It should actually do something, however sits for over an hour seemingly, 'thinking'.

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Gannnki** [comment]
Presumably, you are using a free openAI API which is not supported, you can connect to a billing method and generate a new API key, in my case it works...

**Comment by jbb-kryo** [comment]
I have a paid for API key and subscription.

**Comment by jbb-kryo** [comment]
Fixed it. Had to generate a brand new API key from the OpenAI dashboard.
