### ISSUE TITLE
Alternative to Pinecone.io?

### ISSUE THREAD

**Issue by ocarlisle** [Significant-Gravitas/Auto-GPT#1995]
I've been spinning my wheels all morning trying to get this thing to use ChromaDB locally instead of friggin Pinecode.io. They are no longer accepting people and they wont even let me pay for an account. Does anyone know of an alternative to pinecone.io? or a way to make this work with method locally? frustrating that I put in all that work and get stopped by this.

**Comment by ccheney** [comment]
Use one of the other memory options https://github.com/Significant-Gravitas/Auto-GPT#memory-backend-setup

**Comment by ntindle** [comment]
^
