### ISSUE TITLE
pymilvus not installed. Skipping import. Warning: The file 'auto-gpt.json' does not exist.

### ISSUE THREAD

**Issue by ekonexus** [Significant-Gravitas/Auto-GPT#1998]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [ ] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Current behavior 😯

D:\AI  Files\Auto-GPT>run
All packages are installed.
pymilvus not installed. Skipping import.
Warning: The file 'auto-gpt.json' does not exist.Local memory would not be saved to a file.
Please set your OpenAI API key in .env or as an environment variable.
You can get your key from https://beta.openai.com/account/api-keys

I have my keys correct in .env

It also seems like python (3.10.10) isn't working when I enter the prompt to check requirements. 

### Expected behavior 🤔

it works?

### Your prompt 📝

run

**Comment by nponeccop** [comment]
Pymilvius is an option feature, it doesn't impact the working.

**Comment by ntindle** [comment]
Closing due to no follow up
