### ISSUE TITLE
API Issues

### ISSUE THREAD

**Issue by atwoodsr15** [Significant-Gravitas/Auto-GPT#2004]
![image](https://user-images.githubusercontent.com/48134823/232341040-c1a88fdc-a2a5-4894-81be-0c143de54d18.png)
This is what I'm getting even though I have followed all the steps. Need help troubleshooting.

**Comment by Jaydidit22** [comment]
same

**Comment by atwoodsr15** [comment]
I figured it out....go into the terminal and enter "copy .template.env .env"
