### ISSUE TITLE
execute_python_file throws opaque error if docker is not installed

### ISSUE THREAD

**Issue by Nickonomic** [Significant-Gravitas/Auto-GPT#2006]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [x] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

CRITICISM:  I need to ensure that the command is working properly before attempting to locate and fix the issue with the trading strategies file.
NEXT ACTION:  COMMAND = execute_python_file ARGUMENTS = {'file': 'hello_world.py'}
Executing file 'hello_world.py' in workspace 'E:\auto\Auto-GPT\auto_gpt_workspace'
SYSTEM:  Command execute_python_file returned: Error: Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.')
The JSON object is valid.

### Expected behavior 🤔

The only way I managed to make execute file work was to get rid of docker stuff and re-write it using subprocess.

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by E-Labs-io** [comment]
Yea mine hasn't been able to execute and python ether.  Haven't really looked into it though

**Comment by Wladastic** [comment]
You need to have Docker Desktop running for that to work.

**Comment by robnraz** [comment]
Have the same issue but the bot normally issues a search command for the filename specified, finds the file (in the working directory), and can then execute the file.

It seems a search must be performed first before execution of the file can be done

It has happened this way for me several times.

**Comment by GerardCB** [comment]
I could only execute these files if I asked AutoGPT to run the 'python hello_world.py' command using the command line.
If we need to have Docker Desktop installed, this should be added to some requirements or only allow the bot to use the execute python files command if the user has installed Docker Desktop.

**Comment by E-Labs-io** [comment]
I have Docker desktop running, but when Auto-GPT trys to execute a command we get 

NEXT ACTION:  COMMAND = execute_python_file ARGUMENTS = {'file': 'authenticate_notion.py'}
Executing file 'authenticate_notion.py' in workspace '/Users/tuck/Documents/E-Labs/AI/Build Tests/Auto-GPT-master(16:04 02)/auto_gpt_workspace'
SYSTEM:  Command execute_python_file returned: Error: File 'authenticate_notion.py' does not exist.

The file does exists, just isn't visible it seems to auto-gpt

**Comment by Stunspot** [comment]
The issue is that someone rewrote the execute_python_file command to assume it was in a docker container. An app expecting to be in a docker container that isn't throws a file not found error. Was going nuts from this. Just now had ChatGPT rip out the docker crap for me. Here's my execute_code.py file:

[execute_code - execute_python_file fixed.py.txt](https://github.com/Significant-Gravitas/Auto-GPT/files/11250230/execute_code.-.execute_python_file.fixed.py.txt)

**Comment by iva-nova-e-katerina** [comment]
This bug is annoying me for a week
