### ISSUE TITLE
Linting non-Python files

### ISSUE THREAD

**Issue by nponeccop** [Significant-Gravitas/Auto-GPT#2013]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

We have markdown and .yaml files, which also suffer from whitespace errors

### Examples 🌈

Well, @p-i- has these ones:

![image](https://user-images.githubusercontent.com/528415/232344121-5aac1fff-7c23-41c2-a1bb-ab8d87c94109.png)

### Motivation 🔦

We don't want people continuously adding and removing the final line feed in our Readme.

**Comment by nitinmewar** [comment]
can I work on it?

**Comment by muhamrif** [comment]
I would like to work on it, if approved. Thankyou!

**Comment by pushp1997** [comment]
Can we just add markdown and yaml linting in dependencies and them to pre-commit hook as well?
