### ISSUE TITLE
ImportErro

### ISSUE THREAD

**Issue by Bigrussian8** [Significant-Gravitas/Auto-GPT#2016]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [ ] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

1. Install Visual Studio Center (also occurs without Visual Studio Center)
2. Install Python latest version
3. Using Github link install AutoGPT
4. Test python installation existence (pass)
5. Open AutoGPT in Visual Studio Center
6. Install requirements file (no issues)
7. Open new terminal
8. Try to run main.py running the command given on website (python scripts/main.py)
9. Import error

### Current behavior 😯

ImportError: Cannot import 'main' from 'autogpt' (file location)

### Expected behavior 🤔

Autogpt should launch

### Your prompt 📝

```yaml
python scripts/main.py
```

**Comment by nponeccop** [comment]
This is an out-of-date instruction. Look at the new README.md

**Comment by Bigrussian8** [comment]
Thank you very much!
