### ISSUE TITLE
Why google Everything? 

### ISSUE THREAD

**Issue by uckthis** [Significant-Gravitas/Auto-GPT#2030]
A simple task, here it is: 
```
ai_goals:
- I want to change a registry value so that default folder name for a new folder  is changed to "Uck_This"
- Write a registry value that achives Goal 1 and save it in a text file.
- Rename that text file and change its extension to .reg from .txt
ai_name: Reg Editor
ai_role: Write registry values
```

If I ask ChatGPT this, it'll puke out the code in two seconds.  But AutoGPT has been googling and thinking for the last 5 minutes, and is still thinking.  I don't understand why some information can't be accessed from GPT model itself and why the need of using Google in every query 

Also, I installed AutoGPT on day two of its launch, and so far I have performed only 6-7 tasks on it and none ever gave any results. All it does is endless Google searches and nothing ever to show up for it. Example:  I asked it to find me 5 jobs listing for closed captioning and after 10 minutes, it was still searching (Bing this time) and couldn't show any results. I still don't get the hype around AutoGPT when it just doesn't work, or am I too dumb to understand it?

**Comment by teury** [comment]
It depends a lot on the speed of your computer, the speed of your internet, etc. On a server it should be faster.

You are free to modify and improve this project, this is open source and free, it is not for you to demand much when they are not charging you anything.

**Comment by normen** [comment]
Good question, I suppose thats one of the questions that this *experiment* is trying to answer. Why does GPT, given the option to google, browse and make assistants, use google and does not rely on its model? :)

**Comment by uckthis** [comment]
@teury , 100mbps is more than enough for a simple Google search. I have 13900k Intel Processor and ZOTAC  GeForce RTX 4090 Trinity (24 GB). And I'm as dumb as a cow, but I don't know if your CPU or GPU has anything to do with it when we're using APIs which are on a server. 
Two: Outta 6-7 tasks in 15 days, is it too much to _demand_ at least one result? 
Three: I'm not a coder and hence only pointing out what seems odd to me with no intention of getting anyone's knickers in a twist.

**Comment by AndroidDev77** [comment]
Try specifying that in your goals

**Comment by Androbin** [comment]
See https://github.com/Significant-Gravitas/Auto-GPT/issues/2023#issuecomment-1510593134, the LLM isn't lazy but the emergent agent is

**Comment by teury** [comment]
@uckthis 

1. If you want an AI that uses the internet and that the responses are super fast, I recommend that you use writesonic.
https://writesonic.com/

2.  Auto-gpt3 uses a web browser that searches google and enters the results, then it has to extract that data (all of that is running on your computer), at the end it sends it to the Gpt3 api for analysis and feedback.

The bot is theoretically free to browse the internet, and could give you delayed responses if it gets distracted by irrelevant content, limits could be put on it to avoid this, such as limiting the number of results the bot would enter, limiting the time the bot can extract data .

I think AutoGPT will eventually be able to do the same as writesonic.

**Comment by uckthis** [comment]
@teury I have used Write Sonic. In fact, I have tested almost all of LLMs available for testing, be it locally or remotely. AutoGPT is unique amongst them. Even though I had zero results in last 15 days, I can see its potential and that's why this is my second thread, when otherwise I would just stop using it until it's at its best.
Most recently, I think https://open-assistant.io/ would be another unique LLM, as it is trained purely on human inputs, and we can contribute to make it better too.

**Comment by MikesMoneyMachine** [comment]
i have also noticed this issue, and found some what of a fix that im sure will get fine-tuned out later as auto-GPT progresses, so anyways chatGPT can normally give you a better answer than just searching the web could, yet Auto-GPT loves searching the web, and the plan, criticism, system, speak, messages that it gives out to tell the system what command to do works alot better if the system creates and agent, alot of times it starts by searching then maybe, sometimes, it creates GPT agents and those GPT agents really help to guide those plan, criticism, system, speak, messages, with the system then deciding from that what command to do next, like save a file, search the web, make a GPT agent, etc. so by starting your goal by saying something like "start by creating an agent that..." and then putting (whatever you want) in something like "...gather research on a subject..." it will then respond with its plan and say "starting by creating a GPT agent" this will get it away from using google so much and more importantly its starting with a GPT Agent and not a google search as the first thing it does and the GPT agent is smarter so it really sets it up for success. i did a test that put 1 goal and it said " start by creating two agents that work together to complete the goal of..." and in my case i wrote "...a 1000 word book about cryptocurrency" and its started off by creating two agents a writer and a researcher, and later it made a third called editor, though it didn't exactly write a 1000 word book, the point is about starting with agents helps alot! and if you start with a agent it will give you better google searches and commands on what the system should do next. 👍

**Comment by uckthis** [comment]
I think I'll just stop testing AutoGPT and wait for it to upgrade to something remotely useful. Right now it takes way too much time and outputs (I never got any results), I don't know if they're good or not, but if all of it does is Google search and click the top 5 links, I can do that better than her. And it cannot perform any local tasks. E.g.
```
ai_goals:
- This is a local task and therefore doesn't need access to the internet
- Go to E:\Unseen and rename the files and change the word Unseen with Seen. Keep
  every other part of names intact
ai_name: Rename
ai_role: Rename files

```
It still used Chrome and couldn't perform the task even after 5 minutes. Asked ChatGPT to do this, and it spewed code in two seconds:, which worked like a charm
```
import os

# Directory path where files are located
directory = "E:/Unseen"

# Get all files in the directory
files = os.listdir(directory)

# Loop through each file in the directory
for file in files:
    # Construct the new file name by replacing "Unseen" with "Seen"
    new_file_name = file.replace("Unseen", "Seen")

    # Construct the full file paths
    old_file_path = os.path.join(directory, file)
    new_file_path = os.path.join(directory, new_file_name)

    # Rename the file
    os.rename(old_file_path, new_file_path)

    print(f"Renamed file: {file} -> {new_file_name}")
```

AutoGPT has limited itself by tying to the internet, IMHO.

**Comment by normen** [comment]
> I think I'll just stop testing AutoGPT and wait for it to upgrade to something remotely useful.

I think thats a good idea.

**Comment by Androbin** [comment]
@MikesMoneyMachine Similar to AgentGPT?
>It works through using models to generate a task list and then iteratively executes tasks, evaluating whether or not tasks are completed or require further sub-actions.

https://twitter.com/asimdotshrestha/status/1644883733328310273?s=20

**Comment by ntindle** [comment]
I would work on changing the prompt to fit your goals better. Clarifications are always helpful. Go to the #prompt-engineering chat on discord for more help
