### ISSUE TITLE
Discord links not working on Twitter and Github

### ISSUE THREAD

**Issue by MikesMoneyMachine** [Significant-Gravitas/Auto-GPT#2048]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [X] I am using Auto-GPT with GPT-3 (GPT-3.5)

**Comment by ntindle** [comment]
Can I get an example of non functional link?

**Comment by ntindle** [comment]
No follow up
