### ISSUE TITLE
how to give auto-GPT authority access folder？

### ISSUE THREAD

**Issue by ChesterZhao** [Significant-Gravitas/Auto-GPT#2051]
I want auto-GPT access three pdf file in auto _gpt_workspace but this is the output: SYSTEM: Command read_file returned: Error: Attempted to access outside of working directory.

Maybe I should given it an authority?
How todo it?

**Comment by Advitica** [comment]
Try running your command shell as administrator (windows)

**Comment by ntindle** [comment]
There’s a config in the .env you can use
