### ISSUE TITLE
Translation should be a command and use GPT to do it directly.

### ISSUE THREAD

**Issue by tzengyuxio** [Significant-Gravitas/Auto-GPT#2054]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

When the goal/task is related to translation, Auto-GPT will google first and find an online translation service to do the task. It's back and forth repeatedly, and get no good result, usually in vein.

We can just use ChatGPT 3.5 or 4 to do translation, it may cost just one task round, and return better translation result.

**Comment by ntindle** [comment]
This seems great for a potential plugin. Open an issue here: [Auto-GPT-Plugins](https://github.com/Significant-Gravitas/Auto-GPT-Plugins)
