### ISSUE TITLE
Use chatgpt-retrieval-plugin's datastore for memory + permanent memory

### ISSUE THREAD

**Issue by Jeadie** [Significant-Gravitas/Auto-GPT#2058]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Currently, Auto-GPT is reimplementing backends that have a similar, if not identical, to those in [ChatGPT Retrieval Plugin](https://github.com/openai/chatgpt-retrieval-plugin). Instead of reinventing the wheel, import chatgpt-retrieval-plugin, specifically the datastore and reimplement AutoGPT's memory with the `DataStore` ([link](https://github.com/openai/chatgpt-retrieval-plugin/blob/main/datastore/datastore.py#L17)) class.

### Examples 🌈

See the plugin server ([link](https://github.com/openai/chatgpt-retrieval-plugin/blob/71650a53c8ed609380f3e8341b12846f94ac9287/server/main.py#L16))  for example usage
```python
from datastore.factory import get_datastore

datastore = await get_datastore()

```

### Motivation 🔦

Since `chatgpt-retrieval-plugin` already has had significant work to integrate with many backends, and the developer community for said backends are already invested in it, we should leverage their work.

**Comment by contributorai** [comment]
Note that chatgpt-retrieval-plugin Doesn’t have an option for local storage. 

so it would be harder to install and get started without pinecone Account or something similar.

**Comment by Jeadie** [comment]
It has Redis, Qdrant, Milvus and Weaviate support all of which have open-source, local and container runtimes. Adding more local storage options could easily be done within chatgpt retrieval plugins to help the community broader too.

**Comment by Jeadie** [comment]
Also, one could implement Auto-GPT specific DataStore implementations.

**Comment by contributorai** [comment]
Auto gpt specific data store could be:
https://github.com/Significant-Gravitas/Auto-GPT/pull/2128

(I haven’t tried it)

seems like memory development and improvement would be a strategic direction on this project, since memory is such a core capability...

**Comment by ntindle** [comment]
@Pwuts

**Comment by ether8unny** [comment]
for the record chatgpt-retrieval is langchain

**Comment by Pwuts** [comment]
Thanks for bumping @ether8unny. I'm not sure what happened but wish I had looked into this further before #4208.

**Comment by Jeadie** [comment]
Sorry, didn't track or follow up on this issue, just thought it'd be a great idea that balances various OSS users' demands. 

Happy to help with changes on this one.

**Comment by Pwuts** [comment]
@Jeadie if you want (and have time) to help:
* Check out #3536
* Hop in [this Discord channel](https://discord.com/channels/1092243196446249134/1103542024738717706) for Memory
* Let us know what you could or would like to help with

@collijk and I are working on the agent loop to give it retrieval possibilities (see #3536), and as soon as the restructure is far enough along to start testing and tuning, we'll need something that can do retrieval. It would be grand if by then we have clarity on the pros and cons of choosing between our current DIY approach or importing something like `chatgpt-retrieval-plugin`.
