### ISSUE TITLE
"API Bad Gateway" Issue - Stuck in Thinking

### ISSUE THREAD

**Issue by robg95** [Significant-Gravitas/Auto-GPT#2068]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [x] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

I keep getting this error when trying to run a command, stuck at thinking. Entered debug mode to assess the issue and it keeps saying "API Bad Gateway" (see the attached screenshot).

Is anyone having this issue / have a solution that has worked for them?

![Bad API Gateway](https://user-images.githubusercontent.com/130945107/232364690-67c6b753-65f2-4052-acb4-2f33731d9373.JPG)

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by amosh83** [comment]
Same here.....

**Comment by 7--** [comment]
getting rate limited over here

**Comment by 7--** [comment]
This is because we don't have the paid version of chatgpt. It's very risky and expensive becasue it's postpaid and need to add a credit card. Cost like 6 or 12 cents a query so easily could cost thousands if autogpt gets stuck in a loop making requests. 

To bad I can't afford the risk. I wanted to try this app.

**Comment by ataliap** [comment]
i have the paid version of chat gpt and i havet his message still

**Comment by olivierreuland** [comment]
Same.

Using docker, update my openapi key (premium).

```
  Token limit: 4000
  Send Token Count: 908
  Tokens remaining for response: 3092
  ------------ CONTEXT SENT TO AI ---------------
  System: The current time and date is Mon Apr 17 09:40:42 2023

  System: This reminds you of these events from your past:




  User: Determine which next command to use, and respond using the format specified above:

  ----------- END OF CONTEXT ----------------
Creating chat completion with model gpt-3.5-turbo, temperature 1.0, max_tokens 3092
Error:  Reached rate limit, passing...
Error:  API Bad gateway. Waiting 4 seconds...
Error:  Reached rate limit, passing...
Error:  API Bad gateway. Waiting 8 seconds...
```

**Comment by 7--** [comment]
> i have the paid version of chat gpt and i havet his message still

you need to create a new api key after setting up payment

**Comment by Explorergt92** [comment]
> Is paying the $20 a month the same thing or API payment is a different thing?

Yes ... you'll need to get setup on https://platform.openai.com instead of https://chat.openai.com/

https://github.com/Significant-Gravitas/Auto-GPT#%EF%B8%8F-openai-api-keys-configuration-%EF%B8%8F

**Comment by ntindle** [comment]
Issue in network or api, need more info if it persists
