### ISSUE TITLE
Memory seeding does not work with local memory caching

### ISSUE THREAD

**Issue by mbloom0** [Significant-Gravitas/Auto-GPT#2072]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [ ] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

1. Install Auto-GPT as provided in the README.
3. python -m autogpt --use-memory local 
4. Create AutoGpt.json in the root Auto-GPT-stable folder
5. python -m autogpt.data_ingestion --file 'C:\Users\Username\path\to\Auto-GPT-stable\auto_gpt_workspace\huge_memory_seed\all_memory.txt'
6. AutoGpt.json is seeded with the correct text and vectors in JSON formtting
7. Continue running the previous autoGPT instance
8. AutoGpt.json empty now, just contains {}

### Current behavior 😯

The  ingested data should remain in the local memory cache after starting GPT, and is instead overwritten.
Switching to pinecone makes it work, so it is specific to local memory...

### Expected behavior 🤔

The  ingested data should remain in the local memory cache, so the seeded memory can be referenced by the autoGPT

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by ntindle** [comment]
I think memory is getting emptied on local at spin-up.

**Comment by anshulahuja98** [comment]
+1, facing this same issue.

**Comment by aeslinger0** [comment]
From the documentation at https://significant-gravitas.github.io/Auto-GPT/configuration/memory/:

> For other memory backends, we currently forcefully wipe the memory when starting Auto-GPT. To ingest data with those memory backends, you can call the data_ingestion.py script anytime during an Auto-GPT run.

Run autogpt, then in a second command window seed your memory while it is running.
