### ISSUE TITLE
How can I fix this and proceed?

### ISSUE THREAD

**Issue by pradeepir** [Significant-Gravitas/Auto-GPT#2073]
How can I fix this and proceed?
on step 2, I get: 
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

_Originally posted by @CryptoPrince9 in https://github.com/Significant-Gravitas/Auto-GPT/discussions/1715_

**Comment by charltonh** [comment]
You should have a "requirements.txt" in your main directory.
Did you run the command from there?

Looks like you need to start it now with ./run.sh (from the main dir)

**Comment by CryptoPrince9** [comment]
Thanks. Figured it out

**Comment by Qoyyuum** [comment]
Hi @pradeepir , if you can find `run.bat` file and double-click that, it should work.

**Comment by yyu77458** [comment]
> Hi @pradeepir , if you can find `run.bat` file and double-click that, it should work.

I tried it, but it still shows Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/ pip/ (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1122)'))) - skipping

**Comment by ntindle** [comment]
Are you using a proxy?

**Comment by Qoyyuum** [comment]
Hi @pradeepir I assume you're able to `python -m pip install -r requirements.txt` or double-clicking `run.bat` should work as well.

@yyu77458 can you retry with the latest stable version, and run `python -m pip install -r requirements.txt` in the extracted AutoGPT folder?

**Comment by yyu77458** [comment]
> Hi @pradeepir I assume you're able to `python -m pip install -r requirements.txt` or double-clicking `run.bat` should work as well.
> 
> @yyu77458 can you retry with the latest stable version, and run `python -m pip install -r requirements.txt` in the extracted AutoGPT folder?

I sent the problem to ChatGPT and it made me change the code to solve it, but I forgot the specific code

**Comment by yyu77458** [comment]
> Are you using a proxy?

I sent the problem to ChatGPT and it made me change the code to solve it, but I forgot the specific code

**Comment by ntindle** [comment]
Try and use the #tech-support channel in discord for these issues. We don’t have the capacity to help debug in GitHub issues for problems like this
