### ISSUE TITLE
No module named 'duckduckgo_search'

### ISSUE THREAD

**Issue by geegewu** [Significant-Gravitas/Auto-GPT#2095]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [X] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Current behavior 😯

When running python -m autogpt
show:
  **File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
     return _run_code(code, main_globals, None,
   File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
     exec(code, run_globals)
   File "/Users/aron/Auto-GPT/autogpt/__main__.py", line 4, in <module>
     from autogpt.agent.agent import Agent
   File "/Users/aron/Auto-GPT/autogpt/agent/__init__.py", line 1, in <module>
     from autogpt.agent.agent import Agent
   File "/Users/aron/Auto-GPT/autogpt/agent/agent.py", line 2, in <module>
     from autogpt.app import execute_command, get_command
   File "/Users/aron/Auto-GPT/autogpt/app.py", line 6, in <module>
     from autogpt.commands.google_search import google_official_search, google_search
   File "/Users/aron/Auto-GPT/autogpt/commands/google_search.py", line 6, in <module>
     from duckduckgo_search import ddg
ModuleNotFoundError: No module named 'duckduckgo_search'
aron@MacBook-Pro Auto-GPT %****

### Expected behavior 🤔

Directly enter the setting interface of Auto-GPT

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by arronKler** [comment]
try to install one `pip install duckduckgo_search` .

its not declared in requirements.txt file, but it should be

**Comment by geegewu** [comment]
**Thanks for your reply, I have tried what you suggested,**

Requirement already satisfied: h11<1,>=0.9.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from wsproto>=0.14->trio-websocket~=0.9 ->selenium->-r requirements.txt (line 18)) (0.14.0)
aron@MacBook-Pro Auto-GPT % pip install duckduckgo_search

aron@MacBook-Pro Auto-GPT % pip install duckduckgo_search
Requirement already satisfied: duckduckgo_search in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (2.8.6)
Requirement already satisfied: requests>=2.28.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from duckduckgo_search) (2.28.2)

Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests>=2.28.2->duckduckgo_search) (1.26 .15)

Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests>=2.28.2->duckduckgo_search) (2022.12.7)
Then run: python -m autogpt
But the running result still shows:
from duckduckgo_search import ddg
ModuleNotFoundError: No module named 'duckduckgo_search'

**Comment by mirkomonti6** [comment]
Do you upgrade python before re running the project?

try to upgrade pip and re run pip3 install -r requirements.txt

**Comment by hsoumnk** [comment]
Hi @geegewu - I am having a similar problem as you. Were you able to resolve your issue? and If so, would you be able to share the steps you took? Many thanks.

**Comment by vichopoch** [comment]
have anybody managed to solve this issue? thanks

**Comment by pluto0x0** [comment]
I want to use email plugin so I am using AutoGPT 0.3.0 now. And I found the `requirements.txt` didn't specify the version for `duckduckgo-search` package. So I tried to install a older version (e.g. v3.5.0 from May 2023) for this package and that resolved the problem for me. It seems like some modules was changed in the later versions.

To sepecify a version for `duckduckgo-search` package, you can simply change a line in `requirements.txt` from

```shell
...
duckduckgo-search
...
```

to 

```shell
...
duckduckgo-search==3.5.0
...
```

and run

```shell
pip install -r requirements.txt
```
