### ISSUE TITLE
"Invalid JSON, setting it to empty JSON now"

### ISSUE THREAD

**Issue by robg95** [Significant-Gravitas/Auto-GPT#2098]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [ ] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

Every single time AutoGPT executes a command, I receive this error. Does anyone have a solution to this?

![Invalid JSON](https://user-images.githubusercontent.com/130945107/232385272-f9f200e1-6de2-4946-8077-b86b53aac4f1.JPG)

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Dupper19** [comment]
I'm having the same problem.

**Comment by mr0ng** [comment]
Same problem

**Comment by yaojin17** [comment]
Same here.

**Comment by omphos** [comment]
Same. Affects last stable version. 0.2.1
