### ISSUE TITLE
OpenAI throttling breaks summarization of large files

### ISSUE THREAD

**Issue by dbillor** [Significant-Gravitas/Auto-GPT#210]
this allows model to summarize large documents.

**Comment by ryanmac** [comment]
I've seen this too. OpenAI responds too many tokens after summary text.

**Comment by dbillor** [comment]
I have a fix can i contribute?

**Comment by dbillor** [comment]
https://github.com/Torantulino/Auto-GPT/pull/214

**Comment by Pwuts** [comment]
I strongly suspect this is a result of using Auto-GPT with a free account. The instructions clearly state to set up billing as there are strict rate limits for free accounts (max 3 requests/minute).

**Comment by maxluc1980** [comment]
> I strongly suspect this is a result of using Auto-GPT with a free account. The instructions clearly state to set up billing as there are strict rate limits for free accounts (max 3 requests/minute).

@Pwuts  I use the latest stable build of Auto-GPT with a **paid** account and run into the same issue on every task I give Auto-GPT. I also:
- re-installed it fresh multiple times
- re-installed the required files
- switched to gpt3only
- reduced the limit of tokens used to 1K

all to no avail. 

**I haven't been able to fully complete __a single task__ up to this date.**

**Comment by ZylerKade** [comment]
> > I strongly suspect this is a result of using Auto-GPT with a free account. The instructions clearly state to set up billing as there are strict rate limits for free accounts (max 3 requests/minute).
> 
> @Pwuts I use the latest stable build of Auto-GPT with a **paid** account and run into the same issue on every task I give Auto-GPT. I also:
> 
> * re-installed it fresh multiple times
> * re-installed the required files
> * switched to gpt3only
> * reduced the limit of tokens used to 1K
> 
> all to no avail.
> 
> **I haven't been able to fully complete a single task up to this date.**

Same situation. Using Stable AutoGPT v0.3.0 and **Paid** OpenAI account that was working perfectly fine with the stable AutoGPT 0.2.2. Can't get it to run with CMD for v0.3.0 though.

**Comment by Pwuts** [comment]
@maxluc1980 @ZylerKade can either of you post a log?

**Comment by pfsgaz** [comment]
at this point using autogpt is just to burn money
