### ISSUE TITLE
Error: Attempted to access path .......   outside of working directory

### ISSUE THREAD

**Issue by FakeSnake618** [Significant-Gravitas/Auto-GPT#2101]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [X] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

I give AI an task to write some code about a web page .

### Current behavior 😯

continue showing  Error: Attempted to access path  outside of working directory

### Expected behavior 🤔

It should build a folder and start writting

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Pwuts** [comment]
Please post your log and reopen.
