### ISSUE TITLE
Auto-GPT cant read javascript site

### ISSUE THREAD

**Issue by luanon404** [Significant-Gravitas/Auto-GPT#2104]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Some sites require JavaScript to load. For example: `<script src="https://abc.com/xyz.js"></script>`
They load the site by running the _https://abc.com/xyz.js_ file. After 5 seconds, a picture of a cat will appear. However, auto-gpt can't wait for it and get a cat picture and only retrieves the raw response HTML: `<script src="https://abc.com/xyz.js"></script>`

**Comment by arronKler** [comment]
autogpt's web browse tool is designed only for static site which will response pure html code in the first time.it will remove scripts links.

**Comment by ntindle** [comment]
This seems great for a potential plugin. Open an issue here: [Auto-GPT-Plugins](https://github.com/Significant-Gravitas/Auto-GPT-Plugins)
