### ISSUE TITLE
The json file saved by my auto gpt has garbled characters

### ISSUE THREAD

**Issue by Acekess** [Significant-Gravitas/Auto-GPT#2106]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [X] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

I asked my auto gpt to help me write a 10,000-word article, but the json format he saved was garbled, and I couldn’t watch it. The content in it was English plus Chinese, and there were a lot of numbers

### Expected behavior 🤔

I hope he can give the output a normal format and not garbled characters, so that I can watch it

### Your prompt 📝

ai_goals:
- 帮我写一篇1万字的论文
- 关于环保的
ai_name: 导师
ai_role: 写论文

**Comment by veerareddyvishal144** [comment]
The issue here is chatgpt is not that great in dealing with languages other than english

**Comment by ntindle** [comment]
I would work on changing the prompt to fit your goals better. Clarifications are always helpful. Go to the #prompt-engineering chat on discord for more help
