### ISSUE TITLE
Unicode URLencoded strings exceeded max prompt length

### ISSUE THREAD

**Issue by manageseverin** [Significant-Gravitas/Auto-GPT#2116]
When I asked it to search for a specific product in specific country it does not take into account the urls that contain urlencoded unicode strings and crashes with "This model's maximum context length "

```
    raise self.handle_error_response(
openai.error.InvalidRequestError: This model's maximum context length is 8191 tokens, however you requested 8451 tokens (8451 in your prompt; 0 for the completion). Please reduce your prompt; or completion length.
```

**Comment by kinance** [comment]
@manageseverin can you provide more debug info, e.g. call stack? It probably duplicates #2906
