### ISSUE TITLE
browse_website appear 500errorCode

### ISSUE THREAD

**Issue by kuok246** [Significant-Gravitas/Auto-GPT#2119]
NEXT ACTION:  COMMAND = browse_website ARGUMENTS = {'url': 'https://www.baeldung.com/java-clean-code', 'question': 'What are some best practices for writing clean code in Java that I can use to improve my coding ability?'}
![image](https://user-images.githubusercontent.com/67988538/232421576-cbb3df90-3d4d-460f-94c9-4fdce7312477.png)

**Comment by Explorergt92** [comment]
500 errors are issues with the server that hosts the site it tried to browse.

Can you access the link it tried to browse in chrome?

**Comment by Pwuts** [comment]
Closing as not a problem with Auto-GPT or the GPT itself
