### ISSUE TITLE
Could not find the version that satisfies the requirement sourcery

### ISSUE THREAD

**Issue by Jbbancud10** [Significant-Gravitas/Auto-GPT#2121]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [X] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement sourcery (from versions: none)
ERROR: No matching distribution found for sourcery

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by talvasconcelos** [comment]
There should be a distiction from development requirements and operation requirements. isort, black, sourcery, etc... are not needed for using AutoGPT!

**Comment by spiderhands** [comment]
Any update on this?

**Comment by k-boikov** [comment]
Are you using Docker? The Steps to reproduce are quite insufficient.

**Comment by spiderhands** [comment]
yes, on Apple M1 Pro

**Comment by k-boikov** [comment]
Please verify that you have the following code in your version of Dockerfile on line 21:
`RUN pip install --no-cache-dir --user -r requirements-docker.txt`
If not - update the project.

**Comment by spiderhands** [comment]
Thanks @k-boikov, I found a solution

There is no requirements-docker.txt file in the repo, but there is a flag in the requirements.txt file that separates non-docker requirements. The sourcery was written in the non-docker ones

**Comment by k-boikov** [comment]
Just curious - which branch/release are you using? And you are saying including sourcery fix the Docker issue?

**Comment by spiderhands** [comment]
This file is in the last commit:
```
beautifulsoup4
colorama==0.4.6
openai==0.27.2
playsound==1.2.2
python-dotenv==1.0.0
pyyaml==6.0
readability-lxml==0.8.1
requests
tiktoken==0.3.3
gTTS==2.3.1
docker
duckduckgo-search
google-api-python-client #(https://developers.google.com/custom-search/v1/overview)
pinecone-client==2.2.1
redis
orjson
Pillow
selenium
webdriver-manager
jsonschema
tweepy

##Dev
coverage
flake8
numpy
pre-commit
black
sourcery
isort
gitpython==3.1.31

# Items below this point will not be included in the Docker Image

# Testing dependencies
pytest
asynctest
pytest-asyncio
pytest-benchmark
pytest-cov
pytest-integration
pytest-mock
```

If you change to the following one, the error will go away

```
beautifulsoup4
colorama==0.4.6
openai==0.27.2
playsound==1.2.2
python-dotenv==1.0.0
pyyaml==6.0
readability-lxml==0.8.1
requests
tiktoken==0.3.3
gTTS==2.3.1
docker
duckduckgo-search
google-api-python-client #(https://developers.google.com/custom-search/v1/overview)
pinecone-client==2.2.1
redis
orjson
Pillow
selenium
webdriver-manager
jsonschema
tweepy
gitpython==3.1.31

# Items below this point will not be included in the Docker Image

##Dev
coverage
flake8
numpy
pre-commit
black
sourcery
isort

# Testing dependencies
pytest
asynctest
pytest-asyncio
pytest-benchmark
pytest-cov
pytest-integration
pytest-mock
```

**Comment by franken133521** [comment]
I have the same issue in Mac m1 max

**Comment by franken133521** [comment]
no, I tried it in the docker

**Comment by franken133521** [comment]
> 

I tried with docker, not with py

**Comment by michelem09** [comment]
I'm on `stable` branch but I get `No matching distribution found for openai==0.27.2 (from -r requirements.txt (line 3))`

**Comment by Pwuts** [comment]
Should be fixed by now. Please try with latest version on `master`. New stable release including this fix is expected to release tomorrow morning.

**Comment by franken133521** [comment]
use stable branch fix the problem, docker works.
thanks all.
