### ISSUE TITLE
微信群欢迎加入讨论 WeChat group

### ISSUE THREAD

**Issue by laixiao** [Significant-Gravitas/Auto-GPT#2125]
希望能支持中文，建了一个微信讨论群，欢迎加入。

Hope to support Chinese, built a WeChat discussion group, welcome to join.

![928819fc70ebf41d34134be7d62df23](https://user-images.githubusercontent.com/7324402/232440859-12148169-7c81-4027-87f6-bcee595e846d.jpg)

**Comment by gzp20182108** [comment]
nice！！

**Comment by gzp20182108** [comment]
需要被邀请

**Comment by weiyoubest** [comment]
另外开个群吧 这个满了

**Comment by laixiao** [comment]
> 需要被邀请

新建了2群

**Comment by laixiao** [comment]
> 另外开个群吧，这个满了

新建了2群哈

**Comment by weiyoubest** [comment]
> > 另外开个群吧，这个满了
> 
> 新建了2群哈

邀请下  兄弟

**Comment by laixiao** [comment]
done
