### ISSUE TITLE
Can i use my own trained language model instead of GPT?

### ISSUE THREAD

**Issue by yeserumo** [Significant-Gravitas/Auto-GPT#2126]
I need to use local model to do these jobs due to some reasons. Can I do this? Or how can i do this?

**Comment by Artemonim** [comment]
Have you used issue and pull request search?
It is one of the expected features, but it is not yet implemented. You can find some workarounds in the comments.

**Comment by veerareddyvishal144** [comment]
Yes you can do this 
in llm_utils.py
you can see create_chat_completion where you can switch models accordingly

**Comment by ntindle** [comment]
Lots of different efforts on this. Check discord and PRs for more info
