### ISSUE TITLE
The model: `gpt-4` does not exist 这个问题怎么解决？

### ISSUE THREAD

**Issue by gzp20182108** [Significant-Gravitas/Auto-GPT#2133]
The model: `gpt-4` does not exist 这个问题怎么解决？

**Comment by Artemonim** [comment]
Use `--gpt3only` or pay to OpenAI

**Comment by nponeccop** [comment]
@Artemonim Isn't there an API waitlist?

**Comment by gklab** [comment]
> The model: `gpt-4` does not exist 这个问题怎么解决？

先去官网申请gpt4 waitlist，有申请成功的邮件后才可以调用。申请成功前可以先用3

**Comment by ntindle** [comment]
Need more info
