### ISSUE TITLE
How to limit the interface to only GPT-3.5?

### ISSUE THREAD

**Issue by weiyoubest** [Significant-Gravitas/Auto-GPT#2134]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [X] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

--gpt3only The command gpt3only is no work  Where are the modifications made in Env? gpt-3 only

### Current behavior 😯

The model: gpt-4 does not exist

### Expected behavior 🤔

Where are the modifications made in Env? gpt-3 only

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Explorergt92** [comment]
You shouldn't need to modify the file, using `python -m autogpt --gpt3only` to start Auto-GPT is working on my end. 

If it still doesn't work for you, try changing line 39 in your `".env"` file from `SMART_LLM_MODEL=gpt-4` to `SMART_LLM_MODEL=gpt-3.5-turbo'

**Comment by weiyoubest** [comment]
> You shouldn't need to modify the file, using `python -m autogpt --gpt3only` to start Auto-GPT is working on my end.
> 
> If it still doesn't work for you, try changing line 39 in your `".env"` file from `SMART_LLM_MODEL=gpt-4` to `SMART_LLM_MODEL=gpt-3.5-turbo`

thank you  I will try

**Comment by Holpa** [comment]
what about using GPT 2.5 legacy the free version? Turbo needs a subscription

**Comment by ntindle** [comment]
Fixed?
