### ISSUE TITLE
No response after starting the command using ‘’Python - m autogpt‘’

### ISSUE THREAD

**Issue by feng199464** [Significant-Gravitas/Auto-GPT#2140]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [ ] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Current behavior 😯

![1681724328352](https://user-images.githubusercontent.com/46559381/232446603-c47ffa16-3349-4eba-b9fa-035f655175b3.png)

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Qoyyuum** [comment]
Can you show what is in your `G:\IDEA_WORKSPACE\Auto-GPT` folder? Is there a folder for `autogpt`? @feng199464

**Comment by feng199464** [comment]
> 

![image](https://user-images.githubusercontent.com/46559381/232487857-b060f33a-a561-45dc-ba5b-ab6c7fbe9822.png)

**Comment by Qoyyuum** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/46559381/232487857-b060f33a-a561-45dc-ba5b-ab6c7fbe9822.png)
> 

Can you confirm if there's anything in autogpt folder?

If there is, can you retry `python -m autogpt`?

**Comment by feng199464** [comment]
> > > 
> > 
> > 
> > ![图像](https://user-images.githubusercontent.com/46559381/232487857-b060f33a-a561-45dc-ba5b-ab6c7fbe9822.png)
> 
> 你能确认 autogpt 文件夹中是否有任何东西吗？
> 
> 如果有，可以重试吗？`python -m autogpt`
Still like this
![image](https://user-images.githubusercontent.com/46559381/232641856-58452c63-2a9e-43be-8bee-cc610209ab35.png)

**Comment by Qoyyuum** [comment]
Do you have Python installed?

**Comment by feng199464** [comment]
> 你有安装 Python 吗？

Thank you. It's already resolved
