### ISSUE TITLE
Project help: Tier 1 support volunteers are wanted

### ISSUE THREAD

**Issue by nponeccop** [Significant-Gravitas/Auto-GPT#2144]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

People who would like to volunteer as Tier-1 support can contact me (I'm @nponeccop there too) on the official Discord server (or just write here in comments). Also @pi is of great help there.

Presently, there is a flow of low-quality reports, where people are having various support issues or have bad prompts so that AutoGPT doesn't work for them. We need someone to sort those out and help those people with their problems.

If you feel that you can work as a T1 we can give you labeling permissions. It usually takes a day.

### Examples 🌈

Is possible execute auto-gpt on Debian 11? #2141 - clearly a support question
How can I fix this and proceed? #2073 - it clearly comes from someone who has never used a tracker before

And so on.

### Motivation 🔦

There are already people working on sorting the issues out, but they are high-class engineers so it's not a good idea to waste their effort on easy tasks. This is a common issue in technical support, and it's solved by having support tiers, where T1 support faces all the support traffic, and escalates the issues they cannot solve to T2. And T2 escalates to T3 which is commonly core developers.

So:

- T1 labels the support requests as such using GitHub labels and helps the persons with their (relatively simple) problems
- T2 works on the remaining unlabeled requests to get bug reports and/or ask the authors to improve their reports (we already have it staffed but more persons are welcome), and to notify T3 of urgent problems, such as bugs in stable or recently introduced bugs in master
- T3 will be just our `contributors` group in Discord.

**Comment by dai-dao** [comment]
Why not just apply AutoGPT to answer and filter out these (relatively simple) problems

**Comment by k-boikov** [comment]
I would like to help with labeling, currently I try to do that in comments, I can also help with merge conflicts, but I guess that would require making a PR to the forked repo.

**Comment by moltra** [comment]
I would like to volunteer to help as a T1.  I am a hobby programming hacker, so I know enough to be able to help classify issues and requests.
