### ISSUE TITLE
Run Linting and Tests by default

### ISSUE THREAD

**Issue by nponeccop** [Significant-Gravitas/Auto-GPT#2154]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

I'd like to change project settings so that CI workflows (at least 2 of them) don't need approval and run whenever a pull request is created. It's a common configuration, and there are very few bad quality CI, so someone should find out how it is done and tell to @p-i- so that he tells to @Torantulino 

### Motivation 🔦

Many PRs are slowed down because of the extra round of me approving the PR.

**Comment by ntindle** [comment]
Are those the only two? Related #2424

**Comment by muhamrif** [comment]
I would like to work on it, if approved. Thankyou!

**Comment by Pwuts** [comment]
fixed (to the extent that it's possible) :)
