### ISSUE TITLE
Sort out team permissions

### ISSUE THREAD

**Issue by nponeccop** [Significant-Gravitas/Auto-GPT#2156]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

The support team needs labeling permissions added for them to be able to work.

@nponeccop requested to remove write access so that his preliminary approvals don't mean approval to merge.

Also there is a separate CI issue of running CI on all requests without an approval procedure

**Comment by Pwuts** [comment]
I think this is resolved
