### ISSUE TITLE
\ Thinking... (endlessly)

### ISSUE THREAD

**Issue by shayanjojo** [Significant-Gravitas/Auto-GPT#2169]
For a long time, stay on 
\ Thinking...
 and I can't do anything.
 
 `C:\Users\Shayan_GR>cd Auto-GPT

C:\Users\Shayan_GR\Auto-GPT>setx GOOGLE_API_KEY "AIzaS************************wI-0k6urUA"

SUCCESS: Specified value was saved.

C:\Users\Shayan_GR\Auto-GPT>setx CUSTOM_SEARCH_ENGINE_ID "516dc*********f27"

SUCCESS: Specified value was saved.

C:\Users\Shayan_GR\Auto-GPT>python -m autogpt
Warning: The file 'AutoGpt.json' does not exist. Local memory would not be saved to a file.
Welcome back!  Would you like me to return to being jk?
Continue with the last settings?
Name:  jk
Role:  help me to coding
Goals: ['Increase net worth', 'Grow Twitter Account', 'Develop and manage multiple businesses autonomously']
Continue (y/n): y
Using memory of type:  LocalCache
Using Browser:  chrome
- Thinking...

`

**Comment by laviua** [comment]
in my case debug shows the following
```
Using memory of type:  LocalCache
Using Browser:  chrome
  Token limit: 4000
  Memory Stats: (0, (0, 1536))
  Token limit: 4000
  Send Token Count: 922
  Tokens remaining for response: 3078
  ------------ CONTEXT SENT TO AI ---------------
  System: The current time and date is Mon Apr 17 13:54:30 2023
  
  System: This reminds you of these events from your past:



  
  User: Determine which next command to use, and respond using the format specified above:
  
  ----------- END OF CONTEXT ----------------
Creating chat completion with model gpt-3.5-turbo, temperature 0.0, max_tokens 3078
Error:  Reached rate limit, passing...
Error:  API Bad gateway. Waiting 4 seconds...
Error:  Reached rate limit, passing...
Error:  API Bad gateway. Waiting 8 seconds...
Error:  Reached rate limit, passing...
Error:  API Bad gateway. Waiting 16 seconds...
Error:  Reached rate limit, passing...
Error:  API Bad gateway. Waiting 32 seconds...
Error:  Reached rate limit, passing...
Error:  API Bad gateway. Waiting 64 seconds...
```

**Comment by tronving** [comment]
My --debug showed the exact same messages when I ran out of tokens. In your OpenAI dashboard, how much credit do you have left? Do you have a payment method linked?

**Comment by laviua** [comment]
yes, i found also two linked issues:
https://github.com/Significant-Gravitas/Auto-GPT/issues/2017
https://github.com/Significant-Gravitas/Auto-GPT/issues/2068

my plan is paid is I have the following.
in March tried to use Dalle2 via API, that's why it shows a bit usage

<img width="879" alt="image" src="https://user-images.githubusercontent.com/6020185/232508474-0aee77c9-1e52-4d36-86ab-a14d8984dcb6.png">

**Comment by tronving** [comment]
Do you have a payment method linked in platform.openai.com, or a ChatGPT Plus account?

**Comment by laviua** [comment]
yes, i have

**Comment by tronving** [comment]
Which one do you have?

**Comment by tronving** [comment]
Hmmm. Have you generated a new API key since you added your card? What are your preferences in the billing menu set to?

**Comment by laviua** [comment]
Yes, you were right.
I used the wrong account. API Key was generated via one account, but the paid account was setup in another!
Problem solved

**Comment by vgatto11** [comment]
I have a similar issue.
Can't think of an easier set of goals - but stuck forever in "Thinking."

sally is: food critic
Enter up to 5 goals for your AI:  For example: Increase net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously'
Enter nothing to load defaults, enter nothing when finished.
Goal 1: Conduct a Google search to find the best restaurant for chicken in Nashville, TN
Goal 2: Output the top result in a text file called chicken.txt
Goal 3: shutdown
Goal 4: 
Using memory of type:  LocalCache
Using Browser:  chrome
You can read more here: https://github.com/Significant-Gravitas/Auto-GPT#openai-api-keys-configuration
| Thinking...

**Comment by Pwuts** [comment]
@vgatto11 please try the solution mentioned in the thread. Closing as resolved for now.

**Comment by ninja-xu229** [comment]
![image](https://user-images.githubusercontent.com/59460199/234743178-8ead6c9e-6c1c-41bf-9cb7-aab550e7ccf5.png)
Free quota has expired

**Comment by Micbut** [comment]
I am using macbook m1 and I have the same issue - how can I solve it? 
I have a paid subscription to chatgpt

<img width="1166" alt="Screenshot 2023-04-28 at 21 00 43" src="https://user-images.githubusercontent.com/54619028/235232976-a28f0c75-33d9-46ed-a765-3fc290317782.png">
