### ISSUE TITLE
Command send_tweet not working

### ISSUE THREAD

**Issue by sjnt1** [Significant-Gravitas/Auto-GPT#2177]
the send_tweet command is not working for me: 

'Unknown command 'send_tweet'. Please refer to the 'COMMANDS' list for available commands and only respond in the specified JSON format.'

Any tips to what I am doing wrong? The twitter file with the send tweet is present in the commands folder

**Comment by gklab** [comment]
your version is the latest code?
'send_tweet' command add at yesterday.
try 'git pull' new code.

**Comment by sjnt1** [comment]
tried that and now autogpt is not working again :p

**Comment by sjnt1** [comment]
Ok so got it to work with 2.1. Not sure if it was the upgrade or the fact that i installed git that solved it
