### ISSUE TITLE
Rewrite the command system so each command is a plugin, so we can add commands as needed and disable defaults we do not want

### ISSUE THREAD

**Issue by grayfallstown** [Significant-Gravitas/Auto-GPT#2189]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

We need to have a flexible and extensible command system that allows us to easily add new commands and disable default commands that are not needed. Currently, the commands are hardcoded, making it difficult to customize the system to suit specific needs.

To address this, I propose rewriting the command system as plugins. Each command will be implemented as a separate plugin that can be added or disabled as needed. This will provide a modular approach to managing commands, allowing users to easily add new commands and share them with other users and disable default commands that are not required/desired for a given project.

### Motivation 🔦

- Flexibility: The ability to add new commands without modifying the core codebase. This will allow us to easily extend the functionality of our AI-Self-Prompting-System and adapt it to changing requirements.
- Customization: The ability to disable default commands that are not relevant to our project. This will help us streamline the system and make it more tailored to our specific use case.
- Scalability: The plugin-based architecture will provide a scalable and maintainable way to manage commands as our project grows and evolves over time.

To be honest, my primary motivation is to replace the google search API with the reddit API, as google got progressively worse over the years and these days google primarily delivers good results once you add reddit to your search. SEO is to blame here.

**Comment by ntindle** [comment]
This seems great for a potential plugin. Open an issue here: [Auto-GPT-Plugins](https://github.com/Significant-Gravitas/Auto-GPT-Plugins)
