### ISSUE TITLE
Issue with PlaySound error 263

### ISSUE THREAD

**Issue by alexandremassaro** [Significant-Gravitas/Auto-GPT#219]
I was having a issue with PlaySound when trying to play the speech.mpeg file it would throw an error 263 "The specified device is not open or is not recognized by MCI."

The fix I posted before doesn't work.

The one posted down in the comments by @VerteronParticle https://github.com/Torantulino/Auto-GPT/issues/219#issuecomment-1496832739  seems to be working.

For some people this was a better fix: https://github.com/Torantulino/Auto-GPT/issues/191#issuecomment-1496406940

**Comment by VerteronParticle** [comment]
I had this same problem on my system. I resolved it by passing an absolute path to playsound:

`import os
from playsound import playsound
import requests
from config import Config
cfg = Config()

# TODO: Nicer names for these ids
voices = ["ErXwobaYiN019PkySvjV", "EXAVITQu4vr4xnSDxMaL"]

tts_headers = {
    "Content-Type": "application/json",
    "xi-api-key": cfg.elevenlabs_api_key
}

def say_text(text, voice_index=0):
    tts_url = "https://api.elevenlabs.io/v1/text-to-speech/{voice_id}".format(
        voice_id=voices[voice_index])

    formatted_message = {"text": text}
    response = requests.post(
        tts_url, headers=tts_headers, json=formatted_message)

    if response.status_code == 200:
        with open("speech.mpeg", "wb") as f:
            f.write(response.content)
        current_dir = os.getcwd()
        file_path = current_dir + "/speech.mpeg" 
        playsound(file_path)
        # Delete audio file
        os.remove("speech.mpeg")
    else:
        print("Request failed with status code:", response.status_code)
        print("Response content:", response.content)`

**Comment by jlsnow301** [comment]
fixes listed here do not seem to be working.

@VerteronParticle please format your code snippet with triple backticks, not single

**Comment by Megachill** [comment]
@jlsnow301 this works for me on cmder under windows

```
import os
from playsound import playsound
import requests
from config import Config
cfg = Config()

#TODO: Nicer names for these ids

voices = ["ErXwobaYiN019PkySvjV", "EXAVITQu4vr4xnSDxMaL"]

tts_headers = {
    "Content-Type": "application/json",
    "xi-api-key": cfg.elevenlabs_api_key
}

def say_text(text, voice_index=0):
    tts_url = "https://api.elevenlabs.io/v1/text-to-speech/{voice_id}".format(voice_id=voices[voice_index])

    formatted_message = {"text": text}
    response = requests.post(
        tts_url, headers=tts_headers, 
        json=formatted_message
    )

    if response.status_code == 200:
        with open("speech.mpeg", "wb") as f:
            f.write(response.content)
        current_dir = os.getcwd()
        file_path = current_dir + "/speech.mpeg" 
        playsound(file_path)
        # Delete audio file
        os.remove("speech.mpeg")
    else:
        print("Request failed with status code:", response.status_code)
        print("Response content:", response.content)
```

**Comment by MoreTore** [comment]
I have the same issue but it works sometimes but then it will stop working while running.
