### ISSUE TITLE
MEMORY_INDEX defined twice in env tempalte

### ISSUE THREAD

**Issue by k-boikov** [Significant-Gravitas/Auto-GPT#2191]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [ ] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Current behavior 😯

In the ### WEAVIATE section we have MEMORY_INDEX=AutoGpt (added 15.04.23), but above in ### REDIS we have MEMORY_INDEX=auto-gpt (added 3 days earlier)

### Expected behavior 🤔

Env variables should have different names if they need to be different memory files or if its ok to be one file - to remove the second declaration. (discussion needed)

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by ntindle** [comment]
Is this fixed now?

**Comment by k-boikov** [comment]
Yes, it is on master and latest release, but it fixes the template, old .env would need to be updated.
