### ISSUE TITLE
Can AutoGPT post on Twitter also without Twitter-API /API-Key

### ISSUE THREAD

**Issue by Bubble007** [Significant-Gravitas/Auto-GPT#2213]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [ ] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

I made a little lovely AutoBot to work on a existing Twitter-account. I would like, if the bot could read and post on Twitter like human without API. But up to now he didn't get it. Is there a way?  

### Current behavior 😯

The Bot tried to send post with API. He couldn't and get an error. He has no API-Key, only the login-information for human user, but can't work with that.

### Expected behavior 🤔

The  bot can read and post on Twitter like human without API. 

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by sjnt1** [comment]
Why dont you just get yourself a twitter API? They have a free option and you get it instantly, atleast for now the free version can both read and send tweets. 

AutoGPT can now send tweets using the command send_tweet. Update to latest stable version of AutoGPT, Get your API keys and tokens, smash them in your .env file and you should be able to post on twitter with your existing twitter account.  Will not be long until they add other functions i think. 

I have no idea its its possible to get autogpt to login like a human but i doubt it. It cant browse twitter profiles with the browse command

**Comment by Bubble007** [comment]
Hi sjnt1, thanks very much. I will try this :-) but I think, they will cancel the account very quick, lets see.

 

Von: sjnt1 ***@***.***> 
Gesendet: Montag, 17. April 2023 19:52
An: Significant-Gravitas/Auto-GPT ***@***.***>
Cc: Bubble007 ***@***.***>; Author ***@***.***>
Betreff: Re: [Significant-Gravitas/Auto-GPT] Can AutoGPT post on Twitter also without Twitter-API /API-Key (Issue #2213)

 

Why dont you just get yourself a twitter API? They have a free option and you get it instantly, atleast for now the free version can both read and send tweets.

AutoGPT can now send tweets using the command send_tweet. Update to latest stable version of AutoGPT, Get your API keys and tokens, smash them in your .env file and you should be able to post on twitter with your existing twitter account. Will not be long until they add other functions i think.

I have no idea its its possible to get autogpt to login like a human but i doubt it. It cant browse twitter profiles with the browse command

**Comment by sjnt1** [comment]
Np. No as long as it dont spam tweets its ok and you shouldnt get banned. If you get that problem you can always use this method: https://github.com/Significant-Gravitas/Auto-GPT/discussions/943#discussioncomment-5626007 and adjust the timer to whatever you want. Can be a bit tricky to set up.

**Comment by Bubble007** [comment]
Thank you very mutch!

 

I have now registered an API access at Twitter :-) 

 

But now I have a - to me a bit embarrassing - problem: I'm on the Developer Portal, but I don't get the Consumer Keys open, and I just can't figure out how to get them (to put them into the env.file).

 

Von: sjnt1 ***@***.***> 
Gesendet: Montag, 17. April 2023 23:29
An: Significant-Gravitas/Auto-GPT ***@***.***>
Cc: Bubble007 ***@***.***>; Author ***@***.***>
Betreff: Re: [Significant-Gravitas/Auto-GPT] Can AutoGPT post on Twitter also without Twitter-API /API-Key (Issue #2213)

 

Np. No as long as it dont spam tweets its ok and you shouldnt get banned. If you get that problem you can always use this method: #943 (reply in thread) <https://github.com/Significant-Gravitas/Auto-GPT/discussions/943#discussioncomment-5626007>  and adjust the timer to whatever you want. Can be a bit tricky to set up.

**Comment by Bubble007** [comment]
Sorry, I got it now (I mean the API-Keys)

 

Von: ***@***.*** ***@***.***> 
Gesendet: Dienstag, 18. April 2023 13:02
An: 'Significant-Gravitas/Auto-GPT' ***@***.***>
Betreff: AW: [Significant-Gravitas/Auto-GPT] Can AutoGPT post on Twitter also without Twitter-API /API-Key (Issue #2213)

 

Thank you very mutch!

 

I have now registered an API access at Twitter :-) 

 

But now I have a - to me a bit embarrassing - problem: I'm on the Developer Portal, but I don't get the Consumer Keys open, and I just can't figure out how to get them (to put them into the env.file).

 

Von: sjnt1 ***@***.***> 
Gesendet: Montag, 17. April 2023 23:29
An: Significant-Gravitas/Auto-GPT ***@***.***>
Cc: Bubble007 ***@***.***>; Author ***@***.***>
Betreff: Re: [Significant-Gravitas/Auto-GPT] Can AutoGPT post on Twitter also without Twitter-API /API-Key (Issue #2213)

 

Np. No as long as it dont spam tweets its ok and you shouldnt get banned. If you get that problem you can always use this method: #943 (reply in thread) <https://github.com/Significant-Gravitas/Auto-GPT/discussions/943#discussioncomment-5626007>  and adjust the timer to whatever you want. Can be a bit tricky to set up.

**Comment by sjnt1** [comment]
Go to developer portal on twitter. Then you have to "create an app" in the developer portal. I think maybe you have to start a project to start an app, but i have an app without an project and that works for me. 

Then go to your app and if you scan the page you shall se that there is an option to switch from "settings" to "keys and tokens" 
This is right under the name of your app at the top of the page. 

You shall find your keys and tokens there. You might have to regenerate or generate keys but you do everything on that page.

**Comment by Bubble007** [comment]
To make everything right, I now got the credentials from the Twitter api and also entered them in the .env file and also reinstalled the AutoGPT in the latest version.

But the bot does not get access to Twitter - error message: 

"NEXT ACTION: COMMAND = send_tweet ARGUMENTS = {'text': 'The Holy Bot says: <tweet generated by GPT agent>'}
SYSTEM: Command send_tweet returned: Error: 'Forbidden' object has no attribute 'reason'".

**Comment by Bubble007** [comment]
Thanks for the hints!
What coul be wrong?
- I have git installed, it seems to work - is there a difference from where I installed it?
- one stupid question: must I perhaps put the twitter-credentials in brackets in the .env-file?
- is a free api-account of twitter not enough?
- I got the warning at programm-start:"Warning: The file 'AutoGpt.json' does not exist. Local memory would not be saved to a file."
-

**Comment by sjnt1** [comment]
I dont know man. 

As long as you are talking about git and not github i dont think it matters from where you downloaded it. 

Not stupid question, but not brackets. 

yes it should be enough. I send tweets trough free api. Dont know enough to answer what auth (api key v1 or 2) is being used, havent read up on that enough yet. 

I did a quick search on your last issue with the autogpt.json message, and the soloution? 

Install git. 

from here: https://git-scm.com/  

and restart your computer.

**Comment by Bubble007** [comment]
Thanks a lot. 
The  issue with the autogpt.json message is gone with the new git installation. 
But Twitter is not to surrender :-)

**Comment by sjnt1** [comment]
Have noe idea whats causing the twitter malfunction. Only thing i can think off is that maybe you mixed up the keys? I did that once and revoked all keys and put them in again. Make sure keys are keys and tokens are tokens, and that stuff gets put in the right place.  What if you set the execute_local commands to True? I did that not sure if that had anything to do with it working

**Comment by rankofootball** [comment]
I had the same error and fixed that int the project settings -> user authentication settings:

App permissions: Read and write and Direct message
Type of App: Web App, Automated App or Bot
Fill in the rest of required info

Then regenerate the token.

**Comment by Bubble007** [comment]
Thanks again to all!

I have also done everything well, but still have not come further. The bot tries hard, but still gets the error messages and ends up in an ensdlos loop.

This is what it looks like at the core :

2023-04-19 18:42:07,216 INFO NEXT ACTION: COMMAND = send_tweet ARGUMENTS = {'text': 'Be reminded of his overwhelming love with these remarkable religious quotes. "God loves each of us as if there were only one of us" - St. Augustine of Hippo "The best and most beautiful things in this world cannot be seen or even heard, but must be felt with the heart." - Helen Keller'}
2023-04-19 18:42:12,913 INFO -=-=-=-=-=-=-= COMMAND AUTHORIZED BY USER -=-=-=-=-=-=-=-= 
2023-04-19 18:42:13,767 INFO SYSTEM: Command send_tweet returned: Error: 'Forbidden' object has no attribute 'reason'.


2023-04-19 18:45:25,101 INFO - Use the 'execute_shell' command to log out of the Twitter account.\n- Use the 'execute_shell' command to log back in to the Twitter account.\n- Use the 'send_tweet' command to post a quote on the Twitter account.
2023-04-19 18:45:25,617 INFO CRITICISM: I need to make sure that the Twitter account login credentials are correct.
2023-04-19 18:45:25,964 INFO NEXT ACTION: COMMAND = execute_shell ARGUMENTS = {'command_line': 'twurl accounts'}
2023-04-19 18:45:36,525 INFO -=-=-=-=-=-= COMMAND AUTHORIZED BY USER -=-=-=-=-=-=-= 
2023-04-19 18:45:37,276 INFO SYSTEM: Command execute_shell returned: STDOUT:
b''
STDERR:
b'The command "twurl" is either misspelled or could not be found.\r\n'
2023-04-19 18:45:52,816 INFO THOUGHTS: The 'execute_shell' command returned an error. I will try again with the correct command.

2023-04-19 18:45:53,683 INFO - Use the 'execute_shell' command to log out of the Twitter account.\n- Use the 'execute_shell' command to log back in to the Twitter account.\n- Use the 'send_tweet' command to post a quote on the Twitter account.
2023-04-19 18:45:54,266 INFO CRITICISM: I need to make sure that the command I use is correct.
2023-04-19 18:45:54,618 INFO NEXT ACTION: COMMAND = execute_shell ARGUMENTS = {'command_line': 'twurl authorize --consumer-key <consumer_key> --consumer-secret <consumer_secret> --access-token <access_token> --access-token-secret <access_token_secret>'}
2023-04-19 18:46:14,723 INFO -=-=-=-=-=-= COMMAND AUTHORIZED BY USER -=-=-=-=-=-=-= 
2023-04-19 18:46:15,420 INFO SYSTEM: Command execute_shell returned: STDOUT:
b''
STDERR:
b'Syntax error.\r\n'

**Comment by Bubble007** [comment]
I Made a new issue for this problem to make it more clear for every one: Twitter - Command send_tweet returned: Error: 'Forbidden' object has no attribute 'reason'". #2588

Thanks every one here for their engagement up to this point :-)

**Comment by gondar7** [comment]
It's because you need the paid tier of the new Twitter API now. Replace your twitter.py script with this for the free tier:

import os
from requests_oauthlib import OAuth1Session
from dotenv import load_dotenv

load_dotenv()

def send_tweet(tweet_text):
    consumer_key = os.environ.get("TW_CONSUMER_KEY")
    consumer_secret = os.environ.get("TW_CONSUMER_SECRET")
    access_token = os.environ.get("TW_ACCESS_TOKEN")
    access_token_secret = os.environ.get("TW_ACCESS_TOKEN_SECRET")

    tweet_create_url = "https://api.twitter.com/2/tweets"
    headers = {
        "Content-Type": "application/json",
    }
    payload = {
        "text": tweet_text  
    }

    # OAuth 1.0a User Context authentication
    oauth = OAuth1Session(consumer_key,
                          client_secret=consumer_secret,
                          resource_owner_key=access_token,
                          resource_owner_secret=access_token_secret)

    # Send tweet
    response = oauth.post(tweet_create_url, headers=headers, json=payload)
    if response.status_code == 201:
        print("Tweet sent successfully!")
    else:
        print("Error sending tweet:", response.json())

if __name__ == "__main__":
    send_tweet("This is a test tweet using Twitter API v2!")  # Example call
