### ISSUE TITLE
No module named autogpt - MacOs

### ISSUE THREAD

**Issue by spooksie** [Significant-Gravitas/Auto-GPT#2216]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [ ] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

I've followed the steps as per the tutorial. Installed Python via brew and it shows this error.

```
❯ python -m autogpt
/Applications/Xcode.app/Contents/Developer/usr/bin/python3: No module named autogpt
```

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by k-boikov** [comment]
Please verify that you are running `python -m autogpt` from the root of the project.

**Comment by 230238** [comment]
"You need to enter the AutoGpt folder and have Python environment variables.

**Comment by spooksie** [comment]
The fix was to add 3 to python

`python3 -m autogpt`
