### ISSUE TITLE
browse_website is broken on RPi

### ISSUE THREAD

**Issue by talvasconcelos** [Significant-Gravitas/Auto-GPT#2219]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

On latest, using selenium, on an arm device, browse_website doesn't work, as it doesn't get the correct (if any) drivers. 

Also, using chromium, as there's no chrome on the RPI, needs some selenium love, I'm trying to add it locally but still testing. 

Please guys, don't start assuming everyone is on a desktop, or on windows, or any assumptions!

**Comment by Pwuts** [comment]
> Please guys, don't start assuming everyone is on a desktop, or on windows, or any assumptions!

We learned that the hard way over the past week :')

**Comment by cryptidv** [comment]
Chromium is supported, and with #2066 you should be able to specify the chromium binary (I'm not sure if that will fix as I think you would still selenium drivers). However I do agree, non-selenium web-scraping should still be supported.

**Comment by Pwuts** [comment]
@talvasconcelos can you post the output of the WebDriver manager? (like in #2600)

**Comment by Pwuts** [comment]
https://github.com/SeleniumHQ/docker-selenium/issues/1076

**Comment by talvasconcelos** [comment]
> @talvasconcelos can you post the output of the WebDriver manager? (like in #2600)

i don't have an output, webdriver just installs the wrong driver (i assume it's because of the settings in user-agent)

**Comment by Pwuts** [comment]
Which one does it install, and which one *should* it install?

**Comment by k-boikov** [comment]
The user-agent is used only for the http request header, that could not be the issue.
