### ISSUE TITLE
SYSTEM:  Command google returned: Error: timed outt

### ISSUE THREAD

**Issue by lihongyong** [Significant-Gravitas/Auto-GPT#2222]
"SYSTEM: Command google returned: Error: timed out" is displayed. I don't know how to deal with it. Help Please.

**Comment by levidyrek** [comment]
Had the same issue. Make sure you follow these instructions very carefully: https://github.com/Significant-Gravitas/Auto-GPT#-google-api-keys-configuration

I missed the step to enable the Custom Search API.

**Comment by lihongyong** [comment]
wow. thank you.
