### ISSUE TITLE
Why GPT 4 payment Nagging?

### ISSUE THREAD

**Issue by nostrodamus2023** [Significant-Gravitas/Auto-GPT#2223]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [x] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

just why was this added, gpt 3.5 turbo is a great option for developers.

### Current behavior 😯

I guess we all have different ideas what ' open ' means.

here: https://github.com/Significant-Gravitas/Auto-GPT#openai-api-keys-configuration

### Expected behavior 🤔

why a nag? is this an android app already?

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by LuckyoKnight** [comment]
I'm having the same problem

**Comment by ezolenko** [comment]
Same, I still have a couple of quarters left off the trial grant, so gpt4 requests should still be going through

**Comment by Pwuts** [comment]
@nostrodamus2023 you get that warning if Auto-GPT's API requests get rate limited

**Comment by nelsonchung** [comment]
Would this cause the process to be unable to proceed, or should I consider switching the chatgpt engine from GPT4 to GPT3.5?

**Comment by Li1177** [comment]
> DOUBLE CHECK CONFIGURATION Please double check that you have setup a PAID OpenAI API Account. You can read more here: https://github.com/Significant-Gravitas/Auto-GPT#openai-api-keys -configuration Added chunk 3 summary to memory Adding chunk 4 / 15 to memory Summarizing chunk 4 / 15 DOUBLE CHECK CONFIGURATION Please double check that you have setup a PAID OpenAI API Account. You can read more here: https://github.com/Significant-Gravitas/Auto-GPT#openai-api-keys -configuration Added chunk 4 summary to memory Adding chunk 5 / 15 to memory Summarizing chunk 5 / 15 DOUBLE CHECK CONFIGURATION Please double check that you have setup a PAID OpenAI API Account. You can read more here: https://github.com/Significant-Gravitas/Auto-GPT#openai-api-keys
> 
> bla, what a waste of bytes.

Same. I use gpt3.5 api,why showing these error message

**Comment by ezolenko** [comment]
This has nothing to do with gpt4, it means your script sends too many requests to either model. Paid account has higher rate limit so you would see this more often. Error message is confusing.

**Comment by ntindle** [comment]
Sometimes it executes something unexpected or doesn’t do what you want.  Check out the #prompt-engineering channel in discord to get a better fit prompt 

Also #6

**Comment by mooneee** [comment]
metoo

**Comment by Pwuts** [comment]
Free accounts are limited to 3 requests per minute, which is less than Auto-GPT needs and exactly why we strongly recommend setting up a paid account.

**Comment by Damian-AndT** [comment]
> 

So it is not possible to use Auto-GPT with a free account?

**Comment by Pwuts** [comment]
@antoan please post a log when reporting an issue
