### ISSUE TITLE
Relevant memory is essentially a duplicate of the conversation

### ISSUE THREAD

**Issue by yackimoff** [Significant-Gravitas/Auto-GPT#2232]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [X] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Current behavior 😯

Look at the code here:
https://github.com/Significant-Gravitas/Auto-GPT/blob/75baa11e8196d9cdb26d26bf971ce3f98ebdaee5/autogpt/chat.py#L85

To generate context for the request, autogpt currently fetches 10 most relevant "memories" to previous 10 messages without any filtering. It doesn't make sense, since these previous 10 messages *are* in the database, so they're essentially most relevant to themselves.

### Expected behavior 🤔

1. Messages that are still part of a conversation sent to the model should not at the same time be sent as "past events" to it.
2. "Past events" should be sorted chronologically to not confuse the model.

### Your prompt 📝

Irrelevant.

**Comment by jeremylaratro** [comment]
From my experience, there is no contextual memory when using the OpenAI API ( only when you're using the web interface), so I'm assuming this is the workaround the devs decided to use for this issue, but I'm not a dev on this project so I don't know for sure

**Comment by yackimoff** [comment]
Yeah, it is a workaround of context length limit. It's actually great idea. It's just not implemented thoughtfully.

**Comment by fluxism** [comment]
I added some discussion of this issue at https://github.com/Significant-Gravitas/Auto-GPT/discussions/2847 before I saẇ this issue.
