### ISSUE TITLE
Changing the temperature results in garbled text

### ISSUE THREAD

**Issue by T-Higgins** [Significant-Gravitas/Auto-GPT#2236]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [ ] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

1. Change the temperature to 2 or 1.5 in the .env file (both values worked for me)
2. Try a scenario and watch it generate endless garbled text :) 

https://github.com/Significant-Gravitas/Auto-GPT/discussions/2224

### Current behavior 😯

AutoGPT produces incredibly garbled responses to any input.

https://github.com/Significant-Gravitas/Auto-GPT/discussions/2224

### Expected behavior 🤔

AutoGPT should give legible, understandable responses

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by k-boikov** [comment]
AutoGPT is not responsible for the garbled responses, everything is produced by the LLM. I don't think its AutoGPT's job to correct them if you allow the LLM to produce garbled responses.

**Comment by T-Higgins** [comment]
> AutoGPT is not responsible for the garbled responses, everything is produced by the LLM. I don't think its AutoGPT's job to correct them if you allow the LLM to produce garbled responses.

It resulted from a setting in AutoGPT's env file. I've never, ever seen ChatGPT do anything even remotely close to this. Did you look at the related thread I included?

**Comment by k-boikov** [comment]
The value from the .env is passed to GPT.
![image](https://user-images.githubusercontent.com/64261260/232622109-6d6d0920-99c0-4cfb-a148-3bde6c9018ce.png)

**Comment by cryptidv** [comment]
I don't think is an issue with AutoGPT at all. As per OpenAI's [documentation](https://platform.openai.com/docs/api-reference/chat/create#chat/create-temperature), the `temperature` of a chat completion model can be set from `0` to `2.0`.

And as @k-boikov pointed out, this would be expected behavior for any LLM.

**Comment by T-Higgins** [comment]
I've been experimenting with this more and there is definitely something strange going on. 

The default temperature value 1 works fine, obviously.

0 also works fine, but AutoGPT completely ignores any inputs you give it after the initial scenario and goals. It just continues on with the path it was following no matter what you right.

However, any value between 1 and 2 completely breaks AutoGPT. It generates the kind of gibberish I've shared above no matter what value you choose.

**Comment by T-Higgins** [comment]
Just another thought from some things I've seen this week.
I got access to GPT-4 and started messing with it in the Open AI Playground.

There, the Temperature scale runs from 0 to 1. 
Its default setting is 0.7.
Should AutoGPT's temperature range be similar?
In other words, 0 to 1 instead of 0 to 2 as it is in the ENV file?
Is it possible that Open AI's documentation has an error?

@cryptidv

**Comment by cryptidv** [comment]
I don't think OAI's docs themselves have a mistake in them. The range they allow for some reason with the API is 0-2. Going over that results in an api error (I think) Why? I have no idea. Anything over 1 is most definitely going to break autogpt as chatgpt is gonna go a little too crazy. Generally speaking, it's good to leave autogpt on anything under `0.5` so it can use tools, stick to correct output, etc.

But yea, there's a reason in the OAI playground temperature is a range from 0-1.

**Comment by T-Higgins** [comment]
> I don't think OAI's docs themselves have a mistake in them. The range they allow for some reason with the API is 0-2. Going over that results in an api error (I think). Anything over 1 is most definitely going to break autogpt as chatgpt is gonna go a little too crazy. Generally speaking, it's good to leave autogpt on anything under `0.5` so it can use tools, stick to correct output, etc.
> 
> But yea, there's a reason in the OAI playground temperature is a range from 0-1.

Keeping it below 0.5 is good advice, especially since the default is set to 1. It might even be why people have so many looping errors. 

Maybe worth adding to the documentation?

**Comment by T-Higgins** [comment]
Anecdotal evidence, but I dropped the Temperature to 0.5 and it seems to be
working better.
