### ISSUE TITLE
Please set your OpenAPI API key in .env or as an environment variable

### ISSUE THREAD

**Issue by Borrismorris** [Significant-Gravitas/Auto-GPT#2243]
This script was working perfectly until it was updated yesterday. Command prompts seem to have changed and for the life of me i CANNOT remember them, new python commands dont seem to be working. Is there any reason the stable version NEEDED to be changed in this way? I have tried re-installing the stable version and now i am having issues and getting an error
![image](https://user-images.githubusercontent.com/40410556/232610346-756be7a3-9420-4108-a378-ee1781e80b33.png)
i have tried numberous times to figure out the problem, but upon downloading i dont even get the .envtemplate file i just get the .env , so just saying this was some bad changes for no reason?

**Comment by k-boikov** [comment]
The reason that you don't get an .env.template is probably that you have "Hide extensions for known file types" enabled. Disable it and you will be able to get to the .env.temaplte file, copy it to .env and put your API key there.

**Comment by Borrismorris** [comment]
![image](https://user-images.githubusercontent.com/40410556/232613939-95b8b4b9-887a-4085-9c97-997b52002efb.png)

![image](https://user-images.githubusercontent.com/40410556/232613990-12bc5690-7fa8-4f65-bb2e-40e2b765c4b1.png)


Ok so that got me so far and i found the .template file, however im now getting this message instead, and im still using the same API keys

**Comment by Borrismorris** [comment]
And once i decided to add another API key (fixing this issue) i got a different message

![image](https://user-images.githubusercontent.com/40410556/232614845-ccb1f998-eeb9-4009-851b-a6715176097c.png)

**Comment by Borrismorris** [comment]
I have managed to get it working but somehow setting it to default used the pinecone memory??? Not sure how that helps anyone else but it might help them get it working. Just saying something has changed and its not as simple for a casual idiot like myself

**Comment by Timmytim1976** [comment]
yup they changed something they changed the default search from Google to bloody crappy chrome.

**Comment by k-boikov** [comment]
> And once i decided to add another API key (fixing this issue) i got a different message
> 
> ![image](https://user-images.githubusercontent.com/40410556/232614845-ccb1f998-eeb9-4009-851b-a6715176097c.png)

Seems like you have an issue with pinecone, please check PINECONE_API_KEY and PINECONE_ENV in your .env. They need to match the pinecone's dashboard values.
![image](https://user-images.githubusercontent.com/64261260/232621560-4f634e06-3e57-41ab-bdd0-8fb1153584fe.png)

**Comment by epicshardz** [comment]
I am receiving the same error all of a sudden:
```
D:\Auto-GPT>python -m autogpt --debug
Please set your OpenAI API key in .env or as an environment variable.
You can get your key from https://beta.openai.com/account/api-keys
```

**Comment by epicshardz** [comment]
If it helps. I did change my API key to see if that would fix it, but same result. I use the .env file and I update in vscode. Worked previously. I don't use pinecone

**Comment by k-boikov** [comment]
Please verify that you are using .env file, not .env.template, if you have "Hide extensions for known file types" on it would hide the ".template" part of the name of the file.

**Comment by epicshardz** [comment]
@k-boikov thanks for the reply, yes I am using the .env file and I don't have the "Hide extensions for known file types" on. In addition, I am using VSCode to update the .env file. I just did another pull but issue persists.
![image](https://user-images.githubusercontent.com/1273172/232635536-9ac13fda-9734-482a-a9f3-b6380894746b.png)

**Comment by epicshardz** [comment]
![image](https://user-images.githubusercontent.com/1273172/232635601-e8f210c1-8b62-4a67-a4e5-1bab3f208571.png)

**Comment by epicshardz** [comment]
I restarted my computer and deleted the old files and just started over with a new zip. Works fine now.

**Comment by sloofin** [comment]
Same problem here, Monterey 12.6.4, got a new openai key, made no difference. Wiping and reinstalling it all and hoping that works.

**Comment by Pwuts** [comment]
Closing as resolved
