### ISSUE TITLE
Auto-GPT-0.2.1 - GIT_PYTHON_REFRESH Error

### ISSUE THREAD

**Issue by Jluethke** [Significant-Gravitas/Auto-GPT#2248]
### Discussed in https://github.com/Significant-Gravitas/Auto-GPT/discussions/2247

<div type='discussions-op-text'>

<sup>Originally posted by **Jluethke** April 17, 2023</sup>
I had ran Auto-GPT-0.2.0 Since saturday. That has been working -eh'ish for me. It started to provide issues. Found the .1 update and trying to configure/run and I am now getting this error. 

Suggestions? 

![image](https://user-images.githubusercontent.com/131061783/232613658-16c76256-1fc7-4bb5-9669-02960d2c645e.png)
![image](https://user-images.githubusercontent.com/131061783/232613855-c6ef13bd-6f86-48cd-9e2e-9d05dbd15fa6.png)
</div>

**Comment by k-boikov** [comment]
Check this https://github.com/Significant-Gravitas/Auto-GPT/issues/2190#issuecomment-1511967805

**Comment by Jluethke** [comment]
> Check this [#2190 (comment)](https://github.com/Significant-Gravitas/Auto-GPT/issues/2190#issuecomment-1511967805)

That got me through most of the hurdles, however, I am running into an issue where it cannot find it's own directory.  Immediately tried to have it fix itself.

![image](https://user-images.githubusercontent.com/131061783/232628743-fe50b664-fe3a-48fd-94c5-7abe5dc49e17.png)

**Comment by k-boikov** [comment]
"read_file" is looking in the workspace directory, that is how it was coded. You can try telling it to clone the AutoGPT repo in the workspace directory and then search for bugs.

**Comment by Jluethke** [comment]
I did as you suggested and it wrote the file to the wrong directory altogether. I think you know what i'm going after here. I just wanted to be able to read/write files and generate a working UI for this (Not AgentGPT) 
![image](https://user-images.githubusercontent.com/131061783/232635365-9d260087-2684-4542-9314-e630e1101d6f.png)
![image](https://user-images.githubusercontent.com/131061783/232635528-a76c1c13-1159-4a3c-b283-55bd8a58b5ed.png)



> "read_file" is looking in the workspace directory, that is how it was coded. You can try telling it to clone the AutoGPT repo in the workspace directory and then search for bugs.

**Comment by Qoyyuum** [comment]
You need to prompt it to work inside its workspace folder, not in a different folder outside of it.

**Comment by ifcen** [comment]
In the file "git_operations.py", add 
"import os
os.environ["GIT_PYTHON_REFRESH"] = "quiet""
before "import git"

As shown below:

"""Git operations for autogpt"""
import os
os.environ["GIT_PYTHON_REFRESH"] = "quiet"
import git

**Comment by zhihuiyunrui** [comment]
请问有办法解决语言互译功能，输入母语自动转换为英文输入给Auto-GPT执行，Auto-GPT输出英文自动转换为母语输出。 执行令命行除了。

**Comment by zhihuiyunrui** [comment]
May I ask if there is a way to solve the language translation function? That is, automatically converting input in one's native language into English for Auto-GPT execution, and then automatically converting output back into one's native language. Additionally, running commands does not require translation.

**Comment by ntindle** [comment]
I would work on changing the prompt to fit your goals better. Clarifications are always helpful. Go to the #prompt-engineering chat on discord for more help

**Comment by ntindle** [comment]
Closing as I think we fixed the primary issue, open a new one for any additional problems
