### ISSUE TITLE
Free accounts don't work?

### ISSUE THREAD

**Issue by LockMan007** [Significant-Gravitas/Auto-GPT#225]
I don't have a paid account. I tried these settings:
OPENAI_API_KEY= **(NOT GOING TO POST THIS)**
ELEVENLABS_API_KEY= **(I tried with and without this)**
SMART_LLM_MODEL="gpt-3.5-turbo" _(suggested by someone on github for people that can't get it to work with the --gpt3only)_
FAST_LLM_MODEL="gpt-3.5-turbo"
GOOGLE_API_KEY=
CUSTOM_SEARCH_ENGINE_ID=

but no matter what I try, the errors are always the same:

Traceback (most recent call last):
  File "C:\Auto-GPT-master\scripts\main.py", line 3, in <module>
    import commands as cmd
  File "C:\Auto-GPT-master\scripts\commands.py", line 1, in <module>
    import browse
  File "C:\Auto-GPT-master\scripts\browse.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by EricFedrowisch** [comment]
This is an import error, so your python can't find a module it needs. 
You can try getting requests module, the one it's asking for with:
`
python -m pip install requests
`

To make sure you have all the requirements installed, you could also run this command from the project directory:
`
python -m pip install -r requirements.txt
`

**Comment by Anay21110** [comment]
Make sure to follow installation guide.
Inside `AutoGPT` run the command `pip install -r requirements.txt`
This will download all the required libraries

**Comment by hamzafar** [comment]
![image](https://user-images.githubusercontent.com/6842017/230191373-d23f0989-f74c-4c8e-bb51-7d2037cf060e.png)
The error mentioned above is occurring when I use a free OpenAI API key.

**Comment by EricFedrowisch** [comment]
Sorry, I don't have a free key and can't see a way to create one at OpenAI to try this out.

**Comment by Anay21110** [comment]
You can create one from [here](https://platform.openai.com/account/api-keys)

**Comment by EricFedrowisch** [comment]
Yes, thank you @Anay21110. To be clear, I know how to use that page to create API Keys. What I don't see is any option to create keys that would be set to "free". I've already provided OpenAI with payment info. Gonna bow outta this one as being unable to test, so unable to help.

**Comment by wonhyeongseo** [comment]
I'm pretty sure OpenAI will just charge API keys that go past the free-tier limit, and it's up to the user to monitor. That being said, it would be neat if there was a library that just inches beneath the limit automatically.

**Comment by r1di** [comment]
@LockMan007 
To clarify, OpenAI does not offer free API access. However, when you create an account, you will receive a $5 credit. It seems that you may be confusing this with the free web UI available at chat.openai.com.

**Comment by Explorergt92** [comment]
@LockMan007 is this still an issue for you or can this be closed?

**Comment by arcaela** [comment]
OpenAI stopped giving free API credits to new accounts a while ago, so you need billing set up.

If you want to experiment with AutoGPT-style agents without paying, you can use OpenAI-compatible APIs as drop-in replacements:

- **Groq** -- free Llama 3 access, very fast inference. https://console.groq.com
- **Google AI Studio** -- free Gemini API, generous limits. https://aistudio.google.com/apikey
- **Arko Studio** -- free API keys with an OpenAI-compatible endpoint at https://arko.arcaelas.com

You'd just need to update the base URL and model name in your config. All three support the same OpenAI SDK format.
