### ISSUE TITLE
data_ingestion.py does not work for Python 3.8.10

### ISSUE THREAD

**Issue by tencur** [Significant-Gravitas/Auto-GPT#2261]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [X] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

On Ubuntu 20.04 server VM with Python v3, run the following:

sudo python3 data_ingestion.py --dir Datafolder

### Current behavior 😯

Provides error: "Error while ingesting directory 'Datafolder': 'PosixPath' object has no attribute 'is_relative_to'"

It looks like this is a known issue to happen for version of python <3.9. 

Readme requirements state only requires Python 3.8 or later.

### Expected behavior 🤔

should ingest the file successfully.  

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by k-boikov** [comment]
Strange, I see 3.10
![image](https://user-images.githubusercontent.com/64261260/232628810-96058cb5-f923-4449-a128-c9072e229bdd.png)

**Comment by tencur** [comment]
You're absolutely right.  My mistake.  Closing.
