### ISSUE TITLE
Add a docker volume so that the config files can be accessed easier

### ISSUE THREAD

**Issue by moltra** [Significant-Gravitas/Auto-GPT#2265]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

if we create a docker volume and map the config files to it.  We can edit the config files easier.

**Comment by k-boikov** [comment]
If you mean the autogpt/config/* files - they are not supposed to be edited. Instead you should edit the .env file. There is a mapping in the docker-compose.yml for it.

**Comment by Pwuts** [comment]
Please make your proposal more specific and feel free to reopen the issue then.

**Comment by moltra** [comment]
I am talking about things like name, description... 

`AI Name: 
Entrepreneur-GPT here!  I am at your service.
Describe your AI's role:  For 
example, 'an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.'
Entrepreneur-GPT is: Enter up to 5 goals for your AI:  For example: Increase net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously'
Enter nothing to load defaults, enter nothing when finished.
Goal 1: 
Traceback (most recent call last):
  File "/app/main.py", line 325, in <module>
    prompt = construct_prompt()
             ^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 202, in construct_prompt
    config.save()
  File "/app/ai_config.py", line 72, in save
    with open(config_file, "w") as file:
         ^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/app/../ai_settings.yaml'
`

**Comment by Pwuts** [comment]
If I understand correctly, your issue is addressed by #1843
