### ISSUE TITLE
Requirements.txt package versions

### ISSUE THREAD

**Issue by Salaah01** [Significant-Gravitas/Auto-GPT#2269]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [ ] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

The requirements.txt do not have proper versions defined. This can be an issue if one of the dependencies were to update and break the environment. Consider putting actual versions for each package. This would be a proactive measure to ensure that the pipeline doesn't suddenly break due to a change in the dependencies.

Consider using something like pip-compile to track the dependencies of dependencies ensuring that all versions are correctly maintained.

If this is adopted, ensure dependabot/synk is setup to look out for security vulnerabilities in the packages.

### Current behavior 😯

Fetches the latest version of packages when running `pip install -r requirements.txt

### Expected behavior 🤔

It should install specific versions that have actually been tested.

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Pwuts** [comment]
Please give concrete examples of things breaking, or submit a PR to fix. This issue isn't actionable with the limited capacity we have.

**Comment by Salaah01** [comment]
I haven't got a live case right now for AutoGPT. However, I have experienced cases in the past where CI/CD pipelines would break for this very reason where a dependency would deprecate/change something and that would break the code.

This is a pretty easy fix, I can fix it myself and raise a PR.
