### ISSUE TITLE
Ability to save outside of working directory

### ISSUE THREAD

**Issue by 1nnovat1on** [Significant-Gravitas/Auto-GPT#2284]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

It is limiting to deny it access to outside the working directory, because it has a hard time saving code it wrote there. I think it should have access to the full os when cloning repositories. It should save the files it writes as scripts (python or otherwise)

### Examples 🌈

Allow it to save any where and also remember what directories it chose. 

Maybe there should be a 'left brain' and a 'right brain' - it should parse important info from its memories and save them in a list, like file paths

### Motivation 🔦

To improve its speed! It takes a long time to take action.

**Comment by sdfgsdfgd** [comment]
you can tell it to operate within a different directory in `Input: ` as a feedback, even after the beginning of the program.  

The memory management may not work perfectly every time though, sometimes it sets the working directory path to: 
`~/folder1/autogpt/working directory/~/Desktop/directory_you_wanted` 
so it can still go wrong in this way, but it could even be an issue with GPT-3.5's transformer.

**Comment by Pwuts** [comment]
You have ticked the box but failed to search for existing issues... #23 #1862 #2131
