### ISSUE TITLE
WeChat Group - 加入微信群，一起讨论快速解决问题。我已经实现输入、输出、目标设定都搞成中文了。

### ISSUE THREAD

**Issue by laixiao** [Significant-Gravitas/Auto-GPT#2287]
加入微信群，一起讨论快速解决问题。我已经实现输入、输出、目标设定都搞成中文了。
Join the WeChat group to discuss and solve problems quickly. I have realized that the input, output, and goal setting are all in Chinese.

![Chinese](https://user-images.githubusercontent.com/7324402/232651490-0e61a908-a4fd-4418-9eb4-d3cbb6ee7cad.png)

![581b3318abd26f569fd2a540b7980e0](https://user-images.githubusercontent.com/7324402/232651578-306c41c4-65bf-4f2a-b478-c040cbf5493b.jpg)

![a68cc98ede02992e9d6af214646e6ce](https://user-images.githubusercontent.com/7324402/232651589-f5542bab-b5ad-4991-a914-4aa9b375419c.jpg)

**Comment by Jun10ng** [comment]
下次合并窗口PR7，master分支就支持多语言输入输出了，我提了两个PR已经在路上了

**Comment by laixiao** [comment]
> 下次合并窗口[PR7](https://github.com/Significant-Gravitas/Auto-GPT/issues/2256)，master分支就支持多语言输入输出了，我提了两个PR已经在路上了

厉害，可以分享下怎么使用吗？

**Comment by Jun10ng** [comment]
现在想使用的话，需要把这两个PR先合到自己的本地分支，然后把两个环境变量改成zh-CN就行了。
https://github.com/Significant-Gravitas/Auto-GPT/pull/1880
https://github.com/Significant-Gravitas/Auto-GPT/pull/1781

**Comment by Pwuts** [comment]
Closing as non-actionable

**Comment by nponeccop** [comment]
Well, WeChat is a specific Chinese communication platform. They are restricted so this is perfectly valid. And there are no Chinese discord channels. So I vote for reopening.

**Comment by nponeccop** [comment]
有人可以解释一下这是不是一个随机的微信频道吗？它背后是否有一个社区？微信对中国人来说重要吗？它有什么优势吗？

**Comment by laixiao** [comment]
> 有人可以解释一下这是不是一个随机的微信频道吗？它背后是否有一个社区？微信对中国人来说重要吗？它有什么优势吗？

首先，非常感谢你打开了此贴。

另外几乎每一个能上网的中国人都在用微信，除了基本的聊天外，它还包含了各种功能的小程序和公众号，类似一个超级App。微信有很多不同类型社群，我们在上面创建群聊来讨论各种问题。我创建的群聊就是为了解决Auto-GPT使用过程中遇到的各种问题以及推进项目的发展。

**Comment by laixiao** [comment]
> Well, WeChat is a specific Chinese communication platform. They are restricted so this is perfectly valid. And there are no Chinese discord channels. So I vote for reopening.

是的，在我们国家是不允许访问国外的聊天软件、网站和论坛的，这是违法行为。所以我们都是使用微信进行沟通交流。

**Comment by Leven1113** [comment]
你好，我有个问题，就是我在用的时候它总会报Timeout error，
`openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14d65c9942b0>: Failed to establish a new connection: [Errno 110] Connection timed out'))`
我用的是免费的5美元额度，我不知道是对中国这边有限制，还是我需要用信用卡来绑定一下付款方式才可以，它在thinking之后一直会报这个错。

**Comment by kinance** [comment]
My understanding is that there is 2 threads in this issue: 1. WeChat is authorized social messaging app in mainland China. The QR code is shared above to invite people in mainland China. 2. There is an ask to enhance auto-gpt to work in and understand different language, e.g. chinese.

**Comment by kinance** [comment]
Duplicates #1563

**Comment by kinance** [comment]
Closing this as it's tracked by #1563. Please reopen if mistaken.
