### ISSUE TITLE
What is the problem with obtaining information from several web pages that have been repeating?

### ISSUE THREAD

**Issue by string-new** [Significant-Gravitas/Auto-GPT#2289]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [ ] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Pwuts** [comment]
Please provide more information and reopen. The issue form is there for a reason.
