### ISSUE TITLE
Instruct AI to use relative paths when restricted to workspace

### ISSUE THREAD

**Issue by FakeSnake618** [Significant-Gravitas/Auto-GPT#2290]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [X] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

PLAN:
-  Clone a repository with a basic web3 website code
-  Modify the code to add the functionality to upload and download files
-  Test the website locally
-  Improve the code based on test results
-  Write tests for the code
-  Execute the tests to ensure the code works as expected
-  Deploy the website
CRITICISM:  I need to ensure that the repository I clone is reliable and has a license that allows me to use the code for my project.
NEXT ACTION:  COMMAND = clone_repository ARGUMENTS = {'repository_url': 'https://github.com/ethereum/dapp-bin', 'clone_path': '/home/user/web3_website'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-=
SYSTEM:  Command clone_repository returned: Error: Attempted to access path 'D:\home\user\web3_website' outside of working directory 'D:\auto\Auto-GPT\auto_gpt_workspace'.
 THOUGHTS:  I need to create the directory where I will clone the repository. I will use the 'do_nothing' command to create the directory manually.

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by moltra** [comment]
I think that this is a valid issue, Auto-GPT is trying to create a folder outside of the sandboxed workspace.  I am getting the same error.  It is trying to clone to a folder outside the workspace.

`THOUGHTS:  I suggest we start by cloning the Power BI visuals repository to get started with developing custom visuals using TypeScript.

REASONING:  Cloning the repository will give us access to the necessary files and code to get started with developing custom visuals using TypeScript.

PLAN: 
-  Clone the Power BI visuals repository

CRITICISM:  I need to ensure that the repository is cloned successfully and that we have access to all the necessary files.

NEXT ACTION:  COMMAND = clone_repository ARGUMENTS = {'repository_url': 'https://github.com/microsoft/powerbi-visuals.git', 'clone_path': '/home/user/powerbi-visuals'}

Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
SYSTEM:  Command clone_repository returned: Error: Attempted to access path '/home/user/powerbi-visuals' outside of working directory '/home/appuser/auto_gpt_workspace'.
`
it should be trying to create the Repo in "/home/appuser/autogpt/powerbi_visuals"

**Comment by richstokes** [comment]
Is there a way to tell AutoGPT to use a specific directory for any local files it needs?

**Comment by revoluter** [comment]
Try this as an input:
try to use relative paths instead of absolute paths

**Comment by lmflorentino** [comment]
@revoluter 

![Image](https://user-images.githubusercontent.com/103535748/234881027-2d867a7d-053a-4229-a7c2-e4dcf92ca4db.png)

wrong.

**Comment by psvensson** [comment]
It is still a problem in master that it always looks for files (read or write) inside /app/autogpt/auto_gpt_workspace when the workspace is actually mounted at /app/auto_gpt_workspace.

Is there any developer who runs docker and tries local file access? Try it. Just see how it works

**Comment by lmflorentino** [comment]
I tried to run docker but failed too. This project smells very bad.

**Comment by Pwuts** [comment]
Is this still an issue?
