### ISSUE TITLE
When cloning the project, autogpt wrote to the wrong directory, not in auto_gpt_workspace, but in /.

### ISSUE THREAD

**Issue by maxadc** [Significant-Gravitas/Auto-GPT#2294]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [X] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

System environment: win10 + conda

### Current behavior 😯

Task objective: Git clone the autogpt project locally. The auto operation is successful, but the written directory is [disk]:\home[robot name]\Auto-GPT.
This is obviously a bug and can also cause security risks.

### Expected behavior 🤔

Should clone in the auto_gpt_workspace directory.

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Pwuts** [comment]
See https://github.com/Significant-Gravitas/Auto-GPT/issues/2018#issuecomment-1511827654
