### ISSUE TITLE
怎么安装openai库？how to install openai in china mainland?

### ISSUE THREAD

**Issue by Meoooww** [Significant-Gravitas/Auto-GPT#2296]
problem fixed
https://blog.csdn.net/qq_41413211/article/details/130216828?csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22130216828%22%2C%22source%22%3A%22qq_41413211%22%7D

**Comment by Pwuts** [comment]
Apparently it is fixed

> problem fixed
