### ISSUE TITLE
No module named 'openai'

### ISSUE THREAD

**Issue by xasaqu** [Significant-Gravitas/Auto-GPT#2297]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [ ] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

when I run python -m autogpt, it show me No module named 'openai'
![image](https://user-images.githubusercontent.com/84566024/232660633-de2bd4ff-32d8-4323-a927-582091e0dc30.png)

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by jpcapone** [comment]
I had this same error and i found that running `pip install -r requirements.txt`
fixed it for me.
