### ISSUE TITLE
write_to_file arguments are printed on a single line, which is hard to read

### ISSUE THREAD

**Issue by feffy380** [Significant-Gravitas/Auto-GPT#2302]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

When the current COMMAND is write_to_file (and possibly others), large multiline arguments should be printed as multiple lines for readability.

### Examples 🌈

Current behavior:
```
NEXT ACTION:  COMMAND = write_to_file ARGUMENTS = {'file': 'test.txt', 'text': 'Hello\nWorld'}
```

Expected behavior (or something similar):
```
NEXT ACTION:  COMMAND = write_to_file
ARGUMENTS = {'file': 'test.txt', 'text':
  Hello
  World
}
```

### Motivation 🔦

Currently, the arguments for NEXT ACTION are a simple json dump, which combines all the lines into a single long string.
I'd like to be able to review what write_to_file is doing, which is difficult when the text isn't formatted.

**Comment by ashuk2000** [comment]
https://github.com/Significant-Gravitas/Auto-GPT/pull/2421

**Comment by ntindle** [comment]
Fixed by #2421

**Comment by z-x-x136** [comment]
> [由#2421](https://github.com/Significant-Gravitas/Auto-GPT/pull/2421)修复[](https://github.com/Significant-Gravitas/Auto-GPT/pull/2421)

Can you print multiple lines by changing the code to f"ARGUMENTS = {Fore.CYAN} {arguments} {Style.RESET_ALL}"

**Comment by z-x-x136** [comment]
> #2421

Can you print multiple lines by changing the code to f"ARGUMENTS = {Fore.CYAN} {arguments} {Style.RESET_ALL}"

**Comment by ashuk2000** [comment]
> > #2421
> 
> Can you print multiple lines by changing the code to f"ARGUMENTS = {Fore.CYAN} {arguments} {Style.RESET_ALL}"

I think it can be done but the code won't be pretty. The problem is ,when python sees \n strings in a dictionary it replaces the new line \n with a literal \ and n in the f string. Maybe some kinda complex re split might do the trick.
