### ISSUE TITLE
Installed but not running

### ISSUE THREAD

**Issue by aditya2922** [Significant-Gravitas/Auto-GPT#2303]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [ ] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

I have installed and tested both master and the stable version. then i have added my openai api in quotes , actually copy pasted from one of my working project. after all when I give cmd _python -m autogpt_ then it shows no open ai api please add one although i  have added and rechecked it several times.

**proper statement was this in red colour**

Warning: The file 'auto-gpt.json' does not exist. Local memory would not be saved to a file.
Please set your OpenAI API key in .env or as an environment variable.
You can get your key from https://platform.openai.com/account/api-keys

### Current behavior 😯

instead of running the tool it is keep on saying that open ai api is missing 

### Expected behavior 🤔

it should start the system to run

### Your prompt 📝

```yaml
# Paste your prompt here
```
root@pop-os:/home/adiuuu/Desktop/Projects/Auto-GPT# python -m autogpt
Warning: The file 'auto-gpt.json' does not exist. Local memory would not be saved to a file.
Please set your OpenAI API key in .env or as an environment variable.
You can get your key from https://platform.openai.com/account/api-keys
root@pop-os:/home/adiuuu/Desktop/Projects/Auto-GPT#

**Comment by zhangzimingmmz** [comment]
how did you resolve it?
