### ISSUE TITLE
The problem handles the situation where it goes into an infinite loop, repeatedly visiting the same website

### ISSUE THREAD

**Issue by gfwfg** [Significant-Gravitas/Auto-GPT#2307]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [X] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

The problem handles the situation where it goes into an infinite loop, repeatedly visiting the same website

### Current behavior 😯

The problem handles the situation where it goes into an infinite loop, repeatedly visiting the same website

### Expected behavior 🤔

it does not repeatedly visiting same websites

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Pwuts** [comment]
Please add your log

**Comment by gfwfg** [comment]
My mistake
