### ISSUE TITLE
Speed up by using  requests or pyppeteer to get html code

### ISSUE THREAD

**Issue by efwfe** [Significant-Gravitas/Auto-GPT#2314]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

open and close browser is slow and much cost. Using `requests`,`httpx`maybe helpful. Or keep the browser alive not close every query.

### Examples 🌈

import requests
x = requests.get('https://w3schools.com/python/demopage.htm')
print(x.text)

### Motivation 🔦

make it better

**Comment by ntindle** [comment]
Is this 
`autogpt/commands/web_requests.py`
what you seek?
