### ISSUE TITLE
Can't write to file error

### ISSUE THREAD

**Issue by karingijs2727** [Significant-Gravitas/Auto-GPT#2334]
I was using autogpt for a while and everything was fine i didn't had the error below but after a while this error apeard why?
SYSTEM:  Command write_to_file returned: Error: 'WindowsPath' object has no attribute 'is_relative_to'

**Comment by userbox020** [comment]
same problem, im using python 3.8

**Comment by karingijs2727** [comment]
I was using python 3.8 this was the problem i have change it to 3.10 thansk!
