### ISSUE TITLE
when I start autogpt，it seems stuck in while loop and nothing print out in nearly 1 hour

### ISSUE THREAD

**Issue by zky001** [Significant-Gravitas/Auto-GPT#2341]
![image](https://user-images.githubusercontent.com/9131265/232715803-94f0754c-31d5-4fb1-acc9-e17437c439fe.png)

**Comment by k-boikov** [comment]
Please follow the Bug report template and provide prompt. Seems like your prompt didn't have well defined goals.

**Comment by cryptidv** [comment]
Closing this. As @k-boikov said: please submit issues with the correct template and try to explain your issues in more detail, include prompts, expected behaviors, etc.
