### ISSUE TITLE
Selenium is missing "darwin" (macos platform) on chrome options check

### ISSUE THREAD

**Issue by Wladastic** [Significant-Gravitas/Auto-GPT#2358]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [X] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by cryptidv** [comment]
We have seen no issues with Chrome on MacOS. The Linux checks are there to provide some fixes Linux users were having on Linux. Please see:
* #2096

If there are any issues you are experiencing with Chrome on MacOS, please open a separate issue with more detailed information. Cheers!
