### ISSUE TITLE
Crash on connection failure

### ISSUE THREAD

**Issue by SpaceTTAngel** [Significant-Gravitas/Auto-GPT#2363]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [X] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

While auto-gpt is running , with a task ongoing : 
NEXT ACTION:  COMMAND = browse_website ARGUMENTS = {.....

I had for a moment a internet connection problem (maybe 1 minute without internet); I observed the following log:

    raise error.APIConnectionError(openai.error.APIConnectionError: Error communicating with OpenAI: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

I expected that auto-gpt continued to run also if for a moment internet connection was not available

### Current behavior 😯

Auto-gpt crashes during the task ongoing : 

NEXT ACTION:  COMMAND = browse_website ARGUMENTS = {.....

with the following log:

    raise error.APIConnectionError(openai.error.APIConnectionError: Error communicating with OpenAI: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

if internet connection is not available

### Expected behavior 🤔

Auto-gpt should not crash if internet connection is not available during website searching / browsing

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by ntindle** [comment]
#348

**Comment by Pwuts** [comment]
It would probably be good to implement some kind of back-off for this.

**Comment by ntindle** [comment]
#214 would probably cover that for the most part right?
