### ISSUE TITLE
CI autolabeling is broken by introduction of new events

### ISSUE THREAD

**Issue by nponeccop** [Significant-Gravitas/Auto-GPT#2370]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [ ] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

https://github.com/Significant-Gravitas/Auto-GPT/actions/runs/4723149859/jobs/8378707214?pr=1569

It crashes when run in the merging forks (as opposed to our main repo). We introduced this this morning (see the changes in .github) but now it crashes.

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Pwuts** [comment]
It failed a few times because the permissions on the workflow weren't sorted out yet. Last failure was 16 hours ago. Closing as resolved
