### ISSUE TITLE
Add flag to skip confirmation in continuous mode

### ISSUE THREAD

**Issue by LanceLake** [Significant-Gravitas/Auto-GPT#2380]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

I have a batch file that reloads on crash automatically on continuous looping, but it's held up by the continue option. I'd like to see a parameter that is basically, "-AlwaysContinue" that will skip the continue question and just start it thinking for overnight use.

### Motivation 🔦

I have something that I want to be able to work overnight by itself. When a bug crashes it, I wake up to "Continue(y/n)?" I'd like it to not ask and just go back to computing.

**Comment by cryptidv** [comment]
There is already such a flag. Run autogpt with `-y` to skip the question.

So you could run `python -m autogpt start -yc` to run in continuous mode while skipping the initial question. Let me know if that worked out for you 😄

**Comment by LanceLake** [comment]
I didn't know that. Thank you. :)
