### ISSUE TITLE
start_agent to start with the same memory settings

### ISSUE THREAD

**Issue by davideoliveri** [Significant-Gravitas/Auto-GPT#2384]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

I am running an agent using Redis and I noticed that the agents launched by the main one are using a local json file instead of the Redis instance I associated with the first agent. 
Would it make sense to feed the same parameters to the sub agents?

**Comment by Pwuts** [comment]
The agents are separate instances and probably shouldn't share memory with the main instance. Interesting idea tho. Could be an option?

**Comment by ntindle** [comment]
I can see this going both ways. Too much context could cause problems. It would be interesting if the main instance could decide when it spawns the agent if it gets context
