### ISSUE TITLE
Give the avibility to create images on midjourney

### ISSUE THREAD

**Issue by horazius** [Significant-Gravitas/Auto-GPT#2403]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Give the avibility to create images on midjourney. So the best approach would be to create a image ChatGPT has described before. So we should give ChatGPT always a short intruduction how to create images with MidJourney. Then when the four pictures are created we upscale everyone of them and use the /describe prompt of midjournes. The description how fit's the best to our use case scenario we use. 

### Examples 🌈

I guess it's clear, without examples.

### Motivation 🔦

Motivation is easy: We could post pictures on Twitter, we could post on instagram we could do so much more.

**Comment by cryptidv** [comment]
I don't think it's possible to do this directly. This however would make for a great plugin. Auto-GPT even iteratively improving the prompt?

**Comment by horazius** [comment]
Yes, but with the describe you have a addional itteration and also a security that you get what you want.

**Comment by rocks6** [comment]
does midjourney expose an API? if not can we use a discord connector?

**Comment by ahmedlone127** [comment]
@rocks6  can you expand on what a discord connector is?

**Comment by rocks6** [comment]
If we aren't able to interact with mid journey directly via API, we could try using discord programmatically to interact with it on the main server or by dm

**Comment by GerardCB** [comment]
I tried developing a Discord bot to interact with the Midjourney Bot, but it is *not possible*, at least following the terms and conditions of Discord. Let me explain: a typical bot can't interact with the Midjourney bot, as they have specifically not allowed this. However, there are some user-bots (idk what they are called) that Discord interprets as standard users and thus are allowed to interact with Midjourney. Sadly, although technically possible, it is illegal, according to Discord.

**Comment by ntindle** [comment]
Not possible.... but if you're so inclined
This seems great for a potential plugin. Open an issue here: [Auto-GPT-Plugins](https://github.com/Significant-Gravitas/Auto-GPT-Plugins)
