### ISSUE TITLE
Error: name 'WORKING_DIRECTORY' is not defined

### ISSUE THREAD

**Issue by guppyO** [Significant-Gravitas/Auto-GPT#2414]
### 

- [x] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

Hi, I'm simply running the default program with no changes to code but I always end up stuck in a loop where the program is trying to do the following command in a loop, I have checked and the requests package is already installed. 
Any help would be great. 
 
 NEXT ACTION:  COMMAND = execute_shell_popen ARGUMENTS = {'command_line': 'pip install requests', 'working_directory': '/path/to/WORKING_DIRECTORY'}
SYSTEM:  Command execute_shell_popen returned: Error: name 'WORKING_DIRECTORY' is not defined
 THOUGHTS:  sample command to install requests package with pip
REASONING:  Ensuring that the correct working directory for process execution is set before running the pip install command will help to avoid errors such as this.
PLAN:
-  Import the OS module.
-  Define the `WORKING_DIRECTORY` variable with the correct filepath of the directory you want to install 'requests' package to.
-  Use the execute_shell_popen command, including the pip command in the command line and working directory using the previously defined `WORKING_DIRECTORY` variable.
-  Ensure after installation running 'pip list' command to confirm the successful installation of the 'requests' package.
CRITICISM:  Once you have the successful installation of the `requests` package, I suggest you test it in a simple project or within a virtual environment.

NEXT ACTION:  COMMAND = execute_shell_popen ARGUMENTS = {'command_line': 'pip install requests', 'working_directory': '/path/to/WORKING_DIRECTORY'}
SYSTEM:  Command execute_shell_popen returned: Error: name 'WORKING_DIRECTORY' is not defined
 THOUGHTS:  An example command to install the 'requests' python package using pip
REASONING:  We must specify the correct working directory and pip installation command to install the 'requests' package correctly. Defining the `WORKING_DIRECTORY` variable before execution is Ensuring that the correct working directory for process execution is set.
PLAN:
-  Import the OS module.
-  Define the `WORKING_DIRECTORY` variable that matches the filepath of the directory you intend to work on.
-  Run your pip installation command within the execute_shell_popen command with the appropriate working directory.
-  After successful installation, verify it by executing 'pip list' command to check if required packages have been installed.
CRITICISM:  I suggest you find a simple project to work on and test the installation of the requests package with a virtual environment to avoid affecting other projects or the operating system.

NEXT ACTION:  COMMAND = execute_shell_popen ARGUMENTS = {'command_line': 'pip install requests', 'working_directory': '<path/to/WORKING_DIRECTORY>'}
SYSTEM:  Command execute_shell_popen returned: Error: name 'WORKING_DIRECTORY' is not defined
 THOUGHTS:  Steps to define WORKING_DIRECTORY variable and install the 'requests' python package using pip.
REASONING:  We want to avoid hard-coding the directory in our program since we may have to work on different directories in the future. Therefore, by defining and using the `WORKING_DIRECTORY` variable from a file, we ensure the potential for working with multiple directories is available.
PLAN:
-  Use `write_to_file` to write the filepath of your desired working directory to file `working_directory.txt`.
-  Use `read_file` command to read the value from `working_directory.txt` and assign it to `WORKING_DIRECTORY` variable.
-  Use `execute_shell_popen` command to run the pip installation command with the correct working directory.
CRITICISM:  I suggest you find a simple project to work on and test the installation of the requests package with a virtual environment to avoid affecting other projects or the operating system.

NEXT ACTION:  COMMAND = write_to_file ARGUMENTS = {'file': 'working_directory.txt', 'text': '<path/to/directory>'}
SYSTEM:  Command write_to_file returned: File written to successfully.
 THOUGHTS:  Read the directory path from file, save it to `WORKING_DIRECTORY` variable, and install 'requests' using `execute_shell_popen` command.
REASONING:  Hardcoding the directory path is not recommended in our program. By saving it to a file with a specific name, we can reuse it efficiently with the `read_file` command. We'll then pass the value stored in the `working_directory.txt` file to the `execute_shell_popen` command.
PLAN:
-  Use `read_file` command to read the value of the directory path from file `working_directory.txt`. Assign the value to the `WORKING_DIRECTORY`
 variable.
-  Use `execute_shell_popen` command, including the `pip install requests` command in the command line and the directory path in the working directory argument
CRITICISM:  Don't forget to test the pip installation, verifying that the package has been successfully installed.

NEXT ACTION:  COMMAND = read_file ARGUMENTS = {'file': 'working_directory.txt'}
SYSTEM:  Command read_file returned: <path/to/directory>
The JSON object is invalid.
 THOUGHTS:  None
REASONING:  None
CRITICISM:  None
NEXT ACTION:  COMMAND = execute_shell_popen ARGUMENTS = {'command_line': 'pip install requests', 'working_directory': '<path/to/directory>'}
SYSTEM:  Command execute_shell_popen returned: Error: name 'WORKING_DIRECTORY' is not defined
 THOUGHTS:  sample command to install requests package with pip
REASONING:  Ensuring that the correct working directory for process execution is set before running the pip install command will help to avoid errors such as this.
PLAN:
-  Import the OS module.
-  Define the `WORKING_DIRECTORY` variable with the correct filepath of the directory you want to install 'requests' package to.
-  Use the execute_shell_popen command, including the pip command in the command line and working directory using the previously defined `WORKING_DIRECTORY` variable.
-  Ensure after installation running 'pip list' command to confirm the successful installation of the 'requests' package.
CRITICISM:  Once you have the successful installation of the `requests` package, I suggest you test it in a simple project or within a virtual environment.

### Current behavior 😯

NEXT ACTION:  COMMAND = execute_shell_popen ARGUMENTS = {'command_line': 'pip install requests', 'working_directory': '/'}
SYSTEM:  Command execute_shell_popen returned: Error: name 'WORKING_DIRECTORY' is not defined

stuck in loop.

### Expected behavior 🤔

I assume it should recognise "requests is already installed"

### Your prompt 📝

Default Prompt.

### Your Logs 📒

Provided above

**Comment by cryptidv** [comment]
Should be Fixed with #2318
