### ISSUE TITLE
Odd behavior with reading multiple text files

### ISSUE THREAD

**Issue by davidlevy247** [Significant-Gravitas/Auto-GPT#2420]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

Use a goal similar to this:
> Included in the default workspace directory is 1 set of 15 files split from 1 report and one additional file that will help explain how to create a documentary pitch. However, when you read the files you can not declare a directory or the read process will error out, you need to simple call for the file to read it. Remember, you are in a Python environment. The files to analyze are pitchdeck2.txt and the set of 15 files split from one report are pitchdeck1_1.txt, pitchdeck1_2.txt, pitchdeck1_3.txt, pitchdeck1_4.txt, pitchdeck1_5.txt, pitchdeck1_6.txt, pitchdeck1_7.txt, pitchdeck1_8.txt, pitchdeck1_9.txt, pitchdeck1_10.txt, pitchdeck1_11.txt, pitchdeck1_12.txt, pitchdeck1_13.txt, pitchdeck1_14.txt, pitchdeck1_15.txt. You need to process the 15 split files individually and remember that those 15 files are from one report. The formatting for the two files is messy, so disregard any formatting issues within the text and thoroughly analyze all files to discover insight and guidelines for developing an effective pitch deck. To be clear, analyze pitchdeck2.txt first. Then analyze each of the 15 files individually in order of their filenames. Make sure to not analyze over the token limit of your ChatGPT model. It would be good to check each file's character limit before you study them to avoid a software crash.

### Current behavior 😯

Some odd behavior when it comes to reading multiple local files. I didn't see an issue exactly like this other than when a token limit error happens... which getting around that is the point of splitting up a text file into multiple text files. Because of the token limit, files with too much content must be split into chunks for processing. 

But the program seems to forget the environment it is in for the correct argument to pass to the command and the file order it should read and it also fails to process and extract relevant information from each file.

### Expected behavior 🤔

Keep track of files left to read, use correct arguments to read each file in order, process data as expected.and

**Comment by ntindle** [comment]
@Pwuts add this to your batching for splitting a command into multiple parts

**Comment by Pwuts** [comment]
This issue should be fixed when `read_file` or `ingest_file` supports chunking so she AI doesn't have to read 15 separate files. Please follow this issue for that: #2801

If the AI forgets to read all the files halfway through, or doesn't use the provided commands correctly, that is a bigger issue that will be addressed elsewhere, e.g. by implementing task management or improving benchmarking and taking measures to improve the AI's efficacy based on those benchmarks. 

Related items:
* #495
* #2987
* @ntindle any others?
