### ISSUE TITLE
Explicitly add GPT capabilities like summarization as commands to compensate for lack of self-awareness.

### ISSUE THREAD

**Issue by zachary-kaelan** [Significant-Gravitas/Auto-GPT#2422]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

I've asked ChatGPT for command suggestions a few times in separate chats and it keeps suggesting commands for things that GPT can just do on its own. 

Examples:

```
("Translate Text", "translate_text", {"text": "<text>", "source_lang": "<source_lang>", "target_lang": "<target_lang>"})
("Summarize Text", "summarize_text", {"text": "<text>", "summary_length": "<summary_length>"})
("Sentiment Analysis", "sentiment_analysis", {"text": "<text>"})
("Generate Text", "generate_text", {"prompt": "<prompt>", "length": "<length>"})
("Conversational Context", "conversational_context", {"history": "<list_of_past_messages>", "message": "<message>"})
```

GPT can do all of these things by itself, so what is the point? The point is that GPT isn't self-aware, and as stated in #2054, it sometimes stupidly looks for third-party tools to do things it is fully capable of doing itself.

Providing a full list of commands for GPT capabilities will hog a lot of memory context, so they could all just go into a command like this:

```
(
  "Call Text API",
  "call_text_api",
  {"api_id": "<api_id>", "text": "<text>", "args": "<args>"}
)
```

Then add a list of "API" names to a list in this command, the resources list, or a separate list. When a text API is called, the id, text, and arguments can just be tossed into one of those [bogus AI functions](https://github.com/Torantulino/AI-Functions) like those used by `evaluate_code`, `improve_code`, and `write_tests`.

### Examples 🌈

I could see an agent using commands like these often for human-facing stuff like social media management, messaging, or logging. 

### Motivation 🔦

Explicitly stating these capabilities helps ensure certain simple tasks aren't overcomplicated by the agent. The abstraction can also allow for us to pick and choose third-party tools if we actually want to make use of any. 

It might also be interesting to do something like modify `generate_text` to take user input then "generate" really stupid text to see if the agent has proper standards for the use case and re-generates.

**Comment by ntindle** [comment]
This seems great for a potential plugin. Open an issue here: [Auto-GPT-Plugins](https://github.com/Significant-Gravitas/Auto-GPT-Plugins)
