### ISSUE TITLE
Bug: sometimes return error `Command evaluate_code returned: Error: The model: gpt-4 does not exist` when execute with --gpt3only prefix

### ISSUE THREAD

**Issue by saccohuo** [Significant-Gravitas/Auto-GPT#243]
Bug: sometimes return error `Command evaluate_code returned: Error: The model: gpt-4 does not exist` when execute with --gpt3only prefix

**Comment by Mars-e** [comment]
https://github.com/Torantulino/Auto-GPT/issues/187#issuecomment-1496599571

Thanks to this kind reference, please edit the     .env    file accordingly.

This is also my walkaround to use only gpt3, and works.

#SMART_LLM_MODEL="gpt-4"
SMART_LLM_MODEL="gpt-3.5-turbo"

I hope this helps. Please give us feedback!

**Comment by bensig** [comment]
I have edited my SMART_LLM_MODEL in .env and it is not working... still get the same error.

**Comment by rajeshalda** [comment]
same error ..

**Comment by Pwuts** [comment]
Duplicate of #168
