### ISSUE TITLE
hangs on execution shell command which requires user input

### ISSUE THREAD

**Issue by iva-nova-e-katerina** [Significant-Gravitas/Auto-GPT#2438]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Ubuntu 22

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

sudo python3 -m autogpt  --continuous --gpt3only
y

### Current behavior 😯

root@user-VirtualBox:/home/user/Auto-GPT# git rev-parse HEAD
5752a466a243548d84f67a1679dd6b0cbc2a7165

it hangs on:

```
NEXT ACTION:  COMMAND = execute_shell ARGUMENTS = {'command_line': 'git clone -v -- https://github.com/sai-teja-ponugoti/Auto-GPT.git ~/Auto-GPT'}
                                                                                                                                                       Executing command 'git clone -v -- https://github.com/sai-teja-ponugoti/Auto-GPT.git ~/Auto-GPT' in working directory '/home/user/Auto-GPT/auto_gpt_workspace'

                                                                                                                                           Username for 'https://github.com': 
```
Sometimes ignoring my input, sometimes not ignoring

### Expected behavior 🤔

Continues work without user's input, skip such shell commands 

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by ntindle** [comment]
You can set GitHub configs in the `.env` to avoid this specific issue with GitHub.
