### ISSUE TITLE
Having issues running python -m autogpt

### ISSUE THREAD

**Issue by davidscode1414** [Significant-Gravitas/Auto-GPT#2439]
This is the error message I receive when running prompt
Warning: The file 'auto-gpt.json' does not exist. Local memory would not be saved to a file.

**Comment by jtgsystems** [comment]
I get that too, and without that, it wouldn't work correctly. 

we need a script to allow permissions for all folders and apply whatever permissions the system maybe lack so it will work on anything.

**Comment by Pwuts** [comment]
Closing as duplicate of #1073

**Comment by PhilosopherChild** [comment]
This is different from #1073 though. This involves the issue with .json but it also has an issue with python -m autogpt being returned instead of continuous dialogue
