### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by cvarrichio** [Significant-Gravitas/Auto-GPT#244]
Shouldn't verbose logging be enabled by default, especially in continuous mode?  This only required a couple of lines of code in my local version.

**Comment by slavakurilyak** [comment]
@cvarrichio Do you mind issuing a pull request?

**Comment by jdonkers** [comment]
For quick logging, I added the following to llm_utils.py (before the return statement)

with open("log.txt", "a", encoding="utf-8") as f:
        f.write(f"Request: {messages}\n\n")
        f.write(f"Response: " + response.choices[0].message["content"] + "\n\n")

**Comment by cvarrichio** [comment]
Suggest doing something more like:

import logging
import datetime
now = datetime.datetime.now()
log_file_name = 'autogpt_{}.log'.format(now.strftime('%Y%m%d_%H%M%S'))
logging.basicConfig(filename=log_file_name, level=logging.DEBUG)

Probably in outputs/logs

I can do it myself, but I'm not sure how conflicts are dealt with in large public projects.

**Comment by dschonholtz** [comment]
Yes, please use the python standard logging library rather than writing directly to a file: https://docs.python.org/3/library/logging.html

**Comment by cvarrichio** [comment]
Alright, I understand the pull request process, I will submit the changes.
