### ISSUE TITLE
having the bot know it has access to the internet along with access and permissions to write to files and folders on the desktop

### ISSUE THREAD

**Issue by jtgsystems** [Significant-Gravitas/Auto-GPT#2447]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

having the bot know it has access to the internet along with access and permissions to write to files and folders on the desktop. right now it doesn't think it can do that, it needs to be able to do that.

**Comment by ntindle** [comment]
It's aware, adjust your prompt. Also, I strongly urge you to not let it read and write random files.

**Comment by jtgsystems** [comment]
Adjust to what, and also do u need pinecone or something for this to work
correctly also using 3.5 model ? Should I use 4

**Comment by ntindle** [comment]
If you have gpt-4, I would encourage you to try it at least. I'd need to know your prompt to help you adjust it. Please attach it

**Comment by ntindle** [comment]
Needs more info
