### ISSUE TITLE
AutoGPT has no clue about working directory

### ISSUE THREAD

**Issue by iva-nova-e-katerina** [Significant-Gravitas/Auto-GPT#2449]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

sudo python3 -m autogpt  --continuous --gpt3only
y

### Current behavior 😯

git rev-parse HEAD
89539d0cf169e6deb3bb475ab771e970462a5687

```
NEXT ACTION:  COMMAND = execute_shell ARGUMENTS = {'command_line': 'cd ~/twitterscraper && pip install -r requirements.txt'}
Executing command 'cd ~/twitterscraper && pip install -r requirements.txt' in working directory '/home/user/Auto-GPT/auto_gpt_workspace'
SYSTEM:  Command execute_shell returned: STDOUT: b'' STDERR: b"/bin/sh: 1: cd: can't cd to /root/twitterscraper\n"

```

### Expected behavior 🤔

AutoGPT must know absolute path to working directory once and forever

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by claytondukes** [comment]
Just a guess, maybe true using `${HOME}` instead of `~`
Not sure what your prompt is.

**Comment by claytondukes** [comment]
Oh, it may also be because it's outside of the working directory (`auto_gpt_workspace`)

**Comment by ntindle** [comment]
Sometimes it executes something unexpected or doesn’t do what you want.  Check out the #prompt-engineering channel in discord to get a better fit prompt
