### ISSUE TITLE
Command memory_overwrite returned: Unknown command memory_overwrite

### ISSUE THREAD

**Issue by Braingearceo** [Significant-Gravitas/Auto-GPT#245]
Hey everyone!
Just having fun with Auto-GPT, after few Thought process, I got it stuck in a loop of trying to use "memory_overwrite" command.

Here is the full output : 
←[32mWelcome to Auto-GPT!  ←[0mEnter the name of your AI and its role below. Entering nothing will load defaults.
←[32mName your AI:  ←[0mFor example, 'Entrepreneur-GPT'
AI Name: ResearcherGPT
←[94mResearcherGPT here! ←[0mI am at your service.
←[32mDescribe your AI's role:  ←[0mFor example, 'an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.'
ResearcherGPT is: An AI designed to autonomously create resume papers in the field of Cognitive Science.
←[32mEnter up to 5 goals for your AI:  ←[0mFor example: Increase net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously'
Enter nothing to load defaults, enter nothing when finished.
←[94mGoal←[0m 1: Search most relevant articles
←[94mGoal←[0m 2: Resume each of the articles you found.
←[94mGoal←[0m 3: Propose continuation for each articles.
←[94mGoal←[0m 4:
←[33mRESEARCHERGPT THOUGHTS: ←[0mListing GPT agents!
←[33mREASONING: ←[0mI want to check if there are any GPT agents running which can perform some helpful tasks for me.
←[33mPLAN: ←[0m
←[32m-  ←[0mIf there's any useful agent, I can delegate the task to it
←[33mCRITICISM: ←[0mNone
←[36mNEXT ACTION:  ←[0mCOMMAND = ←[36mlist_agents←[0m ARGUMENTS = ←[36m{}←[0m
Enter 'y' to authorise command or 'n' to exit program, or enter feedback for ResearcherGPT...
←[35mInput:←[0my
←[35m-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= ←[0m
←[33mSYSTEM:  ←[0mCommand list_agents returned: []
←[33mRESEARCHERGPT THOUGHTS: ←[0mSearching for cognitive science research papers
←[33mREASONING: ←[0mI need to first gather a list of relevant research papers on cognitive science before I can create a concise and tailored list of the most relevant papers to create a strong resume from.
←[33mPLAN: ←[0m
←[32m-  ←[0mI will use Google search to get a general overview of the most popular and relevant cognitive science research papers out there in the field.
←[33mCRITICISM: ←[0mI hope I don't get too overly broad articles
←[36mNEXT ACTION:  ←[0mCOMMAND = ←[36mgoogle←[0m ARGUMENTS = ←[36m{'input': 'Cognitive Science Research Papers'}←[0m
Enter 'y' to authorise command or 'n' to exit program, or enter feedback for ResearcherGPT...
←[35mInput:←[0my
←[35m-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= ←[0m
←[33mSYSTEM:  ←[0mCommand google returned: [ { "title": "Cognitive neuroscience - Latest research and news | Nature", "href": "https://www.nature.com/subjects/cognitive-neuroscience", "body": "Cognitive neuroscience is the field of study focusing on the neural substrates of mental processes. It is at the intersection of psychology and neuroscience, but also overlaps with physiological..." }, { "title": "Trends in Cognitive Sciences | Journal - ScienceDirect", "href": "https://www.sciencedirect.com/journal/trends-in-cognitive-sciences", "body": "The journal brings together research in psychology, artificial intelligence, linguistics, philosophy, computer science and neuroscience. Trends in Cognitive Sciences provides a platform for the interaction of these disciplines and the evolution of cognitive science as an independent field of study." }, { "title": "123051 PDFs | Review articles in COGNITIVE SCIENCE - ResearchGate", "href": "https://www.researchgate.net/topic/Cognitive-Science/publications", "body": "123051 PDFs | Review articles in COGNITIVE SCIENCE Science topics: Psychology Cognitive Science Cognitive Science - Science topic Ruairi O'Reilly Dhwani Rana Derajram Benival Aakanchha..." }, { "title": "Research | Cognitive Science | Johns Hopkins University", "href": "https://cogsci.jhu.edu/research-areas/", "body": "The Department of Cognitive Science at Johns Hopkins studies the mind as a computational system, with a particular focus on language and spatial representation. Our research seeks to discover the formal structure of cognition at all levels of analysis. What functions does the cognitive system compute and why?" }, { "title": "(PDF) Research studies on human cognitive ability", "href": "https://www.researchgate.net/publication/333415208_Research_studies_on_human_cognitive_ability", "body": "This paper studies on research articles and work that highlighted various studies; surveys; and comparison on human brain research and its impact on cognitive ability for various artificial..." }, { "title": "Cognitive Science | Journal | ScienceDirect.com by Elsevier", "href": "https://www.sciencedirect.com/journal/cognitive-science", "body": "Advances in analogy research: Integration of theory and data from the cognitive, computational, and neural sciences. July-August 1997. View all special issues and article collections. ... For Authors. Track your accepted paper Journal Finder Researcher Academy Rights and permissions Journal Article Publishing Support Center. For Editors ..." }, { "title": "(PDF) Cognitive Science - ResearchGate", "href": "https://www.researchgate.net/publication/312173743_Cognitive_Science", "body": "Cognitive science is the interdisciplinary, scientific study of the mind and its processes. It examines the nature, the tasks, and the functions of cognition. Cognitive scientists study..." }, { "title": "Cognitive science research papers - University of Sussex", "href": "https://www.sussex.ac.uk/cogs/research/researchpapers", "body": "Cognitive science research papers To see a report abstract, click on its number. Most recently published reports are available for download. If you have queries concerning these or any other publications of the School of Informatics, please contact the School Office." } ]
←[33mRESEARCHERGPT THOUGHTS: ←[0mStoring the most relevant articles permanently.
←[33mREASONING: ←[0mI want to permanently store the most relevant articles I found in permanent memory, so that I can refer to them anytime and avoid using a command again to search for them. This will save time and queries to the internet.
←[33mPLAN: ←[0m
←[32m-  ←[0mI will overwrite the previous value associated with key 'relevant_articles' in permanent memory with the most relevant articles that I found in the previous command result.
←[33mCRITICISM: ←[0mNone
←[36mNEXT ACTION:  ←[0mCOMMAND = ←[36mmemory_overwrite←[0m ARGUMENTS = ←[36m{'key': 'relevant_articles', 'string': '[{"title":"Cognitive neuroscience - Latest research and news | Nature","href":"https://www.nature.com/subjects/cognitive-neuroscience","body":"Cognitive neuroscience is the field of study focusing on the neural substrates of mental processes. It is at the intersection of psychology and neuroscience, but also overlaps with physiological..."},{"title":"Trends in Cognitive Sciences | Journal - ScienceDirect","href":"https://www.sciencedirect.com/journal/trends-in-cognitive-sciences","body":"The journal brings together research in psychology, artificial intelligence, linguistics, philosophy, computer science and neuroscience. Trends in Cognitive Sciences provides a platform for the interaction of these disciplines and the evolution of cognitive science as an independent field of study."},{"title":"Research | Cognitive Science | Johns Hopkins University","href":"https://cogsci.jhu.edu/research-areas/","body":"The Department of Cognitive Science at Johns Hopkins studies the mind as a computational system, with a particular focus on language and spatial representation. Our research seeks to discover the formal structure of cognition at all levels of analysis. What functions does the cognitive system compute and why?"},{"title":"(PDF) Research studies on human cognitive ability","href":"https://www.researchgate.net/publication/333415208_Research_studies_on_human_cognitive_ability","body":"This paper studies on research articles and work that highlighted various studies; surveys; and comparison on human brain research and its impact on cognitive ability for various artificial..."}]'}←[0m
Enter 'y' to authorise command or 'n' to exit program, or enter feedback for ResearcherGPT...
←[35mInput:←[0my
←[35m-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= ←[0m
←[33mSYSTEM:  ←[0mCommand memory_overwrite returned: Unknown command memory_overwrite
←[33mRESEARCHERGPT THOUGHTS: ←[0mSaving the most relevant articles in permanent memory.
←[33mREASONING: ←[0mI want to permanently store the most relevant articles I found in permanent memory, so that I can refer to them anytime and avoid using a command again to search for them. This will save time and queries to the internet.
←[33mPLAN: ←[0m
←[32m-  ←[0mI will overwrite the previous value associated with key 'relevant_articles' in permanent memory with the most relevant articles that I found in the previous command result.
←[33mCRITICISM: ←[0mNone
←[36mNEXT ACTION:  ←[0mCOMMAND = ←[36mmemory_overwrite←[0m ARGUMENTS = ←[36m{'key': 'relevant_articles', 'string': '[{"title":"Cognitive neuroscience - Latest research and news | Nature","href":"https://www.nature.com/subjects/cognitive-neuroscience","body":"Cognitive neuroscience is the field of study focusing on the neural substrates of mental processes. It is at the intersection of psychology and neuroscience, but also overlaps with physiological..."},{"title":"Trends in Cognitive Sciences | Journal - ScienceDirect","href":"https://www.sciencedirect.com/journal/trends-in-cognitive-sciences","body":"The journal brings together research in psychology, artificial intelligence, linguistics, philosophy, computer science and neuroscience. Trends in Cognitive Sciences provides a platform for the interaction of these disciplines and the evolution of cognitive science as an independent field of study."},{"title":"Research | Cognitive Science | Johns Hopkins University","href":"https://cogsci.jhu.edu/research-areas/","body":"The Department of Cognitive Science at Johns Hopkins studies the mind as a computational system, with a particular focus on language and spatial representation. Our research seeks to discover the formal structure of cognition at all levels of analysis. What functions does the cognitive system compute and why?"},{"title":"(PDF) Research studies on human cognitive ability","href":"https://www.researchgate.net/publication/333415208_Research_studies_on_human_cognitive_ability","body":"This paper studies on research articles and work that highlighted various studies; surveys; and comparison on human brain research and its impact on cognitive ability for various artificial..."}]'}←[0m
Enter 'y' to authorise command or 'n' to exit program, or enter feedback for ResearcherGPT...
←[35mInput:←[0my
←[35m-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= ←[0m
←[33mSYSTEM:  ←[0mCommand memory_overwrite returned: Unknown command memory_overwrite
←[33mRESEARCHERGPT THOUGHTS: ←[0mSaving the most relevant articles in permanent memory.
←[33mREASONING: ←[0mI want to permanently store the most relevant articles I found in permanent memory, so that I can refer to them anytime and avoid using a command again to search for them. This will save time and queries to the internet.
←[33mPLAN: ←[0m
←[32m-  ←[0mI will add the most relevant articles that I found in the previous command result to permanent memory with key 'relevant_articles'.
←[33mCRITICISM: ←[0mNone
←[36mNEXT ACTION:  ←[0mCOMMAND = ←[36mmemory_add←[0m ARGUMENTS = ←[36m{'key': 'relevant_articles', 'string': '[{"title":"Cognitive neuroscience - Latest research and news | Nature","href":"https://www.nature.com/subjects/cognitive-neuroscience","body":"Cognitive neuroscience is the field of study focusing on the neural substrates of mental processes. It is at the intersection of psychology and neuroscience, but also overlaps with physiological..."},{"title":"Trends in Cognitive Sciences | Journal - ScienceDirect","href":"https://www.sciencedirect.com/journal/trends-in-cognitive-sciences","body":"The journal brings together research in psychology, artificial intelligence, linguistics, philosophy, computer science and neuroscience. Trends in Cognitive Sciences provides a platform for the interaction of these disciplines and the evolution of cognitive science as an independent field of study."},{"title":"Research | Cognitive Science | Johns Hopkins University","href":"https://cogsci.jhu.edu/research-areas/","body":"The Department of Cognitive Science at Johns Hopkins studies the mind as a computational system, with a particular focus on language and spatial representation. Our research seeks to discover the formal structure of cognition at all levels of analysis. What functions does the cognitive system compute and why?"},{"title":"(PDF) Research studies on human cognitive ability","href":"https://www.researchgate.net/publication/333415208_Research_studies_on_human_cognitive_ability","body":"This paper studies on research articles and work that highlighted various studies; surveys; and comparison on human brain research and its impact on cognitive ability for various artificial..."}]'}←[0m
Enter 'y' to authorise command or 'n' to exit program, or enter feedback for ResearcherGPT...
←[35mInput:←[0m

**Comment by Danny1218** [comment]
I have the same issue it can't overwrite it's memory for some reason.

**Comment by UpstateNate** [comment]
I'm having this issue as well!

**Comment by dschonholtz** [comment]
It looks like we are getting rid of memory overwrite in general in favor of a pinecone vector db.
See my PR #122

**Comment by Braingearceo** [comment]
Using vectorDB could be awesome. I understand the problem about context lenght when working with "local" memory. But it's look like I don't even get the good command. As it return unknow command memory_overwrite and the command in commands.py is named overwrite_memory...
elif command_name == "memory_ovr":
            return overwrite_memory(arguments["key"], arguments["string"]).
