### ISSUE TITLE
Allow use of `lynx` for browsing web in non-graphical systems

### ISSUE THREAD

**Issue by claytondukes** [Significant-Gravitas/Auto-GPT#2451]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Recently, selenium was added for browsing sites. Cool idea!

Sadly, I run most of my stuff on Linux servers, so no gui :(

It would be super-duper-fantastic if you guys could detect that and use `lynx` or something similar instead.

### Examples 🌈

None to give

### Motivation 🔦

To be able to run auto-gpt in non-gui environments

**Comment by Notarin** [comment]
Hi! I'm really certain that this does not require a graphical environment to work, I've tested this on a linux server, as well as inside a docker container. could you maybe update us with a log or an error?

**Comment by claytondukes** [comment]
After a `git pull` today, I see someone already provided a method for headless, the .env.template now has `HEADLESS_BROWSER=True`, so I'll close this issue.
