### ISSUE TITLE
Using new OPENAI api keys result with error - .env is being ignored 

### ISSUE THREAD

**Issue by dorialn68** [Significant-Gravitas/Auto-GPT#2452]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

you may encounter the issue if you delete you OpenAi api keys and create a new one
editing .env file results with consistent which reclaim to  use the old key which has been deleted 

### Current behavior 😯

starting the chatbot would be result with the following error even and basically ignores .env file : File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: Incorrect API key provided: sk-DEm*******************************************X. You can find your API key at https://platform.openai.com/account/api-keys. 

### Expected behavior 🤔

I would expect the support of and updated apikey with no issues , but even after deleting the autogpt folder is insist upon former api keys 

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by Holpa** [comment]
check your OS environment variables

**Comment by dorialn68** [comment]
yes using windows 11 , gpt4 , should I set my api keys elsewhere then on .env  , please advice , as I didn't find relevant reference in documentation

**Comment by dorialn68** [comment]
Resolved using the correct API environment variable command uisng set and setx :-)
