### ISSUE TITLE
shell command execution hangs AutoGPT forever

### ISSUE THREAD

**Issue by iva-nova-e-katerina** [Significant-Gravitas/Auto-GPT#2459]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

sudo python3 -m autogpt  --continuous --gpt3only
y

### Current behavior 😯

git rev-parse HEAD
89539d0cf169e6deb3bb475ab771e970462a5687

```
NEXT ACTION:  COMMAND = execute_shell ARGUMENTS = {'command_line': 'cd /home/user/Auto-GPT/auto_gpt_workspace/twitterscraper && nano elon_tweets.json'}
Executing command 'cd /home/user/Auto-GPT/auto_gpt_workspace/twitterscraper && nano elon_tweets.json' in working directory '/home/user/Auto-GPT/auto_gpt_workspace'

```
another one example
```
NEXT ACTION:  COMMAND = execute_shell ARGUMENTS = {'command_line': 'ping gitlab.com'}
Executing command 'ping gitlab.com' in working directory '/home/user/Auto-GPT/auto_gpt_workspace'

```

### Expected behavior 🤔

skip execution of broken commands. Probably execute all shell commands in "&" (Linux) detached mode 

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by 6869677a** [comment]
Similar issue, nano and com.

**Comment by Notarin** [comment]
After doing some research I've found that there doesn't really seem to be a solution for detecting if a program is blocking or non-blocking, meaning that the only method for mitigating this in a simple fashion is to set a time-out, which seems rather unfortunate. Hopefully, I'm wrong and someone smarter than me knows how to do so.

**Comment by hurrisonma** [comment]
SYSTEM:  Command execute_shell returned: Error: [Errno 2] No such file or directory: '/home/appuser/autogpt/auto_gpt_workspace'

**Comment by Notarin** [comment]
> SYSTEM: Command execute_shell returned: Error: [Errno 2] No such file or directory: '/home/appuser/autogpt/auto_gpt_workspace'

This is a different issue, please find an issue that applies or create your own.

**Comment by iva-nova-e-katerina** [comment]
> After doing some research I've found that there doesn't really seem to be a solution for detecting if a program is blocking or non-blocking, meaning that the only method for mitigating this in a simple fashion is to set a time-out, which seems rather unfortunate. Hopefully, I'm wrong and someone smarter than me knows how to do so.

how about to detach process then collect its logs and files?

**Comment by TheLegs** [comment]
Same here, for example with running `python -m http.server 8000`. The AI doesn't recognise activities that should rather run in background, so this would never lead to anything.

The culprit seems to be here:

https://github.com/Significant-Gravitas/Auto-GPT/blob/fdd79223b0c6132e1d7fc5127e9ca02fabaea9e5/autogpt/commands/execute_code.py#L113

`subprocess.run()` has a parameter Timeout available, so it might just be a matter of adding it there as well as in the other two functions in that file, either hardcoded to something like `timeout=120` or else in a configurable value via `.env`?

**Comment by Notarin** [comment]
the problem then is now computationally expensive operations will not work whatsoever, due to always being nuked.

**Comment by ntindle** [comment]
This is called [the halting problem](https://brilliant.org/wiki/halting-problem/#:~:text=In%201936%2C%20Alan%20Turing%20proved%20that%20the%20halting,the%20correct%20answer%29%20for%20all%20possible%20program%2Finput%20pairs.), and we won't solve it here without a timeout. May be worth opening a pr for it

**Comment by tomtom94** [comment]
Same issue, I am trying to enter the 3 beginning input.

I am running this Python code :

```
from subprocess import Popen, PIPE
import sys

proc = Popen(["./run.sh"], stdin=PIPE, stdout=PIPE, stderr=PIPE, cwd="./Auto-GPT")
def read_the_line_until_it_finishes():
    while proc.poll() is None:
        line =  proc.stdout.readline().decode()
        if not line:
            break
        sys.stdout.write(line)

read_the_line_until_it_finishes()
proc.stdin.write(b"I want to do this\n")
proc.stdin.flush()
read_the_line_until_it_finishes()
proc.stdin.write(b"My name is Batman\n")
proc.stdin.flush()
read_the_line_until_it_finishes()
proc.stdin.write(b"My AI role is awesome\n")
proc.stdin.flush()
proc.kill()
```

This is the error I am getting, because I had to kill the process by myself, it was too long...

```
$ python3 main.py 
All packages are installed.
Warning: The file 'auto-gpt.json' does not exist. Local memory would not be saved to a file.
NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here. If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
WARNING:  You are running on `master` branch - this is not a supported branch.
Welcome to Auto-GPT!  run with '--help' for more information.
Create an AI-Assistant:  input '--manual' to enter manual mode.
^CTraceback (most recent call last):
  File "/Users/tomtom94/Code/GPTbackv2/main.py", line 15, in <module>
    read_the_line_until_it_finishes()
  File "/Users/tomtom94/Code/GPTbackv2/main.py", line 10, in read_the_line_until_it_finishes
    line =  proc.stdout.readline().decode()
            ^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
```

**Comment by Boostrix** [comment]
> After doing some research I've found that there doesn't really seem to be a solution for detecting if a program is blocking or non-blocking, meaning that the only method for mitigating this in a simple fashion is to set a time-out, which seems rather unfortunate. Hopefully, I'm wrong and someone smarter than me knows how to do so.

Note, the following won't solve the halting problem obviously, but we can look for blocking APIs and interrupt the child processes after a given timeout. More generally, adding a blacklist of interactive programs (nano, vim etc) would seem to suffice though: https://github.com/Significant-Gravitas/Auto-GPT/issues/1327#issuecomment-1529012402

**Comment by SheriAList** [comment]
> SYSTEM: Command execute_shell returned: Error: [Errno 2] No such file or directory: '/home/appuser/autogpt/auto_gpt_workspace'

Looks like you just need to add that folder.
