### ISSUE TITLE
when launching with docker: The file 'AutoGpt.json' does not exist.

### ISSUE THREAD

**Issue by OracleToes** [Significant-Gravitas/Auto-GPT#2463]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Docker

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

clone the github repo
build the docker
launch the docker
get the error that autogpt.json is not there

### Current behavior 😯

I have cloned the github repo and confirmed that autogpt works without the use of docker, but I cannot get python code to execute.
So I have built a docker image and I get the error:
Warning: The file 'AutoGpt.json' does not exist. Local memory would not be saved to a file.

I am using a paid openAI account, and I do not have this issue when launching autoGPT with python.

### Expected behavior 🤔

When launching autoGPT via the docker, I do not to expect to see any errors notifying me that local memory will not be saved to a file.

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by OracleToes** [comment]
I feel like it's worth mentioning that any files present in the auto_gpt_workspace folder do not appear in the docker container. The command I am using to launch the container is this:
`docker run -it --env-file=./.env -v $PWD/auto_gpt_workspace:/app/auto_gpt_workspace autogpt --gpt3only`
I have some files present in the auto_gpt_workspace folder and I am expecting them to show up in the docker container.

**Comment by NBERGERON** [comment]
In the .env file - the MEMORY_INDEX is stated once again at the bottom of the ### WEAVIATE section. Comment that out.
