### ISSUE TITLE
There is no main.py in scripts

### ISSUE THREAD

**Issue by CuzinCash** [Significant-Gravitas/Auto-GPT#2465]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

There is no way to call the program 

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by tukamilano** [comment]
I'm using Mac, and got the same problem

**Comment by merwanehamadi** [comment]
Hi we don't use this file anymore
```
git fetch 
git reset --hard origin/master
python -m autogpt
```
