### ISSUE TITLE
Json parser could select just proper json from the message

### ISSUE THREAD

**Issue by Shin0e** [Significant-Gravitas/Auto-GPT#247]
Often when user tells ai that it did something wrong, it gets confused a bit and instead of pure json starts apologizing, then gives proper JSON and after that is again "polite", ruining the json.
Something like this keeps happening, I assume not just to me:
```I apologize for the mistake again, and thank you for reminding me to only return JSON. Let's try to create the file again: { "command": { "name": "browse_website", "args" [...]```

I think it might be a good idea to parse just text from first `{` to last `}` and only if that doesn't work return error with parsing JSON.

What do you think?

**Comment by rogeriosmorais** [comment]
> I assume not just to me:
Definitely not, happens a lot to me as well.

**Comment by slavakurilyak** [comment]
I think we need to use the [orjson](https://github.com/ijl/orjson) library or LangChain's [Output Parsers](https://python.langchain.com/en/latest/modules/prompts/output_parsers.html) to resolve these issues

**Comment by ArchEight** [comment]
While investigating the potential of using alternative libraries like orjson and refining the AI model, I've got a quick coding suggestion that might help alleviate the issue for now -- implementing a function to extract the JSON content from the AI's response using a regex pattern, as mentioned earlier in this thread.

Here's a possible implementation:

import re

def extract_json(text):
    match = re.search(r'\{(?:[^{}]|(?R))*\}', text)
    return match.group(0) if match else None
This function should return the first valid JSON object found in the input text or None if no JSON object is found. We can then use this function to preprocess the AI's response before passing it to the JSON parser:

response_text = "I apologize for the mistake again, and thank you for reminding me to only return JSON. Let's try to create the file again: { \"command\": { \"name\": \"browse_website\", \"args\" [...]"
json_text = extract_json(response_text)

if json_text:
    # Parse the extracted JSON text and proceed with processing
else:
    # Handle the case where no JSON text is found
This should help handle most cases where the AI returns a mix of text and JSON content. Of course, this is just a temporary solution.

**Comment by ChessScholar** [comment]
> While investigating the potential of using alternative libraries like orjson and refining the AI model, I've got a quick coding suggestion that might help alleviate the issue for now -- implementing a function to extract the JSON content from the AI's response using a regex pattern, as mentioned earlier in this thread.
> 
> Here's a possible implementation:
> 
> import re
> 
> def extract_json(text): match = re.search(r'{(?:[^{}]|(?R))*}', text) return match.group(0) if match else None This function should return the first valid JSON object found in the input text or None if no JSON object is found. We can then use this function to preprocess the AI's response before passing it to the JSON parser:
> 
> response_text = "I apologize for the mistake again, and thank you for reminding me to only return JSON. Let's try to create the file again: { "command": { "name": "browse_website", "args" [...]" json_text = extract_json(response_text)
> 
> if json_text: # Parse the extracted JSON text and proceed with processing else: # Handle the case where no JSON text is found This should help handle most cases where the AI returns a mix of text and JSON content. Of course, this is just a temporary solution.

Where exactly should we try to put this?

**Comment by p-i-** [comment]
Community effort to sort out this JSON fail once and for all at https://github.com/Torantulino/Auto-GPT/issues/1407

We have 17 open PRs for fixing this, and the merge-team are stacked.

**Comment by Pwuts** [comment]
Closing as mostly resolved and superseded by #1407
