### ISSUE TITLE
 "Request for ease of installation or a version from a volunteer that makes it available online

### ISSUE THREAD

**Issue by discapacidad5** [Significant-Gravitas/Auto-GPT#2471]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

: "Request for ease of installation or a version from a volunteer that makes it available online"

I am developing a Braille device with an ESP32, but unfortunately, I have not been able to find anyone who can help me with the HID Braille code, as there is very little information available. I have tried using ChatGPT, but I have had no success. I would like to know if someone can help me achieve the goal of creating a code that works on the ESP32 and turns it into a Braille display that creates a library that can generate Braille displays through HID Bluetooth. When I saw this application, I was very excited because I thought it could help me since it works autonomously and probably gives good results, but I cannot make it work. The way this application works is complex for me, so I beg you to make an installer for Windows or an easy way to run it without so many complications or someone who can help me with its implementation to generate that code for ESP32. I really need a code that serves as an example that works, at least with two buttons, 20 Braille cells displayed in the console, and that connects to the screen reader and displays the text in Braille. This working example would be a starting point for me to continue improving it because there is no public code that one can see to guide them. There is a lot of theoretical information about the HID Braille protocol, but no functional code. I hope you can help me.

**Comment by Explorergt92** [comment]
It could be a potential plugin. I'd reccommend changing the title to mention Braille so it will have a better shot at catching someones eye looking for ideas.

**Comment by discapacidad5** [comment]
> Podría ser un complemento potencial. Recomendaría cambiar el título para mencionar Braille para que tenga una mejor oportunidad de captar la atención de alguien que busca ideas.

¿And what title do you suggest I put?

**Comment by ntindle** [comment]
Use the #prompt-engineering channel on discord to get help generating your prompt for this idea
