### ISSUE TITLE
Text files not consistently being read & memorised / difficult to provide context

### ISSUE THREAD

**Issue by 0rpheus1** [Significant-Gravitas/Auto-GPT#248]
When storing .txt files and advising Auto-GPT to read & memorise them, it rarely does so. Most of the time, it just skips over that task, but sometimes it works.

It would be great to have an easy way to provide a lot of context from the start, in order to push it in the right direction right away.

**Comment by slavakurilyak** [comment]
See pull request https://github.com/Torantulino/Auto-GPT/pull/220

**Comment by gitwithsean** [comment]
I don't think #220 does what this PR is asking for

**Comment by Pwuts** [comment]
Closing as stale. Please reopen with examples if still relevant.
