### ISSUE TITLE
SYSTEM: Command google returned: Error: EOF occurred in violation of protocol (_ssl.c:997)

### ISSUE THREAD

**Issue by sxzq46** [Significant-Gravitas/Auto-GPT#2493]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

set GOOGLE_API_KEY and CUSTOM_SEARCH_ENGINE_ID
run python -m autogpt --gpt3only

### Current behavior 😯

NEXT ACTION:  COMMAND = google ARGUMENTS = {'input': 'ChatGPT principles and applications'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
Input:y -10
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
SYSTEM:  Command google returned: Error: EOF occurred in violation of protocol (_ssl.c:997)

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by Notarin** [comment]
Have you checked your system time? this appears to be caused by some sort of SSL error.

**Comment by ntindle** [comment]
Are you running a proxy?

**Comment by zcqzcg** [comment]
I have fixed this error after shudown the proxy, you may try it if you are using a proxy
