### ISSUE TITLE
Support language configure support and refine prompts

### ISSUE THREAD

**Issue by smallpigss** [Significant-Gravitas/Auto-GPT#2508]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Need to support other language question & answer, such as chinese

### Examples 🌈

LANGUAGE=CN

### Motivation 🔦

now I have add this feature to support chinese and English, and refine the prompts for answer. this is my repo https://github.com/smallpigss/Auto-GPT-CN

**Comment by smallpigss** [comment]
![截屏2023-04-19 15 40 51](https://user-images.githubusercontent.com/128671186/233003881-2b1f62c9-4989-46cc-af3c-5625b0fec60c.png)
this is the snapshot

**Comment by cryptidv** [comment]
Take a look at:
* #1563

Please feel free to contribute to help Auto-GPT be more accessible for everyone!. Closing this issue as completed for now. Feel free to re-open if you need to.
