### ISSUE TITLE
the `memory_add` commad seems not use in Code

### ISSUE THREAD

**Issue by b3y0nd** [Significant-Gravitas/Auto-GPT#2509]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

the `memory_add` commad seems not use in Code, It only has processing logic in app.py, it is not in the added commad when actually constructing the prompt, i.e. chatgpt does not return commands of this type

### Current behavior 😯

No effect

### Expected behavior 🤔

remove memory_add command

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by tusharmakkar08** [comment]
Have added it back to prompt https://github.com/Significant-Gravitas/Auto-GPT/issues/2509
