### ISSUE TITLE
Voices in speech mode

### ISSUE THREAD

**Issue by metzo007** [Significant-Gravitas/Auto-GPT#251]
Hi,

feel free to close this again rightaway since I dont know if the is an issue at all.

In some demos when the AI creates a new instance, the new instance speaks with a female voice, an the conversation between the AI is easy to follow.
When I try it, all GPS's speak in the same male voice, so the conversation is a bit consusing.

Is this expected or an error.
If its expected, I would like to recommend to add a option for changing the voices :-) . Thanks.

Best, Metzo

**Comment by psikosen** [comment]
Hello,

They're likely using eleven labs for the nice voice, I am using one that sounds close to James Earl Jones lol.
If you go to [ElevenLabs](https://beta.elevenlabs.io/). Create an account copy your api key place it in your .env file.  

In the web interface, upload a voice sample  clone a voice and then use your apikey to get all voices via the swagger api copy your voice id. The eleven labs api with a generated voice [swagger](https://api.elevenlabs.io/docs).

**Beware** they have a free version, but you can quickly go through your balance, unless you pay for a higher tier. The 5 and 22 aren't too bad.
 
Change  swap your voice key out with the voice id in  scripts/speak.py 
```
def eleven_labs_speech(text, voice_index=0):
    tts_url = "https://api.elevenlabs.io/v1/text-to-speech/{voice_id}" 
```

**Comment by metzo007** [comment]
> Hello,
> 
> They're likely using eleven labs for the nice voice, I am using one that sounds close to James Earl Jones lol. If you go to [ElevenLabs](https://beta.elevenlabs.io/). Create an account copy your api key place it in your .env file.
> 
> In the web interface, upload a voice sample clone a voice and then use your apikey to get all voices via the swagger api copy your voice id. The eleven labs api with a generated voice [swagger](https://api.elevenlabs.io/docs).
> 
> **Beware** they have a free version, but you can quickly go through your balance, unless you pay for a higher tier. The 5 and 22 aren't too bad.
> 
> Swap out your voice key out with the voice id in scripts/speak.py
> 
> ```
> def eleven_labs_speech(text, voice_index=0):
>     tts_url = "https://api.elevenlabs.io/v1/text-to-speech/{voice_id}" 
> ```

got it. I have a free account, and somehow I an already used all 10.000 characters, while only paying 15 cents to openAI :-)
So I need to find out, why the character usage is so high before I pay for a higher tier.

If you check the "Auto-GPT speaking" video from Torantulino over here
https://github.com/Torantulino/Auto-GPT/discussions/14

you can hear two different voices in video. One main voice, and one instance voice. Any Idea on how to get this working?

**Comment by skynet01** [comment]
This is actually a new issue if you are using the Mac tts it used to do different voices (default and female). Now it only does the default voice. I think the issue is here:

speak.py line 90
```
def macos_tts_speech(text, voice_index=0):
    if voice_index == 0:
        os.system(f'say "{text}"')
    else:
        if voice_index == 1:
            os.system(f'say -v "Ava (Premium)" "{text}"')
        else:
            os.system(f'say -v Samantha "{text}"')
```
I am not a wizard but I think this will always pass index 0 ...

**Comment by Wladastic** [comment]
check my forked repo.
I changed it long ago, it wasnt merged.
also the other voices are only called when agents are created, 0 is default.

**Comment by Wladastic** [comment]
@skynet01  I think you also misunderstand.
mac os tts uses the onboard voices, but only if you activate that.
If it's deactivated, you will need to pay for elevenlabs api, which is slower imo

**Comment by Explorergt92** [comment]
@metzo007 is this still an issue for you or can this be closed?

**Comment by skynet01** [comment]
> @skynet01 I think you also misunderstand. mac os tts uses the onboard voices, but only if you activate that. If it's deactivated, you will need to pay for elevenlabs api, which is slower imo
> 
 I’ve been using your Mac tts implementation since you released, and love it. It’s just recent update broke something, so it doesn’t use 2 voices anymore but same one even when new agents are made. Sorry I think I misunderstood that code snippet and the error might be somewhere else.

 I’ll check out your fork, do you also pull in latest auto-gpt changes?

**Comment by Wladastic** [comment]
I will have to test, but yes it’s up to date. 
There have been some changes that might have broken it. 
or they reference voices that are not installed on your mac, you can remove those that are not on your mac in the mac os tts python file

**Comment by gabkk** [comment]
I have fixed the voices issue for Macos in this PR.
Just waiting for someone to review and merge it ^^

https://github.com/Significant-Gravitas/Auto-GPT/pull/2489
