### ISSUE TITLE
browse_website return : error : message :  (error but not detail message)

### ISSUE THREAD

**Issue by Peakara** [Significant-Gravitas/Auto-GPT#2513]

**Comment by Peakara** [comment]
开始我还以为是webdriver的问题，后边调试也显示是webdriverException，但是chrome和chromedriver版本也是匹配的应该没什么问题，但是需要注意的是在command文件夹里边的web_selenium.py文件中的chrome版本号记得配对，因为chrome可能自动更新。后边尝试了关闭防火墙和杀毒软件，果然是因为防火墙和杀毒软件的拦截，关闭即可成功使用browse_website，这俩把webdriver给拦截了。
总结：
1.web_selenium.py中的chrome版本号匹配问题
2.webdriver被防火墙和杀毒软件拦截问题
解决方案：
1.修改字段Chrome/112.0.5615.49 ==》相对应的版本号：我的是Chrome/112.0.5615.138 
2.关闭防火墙和杀毒软件（设置--安全中心）

Summary:

The Chrome version matching issue in web_selenium.py.
The problem of firewall and antivirus software blocking webdriver.
Solutions:

Modify the field 'Chrome/112.0.5615.49' to the corresponding version number, e.g., 'Chrome/112.0.5615.138'.
Disable the firewall and antivirus software (Settings -> Security Center).

**Comment by dattecode** [comment]
your self my life thx
