### ISSUE TITLE
PS C:\Auto-GPT\Auto-GPT\Auto-GPT> & 　Users/USER/AppData/Local/Programs/Python/Python311/python.exe c:/Auto-GPT/Auto-GPT/Auto-GPT/autogpt/__main__.py

### ISSUE THREAD

**Issue by kitune-JP** [Significant-Gravitas/Auto-GPT#2517]
PS 　Auto-GPT\Auto-GPT\Auto-GPT> & 　Users/USER/AppData/Local/Programs/Python/Python311/python.exe c:/Auto-GPT/Auto-GPT/Auto-GPT/autogpt/__main__.py
Traceback (most recent call last):
  File "　\Auto-GPT\Auto-GPT\Auto-GPT\autogpt\__main__.py", line 6, in <module>
    from autogpt.agent.agent import Agent
ModuleNotFoundError: No module named 'autogpt'　

_Originally posted by @kitune-JP in https://github.com/Significant-Gravitas/Auto-GPT/discussions/2157#discussioncomment-5659121_

**Comment by k-boikov** [comment]
Please run:
# On Linux of Mac:
./run.sh start
# On Windows:
.\run.bat
or
python -m autogpt

**Comment by cryptidv** [comment]
If you're still having this issue @kitune-JP, please re-create an issue with the correct template. Closing now. Cheers!
