### ISSUE TITLE
browse_website always return "Remote end closed connection"

### ISSUE THREAD

**Issue by sunhui0608** [Significant-Gravitas/Auto-GPT#2518]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

using wsl, ubuntu 22.04.
export HTTP_PROXY="localhost:xxx"
python -m autogpt --gpt3only

### Current behavior 😯

report below error, when it uses browse_website any website
SYSTEM:  Command browse_website returned: Error: Remote end closed connection without response

### Expected behavior 🤔

It will work.

### Your prompt 📝

```yaml
# Paste your prompt here
```
ai_goals:
- "find cited times\uDCE6s of sixthtone or \"Sixth Tone\" in nytimes.com"
ai_name: n
ai_role: n

### Your Logs 📒

```log
<insert your logs here>
```
[activity.log](https://github.com/Significant-Gravitas/Auto-GPT/files/11271731/activity.log)

**Comment by ntindle** [comment]
See if #1275 helps

**Comment by sunhui0608** [comment]
> See if #1275 helps

It is not the same problem. Actually, I can already connect with openai, but it will report above error when I use browse_website.

**Comment by ntindle** [comment]
How is your proxy configured?

**Comment by sunhui0608** [comment]
> How is your proxy configured?

Use below words:
export HTTP_PROXY="http://localhost:xxx"

it can connect with openai api, but can not browse any website. Don't know why.

**Comment by ntindle** [comment]
Sorry the proxy itself, not how you’re configuring it to connect here

**Comment by sunhui0608** [comment]
> Sorry the proxy itself, not how you’re configuring it to connect here. What tools, config options etc

it is a internal ip address, the proxy should be in Hongkong.  
it looks like below:  export HTTP_PROXY="http://10.10.100.199:3128"

**Comment by ntindle** [comment]
Proxys are not well supported right now. Feel free to open a PR but I'm going to need significantly more information to debug this . Also may want to try removing the quotes so it's like `export HTTP_PROXY=http://10.10.100.199:3128`

**Comment by sunhui0608** [comment]
> Proxys are not well supported right now. Feel free to open a PR but I'm going to need significantly more information to debug this . Also may want to try removing the quotes and slash so it's like `export HTTP_PROXY=http://10.10.100.199:3128`

I have tried it. It seems not working. 
<img width="875" alt="image" src="https://user-images.githubusercontent.com/7566367/233624031-9674c875-8e19-4212-a792-b4d3fc98e1f0.png">

**Comment by sunhui0608** [comment]
Also google can work. But as to browse any website,  it doesn't work.

**Comment by ntindle** [comment]
Proxys are not well supported right now. Feel free to open a PR to add better proxy support
