### ISSUE TITLE
Semantic Kernel

### ISSUE THREAD

**Issue by DixonDs** [Significant-Gravitas/Auto-GPT#2519]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

I think there is an opportunity to simplify the code base if we use Semantic Kernel library from Microsoft, e.g. https://github.com/microsoft/semantic-kernel/blob/main/samples/notebooks/python/06-memory-and-embeddings.ipynb

**Comment by ntindle** [comment]
Would love to hear more

**Comment by mezafits** [comment]
Totally agree, but honestly I'm not even sure there is a secret sauce here in Auto-GPT. You could basically rewrite it using SK and probably get just as far as Auto-GPT in very little time.
