### ISSUE TITLE
ModuleNotFoundError: No module named 'selenium.webdriver.safari.options'

### ISSUE THREAD

**Issue by easynotedotcom** [Significant-Gravitas/Auto-GPT#2539]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

Hi, 

I have cloned the stable branch with 

`git clone --branch stable https://github.com/Significant-Gravitas/Auto-GPT.git`

Then installed requirements, 
`pip install -r requirements.txt`

Change the open AI key, and saved the .env file and when i try to run it i get the following error below. 

`autogpt\commands\web_selenium.py", line 16, in <module>
    from selenium.webdriver.safari.options import Options as SafariOptions
ModuleNotFoundError: No module named 'selenium.webdriver.safari.options'`

I'm on windows. Any idea what this is happening? 

### Current behavior 😯

Cabt start the autogpt4 at all. 

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
web_selenium.py", line 16, in <module>
    from selenium.webdriver.safari.options import Options as SafariOptions
ModuleNotFoundError: No module named 'selenium.webdriver.safari.options'
```

**Comment by fuckupic** [comment]
Fixed this by running the

python3 -m pip install selenium

After that it said that another module was missing. But the initial error was gone.
I've kept installing the missing modules separately until it started to run without problems.

I hope this helps.

**Comment by easynotedotcom** [comment]
Actually tried that but facing same issue still.

**Comment by easynotedotcom** [comment]
I fixed this issue by running this: 

`pip install --upgrade --force-reinstall -r  requirements.txt`

I hope it helps other people as well :)
