### ISSUE TITLE
Determine chunk size based on model being used

### ISSUE THREAD

**Issue by Pwuts** [Significant-Gravitas/Auto-GPT#2541]
See:
* #38
* #796
* #1841

* Settings:
   * [`BROWSE_CHUNK_MAX_LENGTH`](https://github.com/Significant-Gravitas/Auto-GPT/blob/d163c564e5c33ff70f07608340f1d815a07b6752/.env.template#L8-L9)
   * [`FAST_TOKEN_LIMIT` `SMART_TOKEN_LIMIT`](https://github.com/Significant-Gravitas/Auto-GPT/blob/d163c564e5c33ff70f07608340f1d815a07b6752/.env.template#L40-L44)

The token limit depends directly on the LLM being used, so these settings should be consolidated and calculated where possible, instead of letting the user set them by hand.

**Comment by ntindle** [comment]
Would love a prompts info utils with all this info in it
