### ISSUE TITLE
Support Opera GX as a Browser in Selenium

### ISSUE THREAD

**Issue by Kaletheveggie119** [Significant-Gravitas/Auto-GPT#2554]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### GPT-3 or GPT-4?

GPT-4

### Current behavior 😯

I would like to run chatgpt from Opera GX, but the default is set to chrome. Is it possible to change this?

**Comment by asu00131** [comment]
我电脑上只有Edge浏览器这个情况，也是不能更改，或者让autogpt下载安装chrome也是不行

**Comment by jfranecki** [comment]
I don't think Opera is an option but you would change browsers in the .env file
```
# USE_WEB_BROWSER - Sets the web-browser drivers to use with selenium (defaults to chrome).
# Note: set this to either 'chrome', 'firefox', or 'safari' depending on your current browser
# USE_WEB_BROWSER=chrome
```
You can see `USE_WEB_BROWSER=chrome` is commented out because it already defaults to chrome.

**Comment by ltinerary** [comment]
Only support chrome、firfox、safari.

![image](https://user-images.githubusercontent.com/79144923/233286867-4af46215-c658-47cf-b5f6-7aba149740c7.png)

**Comment by ntindle** [comment]
You could open a pr using this driver https://github.com/operasoftware/operachromiumdriver/releases if you're technically inclined
