### ISSUE TITLE
Command google returned: Error: timed out

### ISSUE THREAD

**Issue by lihongyong** [Significant-Gravitas/Auto-GPT#2568]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

Apply and configure the google api key by following the instructions, and then execute "python -m autogpt --gpt3only".
<img width="1439" alt="1" src="https://user-images.githubusercontent.com/24477373/233162770-a3d2e411-6281-42fd-b02b-8c6074b03ba2.png">
<img width="1439" alt="2" src="https://user-images.githubusercontent.com/24477373/233162785-af490c5d-7c41-4f23-89a5-6ca7cb1794ca.png">
<img width="706" alt="3" src="https://user-images.githubusercontent.com/24477373/233162797-25383648-2935-4a3c-b631-709cfb092557.png">
<img width="1128" alt="4" src="https://user-images.githubusercontent.com/24477373/233162818-015e3bda-7a9a-479e-841c-33beb58b6348.png">

### Current behavior 😯

Symptom Command google returned: Error: timed out is displayed when I request the google api.
<img width="1185" alt="5" src="https://user-images.githubusercontent.com/24477373/233162878-2317a0fc-8f63-4c2d-b01d-9438062fabcf.png">

### Expected behavior 🤔

The google api request is successful and the search is performed

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

NEXT ACTION:  COMMAND = google ARGUMENTS = {'input': 'how to create a simple company website'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
SYSTEM:  Command google returned: Error: timed out

**Comment by lihongyong** [comment]
I think my configuration is OK, but I still report errors. Please help me, thank you

**Comment by l1b3ri** [comment]
https://github.com/Significant-Gravitas/Auto-GPT/issues/1010#issuecomment-1510414121
You can try it.

**Comment by lihongyong** [comment]
> [#1010（评论）](https://github.com/Significant-Gravitas/Auto-GPT/issues/1010#issuecomment-1510414121) 你可以试试。

I can not understand what you say.

**Comment by lihongyong** [comment]
who can help me
