### ISSUE TITLE
autogpt is opening google on guest mode can we switch this?

### ISSUE THREAD

**Issue by Glazyman** [Significant-Gravitas/Auto-GPT#2575]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

when scraping the web it opens google on guest mode. is there a way to make it open on your regular google account?

**Comment by LecJackS** [comment]
You can try adding the path to your chrome profile below this line: https://github.com/Significant-Gravitas/Auto-GPT/blob/bb7ca692e35d889723a63da45da34980e7ebf1e9/autogpt/commands/web_selenium.py#L73

As:
```python
    options = options_available[CFG.selenium_web_browser]()
    options.add_argument(
        "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.5615.49 Safari/537.36"
    )
    options.add_argument("user-data-dir=/home/<username>/.config/google-chrome/Default") # Where this is the path to your chrome profile
```

Tried to test it, but the agent didn't want to scrape the web at all 🤷, so I'm not sure it will work right away.

Context: The [`commands`](https://github.com/Significant-Gravitas/Auto-GPT/tree/master/autogpt/commands) folder contains all the commands (tools) the agent can use, so modifying them modifies directly the agent tools.

**Comment by z-x-x136** [comment]
Thank

**Comment by Glazyman** [comment]
> 
autogpt not responding when put in
