### ISSUE TITLE
Autogpt unable to think (or so it seems)

### ISSUE THREAD

**Issue by BoccheseGiacomo** [Significant-Gravitas/Auto-GPT#2595]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

These evening i installed autogpt and all seemed ok. I watched some video tutorials and other stuff, i installed all and is all ok. 

I used this setup:
name: Enterpreneur-GPT
Goals: ['Search online on affordable websites how to get a revenue from this systems', 'summarize the content', 'write all on markdown file with a good layout']

### Current behavior 😯

After setup, in the cmd window, the label "Thinking" appears, but it isn't actually able to think and it doesn't  write nothing. i waited some minutes and was still there: here i paste the complete output: 

`Name:  Enterpreneur-GPT
Role:  An ai that helps me understand how to make money with AI
Goals: ['Search online on affordable websites how to get a revenue from this systems', 'summarize the content', 'write all on markdown file with a good layout']
Continue (y/n): y
Using memory of type:  LocalCache
Using Browser:  chrome
/ Thinking... ore here: https://github.com/Significant-Gravitas/Auto-GPT#openai-api-keys-configuration
/ Thinking...`

and it seem to remain so forever, unable to start the process. 

It's the first time i use autogpt so it is my first experiment. 

### Expected behavior 🤔

Start to think and do the tasks

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by BoccheseGiacomo** [comment]
Ok maybe the error is mine, i did all the setup using the "master" branch not the stable

**Comment by k-boikov** [comment]
Duplicate https://github.com/Significant-Gravitas/Auto-GPT/issues/2169
