### ISSUE TITLE
sd set in ENV but error returned

### ISSUE THREAD

**Issue by blackshroud** [Significant-Gravitas/Auto-GPT#2607]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

setting "sd" and inputting huggingface API doesn't allow agent to generate image using sd

### Current behavior 😯

when generate image is called, system returns "SYSTEM: Command generate_image returned: No Image Provider Set"

### Expected behavior 🤔

to generate an image

### Your prompt 📝

Generate an image of three people, two women and a man

### Your Logs 📒

EXT ACTION:  COMMAND = generate_image ARGUMENTS = {'prompt': 'Generate an image of three people, two women and a man'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
SYSTEM:  Command generate_image returned: No Image Provider Set
 THOUGHTS:  It seems that the 'generate_image' command is not working.

**Comment by Qoyyuum** [comment]
Hi @blackshroud did you set `IMAGE_PROVIDER` in your `.env`?

**Comment by blackshroud** [comment]
> Hi @blackshroud did you set `IMAGE_PROVIDER` in your `.env`?

Yup, set it as per the readme

**Comment by geopapad** [comment]
same issue here

**Comment by ntindle** [comment]
Do you have an api key configured for HF?

**Comment by geopapad** [comment]
> Do you have an api key configured for HF?

I configured  a User Access Token (Write) for HF and set it HUGGINGFACE_API_TOKEN in .env

**Comment by yhfgyyf** [comment]
same issue  ，
already set  
IMAGE_PROVIDER=sd
HUGGINGFACE_IMAGE_MODEL=CompVis/stable-diffusion-v1-4
HUGGINGFACE_API_TOKEN=hf_***          # my hugging face access tokens (Write)
SD_WEBUI_URL=http://127.0.0.1:7860     

 need to set SD_WEBUI_AUTH?
or something wrong else?

**Comment by joedank** [comment]
I have the issue as well says image provider not set. Tried with and without quotes on the api

**Comment by ak491** [comment]
It's not only a direct command. It can get off the track and get stuck with trying to generate an image 
Also IMAGE_PROVIDER is not set

**Comment by ottoinator82** [comment]
I have set:
IMAGE_PROVIDER=HUGGINGFACE
IMAGE_SIZE=512
HUGGINGFACE_API_TOKEN=(my token read)

I have tried Dalle too...it doesn't work....how can I get image generation to work?
