### ISSUE TITLE
Command browse_website returned: Error: Proxy URL had no scheme, should start with http:// or https://

### ISSUE THREAD

**Issue by river7816** [Significant-Gravitas/Auto-GPT#2613]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

I have post a [issue](https://github.com/Significant-Gravitas/Auto-GPT/issues/2143), however, there is no reply. Is this not a bug? As far as I know, many users have encountered similar situations. 

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by ntindle** [comment]
Please don't open duplicate issues. There are hundreds of them, and they will get looked at when there is time.

**Comment by ntindle** [comment]
Duplicate
