### ISSUE TITLE
WeChat Group For Chinese Users (Auto-GPT 中文交流群)

### ISSUE THREAD

**Issue by wilderchan000** [Significant-Gravitas/Auto-GPT#2620]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

For Chinese communication and develop the project I think we could setup a WeChat Group for communicate.

为了中文交流和开发项目我觉得我们可以建立一个微信群来交流。

![WeChatGroup](https://i.imgur.com/s0Vwiyz.png "Auto-GPT WeChat Group")

### Motivation 🔦

Promote the construction of Auto-GPT Chinese features.
推动 Auto-GTP 中文特性建设

**Comment by zy77777** [comment]
确定 不是卖鞋的？

**Comment by chunfengchuilaoseng** [comment]
二百人满了

**Comment by wilderchan000** [comment]
The WeChat Group reached the upper limit，please join via the above image.
群满了，用上面的那个二维码吧。

**Comment by loseDemon** [comment]
拉我老哥

**Comment by ftp2010** [comment]
拉我一下

**Comment by wsjzs** [comment]
![IMG_2588](https://user-images.githubusercontent.com/17230175/235920167-95ea38dd-8433-493b-bbc5-5524bfd68e79.JPG)

**Comment by wilderchan000** [comment]
![WechatGroup](https://i.imgur.com/27yuWu3.png "Wechat Group For AutoGPT")

@loseDemon @ftp2010 use this one.
更新了一下邀请链接，使用这个。

**Comment by kinance** [comment]
Duplicates #2287

**Comment by kinance** [comment]
Closing this as it's not actionable.

**Comment by dsdnklasmals** [comment]
拉我啊啊啊啊啊啊 求新二维码
