### ISSUE TITLE
quota_exceeded message

### ISSUE THREAD

**Issue by metzo007** [Significant-Gravitas/Auto-GPT#263]
Response content: b'{"detail":{"status":"quota_exceeded","message":"This request exceeds your quota. You have 11 characters remaining, while 70 characters are required for this request.","character_used":10059,"character_limit":10000}}'

i get this message in every response. If does not look like it has any impact on the result

**Comment by loliverhennigh** [comment]
Is this from gpt running out of requests? Seeing same issue

**Comment by loliverhennigh** [comment]
I think this is from the voice api actually...

**Comment by metzo007** [comment]
Hi, I think you are correct. I still get a voice, but it seems to have lower quality

**Comment by Explorergt92** [comment]
You've run out of ElevenLabs characters for the month.. the free plan is capped at 10,000

**Comment by skynet01** [comment]
Thanks for explaining, It would be nice if the prompt told you it's related to voice service.  Otherwise, posts like this will keep popping up. Is there any reason we can't use built-in voice services? For example, Mac and Windows have built-in ones.

**Comment by ghzgod** [comment]
> Thanks for explaining, It would be nice if the prompt told you it's related to voice service. Otherwise, posts like this will keep popping up. Is there any reason we can't use built-in voice services? For example, Mac and Windows have built-in ones.

Or even https://github.com/coqui-ai/TTS, this sounds equally good to elevenlabs in my opinion.

**Comment by rodrix385** [comment]
Same issue. Any fix?

**Comment by Explorergt92** [comment]
> Same issue. Any fix?

Sign up for a paid plan with ElevenLabs ... the free plan has a 10,000 character per month limit.

**Comment by Explorergt92** [comment]
@metzo007 is this still an issue for you or can this be closed?

**Comment by homerdiaz** [comment]
@loliverhennigh You saved my life! thanks!
