### ISSUE TITLE
A command to make it round up what it has already found

### ISSUE THREAD

**Issue by kcibdev** [Significant-Gravitas/Auto-GPT#2630]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

it should work in the same way as how the other commands does
```
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
Input:
```

But it's job is round up or just finish what it has already researched, so if it was given 4 goals and it's now doing the 2nd or 3rd goal you can just enter the command for it to stop or move unto the next goal and maybe save what it has found instead of just immediately exiting

### Motivation 🔦

If what i ask it to do it's still too long to accomplish, i would want it to either finish up with my last research or jump to the next goal

**Comment by Boostrix** [comment]
Related: (meta issue needed)
- #779
- #2460 
- #133 
- #150
