### ISSUE TITLE
agent_manager.py-can be optimized-error handing

### ISSUE THREAD

**Issue by Dr33dM3** [Significant-Gravitas/Auto-GPT#264]
You can use a class to encapsulate the behavior of the agents and remove the need for global variables. This will make the code more organized, and way less prone to error.
You can add error handing in case the API call to Open AI fails or the response is not in the correct format

**Comment by adnanmig** [comment]
An error like this:   File "E:\Python Project\autoGPT\.autogpt\lib\site-packages\openai\api_requestor.py", line 674, in _interpret_response_line
    raise error.APIError(
openai.error.APIError: HTTP code 502 from API (<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
)

**Comment by Dr33dM3** [comment]
@adnanmig you may be correct as I have just started but I thought you could implement this
import openai

def create_agent(task, prompt, model):
    # ... other code here ...

    try:
        response = openai.ChatCompletion.create(
            model=model,
            messages=messages,
        )
    except openai.error.AuthenticationError as e:
        print(f"Error: {e}")
        # Handle the authentication error here
    except openai.error.APIError as e:
        print(f"Error: {e}")
        # Handle other API errors here
    except Exception as e:
        print(f"Unexpected error: {e}")
        # Handle any other unexpected errors here

    if response is None or len(response.choices) == 0:
        print("Unexpected response from OpenAI API")
        # Handle unexpected response here

    # ... other code here ...
please correct me if I am wrong

**Comment by Dr33dM3** [comment]
or will this never happen?

**Comment by adnanmig** [comment]
For my particular error, I think this change should fix it: llm_utils.py

import openai
import backoff
from config import Config
cfg = Config()

openai.api_key = cfg.openai_api_key

# Overly simple abstraction until we create something better
@backoff.on_exception(backoff.expo, openai.error.RateLimitError)
def create_chat_completion(messages, model=None, temperature=None, max_tokens=None)->str:
    if cfg.use_azure:
        response = openai.ChatCompletion.create(
            deployment_id=cfg.openai_deployment_id,
            model=model,
            messages=messages,
            temperature=temperature,
            max_tokens=max_tokens
        )
    else:
        response = openai.ChatCompletion.create(
            model=model,
            messages=messages,
            temperature=temperature,
            max_tokens=max_tokens
        )

    return response.choices[0].message["content"]

**Comment by james431987** [comment]
> For my particular error, I think this change should fix it: llm_utils.py
> 
> import openai import backoff from config import Config cfg = Config()
> 
> openai.api_key = cfg.openai_api_key
> 
> # Overly simple abstraction until we create something better
> @backoff.on_exception(backoff.expo, openai.error.RateLimitError) def create_chat_completion(messages, model=None, temperature=None, max_tokens=None)->str: if cfg.use_azure: response = openai.ChatCompletion.create( deployment_id=cfg.openai_deployment_id, model=model, messages=messages, temperature=temperature, max_tokens=max_tokens ) else: response = openai.ChatCompletion.create( model=model, messages=messages, temperature=temperature, max_tokens=max_tokens )
> 
> ```
> return response.choices[0].message["content"]
> ```

I'm about to try this, did it work for you?
