### ISSUE TITLE
error with image generation using DALLE

### ISSUE THREAD

**Issue by fnefh** [Significant-Gravitas/Auto-GPT#2645]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Docker

### GPT-3 or GPT-4?

GPT-3.5

### Current behavior 😯

System: Command generate_image returned: Error: generate_image_with_dalle() takes 2 positional arguments but 3 were given

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by k-boikov** [comment]
Will be fixed with https://github.com/Significant-Gravitas/Auto-GPT/pull/2491

**Comment by askivo** [comment]
> Will be fixed with #2491

So if the solution listed doesn't work for us we just have to wait for the bug to be fixed?

**Comment by AdelElo13** [comment]
in line 79 of image_gen.py replace the def generate_image_with_dalle line to this line: def generate_image_with_dalle(prompt: str, filename: str, size: int, ) -> str:

**Comment by Pwuts** [comment]
Fixed in #2691
