### ISSUE TITLE
run.sh start gives the no such command start error

### ISSUE THREAD

**Issue by bobinson** [Significant-Gravitas/Auto-GPT#2689]
]

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Devcontainer / Codespace

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

- clone the repository
- setup devcontainer
- commit hash bb7ca692e35d889723a63da45da34980e7ebf1e9
- installed requirements with `pip install -r requirements.txt`
- execute `./run.sh start`

### Current behavior 😯

Error:

```
Usage: python -m autogpt [OPTIONS] COMMAND [ARGS]...
Try 'python -m autogpt --help' for help.

Error: No such command 'start'.
Press any key to continue...
```

<img width="999" alt="image" src="https://user-images.githubusercontent.com/18070249/233410965-77e16313-a842-402b-9d3b-065b6813e25a.png">

### Expected behavior 🤔

Starting of the auto gpt should work normally

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
Requirement already satisfied: h11<0.15,>=0.13 in /home/vscode/.local/lib/python3.10/site-packages (from httpcore<0.18.0,>=0.15.0->httpx<0.25.0,>=0.15.4->openapi-python-client==0.13.4->-r requirements.txt (line 37)) (0.14.0)
Requirement already satisfied: anyio<5.0,>=3.0 in /home/vscode/.local/lib/python3.10/site-packages (from httpcore<0.18.0,>=0.15.0->httpx<0.25.0,>=0.15.4->openapi-python-client==0.13.4->-r requirements.txt (line 37)) (3.6.2)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/vscode/.local/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0dev,>=1.19.0->google-api-python-client->-r requirements.txt (line 13)) (0.5.0)
Usage: python -m autogpt [OPTIONS] COMMAND [ARGS]...
Try 'python -m autogpt --help' for help.

Error: No such command 'start'.
Press any key to continue...
```

**Comment by qualeo** [comment]
I just ran into the same issue with a fresh pull of the `stable` branch (999990b614f9c5e32dbfb560ab9516755d212884). The fix provided by @Pwuts exists on `master` but not the `stable` branch yet. The fix is simple, instead of `./run.sh start`,  execute simply `./run.sh` instead. FYI @bobinson
