### ISSUE TITLE
Add support for providing OpenAI organization along with the API key

### ISSUE THREAD

**Issue by p22shrey** [Significant-Gravitas/Auto-GPT#270]
If a user has multiple organizations linked to their OpenAI account they will be unable to use keys generated through different organizations.

**Comment by kaneda2004** [comment]
I just added this functionality locally, maybe I can do a PR later tonight.

**Comment by kaneda2004** [comment]
@p22shrey https://github.com/Torantulino/Auto-GPT/pull/289

**Comment by scruel** [comment]
Before this issue been solved, you can set `org_id` with environment variables:
```shell
export OPENAI_ORGANIZATION=<your_organization_id>
```

For set up environment variables on windows, there are many tutorials online.
