### ISSUE TITLE
Legal and Ethical Safeguards for Prompts

### ISSUE THREAD

**Issue by w0lph** [Significant-Gravitas/Auto-GPT#2701]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Currently, the agents are entirely unbounded by ethical and legal considerations. I have provided some examples that are a step toward adding default safeguards against malicious behavior. This is a complex and evolving issue, but _something_ is better than _nothing_.

### Examples 🌈

[Heuristic Imperatives from David Shapiro](https://github.com/daveshap/HeuristicImperatives/blob/main/Heuristic%20Imperatives.pdf):
A simple constraint: "Reduce suffering in the universe, increase prosperity in the universe, and increase understanding in the universe."

[Constitutional AI: Harmlessness from AI Feedback](https://arxiv.org/abs/2212.08073):
A series of self-critique [instructions](https://github.com/anthropics/ConstitutionalHarmlessnessPaper/blob/main/prompts/CritiqueRevisionInstructions.json).

### Motivation 🔦

These constraints must be added to the [prompt.py](https://github.com/Significant-Gravitas/Auto-GPT/blob/master/autogpt/prompts/prompt.py) file so that agents don't end up misbehaving and causing illegal or unethical consequences.

**Comment by Cytranics** [comment]
They are if you use the azure api

**Comment by w0lph** [comment]
> They are if you use the azure api

Relying solely on the underlying levels of the stack to act as a safeguard is not the safest path, as people might use different models that are unconstrained or such models might be compromised.

It's prudent to add a safeguard at the agent level to prevent unintended behavior if the model becomes insufficient. This will help create an additional baseline of safety for Auto-GPT that can help develop more capabilities on top of it more safely.

**Comment by rabyj** [comment]
As discussed in https://github.com/Significant-Gravitas/Auto-GPT/discussions/211, this is a very important concern. Putting a safer default is very valuable globally. This would also help avoid potential future legal problems with the userbase.

@w0lph is there a PR associated with this issue? It would help a lot with getting it processed.

**Comment by hdkiller** [comment]
I will create a plugin with the first prompt.

**Comment by w0lph** [comment]
I'm changing the title to Safeguards as I don't want this to be seen as censorship, just safe defaults. It also encompasses other improvements on this front.

**Comment by ntindle** [comment]
We discussed this internally a bit. One concern is people could remove the safeguarding code very easily. Thoughts on how to help with that?

**Comment by hdkiller** [comment]
That’s their decision if they remove safeguards, as they are responsible for the actions of their bot.

**Comment by Cytranics** [comment]
Encrypt safety prompts using a hash to the average joe wont know. If someone is smart enough to decrypt then they can build their own agent anyways.

**Comment by ntindle** [comment]
They could just remove that section of code though

**Comment by IsleOf** [comment]
Stop calling people taking interest in agi's average Joes, it involves risk to humanity, refer to comic books. :)

**Comment by Boostrix** [comment]
one starting point would be passing shell commands to this safeguard prior to executing such commands, this could then look for "jailbreaks" or other questionable stuff, like trying to get root access etc

**Comment by suparious** [comment]
Makes more sense to have this as a `.env` feature that is enabled by default. 

People will always find a way to circumvent censorship, even when it is been spoon-fed to them as "safety".

**Comment by w0lph** [comment]
> People will always find a way to circumvent censorship, even when it is been spoon-fed to them as "safety."

In a saner and more intelligent society, people would stop conflating those two concepts and start promoting responsible AI development with the caution and nuance it deserves.

**Comment by Boostrix** [comment]
See also: #211
