### ISSUE TITLE
Image Generation Fails with Dalle and how I fixed it

### ISSUE THREAD

**Issue by ladyvanburen** [Significant-Gravitas/Auto-GPT#2718]
Attempted image generation with Dalle and received:

INFO SYSTEM:  Command generate_image returned: Error: generate_image_with_dalle() takes 2 positional arguments but 3 were given

I was able to fix this in the image_gen.py script by adding the third missing argument at line 79 as seen below:

def generate_image_with_dalle(prompt: str, filename: str, size: int = 512)

The current commit has only two arguments there when it does indeed specify 3 on line 31.

Hope this helps!

**Comment by hdkiller** [comment]
https://github.com/Significant-Gravitas/Auto-GPT/pull/2691[2691](https://github.com/Significant-Gravitas/Auto-GPT/pull/2691)  will resolve this issue

**Comment by ladyvanburen** [comment]
Awesome, thank you!

**Comment by ntindle** [comment]
Fixed in #2691
