### ISSUE TITLE
Command google returned only 6 websites and it is not able to change next google page

### ISSUE THREAD

**Issue by SpaceTTAngel** [Significant-Gravitas/Auto-GPT#2723]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

Every time that Auto-GPT perform a search on google with the same input, only 6 entry from the google return feedback are showed.
This creates that Auto-GPT perform the same analysis of the website and it is not able to found other results beyond the 6 entries. The entries must be major than 6, and must be created a memory buffer in which Auto-GPT is able to recognize if a same website is analyzed twice

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by ntindle** [comment]
Sometimes it executes something unexpected or doesn’t do what you want.  Check out the #prompt-engineering channel in discord to get a better fit prompt 

if you want us to help beyond that, we need logs and info to reproduce your results
