### ISSUE TITLE
AutoGPT create nothing

### ISSUE THREAD

**Issue by Cyrillus5** [Significant-Gravitas/Auto-GPT#2731]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

CRITICISM:  I need to ensure that I have the correct repository URL and that I clone it to the correct directory.
NEXT ACTION:  COMMAND = clone_repository ARGUMENTS = {'repository_url': 'https://github.com/binance-exchange/binance-official-api-docs.git', 'clone_path': 'C:/Users/c/OneDrive/Documents/SiteWeb/Test/binance-api'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...        
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
SYSTEM:  Command clone_repository returned: Cloned https://github.com/binance-exchange/binance-official-api-docs.git to /home/appuser/auto_gpt_workspace/C:/Users/c/OneDrive/Documents/SiteWeb/Test/binance-api
 THOUGHTS:  Now that I have cloned the Binance API repository, I will create a new ReactJS application in the specified directory.
REASONING:  I need to create a new ReactJS application to build my arbitrage application.
PLAN:
-  Create a new ReactJS application in the specified directory.
CRITICISM:  I need to ensure that I have the necessary dependencies installed and that I create the application in the correct directory.
NEXT ACTION:  COMMAND = execute_shell ARGUMENTS = {'command_line': 'npx create-react-app C:/Users/c/OneDrive/Documents/SiteWeb/Test/app'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...        
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
Executing command 'npx create-react-app C:/Users/c/OneDrive/Documents/SiteWeb/Test/app' in working directory '/home/appuser/auto_gpt_workspace'

In the .env file
## RESTRICT_TO_WORKSPACE - Restrict file operations to workspace ./auto_gpt_workspace (Default: True)
EXECUTE_LOCAL_COMMANDS=True
RESTRICT_TO_WORKSPACE=False

### Current behavior 😯

Nothing was created or cloned

### Expected behavior 🤔

Create a new reactjs app in a folder within my computer.

### Your prompt 📝

```yaml
# HI 
I tried to create a react app and clone file but nothing was created by autoGPT
I modified the .env file like this :
## EXECUTE_LOCAL_COMMANDS - Allow local command execution (Default: False)
## RESTRICT_TO_WORKSPACE - Restrict file operations to workspace ./auto_gpt_workspace (Default: True)
EXECUTE_LOCAL_COMMANDS=True
RESTRICT_TO_WORKSPACE=False
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by ntindle** [comment]
Failed to execute due to mis matched os execution environments. Try to improve your prompt and tell it where it is operating (linux in this case)

**Comment by Cyrillus5** [comment]
Hi. Can you tell me how to resolve my mis matched os execution environnments. I'm on windows.
