### ISSUE TITLE
Python-dotenv could not parse statement starting at line ...

### ISSUE THREAD

**Issue by qualeo** [Significant-Gravitas/Auto-GPT#2749]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

| Commit | Pip | Python | Python-dotenv |
| --- | --- | --- | --- |
| 999990b614f9c5e32dbfb560ab9516755d212884 | `pip 23.0.1 from /usr/lib/python3/dist-packages/pip (python 3.11)` | `Python 3.11.2` | `python-dotenv, version 1.0.0`

**Fresh install of `stable` branch:**

```shell
git clone https://github.com/Significant-Gravitas/Auto-GPT.git
cd Auto-GPT/
git checkout stable
pip install -r requirements.txt
cp .env.template .env
```

**Uncommented and set `OPENAI_API_KEY` env var only:**

```shell
grep -vE '^#|^$' .env 
OPENAI_API_KEY=sk-XXXXXX
```

**Executed init script (see https://github.com/Significant-Gravitas/Auto-GPT/issues/2689):**

```shell
./run.sh
```

**Output:**

```shell
# ...
Requirement already satisfied: distlib<1,>=0.3.6 in /usr/lib/python3/dist-packages (from virtualenv>=20.10.0->pre-commit->-r requirements.txt (line 30)) (0.3.6)
Requirement already satisfied: filelock<4,>=3.4.1 in /usr/lib/python3/dist-packages (from virtualenv>=20.10.0->pre-commit->-r requirements.txt (line 30)) (3.9.0)
Warning: The file 'auto-gpt.json' does not exist. Local memory would not be saved to a file.
Python-dotenv could not parse statement starting at line 61
NEWS:  ::UPDATED:: Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here. If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
Welcome to Auto-GPT!  run with '--help' for more information.
Create an AI-Assistant:  Enter the name of your AI and its role below. Entering nothing will load defaults.
Name your AI:  For example, 'Entrepreneur-GPT'
AI Name:
```

### Current behavior 😯

`./run.sh` outputs **Python-dotenv could not parse statement starting at line 61**

### Expected behavior 🤔

**Python-dotenv should parse statement starting at line 61.**

```shell
python-dotenv --version
python-dotenv, version 1.0.0

python-dotenv --help
Usage: python-dotenv [OPTIONS] COMMAND [ARGS]...

  This script is used to set, get or unset values from a .env file.

Options:
  -f, --file PATH                 Location of the .env file, defaults to .env
                                  file in current working directory.
  -q, --quote [always|never|auto]
                                  Whether to quote or not the variable values.
                                  Default mode is always. This does not affect
                                  parsing.
  -e, --export BOOLEAN            Whether to write the dot file as an
                                  executable bash script.
  --version                       Show the version and exit.
  --help                          Show this message and exit.

Commands:
  get    Retrieve the value for the given key.
  list   Display all the stored key/value.
  run    Run command with environment variables present.
  set    Store the given key/value.
  unset  Removes the given key.
```

### Your prompt 📝

```yaml
# N/A
```

### Your Logs 📒

```log
2023-04-20 21:36:53,745 INFO NEWS:   ::UPDATED:: Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here.
If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
2023-04-20 21:36:54,234 INFO Welcome to Auto-GPT!  run with '--help' for more information.
2023-04-20 21:36:54,454 INFO Create an AI-Assistant: Enter the name of your AI and its role below. Entering nothing will load defaults.
2023-04-20 21:36:54,812 INFO Name your AI:  For example, 'Entrepreneur-GPT'
```

**Comment by Pwuts** [comment]
And what's on line 61?

**Comment by qualeo** [comment]
@Pwuts line 61 of what file? It doesn't specify.

**Comment by Pwuts** [comment]
Line 61 of `.env`

**Comment by qualeo** [comment]
The `.env` is not the issue. Even if I reduce it to a single line I receive the same error.

```shell
$ cat .env | wc -l
1
```

**Comment by Pwuts** [comment]
Does it still complain about line 61 if there is only 1 line?

**Comment by qualeo** [comment]
> Does it still complain about line 61 if there is only 1 line?

Yes.

**Comment by FranMarteen** [comment]
Hi! Gday. Was this issue solved? I am facing the same issue on line 61. Already copied from template again. Auto-gpt is running but I don't what is causing and what functionality may not be workin.

**Comment by daefv** [comment]
Python-dotenv could not parse statement starting at line 6
Python-dotenv could not parse statement starting at line 9
Python-dotenv could not parse statement starting at line 12
Python-dotenv could not parse statement starting at line 15
Python-dotenv could not parse statement starting at line 18
Python-dotenv could not parse statement starting at line 21
Python-dotenv could not parse statement starting at line 24
Python-dotenv could not parse statement starting at line 35
Python-dotenv could not parse statement starting at line 38
Python-dotenv could not parse statement starting at line 41
Python-dotenv could not parse statement starting at line 64
Python-dotenv could not parse statement starting at line 67
Python-dotenv could not parse statement starting at line 94
Python-dotenv could not parse statement starting at line 97
Python-dotenv could not parse statement starting at line 120
Python-dotenv could not parse statement starting at line 123
Python-dotenv could not parse statement starting at line 126
Python-dotenv could not parse statement starting at line 128
Python-dotenv could not parse statement starting at line 131
Python-dotenv could not parse statement starting at line 134
Python-dotenv could not parse statement starting at line 146
Python-dotenv could not parse statement starting at line 149
Python-dotenv could not parse statement starting at line 156
Python-dotenv could not parse statement starting at line 159
Python-dotenv could not parse statement starting at line 166
Python-dotenv could not parse statement starting at line 169
Python-dotenv could not parse statement starting at line 172
Python-dotenv could not parse statement starting at line 175
Python-dotenv could not parse statement starting at line 178
Python-dotenv could not parse statement starting at line 197
Python-dotenv could not parse statement starting at line 199
Python-dotenv could not parse statement starting at line 207

**Comment by luckman212** [comment]
@daefv I had the same issue, eventually figured out that it's because I had an `.env` file in my `$HOME` directory (for Bash env vars) and `Python-dotenv` was trying to parse this. I renamed this file and the errors disappeared.

**Comment by DonRichards** [comment]
Thanks @luckman212  Error in my ~/.env file was the issue. I didn't realize python-dotenv would traverse up to the ~/ directory and load all of the .env files it found along the way.

**Comment by luckman212** [comment]
Apparently another [workaround][1] could be:

```
export SKIP_PYTHONDOTENV=1
```

[1]: https://github.com/hdb/fastmask/issues/1#issuecomment-2081669825
