### ISSUE TITLE
Error: Redis is not installed. Please install redis-py to use Redis as a memory backend.

### ISSUE THREAD

**Issue by callect** [Significant-Gravitas/Auto-GPT#2759]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

I had ingested chunks form a local file with redis.
The redis is running with docker.

My redis keys:

"auto-gpt:13"
 2) "auto-gpt:17"
 3) "auto-gpt:9"
 4) "auto-gpt:4"
 5) "auto-gpt:19"
 6) "auto-gpt:15"
 7) "auto-gpt:0"
 8) "auto-gpt:11"
 9) "auto-gpt:7"
10) "auto-gpt:3"
11) "auto-gpt:8"
12) "auto-gpt:10"
13) "auto-gpt:14"
14) "auto-gpt:18"
15) "auto-gpt:16"
16) "auto-gpt:1"
17) "auto-gpt:5"
18) "auto-gpt-vec_num"
19) "auto-gpt:12"
20) "auto-gpt:20"
21) "auto-gpt:6"
22) "auto-gpt:2"

### Current behavior 😯

when I run:
python -m autogpt

I got the msg:

Error: Redis is not installed. Please install redis-py to use Redis as a memory backend.
Error: Redis is not installed. Please install redis-py to use Redis as a memory backend.
...

### Expected behavior 🤔

why autogpt send the msg?

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by Dr33dM3** [comment]
did you install redis

**Comment by callect** [comment]
> did you install redis

sure.

Package                  Version
------------------------ ---------
aiohttp                  3.8.4
aiosignal                1.3.1
async-generator          1.10
async-timeout            4.0.2
asynctest                0.13.0
attrs                    22.2.0
beautifulsoup4           4.12.2
black                    23.3.0
blis                     0.7.9
cachetools               5.3.0
catalogue                2.0.8
certifi                  2022.12.7
cffi                     1.15.1
cfgv                     3.3.1
chardet                  5.1.0
charset-normalizer       3.1.0
click                    8.1.3
colorama                 0.4.6
confection               0.0.4
coverage                 7.2.3
cssselect                1.2.0
cymem                    2.0.7
distlib                  0.3.6
dnspython                2.3.0
docker                   6.0.1
duckduckgo-search        2.8.5
en-core-web-sm           3.4.0
exceptiongroup           1.1.1
filelock                 3.12.0
flake8                   6.0.0
frozenlist               1.3.3
gitdb                    4.0.10
GitPython                3.1.31
google-api-core          2.11.0
google-api-python-client 2.85.0
google-auth              2.17.3
google-auth-httplib2     0.1.0
googleapis-common-protos 1.59.0
gTTS                     2.3.1
h11                      0.14.0
hiredis                  2.2.2
httplib2                 0.22.0
identify                 2.5.22
idna                     3.4
iniconfig                2.0.0
isort                    5.12.0
Jinja2                   3.1.2
jsonschema               4.17.3
langcodes                3.3.0
loguru                   0.7.0
lxml                     4.9.2
MarkupSafe               2.1.2
mccabe                   0.7.0
multidict                6.0.4
murmurhash               1.0.9
mypy-extensions          1.0.0
nodeenv                  1.7.0
numpy                    1.24.2
oauthlib                 3.2.2
openai                   0.27.2
orjson                   3.8.10
outcome                  1.2.0
packaging                23.1
pathspec                 0.11.1
pathy                    0.10.1
Pillow                   9.5.0
pinecone-client          2.2.1
pip                      23.0.1
platformdirs             3.2.0
playsound                1.2.2
pluggy                   1.0.0
pre-commit               3.2.2
preshed                  3.0.8
protobuf                 4.22.3
py-cpuinfo               9.0.0
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pycodestyle              2.10.0
pycparser                2.21
pydantic                 1.10.7
pyflakes                 3.0.1
pyparsing                3.0.9
pyrsistent               0.19.3
PySocks                  1.7.1
pytest                   7.3.1
pytest-asyncio           0.21.0
pytest-benchmark         4.0.0
pytest-cov               4.0.0
pytest-integration       0.2.3
pytest-mock              3.10.0
python-dateutil          2.8.2
python-dotenv            1.0.0
pywin32                  306
PyYAML                   6.0
readability-lxml         0.8.1
redis                    3.5.3
redisearch               2.1.1
regex                    2023.3.23
rejson                   0.5.6
requests                 2.28.2
requests-oauthlib        1.3.1
rsa                      4.9
selenium                 4.8.3
setuptools               65.5.0
six                      1.16.0
smart-open               6.3.0
smmap                    5.0.0
sniffio                  1.3.0
sortedcontainers         2.4.0
soupsieve                2.4
sourcery                 1.2.0
spacy                    3.4.4
spacy-legacy             3.0.12
spacy-loggers            1.0.4
srsly                    2.4.6
thinc                    8.1.9
tiktoken                 0.3.3
tomli                    2.0.1
tqdm                     4.65.0
trio                     0.22.0
trio-websocket           0.10.2
tweepy                   4.13.0
typer                    0.7.0
typing_extensions        4.5.0
uritemplate              4.1.1
urllib3                  1.26.15
virtualenv               20.21.0
wasabi                   0.10.1
webdriver-manager        3.8.6
websocket-client         1.5.1
win32-setctime           1.1.0
wsproto                  1.2.0
yarl                     1.8.2

**Comment by ntindle** [comment]
Try and use the #tech-support channel in discord for these issues. We don’t have the capacity to help debug in GitHub issues for problems like this. It seems like a setup issue so please mention it

**Comment by w2404** [comment]
Same issue here. I checked autogpt's source, and I saw autogpt failed to import redis.commands. 

redis.commands is not provided by redis 3.5.3, which is required by the latest redisearch. 

On Archlinux, I have redis 4.5.5 installed as a system package. This package has this redis.commands sub module. But this package is incompatible with autogpt.
