### ISSUE TITLE
Unable to resume last executed task

### ISSUE THREAD

**Issue by Lala-0x3f** [Significant-Gravitas/Auto-GPT#2760]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### GPT-3 or GPT-4?

GPT-3.5

### Current behavior 😯

After restarting autogpt, progress is completely lost

### Expected behavior 🤔

The program should continue where it left off

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by ntindle** [comment]
This is expected behavior; use Redis or another memory backend to persist data.
