### ISSUE TITLE
PINECONE_ENV is defaulting to "us-west1-gcp" when connecting to Pinecone instead of the region defined in .env (parameters are commented out)

### ISSUE THREAD

**Issue by JTKunkel** [Significant-Gravitas/Auto-GPT#2761]
When trying to run Auto-GPT with Pinecone memory enabled, I am receiving this error:

"FAILED TO CONNECT TO PINECONE ('401 Client Error: Unauthorized for url: https://controller.us-west1-gcp.pinecone.io/actions/whoami', 'API key is missing or invalid for the environment "us-west1-gcp". Check that the correct environment is specified.')
DOUBLE CHECK CONFIGURATION Please ensure you have setup and configured Pinecone properly for use.You can check out https://github.com/Torantulino/Auto-GPT#-pinecone-api-key-setup to ensure you've set up everything correctly."

Based on the discussion linked below where the reporter received the same error, it looks like the Pinecone region defined in the .env file is not being used when attempting to connect to Pinecone and is defaulting to the "us-west1-gcp" region. Other parameters defined in the .env file, such as the OpenAI API key, are still working as expected.

https://github.com/Significant-Gravitas/Auto-GPT/discussions/2610#discussioncomment-5681086_

EDIT: For further clarity, I ran into this issue on a fresh install of Auto-GPT on a fresh Windows 10 virtual machine. My Pinecone region is not us-west1-gcp, so it's getting that environment from somewhere else.

NEW EDIT: @Maathony is correct, all of these options except for the OpenAI API key are commented out. Don't change any lines with more than one #, un-comment the lines you need.

**Comment by Maathony** [comment]
I'm having the same issue. Only started when I updated .env. 
I tried reverting back but doesn't fix the issue. Fresh install of all files, same problem. 
Turned memory backend to local, but same problem.
Assume it's related to the .env file not being read properly.

$ python -m autogpt
FAILED TO CONNECT TO PINECONE  ('401 Client Error: Unauthorized for url: https://controller.us-west1-gcp.pinecone.io/actions/whoami', 'API key is missing or invalid for the environment "us-west1-gcp". Check that the correct environment is specified.')
DOUBLE CHECK CONFIGURATION  Please ensure you have setup and configured Pinecone properly for use.You can check out https://github.com/Torantulino/Auto-GPT#-pinecone-api-key-setup to ensure you've set up everything correctly.

.env setting:
# PINECONE_ENV=northamerica-northeast1-gcp

**Comment by Maathony** [comment]
Just realised every line in the new env is commented out...

**Comment by gunesatakan** [comment]
> 

Did u solved it? Same issue here.

**Comment by andy20230323** [comment]
I encounter the same issue. Looking forward the fix.
