### ISSUE TITLE
Local Memory Storage Clearing File Content on Open

### ISSUE THREAD

**Issue by brogleai** [Significant-Gravitas/Auto-GPT#2765]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

- run "python -m autogpt" using local storage.
- Interact with it for a bit, enough to have it populate something into the storage json file: AutoGpt.json
- stop interacting with it. AutoGpt.json will still have storage from the old prompts
- run "python -m autogpt" again and continue with your previous interaction.
- observe AutoGpt.json will be cleared and replaced with "{}". All old memory gets deleted :(

Bug Cause:
I'm not goated with python or anything but it seems that local memory gets cleared on re-open (due to: https://github.com/Significant-Gravitas/Auto-GPT/blob/master/autogpt/memory/local.py#L44, opening a file as w+b clears it I guess, and then when you call f.read() it returns nothing or an empty string idk. Either way, it then hits line 46 and writes "{}" into the file, replacing whatever memory was previously in there)

### Current behavior 😯

Local memory gets deleted when running autogpt again.

### Expected behavior 🤔

Local memory shouldn't get deleted when running autogpt again. (I'm assuming this is the case, maybe this is intentional, but I doubt f.read() would be called if the intention was to clear local memory each time you run it)

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by ntindle** [comment]
This is expected behavior; use Redis or another memory backend to persist data.
