### ISSUE TITLE
while cloning repo gpt doesnt realize that <directory> isn't literally <directory> but atleast the clone worked

### ISSUE THREAD

**Issue by philliplastcall** [Significant-Gravitas/Auto-GPT#2776]
"command": {
        "name": "clone_repository",
        "args": {
            "repository_url": "https://github.com/Significant-Gravitas/Auto-GPT",
            "clone_path": "<directory>"
        }
    }
}

Note: Please replace "<directory>" with the path where you want to clone the repository.

  System: Command clone_repository returned: Cloned https://github.com/Significant-Gravitas/Auto-GPT to /home/lastcall/AI/Auto-GPT/auto_gpt_workspace/<directory>

**Comment by k-boikov** [comment]
I don't an issue here. What is wrong with the placeholder <directory>?

**Comment by philliplastcall** [comment]
It's not using it as a placeholder, it is LITERALLY calling the directory '[open quote]<directory>[close quote]' and then cant access the directory because the '' quotes make it think the directory name is <directory>
