### ISSUE TITLE
sometimes stuck in "Thinking" and requires enter key to continue

### ISSUE THREAD

**Issue by simin75simin** [Significant-Gravitas/Auto-GPT#2779]
os:windows 10 (home edition)
python: 3.10.6
autoGPT is working on my machine but sometimes if i give it a 'y -5' command or just move the PowerShell out of focus it is stuck in "Thinking...", but when i press enter it instantly proceeds to the next part.

is this expected? if not, how do i fix this?

thanks in advacne.

**Comment by T-Higgins** [comment]
I've noticed this too. I thought that perhaps it was because I'd hit the enter key twice or something, but I didn't notice this happening in earlier versions.

**Comment by klrmac** [comment]
I'm experiencing this as well, but when I hit enter it does not progress any further. It just spins at "Thinking..."

**Comment by RKP64** [comment]
i am experiencing same thing its thinking and thinking dont know how to solve it . need help

**Comment by DahaoTang** [comment]
i am experiencing same thing its thinking and thinking dont know how to solve it . need help

**Comment by ryanmmmmm** [comment]
same

> i am experiencing same thing its thinking and thinking dont know how to solve it . need help

same

**Comment by ntindle** [comment]
Oftentimes this is when it executes something that requires input. Check out the #prompt-engineering channel in discord to get a better fit prompt
