### ISSUE TITLE
Maximum context length exceeded after `browse_website`

### ISSUE THREAD

**Issue by vmajor** [Significant-Gravitas/Auto-GPT#2783]
Model token length limit defined in `.env` does not seem to propagate to all relevant parts of the code.

I am using `gpt-3.5-turbo` and have set token limits to 4000 in `.env`

I am using the latest stable branch, in windows and invoked with `run.bat`

**Comment by philliplastcall** [comment]
################################################################################
### AUTO-GPT - GENERAL SETTINGS
################################################################################

# BROWSE_CHUNK_MAX_LENGTH - When browsing website, define the length of chunk stored in mem>
BROWSE_CHUNK_MAX_LENGTH=3000 <----------- set this to 3000, or under 4000, its prolly set to 8172 or something

**Comment by vmajor** [comment]
Nope. Already at 3000

**Comment by callect** [comment]
read_file has same issue

**Comment by Drlordbasil** [comment]
i put mine to 2k and no errors since.

**Comment by Pwuts** [comment]
Closing as duplicate of #796
