### ISSUE TITLE
[Error] - {'error': [{'message': 'resolve node name "a919fbe8b731" to host'}]}

### ISSUE THREAD

**Issue by galihlprakoso** [Significant-Gravitas/Auto-GPT#2784]
## Context
I'm using current latest master code:
- 4eaec804386b84a9aba21791ef0fb7b53d8bdd28
I'm using weaviate as my Memory Backend. 

## Error
<img width="747" alt="Screenshot 2023-04-21 at 14 43 58" src="https://user-images.githubusercontent.com/16918033/233574859-bcfaa903-f288-4769-bae2-7310c62c4a88.png">

I'm getting this error. Do you guys have any idea about this?

**Comment by divyanshsinghvi** [comment]
Try using recent stable release instead of master.
