### ISSUE TITLE
AutoGPT still runs on local memory after Having set up Pinecone?

### ISSUE THREAD

**Issue by shijishi** [Significant-Gravitas/Auto-GPT#2790]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

it should run on Pinecone instead of local memory.

## MEMORY_INDEX - Name of index created in Memory backend (Default: auto-gpt)
# MEMORY_BACKEND=pinecone
# MEMORY_INDEX=auto-gpt
## PINECONE_ENV - Pinecone environment (region) (Example: us-west-2)
# PINECONE_API_KEY=2ab9e0a1-fffe-4797-bd65-2957a3b9f200
# PINECONE_ENV=us-west4-gcp

![image](https://user-images.githubusercontent.com/131226621/233599281-fb65d449-2234-48bb-bb3d-62e574cef371.png)
![1682069017183](https://user-images.githubusercontent.com/131226621/233599449-9ec0cffe-a1bd-4823-a6d0-e40ecc40aa70.jpg)

**Comment by Drlordbasil** [comment]
Delete you secret from this post bro!!!

**Comment by Drlordbasil** [comment]
I'll look into this today, send me your .env file and make sure its not .env.temp

**Comment by TheRealVidex** [comment]
Delete your API its like a password. 
But I had the same problem, even when I set it up with docker redis it just kept on using local memory.

**Comment by imag1neArts** [comment]
the same issue for me. also speech mode doesn't work after setting it up right

**Comment by AntonioCiolino** [comment]
what is your command line for starting?
run --gpt3only --use-memory=pinecone

**Comment by costagc** [comment]
Check this portion of the .env file it needs to be changed from local to pinecone.
### MEMORY_BACKEND - Memory backend type
# local - Default
# pinecone - Pinecone (if configured)
# redis - Redis (if configured)
# milvus - Milvus (if configured)
MEMORY_BACKEND=pinecone

**Comment by TheRealVidex** [comment]
Oh, so in the new version you have to tell autoGTP in the command line which memory it should use? If so, I'll try it later if that solves my problem.

**Comment by tonton2006** [comment]
if you just downloaded it today, check that your .env file doesnt have those lines commented out. in 0.2.2 for some reason, damn near everything was commented out for me

**Comment by quantumJLBass** [comment]
I can confirm on 0.2.2 and even on master, settings in `.env` didn't take it was overwritten it appears and went back to local  but does work when you use the CLI options `py -m autogtp --use-memory=pinecone`

**Comment by ntindle** [comment]
Work with the groups in #tech-support in discord to get this fixed. Closing here for now

**Comment by shijishi** [comment]
Guys, thanks for your input, I have reinstall autogpt on my laptop (windows11) strictly following the steps and run it with .\run.bat;
Here is the error:FAILED TO CONNECT TO PINECONE  HTTPSConnectionPool(host='controller.%3cus-west4-gcp%3e.pinecone.io', port=443): Max retries exceeded with url: /actions/whoami (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
DOUBLE CHECK CONFIGURATION  Please ensure you have setup and configured Pinecone properly for use.You can check out https://github.com/Torantulino/Auto-GPT#-pinecone-api-key-setup to ensure you've set up everything correctly.
![1682237331803(1)](https://user-images.githubusercontent.com/131226621/233828058-1e99b8a5-ed52-4500-bb0f-594519932442.png)

**Comment by Mbrown1230** [comment]
same issue for me won't use pinecone I will try that command , do you suppose to use the same command format when trying to use elevenlabs voice ?
