### ISSUE TITLE
Where are the generated projects and files？

### ISSUE THREAD

**Issue by yanzhao77** [Significant-Gravitas/Auto-GPT#2793]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Where are the generated projects and files? Generated project file not found

### Motivation 🔦

save file

**Comment by adam-paterson** [comment]
@yanzhao77 By default any generated files are created in `/Auto-GPT/auto_gpt_workspace/`

**Comment by IbrahimTimimi** [comment]
I also cannot find the saved files. It says that it created the files but I can't find the files in the `auto_gpt_workspace` folder. I also did a full search of my hard disk but I cannot find the files.

I am running the latest repo clone in Windows 10. Please guide me on how to find these files.

**Comment by Boostrix** [comment]
I guess that info should be shown by default if the number of autogpt starts is below some threshold of say ~100 ?
(would seem like a straightforward PR, regardless of the re-arch effort)
