### ISSUE TITLE
Warning: The file 'auto-gpt.json' does not exist. Local memory would not be saved to a file.

### ISSUE THREAD

**Issue by karunakarg** [Significant-Gravitas/Auto-GPT#2796]
After following all instructions, i get the above warning on running autogpt for the first time.

**Comment by spkkarri** [comment]
1) Go to autogpt repository
2) create auto-gpt.json
ex (linux):   echo "" > auto-gpt.json

**Comment by DrDudeBroman** [comment]
I was able to work around this text file with this in it:

{}


Save As:

Auto-GPT.json

**Comment by bobinson** [comment]
The error message appears even if the file is present in the directory:


[06:27 PM] bobinson@MacBook-Pro 🖖  [~/src/Auto-GPT]vim auto-gpt.json
[06:28 PM] bobinson@MacBook-Pro 🖖  [~/src/Auto-GPT]docker run -it --env-file=./.env -v $PWD/auto_gpt_workspace:/app/auto_gpt_workspace autogpt
Warning: The file 'auto-gpt.json' does not exist. Local memory would not be saved to a file.
NEWS:  ::UPDATED:: Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here. If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
Welcome to Auto-GPT!  run with '--help' for more information.
Create an AI-Assistant:  Enter the name of your AI and its role below. Entering nothing will load defaults.
Name your AI:  For example, 'Entrepreneur-GPT'

**Comment by xcreateadmin** [comment]
I have added a auto_gpt.json file but stillg getting Same issue on mac m1:

Requirement already satisfied: h11<1,>=0.9.0 in /Users/winkltechnologies/opt/anaconda3/lib/python3.9/site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium->-r requirements.txt (line 18)) (0.14.0)
Warning: The file 'auto-gpt.json' does not exist. Local memory would not be saved to a file.
./run.sh: line 8: 22735 Illegal instruction: 4  python -m autogpt $@
Press any key to continue...

**Comment by k-boikov** [comment]
> I have added a auto_gpt.json file but still getting Same issue on mac m1:
> 
> Requirement already satisfied: h11<1,>=0.9.0 in /home/opt/anaconda3/lib/python3.9/site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium->-r requirements.txt (line 18)) (0.14.0) Warning: The file 'auto-gpt.json' does not exist. Local memory would not be saved to a file. ./run.sh: line 8: 22735 Illegal instruction: 4 python -m autogpt $@ Press any key to continue...

Can you try running `python -m autogpt --debug`?

**Comment by ZeddMalum** [comment]
it doesn't say The file 'auto-gpt.json' does not exist, however it says: Please set your OpenAI API key in .env or as an environment variable.
You can get your key from https://platform.openai.com/account/api-keys

although I did set my open api key in .env

**Comment by k-boikov** [comment]
Please make sure you are using the proper .env (not the .template) and you don't have any other .env files around.

**Comment by karunakarg** [comment]
the error goes away if I create a blank auto-gpt.json file, on my m2 mac. When the code runs, it writes `{}` in the file. But wouldn't it be better to just include an empty file in the repo itself if it is important, or am I missing something ?

**Comment by Jl159598** [comment]
I did everything in as suggested. It will run in an Command Prompt in Windows, but not in the Docker Desktop.

**Comment by ntindle** [comment]
Known behavior

**Comment by xz-dev** [comment]
> I did everything in as suggested. It will run in an Command Prompt in Windows, but not in the Docker Desktop.

Use command: `podman run --rm -it --name autogpt --env-file=./.env -v $PWD/auto_gpt_workspace:/home/appuser/auto_gpt_workspace -v $PWD/auto_gpt_workspace/auto-gpt.json:/home/appuser/auto-gpt.json significantgravitas/auto-gpt:0.2.2 --continuous`
