### ISSUE TITLE
AutoGPT always gives itself the COMMAND = do_nothing 

### ISSUE THREAD

**Issue by alienking-sol** [Significant-Gravitas/Auto-GPT#2811]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

When giving AutoGPT tasks, by inputing "y", it always returns COMMAND=do_nothing, even after explaining what it will do and giving itself tasks. 

The only issue I can think of would be I am using local cache for memory and did not set any env variables or api keys for external data storage.

### Examples 🌈

-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-=
SYSTEM:  Command google returned: ['https://slack.com/', 'https://www.getapp.com/marketing-software/social-media-monitoring/w/slack/', 'https://www.brandwatch.com/blog/top-social-media-monitoring-tools/', 'https://www.rivaliq.com/blog/top-social-media-listening-tool-reviews/', 'https://www.linkedin.com/pulse/20-best-social-listening-tools-2021-free-paid-sarah-ava', 'https://www.socialmediaexaminer.com/8-ways-to-customize-slack-for-social-media-marketers/', 'https://bloggingwizard.com/social-media-monitoring-tools/', 'https://sproutsocial.com/insights/how-to-use-slack/']
 THOUGHTS:  We need to evaluate the features and capabilities of each of the social listening tools that integrate with Slack to determine which ones best meet our needs.
REASONING:  By evaluating the features and capabilities of each tool, we can determine which ones are most effective for our specific needs. This will help us to select the top 3 tools that will be most beneficial for our lead generation process.
PLAN:
-  Review the features and capabilities of each tool
-  Determine which tools are most effective for our specific needs
-  Select the top 3 tools that will be most beneficial for our lead generation process
CRITICISM:  I need to ensure that I am evaluating each tool thoroughly and objectively to determine which ones are most effective for our needs.
NEXT ACTION:  COMMAND = do_nothing ARGUMENTS = {}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-=
SYSTEM:  Command do_nothing returned: No action performed.

**_[It would repeat this for each step, sometimes even reverting back to previous goals/tasks and re-running them]_**

### Motivation 🔦

Here were the goals I gave it: 
Goal 1: Find the best AI tools to help enhance and automate business development processes, such as prospecting and identifying high intent leads
Goal 2: Find the top 3 Social Listening tools (such as Sprout Social) that can integrate with Slack to alert us when a high intent lead is looking for a crypto accounting solution
Goal 3: Identify the highest converting and intent keywords that are associated with Crypto accounting, crypto accounting solutions, nft accounting and crypto treasury management
Goal 4: Identify some way to prospect and increase leads on LinkedIn that are high intent only

**Comment by Drlordbasil** [comment]
Could make do_nothing a lower variablity maybe?

**Comment by alienking-sol** [comment]
hmm how would I do that?

**Comment by themetalleg** [comment]
I just deleted the three lines in autogpt/promt.py. Maybe not the nicest solution, but works so far.

**Comment by klrmac** [comment]
Mine repetively says the same Thought reasoning criticism blocks over and over. then says command = do_nothing then I hit y and it repeats. I'm in the same boat.

**Comment by enixlabs** [comment]
I would first check and make sure you're not running any backend tasks, I have my IDE open in Task manager and 9/10 times when I get the do_nothing, it's due to BASH.EXE running, which means it's executing an order, in my case, it tends to read a lot.

**Comment by ntindle** [comment]
This is a prompting issue and a limitation of LLMs. Consult with the teams in #prompt-engineering to get something that works a bit better for you.

**Comment by CRYPTEWORLD** [comment]
ARE you guy using godmode.space  it seemed to out put files at first then started doing out side the box stuff ?  it like some one is just enslaving people to harvest from there out puts .  they save all that people do and ???  looks like a scam i can just use chat GPT faster and keep my work for real .  i'm dumping the scammer stuff

**Comment by CRYPTEWORLD** [comment]
I just had a buddy send me a text. He seems to think that there are a whole bunch of people that are activating. Pass through programs. So they can try to get a million people. To basically give them lots of data. That they can sort through with their AI's. And then incorporate into large master programs and immediately go for copyright. That concept. Is mind boggling. If you think about. A million people. Putting their little micro ideas. Into a system. And then they can't print a file to prove. That they were involved in developing a concept. Which means in hours or days. These people could basically steal hundreds of millions of dollars. In copyright value. And only accelerate their plans and increase them. This is mind boggling.

**Comment by alienking-sol** [comment]
> This is a prompting issue and a limitation of LLMs. Consult with the teams in #prompt-engineering to get something that works a bit better for you.

Okay thank you
