### ISSUE TITLE
speech mod doesn't work

### ISSUE THREAD

**Issue by imag1neArts** [Significant-Gravitas/Auto-GPT#2817]
The speech function does not work properly, although everything was installed correctly. I have entered the eleven labs api key and also the two api for the voice. Autogpt always uses the default voice.

**Comment by andrewbaisden** [comment]
I had this problem as well I put the IDs in the wrong place and the code was commented out. Try this in the `.env` file.

```shell
### ELEVENLABS
## ELEVENLABS_API_KEY - Eleven Labs API key (Example: my-elevenlabs-api-key)
## ELEVENLABS_VOICE_1_ID - Eleven Labs voice 1 ID (Example: my-voice-id-1)
## ELEVENLABS_VOICE_2_ID - Eleven Labs voice 2 ID (Example: my-voice-id-2)
ELEVENLABS_API_KEY=your API Key
ELEVENLABS_VOICE_1_ID=21m00Tcm4TlvDq8ikWAM
ELEVENLABS_VOICE_2_ID=AZnzlk1XvdvUeBnXmlld
```

**Comment by imag1neArts** [comment]
The keys are already in the right place, but it doesn't work.

**Comment by gabkk** [comment]
they have updated the module now you need to use the voice name:
```
        voice_options = {
            "Rachel": "21m00Tcm4TlvDq8ikWAM",
            "Domi": "AZnzlk1XvdvUeBnXmlld",
            "Bella": "EXAVITQu4vr4xnSDxMaL",
            "Antoni": "ErXwobaYiN019PkySvjV",
            "Elli": "MF3mGyEYCl7XYWbV9V6O",
            "Josh": "TxGEqnHWrfWFTfGW9XjX",
            "Arnold": "VR6AewLTigWG4xSOukaG",
            "Adam": "pNInz6obpgDQGcFmaJgB",
            "Sam": "yoZ06aMxZJJ28mfd3POQ",
        }
        self._headers = {
            "Content-Type": "application/json",
            "xi-api-key": cfg.elevenlabs_api_key,
        }
        self._voices = default_voices.copy()
        if cfg.elevenlabs_voice_1_id in voice_options:
            cfg.elevenlabs_voice_1_id = voice_options[cfg.elevenlabs_voice_1_id]
```

So use do

```
ELEVENLABS_VOICE_1_ID=Rachel
```

This module is a bit useless imo because you are limited to 10k token and run out quickly in free plan

**Comment by imag1neArts** [comment]
Thank you. Will try it out now.

10'000 tokens for eleven labs free Plan you mean?

**Comment by andrewbaisden** [comment]
You can use the name or ID that's what it says in the readme file. I pulled the latest repo and both methods work.

> they have updated the module now you need to use the voice name:
> 
> ```
>         voice_options = {
>             "Rachel": "21m00Tcm4TlvDq8ikWAM",
>             "Domi": "AZnzlk1XvdvUeBnXmlld",
>             "Bella": "EXAVITQu4vr4xnSDxMaL",
>             "Antoni": "ErXwobaYiN019PkySvjV",
>             "Elli": "MF3mGyEYCl7XYWbV9V6O",
>             "Josh": "TxGEqnHWrfWFTfGW9XjX",
>             "Arnold": "VR6AewLTigWG4xSOukaG",
>             "Adam": "pNInz6obpgDQGcFmaJgB",
>             "Sam": "yoZ06aMxZJJ28mfd3POQ",
>         }
>         self._headers = {
>             "Content-Type": "application/json",
>             "xi-api-key": cfg.elevenlabs_api_key,
>         }
>         self._voices = default_voices.copy()
>         if cfg.elevenlabs_voice_1_id in voice_options:
>             cfg.elevenlabs_voice_1_id = voice_options[cfg.elevenlabs_voice_1_id]
> ```
> 
> So use the name instead
> 
> ```
> ELEVENLABS_VOICE_1_ID=Rachel
> ```
> 
> This module is a bit useless imo because you are limited to 10k token and run out quickly in free plan

**Comment by andrewbaisden** [comment]
@imag1neArts the free plan is 10,000 characters per month. The starter plan is 30,000 characters per month and right now the first month is 80% Off. So that's about $1 for the first month and then $5 for the second month. It's worth paying for the first month which is less than a cup of coffee 😉

**Comment by ntindle** [comment]
Is this resolved?

**Comment by imag1neArts** [comment]
@andrewbaisden thank you for the informations 👍🏻
