### ISSUE TITLE
Add support for more filters to search_files()

### ISSUE THREAD

**Issue by oppiet30** [Significant-Gravitas/Auto-GPT#2823]
NEXT ACTION:  COMMAND = search_files ARGUMENTS = {'directory': '/', 'query': 'liabilities'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
SYSTEM:  Command search_files returned: Error: search_files() got an unexpected keyword argument 'query'

**Comment by GhaffarSherif** [comment]
Same error on my end

**Comment by Brian-Webster** [comment]
Same:

```SYSTEM:  Command search_files returned: Error: search_files() got an unexpected keyword argument 'query'```

**Comment by sid-newby** [comment]
Seems like sometimes it'll work through it. Most often I see it making up names for the files its looking for or adding duplicate destination directories. Sometimes i'll just create the bullshit path it's looking for and it'll find it and end the error loop :) I know i'm an enabler.

**Comment by ntindle** [comment]
looks like a prompting issue. Kinda funky though. Reopen if it keeps happening with different prompts

**Comment by deWaardt** [comment]
![image](https://user-images.githubusercontent.com/5156382/234112000-82e80f3c-d5dc-4201-b1f2-3c27ea72e6f6.png)

I am having the same issue consistently, independent of prompt. Using a prompt proven functional by another user still sometimes triggers this problem.

GPT 3.5

**Comment by nachtien** [comment]
@ntindle I am encountering this issue also. 

I have the latest code at sha 7a161cc0bd8253759c8e7b15c0a3e3d86f0adbad

I'm incredibly new to AutoGPT, but whatever I can do to help debug this I'm all yours.

**Comment by ntindle** [comment]
Okay seems it's hallucinating other potential parameters for this. If any of y'all code, may as well add them as optional
