### ISSUE TITLE
bug template is borked

### ISSUE THREAD

**Issue by claytondukes** [Significant-Gravitas/Auto-GPT#2826]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Looks like `https://github.com/Significant-Gravitas/Auto-GPT/blob/master/.github/ISSUE_TEMPLATE/1.bug.yml` is busted. Nobody can create a bug report.

**Comment by k-boikov** [comment]
Thanks for the report, will be fixed soon.
