### ISSUE TITLE
Memory pre-seeding seems to be broken in the master

### ISSUE THREAD

**Issue by claytondukes** [Significant-Gravitas/Auto-GPT#2827]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

when running on master, the system doesn't not anything already existing in redis.

when I switch to stable, it does.

Here's a sample output from `stable`:

```
Using memory of type:  RedisMemory
Using Browser:  chrome
 THOUGHTS:  I think the first step is to determine what documentation to create. Based on my knowledge of <redacted>, I believe it would be helpful to create documentation on how to use the <redacted>
```

I get no such thing on the master branch (" Based on my knowledge of ")

**Comment by ntindle** [comment]
the .env clears redis cache on startup. There Is a setting you can change to tell it to not do that on master.

**Comment by claytondukes** [comment]
Yes, I am aware. It was not set to clear
