### ISSUE TITLE
Unexpected IMAGE decoding behaviour with SDWEBUI

### ISSUE THREAD

**Issue by wizzo-gmb** [Significant-Gravitas/Auto-GPT#2836]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

I have configured  details to generate images using local SDWEBUI, everything executes correctly but the image decode seems to produce unfavorable results. The results look nothing like the prompt requirements. I tried to use variations of the decode function, so I’m not sure that might be it. But it seems something is up.

These are all images of "realistic people"

Output

![65a2e476-da13-40af-b28d-a1d3774a6fcf](https://user-images.githubusercontent.com/91214699/233709725-78554e07-69e8-4f36-abce-fa415bf08cc3.png)

![af5bc25b-42de-46ea-8261-fbaf3ff43d23](https://user-images.githubusercontent.com/91214699/233709712-33210aee-493e-469f-8244-aeba87f19e27.png)
![47814b11-1b1b-4fca-beb9-1e0c20d96bc9](https://user-images.githubusercontent.com/91214699/233709716-6d2bb23b-f083-45bd-b406-9502d67d90dc.png)
![039b467f-d809-40fa-ac51-a6316cbef84e](https://user-images.githubusercontent.com/91214699/233709718-3ab339eb-5b35-4e8d-896f-6a637275c964.png)
![39ea918c-4426-4583-91be-8484dc2d216f](https://user-images.githubusercontent.com/91214699/233709723-ba94e821-5957-46c7-9aa6-d22e029b78e3.png)

### Current behavior 😯

Images not closely related to the input prompt

### Expected behavior 🤔

Images matching the prompt

### Your prompt 📝

ai_settings.yml

ai_goals:
- generate images
ai_name: aiartist
ai_role: generate 4 images of realistic people

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by ntindle** [comment]
We need way more info to help you here. Please attempt to modify your prompt to be a little more clear. Work with the team in #prompt-engineering on the discord to do so

**Comment by wizzo-gmb** [comment]
> 

The same exact prompt w the same exact settings on geadio  produced expected behavior. It’s not the prompt that I’m using. Shouldn’t I be able to set the same settings as on gradio, input the same prompt and get something close enough to the result…


Not sure how I would need to engineer the prompt better.
