### ISSUE TITLE
enocde instead of encode: typo in autogpt/commands/google_search.py line 113

### ISSUE THREAD

**Issue by DanielBerns** [Significant-Gravitas/Auto-GPT#2843]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

There is a typo in the file autogpt/commands/google_search.py, line 113.

Instead of 

    [result.enocde("utf-8", "ignore") for result in results]

we need to write

    [result.encode("utf-8", "ignore") for result in results]

### Current behavior 😯

Program halts with an AttributeError: str object has no attribute 'enocde'

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by ntindle** [comment]
Fixed
