### ISSUE TITLE
GPT-3.5 Obsessive Compulsive Behavior

### ISSUE THREAD

**Issue by x-0D** [Significant-Gravitas/Auto-GPT#2858]
GPT-3.5 is overthinking and obsessively reading the same file, thinking that it can miss changes on it. This behavior is causing delays and inefficiencies in the program.

**Comment by dmkilday** [comment]
Agreed...I'm seeing the same thing. Good choice of words. :)

**Comment by ntindle** [comment]
This is a prompt issue/ai model limitation. We are working on changes to address this but for now, we recommend you work with the people in #prompt-engineering on the discord to help this behavior
