### ISSUE TITLE
ChatGPT instead of OpenAI API

### ISSUE THREAD

**Issue by IT-EXPRESS-Munich** [Significant-Gravitas/Auto-GPT#2860]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

autogpt should also offer the possibility to search via ChatGPT because more people could use it

### Examples 🌈

-

### Motivation 🔦

-

**Comment by wizzo-gmb** [comment]
Chat gpt is open ai…

**Comment by R-802** [comment]
The OpenAI API incudes ChatGPT/chat functionality. https://platform.openai.com/docs/api-reference/chat

**Comment by ntindle** [comment]
Closing as works?

**Comment by IT-EXPRESS-Munich** [comment]
ok you dont understand... i mean not the money API i mean the ChatGPT with no money (i buy GPT-Plus )
------- Original Message -------
Shemaiah Rangitaawa ***@***.***> schrieb am Samstag, 22. April 2023 um 07:22:

**Comment by R-802** [comment]
I see, that doesn't exist. Unfortunately, there is no dedicated ChatGPT
API, ChatGPT-Plus and the OpenAI API are separate things.
