### ISSUE TITLE
Autogpt：generate_image_with_dalle() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by liyang185** [Significant-Gravitas/Auto-GPT#2866]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

<img width="872" alt="f8e53473c9b6b4453547c93fa0e2a5d" src="https://user-images.githubusercontent.com/113898465/233753584-5390fa2d-8e50-43cb-9ef9-f04a74fcb74f.png">

### Current behavior 😯

<img width="872" alt="f8e53473c9b6b4453547c93fa0e2a5d" src="https://user-images.githubusercontent.com/113898465/233753645-69346691-df90-4ba8-a9bb-6734d9fb73b5.png">

### Expected behavior 🤔

The expected behavior is for the function generate_image_with_dalle to correctly use prompt and filename as arguments and generate an image with a specified size of 256.

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by wizzo-gmb** [comment]
Solution here : https://github.com/Significant-Gravitas/Auto-GPT/issues/2718

**Comment by ntindle** [comment]
duplicate #2718
