### ISSUE TITLE
Linux chrome driver error

### ISSUE THREAD

**Issue by druytssa** [Significant-Gravitas/Auto-GPT#2878]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of Auto-GPT are you using?

Master (branch)

### GPT-3 or GPT-4?

GPT-4

### Current behavior 😯

Hi, I am running Auto-GPT on a Raspberry P400. Everything seems to work fine however I get an error sometimes of "Command browse_website returned: Error: [Errno 8] Exec format error: '/root/.wdm/drivers/chromedriver/linux64/112.0.5615.49/chromedriver'"

In some cases it just goes into a loop with this error.

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by k-boikov** [comment]
Duplicate https://github.com/Significant-Gravitas/Auto-GPT/issues/2219
