### ISSUE TITLE
Change the run script in order to check env just for one time.  

### ISSUE THREAD

**Issue by liaosunny123** [Significant-Gravitas/Auto-GPT#2901]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

In the current running script, the bat will check environment everytime.  

### Motivation 🔦

I want to pr in order to make the script will just check the environment once.

**Comment by bluebird73** [comment]
Yes, each time I launch run.bat, the program has to check missing dependencies and install them all. This wastes time. Guess it is a bug.

**Comment by ntindle** [comment]
Not a bug, people break things and it doesn’t take too long
