### ISSUE TITLE
Command clone_repository returned: Error

### ISSUE THREAD

**Issue by Xerizaf** [Significant-Gravitas/Auto-GPT#2909]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

Clone repository

### Current behavior 😯

Command clone_repository returned: Error: Attempted to access path 'C:\home\******\auto_gpt_workspace\********' outside of workspace 'C:\Users\********\OneDrive\Desktop\Auto-GPT\auto_gpt_workspace'.

### Expected behavior 🤔

Not to turn an error

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by Xerizaf** [comment]
How to set access to file outside workspace?

**Comment by FlamingFury00** [comment]
In the .env file comment out the line that says RESTRICT_TO_WORKSPACE and set it to False, but it's highly not recommended.

**Comment by ntindle** [comment]
Solution in comments, though not recommended

**Comment by bruno90x** [comment]
> In the .env file comment out the line that says RESTRICT_TO_WORKSPACE and set it to False, but it's highly not recommended.

sorry i cant find in .env
