### ISSUE TITLE
Failed to Connect to Pinecone

### ISSUE THREAD

**Issue by Fellow-Soft** [Significant-Gravitas/Auto-GPT#2916]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

.\run.bat

### Current behavior 😯

PS C:\Users\chefj\AutoGPT> .\run.bat
All packages are installed.
FAILED TO CONNECT TO PINECONE  ('401 Client Error: Unauthorized for url: https://controller.us-west1-gcp.pinecone.io/actions/whoami', 'API key is missing or invalid for the environment "us-west1-gcp". Check that the correct environment is specified.')
DOUBLE CHECK CONFIGURATION  Please ensure you have setup and configured Pinecone properly for use.You can check out https://github.com/Torantulino/Auto-GPT#-pinecone-api-key-setup to ensure you've set up everything correctly.
Press any key to continue . . .

### Expected behavior 🤔

Standard use of auto-gpt. has been working fine, now my windows and replit versions have both stopped launching. i am a paid user of pinecone. 

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by k-boikov** [comment]
Please check you .env. If needed delete it and start over from the .env.tempalte.

**Comment by Fellow-Soft** [comment]
> 

Thanks for the response! I will try deleting and resetting. My error messages always say that my API is unauthorized for 'us-west-gcp'  However, my location is northamerica-northeast1-gcp and is listed as such. 

Are there other locations in the auto-gpt script that this could be adjusted to reflect my correct location?

**Comment by k-boikov** [comment]
This is how your .env should look (with your proper data of course)
![image](https://user-images.githubusercontent.com/64261260/233802216-c83dc03f-f8cb-40d3-914a-1559b84f826a.png)
and above you should have
`MEMORY_BACKEND=pinecone`

**Comment by johnpd** [comment]
I'm a new user and I have the same issue, installed an hour or so ago from latest clone.

**Comment by gunesatakan** [comment]
same issue

**Comment by ntindle** [comment]
Ask for help in #tech-support in discord
