### ISSUE TITLE
Loading Local Pretrained Model Through API

### ISSUE THREAD

**Issue by MazenSalama** [Significant-Gravitas/Auto-GPT#292]
Congratulation for this amazing Project 
i have local p retrained model through https://github.com/oobabooga/text-generation-webui
using their API in this format "

import requests

response = requests.post("http://127.0.0.1:7860/run/textgen", json={
	"data": [
		"Below is an instruction that describes a task. Write a response that appropriately completes the request.
### Instruction:
Write a poem about the transformers Python library. 
Mention the word "large language models" in that poem.
### Response:
",
		200,
		False,
		1.99,
		0.18,
		1,
		1.15,
		1,
		30,
		0,
		0,
		1,
		0,
		1,
		False,
		-1,
	]
}).json()

data = response["data"]

looking forward to be able to use local API instead of openAI one

any suggestion for the required modification that i can work on

Regards

**Comment by demanuPL** [comment]
good idea, I was looking for that funcionality for Vicuna-13b quantized model

**Comment by MazenSalama** [comment]
here is some efforts 

config.py

import os
import openai
from dotenv import load_dotenv
# Load environment variables from .env file
load_dotenv()

class Singleton(type):
    """
    Singleton metaclass for ensuring only one instance of a class.
    """

    _instances = {}

    def __call__(cls, *args, **kwargs):
        if cls not in cls._instances:
            cls._instances[cls] = super(
                Singleton, cls).__call__(
                *args, **kwargs)
        return cls._instances[cls]


class Config(metaclass=Singleton):
    """
    Configuration class to store the state of bools for different scripts access.
    """

    def __init__(self):
        self.continuous_mode = False
        self.speak_mode = False
        # TODO - make these models be self-contained, using langchain, so we can configure them once and call it good 
        self.fast_llm_model = os.getenv("FAST_LLM_MODEL", "gpt-3.5-turbo") 
        self.smart_llm_model = os.getenv("SMART_LLM_MODEL", "gpt-4")
        self.fast_token_limit = int(os.getenv("FAST_TOKEN_LIMIT", 4000))
        self.smart_token_limit = int(os.getenv("SMART_TOKEN_LIMIT", 8000))
        
        self.openai_api_key = os.getenv("OPENAI_API_KEY")
        self.elevenlabs_api_key = os.getenv("ELEVENLABS_API_KEY")
        
        self.google_api_key = os.getenv("GOOGLE_API_KEY")
        self.custom_search_engine_id = os.getenv("CUSTOM_SEARCH_ENGINE_ID")

        # Initialize the OpenAI API client
        openai.api_key = self.openai_api_key
        self.custom_model_mode = False
        self.prompt = "Please answer the following question:"
        self.permanent_memory = ""
        if self.custom_model_mode:
            self.token_limit = self.smart_token_limit
        else:
            self.token_limit = self.fast_token_limit

    def set_continuous_mode(self, value: bool):
        self.continuous_mode = value

    def set_speak_mode(self, value: bool):
        self.speak_mode = value

    def set_fast_llm_model(self, value: str):
        self.fast_llm_model = value

    def set_smart_llm_model(self, value: str):
        self.smart_llm_model = value

    def set_fast_token_limit(self, value: int):
        self.fast_token_limit = value

    def set_smart_token_limit(self, value: int):
        self.smart_token_limit = value

    def set_openai_api_key(self, value: str):
        self.openai_api_key = value
    
    def set_elevenlabs_api_key(self, value: str):
        self.elevenlabs_api_key = value
        
    def set_google_api_key(self, value: str):
        self.google_api_key = value
    
    def set_custom_search_engine_id(self, value: str):
        self.custom_search_engine_id = value
        
    def set_custom_model_mode(self, value: bool):
        self.custom_model_mode = value

    
   chat.py

import time
import openai
from dotenv import load_dotenv
from config import Config
import token_counter

cfg = Config()

from llm_utils import create_chat_completion


def create_chat_message(role, content):
    return {"role": role, "content": content}


def chat_with_ai(
        prompt,
        user_input,
        full_message_history,
        permanent_memory,
        token_limit,
        debug=False):
    while True:
        try:
            model = cfg.fast_llm_model
            send_token_limit = token_limit - 1000

            current_context = [
                create_chat_message("system", prompt),
                create_chat_message("system", f"Permanent memory: {permanent_memory}")
            ]

            next_message_to_add_index = len(full_message_history) - 1
            current_tokens_used = 0
            insertion_index = len(current_context)

            current_tokens_used = count_string_tokens(current_context, model)
            current_tokens_used += token_counter.count_tokens([create_chat_message("user", user_input)], model)

            while next_message_to_add_index >= 0:
                message_to_add = full_message_history[next_message_to_add_index]

                tokens_to_add = token_counter.count_tokens([message_to_add], model)
                if current_tokens_used + tokens_to_add > send_token_limit:
                    break

                current_context.insert(insertion_index, full_message_history[next_message_to_add_index])

                current_tokens_used += tokens_to_add
                next_message_to_add_index -= 1

            current_context.extend([create_chat_message("user", user_input)])

            tokens_remaining = token_limit - current_tokens_used

            if debug:
                print(f"Token limit: {token_limit}")
                print(f"Send Token Count: {current_tokens_used}")
                print(f"Tokens remaining for response: {tokens_remaining}")
                print("------------ CONTEXT SENT TO AI ---------------")
                for message in current_context:
                    if message["role"] == "system" and message["content"] == prompt:
                        continue
                    print(f"{message['role'].capitalize()}: {message['content']}")
                    print()
                print("----------- END OF CONTEXT ----------------")

            assistant_reply = create_chat_completion(
                model=model,
                messages=current_context,
                max_tokens=tokens_remaining,
            )

            full_message_history.append(create_chat_message("user", user_input))
            full_message_history.append(create_chat_message("assistant", assistant_reply))

            return assistant_reply
        except openai.error.RateLimitError:
            print("Error: ", "API Rate Limit Reached. Waiting 10 seconds...")
            time.sleep(10)

main.py
import argparse
from chat import chat_with_ai
from config import Config
from dotenv import load_dotenv
from colorama import Fore, init

cfg = Config()
load_dotenv()
init(autoreset=True)  # Initialize colorama

def main():
    parser = argparse.ArgumentParser(description="Chat with an AI model.")
    parser.add_argument("--continuous", action="store_true", help="Keep chatting with the AI until you type 'quit'.")
    parser.add_argument("--speak", action="store_true", help="Speak the AI's responses out loud.")
    parser.add_argument("--debug", action="store_true", help="Enable debug mode.")
    parser.add_argument("--gpt3only", action="store_true", help="Only use GPT-3 for responses.")
    parser.add_argument("--mine", action="store_true", help="Use the new model defined in the config file.")

    args = parser.parse_args()

    if args.mine:
        print("Custom Model Mode: ", Fore.GREEN + "ENABLED")

        cfg.set_custom_model_mode(True)

    user_input = input("Enter your question: ")

    while user_input.lower() != "quit":
        ai_response = chat_with_ai(
            prompt=cfg.prompt,
            user_input=user_input,
            full_message_history=[],
            permanent_memory=cfg.permanent_memory,
            token_limit=cfg.token_limit,
            debug=args.debug
        )
        print("AI:", ai_response)

        if args.speak:
            speak(ai_response)

        if args.continuous:
            user_input = input("\nEnter your question or type 'quit' to exit: ")
        else:
            break

if __name__ == "__main__":
    main()

**Comment by Boostrix** [comment]
related to #2158
