### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by JuanCruzRausch** [Significant-Gravitas/Auto-GPT#2925]
Hi! I'm on macOS, so to use a Python version greater than 3.10, I have to use the 'python3' command. When I try to execute the command './run.sh start', should I change the code where it says 'python' to 'python3'? The same thing happens with 'pip' and 'pip3'.

i changed the code to execute python3 but it is giving me this error

`Missing packages:
distro, mkdocs
Installing missing packages...
Defaulting to user installation because normal site-packages is not writeable
Collecting en-core-web-sm@ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.5.0/en_core_web_sm-3.5.0-py3-none-any.whl
  Using cached https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.5.0/en_core_web_sm-3.5.0-py3-none-any.whl (12.8 MB)
Requirement already satisfied: beautifulsoup4>=4.12.2 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 1)) (4.12.2)
Requirement already satisfied: colorama==0.4.6 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 2)) (0.4.6)
Requirement already satisfied: distro==1.8.0 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 3)) (1.8.0)
Requirement already satisfied: openai==0.27.2 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 4)) (0.27.2)
Requirement already satisfied: playsound==1.2.2 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 5)) (1.2.2)
Requirement already satisfied: python-dotenv==1.0.0 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 6)) (1.0.0)
Requirement already satisfied: pyyaml==6.0 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 7)) (6.0)
Requirement already satisfied: readability-lxml==0.8.1 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 8)) (0.8.1)
Requirement already satisfied: requests in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 9)) (2.28.2)
Requirement already satisfied: tiktoken==0.3.3 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 10)) (0.3.3)
Requirement already satisfied: gTTS==2.3.1 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 11)) (2.3.1)
Requirement already satisfied: docker in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 12)) (6.0.1)
Requirement already satisfied: duckduckgo-search in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 13)) (2.8.6)
Requirement already satisfied: google-api-python-client in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 14)) (2.86.0)
Requirement already satisfied: pinecone-client==2.2.1 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 15)) (2.2.1)
Requirement already satisfied: redis in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 16)) (4.5.4)
Requirement already satisfied: orjson in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 17)) (3.8.10)
Requirement already satisfied: Pillow in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 18)) (9.5.0)
Requirement already satisfied: selenium==4.1.4 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 19)) (4.1.4)
Requirement already satisfied: webdriver-manager in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 20)) (3.8.6)
Requirement already satisfied: jsonschema in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 21)) (4.17.3)
Requirement already satisfied: tweepy in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 22)) (4.13.0)
Requirement already satisfied: click in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 23)) (8.1.3)
Requirement already satisfied: spacy<4.0.0,>=3.0.0 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 24)) (3.5.2)
Requirement already satisfied: coverage in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 28)) (7.2.3)
Requirement already satisfied: flake8 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 29)) (6.0.0)
Requirement already satisfied: numpy in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 30)) (1.24.2)
Requirement already satisfied: pre-commit in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 31)) (3.2.2)
Requirement already satisfied: black in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 32)) (23.3.0)
Requirement already satisfied: isort in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 33)) (5.12.0)
Requirement already satisfied: gitpython==3.1.31 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 34)) (3.1.31)
Requirement already satisfied: auto-gpt-plugin-template in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 35)) (0.0.3)
Requirement already satisfied: mkdocs in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 36)) (1.4.2)
Requirement already satisfied: openapi-python-client==0.13.4 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 40)) (0.13.4)
Requirement already satisfied: pytest in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 45)) (7.3.1)
Requirement already satisfied: asynctest in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 46)) (0.13.0)
Requirement already satisfied: pytest-asyncio in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 47)) (0.21.0)
Requirement already satisfied: pytest-benchmark in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 48)) (4.0.0)
Requirement already satisfied: pytest-cov in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 49)) (4.0.0)
Requirement already satisfied: pytest-integration in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 50)) (0.2.3)
Requirement already satisfied: pytest-mock in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 51)) (3.10.0)
Requirement already satisfied: tqdm in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from openai==0.27.2->-r requirements.txt (line 4)) (4.65.0)
Requirement already satisfied: aiohttp in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from openai==0.27.2->-r requirements.txt (line 4)) (3.8.4)
Requirement already satisfied: chardet in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from readability-lxml==0.8.1->-r requirements.txt (line 8)) (5.1.0)
Requirement already satisfied: lxml in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from readability-lxml==0.8.1->-r requirements.txt (line 8)) (4.9.2)
Requirement already satisfied: cssselect in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from readability-lxml==0.8.1->-r requirements.txt (line 8)) (1.2.0)
Requirement already satisfied: regex>=2022.1.18 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from tiktoken==0.3.3->-r requirements.txt (line 10)) (2023.3.23)
Requirement already satisfied: typing-extensions>=3.7.4 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from pinecone-client==2.2.1->-r requirements.txt (line 15)) (4.5.0)
Requirement already satisfied: python-dateutil>=2.5.3 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from pinecone-client==2.2.1->-r requirements.txt (line 15)) (2.8.2)
Requirement already satisfied: dnspython>=2.0.0 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from pinecone-client==2.2.1->-r requirements.txt (line 15)) (2.3.0)
Requirement already satisfied: urllib3>=1.21.1 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from pinecone-client==2.2.1->-r requirements.txt (line 15)) (1.26.15)
Requirement already satisfied: loguru>=0.5.0 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from pinecone-client==2.2.1->-r requirements.txt (line 15)) (0.7.0)
Requirement already satisfied: trio-websocket~=0.9 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from selenium==4.1.4->-r requirements.txt (line 19)) (0.10.2)
Requirement already satisfied: trio~=0.17 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from selenium==4.1.4->-r requirements.txt (line 19)) (0.22.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from gitpython==3.1.31->-r requirements.txt (line 34)) (4.0.10)
Requirement already satisfied: attrs>=21.3.0 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from openapi-python-client==0.13.4->-r requirements.txt (line 40)) (23.1.0)
Requirement already satisfied: httpx<0.25.0,>=0.15.4 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from openapi-python-client==0.13.4->-r requirements.txt (line 40)) (0.24.0)
Requirement already satisfied: shellingham<2.0.0,>=1.3.2 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from openapi-python-client==0.13.4->-r requirements.txt (line 40)) (1.5.0.post1)
Requirement already satisfied: jinja2<4.0.0,>=3.0.0 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from openapi-python-client==0.13.4->-r requirements.txt (line 40)) (3.1.2)
Requirement already satisfied: typer<0.8.0,>=0.6 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from openapi-python-client==0.13.4->-r requirements.txt (line 40)) (0.7.0)
Requirement already satisfied: pydantic<2.0.0,>=1.6.1 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from openapi-python-client==0.13.4->-r requirements.txt (line 40)) (1.10.7)
Requirement already satisfied: autoflake<3.0.0,>=1.4 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from openapi-python-client==0.13.4->-r requirements.txt (line 40)) (2.1.1)
Requirement already satisfied: soupsieve>1.2 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from beautifulsoup4>=4.12.2->-r requirements.txt (line 1)) (2.4.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from requests->-r requirements.txt (line 9)) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from requests->-r requirements.txt (line 9)) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from requests->-r requirements.txt (line 9)) (2022.12.7)
Requirement already satisfied: websocket-client>=0.32.0 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from docker->-r requirements.txt (line 12)) (1.5.1)
Requirement already satisfied: packaging>=14.0 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from docker->-r requirements.txt (line 12)) (23.1)
Requirement already satisfied: google-auth<3.0.0dev,>=1.19.0 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from google-api-python-client->-r requirements.txt (line 14)) (2.17.3)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from google-api-python-client->-r requirements.txt (line 14)) (4.1.1)
Requirement already satisfied: httplib2<1dev,>=0.15.0 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from google-api-python-client->-r requirements.txt (line 14)) (0.22.0)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from google-api-python-client->-r requirements.txt (line 14)) (2.11.0)
Requirement already satisfied: google-auth-httplib2>=0.1.0 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from google-api-python-client->-r requirements.txt (line 14)) (0.1.0)
Requirement already satisfied: async-timeout>=4.0.2 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from redis->-r requirements.txt (line 16)) (4.0.2)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from jsonschema->-r requirements.txt (line 21)) (0.19.3)
Requirement already satisfied: oauthlib<4,>=3.2.0 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from tweepy->-r requirements.txt (line 22)) (3.2.2)
Requirement already satisfied: requests-oauthlib<2,>=1.2.0 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from tweepy->-r requirements.txt (line 22)) (1.3.1)
Requirement already satisfied: setuptools in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from spacy<4.0.0,>=3.0.0->-r requirements.txt (line 24)) (58.0.4)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from spacy<4.0.0,>=3.0.0->-r requirements.txt (line 24)) (0.10.1)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from spacy<4.0.0,>=3.0.0->-r requirements.txt (line 24)) (1.0.4)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from spacy<4.0.0,>=3.0.0->-r requirements.txt (line 24)) (3.0.8)
Requirement already satisfied: thinc<8.2.0,>=8.1.8 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from spacy<4.0.0,>=3.0.0->-r requirements.txt (line 24)) (8.1.9)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from spacy<4.0.0,>=3.0.0->-r requirements.txt (line 24)) (3.3.0)
Requirement already satisfied: pathy>=0.10.0 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from spacy<4.0.0,>=3.0.0->-r requirements.txt (line 24)) (0.10.1)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from spacy<4.0.0,>=3.0.0->-r requirements.txt (line 24)) (1.0.9)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from spacy<4.0.0,>=3.0.0->-r requirements.txt (line 24)) (3.0.12)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from spacy<4.0.0,>=3.0.0->-r requirements.txt (line 24)) (2.4.6)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from spacy<4.0.0,>=3.0.0->-r requirements.txt (line 24)) (2.0.7)
Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from spacy<4.0.0,>=3.0.0->-r requirements.txt (line 24)) (6.3.0)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from spacy<4.0.0,>=3.0.0->-r requirements.txt (line 24)) (2.0.8)
Requirement already satisfied: mccabe<0.8.0,>=0.7.0 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from flake8->-r requirements.txt (line 29)) (0.7.0)
Requirement already satisfied: pycodestyle<2.11.0,>=2.10.0 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from flake8->-r requirements.txt (line 29)) (2.10.0)
Requirement already satisfied: pyflakes<3.1.0,>=3.0.0 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from flake8->-r requirements.txt (line 29)) (3.0.1)
Requirement already satisfied: virtualenv>=20.10.0 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from pre-commit->-r requirements.txt (line 31)) (20.22.0)
Requirement already satisfied: nodeenv>=0.11.1 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from pre-commit->-r requirements.txt (line 31)) (1.7.0)
Requirement already satisfied: cfgv>=2.0.0 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from pre-commit->-r requirements.txt (line 31)) (3.3.1)
Requirement already satisfied: identify>=1.0.0 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from pre-commit->-r requirements.txt (line 31)) (2.5.22)
Requirement already satisfied: pathspec>=0.9.0 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from black->-r requirements.txt (line 32)) (0.11.1)
Requirement already satisfied: tomli>=1.1.0 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from black->-r requirements.txt (line 32)) (2.0.1)
Requirement already satisfied: mypy-extensions>=0.4.3 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from black->-r requirements.txt (line 32)) (1.0.0)
Requirement already satisfied: platformdirs>=2 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from black->-r requirements.txt (line 32)) (3.2.0)
Requirement already satisfied: abstract-singleton in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from auto-gpt-plugin-template->-r requirements.txt (line 35)) (1.0.1)
Requirement already satisfied: mergedeep>=1.3.4 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from mkdocs->-r requirements.txt (line 36)) (1.3.4)
Requirement already satisfied: markdown<3.4,>=3.2.1 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from mkdocs->-r requirements.txt (line 36)) (3.3.7)
Requirement already satisfied: watchdog>=2.0 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from mkdocs->-r requirements.txt (line 36)) (3.0.0)
Requirement already satisfied: pyyaml-env-tag>=0.1 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from mkdocs->-r requirements.txt (line 36)) (0.1)
Requirement already satisfied: importlib-metadata>=4.3 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from mkdocs->-r requirements.txt (line 36)) (6.6.0)
Requirement already satisfied: ghp-import>=1.0 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from mkdocs->-r requirements.txt (line 36)) (2.1.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc8 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from pytest->-r requirements.txt (line 45)) (1.1.1)
Requirement already satisfied: pluggy<2.0,>=0.12 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from pytest->-r requirements.txt (line 45)) (1.0.0)
Requirement already satisfied: iniconfig in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from pytest->-r requirements.txt (line 45)) (2.0.0)
Requirement already satisfied: py-cpuinfo in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from pytest-benchmark->-r requirements.txt (line 48)) (9.0.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from gitdb<5,>=4.0.1->gitpython==3.1.31->-r requirements.txt (line 34)) (5.0.0)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client->-r requirements.txt (line 14)) (4.22.3)
Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.56.2 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client->-r requirements.txt (line 14)) (1.59.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from google-auth<3.0.0dev,>=1.19.0->google-api-python-client->-r requirements.txt (line 14)) (5.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from google-auth<3.0.0dev,>=1.19.0->google-api-python-client->-r requirements.txt (line 14)) (4.9)
Requirement already satisfied: six>=1.9.0 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from google-auth<3.0.0dev,>=1.19.0->google-api-python-client->-r requirements.txt (line 14)) (1.15.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from google-auth<3.0.0dev,>=1.19.0->google-api-python-client->-r requirements.txt (line 14)) (0.3.0)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from httplib2<1dev,>=0.15.0->google-api-python-client->-r requirements.txt (line 14)) (3.0.9)
Requirement already satisfied: sniffio in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from httpx<0.25.0,>=0.15.4->openapi-python-client==0.13.4->-r requirements.txt (line 40)) (1.3.0)
Requirement already satisfied: httpcore<0.18.0,>=0.15.0 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from httpx<0.25.0,>=0.15.4->openapi-python-client==0.13.4->-r requirements.txt (line 40)) (0.17.0)
Requirement already satisfied: h11<0.15,>=0.13 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from httpcore<0.18.0,>=0.15.0->httpx<0.25.0,>=0.15.4->openapi-python-client==0.13.4->-r requirements.txt (line 40)) (0.14.0)
Requirement already satisfied: anyio<5.0,>=3.0 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from httpcore<0.18.0,>=0.15.0->httpx<0.25.0,>=0.15.4->openapi-python-client==0.13.4->-r requirements.txt (line 40)) (3.6.2)
Requirement already satisfied: zipp>=0.5 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from importlib-metadata>=4.3->mkdocs->-r requirements.txt (line 36)) (3.15.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from jinja2<4.0.0,>=3.0.0->openapi-python-client==0.13.4->-r requirements.txt (line 40)) (2.1.2)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0dev,>=1.19.0->google-api-python-client->-r requirements.txt (line 14)) (0.5.0)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from thinc<8.2.0,>=8.1.8->spacy<4.0.0,>=3.0.0->-r requirements.txt (line 24)) (0.0.4)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from thinc<8.2.0,>=8.1.8->spacy<4.0.0,>=3.0.0->-r requirements.txt (line 24)) (0.7.9)
Requirement already satisfied: sortedcontainers in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from trio~=0.17->selenium==4.1.4->-r requirements.txt (line 19)) (2.4.0)
Requirement already satisfied: async-generator>=1.9 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from trio~=0.17->selenium==4.1.4->-r requirements.txt (line 19)) (1.10)
Requirement already satisfied: outcome in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from trio~=0.17->selenium==4.1.4->-r requirements.txt (line 19)) (1.2.0)
Requirement already satisfied: wsproto>=0.14 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from trio-websocket~=0.9->selenium==4.1.4->-r requirements.txt (line 19)) (1.2.0)
Requirement already satisfied: urllib3-secure-extra in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from urllib3>=1.21.1->pinecone-client==2.2.1->-r requirements.txt (line 15)) (0.1.0)
Requirement already satisfied: pyOpenSSL>=0.14 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from urllib3>=1.21.1->pinecone-client==2.2.1->-r requirements.txt (line 15)) (23.1.1)
Requirement already satisfied: cryptography>=1.3.4 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from urllib3>=1.21.1->pinecone-client==2.2.1->-r requirements.txt (line 15)) (40.0.2)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from urllib3>=1.21.1->pinecone-client==2.2.1->-r requirements.txt (line 15)) (1.7.1)
Requirement already satisfied: cffi>=1.12 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from cryptography>=1.3.4->urllib3>=1.21.1->pinecone-client==2.2.1->-r requirements.txt (line 15)) (1.15.1)
Requirement already satisfied: pycparser in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from cffi>=1.12->cryptography>=1.3.4->urllib3>=1.21.1->pinecone-client==2.2.1->-r requirements.txt (line 15)) (2.21)
Requirement already satisfied: distlib<1,>=0.3.6 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from virtualenv>=20.10.0->pre-commit->-r requirements.txt (line 31)) (0.3.6)
Requirement already satisfied: filelock<4,>=3.11 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from virtualenv>=20.10.0->pre-commit->-r requirements.txt (line 31)) (3.12.0)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from aiohttp->openai==0.27.2->-r requirements.txt (line 4)) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from aiohttp->openai==0.27.2->-r requirements.txt (line 4)) (1.3.1)
Requirement already satisfied: yarl<2.0,>=1.0 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from aiohttp->openai==0.27.2->-r requirements.txt (line 4)) (1.9.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/juancruzrausch/Library/Python/3.9/lib/python/site-packages (from aiohttp->openai==0.27.2->-r requirements.txt (line 4)) (6.0.4)
WARNING: You are using pip version 21.2.4; however, version 23.1.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Usage: python -m autogpt [OPTIONS] COMMAND [ARGS]...
Try 'python -m autogpt --help' for help.

Error: No such command 'start'.
Press any key to continue...`

**Comment by LecJackS** [comment]
You should not run `./run.sh start`, but `./run.sh`, as is described here: https://github.com/Significant-Gravitas/Auto-GPT/blob/master/docs/usage.md

**Comment by k-boikov** [comment]
Python 3.9 is not officially supported, please upgrade to 3.10 or higher.

**Comment by ntindle** [comment]
Please upgrade to 3.10 or later
