### ISSUE TITLE
How can I use autogpt in python script without cmd

### ISSUE THREAD

**Issue by mostafamdy** [Significant-Gravitas/Auto-GPT#2933]
### ⚠️ Search for existing issues first ⚠️

- [ ] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

.

### Current behavior 😯

.

### Expected behavior 🤔

.

### Your prompt 📝

.

### Your Logs 📒

.

**Comment by ntindle** [comment]
No info, no context. Closing as not actionable. Check #tech-support in the discord for better place for this question
