### ISSUE TITLE
Files are not getting created in 'auto_gpt_workspace' folder

### ISSUE THREAD

**Issue by vinodvarma24** [Significant-Gravitas/Auto-GPT#2938]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

Docker 

### Current behavior 😯

AugoGPT running in Docker is givign this message, 'SYSTEM:  Command write_to_file returned: File written to successfully.' --- But the file is not getting written in 'auto_gpt_workspace' folder.  May I know what is the issue here ? Any help would be of a great help

### Expected behavior 🤔

Ideally it should create the files,

### Your prompt 📝

```yaml
# Paste your prompt here
```
SYSTEM:  Command write_to_file returned: File written to successfully.

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by philliplastcall** [comment]
cant fix things without data. add logs. run in --debug mode and copy paste

**Comment by ntindle** [comment]
Closing b/c no logs
