### ISSUE TITLE
Different profiles

### ISSUE THREAD

**Issue by iller75** [Significant-Gravitas/Auto-GPT#2940]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

So i've been running into an issue. I use this for several different things, such as market research for my company, creating trading strategies for my personal use and other things. This means i have to restart every time and give the ai new names and instructions every time. So my suggestion would be to allow one to save different profiles and then one could load those when you start the script. 

### Examples 🌈

As an example you could have different folders like

/Auto-gpt
   /Profiles
      /Company profile
      /python script profile
      /trading profile
      
Then under each profile you could have a file that specifies it's name and it's role so each time it get's loaded it reads that info and know who it is etc.

Also in each profile one could have another folder where one could put all info one would like to pre-load it with and every time it starts it would just read those files etc that are in that folder for that specific profile. This way one could easily keep everything organized and keep the pre-load info up to date etc. 

And then lastly all the output a certain profile creates could be put into an output folder under that profile. 

    

### Motivation 🔦

It's annoying to keep educating the ai every time i want it to do another task and it takes time to organize everything and remember where one put all info etc.

**Comment by ntindle** [comment]
Clone multiple copies of the repo and use that as a workaround for now.
