### ISSUE TITLE
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.

### ISSUE THREAD

**Issue by bitcoinmeetups** [Significant-Gravitas/Auto-GPT#295]
Collecting duckduckgo-search
  Downloading https://www.piwheels.org/simple/duckduckgo-search/duckduckgo_search-2.8.5-py3-none-any.whl (30 kB)
/usr/share/python-wheels/packaging-20.9-py2.py3-none-any.whl/packaging/version.py:127: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
Collecting google-api-python-client
  Downloading https://www.piwheels.org/simple/google-api-python-client/google_api_python_client-2.84.0-py2.py3-none-any.whl (11.2 MB)
     |██████████████████████████████▏ | 10.6 MB 10 kB/s eta 0:01:01
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    google-api-python-client from https://www.piwheels.org/simple/google-api-python-client/google_api_python_client-2.84.0-py2.py3-none-any.whl#sha256=2e0efc004448a036b932d6353ff092bfd92da8aeceaf24ee060bbabc4bd714b5 (from -r requirements.txt (line 13)):
        Expected sha256 2e0efc004448a036b932d6353ff092bfd92da8aeceaf24ee060bbabc4bd714b5
             Got        43b03880120c3d5f815366c1988319434a36cee617531a93da49ccdc8832ad69

4>

**Comment by sinameraji** [comment]
i just re-ran pip install -r requirements.txt and it worked this time.

**Comment by Explorergt92** [comment]
@bitcoinmeetups is this still an issue for you or can this be closed?
