### ISSUE TITLE
No module named 'distro'

### ISSUE THREAD

**Issue by walaccio** [Significant-Gravitas/Auto-GPT#2956]
Apologies, feel free to delete.

**Comment by jtgsystems** [comment]
what was the solution here?

**Comment by MarcoLP1822** [comment]
Please can you tell us the solution?

**Comment by Dustinhoefer** [comment]
Run as admin

**Comment by walaccio** [comment]
Yes, was just running "python pip install -r requirements.txt"

**Comment by PinkPanther-ny** [comment]
not working, I'm using linux, how to fix this?
