### ISSUE TITLE
error During Requirement .txt execution 

### ISSUE THREAD

**Issue by sujitrp** [Significant-Gravitas/Auto-GPT#296]
error During Requirement .txt execution 

On raspberry pi 4b 8GB with Raspbian OS 

Python 3.7.3
pip3 install -r requirements.txt

error: 
  Could not find a version that satisfies the requirement python-dotenv==1.0.0 (from -r requirements.txt (line 5)) (from versions: 0.1.0, 0.1.2, 0.1.3, 0.1.5, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.7.0, 0.7.1, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.5, 0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.15.0, 0.16.0, 0.17.0, 0.17.1, 0.18.0, 0.19.0, 0.19.1, 0.19.2, 0.20.0, 0.21.0, 0.21.1)
No matching distribution found for python-dotenv==1.0.0 (from -r requirements.txt (line 5))

Python 2.7.16
pip install -r requirements.txt

Error : 
Could not find a version that satisfies the requirement openai==0.27.2 (from -r requirements.txt (line 3)) (from versions: 0.0.2, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.2.0, 0.2.1, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.3.0, 0.4.0, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4)
No matching distribution found for openai==0.27.2 (from -r requirements.txt (line 3))

**Comment by kevzy** [comment]
> error:
> Could not find a version that satisfies the requirement python-dotenv==1.0.0 (from -r requirements.txt (line 5)) (from versions: 0.1.0, 0.1.2, 0.1.3, 0.1.5, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.7.0, 0.7.1, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.5, 0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.15.0, 0.16.0, 0.17.0, 0.17.1, 0.18.0, 0.19.0, 0.19.1, 0.19.2, 0.20.0, 0.21.0, 0.21.1)
> No matching distribution found for python-dotenv==1.0.0 (from -r requirements.txt (line 5))

try pip install python-dotenv  

or pip install python-dotenv==0.21.1

**Comment by sujitrp** [comment]
I tried it on a Windows machine with Python3.10. It worked very well . 

For these goals following screenshot is the output 

- find out and List the Sony PS5 features
- Save features in the file
- Collect the price of the Sony PS5 
- Save the list in a file with PS5  source, price, country
- Shutdown after achieving your goal

python scripts/main.py --gpt3only --continuous

![image](https://user-images.githubusercontent.com/7476632/230395326-618411d5-681e-46e8-9a00-47120ce5b052.png)

**Comment by kevzy** [comment]
> > > error:
> > > Could not find a version that satisfies the requirement python-dotenv==1.0.0 (from -r requirements.txt (line 5)) (from versions: 0.1.0, 0.1.2, 0.1.3, 0.1.5, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.7.0, 0.7.1, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.5, 0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.15.0, 0.16.0, 0.17.0, 0.17.1, 0.18.0, 0.19.0, 0.19.1, 0.19.2, 0.20.0, 0.21.0, 0.21.1)
> > > No matching distribution found for python-dotenv==1.0.0 (from -r requirements.txt (line 5))
> > 
> > 
> > try pip install python-dotenv
> > or pip install python-dotenv==0.21.1
> 
> I will try this on my Raspberry Pi with Python 3.7

ok if it fails try installing conda  with pip install conda then run the script inside conda youll have to install all requirements then run the script

**Comment by Explorergt92** [comment]
@sujitrp is this still an issue for you or can this be closed?

**Comment by TruthTrill** [comment]
Still a problem. I had it running on my raspberry pi then I got this error.

**Comment by Qoyyuum** [comment]
Most of the packages require a later more recent version of Python to work like 3.10 or 3.11. Can either of @sujitrp or @TruthTrill test pip install with those Python versions instead on your raspberry pis please?

**Comment by TruthTrill** [comment]
> Most of the packages require a later more recent version of Python to work like 3.10 or 3.11. Can either of @sujitrp or @TruthTrill test pip install with those Python versions instead on your raspberry pis please?

Wow! It actually started installing wheels!!! Now it always stops on sourcery. I even went to the site to directly install it and it seems broken on the pip end. https://pypi.org/project/sourcery/ See if it's broken for everyone else?

**Comment by FuzzTalkAI** [comment]
> Have any of you all powerful Wizards figured out why sourcery simply chooses not to work... Wow that pun wasn't even intended... Anyway, I tried all the pips an pythonsx.x -m I could run. I give up. If we don't fix this soon I'll have to slam this Raspberry Pi against the wall and give up on the golden path of technology. I guess I'll have to turn to petty crime and/or alcoholdrugs. Just put some quarters in my cup later when you see me... 🥺
> 
> > Most of the packages require a later more recent version of Python to work like 3.10 or 3.11. Can either of @sujitrp or @TruthTrill test pip install with those Python versions instead on your raspberry pis please?
> 
> Wow! It actually started installing wheels!!! Now it always stops on sourcery. I even went to the site to directly install it and it seems broken on the pip end. https://pypi.org/project/sourcery/ See if it's broken for everyone else?

I don't know what I'm doing wrong but I cannot get it working on my Pi.
