### ISSUE TITLE
python: can't open file 'F:\\AI\\AutoGpt\\Auto-GPT\\scripts\\main.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by ahmedmoemen** [Significant-Gravitas/Auto-GPT#2960]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

search on google 

### Current behavior 😯

Recieve this message and don't know how can solve it 
python: can't open file 'F:\\AI\\AutoGpt\\Auto-GPT\\scripts\\main.py': [Errno 2] No such file or directory

### Expected behavior 🤔

help with solution or work around

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by mikehnta00** [comment]
use python -m autogpt instead to start the app

**Comment by ntindle** [comment]
Fix provided above

**Comment by ahmedmoemen** [comment]
Thanks, it gives me this message, while i already added the key to ev file Warning: The file 'auto-gpt.json' does not exist. Local memory would not be saved to a file.
Please set your OpenAI API key in .env or as an environment variable.
You can get your key from https://platform.openai.com/account/api-keys
