### ISSUE TITLE
NameError: name 'cfg' is not defined

### ISSUE THREAD

**Issue by ahmadmosama** [Significant-Gravitas/Auto-GPT#2964]
### Discussed in https://github.com/Significant-Gravitas/Auto-GPT/discussions/2963

<div type='discussions-op-text'>

<sup>Originally posted by **ahmadmosama** April 23, 2023</sup>
I am stuck in this error for a while now, any ideas?

![Capture](https://user-images.githubusercontent.com/31259157/233813084-804a04d6-f4bf-499c-93c9-1520fd099516.PNG)

SYSTEM:  Command Error: threw the following error: name 'cfg' is not defined
  Warning: Failed to parse AI output, attempting to fix.
 If you see this warning frequently, it's likely that your prompt is confusing the AI. Try changing it up slightly.
Error:
  Traceback (most recent call last):
  File "D:\OpenAI - GPT\Auto-GPT\Auto-GPT\autogpt\json_fixes\parsing.py", line 101, in fix_and_parse_json
    brace_index = json_to_load.index("{")
                  ^^^^^^^^^^^^^^^^^^^^^^^
ValueError: substring not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\OpenAI - GPT\Auto-GPT\Auto-GPT\autogpt\logs.py", line 211, in print_assistant_thoughts
    assistant_reply_json = fix_and_parse_json(assistant_reply)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\OpenAI - GPT\Auto-GPT\Auto-GPT\autogpt\json_fixes\parsing.py", line 107, in fix_and_parse_json
    return try_ai_fix(try_to_fix_with_gpt, e, json_to_load)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\OpenAI - GPT\Auto-GPT\Auto-GPT\autogpt\json_fixes\parsing.py", line 136, in try_ai_fix
    ai_fixed_json = fix_json(json_to_load, JSON_SCHEMA)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\OpenAI - GPT\Auto-GPT\Auto-GPT\autogpt\json_fixes\auto_fix.py", line 24, in fix_json
    function_string, args, description_string, model=cfg.fast_llm_model
                                                     ^^^
NameError: name 'cfg' is not defined

Attempting to fix JSON by finding outermost brackets
Error: Invalid JSON, setting it to empty JSON now.</div>

**Comment by holisHsu** [comment]
I seems you are not in master or release v0.2.2 🤔 what's the branch or commit or tag you are in ?

**Comment by ntindle** [comment]
Need more logs

**Comment by ahmadmosama** [comment]
> I seems you are not in master or release v0.2.2 🤔 what's the branch or commit or tag you are in ?

It was an outdated release. Thanks for the heads up!
