### ISSUE TITLE
Auto-GPT Command evaluate_code returned: Error: The model: `gpt-4` does not exist

### ISSUE THREAD

**Issue by Khnaz35** [Significant-Gravitas/Auto-GPT#2973]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

MacBook-Pro-2:Auto-GPT khnaz35 $ docker run -it --env-file=/Users/desktop/Auto-GPT/.env -v $PWD/auto_gpt_workspace:/home/appuser/auto_gpt_workspace autogpt
Warning: The file 'auto-gpt.json' does not exist. Local memory would not be saved to a file.
NEWS:  ::UPDATED:: Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here. If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
Welcome to Auto-GPT!  run with '--help' for more information.
Create an AI-Assistant:  Enter the name of your AI and its role below. Entering nothing will load defaults.
Name your AI:  For example, 'Entrepreneur-GPT'
AI Name: 
Entrepreneur-GPT here!  I am at your service.
Describe your AI's role:  For example, 'an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.'
Entrepreneur-GPT is: 
Enter up to 5 goals for your AI:  For example: Increase net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously'
Enter nothing to load defaults, enter nothing when finished.
Goal 1: How many GPT agents are available?

### Current behavior 😯

Using memory of type:  LocalCache
Using Browser:  chrome
 THOUGHTS:  I think I should start by listing the available GPT agents to see what resources I have available.
REASONING:  Listing the available GPT agents will give me an idea of what tasks I can delegate to them and what resources I have available to me.
PLAN: 
-  List available GPT agents
CRITICISM:  I need to ensure that I am delegating tasks effectively and not overloading any one agent with too many tasks.
NEXT ACTION:  COMMAND = list_agents ARGUMENTS = {}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
SYSTEM:  Command list_agents returned: List of agents:
 THOUGHTS:  I think I should start a new GPT agent to help me with my tasks.
REASONING:  Starting a new GPT agent will allow me to delegate tasks to it and free up my own resources.
PLAN: 
-  Start a new GPT agent
CRITICISM:  I need to ensure that I am giving the agent clear and concise tasks to complete, and that I am not overloading it with too many tasks.
NEXT ACTION:  COMMAND = start_agent ARGUMENTS = {'name': 'task_agent', 'task': 'Assist with simple tasks', 'prompt': 'What task would you like me to complete?'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
SYSTEM:  Command start_agent returned: Agent task_agent created with key 0. First response: As an AI language model, I do not have any specific task for you to complete. However, if you have any questions or need assistance with anything, feel free to ask and I will do my best to help you.
 THOUGHTS:  I should ask the new GPT agent to search for the number of agents I have available.
REASONING:  Asking the new GPT agent to search for the number of agents I have available will give me an idea of how many resources I have available.
PLAN: 
-  Ask task_agent to search for the number of agents available
CRITICISM:  I need to ensure that I am giving the agent clear and concise tasks to complete, and that I am not overloading it with too many tasks.
NEXT ACTION:  COMMAND = message_agent ARGUMENTS = {'key': 0, 'message': 'Please search for the number of agents I have available.'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
Input:

### Expected behavior 🤔

Should list the available agent from my .env files. I have these settings available.
`
## FAST_LLM_MODEL - Fast language model (Default: gpt-3.5-turbo)
SMART_LLM_MODEL=gpt-4
FAST_LLM_MODEL=gpt-3.5-turbo

## When using --gpt3only this needs to be set to 4000.
FAST_TOKEN_LIMIT=4000
SMART_TOKEN_LIMIT=8000`

Also i have paid account setup for my use case 
<img width="532" alt="image" src="https://user-images.githubusercontent.com/43812103/233819701-c298d6c1-48bd-415a-8b72-fdc5366ab397.png">

### Your prompt 📝

```yaml
# Paste your prompt here
```
How many GPT agents are available?

Also i don't see the file ai_settings.yaml file
<img width="104" alt="image" src="https://user-images.githubusercontent.com/43812103/233819795-2191c646-2a74-4f24-9df3-b10345597767.png">

### Your Logs 📒

```log
<insert your logs here>
```
I am not seeing the log/activity.log
<img width="104" alt="image" src="https://user-images.githubusercontent.com/43812103/233819792-cc087107-ecfd-4f38-abdc-488ee50199c1.png">

**Comment by manuel919** [comment]
I assume you do not have access to the model GPT4, yet. You can join the waitlist here: https://openai.com/waitlist/gpt-4-api
Alternatively just use GPT3.5 by calling 
`python -m autogpt --gpt3only`

**Comment by Khnaz35** [comment]
Might be that's an issue even after setting up the paid account its not allowing access to gtp-4, 
Btw i do have access to chatgpt plus though. 

Also can you confirm that why it still doesn't list the other user agent ?

SMART_LLM_MODEL=gpt-4
**FAST_LLM_MODEL=gpt-3.5-turbo**
Because my prompt was "How many GPT agents are available?" I also tried with "How many GPT agents I do have?"

**Comment by manuel919** [comment]
Yeah, chatgpt plus gives you access to gpt4 via their chat interface. But
not via API, which is required for auto gpt.

You could also set SMART_LLM_MODEL to the same value as *FAST_LLM_MODEL*

**Comment by bradiosd** [comment]
I had access to message_agent on 20/21 of April and now I am getting the error that the OP is getting. They seem to have taken my GPT4 access away?
