### ISSUE TITLE
Add `model` argument to `analyze_code`

### ISSUE THREAD

**Issue by javableu** [Significant-Gravitas/Auto-GPT#2986]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

NEXT ACTION:  COMMAND = analyze_code ARGUMENTS = {'code': '<full_code_string>', 'model': 'gpt-3'}

### Examples 🌈

The ai is trying to anaylze_code with the model as an argument. I thaught it would be a good idea to have this option.

**Comment by NISPUK** [comment]
Hey do you know how i can fix this error? maybe it is related to your topic

problem:
Command analyze_code returned: Error: The model: `gpt-4` does not exist

i want autogpt to analyze text documents for me and delete dublicates

**Comment by khanfar** [comment]
I I get same error on gpt3

**Comment by Pwuts** [comment]
Are you still having this issue with the latest version (of `master`)?

**Comment by Pwuts** [comment]
I don't think we'll be implementing this anytime soon. Do you have any specific use cases in mind?

**Comment by javableu** [comment]
When the AI wants to use a command, it really often comes up with its own type of argument even if they are not available in the definition of the command. 
Basically, each time the ai does that, it thinks it would be a cool argument to implement in the specific command. 
In that particular case, this model argument could be used to call any type of AI model. It will be really nice to have in the near future when you'll have local model running. It would already be nice to have if you want the ai to decide if it wants to use gp3.5 or 4 I guess. This could be an argument used in all of the "intelligent".

**Comment by javableu** [comment]
You can try to use --gpt3only arg when you call autogpt to solve your issues https://github.com/Significant-Gravitas/Auto-GPT/issues/2986#issuecomment-1519123679
