### ISSUE TITLE
Continuos mode cut off

### ISSUE THREAD

**Issue by Ckemplen** [Significant-Gravitas/Auto-GPT#299]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

As there are concerns about continuous mode running forever (or just longer than is desirable). Could a feature be to allow the user to set an arbitrary number of actions to be done autonomously before asking user for authorisation again? E.g. allow for 50 autonomous actions without approval before stopping to check in with the user

**Comment by Arlodotexe** [comment]
This is available if you pull

**Comment by Explorergt92** [comment]
@Ckemplen is this still an issue for you or can this be closed?

**Comment by Pwuts** [comment]
Closing as completed
