### ISSUE TITLE
Run autogpt - ./run.sh: line 2: python: command not found

### ISSUE THREAD

**Issue by fuser333** [Significant-Gravitas/Auto-GPT#2992]
### Discussed in https://github.com/Significant-Gravitas/Auto-GPT/discussions/2974

<div type='discussions-op-text'>

<sup>Originally posted by **ryanbakkerNZ** April 22, 2023</sup>
Getting the following error when trying to run ./run.sh start on Mac.

./run.sh: line 2: python: command not found
./run.sh: line 8: python: command not found</div>

**Comment by dilldill1** [comment]
I had to update my run.sh file and change python to python3 and pip to pip3 and then was able to successfully run

**Comment by UlrichThiess** [comment]
make symlinks python to python3 and so on

**Comment by danielehrhardt** [comment]
Mac:
`sudo unlink /usr/local/bin/python`
`sudo ln -s /usr/bin/python3 /usr/local/bin/python`

**Comment by RoyalFatness** [comment]
Can someone show me step-by-step how to do this? I am complete nub

**Comment by Cyrillus5** [comment]
For me, inside the run.bat file (within root), I replaced python -m autogpt %* by py -m autogpt %*., and now it runs.

**Comment by klppl** [comment]
> Can someone show me step-by-step how to do this? I am complete nub

On what OS are you trying to run run.sh ?

**Comment by nawartamawi** [comment]
To create symbolic links for python to point to python3, and also for pip to point to pip3, follow these steps:

Open a terminal.

Remove any existing python and pip symbolic links in /usr/local/bin:

```
sudo rm /usr/local/bin/python
sudo rm /usr/local/bin/pip
```
Create new symbolic links for python to point to python3 and for pip to point to pip3:


```
ln -s /usr/local/bin/python3 /usr/local/bin/python
ln -s /usr/local/bin/pip3 /usr/local/bin/pip
```
Now, when you run the python command, it should invoke Python 3.x, and when you run the pip command, it should invoke pip3

**Comment by UlrichThiess** [comment]
Just ask Chat-GPT.

"How could i run Python with the command 'python' instead of 'python3'?

**Comment by blizzard25** [comment]
There's a much simpler solution to this.

`sudo apt install python-is-python3`

Install and everything works

**Comment by Raven2905** [comment]
In the Auto-GPT Folder. Go down to "run.sh" in there, go to line 2 and line 8 and switch "python" to "python3" and in line 6 switch "pip" to "pip3"

**Comment by tctdng** [comment]
> In the Auto-GPT Folder. Go down to "run.sh" in there, go to line 2 and line 8 and switch "python" to "python3" and in line 6 switch "pip" to "pip3"

thanks you , I did it

**Comment by Yakelixir** [comment]
Changes to pip3 and python3 confirmed. Works

**Comment by AdamDudley** [comment]
changed pip to pip3 and python to python3 fixed for me too.

**Comment by Jaryllim98** [comment]
hi how do i resolve this issue? somehow still doesnt seem to work?

  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/venv/__init__.py", line 31, in should_use_symlinks
    raise Exception("This build of python cannot create venvs without using symlinks")
Exception: This build of python cannot create venvs without using symlinks
❌ There was an issue with the installation.
