### ISSUE TITLE
wrong sponsor logo

### ISSUE THREAD

**Issue by founderblocks-sils** [Significant-Gravitas/Auto-GPT#2999]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

I'm not personally sponsoring this repository, but my company FounderBlocks is.

1. Check the readme

### Current behavior 😯

my personal profile is highlighted

### Expected behavior 🤔

https://founderblocks.io/ should be highlighted as it's the actual sponsor

here's a link for the logo including transparency: https://founderblocks.io/images/founderblocks_logotext_anim.webp

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by Torantulino** [comment]
Hi @founderblocks-sils 
Let's resolve this over email, check your inbox :)
