### ISSUE TITLE
th AI only Thinking.. wtih no results

### ISSUE THREAD

**Issue by ahmedmoemen** [Significant-Gravitas/Auto-GPT#3003]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

send here

### Current behavior 😯

AI stock here Using memory of type:  LocalCache
Using Browser:  chrome
more here: https://github.com/Significant-Gravitas/Auto-GPT#openai-api-keys-configuration
\ Thinking... 

with no results

### Expected behavior 🤔

help me solve it

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by raczy07** [comment]
I am getting the same thing. Any help would be greatly appreciated

**Comment by FlamingFury00** [comment]
Have you set up a payment method in your OpenAi account to use the GPT-4 model? You can't use GPT-4 for free.

**Comment by k-boikov** [comment]
Duplicate https://github.com/Significant-Gravitas/Auto-GPT/issues/2169
