### ISSUE TITLE
ModuleNotFoundError: No module named 'selenium.webdriver.safari.options'

### ISSUE THREAD

**Issue by mohammadmaso** [Significant-Gravitas/Auto-GPT#3005]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

Safari Options was a known bug for Selenium 4 for Py.
This has been resolved - [Py safari options #10385](https://github.com/SeleniumHQ/selenium/pull/10385)
This was merged into release 4.1.3 for Py, update your Selenium version to 4.1.3 or 4.1.4 to resolve the issue.

### Current behavior 😯

ModuleNotFoundError: No module named 'selenium.webdriver.safari.options'

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by tyler-potter** [comment]
Having this exact issue as well.

**Comment by tyler-potter** [comment]
I had this error as well. I fixed it by downgrading my Selenium library to 4.1.4.

**Comment by cannacak** [comment]
If you trying to install auto-gpt, I recommend you to create a new environment and execute requirement.txt file.This was the way I solved the issue.
