### ISSUE TITLE
Add: proxy-server for chrome

### ISSUE THREAD

**Issue by twinsant** [Significant-Gravitas/Auto-GPT#3008]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

I have hacked the web_selenium.py to support proxy-server.

<img width="1365" alt="image" src="https://user-images.githubusercontent.com/299586/233837695-0627781a-c02d-403f-b646-4a093f314667.png">

<img width="1402" alt="image" src="https://user-images.githubusercontent.com/299586/233837715-258c8819-6bbb-477d-94dc-d5998f491517.png">

### Examples 🌈

Add this line to .env:

PROXY_SERVER=socks5://127.0.0.1:9999

### Motivation 🔦

So the selenium browser will work.

**Comment by k-boikov** [comment]
Do you have a PR?
