### ISSUE TITLE
Github API Integration

### ISSUE THREAD

**Issue by timbrunette** [Significant-Gravitas/Auto-GPT#301]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Is there any plan to develop a github integration API so relevant code changes (e.g. if we are getting Auto-GPT to CRUD code) that it can automatically push it to a remote repo, and open a PR?

### Examples 🌈

https://twitter.com/mckaywrigley/status/1641204093074145281?s=20

### Motivation 🔦

Write the code, push the code.

Extension would be then playing adversarial role as PR reviewer wearing different 'hats' (e.g. I am a security orientated agent, I am a test orientated agent, I care about code quality etc etc)

**Comment by Qoyyuum** [comment]
Duplicate to #280 . Closing.
