### ISSUE TITLE
Stable 0.2.2 Command browse_website returned Error

### ISSUE THREAD

**Issue by gregko** [Significant-Gravitas/Auto-GPT#3017]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

Running on Windows 11 [Version 10.0.22621.1631], python 3.11.3. Asked to design a modern website template for my small software business. It tried to browse my website and gave me this error.

### Current behavior 😯

Every time it tries to browse website, this error pops up:

2023-04-23 08:43:36,523 INFO NEXT ACTION:  COMMAND = browse_website  ARGUMENTS = {'url': 'http://hyperionics.com/', 'question': 'What are the main products and services offered by Hyperionics Technology?'}
2023-04-23 08:43:51,271 INFO SYSTEM:  Command browse_website returned: Error: Message: 
Stacktrace:
Backtrace:
	GetHandleVerifier [0x0060DCE3+50899]
	(No symbol) [0x0059E111]
	(No symbol) [0x004A5588]
	(No symbol) [0x004D08F9]
	(No symbol) [0x004D0AFB]
	(No symbol) [0x004FF902]
	(No symbol) [0x004EB944]
	(No symbol) [0x004FE01C]
	(No symbol) [0x004EB6F6]
	(No symbol) [0x004C7708]
	(No symbol) [0x004C886D]
	GetHandleVerifier [0x00873EAE+2566302]
	GetHandleVerifier [0x008A92B1+2784417]
	GetHandleVerifier [0x008A327C+2759788]
	GetHandleVerifier [0x006A5740+672048]
	(No symbol) [0x005A8872]
	(No symbol) [0x005A41C8]
	(No symbol) [0x005A42AB]
	(No symbol) [0x005971B7]
	BaseThreadInitThunk [0x76077D59+25]
	RtlInitializeExceptionChain [0x777DB74B+107]
	RtlClearBits [0x777DB6CF+191]

### Expected behavior 🤔

No error, just continue processing...

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by k-boikov** [comment]
Does it fail on all browse_website commands?

**Comment by gregko** [comment]
It says something like "since browse failed, let's try what Google says" and seems to return some results from a Google search. Not sure if it uses the same browser. Then it tries again to access my website with the same error, seems to be looping. My business website uses frames (very, very old design), could this be the reason?

**Comment by wosyoo** [comment]
I have meet the same question
