### ISSUE TITLE
pls help me install auto-gpt

### ISSUE THREAD

**Issue by Panepitter** [Significant-Gravitas/Auto-GPT#3022]
hi, i'm new to this world and i'm having issues installing auto-gpt properly. I need a step by step help from anyone that could be so kind to follow me through this. i'm really patient and i have some basic knowledge of the subject. hope to recive some help pls :P

**Comment by SparksSkywere** [comment]
Have you checked the documentation?: https://github.com/Significant-Gravitas/Auto-GPT/blob/master/docs/installation.md

> hi, i'm new to this world and i'm having issues installing auto-gpt properly. I need a step by step help from anyone that could be so kind to follow me through this. i'm really patient and i have some basic knowledge of the subject. hope to recive some help pls :P

**Comment by markgoho** [comment]
use the codespaces setup, it's a one-click setup

**Comment by Panepitter** [comment]
> Have you checked the documentation?: https://github.com/Significant-Gravitas/Auto-GPT/blob/master/docs/installation.md
> 
> > hi, i'm new to this world and i'm having issues installing auto-gpt properly. I need a step by step help from anyone that could be so kind to follow me through this. i'm really patient and i have some basic knowledge of the subject. hope to recive some help pls :P

yeah i tried everything but i encounter problems continiously

**Comment by Panepitter** [comment]
> use the codespaces setup, it's a one-click setup

tyvm i'm gonna try, any advide on how to set up the codespace for autogpt and how to use it? ty again!

**Comment by k-boikov** [comment]
Please read the Installation guide https://github.com/Significant-Gravitas/Auto-GPT/blob/master/docs/installation.md If you encounter an error - post a proper bug report following the template.
