### ISSUE TITLE
Add support for more web broswers.

### ISSUE THREAD

**Issue by liyanes** [Significant-Gravitas/Auto-GPT#3027]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Now it only support Chrome, Firefox and Safari.
I need more support, such as Edge and Opera.

### Motivation 🔦

Selenium support them and can be written like the Chrome.

**Comment by yayafengzi** [comment]
i agree with you

**Comment by hdkiller** [comment]
#3058 will add edge support if gets merged
