### ISSUE TITLE
Improve reasoning based on web data

### ISSUE THREAD

**Issue by guyweissman** [Significant-Gravitas/Auto-GPT#3029]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

I've been trying AutoGPT and I think we can improve the reasoning behind using web data. This is meant to address the issue of poor data quality on the Internet. Right now I've encountered the following actions:
-If the first article returned isn't relevant, a different query is formed
-The first result is often used to develop new tasks

But as well know, a lot of the top content on the internet is low quality / commercial, so shouldn't be relied on.

I suggest to add the following reasoning:
-Use first N results for making decisions (N configurable)
-For these N results, use ChatGPT to assess the quality of the data on 1-10. Results that show a low score are removed

### Motivation 🔦

I think this will make the connection to web browsing incredibly more powerful, and also save on API calls because there will be less in depth analysis of low quality data.

**Comment by Boostrix** [comment]
there also is the issue of requiring cookies/user interaction or so called "paywalls" - basically, a source like wikipedia is "better" (=more accessible) than a source like medium due to these issues. That also applies to highly dynamic webpages using tons of AJAX/JavaScript etc
