### ISSUE TITLE
Support EdgeGPT

### ISSUE THREAD

**Issue by iamashwin99** [Significant-Gravitas/Auto-GPT#3038]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Is there any plan to support non openAI APIs for eg [EdgeGPT](https://github.com/acheong08/EdgeGPT)

### Motivation 🔦

If this is enabled, we could make use of other LLM as backends for prompt replies. EdgeGPT for eg is free and uses GPT 4 internally and the example repo is an unofficial API for the same.

**Comment by k-boikov** [comment]
I am not sure, but I think EdgeGPT might be against some TOS.

**Comment by iamashwin99** [comment]
But some other LMs like WizardLM,  LLaMA, Alpaca etc could be used. so an interface to connect to other LLM could be useful

**Comment by blackthunder101** [comment]
Hey just letting you guys know about: https://github.com/Significant-Gravitas/Auto-GPT-Plugins/pull/93 
BingAI and Web Interaction #93 it's still in the pull request phase but I'm playing around with it and it does seem to be able to Bing which itself is using ChatGPT4

**Comment by gravelBridge** [comment]
yep! lemme know if you have any questions!

**Comment by Boostrix** [comment]
related to #2158
