### ISSUE TITLE
Wikidata Query support

### ISSUE THREAD

**Issue by stefangrotz** [Significant-Gravitas/Auto-GPT#304]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Right now I am experimenting with a Wikidata Query command in auto-gpt on my repo: https://github.com/stefangrotz/Auto-GPT-Wikidata

Feel free to join!

Once this works well I can create a pull request and add this functionality to this repo. Would this make sense to you? 

At one point some sort of plugin system will be inevitable, but Wikidata could be usefull enought to become part of the main system since it gives you acces to all kind of data in a structured way. This includes lists of API endpoints of Open Data CKAN Portals and many other useful data that is hard to find just using google.

### Examples 🌈

Here is an example how this can look:
![image](https://user-images.githubusercontent.com/5982239/230336137-f8dc6707-2a45-42ab-a745-2ca4c6419e36.png)

### Motivation 🔦
Wikidata ftw

**Comment by stefangrotz** [comment]
Propably obsolete because of the REST API functionality on https://github.com/Torantulino/Auto-GPT/pull/765

**Comment by Qoyyuum** [comment]
Would work best as a plugin though.

**Comment by jnt0rrente** [comment]
@stefangrotz are you still working on this? your repo seems a bit dead - I could give this a go.

**Comment by stefangrotz** [comment]
I wanted to wait until auto-gpt doesn't change so dynamically anymore because it was hard to keep synced with the main project. Feel free to give it a go, I don't habe much time this week. If you like you can also get rights for my repo.

**Comment by jnt0rrente** [comment]
I'll start working on this later, then. Thanks, but I prefer to clean fork this myself.

**Comment by jnt0rrente** [comment]
As for making this a plugin, @Qoyyuum in my opinion wikidata is general-purpose enough and well-established enough to be a "core" functionality, since google is not always the best source of truth. Open to discussion, though.

**Comment by stefangrotz** [comment]
Is there a plugin functionality for auto-gpt yet?

**Comment by stefangrotz** [comment]
It looks like [AgentGPT ](https://agentgpt.reworkd.ai/)is already capable to do Wikidata Queries:

![image](https://user-images.githubusercontent.com/5982239/234240885-eda9354d-9f9a-4cb1-9fc6-aaee64ecc769.png)

But it doesn't show any details of the call, so it could also be hallucinating.
