### ISSUE TITLE
PIP Error during installation

### ISSUE THREAD

**Issue by AlexNetman** [Significant-Gravitas/Auto-GPT#3041]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

`pip install -r requirements.txt` gives this:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mindflow 0.3.16 requires openai==0.27.0, but you have openai 0.27.2 which is incompatible.
mindflow 0.3.16 requires tiktoken==0.3.0; python_version >= "3.8", but you have tiktoken 0.3.3 which is incompatible.
flask 1.1.4 requires click<8.0,>=5.1, but you have click 8.1.3 which is incompatible.

### Current behavior 😯

error

### Expected behavior 🤔

no error expected

### Your prompt 📝

```yaml
before prompt
```

### Your Logs 📒

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mindflow 0.3.16 requires openai==0.27.0, but you have openai 0.27.2 which is incompatible.
mindflow 0.3.16 requires tiktoken==0.3.0; python_version >= "3.8", but you have tiktoken 0.3.3 which is incompatible.
flask 1.1.4 requires click<8.0,>=5.1, but you have click 8.1.3 which is incompatible.

**Comment by mikehnta00** [comment]
Is this an autoGPT error or a pip error?

**Comment by AlexNetman** [comment]
pip

**Comment by mikehnta00** [comment]
From my limited understanding of all this, it seems like the requirements doc is working as intended. Pip should be handling the error above.

Are you using the latest version of pip?

**Comment by k-boikov** [comment]
Please use Python 3.10 or higher and a venv if you need other specific version of packages for other projects.

**Comment by AlexNetman** [comment]
Thanks @k-boikov 
I was using Python 3.8 . 
OK. I see now that minimum requirement is 3.10.
Though basic functionality was fine for me in 3.8 even with those notices during installation.
