### ISSUE TITLE
 Line 45 configurator.py CFG.set_speak_mode(True) set True as default

### ISSUE THREAD

**Issue by PaulShroom** [Significant-Gravitas/Auto-GPT#3043]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

 Line 45 configurator.py CFG.set_speak_mode(False) set "True" as default on first use. As I had no tts and this would have been good to have on to stop me from going crazy thinking something was wrong with my installation.

### Current behavior 😯

no tts Line 45 configurator.py CFG.set_speak_mode(False)

### Expected behavior 🤔

Line 45 configurator.py CFG.set_speak_mode(True) tts on

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by k-boikov** [comment]
![image](https://user-images.githubusercontent.com/64261260/233865221-323ec9a1-ec3a-4ba9-b947-9de4985e2cb4.png)
Speak is off by default, you can turn it on with the --speak flag.
