### ISSUE TITLE
when running on Kali linux will get error: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by r4zmuz** [Significant-Gravitas/Auto-GPT#3052]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Other (Please specify in your problem)

### Which version of Auto-GPT are you using?

Master (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

when running first time on kali linux if there is nothing saved inside ai_setting.yaml.

### Current behavior 😯

Exception has occurred: AttributeError
'NoneType' object has no attribute 'get'
  File "/media/kali/4b9de0e2-9707-470a-a3e1-2d9ecd620795/python_projects/AutoGPT/Auto-GPT/autogpt/config/ai_config.py", line 67, in load
    ai_name = config_params.get("ai_name", "")
              ^^^^^^^^^^^^^^^^^
  File "/media/kali/4b9de0e2-9707-470a-a3e1-2d9ecd620795/python_projects/AutoGPT/Auto-GPT/autogpt/prompt.py", line 173, in construct_prompt
    config = AIConfig.load(CFG.ai_settings_file)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/kali/4b9de0e2-9707-470a-a3e1-2d9ecd620795/python_projects/AutoGPT/Auto-GPT/autogpt/cli.py", line 126, in main
    system_prompt = construct_prompt()
                    ^^^^^^^^^^^^^^^^^^
  File "/media/kali/4b9de0e2-9707-470a-a3e1-2d9ecd620795/python_projects/AutoGPT/Auto-GPT/run_autogpt.py", line 4, in <module>
    __main__.autogpt.cli.main()
AttributeError: 'NoneType' object has no attribute 'get'

### Expected behavior 🤔

It should not throw an error but error should be handled without exiting application.

here is one possible quick fix for it.

in directory: autogpt/ai_config.py

```diff
-    ai_name = config_params.get("ai_name", "")
-    ai_role = config_params.get("ai_role", "")
-    ai_goals = config_params.get("ai_goals", [])
-    return AIConfig(ai_name, ai_role, ai_goals)
+ try:
+            ai_name = config_params.get("ai_name", "")
+            ai_role = config_params.get("ai_role", "")
+            ai_goals = config_params.get("ai_goals", [])
+        except AttributeError:
+            ai_name = ""
+            ai_role = ""
+            ai_goals = []
+        finally:
+            # type: Type[AIConfig]
+            return AIConfig(ai_name, ai_role, ai_goals)
```

### Your prompt 📝

```yaml
# this file is also empty
```

### Your Logs 📒

```log
# this error is not showing here. this file is empty
```

**Comment by jackvargo** [comment]
I have the same issue running with MAcbook M1 via the docker instructions from the setup documentation, fresh install as of today.  MacOS 12.4, Docker Desktop v4.9.1 (updating soon).  
Could just be a documentation update for setup instructions for us newbs is to provide more explicit listing of the Configuration files required and their location to create before running the image.
