### ISSUE TITLE
 Command browse_website returned: Error: Sentence is too long in webpage: 7707 tokens.

### ISSUE THREAD

**Issue by Jl159598** [Significant-Gravitas/Auto-GPT#3069]
Command browse_website returned: Error: Sentence is too long in webpage: 7707 tokens.

**Comment by k-boikov** [comment]
Please reopen your issue following the template.

**Comment by Jl159598** [comment]
I’m new to this so I’m not sure what you’re direction mean.On Apr 23, 2023, at 9:06 PM, k-boikov ***@***.***> wrote:﻿
Please reopen your issue following the template.
