### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by learning2deve** [Significant-Gravitas/Auto-GPT#3070]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

How to fix the error

Auto-GPT/autogpt/api_manager.py", line 31, in ApiManager
    model: str | None = None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

when run "bash run.sh"? Thanks alot.

### Current behavior 😯

How to fix the error

Auto-GPT/autogpt/api_manager.py", line 31, in ApiManager
    model: str | None = None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

when run "bash run.sh"? Thanks alot.

### Expected behavior 🤔

How to fix the error

Auto-GPT/autogpt/api_manager.py", line 31, in ApiManager
    model: str | None = None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

when run "bash run.sh"? Thanks alot.

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by Dimosts** [comment]
You need python3.10 in order to run it. In case you do not have it, you need to install it. In case you have it and it is not the default, you should run python3.10 -m autogpt

**Comment by k-boikov** [comment]
This is a setup error, I’m sorry but we don’t have the resources to help everyone fix their setups. Join the discord and use the #tech-support channel to get help

**Comment by JStormrage** [comment]
Use Python versions 3.10, 3.11 and it will not error out.

**Comment by gregazbill** [comment]
this issue cropped up after my latest git pull when it was working fine before - Linux mint, python 3.10.6
python3.10 -m autogpt solved it.

**Comment by kevinAndreazza** [comment]
> You need python3.10 in order to run it. In case you do not have it, you need to install it. In case you have it and it is not the default, you should run python3.10 -m autogpt

i did it and is not functional rturn another error ModuleNotFoundError: No module named 'dotenv' i will explore other issue

**Comment by rammohan-PMCPL** [comment]
default: T | UndefinedType = Undefined,
TypeError: unsupported operand type(s) for |: 'TypeVar' and 'type'

how to fix this issue in ubuntu
