### ISSUE TITLE
start autogpt from master branch with any plugin seem doesent work

### ISSUE THREAD

**Issue by SimDamDev** [Significant-Gravitas/Auto-GPT#3071]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Master (branch)

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

have any plugin in plugin folder
start autogpt

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

 python -m autogpt
NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here. If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
WARNING:  You are running on `master` branch - this is not a supported branch.
WARNING: Plugin AutoGPTDollyPlugin found. But not in the allowlist... Load? (y/n): y

Plugins found: 1
--------------------
Auto-GPT-Dolly-Plugin: 0.1.0 - This plugin adds a 'create_clone' command that lets Auto-GPT build an army of powerful minions.
Welcome back!  Would you like me to return to being LMMGPT?
Continue with the last settings?
Name:  LMMGPT
Role:  an AI assistant that guides users through the process of adding a local LMM model to AutoGPT, providing step-by-step instructions and troubleshooting support.
Goals: ['Provide clear and concise instructions for installing and setting up the necessary software and dependencies required for adding a local LMM model to AutoGPT.', 'Guide users through the process of preparing their data and fine-tuning the LMM model to ensure optimal performance and accuracy.', 'Offer troubleshooting support and solutions for common issues that may arise during the process of adding a local LMM model to AutoGPT.', 'Provide ongoing support and updates to ensure that the LMM model remains up-to-date and continues to perform optimally.', 'Ensure that users have a thorough understanding of the process and are able to successfully add a local LMM model to AutoGPT on their own.']
API Budget: infinite
Continue (y/n): y
LMMGPT  has been created with the following details:
Name:  LMMGPT
Role:  an AI assistant that guides users through the process of adding a local LMM model to AutoGPT, providing step-by-step instructions and troubleshooting support.
Goals:
-  Provide clear and concise instructions for installing and setting up the necessary software and dependencies required
 for adding a local LMM model to AutoGPT.
-  Guide users through the process of preparing their data and fine-tuning the LMM model to ensure optimal performance and accuracy.
-  Offer troubleshooting support and solutions for common issues that may arise during the process of adding a local LMM model to AutoGPT.
-  Provide ongoing support and updates to ensure that the LMM model remains up-to-date and continues to perform optimally.
-  Ensure that users have a thorough understanding of the process and are able to successfully add a local LMM model to AutoGPT on their own.
Using memory of type:  PineconeMemory
Using Browser:  chrome
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\simon\OneDrive\Documents\GitHub\Auto-GPT\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\Users\simon\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\simon\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\simon\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\simon\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\simon\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\simon\AppData\Roaming\Python\Python311\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\simon\OneDrive\Documents\GitHub\Auto-GPT\autogpt\cli.py", line 174, in main
    system_prompt = ai_config.construct_full_prompt()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\simon\OneDrive\Documents\GitHub\Auto-GPT\autogpt\config\ai_config.py", line 142, in construct_full_prompt
    prompt_generator = plugin.post_prompt(prompt_generator)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins\AutoGPTDolly.zip\src\auto_gpt_plugin_template\__init__.py", line 48, in post_prompt
  File "plugins\AutoGPTDolly.zip\src\auto_gpt_plugin_template\dolly.py", line 4, in <module>
ImportError: cannot import name 'path_in_workspace' from 'autogpt.workspace' (C:\Users\simon\OneDrive\Documents\GitHub\Auto-GPT\autogpt\workspace\__init__.py)

**Comment by ntindle** [comment]
@BillSchumacher ?
