### ISSUE TITLE
python: can't open file 'D:\\AI\\Auto-GPT\\Auto-GPT\\scripts\\main.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by YassinKhalil** [Significant-Gravitas/Auto-GPT#3075]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

1- Git installed and Python 3.10.10 (exe path allowed)
cmd from folder directory:
git clone https://github.com/Significant-Gravitas/Auto-GPT.git
pip install -r requirements.txt
(Pinecone-region/Apikey edited in .env)
python scripts/main.py
2- and then i tried python -m autogpt

### Current behavior 😯

1- python: can't open file 'D:\\AI\\Auto-GPT\\Auto-GPT\\scripts\\main.py': [Errno 2] No such file or directory
2- Traceback (most recent call last):
  File "C:\Users\Yassin\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Yassin\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\AI\Auto-GPT\Auto-GPT\autogpt\__main__.py", line 2, in <module>
    import autogpt.cli
  File "D:\AI\Auto-GPT\Auto-GPT\autogpt\cli.py", line 2, in <module>
    import click
ModuleNotFoundError: No module named 'click'

D:\AI\Auto-GPT\Auto-GPT>

### Your prompt 📝

m

### Your Logs 📒

python: can't open file 'D:\\AI\\Auto-GPT\\Auto-GPT\\scripts\\main.py': [Errno 2] No such file or directory

**Comment by k-boikov** [comment]
This is a setup error, I’m sorry but we don’t have the resources to help everyone fix their setups. Join the discord and use the #tech-support channel to get help

**Comment by EstebanOD** [comment]
Following your instructions using commands provided on your website leads to this error
