### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by learning2deve** [Significant-Gravitas/Auto-GPT#3086]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

How to fix

" File "/usr/local/lib/python3.10/pathlib.py", line 960, in __new__
    self = cls._from_parts(args)
  File "/usr/local/lib/python3.10/pathlib.py", line 594, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/local/lib/python3.10/pathlib.py", line 578, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType"

when running "./run.sh"? Thanks a lot!

### Current behavior 😯

How to fix

" File "/usr/local/lib/python3.10/pathlib.py", line 960, in __new__
    self = cls._from_parts(args)
  File "/usr/local/lib/python3.10/pathlib.py", line 594, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/local/lib/python3.10/pathlib.py", line 578, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType"

when running "./run.sh"? Thanks a lot!

### Expected behavior 🤔

How to fix

" File "/usr/local/lib/python3.10/pathlib.py", line 960, in __new__
    self = cls._from_parts(args)
  File "/usr/local/lib/python3.10/pathlib.py", line 594, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/local/lib/python3.10/pathlib.py", line 578, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType"

when running "./run.sh"? Thanks a lot!

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by ntindle** [comment]
Hey can you give your specific os and versions of it? Linux seems to be having this error only

**Comment by learning2deve** [comment]
Linux; 5.4.0-1105-azure

**Comment by paryzhov** [comment]
I have the same issue but on Mac OS 13.1
<img width="872" alt="Screenshot 2023-04-23 at 8 31 42 PM" src="https://user-images.githubusercontent.com/46252747/233894096-6bdaa6fe-9452-4cb9-99da-35301ed97a1c.png">

**Comment by collijk** [comment]
Patch incoming shortly!

**Comment by collijk** [comment]
This should fix your issue: https://github.com/Significant-Gravitas/Auto-GPT/pull/3089.  Update to the latest master branch and try again.  Feel free to reopen this issue if you still have problems!

**Comment by learning2deve** [comment]
Linux; 5.4.0-1105-azure; So can you fix the error? Thanks.



> Hey can you give your specific os and versions of it? Linux seems to be having this error only
