### ISSUE TITLE
Please set your OpenAI API key in .env or as an environment variable. 

### ISSUE THREAD

**Issue by ronrevog** [Significant-Gravitas/Auto-GPT#3091]
I just updated to the latest stable codebase, and I place the openai key in the exact same place I had it before, and now im getting this error message. Any Ideas?

**Comment by mburak** [comment]
same here

**Comment by nigromancer69** [comment]
same

**Comment by ntindle** [comment]
Replace your .env with the one from the template and let me know if that fixes it

**Comment by nigromancer69** [comment]
It fixed the issue once I deleted the old .env and added the .env template
file that was extracted from the master version of autogpt. I had to change
my openai api key but afterwards it ran no problem.

**Comment by k-boikov** [comment]
This is a setup error, I’m sorry but we don’t have the resources to help everyone fix their setups. Join the discord and use the #tech-support channel to get help

**Comment by JeongMyeong** [comment]
same here.
![image](https://user-images.githubusercontent.com/44393016/233941336-2aecd6e6-7649-42fd-8b35-2bf9a26cd0ec.png)
I have already set my valid OpenAI API key

**Comment by Anhmarukita123** [comment]
C:\Users\Anh\babyagi> python babyagi.py
Traceback (most recent call last):
  File "C:\Users\Anh\babyagi\babyagi.py", line 33, in <module>
    assert OPENAI_API_KEY, "\033[91m\033[1m" + "OPENAI_API_KEY environment variable is missing from .env" + "\033[0m\033[0m"
AssertionError: OPENAI_API_KEY environment variable is missing from .env(I have already set my valid OpenAI API key
I'm using the latest repo}
