### ISSUE TITLE
Trackback issue upon installation

### ISSUE THREAD

**Issue by uditgoenka** [Significant-Gravitas/Auto-GPT#3113]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

I am getting the following error upon installation of Auto-gpt on my macOS

--

`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/uditgoenka/Auto-GPT/autogpt/__main__.py", line 2, in <module>
    import autogpt.cli
  File "/Users/uditgoenka/Auto-GPT/autogpt/cli.py", line 2, in <module>
    import click
ModuleNotFoundError: No module named 'click'
uditgoenka@uditgoenkaco auto-gpt % 
`

I have tried all the possible solutions but nothing seems to be working. Any help will be appreciated. 

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by hdkiller** [comment]
Try starting it with ./run.sh to install the missing dependencies with pip.
