### ISSUE TITLE
The file 'auto-gpt.json' does not exist

### ISSUE THREAD

**Issue by MdSaib** [Significant-Gravitas/Auto-GPT#3115]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

![image](https://user-images.githubusercontent.com/61196431/233964726-a5511339-8e88-472e-a881-5279eec7a6f8.png)

### Current behavior 😯

Perhaps, I need The file 'auto-gpt.json' that does not exist. 

I am a beginner, pardon me.

### Expected behavior 🤔

I wish when I run the commandline "python -m autogpt", it will proceed further.

### Your prompt 📝

```yaml
E:\ai\autoGPT\Auto-GPT-stable>python -m autogpt
Warning: The file 'auto-gpt.json' does not exist. Local memory would not be saved to a file.

### Your Logs 📒

```log
<System haven't run yet. So, their is no log.>
```

**Comment by faha1999** [comment]
i'm facing same issue in fedora 38

**Comment by NiceTryGuyPython** [comment]
That's not the issue. The system will run without the json file. Your real problem is the red text underneath that, which is that your OpneAI API key is not set in your .env file.

**Comment by MdSaib** [comment]
> That's not the issue. The system will run without the json file. Your real problem is the red text underneath that, which is that your OpenAI API key is not set in your .env file. 

Thanks for pointing out the actual problem. I will try accordingly.
