### ISSUE TITLE
Financial Data Pull

### ISSUE THREAD

**Issue by Jl159598** [Significant-Gravitas/Auto-GPT#3127]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Need the system to be able to read SEC Financial Statements and not be limited because of a token limitation. 

### Examples 🌈

Not limited to token read.

### Motivation 🔦

The SEC Edgar website has a lot of financial data, but the AI is limited to how much it can read.

**Comment by k-boikov** [comment]
Unfortunately that is not up to Auto GPT.
