### ISSUE TITLE
Relative module names not supported

### ISSUE THREAD

**Issue by zc994646659** [Significant-Gravitas/Auto-GPT#3135]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

How to solve "Relative module names not supported" error when running "python -m autogpt" on Windows after following the installation steps? The error message is "C:\Users\99464\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe: Relative module names not supported".

### Current behavior 😯

Cannot run autogpt despite installing the necessary dependencies

### Expected behavior 🤔

the autoGPT will run successfully

### Your prompt 📝

```yaml
# Paste your prompt here
```
 python .\main.py
Traceback (most recent call last):
  File "C:\Users\99464\tools\Auto-GPT-master\main.py", line 1, in <module>
    from autogpt import main
ImportError: cannot import name 'main' from 'autogpt' (C:\Users\99464\tools\Auto-GPT-master\autogpt\__init__.py)
PS C:\Users\99464\tools\Auto-GPT-master> python -m .\autogpt\
C:\Users\99464\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe: Relative module names not supported

### Your Logs 📒

```log
<insert your logs here>
``

**Comment by k-boikov** [comment]
This is a setup error, I’m sorry but we don’t have the resources to help everyone fix their setups. Join the discord and use the #tech-support channel to get help.
