### ISSUE TITLE
Implement better website navigation and parsing

### ISSUE THREAD

**Issue by glenviewjeff** [Significant-Gravitas/Auto-GPT#3136]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

AutoGPT should be able to parse website elements, as well as directly interact with the website. As of now `web_selenium.py` can only scrape text and links from each page. It should be able to, for instance, scrape buttons and click them, or fields and fill them. Ideally AutoGPT would figure all of this out and write and maintain code that does it. I tried coaxing it to do this without success.

### Examples 🌈

Example goal: find the cheapest round-trip flight from New York to Paris leaving May 1 and returning May 10. Flights should be direct and departing during typical waking hours.

### Motivation 🔦

Better interact with websites, use GUI elements, fill forms, etc.

**Comment by tenghanc** [comment]
how did you even get it to surf the web ...can it do google search?

**Comment by glenviewjeff** [comment]
> how did you even get it to surf the web ...can it do google search?

Yes but you should post this in Q&A, not in an issue comment. I take it you have not yet tried using the tool. Accessing websites is one of its core behaviors.

**Comment by ntindle** [comment]
This is a little bit advanced for the goals of that particular unit of code. If you want to give a shot at adding it, please open a pr but otherwise closing in favor of older issues that are duplicates
