### ISSUE TITLE
clone_repository returning error, fatal: could not create leading directories of /home/user/.../ : Permission denied

### ISSUE THREAD

**Issue by NiceTryGuyPython** [Significant-Gravitas/Auto-GPT#3137]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

Requested auto-gpt clone a repository and access it's information. An access token has been generated and granted. Also, I've set the settings in the .env file. 
EXECUTE_LOCAL_COMMANDS=True
RESTRICT_TO_WORKSPACE=False

### Current behavior 😯

It attempts to clone the repository and seems to run into trouble accessing the working directory. 
SYSTEM:  Command clone_repository returned: Error: Cmd('git') failed due to: exit code(128) cmdline: git clone -v -- https://*****:*****@github.com/NiceTryGuyPython/etc stderr: 'fatal: could not create leading directories of '/home/user/Folders_Name': Permission denied '

### Expected behavior 🤔

It should be capable of cloning the repo into the generated folder in the directory.

**Comment by mv2woods** [comment]
Same here
