### ISSUE TITLE
I suggest you to add Javascript files and more and PLEASE update the list of commands

### ISSUE THREAD

**Issue by AayushGoyal22** [Significant-Gravitas/Auto-GPT#3139]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

the list of commands are a huge limitation and its really annoying when all the processes are done and at last it says unkown commands and gets stuck there forever

### Motivation 🔦

it's hard because of the limited commands and the limitation to only run .py files

**Comment by ntindle** [comment]
Dupe
