### ISSUE TITLE
Any platform to share users' successful autogpt examples?

### ISSUE THREAD

**Issue by waterhorse1** [Significant-Gravitas/Auto-GPT#3141]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

I am wondering if there exist any plarforms, like sharegpt, for users to share their use case of autogpt?

**Comment by Mega4alik** [comment]
This platform has been for more than a year already - webapi.ai/

**Comment by k-boikov** [comment]
You can check our Discord. https://discord.gg/autogpt
