### ISSUE TITLE
Why does it always search the web when answering questions? It should only search the web very infrequently

### ISSUE THREAD

**Issue by 1nnovat1on** [Significant-Gravitas/Auto-GPT#3159]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

You should leverage the power of GPT-4 Much more, rather than having it spend time search the web. To get information, it should build specific programs and scripts, and store the information in the vector database. Then it should query itself with information from the vector database.

### Examples 🌈

USER -> GPT -> GPT -> GPT ->... until (WIN CONDITION = YES (a second GPT call that asks "does this response answer the question?")

### Motivation 🔦

It spends most of its time searching the web, and never gets to the solution in time.

**Comment by tenghanc** [comment]
I wish I have your problem...mine keeps giving google api key error when it is keyed into the env file.

**Comment by deWaardt** [comment]
I’m thinking of perhaps giving it a plugin that makes it talk to ChatGPT (GPT 3.5 API).

I know it can theoretically already do that using agents, but AutoGPT doesn’t really use agents like that. Perhaps by marking the plugin as specifically for research, it’s more likely to contact ChatGPT.

Ideally it’d leverage it’s own knowledge base as we know how much GPT knows, but I have no clue how I’d convince it to do that.

**Comment by khanfar** [comment]
When I ask question,  it ask me.to search from web , how to make it answer just through openai api ????
