### ISSUE TITLE
auto-gpt.json is not copied into the docker container

### ISSUE THREAD

**Issue by RoccoRakete** [Significant-Gravitas/Auto-GPT#3163]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Arch/Docker

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

Running AutoGPT in Docker.

### Current behavior 😯

Running AutoGPT in Docker gives there error of the missing "auto-gpt.json" file

 Warning: The file 'auto-gpt.json' does not exist. Local memory would not be saved to a file.

### Expected behavior 🤔

It should work, because the file is there and it works when running AutoGPT with the .sh script.

**Comment by lameTookan** [comment]
Same issue

**Comment by maad-maxx** [comment]
same issue

**Comment by philliplastcall** [comment]
create a blank 'auto-gpt.json' file

**Comment by Jiayi-S0809** [comment]
same issue

**Comment by NISPUK** [comment]
open your visual studio code and create the auto-gpt.json file there and not directly on your system than ask autogpt to look for the file with the search_file command if it finds it once it will find it again 

(im trying to remember how i fixed it but im at work and not on my pc)

**Comment by Martin1134** [comment]
> open your visual studio code and create the auto-gpt.json file there and not directly on your system than ask autogpt to look for the file with the search_file command if it finds it once it will find it again 
> 
> 
> 
> (im trying to remember how i fixed it but im at work and not on my pc)
> 
> 

Okay. I've created the file simply with "touch auto-gpt.json"

I will give this a try

**Comment by AramKoorn** [comment]
same issue

**Comment by Fasani** [comment]
I resolved this by doing the following (Mac OS, M1, Running docker):

**Create an empty file in the root folder:**
```
touch auto-gpt.json
```

Modify the **Dockerfile**, find this section:
```
# Copy the application files
COPY --chown=appuser:appuser autogpt/ ./autogpt
```
Add this:
```
# Copy auto-gpt.json
COPY --chown=appuser:appuser auto-gpt.json .
```

Errors goes away.

**Comment by Fasani** [comment]
Also at some point, you may want the content of the file, there may be other (better) ways, I am no docker expert but I did the following:

To get content out, when the container is still running you can do this:
```
docker container ls
```
This will give you the list of running containers. You need the container ID, eg:
```
CONTAINER ID         IMAGE
88576df5d5ab         auto-gpt-auto-gpt
```
Then you can do:
```
docker exec 88576df5d5ab cat auto-gpt.json | pbcopy
```
Then you can paste the content of the file into a new file in VSCode or similar.

**Comment by Pwuts** [comment]
Newest version will just use Redis instead of LocalCache when running in Docker. :)

**Comment by pranay16** [comment]
Is the latest version available on any branch?
Can we please close the issue only once it's available?

**Comment by Pwuts** [comment]
@pranay16 yes, `master`
