### ISSUE TITLE
Running docker-compose build auto-gpt fails when trying to install chromium-driver

### ISSUE THREAD

**Issue by mfcochauxlaberge** [Significant-Gravitas/Auto-GPT#3164]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

Clone repo, checkout at stable, master, or latest release (I tried v0.2.2).
Run `docker-compose build auto-gpt` or `docker build -t auto-gpt .`.

### Current behavior 😯

The build process fails when installing chromium-driver. For example on stable, it fails when running `RUN apt-get -y install git chromium-driver`. Refactoring this to two lines where the first line is for `git` and the second for `chromium-driver`, then the first line runs fine, but not the second.

It fails with the following error:

```
Selecting previously unselected package python3.9-minimal.
Preparing to unpack .../30-python3.9-minimal_3.9.2-1_amd64.deb ...
Unpacking python3.9-minimal (3.9.2-1) ...
Setting up libpython3.9-minimal:amd64 (3.9.2-1) ...
Setting up python3.9-minimal (3.9.2-1) ...
Traceback (most recent call last):
  File "/usr/lib/python3.9/py_compile.py", line 215, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/py_compile.py", line 207, in main
    compile(filename, doraise=True)
  File "/usr/lib/python3.9/py_compile.py", line 172, in compile
    importlib._bootstrap_external._write_atomic(cfile, bytecode, mode)
  File "<frozen importlib._bootstrap_external>", line 126, in _write_atomic
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.9/__pycache__/__future__.cpython-39.pyc.139876962836864'
dpkg: error processing package python3.9-minimal (--configure):
 installed python3.9-minimal package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 python3.9-minimal
E: Sub-process /usr/bin/dpkg returned an error code (1)
The command '/bin/sh -c apt-get -y install git chromium-driver' returned a non-zero code: 100
```

### Expected behavior 🤔

I expect the build to run without errors.

### Your prompt 📝

N/A

### Your Logs 📒

N/A

**Comment by mfcochauxlaberge** [comment]
I found a solution to my problem.

My setup was running Docker from Ubuntu using snap and the default storage engine is which `overlay2`. It turns out that there's an issue with installing `python3.9-minimal` with that storage engine.

An solution is to move to the `vfs` storage engine.

To accomplish that, edit `/var/snap/docker/current/config/daemon.json` and change `overlay2` with `vfs`. Then, restart the Docker daemon with `sudo snap restart docker`.

Note that I don't get any issue when installing `python3.10-minimal` with the default storage engine, so that problem might go away if whatever depends on `python3.9-minimal` upgrades to a newer version of Python.

Source: https://stackoverflow.com/a/75585238/1407735

**Comment by ericoschuch** [comment]
Hi @mfcochauxlaberge,

Thank you for sharing the solution regarding the chromium-driver installation issue when building auto-gpt with Docker. After running "docker system prune", your suggestion to change the storage engine from overlay2 to vfs worked perfectly.

**Comment by AJTEDOM** [comment]
i have the same issue im using a windows. please need help

**Comment by AJTEDOM** [comment]
is there a solution for non coders like us ?

**Comment by zyzykamarmag** [comment]
> i have the same issue im using a windows. please need help

I found a solution, after installing the linux subsystem you have to go into it and update the repositories 
`apt-get upgrade`
