### ISSUE TITLE
Scrape websites using Playwright.

### ISSUE THREAD

**Issue by carlosplanchon** [Significant-Gravitas/Auto-GPT#3165]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Since this is a technology more powerful that Selenium, I propose it as a feature to use on AutoGPT.

Playwright also support multiple browsers:
https://github.com/Significant-Gravitas/Auto-GPT/issues/3027

Some days ago I made a docker image which uses Playwright with an spoofed User-Agent, AdBlocking capabilities and a "stealthy" browser configuration. 

URLs:
https://hub.docker.com/repository/docker/carlosplanchon/playwright_splash/general
https://github.com/carlosplanchon/playwright_splash

Description:
Simple Playwright scraper which receives an URL and returns the website code.

### Examples 🌈

https://github.com/carlosplanchon/playwright_splash
https://hub.docker.com/repository/docker/carlosplanchon/playwright_splash/general

### Motivation 🔦

I made playwright_splash for a different use case, and I bring the solution here because I saw on Discord that you are also battling with this kind of problems.

**Comment by Rakoun** [comment]
Very Good Idea, Playwright is faster then selenium.
