### ISSUE TITLE
@validate_url truncates url search parameters

### ISSUE THREAD

**Issue by RoyalSWiSH** [Significant-Gravitas/Auto-GPT#3175]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of Auto-GPT are you using?

Master (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

When opening a URL with a search parameter, the parameter is truncated @validate_url.

### Current behavior 😯

When opening a url like `https://www.site.org/?query=<query>&view=cards` it just opens `https://www.site.org/`.

Removing  @validate_url in browse_website function in web_selenium.py resolves the issue. But a better way would be to improve the url validation.

### Expected behavior 🤔

When opening a url like `https://www.site.org/?query=<query>&view=cards` it should open `https://www.site.org/?query=parameter1&view=cards` to search the site.

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by Pwuts** [comment]
Fixed in #3370
