### ISSUE TITLE
[Errno 13] Permission denied: '../ai_settings.yaml'

### ISSUE THREAD

**Issue by 126-Gallons** [Significant-Gravitas/Auto-GPT#318]
Any time I set the goals (non speak), I encounter various errors. I have looked though the issues listed but not found a solution. 

Traceback (most recent call last):
  File "C:\Auto-GPT\scripts\main.py", line 275, in <module>
    prompt = construct_prompt()
             ^^^^^^^^^^^^^^^^^^
  File "C:\Auto-GPT\scripts\main.py", line 179, in construct_prompt
    config.save()
  File "C:\Auto-GPT\scripts\ai_config.py", line 31, in save
    with open(config_file, "w") as file:
         ^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '../ai_settings.yaml'

This has been the most common error.

Thanks

**Comment by kevzy** [comment]
> Any time I set the goals (non speak), I encounter various errors. I have looked though the issues listed but not found a solution.
> 
> Traceback (most recent call last): File "C:\Auto-GPT\scripts\main.py", line 275, in prompt = construct_prompt() ^^^^^^^^^^^^^^^^^^ File "C:\Auto-GPT\scripts\main.py", line 179, in construct_prompt config.save() File "C:\Auto-GPT\scripts\ai_config.py", line 31, in save with open(config_file, "w") as file: ^^^^^^^^^^^^^^^^^^^^^^ PermissionError: [Errno 13] Permission denied: '../ai_settings.yaml'
> 
> This has been the most common error.
> 
> Thanks

hey have you tried running the script as administrator

**Comment by dwrtz** [comment]
does it make a difference running from the scripts vs project root?

```
python scripts/main.py
```

or try

```
cd scripts
python main.py
```

I noticed that in the first case it tries to save ai_settings.yaml outside the project root directory. In your case this would be C:\ai_settings.yaml, and windows may prevent writing files here.

I believe this is a bug in determining the save path for ai_settings.yaml. The path should be relative to ai_config.py, but instead it's relative to the directory where python was launched.

**Comment by mindfu23** [comment]
I am also receiving this error.
I have already added both the pinecone region and pinecone API key to the renamed .env file, as per the instructions.

**Comment by Explorergt92** [comment]
@126-Gallons is this still an issue for you or can this be closed?

**Comment by souravjamwal77** [comment]
@Explorergt92 This is still an issue on Linux. Like if you are using a virtualenv then it's not working. Also, running the script as sudo could have devastating effects.
