### ISSUE TITLE
pre-commit with pytest-check failed

### ISSUE THREAD

**Issue by resduo** [Significant-Gravitas/Auto-GPT#3183]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Devcontainer / Codespace

### Which version of Auto-GPT are you using?

Master (branch)

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

1. Open folder in a Dev Container
2. `pip install black`
3. `pip install pre-commit`
4. Change content in docs/installation.md
5. `black .`
6. `git commit -m "your message"`

### Current behavior 😯

`pytest-check.............................................................Failed
- hook id: pytest-check
- exit code: 4

ImportError while loading conftest '/workspaces/Auto-GPT/tests/conftest.py'.
tests/conftest.py:4: in <module>
    from dotenv import load_dotenv
E   ModuleNotFoundError: No module named 'dotenv'`

### Expected behavior 🤔

pytest-check: Skipped

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by k-boikov** [comment]
Are you able to run autogpt with the run script?
