### ISSUE TITLE
AutoGPT in codespace

### ISSUE THREAD

**Issue by Bubble007** [Significant-Gravitas/Auto-GPT#3188]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Devcontainer / Codespace

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

I have installed Auto-GPT using the green "Code" button in codespace. But I can't figure out how to start Auto-GPT there now. I got as far as the terminal, but it doesn't go any further. I tried the usual commands like "run" or "python -m autogpt" or "shell" or "docker-compose run --rm auto-gpt", but they don't work. A button, as shown in a video, to start in the browser does not exist for me. 
Unfortunately I can't find any instructions for it anywhere.

### Current behavior 😯

a
AutoGPT doesn't start in codespace

### Expected behavior 🤔

AutoGPT starts in codespace

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by devlux76** [comment]
I just tried it, it's working fine, but you do actually have to have your OPENAI_API_KEY (and any other services you'll plan to use) set as a secret in your github user profile. You must also start it with ./run.sh and interact with it on the command line.

**Comment by wink** [comment]
> Thank you! I'm now one step forward. with the "./run.sh" comand.
> 
> But I don't get it, to save the OPENAI_API_KEY as a secret. I don't find the right way to it :-(

Check out Github docs for creating secrets to be injected into your codespace as environment variables.
https://docs.github.com/en/codespaces/managing-your-codespaces/managing-encrypted-secrets-for-your-codespaces
