### ISSUE TITLE
autogpt login

### ISSUE THREAD

**Issue by yyu77458** [Significant-Gravitas/Auto-GPT#3192]
After the operation is completed, autogpt needs to open the Google form to fill in the data, but it is not logged in by default after opening the browser, and the page shows that the autogpt analysis is in progress, and I cannot log in manually. How can I solve this problem?

**Comment by philliplastcall** [comment]
tell it to log in and give it a user name password

**Comment by Pwuts** [comment]
Please use (and fill out) the issue form for submitting issues
