### ISSUE TITLE
How to get GPT-4 API key

### ISSUE THREAD

**Issue by Xerizaf** [Significant-Gravitas/Auto-GPT#3197]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

I want to get an API key of GPT-4 but I don't know how.

### Examples 🌈

Please help me.

### Motivation 🔦

I want to create a software for biomedical engineers

**Comment by moose-iconstorm** [comment]
[Click Here](https://letmegooglethat.com/?q=how+to+get+api+for+gpt4).
