### ISSUE TITLE
Issue using clone_repository

### ISSUE THREAD

**Issue by aacostarua** [Significant-Gravitas/Auto-GPT#3204]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

Normal setup.  Gave local file write access and everything required in the env.  OpenAI Key etc.

### Current behavior 😯

Returns an error when trying to Git Clone anything.   Command clone_repository returned: Error: clone_repository() missing 1 required positional argument: 'url'

### Expected behavior 🤔

It should git clone as I am allowed to do this normally through command prompt.

### Your prompt 📝

Learning and writing code.  Can't clone anything so it stops.

### Your Logs 📒

 Command clone_repository returned: Error: clone_repository() missing 1 required positional argument: 'url'

**Comment by talkahe** [comment]
This issue is fixed in PR #3150
