### ISSUE TITLE
SSH to other server, after input password, auto-GPT stuck there

### ISSUE THREAD

**Issue by qiangziakbar** [Significant-Gravitas/Auto-GPT#3206]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux- Ubuntu 22.04

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

**use ssh to connect any server,** after user input password, or even let auto-GPT input password(tell GPT in Goal description), auto-GPT stuck there, 

EXECUTE_LOCAL_COMMAND=True
RESTRICT_TO_WORKSPACE=False

### Current behavior 😯

auto-GPT just stuck there, dont know what it doing, and even Crtl+z and Crtl+c dont work, seems GPT loop waiting something

### Expected behavior 🤔

after user input password, auto-GPT could connect the server, and work on that server

### Your prompt 📝

```yaml
# use ssh to connect server root@XXX.XXX.XXX.XXX (true IP address in prompt), I will input password
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by ntindle** [comment]
Letting autogpt execute commands on a remote server isn’t necessarily a use case I want to encourage right now. 

It also comes with a significant increase in complexity of hooking up all the logging/input/output and related and is probably the problem you were seeing. I’m going to close this as wontfix for now but feel free to create a plug-in and contribute it to https://github.com/Significant-Gravitas/Auto-GPT-Plugins if it’s something you absolutely need

**Comment by qiangziakbar** [comment]
Thank you!
let me see what I can do on this, I would like to do some research on remote server plug-in
