### ISSUE TITLE
Auto-GPT stuck on the same task - task ends in error, Auto-GPT starts over with the same task... (ver. 3,5) #2919

### ISSUE THREAD

**Issue by Khnaz35** [Significant-Gravitas/Auto-GPT#3211]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Docker

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

Run any goal and Auto-GPT will end up in loops. 

### Current behavior 😯

Stays forever in loop

### Expected behavior 🤔

Should kill the loop if its a dead end.

You can try testing on https://agentgpt.reworkd.ai/ and will see developer already thought of it.  

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by ntindle** [comment]
Sometimes it executes something unexpected or doesn’t do what you want.  Check out the #prompt-engineering channel in discord to get a better fit prompt

**Comment by paigerodeghero** [comment]
This consistently happens for me. I have not been able to complete any task because of this bug.  @ntindle @Khnaz35

**Comment by ntindle** [comment]
What version are you on? The newer versions should support Human in the Loop scenarios to tell it to do something else

**Comment by paigerodeghero** [comment]
thanks for the quick reply!

I'm on the newest version of stable
<img width="1114" alt="Screen Shot 2023-04-26 at 2 44 29 PM" src="https://user-images.githubusercontent.com/1682644/234672814-88b0641f-beaf-4919-a66a-e94c85cf659b.png">

**Comment by Khnaz35** [comment]
> Sometimes it executes something unexpected or doesn’t do what you want. Check out the #prompt-engineering channel in discord to get a better fit prompt

When i am trying to join the Discord i am seeing this screen.
<img width="594" alt="image" src="https://user-images.githubusercontent.com/43812103/234869340-75cb8496-73ab-4126-a490-3ba676ffbf3d.png">
