### ISSUE TITLE
Coding tools for Auto-GPT to use in the future.

### ISSUE THREAD

**Issue by SBerkeB** [Significant-Gravitas/Auto-GPT#3213]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

First of all AI is not my expertise. I really do not even have an amazing understanding of it. But I am trying to get good at it. So my situation is something like: I may not have a brain, gentlemen, but I have an idea. :D

The first time I tried to use Auto-GPT it had an issue with Twitter API, not sure if it was A-GPT's issue or mine. But I went through documentation of Tweepy and solved it by changing the send_tweet command a little. 

_**Then I came up with an idea, is there a way to code new files of python that A-GPT can use in the future.**_ 

For example a mail_sender code using AWS. What I want A-GPT to do is when I give a task including sending mails, AI uses my code to achieve mail sending goal. 

Not sure if this is possible with the current state of Auto-GPT or done before or has an easy explanation. But I really do not think that this is impossible...

**Comment by ntindle** [comment]
There is a plug-in for this! Check out the plugins repo! https://github.com/Significant-Gravitas/Auto-GPT-Plugins

**Comment by SBerkeB** [comment]
> There is a plug-in for this! Check out the plugins repo! https://github.com/Significant-Gravitas/Auto-GPT-Plugins

Thanks alot for advice🙏
