### ISSUE TITLE
openai.error.InvalidRequestError: This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?

### ISSUE THREAD

**Issue by zsmj610** [Significant-Gravitas/Auto-GPT#3215]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

1.  install anaconda
2. conda creat -n  new_env  python=3.10
3.  download the latest version auto-gpt
4.  configure the openai api_key
5. python -m autogpt
6. any question will lead the problem

### Your prompt 📝

```yaml
AI Name: testAI
testAI here!  I am at your service.
Describe your AI's role:  For example, 'an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.'
testAI is: an AI designed to autonomously make a product design
Enter up to 5 goals for your AI:  For example: Increase net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously'
Enter nothing to load defaults, enter nothing when finished.
Goal 1: Determine product direction
Goal 2: Sort out product features
Goal 3:
```

### Your Logs 📒

```log
Using memory of type:  LocalCache
Using Browser:  chrome
Traceback (most recent call last):
  File "D:\anaconda3\envs\auto_gpt\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\anaconda3\envs\auto_gpt\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\Auto-GPT-0.2.2\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "D:\anaconda3\envs\auto_gpt\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\anaconda3\envs\auto_gpt\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\anaconda3\envs\auto_gpt\lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "D:\anaconda3\envs\auto_gpt\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\anaconda3\envs\auto_gpt\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\anaconda3\envs\auto_gpt\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "E:\Auto-GPT-0.2.2\autogpt\cli.py", line 151, in main
    agent.start_interaction_loop()
  File "E:\Auto-GPT-0.2.2\autogpt\agent\agent.py", line 75, in start_interaction_loop
    assistant_reply = chat_with_ai(
  File "E:\Auto-GPT-0.2.2\autogpt\chat.py", line 159, in chat_with_ai
    assistant_reply = create_chat_completion(
  File "E:\Auto-GPT-0.2.2\autogpt\llm_utils.py", line 93, in create_chat_completion
    response = openai.ChatCompletion.create(
  File "D:\anaconda3\envs\auto_gpt\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "D:\anaconda3\envs\auto_gpt\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "D:\anaconda3\envs\auto_gpt\lib\site-packages\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "D:\anaconda3\envs\auto_gpt\lib\site-packages\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "D:\anaconda3\envs\auto_gpt\lib\site-packages\openai\api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?
```

**Comment by k-boikov** [comment]
Have you tried using some of the other methods to run it other that conda? Does it work?

**Comment by WangPeterXF** [comment]
i met same error. CMD under win 10

**Comment by WangPeterXF** [comment]
i met same error. CMD under win 10

> ### ⚠️ Search for existing issues first ⚠️
> * [x]  I have searched the existing issues, and there is no existing issue for my problem
> 
> ### Which Operating System are you using?
> Windows
> 
> ### Which version of Auto-GPT are you using?
> Latest Release
> 
> ### GPT-3 or GPT-4?
> GPT-3.5
> 
> ### Steps to reproduce 🕹
> 1. install anaconda
> 2. conda creat -n  new_env  python=3.10
> 3. download the latest version auto-gpt
> 4. configure the openai api_key
> 5. python -m autogpt
> 6. any question will lead the problem
> 
> ### Current behavior 😯
> _No response_
> 
> ### Expected behavior 🤔
> _No response_
> 
> ### Your prompt 📝
> ```yaml
> AI Name: testAI
> testAI here!  I am at your service.
> Describe your AI's role:  For example, 'an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.'
> testAI is: an AI designed to autonomously make a product design
> Enter up to 5 goals for your AI:  For example: Increase net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously'
> Enter nothing to load defaults, enter nothing when finished.
> Goal 1: Determine product direction
> Goal 2: Sort out product features
> Goal 3:
> ```
> 
> ### Your Logs 📒
> ```
> Using memory of type:  LocalCache
> Using Browser:  chrome
> Traceback (most recent call last):
>   File "D:\anaconda3\envs\auto_gpt\lib\runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "D:\anaconda3\envs\auto_gpt\lib\runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "E:\Auto-GPT-0.2.2\autogpt\__main__.py", line 5, in <module>
>     autogpt.cli.main()
>   File "D:\anaconda3\envs\auto_gpt\lib\site-packages\click\core.py", line 1130, in __call__
>     return self.main(*args, **kwargs)
>   File "D:\anaconda3\envs\auto_gpt\lib\site-packages\click\core.py", line 1055, in main
>     rv = self.invoke(ctx)
>   File "D:\anaconda3\envs\auto_gpt\lib\site-packages\click\core.py", line 1635, in invoke
>     rv = super().invoke(ctx)
>   File "D:\anaconda3\envs\auto_gpt\lib\site-packages\click\core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "D:\anaconda3\envs\auto_gpt\lib\site-packages\click\core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>   File "D:\anaconda3\envs\auto_gpt\lib\site-packages\click\decorators.py", line 26, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "E:\Auto-GPT-0.2.2\autogpt\cli.py", line 151, in main
>     agent.start_interaction_loop()
>   File "E:\Auto-GPT-0.2.2\autogpt\agent\agent.py", line 75, in start_interaction_loop
>     assistant_reply = chat_with_ai(
>   File "E:\Auto-GPT-0.2.2\autogpt\chat.py", line 159, in chat_with_ai
>     assistant_reply = create_chat_completion(
>   File "E:\Auto-GPT-0.2.2\autogpt\llm_utils.py", line 93, in create_chat_completion
>     response = openai.ChatCompletion.create(
>   File "D:\anaconda3\envs\auto_gpt\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
>     return super().create(*args, **kwargs)
>   File "D:\anaconda3\envs\auto_gpt\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
>     response, _, api_key = requestor.request(
>   File "D:\anaconda3\envs\auto_gpt\lib\site-packages\openai\api_requestor.py", line 226, in request
>     resp, got_stream = self._interpret_response(result, stream)
>   File "D:\anaconda3\envs\auto_gpt\lib\site-packages\openai\api_requestor.py", line 619, in _interpret_response
>     self._interpret_response_line(
>   File "D:\anaconda3\envs\auto_gpt\lib\site-packages\openai\api_requestor.py", line 682, in _interpret_response_line
>     raise self.handle_error_response(
> openai.error.InvalidRequestError: This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?
> ```

i met same error. CMD under win 10
