### ISSUE TITLE
Add email management to Auto-GPT

### ISSUE THREAD

**Issue by Kenshiro-28** [Significant-Gravitas/Auto-GPT#3221]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Adding an optional email account would allow sending and receiving emails, which would greatly increase the functionality of Auto-GPT.

### Examples 🌈

It looks it's easy to implement using Flask-Mail: 

https://pythonhosted.org/Flask-Mail/ 

### Motivation 🔦

Many websites require an e-mail account to login and use their services. Adding an optional e-mail account to Auto-GPT would allow it to use those services. Another utility could be a personal assistant that manages your own e-mail.

**Comment by k-boikov** [comment]
Have you checked this https://github.com/Significant-Gravitas/Auto-GPT-Plugins/tree/master/src/autogpt_plugins/email ?

**Comment by Kenshiro-28** [comment]
This plugin looks great! will it be included in next stable? :)

**Comment by k-boikov** [comment]
Yes, plugins are coming in next stable.
