### ISSUE TITLE
download_file fails when downloading to a folder that doesn't exist yet

### ISSUE THREAD

**Issue by garrettg123** [Significant-Gravitas/Auto-GPT#3249]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

After prompting to download a file to a folder, it runs the download_file command, but the directory doesn't exist.
```
System: Command download_file returned: Error: [Errno 2] No such file or directory: '/Users/me/Sites/Auto-GPT/autogpt/auto_gpt_workspace/2023-04-25/rss/cnn.xml'
```
It fails and eventually creates the directory, but this can be sped up by the download_file command to check that the directory exists, and create it if it doesn't yet.

**Comment by JPDucky** [comment]
I am experiencing this behavior as well. It will talk in circles saying "I am going to to run xyz" then I get back "file not found", where it then says something along the lines of "I apologize for the mistake. Here's the correct command to use:", rinse and repeat
