### ISSUE TITLE
"WARNING: You are running on master branch - this is not a supported branch"

### ISSUE THREAD

**Issue by aboda28** [Significant-Gravitas/Auto-GPT#3268]
"WARNING: You are running on master branch - this is not a supported branch"

its happend when i run autogpt i want to know how i can use  stable not master
i mean when i download the folder AUTO-GPT 0.2.2 iwill replace it with the old one or what to do ?

**Comment by aboda28** [comment]
ok i know it 
idid clone the master i need to replace it ? with the new one ? 
oneed to download the stable or i can clone it like master and if i can clone it where is the link ?

**Comment by KobiSteve07** [comment]
you can use this command: git clone https://github.com/Significant-Gravitas/Auto-GPT.git

**Comment by aboda28** [comment]
but this will download master one and this have problems how i can use stable one insted of master one?

**Comment by Scn64** [comment]
run "git checkout stable"

**Comment by Rinkabox** [comment]
I'm getting this error even with the stable versions:
WARNING:  You are running on `stable-0.2.2` branch - this is not a supported branch.

I have donwloaded the auto gpt release 0.3.0 and replaced the files, but i can't seem to find it from cmd. 

Branch -a shows 0.2.2 is the newest.

Any idea how to replace with the newset version so i have no error?

**Comment by Yeheyousen** [comment]
Hi, I got the same problem today, have you solved this case? What can I do? Thanks@

**Comment by Rinkabox** [comment]
I asked chat gpt to give me the python codes for the fix. I switched to 0.2.2 but couldn't load the 0.3 stable version.
