### ISSUE TITLE
Kinna selective token length for each model e.g. GPT3.5 or 4 / ada-2 or ... is necessary

### ISSUE THREAD

**Issue by wooramkang** [Significant-Gravitas/Auto-GPT#3273]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

sometime token length errors just stop the continuous runs. 
there should be length conditions or mitigators for running AutoGPT

### Examples 🌈

openai.error.InvalidRequestError: This model's maximum context length is 8191 tokens, however you requested 144417 tokens (144417 in your prompt; 0 for the completion). Please reduce your prompt; or completion length.

### Motivation 🔦

AutoGPT must run Autonomously :) 
For that, there must be no INTERRUPT

**Comment by ntindle** [comment]
Re clone and setup again

**Comment by ntindle** [comment]
That’s a config
