### ISSUE TITLE
Setting up Auto-GPT on Azure OpenAI

### ISSUE THREAD

**Issue by infinitelyloopy-bt** [Significant-Gravitas/Auto-GPT#3275]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

azure.yaml

How do I input my Azure credentials? I searched online and it appears that someone created this template pasted below. However, there is no line for:

- Azure OpenAI API credentials
- Endpoint
- Location/region

```
### AZURE
# OPENAI AZURE API BASE=OpenAl API base URL for Azure (Example: https:/ /my-azure-openai-url.com)
# OPENAT _AZURE _API_VERSION=OpenAI API version for Azure (Example: v1)
# OPENAI AZURE DEPLOYMENT_ ID=OpenAI deployment ID for Azure (Example: my-deployment-id)
# OPENAI AZURE_ CHAT DEPLOYMENT ID=OpenAI deployment ID for Azure Chat (Example: my-deployment-1d-for-azure -chat)
# OPENAI AZURE EMBEDDINGS DEPLOYMENT ID=OpenAl deployment ID for Embedding (Example: my-deployment-id-for-azure-embeddigs)
```

For example:
```
OPENAI AZURE_API BASE=“https://testing123.openai.azure.com/”
OPENAI AZURE API VERSION="api-Key1"
OPENAI AZURE API="abcd12345fghijk"
OPENAI AZURE DEPLOYMENT ID=“text-davinci-003”
OPENAI AZURE CHAT DEPLOYMENT ID=“gpt-35-turbo”
OPENAI_AZURE_EMBEDDINGS_DEPLOYMENT_ID=“text-embedding-ada-002”`
```

### Current behavior 😯

The configuration files are only setup for using OpenAI and not Azure OpenAI

'Please set your OpenAI API key in .env or as an environment variable.'

### Expected behavior 🤔

Azure OpenAI credentials

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by mindfu23** [comment]
FYi, I came across this today. I commented out the parts of the .env file that asked for Azure credentials, and Auto-GPT now appears to moving forward as before. Macbook M2.

**Comment by Pwuts** [comment]
`OPENAI_API_KEY` for authentication, and in azure.yaml, `azure_api_base` is the hostname of your instance.

**Comment by Pwuts** [comment]
Closing as resolved. If you have more questions, please ask in the discord.
