### ISSUE TITLE
Compatible with other AI APIs

### ISSUE THREAD

**Issue by zx2022x** [Significant-Gravitas/Auto-GPT#3281]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Please set it to be able to be configured as other APIs, as other artificial intelligence will stand out in a certain aspect and be more powerful than GPT

### Examples 🌈

This way, it can be compatible with many artificial intelligence, and there is also a need for programmers to write code, which needs to be verified in a testing environment

### Motivation 🔦

Comparing autogpt to a person

**Comment by ntindle** [comment]
Duplicate
