### ISSUE TITLE
Auto-GPT : Getting counts of Job Types In LinkedIn

### ISSUE THREAD

**Issue by kamal140415** [Significant-Gravitas/Auto-GPT#3290]
### Discussed in https://github.com/Significant-Gravitas/Auto-GPT/discussions/3124

<div type='discussions-op-text'>

<sup>Originally posted by **kamal140415** April 24, 2023</sup>
Hello,

I have installed all the packages required to set up Auto-GPT on a Windows Machine. I have configured Auto-GPT as per the installation instructions provided in the [installation](https://github.com/Significant-Gravitas/Auto-GPT/blob/master/docs/installation.md) page. 

My main aim is to **set up a goal such that Auto-GPT searches the "LinkedIn" Job website for "Software Engineer", "Senior Software Engineer" and "Software Development" Job Types , get counts of each of these Job Types and return a report of it**. 

I have setup the following goals in the settings file of the project in order to get the required results but Auto-GPT is not able to get the results of these Job types. 

- Search LinkedIn for "Software Engineers" Job Type and get counts of it.
- Further search LinkedIn having "Senior Software Engineers" Job Type and get counts of it.
- Also search for "Software Development" Job Type in LinkedIn and get counts of it.
- Save the job types along with their counts in a text document.
- Shutdown

Can you please suggest regarding the process/steps to be followed such that Auto-GPT provides us the count of these Job types from LinkedIn account?

Thanks and Regards,
A.K.Srinivas</div>

**Comment by ntindle** [comment]
Try and use the #tech-support channel in discord for these issues. We don’t have the capacity to help debug in GitHub issues for problems like this
