### ISSUE TITLE
Major bug with trivial codes difference on generate_image_with_dalle()

### ISSUE THREAD

**Issue by wooramkang** [Significant-Gravitas/Auto-GPT#3295]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

any command with dalle

### Current behavior 😯

SYSTEM:  Command generate_image returned: Error: generate_image_with_dalle() takes 2 positional arguments but 3 were given

### Expected behavior 🤔

image came out without error

this line 
def generate_image_with_dalle(prompt: str, filename: str) -> str:
>>>>
should be this
def generate_image_with_dalle(prompt: str, filename: str, size :int) -> str:

### Your prompt 📝

```yaml
# Paste your prompt here
NEXT ACTION:  COMMAND = generate_image ARGUMENTS = {'prompt': 'A beautiful landscape with a sunset over the ocean.'}
```

### Your Logs 📒

```log
<insert your logs here>
SYSTEM:  Command generate_image returned: Error: generate_image_with_dalle() takes 2 positional arguments but 3 were given
```

**Comment by raczy07** [comment]
I found that the latest .env file does not return this error (I got this error when using the mater .env

**Comment by k-boikov** [comment]
generate_image_with_dalle should be fixed in master

**Comment by Pwuts** [comment]
What @k-boikov said :)
