### ISSUE TITLE
Respondeat Superior 

### ISSUE THREAD

**Issue by devlux76** [Significant-Gravitas/Auto-GPT#3315]
This is not intended as legal advice, but I'm in my 3rd year of law school and as I was browsing the code and interacting with the program, I felt it might be a good time to mention something.

There is a concept under the law called [Respondeat Superior](https://www.law.cornell.edu/wex/respondeat_superior)
In a nutshell it means that a principle is liable for the actions of their agents. Using an autonomous agent unsupervised has the potential to magnify exposure to this liability exponentially.

It would be wise to include a warning to this effect in the ./run_continous warnings such that users must accept it in order to continue.

>DISCLAIMER AND INDEMNIFICATION AGREEMENT
>
>PLEASE READ THIS DISCLAIMER AND INDEMNIFICATION AGREEMENT CAREFULLY BEFORE USING THE AUTOGPT SYSTEM. BY USING THE AUTOGPT SYSTEM, YOU AGREE TO BE BOUND BY THIS AGREEMENT.
>
>Introduction
>AutoGPT (the "System") is a project that connects a GPT-like artificial intelligence system to the internet and allows it to automate tasks. While the System is designed to be useful and efficient, there may be instances where the System could perform actions that may cause harm or have unintended consequences.
>
>No Liability for Actions of the System
>The developers, contributors, and maintainers of the AutoGPT project (collectively, the "Project Parties") make no warranties or representations, express or implied, about the System's performance, accuracy, reliability, or safety. By using the System, you understand and agree that the Project Parties shall not be liable for any actions taken by the System or any consequences resulting from such actions.
>
>User Responsibility and Respondeat Superior Liability
>As a user of the System, you are responsible for supervising and monitoring the actions of the System while it is operating on your 
 behalf. You acknowledge that using the System could expose you to potential liability including but not limited to respondeat superior and you agree to assume all risks and liabilities associated with such potential liability.
>
>Indemnification
>By using the System, you agree to indemnify, defend, and hold harmless the Project Parties from and against any and all claims, liabilities, damages, losses, or expenses (including reasonable attorneys' fees and costs) arising out of or in connection with your use of the System, including, without limitation, any actions taken by the System on your behalf, any failure to properly supervise or monitor the System, and any resulting harm or unintended consequences.
 
I'm not a lawyer (yet), but I plan to put something like that in my fork. Again, not intended as legal advice, but it couldn't hurt.

**Comment by merwanehamadi** [comment]
thanks ! @devlux76 we have other issues like our plugins that could be a security hazards.
You wanna jump on discord and discuss about it ? you can dm me same name
https://discord.gg/autogpt

**Comment by ntindle** [comment]
Agreed. This is top of mind. Ping me @merwanehamadi for this convo

**Comment by Boostrix** [comment]
as per request on discord:

> printing would be a first step, but probably in conjunction with clean_input() from utils.py to confirm y/n - analogous to how we ask users whether they want to continue with the current aisettings.yaml file during startup. This is even more important in conjunction with having any of the execute* stuff enabled (shell commands and python scripts). In particular outside a VM/container environment (with those heuristics, I would suggest to even print out the disclaimer in bold red text)
