### ISSUE TITLE
Pinecone vectors are not persisted between AutoGPT restarts

### ISSUE THREAD

**Issue by perrosnk** [Significant-Gravitas/Auto-GPT#3317]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

Start Autogpt with pinecone
Create a new agent with a role and goals
After a while, stop the agent
Restart autogpt with the same agent

### Current behavior 😯

Pinecone vectors are deleted when restarting autogpt, even with the same agent

### Expected behavior 🤔

Pinecone vectors should not be deleted after restarting

**Comment by remriel** [comment]
This is by design. I don't really understand why there's no option to keep the data or reset it in the config file. After all, why even set up third-party memory if you can't even retain it?

**Comment by perrosnk** [comment]
Is there a reason why this was designed this way?

**Comment by anbardoi** [comment]
I added a PR that makes vectors persist between each run

**Comment by perrosnk** [comment]
@anbardoi works perfectly! Thanks!
