### ISSUE TITLE
Let's add create_folder action to build a structure of files

### ISSUE THREAD

**Issue by ilyamk** [Significant-Gravitas/Auto-GPT#3333]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Let's add create_folder action to build a structure of files

### Examples 🌈

na

### Motivation 🔦

na

**Comment by Pwuts** [comment]
Without further explanation of the use case, we're not going to pick this up. Building a file structure can be done with the file related commands, as those will create directories as necessary when writing.
