### ISSUE TITLE
fresh clean install, docker installation fail

### ISSUE THREAD

**Issue by ram-sh** [Significant-Gravitas/Auto-GPT#3334]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

running on windows 11, powershell runs as admin, docker desktop in running and logged in, when following the installation from "https://significant-gravitas.github.io/Auto-GPT/installation/" to install Docker i get the following error: 

`Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\WINDOWS\system32> cd e:
PS E:\> cd .\autoGPT\
PS E:\autoGPT> git clone -b stable https://github.com/Significant-Gravitas/Auto-GPT.git
Cloning into 'Auto-GPT'...
remote: Enumerating objects: 9007, done.
remote: Counting objects: 100% (56/56), done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 9007 (delta 18), reused 26 (delta 3), pack-reused 8951
Receiving objects: 100% (9007/9007), 5.68 MiB | 7.65 MiB/s, done.
Resolving deltas: 100% (6239/6239), done.
PS E:\autoGPT> cd .\Auto-GPT\
PS E:\autoGPT\Auto-GPT> docker-compose build auto-gpt
[+] Building 12.5s (10/16)
 => [internal] load build definition from Dockerfile                                                               0.1s
 => => transferring dockerfile: 1.42kB                                                                             0.0s
 => [internal] load .dockerignore                                                                                  0.1s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load metadata for docker.io/library/python:3.10-slim                                                2.0s
 => [auth] library/python:pull token for registry-1.docker.io                                                      0.0s
 => [ 1/11] FROM docker.io/library/python:3.10-slim@sha256:330173e29b1d14a58aecf60031d53fbda203886d5306c235d6a65e  0.0s
 => [internal] load build context                                                                                  0.1s
 => => transferring context: 201.09kB                                                                              0.0s
 => CACHED [ 2/11] RUN apt-get -y update                                                                           0.0s
 => CACHED [ 3/11] RUN apt-get -y install git chromium-driver                                                      0.0s
 => CACHED [ 4/11] RUN apt-get update     && apt-get install -y wget gnupg2 libgtk-3-0 libdbus-glib-1-2 dbus-x11   0.0s
 => ERROR [ 5/11] RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -     &&   10.4s
------
 > [ 5/11] RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -     && echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list     && apt-get update     && apt-get install -y chromium firefox-esr:
#0 0.385 Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
#0 10.38 gpg: no valid OpenPGP data found.
------
failed to solve: executor failed running [/bin/sh -c wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -     && echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list     && apt-get update     && apt-get install -y chromium firefox-esr]: exit code: 2
PS E:\autoGPT\Auto-GPT>`

any thoughts on how to fix this?

many thanks in advance!
RS

### Current behavior 😯

installation fails at step 5/11:

=> ERROR [ 5/11] RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -     &&   10.4s
------
 > [ 5/11] RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -     && echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list     && apt-get update     && apt-get install -y chromium firefox-esr:
#0 0.385 Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
#0 10.38 gpg: no valid OpenPGP data found.
------
failed to solve: executor failed running [/bin/sh -c wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -     && echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list     && apt-get update     && apt-get install -y chromium firefox-esr]: exit code: 2

### Expected behavior 🤔

should have finished without an error.

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\WINDOWS\system32> cd e:
PS E:\> cd .\autoGPT\
PS E:\autoGPT> git clone -b stable https://github.com/Significant-Gravitas/Auto-GPT.git
Cloning into 'Auto-GPT'...
remote: Enumerating objects: 9007, done.
remote: Counting objects: 100% (56/56), done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 9007 (delta 18), reused 26 (delta 3), pack-reused 8951
Receiving objects: 100% (9007/9007), 5.68 MiB | 7.65 MiB/s, done.
Resolving deltas: 100% (6239/6239), done.
PS E:\autoGPT> cd .\Auto-GPT\
PS E:\autoGPT\Auto-GPT> docker-compose build auto-gpt
[+] Building 12.5s (10/16)
 => [internal] load build definition from Dockerfile                                                               0.1s
 => => transferring dockerfile: 1.42kB                                                                             0.0s
 => [internal] load .dockerignore                                                                                  0.1s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load metadata for docker.io/library/python:3.10-slim                                                2.0s
 => [auth] library/python:pull token for registry-1.docker.io                                                      0.0s
 => [ 1/11] FROM docker.io/library/python:3.10-slim@sha256:330173e29b1d14a58aecf60031d53fbda203886d5306c235d6a65e  0.0s
 => [internal] load build context                                                                                  0.1s
 => => transferring context: 201.09kB                                                                              0.0s
 => CACHED [ 2/11] RUN apt-get -y update                                                                           0.0s
 => CACHED [ 3/11] RUN apt-get -y install git chromium-driver                                                      0.0s
 => CACHED [ 4/11] RUN apt-get update     && apt-get install -y wget gnupg2 libgtk-3-0 libdbus-glib-1-2 dbus-x11   0.0s
 => ERROR [ 5/11] RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -     &&   10.4s
------
 > [ 5/11] RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -     && echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list     && apt-get update     && apt-get install -y chromium firefox-esr:
#0 0.385 Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
#0 10.38 gpg: no valid OpenPGP data found.
------
failed to solve: executor failed running [/bin/sh -c wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -     && echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list     && apt-get update     && apt-get install -y chromium firefox-esr]: exit code: 2
PS E:\autoGPT\Auto-GPT> docker build -t auto-gpt .
[+] Building 12.2s (10/16)
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 1.42kB                                                                             0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load metadata for docker.io/library/python:3.10-slim                                                1.7s
 => [auth] library/python:pull token for registry-1.docker.io                                                      0.0s
 => [ 1/11] FROM docker.io/library/python:3.10-slim@sha256:330173e29b1d14a58aecf60031d53fbda203886d5306c235d6a65e  0.0s
 => [internal] load build context                                                                                  0.1s
 => => transferring context: 201.09kB                                                                              0.0s
 => CACHED [ 2/11] RUN apt-get -y update                                                                           0.0s
 => CACHED [ 3/11] RUN apt-get -y install git chromium-driver                                                      0.0s
 => CACHED [ 4/11] RUN apt-get update     && apt-get install -y wget gnupg2 libgtk-3-0 libdbus-glib-1-2 dbus-x11   0.0s
 => ERROR [ 5/11] RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -     &&   10.4s
------
 > [ 5/11] RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -     && echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list     && apt-get update     && apt-get install -y chromium firefox-esr:
#9 0.364 Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
#9 10.35 gpg: no valid OpenPGP data found.
------
executor failed running [/bin/sh -c wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -     && echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list     && apt-get update     && apt-get install -y chromium firefox-esr]: exit code: 2
PS E:\autoGPT\Auto-GPT>
```

**Comment by ram-sh** [comment]
same error when trying no-cache as well:

`docker-compose build auto-gpt --no-cache`


`PS E:\autoGPT\Auto-GPT> docker-compose build auto-gpt --no-cache
[+] Building 259.1s (10/16)
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 32B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load metadata for docker.io/library/python:3.10-slim                                                1.7s
 => [auth] library/python:pull token for registry-1.docker.io                                                      0.0s
 => CACHED [ 1/11] FROM docker.io/library/python:3.10-slim@sha256:330173e29b1d14a58aecf60031d53fbda203886d5306c23  0.0s
 => [internal] load build context                                                                                  0.0s
 => => transferring context: 3.28kB                                                                                0.0s
 => [ 2/11] RUN apt-get -y update                                                                                  6.2s
 => [ 3/11] RUN apt-get -y install git chromium-driver                                                           217.5s
 => [ 4/11] RUN apt-get update     && apt-get install -y wget gnupg2 libgtk-3-0 libdbus-glib-1-2 dbus-x11 xvfb c  23.1s
 => ERROR [ 5/11] RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -     &&   10.5s
------
 > [ 5/11] RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -     && echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list     && apt-get update     && apt-get install -y chromium firefox-esr:
#0 0.468 Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
#0 10.46 gpg: no valid OpenPGP data found.
------
failed to solve: executor failed running [/bin/sh -c wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -     && echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list     && apt-get update     && apt-get install -y chromium firefox-esr]: exit code: 2
PS E:\autoGPT\Auto-GPT>`

**Comment by k-boikov** [comment]
In the meantime you can try adding --no-check-certificate to wget on line 13 in your Dockerfile.

**Comment by ram-sh** [comment]
@k-boikov - many thanks for your quick response!

i edit the wget command:
`RUN wget --no-check-certificate -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list \
    && apt-get update \
    && apt-get install -y chromium firefox-esr`

unfortunately, same results:
` => ERROR [ 5/11] RUN wget --no-check-certificate -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub   10.4s
------
 > [ 5/11] RUN wget --no-check-certificate -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -     && echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list     && apt-get update     && apt-get install -y chromium firefox-esr:
#0 0.356 Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
#0 10.34 gpg: no valid OpenPGP data found.
------
failed to solve: executor failed running [/bin/sh -c wget --no-check-certificate -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -     && echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list     && apt-get update     && apt-get install -y chromium firefox-esr]: exit code: 2`

**Comment by ram-sh** [comment]
I've updated line 13 with the following:

`RUN wget --no-check-certificate -O google-chrome-signing-key.pub 'https://dl.dropbox.com/s/y481phtbpa4mhbn/linux_signing_key.pub' && \
    gpg --dearmor -o /usr/share/keyrings/google-chrome-archive-keyring.gpg google-chrome-signing-key.pub && \
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome-archive-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list && \
    apt-get update && \
    apt-get install -y chromium firefox-esr`

and it ran:
```PS E:\autoGPT\Auto-GPT> docker-compose build auto-gpt
[+] Building 110.0s (16/16) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 1.64kB                                                                             0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load metadata for docker.io/library/python:3.10-slim                                                0.7s
 => [ 1/11] FROM docker.io/library/python:3.10-slim@sha256:330173e29b1d14a58aecf60031d53fbda203886d5306c235d6a65e  0.0s
 => [internal] load build context                                                                                  0.1s
 => => transferring context: 3.28kB                                                                                0.0s
 => CACHED [ 2/11] RUN apt-get -y update                                                                           0.0s
 => CACHED [ 3/11] RUN apt-get -y install git chromium-driver                                                      0.0s
 => CACHED [ 4/11] RUN apt-get update     && apt-get install -y wget gnupg2 libgtk-3-0 libdbus-glib-1-2 dbus-x11   0.0s
 => [ 5/11] RUN wget --no-check-certificate -O google-chrome-signing-key.pub 'https://dl.dropbox.com/s/y481phtbp  57.2s
 => [ 6/11] RUN useradd --create-home appuser                                                                      0.5s
 => [ 7/11] WORKDIR /home/appuser                                                                                  0.1s
 => [ 8/11] RUN chown appuser:appuser /home/appuser                                                                0.5s
 => [ 9/11] COPY --chown=appuser:appuser requirements.txt .                                                        0.1s
 => [10/11] RUN sed -i '/Items below this point will not be included in the Docker Image/,$d' requirements.txt &  46.0s
 => [11/11] COPY --chown=appuser:appuser autogpt/ ./autogpt                                                        0.1s
 => exporting to image                                                                                             4.8s
 => => exporting layers                                                                                            4.7s
 => => writing image sha256:f63c79425c03db4e047dabe3702387d22fdc8fa3ea9bcc5ac095d2c85c3794df                       0.0s
 => => naming to docker.io/library/auto-gpt-auto-gpt                                                               0.0s
PS E:\autoGPT\Auto-GPT>```
