### ISSUE TITLE
Stop continuous iteration on repeated `do_nothing`

### ISSUE THREAD

**Issue by SimDamDev** [Significant-Gravitas/Auto-GPT#3335]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

when the next action is 
NEXT ACTION:  COMMAND = do_nothing ARGUMENTS = {'reason': 'Waiting for user input.'}

the y -N cycling would stop to wait for user input

### Examples 🌈

y -10

action
action 
action

next action "waiting for user input"

y = 0 the wait user input

### Motivation 🔦

avoid wast of token in loop of asking user input

**Comment by k-boikov** [comment]
Fixed with https://github.com/Significant-Gravitas/Auto-GPT/pull/3369
