### ISSUE TITLE
Error with 'write_to_file' command: 'PosixPath' object has no attribute 'is_relative_to'

### ISSUE THREAD

**Issue by nuo24** [Significant-Gravitas/Auto-GPT#3339]
- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-4

### Current behavior 😯

Hello,

I'm experiencing an error with the 'write_to_file' command in Auto-GPT. When I run the command, I receive the following error message:

"Error: 'PosixPath' object has no attribute 'is_relative_to'"

I am running the latest version of Auto-GPT and Python 3.11.0 on macOS. I have tried running the command with different file paths and permissions, but I keep encountering the same error.

The second issue Description: When attempting to execute a Python file in the workspace using the Auto-GPT command execute_python_file, an error message is returned stating "Invalid file type. Only .py files are allowed." The path to the Python file and workspace are correctly specified in the command. This error prevents the Python file from being executed and impedes the workflow of the Auto-GPT program.

Could you please provide guidance on how to resolve this issue?

### Expected behavior 🤔

to search my system if I have python 3.11 or not.

### Your prompt 📝

```yaml
firstly, i have installed python 3.11, so do I need to restart for it to be activated, or you are already aware
(this is the prompt)

```

### Your Logs 📒

```log
SYSTEM:  Human feedback: firstly, i have installed python 3.11, so do I need to restart for it to be activated, or you are already aware
 THOUGHTS:  Before we proceed, let's confirm that Python 3.11 is installed and working properly. We can do this by checking the version of Python installed on your system.
REASONING:  It is important to ensure that Python 3.11 is installed and working properly before we proceed with the assignments. This will help us avoid any issues that may arise due to an incorrect installation or version of Python.
PLAN: 
-  Check the version of Python installed on your system to confirm that Python 3.11 is installed and working properly.
CRITICISM:  I need to ensure that Python 3.11 is installed and working properly before we proceed with the assignments.
NEXT ACTION:  COMMAND = execute_python_file ARGUMENTS = {'file': '<path_to_python_file>'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
Executing file '<path_to_python_file>' in workspace '/Users/---/Downloads/Auto-GPT/Auto-GPT-0.2.2/auto_gpt_workspace'
SYSTEM:  Command execute_python_file returned: Error: Invalid file type. Only .py files are allowed.
```

**Comment by Pwuts** [comment]
What does `python --version` return?

**Comment by josemizrahi8** [comment]
Python 3.10.9

**Comment by nuo24** [comment]
Hello, i got into the discord and no one is answering my questions

**Comment by Boostrix** [comment]
FYI, I am also seeing this using Python 3.8.10: 

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
