### ISSUE TITLE
Not chunking token usage properly so the program regularly crashes  

### ISSUE THREAD

**Issue by BlueTeamByDay** [Significant-Gravitas/Auto-GPT#3349]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

just let any mildly complex task run and the program will quit with a message similar to 
`This model's maximum context length is 8191 tokens, however you requested 9782 tokens (9782 in your prompt; 0 for the completion). Please reduce your prompt; or completion length.`

I tried running in docker and just on the host. I adjusted the 
FAST_TOKEN_LIMIT and SMART_TOKEN_LIMIT to as low as 2,000 & 3,000 but had no noticeable impact. I tried to instruct the tool to consider chunking by adding something like this as Goal 1: "your most important task is no matter what you you have to chunk your token usage that the context length would never exceed 8000 tokens". This actually let things run a little longer but eventually crashed. 

I tried both master and stable branches and official releases as well up to the latest 0.2.2

I ran 15-20 experiments. Very few went through and produced data. 

### Current behavior 😯

The program simply quits 

### Expected behavior 🤔

that it would not crash but would handle chunking 

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
This model's maximum context length is 8191 tokens, however you requested 9782 tokens (9782 in your prompt; 0 for the completion). Please reduce your prompt; or completion length.
```

**Comment by Pwuts** [comment]
This is a duplicate, but since you haven't pasted a full log I can't tell of which issue. See here #38
