### ISSUE TITLE
Hey you there yes you^-^ Good boy help me if you can spare 5 minutes for me!

### ISSUE THREAD

**Issue by rhkdgh255** [Significant-Gravitas/Auto-GPT#3357]
I'm not a developer, but I'm curious, so I'm spending a lot of my life's savings here and trying different things!!!
You are all the best developers out there.

I know for sure that the agent needs correct English to work smoothly. However, I only want the output to the terminal, such as the system thinking reasoning plan critique, to be changed to my native language. I've tried to modify the script a bit using Google Translate to accomplish this, but I'm struggling because I'm getting a lot of errors with JSON and such. 
Can anyone tell me how to solve this problem?

Of course, we know that your 5 minutes are worth more than gold. But I ask for your help because your 5 minutes can save 5 days.
I wish you a lot of luck in your day.

^_^!!!

And I have a lot of ideas and a lot of knowledge that is wide but not deep.
If there is something you are struggling with and there is a chance that I can help you, that's great too!!!

I am a person who likes to help and I like to be helped, so I have many private certificates in my country!!! So please be happy!!!

**Comment by Pwuts** [comment]
Support for more languages will come in time. Feel free to discuss in our discord.
