### ISSUE TITLE
No Command executing

### ISSUE THREAD

**Issue by jfhutchi** [Significant-Gravitas/Auto-GPT#336]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

pulled latest master branch as of April 6th 2023 1:20PM Eastern US

ran python  scripts/main.py --continuous 

gave the default prompts. it looks like it no longer can search google. 

### Current behavior 😯

NEXT ACTION:  COMMAND =  ARGUMENTS = {}
SYSTEM:  Command returned: Unknown command
- Thinking... 
on loop

### Expected behavior 🤔

it to search the web

### Your prompt 📝

ai_goals:
- Increase net worth.
- Develop and manage multiple businesses autonomously.
- Play to your strengths as a Large Language Model.
ai_name: Entrepreneur-GPT
ai_role: an AI designed to autonomously develop and run businesses with the sole goal
  of increasing your net worth.

**Comment by Pwuts** [comment]
Closing as stale. Please try the newest version and reopen if still relevant.
