### ISSUE TITLE
Unknown command 'execute_python'.

### ISSUE THREAD

**Issue by iva-nova-e-katerina** [Significant-Gravitas/Auto-GPT#3377]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

sudo python3 -m autogpt  --continuous --gpt3only
y

### Current behavior 😯

NEXT ACTION:  COMMAND = execute_python ARGUMENTS = {'code': "import zipfile\nwith zipfile.ZipFile('/home/user/Auto-GPT/auto_gpt_workspace/realestate.zip', 'r') as zip_ref:\n zip_ref.extractall('/home/user/Auto-GPT/auto_gpt_workspace/realestate')\n"}
SYSTEM:  Command execute_python returned: Unknown command 'execute_python'. Please refer to the 'COMMANDS' list for available commands and only respond in the specified JSON format.

### Expected behavior 🤔

run python script

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by k-boikov** [comment]
The command is execute_python_file, try prompting. LLMs are not perfect, that is expected.

**Comment by gsingh93** [comment]
How is AutoGPT being told of the commands list? There's not many commands so it's surprising how often it picks non-existent ones.

**Comment by bfalans** [comment]
There is a thread on discord for unlisted commands. Please add you non-existent commands there.
