### ISSUE TITLE
README Installation instructions broken link

### ISSUE THREAD

**Issue by EddieLF** [Significant-Gravitas/Auto-GPT#3386]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

Click the link [installation instructions](https://github.com/Significant-Gravitas/Auto-GPT/blob/d8c16de1230232dcbc0f5c1cb9abd75c3f9d06d6/README.md?plain=1#L96) in the README.

### Current behavior 😯

The link takes you to 

https://significant-gravitas.github.io/Auto-GPT/setup/ 

which is a 404 page

### Expected behavior 🤔

I think the link should go to 

https://significant-gravitas.github.io/Auto-GPT/installation/

OR

https://significant-gravitas.github.io/Auto-GPT/installation/#general-setup

**Comment by ntindle** [comment]
@richbeales

**Comment by richbeales** [comment]
Thanks for pointing this out, we refactored the docs but hadn't deployed the new docs to github pages.  Fixed now
