### ISSUE TITLE
Expanding Auto-GPT to accept multi-modality input to reach humanoid robot level

### ISSUE THREAD

**Issue by bharathraja** [Significant-Gravitas/Auto-GPT#3393]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Can the auto-GPT be expanded to take in multi-modality input such as image, audio, touch and can act through the humanoid robot body ? The modularization of image object recognition, audio-text processing and touch based input tokenisation into text format would integrate all senses. This would make truly autonomous humanoid robots. this can be tested in the simulated environments like OpenAI gym initially. 

There are literature which has expanded GPT ability to human action sequences, like this one: https://actiongpt.github.io/

### Motivation 🔦

i-Robot movie

**Comment by zachary-kaelan** [comment]
GPT can't generate text anywhere near fast enough to react to a real-time environment, and if it could then we'd be broke from the token costs of generating detailed actions 60 times a second.

**Comment by ntindle** [comment]
This isn’t the worst idea, could be done if the gradio tools plug-in is fixed up a bit

**Comment by zachary-kaelan** [comment]
I have embeddings fever and it's exciting to see that we got a latent space for motions going, but multimodal, spatiotemporal autoencoding and decoding isn't cheap.

**Comment by Boostrix** [comment]
this should probably be renamed to something like "multi modality" ?
