### ISSUE TITLE
Have AI ask question of human

### ISSUE THREAD

**Issue by DMTarmey** [Significant-Gravitas/Auto-GPT#3396]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

In the process of finding information could it be possible to have an option which is clearly to assist the AI, if you know information it could say I'm looking for key xxx and leave a box to past it I'm if you have it.

**Comment by zachary-kaelan** [comment]
AI: "I need a little neurotoxin."
Me: "Well as long as it's for science."

**Comment by Boostrix** [comment]
See: https://github.com/Significant-Gravitas/Auto-GPT/issues/1548#issuecomment-1518328221 and #1377

**Comment by Boostrix** [comment]
Please help take a look at the following PR #3083, hopefully this can then be closed or made more specific ?

**Comment by Boostrix** [comment]
Hi, just a short update - thanks for taking the time to update your PR, your PR was today discussed on Discord by several devs and it's being assigned to be reviewed right now!

So, given that there seem to be at least 5+ different PRs in the pipeline currently using similar but still a different method, it is likely that we're going to take parts from each and every one of these PRs, to ensure that the feature is well-aligned with the ongoing re-arch effort.

This means, you will end up in the credits automagically - but won't have to do any more work from now on.

If there are remaining questions, someone is going to contact you, the PR is being reviewed by @gravelBridge
