### ISSUE TITLE
Calculations and math

### ISSUE THREAD

**Issue by aliasal** [Significant-Gravitas/Auto-GPT#3412]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

I was not sure wether to file under bug report or under feature request.
All language models are bad with math.
Can tools like wolfram-alpha or the llm-math from LangChain be integrated?

### Examples 🌈

I created an agent that should solve the problem to find out the weight difference between 1 cubicmeter gold and a regular tetrahedron of edge length 2m made of lead.
It worked quite good, but stumbled the landing, where it did the following:

The weight of 1 cubic meter of gold is 19,300 kg. The volume of a regular tetrahedron with edge length 2m is (2^3)/(6sqrt(2)) m^3, which is approximately 0.4714 m^3

Everything is correct, except the calculated volume of the tetrahedron. The formula is correct and gives exact the double of the volume, that the system found, that is 0.95 m^3

### Motivation 🔦

"Simple" calculation needs to be done all the time and without relieable results not much can be achieved.

**Comment by Boostrix** [comment]
#3775
