### ISSUE TITLE
SSHing into remote server hangs Auto-GPT

### ISSUE THREAD

**Issue by Benjman** [Significant-Gravitas/Auto-GPT#3420]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

* Does it work on stable branch? **No**
* Does it work on master branch? **No**
* Search for existing issues. **Could not find issues related to SSH.**
* Ask on our Discord **Asked several times without receiving any response.**
* Provide relevant info
  * master git hash 6b4ad1f933dee86dfc272ee6b7d1e43826c6cffb
  * stable git hash 91537b049625b6516f2b5f7361ae993d4e878a2e
* Operating System **Arch `6.2.11-arch1-1`**

# Steps to reproduce
Give the following prompts:

> Goal 1: SSH into server 1.1.1.1
> Goal 2: Update packages

Auto-GPT responds with:

```sh
Using memory of type:  LocalCache
Using Browser:  firefox
 THOUGHTS:  I will SSH into the server 1.1.1.1 and update the packages.
REASONING:  I need to access the server to update the packages. SSH is the best way to do this. I will then use the package manager to update the packages.
PLAN:
-  SSH into the server
-  Use the package manager to update the packages
CRITICISM:  I need to ensure that I am using the correct package manager for the Arch distro.
NEXT ACTION:  COMMAND = execute_shell ARGUMENTS = {'command_line': 'ssh 1.1.1.1'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-=
Executing command 'ssh 1.1.1.1' in working directory '/home/ben/.local/src/Auto-GPT/auto_gpt_workspace'
```

(ip address changed for description)

### Current behavior 😯

I see that the Auto-GPT agent successfully SSHs into the server:

![](https://cdn.discordapp.com/attachments/1092275629602394184/1099748068351553656/image.png)

However, the agent hangs and will not continue. The last line of the prompt above is where it gets stuck. Ctrl+c does not affect the session, I have to force close the terminal.

### Expected behavior 🤔

Successfully recognizes it has SSH'd into the server, and continues with the next goal.

### Your Logs 📒

```log
2023-04-27 11:52:33,828 INFO Welcome back!  Would you like me to return to being Web server configurer?
2023-04-27 11:53:07,387 INFO Using memory of type: LocalCache
2023-04-27 11:53:07,508 INFO Using Browser: firefox
2023-04-27 11:53:22,554 INFO  THOUGHTS: I need to ssh into the server aliased as `bscore02` to begin configuring the web server.
2023-04-27 11:53:22,944 INFO REASONING: I will use the `ssh` command to connect to the server.
2023-04-27 11:53:23,246 INFO PLAN: 
2023-04-27 11:53:23,295 INFO -  Use `ssh` command to connect to the server.
2023-04-27 11:53:23,557 INFO CRITICISM: I need to ensure that I have the correct credentials to connect to the server.
2023-04-27 11:53:23,901 INFO NEXT ACTION:  COMMAND = execute_shell  ARGUMENTS = {'command_line': 'ssh bscore02'}
2023-04-27 11:53:27,618 INFO -=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
```

**Comment by Benjman** [comment]
I would really like to know if this is reproducible for anybody else. Are SSH capabilities generally not available in Auto-GPT?

**Comment by Boostrix** [comment]
For the likely background info, please see: #1327 and #346
