### ISSUE TITLE
Add command "autodebug_code" to Auto-GPT

### ISSUE THREAD

**Issue by Emasoft** [Significant-Gravitas/Auto-GPT#3445]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Add command "autodebug_code" to Auto-GPT. 
The command should automatically fix errors in a source code file.
To fix source code files it should execute them, read the error messages and change the source code iteratively until no more errors are reported.  
It should be based on the excellent [SebRinnebach autodebug](https://github.com/SebRinnebach/autodebug) for Python. It uses GPT-4 and works very well.
To boost the command it would be ideal to accompany it with another command called "learn_api", based on [danielgross LlamaAcademy](https://github.com/danielgross/LlamaAcademy), an excellent project aiming at automate API learning for LLMs.  

### Examples 🌈

[SebRinnebach autodebug](https://github.com/SebRinnebach/autodebug) for Python.

See also issue https://github.com/Significant-Gravitas/Auto-GPT/issues/3686

### Motivation 🔦

The current Auto-GPT commands set does not include the function to fix source code files executing them, reading the error messages and changing the source code iteratively until no more errors are reported.  

Currently there are 3 commands relative to handling source code:  
 -  autogpt.commands.analyze_code  
 -  autogpt.commands.execute_code  
 -  autogpt.commands.improve_code  
  
What is missing is a command that just fix the errors in the code, like this:  
 -  autogpt.commands.autodebug_code  
  
[SebRinnebach autodebug](https://github.com/SebRinnebach/autodebug) for Python uses GPT-4 and works very well. It should be considered as a model to follow for the new command.  
  
It could also be boosted by adding a function to learn API from docs:  
 -  autogpt.commands.learn_api  
  
For example [danielgross LlamaAcademy](https://github.com/danielgross/LlamaAcademy) is an excellent project aiming at automate API learning for LLMs. It should be studied or even integrated into Auto-GPT.

Also, all commands should be converted into plugins. The plugin model is much more consistent and extensible.

**Comment by Boostrix** [comment]
this is definitely of interest in the context of #15
