### ISSUE TITLE
Reducing momery size for very large and complex tasks using ChatGPT to summarize the memory

### ISSUE THREAD

**Issue by jaykay9999** [Significant-Gravitas/Auto-GPT#3446]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

The idea is when a task is very large, Rather than removing past token from the memory, ChatGPT can create a short detailed summary of the tasks done including set of actions, goals, deliverables.. etc.

The goal is to increase the long term memory through understanding the context of the memory, then create a summary of it rather than treating it as embedding of multiple words. say each 1000 word can be reduced to a summary of only 200 without losing context.

I'am currently working on a project in which ChatGPT automatically reads ocr text from multiple PDF files (which is very large data) to help companies take decisions, and that was the approach i took to not lose context when very large data is being inputted.

email : jasemkhlifi@gmail.com

### Examples 🌈

The following screenshot shows an example of a function that takes ocr text data from a 32 pages long pdf. the function "important_info_extraction()" takes an ocr text of a page and creates a 70 tokens long summary of that page. then the summaries of all the pages are stored in a variable that does not exceed 70x32 tokens. that variable is then passed to a different prompt that will analyze the full 32 pages long pdf files to provide analysis, risk factors, decision making, etc... 

The same logic can be applied for AutoGPT to be used only when the memory becomes full and some tokens are going to be removed. (it can even used for a sub part "the older memories" only rather then the whole memory)

![Screenshot 2023-04-28 030144](https://user-images.githubusercontent.com/74210873/235036626-d0341bdc-9514-4594-abed-38c5f96f958b.png)

### Motivation 🔦

I have multiple ideas and architectures to use for this specific feature and I would really love to contact anyone to further discuss this feature and I would do my best to work on it. 

I also have multiple other ideas but much more complex (such as creating an super agent who creates multiple agents) but that is for the future. 

If something would change the world in future, it is autonomous artificial general intelligence that exponentially scales. I would love to be a part of it :)

**Comment by Boostrix** [comment]
you don't want to "summarize", you want to "serialize" or rather "snapshot", right ?

**Comment by Boostrix** [comment]
however, that doesn't work too well when working with structured data (think documents or source code), where you need to retain all of the structure to be able to make meaningful changes

**Comment by jaykay9999** [comment]
that is true, but in my opinion, when you face a tradeoff where your only choice is to conpletely get rid of let's a code snippet that was mentioned way early in chat, keeping a small sentence that says for example " python code that runs sorting algorithm " would be better. this is just a personal opinion, it can be tested if it is implemented and tested to a very large chat and see how it works in action.

**Comment by Boostrix** [comment]
the powerful thing is being able to do the reverse afterwards, i.e. looking up the original portion of the file in question based on the context (which may be a vector of portions spread out over several pages/files)

**Comment by jaykay9999** [comment]
I can work on this feature and run multiple tests regarding the issue you mentioned in this comment section, all I need is simple guidance and I can happily start :)
