### ISSUE TITLE
'repository_url' vs. 'url'

### ISSUE THREAD

**Issue by TerminalGravity** [Significant-Gravitas/Auto-GPT#3452]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

Follow the conversation and observe the system using 'repository_url' as an argument in the clone_repository command.

### Current behavior 😯

The system is using the 'repository_url' argument when calling the clone_repository command, which results in an error.

### Expected behavior 🤔

The system should use the 'url' argument when calling the clone_repository command to avoid errors.

### Your prompt 📝

```yaml
# N/A -- has to do with cloning langchain with auto-gpt to create vector stores on content exceeding max token length. 
```

### Your Logs 📒

```log
SYSTEM:  Command clone_repository returned: Error: clone_repository() missing 1 required positional argument: 'url'
```

**Comment by bobisme** [comment]
did this happen repeatedly?
did you try telling your agent to use "url" instead of "repository_url"?

**Comment by bobisme** [comment]
maybe this should be changed:

```python
@command(
    "clone_repository",
    "Clone Repository",
    '"url": "<repository_url>", "clone_path": "<clone_path>"',
    ...
)
```
to
```python
@command(
    "clone_repository",
    "Clone Repository",
    '"url": "<url of the repository>", "clone_path": "<local file path to clone into>"',
    ...
)
```

https://github.com/Significant-Gravitas/Auto-GPT/blob/cdd91f7ea38c468a1f090a65d1ca1292e2bbedcb/autogpt/commands/git_operations.py#L14
