### ISSUE TITLE
build error with M1 mac

### ISSUE THREAD

**Issue by zyt600** [Significant-Gravitas/Auto-GPT#3455]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

git clone -b stable https://github.com/Significant-Gravitas/Auto-GPT.git
cd Auto-GPT
./run.sh

How to solve: 
change requirements.txt: orjson->orjson==3.8.10
I don't know why, but it solved my problem

### Current behavior 😯

error before change requirements.txt: orjson->orjson==3.8.10 are listed below

ImportError: dlopen(/Users/zhouyutong/anaconda3/envs/autogpt2/lib/python3.10/site-packages/orjson/orjson.cpython-310-darwin.so, 0x0002): tried: '/Users/zhouyutong/anaconda3/envs/autogpt2/lib/python3.10/site-packages/orjson/orjson.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/zhouyutong/anaconda3/envs/autogpt2/lib/python3.10/site-packages/orjson/orjson.cpython-310-darwin.so' (no such file), '/Users/zhouyutong/anaconda3/envs/autogpt2/lib/python3.10/site-packages/orjson/orjson.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
Press any key to continue... 

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by Pwuts** [comment]
Please create an issue in the `orjson` repo as well: https://github.com/ijl/orjson/issues

**Comment by Pwuts** [comment]
None of our testers can reproduce this issue with `orjson` version 3.8.11

**Comment by kskk02** [comment]
I am getting this error too. Im on a M1 macbook !

**Comment by kskk02** [comment]
I made the change to orjson and this did not fix the issue. I still get the error  (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64)))

**Comment by filip-michalsky** [comment]
@Pwuts Had this issue in the morning. downgraded `orjson` to `3.8.1` then it worked for me on Mac with M1

**Comment by Pwuts** [comment]
@filip-michalsky ok so 3.8.11 is broken. Does version 3.8.10 work for you?

**Comment by zyt600** [comment]
> 

As for me, version 3.8.10 works for me. I just need to change the orjson  version to 3.8.10 to fix the bug

**Comment by zyt600** [comment]
UPDATE: HOW TO REPRODUCE
use a M1 Mac with macOS 13.3.1 

git clone -b stable https://github.com/Significant-Gravitas/Auto-GPT.git
cd Auto-GPT
conda create -n bug_env python=3.10
conda activate bug_env
./run.sh

**Comment by chett2001** [comment]
I am having the same issue. Downgrading orson to orjson==3.8.10 fixed the issue.
