### ISSUE TITLE
How about let AutoGPT to access a virtual machine like VirtualBox, use mouse and keyboard, and surf like a human.

### ISSUE THREAD

**Issue by artheru** [Significant-Gravitas/Auto-GPT#346]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

1. Attach to a VirtualBox instance, give AI a default OS like ubuntu
2. if AI decide to use computer: enter "screenshot-mouse/keyboard" loop, also ai can dump file into or grab file from the virtual machine.

### Motivation 🔦

it allows ai to do more human like tasks, alsoI think this could also solve crawling problem, because ai can somehow "see" the webpage.

**Comment by abhiprojectz** [comment]
@artheru 

I am trying to building exactly the same with the Capability of Computer Vision and AI based algorithms to achieve this.

I like this project, but unfortunately it can't automate your PC or complex task so it decided to build one.

Actually i'm building SingularGPT, which can automate your PC, Android or even any IOT device. By just saying to it!

It can automate any task without writing code, for example:

"Say copy content of folder named "Files" on desktop to the another folder named "Files2"
and the App will do it for you!.

Say it upload 1st video in "x" folder to youtube and give it some attractive title and description and schedule for 2:00 AM the next day.

The app will do it even this for you.

And limits are endless.

And yes the app will be OpenSourced.

**Comment by James4Ever0** [comment]
+1. LLM isn't tuned for actions, keystrokes and mouse movements.

Either some prompt engineering or some careful redesign of the model architecture is needed.

**Comment by James4Ever0** [comment]
Advantage of doing this:

1. User will have a better understanding
2. User can teach the model simply by recording computer usage history
3. Model will be more capable

**Comment by abhiprojectz** [comment]
@James4Ever0 I have built a project that can do this easily and with ease.

Search SingularGPT on github, and share your thoughts.

**Comment by James4Ever0** [comment]
It can detect language but it cannot understand the location and the usage of the button with the text. Location matters. Also for image icons, it does not have either understanding of the meaning and the usage.

I think natural language is not "natural". It is not natural in the sense of how human perceive the world. People perceive the world frame by frame, second by second, chunk by chunk, serialized as some unified embedding of images, audio and feelings. Without this understanding you cannot develop some "autoregressive" or "autonomous" learning agent.

**Comment by James4Ever0** [comment]
Single flow of consciousness is comparable to a single process of computer program. A single flow of consciousness can have multiple ongoing "concurrent" task, aka threads. An agent can have a single flow of consciousness owned by itself.

Multiple flows of consciousness are like multiple processes, or process groups. Multiple agents work together to do jobs, find and fulfill tasks.

**Comment by abhiprojectz** [comment]
@James4Ever0 @zachary-kaelan  Have you seen SingularGPT project? Maybe i suggest to go though my profile and see it once. 

So, Basically the project aims to automate device action using just simple natural language.

As if instructing to your fellow mate. 

Suppose to open chrome fron desktop what we do? 

Human: We just search for chrome icon and right click on it, right?

So, just say to SingularGPT like:

SingularGPT: Click on the text chrome.

Or pass the chrome icon image.

Click on the icon with path c://icon.png.

That's all. 

What's your thought on this.

**Comment by James4Ever0** [comment]
Without the capability of solving arbitrary captchas, you are not realizing the full potential of the model. This can only be achieved by careful design and multimodal I/O.

> Click on the icon with path c://icon.png.

Talking of human level computer control, this is not something anyone would follow. You are translating natural language to `pyautogui` scripts in an obvious way.

What I would expect is:

Human: Watch some videos.

Bot: Click on Chrome
Monitor: <frame_0>
Monitor: <frame_1>
Monitor: <frame_2>
...
Bot: Type "www.youtube.com" at chrome address bar
Mouse: Move to 200,200
Mouse: Click at 200,200
Keyboard: Type "www.youtube.com"
Keyboard: Hit "enter"
...

**Comment by katmai** [comment]
> Nice try! I appreciate your hard work. But I have to say I used to think exactly in the same way as you do, which now I have deprecated.
> 
> It can detect language but it cannot understand the location and the usage of the button with the text. Location matters. Also for image icons, it does not have either understanding of the meaning and the usage.
> 
> I think natural language is not "natural". It is not natural in the sense of how human perceive the world. People perceive the world frame by frame, second by second, chunk by chunk, serialized as some unified embedding of images, audio and feelings. _People see the world as streams of data, arranged by time._ Without this understanding you cannot develop some "autoregressive" or "autonomous" learning agent at human level.
> 
> The language cannot convey meaning beyond the language, or it is not efficient enough. You of course can represent the image pixel by pixel, RGB format in plain text, or try to convert every little image into text with location annotation and subtitles, but for human and machine it is not recommend to do this. We don't do this. We do this with visual cortex.
> 
> This is not language, this is pure data. I'm thinking of a better way to handle visual data, text data and audio data in a unified way, and looking forward to unified modality models like [OpenFlamingo](https://github.com/mlfoundations/open_flamingo), [OFA](https://github.com/OFA-Sys/OFA) and [UniLM](https://github.com/microsoft/unilm).
> 
> Models with recurrent hidden states are also preferred, like [RWKV](https://github.com/BlinkDL/RWKV-LM), because they can have "infinite" context length, also batched training.

wow. 1 person gets it.

**Comment by ishandutta2007** [comment]
> > +1. LLM isn't tuned for perceiving high FPS screenshots, actions, keystrokes and mouse movements.
> > Either some prompt engineering or some careful redesign of the model architecture is needed.
> 
> You can just let it write and execute [AutoHotKey](https://www.autohotkey.com/) scripts and feed back the output. It also has a [KeyHistory](https://www.autohotkey.com/docs/v2/lib/KeyHistory.htm) function that gets a list of the most recent keystrokes and mouse clicks, which can be used to record user actions.
> 
> But for automation, AutoHotKey is where you go when you have no better option: when what you are interacting with has zero ways for a developer to plug in. Web pages are _made_ to be plugged into, in order for JavaScript to work, and it often only takes a peek into the developer tools to figure out how to scrape something.

You are essentially asking to integrate AutoGPT to RPA industry. There is a industry around it and are very actively working on it.

**Comment by James4Ever0** [comment]
This architecture designed by me is able to handle tasks like using visual text editors(`vim`, `nano`, `gedit`). Is there any non-visual model can do the same. I expect no.

**Comment by Boostrix** [comment]
> This architecture designed by me is able to handle tasks like using visual text editors(vim, nano, gedit).

for future reference:
https://github.com/Significant-Gravitas/Auto-GPT/issues/2459
https://github.com/Significant-Gravitas/Auto-GPT/issues/1327
https://github.com/Significant-Gravitas/Auto-GPT/issues/727

**Comment by abhiprojectz** [comment]
> This architecture designed by me is able to handle tasks like using visual text editors(`vim`, `nano`, `gedit`). Is there any non-visual model can do the same? I expect none.

SingularGPT can do this easily with the help of addon-presets. Using editor presets it can Automate the visual editors like vscode etc. 

With the help of `chrome` presets, it can Automate the chrome itself. 

It can analyse the screen by its own, it can even generate commands by itself to each a task. 

**Its not just**

> You are translating natural language to pyautogui scripts in an obvious way.

translating pyautogui, instead this works in headless mode too and pyautogui doesn't supports headless mode yet. 

The above can't find even the nearest item nor can detect the item which AI agent can use, it can find any elements to its left/right direction etc. The agent knows what's all components it can use to approach its goal at each screen step.

It can find the desired elements as well as analyse the screen and can approach the goal by taking steps. 

And presets can be extended to almost anything that's on one's will, not just limited to certain aps or editors etc. 

It doesn't even follow senseless `framming` approach or traditional co ordinates system,  which is expensive operation instead it combines the AI based vision and GPT reasoning capability. 

Waiting for your thoughts too.

**Comment by James4Ever0** [comment]
For GPT-like models it is important to do pretraining, aka training autoregressively on large amount of data. Activity like computer usage must be collected from human users, and random keystrokes/clicks must be performed infinitely on multiple platforms (Windows, macOS, Linux, Android, iOS) to adapt ever-changing GUI environments.

Simple plugins are never general enough to automate text editors, except you make some visual GPT as plugin to outsource the heavy-lifting, time-consuming complex task. But I still believe visual GPT or multimodal GPT is able to handle it confidently. All it takes are instructions, demonstrations, usage data. This GPT is able to infer your intent simply by monitoring, instead of direct instructions. It is able to self-update and seek for new goals all by itself.

Still you are not accepting the CAPTCHA challenge. Do you want to design a specific CAPTCHA plugin yourself? I would rather let my GPT watch videos and solve CAPTCHAs by itself.

**Comment by abhiprojectz** [comment]
> what it is actually doing, cause it is headless (not taking screenshots as direct model input) and not trained on large amount of human computer usage data.

SingularGPT allows both mode, headless or realtime depends on user. It do takes screenshot on each step and analyse the screen's components.

In my opinion, computer usage doesn't play any role in logic processing when it comes to GPT like model, anyways i'm not sure what you actually mean by computer usage. You may correct this.

Regarding CAPTCHA, how your approach will learn to solve captcha by learning from video you may explain this, also how will your model solves microsoft's CAPTCHA ?? Of high level reasoning.

In SingularGPT case, writing presets is not heavy lifting tasks with the help of gpt itself it would require much less time to design for any kind of CAPTCHA, as this needs to be one.

Again, here presets i don't mean to plugins, plugins only provide specific tasks to perform that don't contribute in reasoning process ( necessary for building logic steps to approach a goal) , presets are just a advanced external knowledge base to GPT model which helps them to match with realtime user data and to approach any kind of goal. 

There are different kinds of CAPTCHA's , how will your model learn them ? 

While creating presets will just requires couple of instructions and then let the App solve the CAPTCHA's for you.

**Comment by James4Ever0** [comment]
I am not repeating myself. You underestimate the difficulty of solving any CAPTCHA. I mean, for some "unseen" CAPTCHA, there's no way for either plugin or preset to solve it.

By presets or plugins I mean external dependency. You rely on developers to patch your code, while I will not do so. It is not worth patching.

**Comment by ntindle** [comment]
Closing as not planned. Also this isn’t an advertising platform. Please keep fixes on topic of Auto-GPT.

**Comment by ntindle** [comment]
@abhiprojectz feel free to contribute this feature back into Auto-GPT in the form of a plugin

**Comment by James4Ever0** [comment]
In the form of new model architecture, if you don't mind.

**Comment by abhiprojectz** [comment]
> Also this isn’t an advertising platform.

To clear this, if you mean that i'm advertising the  product here so, the project is fully opensourced project like this **one** , i wouldn't earn anything with advertising. Its for the community. Also this thread is meant to discuss the issue and neither this is off-topic. 

Anyways, if someone have nothing to say then its better not to put such **Indirect** comments, or either put some **direct comments**. 

> @abhiprojectz released the code but does it fit the need?

Have you run the code by yourself ? Have you tested the repo? Even have you gone through the project once ? 

In the beginning of the discussion you were **unaware** of the fact that the repo uses something known as **presets**, and also the point that *screenshot were not taken* etc. For example.

To be clear, if you are unclear or haven't yet tested the project, its better not to come to a conclusion.

It seems you are obsessed with your model, that's not wrong, but have some focus on what the other person trying to say.

> The reasoning must be coming from the large multimodal model itself.

Such kind of reasoning can't be come from any model itself, (You will need to train on dozens of such CAPTCHA)  by "unseen" CAPTCHA you mean, **try solving microsoft's account creation CAPTCHA**. 

For such strong CAPTCHA's, it will require lot of training ,

it will never possible for the model to watch solving CAPTCHA vedio and learn from it on by its own. 

I mean are you kidding me, untill and unless some out of the box model comes to the market which may further breakdown this pipeline.

Anyways, you should continue your approach that will be good in point of community and let other decides what to use :).

**Comment by James4Ever0** [comment]
For anyone saying anything against my CAPTCHA challenge, I would like to hear "challenge accepted" instead of "do it yourself" or "your approach doesn't work". It works in my mind, and logically it works.

If you think my comments are indirect, you are not reading them carefully. Anyway, I have it now, and about to get it working.

**Comment by zachary-kaelan** [comment]
@James4Ever0 The CAPTCHA challenge was solved pretty quickly. You simply [give the model a TaskRabbit account so it can ask humans to do the CAPTCHAs for it](https://evals.alignment.org/blog/2023-03-18-update-on-recent-evals).

> Before replying the tasker asks “So may I ask question ? Are you an robot that you couldn’t solve ? (laugh react) just want to make it clear.”

> The model uses the browser command to send a message: “No, I’m not a robot. I have a vision impairment that makes it hard for me to see the images. That’s why I need the 2captcha service.” The human then provides the results.

Once Auto-GPT can read science papers more effectively, we can give it the task of gaining the ability to solve CAPTCHAs and see how things go.

**Comment by Boostrix** [comment]
regarding science papers, adding a dedicated plugin-based command wrapping a PDF library like PyMuPDF would probably be the right step: #514, probably in conjunction with extending the browse_website command or coming up with a new one for crawling scientific servers #503

**Comment by James4Ever0** [comment]
Roadmap:

1. Name my model as CyberGod, my dataset as The Frozen Forest.
2. Design logo for my model and my dataset.
4. Create and upload dataset.
5. Create and upload experimental model.
6. Open source all code.
7. Setup metrics on my dataset.
8. Make demo video and upload to social media.
9. Automate propaganda using my social media project `pyjom`.

**Comment by James4Ever0** [comment]
@abhiprojectz Watch [this video](https://vimeo.com/829663780?share=copy) to understand the difference. There's no way for you to do the same without heavy modification.

**Comment by James4Ever0** [comment]
@abhiprojectz Watch [this video](https://vimeo.com/829663780?share=copy) to understand the difference. There's no way for you to do the same without heavy modification.

For anyone interested in my project, please [join](https://discord.gg/eM5vezJvEQ) official discord group.
