### ISSUE TITLE
Constraints awareness

### ISSUE THREAD

**Issue by Boostrix** [Significant-Gravitas/Auto-GPT#3466]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

There's a bunch of RFEs here using the terms "maximum FOO" (context, tokens, time, memory, space etc).

- #762 
- #3313

Thus, more broadly, it might make sense to encode support for actual constraints as a first class concept into the design, so that under the hood, the system is aware of its own resource utilization (execution time, space, traffic, tokens, context, API usage and so on).

As to API usage/billing, it would currently have to scrape some of the openai pages apparently.

That way, planning would also be better informed/simplified, because the system could take into account the "costs" of its operations.

This sort of thing would also make it possible to constrain the system when it is behind a low-bandwidth connection, and e.g. prioritize other work, to reduce bandwidth utilization 

Could be thought of as the equivalent of Unix/Linux "quotas" - i.e. a way to monitor resource utilization for different types of resources - which also be a great thing for benchmarking purposes

**Comment by Boostrix** [comment]
this is somewhat related, but not identical: #2237

**Comment by johnisanerd** [comment]
I want to echo my support for this idea.  It would be great to be able to constrain resources.

**Comment by Boostrix** [comment]
note that this implies being able to specify custom API keys for sub-agents, too (as mentioned yesterday in an PR)

**Comment by johnisanerd** [comment]
Not knowing the architecture here very well, could it be accomplished as a plugin?

**Comment by Boostrix** [comment]
The plugin-interface is in the process of being revamped as part of #3652 
So, I guess, yes it would be possible - the question is whether that's sensible, given that these "quotas" (will be using that term from now on, since constraints have a different meaning in the context of LLM) will need to be monitored/tracked basically ALL THE TIME when an agent is running a task/objective or planning stage.

Thus, while the code might conceptually reside in plug-in space, it would de facto be a core component -since it would need to be called permanently by the core to track costs of different actions.

Then again, if the core devs should end up not being supportive of the idea, that's certainly an option - but based on some comments I've seen in a few PRs, there's related work going on anyway, so what seems more likely is that this will be implemented "soonish".

Initially, with a focus on tracking "obvious costs" (API use), but probably with means to extend this over time.

To literally track bandwidth, CPU/RAM utilization and disk space, we'd want to use - de facto, wrapping a library like psutil to do in a multi platform fashion:

`import psutil

# CPU utilization
cpu_percent = psutil.cpu_percent()

# RAM utilization
mem = psutil.virtual_memory()
ram_percent = mem.percent

# Disk utilization
disk = psutil.disk_usage('/')
disk_percent = disk.percent

# Network utilization
net_io_counters = psutil.net_io_counters()
bytes_sent = net_io_counters.bytes_sent
bytes_recv = net_io_counters.bytes_recv

print(f"CPU utilization: {cpu_percent}%")
print(f"RAM utilization: {ram_percent}%")
print(f"Disk utilization: {disk_percent}%")
print(f"Bytes sent: {bytes_sent}")
print(f"Bytes received: {bytes_recv}")`

**Comment by johnisanerd** [comment]
You raise an interesting point regarding the use of quotas as a means of controlling robots within a software framework. Quotas can be a powerful tool in limiting the behavior of robots, especially when they are tied to a reporting system that allows for effective oversight.

However, as you suggest, it may be more effective to implement quotas at the main software level, rather than within a plugin. This would ensure that all sub-agents within the system are subject to the same constraints and reporting mechanisms, and that violations are handled consistently across the board.

It's also worth considering the potential trade-offs of using quotas in this way. On the one hand, quotas can help to prevent robots from engaging in harmful or risky behaviors, and can provide a mechanism for catching and correcting errors. On the other hand, overly restrictive quotas could limit the effectiveness of the system and prevent it from achieving its goals.

Ultimately, the decision to use quotas in this way will depend on the specific context and goals of the software framework in question. It may be helpful to experiment with different levels of constraint and to solicit feedback from stakeholders and users to determine the optimal balance between control and flexibility.

**Comment by johnisanerd** [comment]
I guess I was thinking a plugin would be an easy way to deploy it quickly, get user feedback, and then when demonstrated it could become a core feature.

**Comment by zachary-kaelan** [comment]
When it comes to human stuff, it may be worth trying to phrase it in the prompt as a, "very slow but very powerful AGI model for usage when you get stuck", which when called just sends you a message asking for input. We could integrate that into the quota system with some fake numbers to make it tunable in the same way. "Flat $30 per generation with latency of 5 minutes".

**Comment by Boostrix** [comment]
latency is indeed an important consideration, not just network latency, but also "thinking" latency - i.e. the pure process of delegating a task to the [remote] LLM/GPT (and that would even apply if it were local)

**Comment by anonhostpi** [comment]
This will be partially mitigated by the introduction of workspaces in the re-arch. Of course a REST API is also good for linking more than one instance of AutoGPT to another

**Comment by Boostrix** [comment]
> Of course a REST API is also good for linking more than one instance of AutoGPT to another

https://github.com/Significant-Gravitas/Auto-GPT/pull/765

**Comment by Boostrix** [comment]
the new budget manager implementatoin (#4040) is likely to provide a good foundation to experiment with the concept of gathering stats and monitoring/tracking those to comply with some constraints.

From an architectural perspective, it would probably make sense to have the equivalent of a StatsProvider (to capture/provide data), and an actual StatsObserver/Monitor to actually see if the system remains within same well-defined bounds.

Whiile this is straightforward to do for simple metrics like API tokens, number of steps taken, or duration of an execution - system specific stats would be better captured by coming up with an adaptor class to wrap psutil accordingly.

That way, the system could also be told to observer CPU/RAM/DISK utilization etc

**Comment by Boostrix** [comment]
This article goes into detail about lack of contraint awareness/budget management (beyond just API tokens): https://lorenzopieri.com/autogpt_fix/

**Comment by Boostrix** [comment]
For the record, not agreeing with this being "staled" - should probably be re-opened and added to some future milestone?
