### ISSUE TITLE
💡Support Local Embeddings

### ISSUE THREAD

**Issue by MarkSchmidty** [Significant-Gravitas/Auto-GPT#347]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Local Models (LLaMA & its finetunes) now work in a fork of Auto-GPT, including with Pinecone Embeddings. See https://github.com/Torantulino/Auto-GPT/issues/25#issuecomment-1499531177

Local models and embeddings offer better privacy, lower costs, and enable new uses, like Auto-GPT experiments in private/air-gapped networks. To get these benefits, we should add local (offline) embeddings storage and recall to Auto-GPT.

### Examples 🌈

A version of ooba's text-generation-webui, called [wawawario2/long_term_memory](https://github.com/wawawario2/long_term_memory), has done this using zarr and Numpy. Check [wawawario2/long_term_memory#how-it-works-behind-the-scenes](https://github.com/wawawario2/long_term_memory#how-it-works-behind-the-scenes)

![image](https://user-images.githubusercontent.com/5949853/230487779-d6748718-8ee0-49b6-9026-6758b48deaae.png)

Though the Auto-GPT fork uses ooba's webui API for local models, the long_term_memory project is closely tied to ooba's UI. We mention it only as a reference. We need to create a similar setup in Auto-GPT.

### Motivation 🔦

1. Better Privacy: Local embeddings keep user data on their devices or networks, avoiding the risk of online data breaches.
2. Lower Costs: Users save money on cloud storage, bandwidth, and processing power when they use local embeddings.
3. Offline Use: Auto-GPT can work in offline environments or areas with limited internet, like secure facilities or remote research stations.
4. Customization: Users can create and manage their own embeddings for better model performance and results.
5. Faster Response: Local embeddings can speed up response times since data doesn't need to travel to remote servers.

By adding local embeddings storage and recall to Auto-GPT, users get more control, flexibility, and benefits like privacy, cost savings, and accessibility.

**Comment by MarkSchmidty** [comment]
This feature is blocking [Fully Air-Gapped Offline Auto-GPT](https://github.com/Torantulino/Auto-GPT/issues/348)

**Comment by slavakurilyak** [comment]
Related issue https://github.com/Torantulino/Auto-GPT/issues/273

**Comment by 9cento** [comment]
+1
