### ISSUE TITLE
Create GPT Agent Command is Creating Ineffective Agents, and a Fix

### ISSUE THREAD

**Issue by fluxism** [Significant-Gravitas/Auto-GPT#3473]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows Subsystem for Linux (WSL)

### Which version of Auto-GPT are you using?

Master (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

Ask GPT to create an agent for a task.

### Current behavior 😯

GPT creates an agent using a simple, short prompt, usually a single sentence, that is not effective at priming for complex behavior.

### Expected behavior 🤔

Auto-GPT should start the agent with a lengthy prompt well suited to priming it for it's purpose.

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by fluxism** [comment]
Auto-GPT uses the command list that's included in it's prompt as the "instruction manual" for how to use commands. We can alter Auto-GPT's command usage by modifying the command description in prompt.py.

I was able to greatly improve the agent creation by changing the command in prompt.py from:
```
{"name": "<name>", "task": "<short_task_desc>", "prompt": "<prompt>"}
```

to:
```
{"name": "<name>", "task": "<a description of the task being assigned for our own records>", "prompt": "<A lengthy detailed prompt such as 'You are an expert in project management. You will manage any project that is presented to you. You are presented with a tic-tac-toe game project. Please begin to manage the development of this game.'>"}
```

**Comment by Boostrix** [comment]
Not sure, how to edit the wiki - but I suppose, adding commands/plugins could be better documented. Either way, a good starting point might be extending existing commands and plugins



`diff --git a/autogpt/app.py b/autogpt/app.py
index 58d9f71..2d26ce9 100644
--- a/autogpt/app.py
+++ b/autogpt/app.py
@@ -18,7 +18,7 @@ from autogpt.commands.file_operations import (
     search_files,
     write_to_file,
 )
-from autogpt.commands.git_operations import clone_repository
+from autogpt.commands.git_operations import clone_repository, create_repository
 from autogpt.commands.google_search import google_official_search, google_search
 from autogpt.commands.image_gen import generate_image
 from autogpt.commands.improve_code import improve_code
@@ -158,6 +158,10 @@ def execute_command(command_name: str, arguments):
             return get_text_summary(arguments["url"], arguments["question"])
         elif command_name == "get_hyperlinks":
             return get_hyperlinks(arguments["url"])
+        elif command_name == "create_repository":
+            return create_repository(
+                arguments["repo_path"]
+            )
         elif command_name == "clone_repository":
             return clone_repository(
                 arguments["repository_url"], arguments["clone_path"]
diff --git a/autogpt/commands/git_operations.py b/autogpt/commands/git_operations.py
index 028f3b8..24c729e 100644
--- a/autogpt/commands/git_operations.py
+++ b/autogpt/commands/git_operations.py
@@ -1,4 +1,5 @@
 """Git operations for autogpt"""
+import os
 import git
 
 from autogpt.config import Config
@@ -24,3 +25,21 @@ def clone_repository(repo_url: str, clone_path: str) -> str:
         return f"""Cloned {repo_url} to {safe_clone_path}"""
     except Exception as e:
         return f"Error: {str(e)}"
+
+def create_repository(repo_path: str) -> str:
+    """Create a new Git repository
+
+    Args:
+        repo_path (str): The path to create the repository in
+
+    Returns:
+        str: The result of the repository creation operation"""
+    try:
+        safe_repo_path = path_in_workspace(repo_path)
+        os.makedirs(safe_repo_path, exist_ok=True)
+        repo = git.Repo.init(safe_repo_path)
+        return f"""Initialized new Git repository in {safe_repo_path}"""
+    except Exception as e:
+        return f"Error: {str(e)}"
+
+
diff --git a/autogpt/prompt.py b/autogpt/prompt.py
index 0875460..aaa1ac6 100644
--- a/autogpt/prompt.py
+++ b/autogpt/prompt.py
@@ -68,6 +68,11 @@ def get_prompt() -> str:
             "clone_repository",
             {"repository_url": "<url>", "clone_path": "<directory>"},
         ),
+        (
+            "Create Repository",
+            "create_repository",
+            {"repo_path": "<directory>"},
+        ),
         ("Write to file", "write_to_file", {"file": "<file>", "text": "<text>"}),
         ("Read file", "read_file", {"file": "<file>"}),
         ("Append to file", "append_to_file", {"file": "<file>", "text": "<text>"}),
`

**Comment by zachary-kaelan** [comment]
Something else to try is to add another LLM call to the command saying, "expand this to be more detailed". That sounds ridiculous, but [ActionGPT](https://actiongpt.github.io/) does it to get better text to feed another model.

**Comment by Boostrix** [comment]
> I was able to greatly improve the agent creation by changing the command in prompt.py 

that's probably the sort of thing that would better be done via the ai-settings.yaml file ?

**Comment by ntindle** [comment]
> Auto-GPT uses the command list that's included in it's prompt as the "instruction manual" for how to use commands. We can alter Auto-GPT's command usage by modifying the command description in prompt.py.
> 
> I was able to greatly improve the agent creation by changing the command in prompt.py from:
> 
> ```
> {"name": "<name>", "task": "<short_task_desc>", "prompt": "<prompt>"}
> ```
> 
> to:
> 
> ```
> {"name": "<name>", "task": "<a description of the task being assigned for our own records>", "prompt": "<A lengthy detailed prompt such as 'You are an expert in project management. You will manage any project that is presented to you. You are presented with a tic-tac-toe game project. Please begin to manage the development of this game.'>"}
> ```

Have you opened a pr with this? Better prompting helps the whole community and is hard for each individual to do.

**Comment by ntindle** [comment]
> > I was able to greatly improve the agent creation by changing the command in prompt.py
> 
> that's probably the sort of thing that would better be done via the ai-settings.yaml file ?

I’m thinking somewhere else long term and we are working to get there asap

**Comment by Boostrix** [comment]
yaml but would seem like a good format though ?
