### ISSUE TITLE
Looping ModuleNotFoundError after just install it

### ISSUE THREAD

**Issue by trungthanh1288** [Significant-Gravitas/Auto-GPT#3474]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

Executing command 'pip install pandas' in working directory 'J:\AutoGPT\Auto-GPT\InstalledbyShell\Auto-GPT\auto_gpt_workspace'
SYSTEM:  Command execute_shell returned: STDOUT: b'Requirement already satisfied: pandas in ...
after that it keep said ModuleNotFoundError even with install comand above it said Requirement already satisfied
SYSTEM:  Command execute_python_file returned: Traceback (most recent call last): File "/workspace/open_excel.py", line 1, in <module> import pandas as pd ModuleNotFoundError: No module named 'pandas'

### Expected behavior 🤔

Should It recognize installed modules?

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by vaisov** [comment]
Run:
```
pip install -r requirements.txt
```

**Comment by trungthanh1288** [comment]
> Run:
> 
> ```
> pip install -r requirements.txt
> ```

Seriously? It's first thing to run when begin to install AutoGPT

**Comment by k-boikov** [comment]
pandas is not part of AutoGPT, what exactly are you trying to do?

**Comment by trungthanh1288** [comment]
> pandas is not part of AutoGPT, what exactly are you trying to do?

It’s not just pandas. Every modules it try to use is not recognized and it keep trying to install it again. Pandas is just a module fot example

**Comment by ntindle** [comment]
Take a look at your python environment and how it’s configured. Check the commands it’s running with —debug and see if it’s running your expected versions of python. This isn’t an issue with the tool imo but a configuration error. Try and use the #tech-support channel in discord for these issues. We don’t have the capacity to help debug in GitHub issues for problems like this

**Comment by dcbStudios** [comment]
https://github.com/Significant-Gravitas/Auto-GPT/discussions/309

similar issues? There's progress in other attempts to bipass this, also seen that in the env file we crated there is a hashnoted function:

## EXECUTE_LOCAL_COMMANDS - Allow local command execution (Default: False)
## RESTRICT_TO_WORKSPACE - Restrict file operations to workspace ./auto_gpt_workspace (Default: True)
# EXECUTE_LOCAL_COMMANDS=false
# RESTRICT_TO_WORKSPACE=True

changed mine to:

## EXECUTE_LOCAL_COMMANDS - Allow local command execution (Default: False)
## RESTRICT_TO_WORKSPACE - Restrict file operations to workspace ./auto_gpt_workspace (Default: True)
EXECUTE_LOCAL_COMMANDS=True
# RESTRICT_TO_WORKSPACE=True

So far, the agent hasn't mentioned an issue, and i was having issues with pandas as well being ran into. If the problem returns I'll be back to update.

**Comment by crisenvia** [comment]
Thanks a lot!
