### ISSUE TITLE
Loop when create and read py file

### ISSUE THREAD

**Issue by Sr-Grimm** [Significant-Gravitas/Auto-GPT#349]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

just run the prompt

### Current behavior 😯

It keeps looping trying to reach the file when:

1) - Execute the 'calculate.py' file using the 'execute_python_file' command.
 ir outputs that fhe file is not found and then...
2) -  Use the 'list_directory' command to display the contents of the current directory.
 and the file is on the list but when try to run it... go to first step again.
 
 It also tryed to generate a python file to run it but without success.

### Expected behavior 🤔

Find and run the file correctly

### Your prompt 📝

Name: Python file runner

description: Designed to create a run a simple python script

Goal 1: create a python script that sum 2 numbers and print the result
Goal 2: save the file under calculate.py name
Goal 3: execute the file
Goal 4: save the result on result.txt
Goal 5: shut-down

**Comment by OannesGPT** [comment]
I am running in the same issue

**Comment by alexonab** [comment]
Make sure docker is installed and you have permission to run docker commands

`docker run hello-world`

**Comment by OannesGPT** [comment]
> Make sure docker is installed and you have permission to run docker commands
> 
> `docker run hello-world`

Thanks for the tip. I had to enable Virtual Maschine in BIOS to run the Docker now. (...)! I believe it worked! One strange thing though, as you can see: it first states it cant find the file, then proceeds to read the output of the fily anyway -meaning it found the file-:
Executing file 'generate_dinner_recipe.py' in workspace 'auto_gpt_workspace'
[2023-04-07T03:22:43.847792900Z][docker-credential-desktop.EXE][W] Windows version might not be up-to-date: The system cannot find the file specified.
SYSTEM:  Command execute_python_file returned: (...)

BUT, I feel like this was a big step and THANK you

**Comment by Pwuts** [comment]
Closing as resolved
