### ISSUE TITLE
How to make AutoGPT answer me like chatgpt without get web results?

### ISSUE THREAD

**Issue by khanfar** [Significant-Gravitas/Auto-GPT#3504]
How to make AutoGPT answer me like chatgpt without get web results? Just answer me through openai api . Please help

**Comment by onekum** [comment]
This isn't the place for that. You probably want [BetterGPT](https://bettergpt.chat/).

**Comment by k-boikov** [comment]
AutoGPT has a completely different idea. You can just use ChatGPT. Changes are coming soon thou.
