### ISSUE TITLE
'API key is missing or invalid for the environment "us-east4-gcp"' when .env uses "asia-southeast1-gcp"

### ISSUE THREAD

**Issue by ETH3R3AL93** [Significant-Gravitas/Auto-GPT#351]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Attempt to change your PINECONE_ENV and API_KEY values within the .env file to use a new Pinecone project and key.

Seems like pinecone values persist between terminal sessions, restarts and new repo clones.

Using a new api key for "us-east4-gcp" results in same error.

### Current behavior 😯

After creating a new pinecone project in Singapore the script repeatedly tries my old API and ENV values.

PINECONE_ENV=asia-southeast1-gcp

pinecone.core.client.exceptions.UnauthorizedException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'www-authenticate': 'API key is missing or invalid for the environment "us-east4-gcp". Check that the correct environment is specified.', 'content-length': '114', 'date': 'Thu, 06 Apr 2023 23:02:32 GMT', 'server': 'envoy'})
HTTP response body: API key is missing or invalid for the environment "us-east4-gcp". Check that the correct environment is specified.

### Expected behavior 🤔

It should clear old variables for Pinecone and replace with those from .env file

### Your prompt 📝

Default

ai_goals:
- Increase net worth.
- Develop and manage multiple businesses autonomously.
- Play to your strengths as a Large Language Model.
ai_name: Entrepreneur-GPT
ai_role: an AI designed to autonomously develop and run businesses with the sole goal
  of increasing your net worth.

**Comment by Justiniha1** [comment]
I have the same problem, lemme know if you fixed it

**Comment by mrdanpearce** [comment]
I had this happen. I'd stored the PINECONE_API_KEY both in my .env file but also as an environment variable (Windows). Changes to .env file were not overriding the old value stored as an environment variable. 

Looking in `scripts/config.py` it seems the code is picking up the value using `os.getenv("PINECONE_API_KEY")` after calling `load_env()` from the `dotenv` library. `load_env()` will only load environment variables that are not already set in the environment. If an environment variable is already set, its value in the .env file will be ignored.

Deleting the environment variable fixed my issue (or you could update the environment variable).

**Comment by zejacky** [comment]
Same error message as mentioned.
I was searching for environment code (PINECONE_ENV=) inside my elevenlabs account.
However I see only the API Key. Where did you obtain the region code?

Thank you

**Comment by zejacky** [comment]
> Same error message as mentioned. I was searching for environment code (PINECONE_ENV=) inside my elevenlabs account. However I see only the API Key. Where did you obtain the region code?
> 
> Thank you

Just fixed by myself. I was confusing eleven labs with pinecone api key :-)
Didn't  know we need tree different website/account logins!

**Comment by dreiscm** [comment]
> I had this happen. I'd stored the PINECONE_API_KEY both in my .env file but also as an environment variable (Windows). Changes to .env file were not overriding the old value stored as an environment variable.
> 
> Looking in `scripts/config.py` it seems the code is picking up the value using `os.getenv("PINECONE_API_KEY")` after calling `load_env()` from the `dotenv` library. `load_env()` will only load environment variables that are not already set in the environment. If an environment variable is already set, its value in the .env file will be ignored.
> 
> Deleting the environment variable fixed my issue (or you could update the environment variable).

I am sorry, but i do not have this much experience in python. I am now facing the same problem you were. How can i change the environment variables like you did?

**Comment by Explorergt92** [comment]
@ETH3R3AL93 is this still an issue for you or can this be closed?
