### ISSUE TITLE
Setting default value for IMAGE_PROVIDER

### ISSUE THREAD

**Issue by ManishAradwad** [Significant-Gravitas/Auto-GPT#3510]
### ⚠️ Search for existing issues first ⚠️

- [x] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

![Screenshot from 2023-04-29 09-46-10](https://user-images.githubusercontent.com/29497701/235283006-802bac6c-9656-464a-b4a3-20ff84e550d9.png)

### Current behavior 😯

Returns simply the warning "No Image Provider Set" and moves on to the next step
![Screenshot from 2023-04-29 09-47-58](https://user-images.githubusercontent.com/29497701/235283075-f4a076c0-70dd-4ad7-9d1c-ac30532ea384.png)

### Expected behavior 🤔

Instead of returning the warning, we can keep a default Image Provider(maybe `dalle`) if user hasn't specified any. The user will get an output for sure this way.

**Comment by ManishAradwad** [comment]
I'll send a PR soon on this if that's fine

**Comment by guppyO** [comment]
I too am having this issue. "No Image Provider set" even though my .env file has it set to dalle
