### ISSUE TITLE
Use of autogpt without open ai paid api

### ISSUE THREAD

**Issue by joker45op** [Significant-Gravitas/Auto-GPT#3513]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Today i installed autogpt and when i started runnin it it asked for open ai paid api because normal api allows very less api calls. So please add a feature for the ones who don't have a paid api.

**Comment by WifiRouterYT** [comment]
You can use GPT 3-only mode, which can be found in the [docs](https://significant-gravitas.github.io/Auto-GPT/usage/).

> **GPT-3.5 ONLY Mode**
> If you don't have access to GPT-4, this mode allows you to use Auto-GPT!
>
> **`./run.sh --gpt3only`**
> You can achieve the same by setting `SMART_LLM_MODEL` in .env to `gpt-3.5-turbo`.

**Comment by k-boikov** [comment]
Unfortunately that is not up to us, currently there is no implemented alternative to the paid API of open ai. Maybe one day...

**Comment by AlejandroToque** [comment]
Can I use a paid API but with $0,01 limit?
