### ISSUE TITLE
Looking to purchase GPT-4 API Keys

### ISSUE THREAD

**Issue by OpenAI-365** [Significant-Gravitas/Auto-GPT#3517]
I have obtained the GPT-4 API and intend to rent out keys, as it can enable us to achieve higher quality and efficiency with Auto GPT and similar programs.

**Comment by vaisov** [comment]
Are you paying upfront?

**Comment by OpenAI-365** [comment]
> 你是先付钱吗？

Provide a small amount of tokens for trial use, and then officially use them through the website platform.

**Comment by OpenAI-365** [comment]
> Are you paying upfront?

Provide a small amount of tokens for trial use, and then officially use them through the website platform.
