### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by slavakurilyak** [Significant-Gravitas/Auto-GPT#352]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

We should start using Releases in Auto-GPT to help core developers with debugging. By creating releases, we can clearly identify which version of the software we are working with and easily access previous versions. This can be helpful when debugging issues that may be specific to a certain version. We can also use releases to provide release notes and changelogs to users.

Here's a simple way to get started: [GitHub Automatic Releases](https://github.com/marketplace/actions/automatic-releases)

### Motivation 🔦

The lack of Releases in Auto-GPT has made it difficult for core developers to manage and debug different versions of the software. This can lead to confusion and wasted time trying to identify issues that may be specific to a certain version. By implementing Releases, we can streamline the debugging process and provide better support to our users. Additionally, providing release notes and changelogs can help users understand what changes have been made in each version and how it may affect their use of the software.

**Comment by aosan** [comment]
I'm very supportive of this idea. Release management is badly needed.

A larger pool or contributors can review and approve PRs faster in a development branch. Anyone willing and able to play with the latest code can deploy from the development branch. Once features stabilise and are documented, they can be merged in release branch. Those without the skills or inclinations, can use the release packages matching release tags.

I'm ready to help.

**Comment by richbeales** [comment]
done :-)
