### ISSUE TITLE
title

### ISSUE THREAD

**Issue by cdgg1234** [Significant-Gravitas/Auto-GPT#3520]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

How to change the search engine

### Examples 🌈

How to change the search engine

### Motivation 🔦

How to change the search engine

**Comment by vaisov** [comment]
You can use this plug-in to change it to Bing Search if you want: https://github.com/Significant-Gravitas/Auto-GPT-Plugins/tree/master/src/autogpt_plugins/bing_search

**Comment by k-boikov** [comment]
Just change USE_WEB_BROWSER= to whatever you want in your .env. And dont forget to remove the # in the beginning.
