### ISSUE TITLE
is progress really being made? (yes it is)

### ISSUE THREAD

**Issue by raymerjacque** [Significant-Gravitas/Auto-GPT#3524]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

seems every time i run auto-gpt it spends the first hour just going in circles... 20 minutes trying to execute some non existent python script, 2 hours doing meaningless research on the same 5 websites over and over again.... and all the while the bill ticks over at openai .... i know someone who against my advice ran it in continuous mode and ended up with a $50 bill and nothing to show for it except a few empty or barely filles meaningless files in the workspace, many of them duplicated like the bots had tried to start the same task many times over. I have created multiple applications on my own and also with the help of a single AI bot and finished 2 of them so far and my friend still hasnt gotten anywhere with auto-gpt 2 weeks later... what are you guys doing ? i think the priorities here are all over the place, much like the autonomous AI....

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by comienzo2093** [comment]
> 

Even in my case, gpt-3.5 was really stupid and often didn't function properly. After switching to gpt-4, I experienced a huge change.

**Comment by ram-sh** [comment]
> > 
> 
> Even in my case, gpt-3.5 was really stupid and often didn't function properly. After switching to gpt-4, I experienced a huge change.

how long did you wait on the waiting list until getting the gpt-4 key?

**Comment by raymerjacque** [comment]
one of the biggest issue here is that you cant steer the script when it goes off course... you cant say "why bot, stop your sh!t and get back on track, focus on x or y" .... i think this leads to endless automation that is pointless.

**Comment by comienzo2093** [comment]
> > 내 경우에도, gpt-3.5는 정말 멍청했고 종종 제대로 작동하지 않았다. gpt-4로 전환한 후, 나는 큰 변화를 경험했다. > > gpt-4 키를 받을 때까지 대기자 명단에서 얼마나 기다렸나요? 24hour

> > Even in my case, gpt-3.5 was really stupid and often didn't function properly. After switching to gpt-4, I experienced a huge change.
> 
> how long did you wait on the waiting list until getting the gpt-4 key?


I applied a month ago but didn't get it. After waiting, I applied again yesterday and got access to the api today.

**Comment by Pwuts** [comment]
We're working hard on reworking the memory system, that should bring a huge performance increase and resolve a lot of looping issues.

**Comment by Kenshiro-28** [comment]
Related to this:

https://github.com/Significant-Gravitas/Auto-GPT/issues/3428

Auto-GPT shouldn't create python scripts on the fly, at least not when using GPT-3. These "helper" scripts make impossible to finish even some trivial tasks that you can do just using the web chat.

**Comment by raymerjacque** [comment]
> We're working hard on reworking the memory system, that should bring a huge performance increase and resolve a lot of looping issues.
> 
> If you want to know what we're up to, check out our [kanban](https://github.com/orgs/Significant-Gravitas/projects/1/views/1) and [roadmap](https://github.com/orgs/Significant-Gravitas/projects/2/views/1).

you do know this still doesnt run on some linux systems due to spaCy ...  i reported this, nothing was done, i even presented an alternative nltk to use instead of spaCy that achieves exactly the same thing and is compatible with all systems, still i was ignored...  so im not sure exactly how you can say yes... some people cant even boot it.

**Comment by Pwuts** [comment]
Nobody except yourself reported that issue to us, and we stick with spaCy also because it seems to outperform NTLK overall.

**Comment by raymerjacque** [comment]
the ego on you ... i dont need you to fix anything, i forked it and fixed it myself. UNLIKE you, i asked you to fix it your side so that others that encounter the issue that may not know how to fix it will not have to struggle with setup. I am perfectly capable of fixing my own issues thank you. UNLIKE you, i consider other people...

**Comment by ntindle** [comment]
You came here and asked us if something we are pouring hundreds of hours a week into is making progress. How did you expect us to react? Of course we wouldn’t say no. 

How would you feel if I looked at a mountain of work that you’ve accomplished and asked “does it do anything” and then started prioritizing what you should work on next without the full context of the goals and problems. If I did that to you, I’d come across as a real jerk to say the least.  

I’m going to lock this conversation because it won’t be productive to the team to continue this but I want you to look in the mirror and consider that saying “unlike you I consider people” may not be considerate of the people you’re saying it to.
