### ISSUE TITLE
significantgravitas/auto-gpt:latest does not exist

### ISSUE THREAD

**Issue by atrifex** [Significant-Gravitas/Auto-GPT#3540]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

docker pull significantgravitas/auto-gpt:latest

### Current behavior 😯

> ERROR: manifest for significantgravitas/auto-gpt:latest not found: manifest unknown: manifest unknown

### Expected behavior 🤔

Pull correctly.

### Your prompt 📝

N/A

### Your Logs 📒

N/A

**Comment by ReDNeQ** [comment]
Same issue as well

**Comment by bobisme** [comment]
to devs reading this who have access to docker hub, you can just add tags to an existing image and push them.

```shell
docker tag SOURCE_IMAGE[:TAG] TARGET_IMAGE[:TAG]
```

**Comment by NickAtGit** [comment]
This helped: `docker pull significantgravitas/auto-gpt:0.2.2`

**Comment by k-boikov** [comment]
Duplicate https://github.com/Significant-Gravitas/Auto-GPT/issues/3403
