### ISSUE TITLE
Add an ability to continue a run after exit

### ISSUE THREAD

**Issue by Yolley** [Significant-Gravitas/Auto-GPT#3542]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Currently each time when we start auto-gpt, even if we want to continue running with existing `ai_settings.yaml` and logs, it calls `start_interaction_loop` of gpt agent. On first iteration this function always sends a prompt to GPT. But what if we had auto-gpt running and then stopped it manually before running a command (or had a power outage)? And then we want it continue running from this command? What was the reasoning behind making auto-gpt always run from ground up, even if there is available `ai_settings.yaml` and we want to continue running with it?

It doesn't seem that hard to support it, we will just need to preserve `full_message_history` and not clear `memory` on each run (and also do the same for every agent in agent_manager I guess). So I'd just like to know why this feature hasn't been considered initially? I can think and try to implement it, but first I need to understand if it doesn't go against the design of the project.

There are some active issues addressing it like https://github.com/Significant-Gravitas/Auto-GPT/issues/1176 or https://github.com/Significant-Gravitas/Auto-GPT/issues/822, but it doesn't seem that they also address the core issue that `start_interaction_loop` always run initial prompt for some reason, what was the reasoning behind that (and why don't we allow to persist message history between `auto-gpt` launches)?

### Motivation 🔦

It will be pretty convenient for cases when for example user shutdowns their pc or electricity crashes and their auto-gpt stops running, and they want to continue running from the **exact** step they were stopped at.

**Comment by Boostrix** [comment]
in another issue I mentioned that I extended git support a little more - in practice, that would make it pretty straightforward to dump all interaction to a git repo and commit the current state, to be able tor revert/continue later on.
