### ISSUE TITLE
Consumer key must be string or bytes, not NoneType

### ISSUE THREAD

**Issue by gamehendge02** [Significant-Gravitas/Auto-GPT#3544]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

After adding Twitter API keys and bearer token to the .env file, I ask to send a test Tweet with today's date

> 

### Current behavior 😯

Consumer key must be string or bytes, not NoneType

### Expected behavior 🤔

Send Test Tweet with todays date

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by gamehendge02** [comment]
After a fresh install of everything I still get the same error when attempting a test tweet
(Consumer key must be string or bytes, not NoneType)

Seems like it's not actually reading the env file. 
I also have set env to use firefox but get the following:

Using memory of type:  LocalCache
Using Browser:  chrome

**Comment by bobisme** [comment]
how are you running it?

**Comment by gamehendge02** [comment]
with ./run.sh
the env file is in the same folder as run.sh

**Comment by bobisme** [comment]
this maybe a pointless question, but is the file named ".env" or "env"?

**Comment by gamehendge02** [comment]
Its named ".env"
I used the command `cp .env.template .env` from the install guide
