### ISSUE TITLE
Eliminate prompting to enable plugins not in ALLOWLISTED_PLUGINS

### ISSUE THREAD

**Issue by askpatrickw** [Significant-Gravitas/Auto-GPT#3555]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

`WARNING: Plugin AutoGPTEmailPlugin found. But not in the allowlist... Load? (y/n):`

These prompts don't feel necessary and they create more than one path for how things work which can be confusing.

### Examples 🌈

I could see fixing this two ways:

1. Remove these prompts completely. If a plugin is not in ALLOWLISTED_PLUGINS, it won't run.
2. Add a way to disable these prompts or have `--skip-reprompt` also skip these prompts.

My opinion is the first option is easier to implement (removes code) and makes for a very deterministic system where the plugins enabled run and those which are not enabled do not.

### Motivation 🔦

I think the plugins could be more deterministic an easier to understand what is going on.

Scenarios:
- As a new user, If I don't want certain plugins to run, I don't put them in the allowed list. Why am I being asked to run them? Should I run them? Did I do something wrong? ;-)
- As an experienced user, stop asking me to run things I've not enabled.

**Comment by ntindle** [comment]
Yeah that makes sense. Would you prefer —prompt-plugins rather than skip prompt?

**Comment by levlevin** [comment]
I agree, especially given that first party plugins are bundled together by default. Wouldn't it make more sense to set this in .env, next to allowlisted plugins? I think this should be set globally once

**Comment by askpatrickw** [comment]
Yeah, I think there should be NO prompting. Run what is configured to run.
