### ISSUE TITLE
Support other Programming Languages

### ISSUE THREAD

**Issue by BlueNebulaDev** [Significant-Gravitas/Auto-GPT#356]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

I'm wondering whether Auto-GPT, even if it's written in Python, could support other programming languages as well, since GPT is able to program in multiple ones.

I'm also thinking that Auto-GPT could be more effective in languages with a good type system, like Rust or Haskell. That's because function signatures give a lot of information to understand what a function does: we could be very efficient in token usage, if we transmitted function signatures without a function body.

**Comment by nponeccop** [comment]
Forget about Haskell. My tests show a pretty low capability of recursion. So, while there are workarounds, it's actually easier for the model to use untyped languages, just like for humans.

Also, the stability is important. Many node.js libraries are 8 years old and stable, so ChatGPT is able to use them out of the box. But with Haskell or Rust they move too fast, you need a model trained on the version you are going to use, to the very least.
