### ISSUE TITLE
Huggingface Audio-to-text is not working

### ISSUE THREAD

**Issue by zenchantlive** [Significant-Gravitas/Auto-GPT#3573]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

Ask it to listen to an audio file and summarize.

### Current behavior 😯

Propmt is supposed to listen to a downloaded file with huggingface audio-to-text and be able to summarize it. 

### Expected behavior 🤔

I am unable to get it to listen to the audio, it just trys to make a python script to do so itself and coninues to fail. How should iI prompt it, or is there something wrong?

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by k-boikov** [comment]
Please provide prompt, logs and better steps to reproduce it.
