### ISSUE TITLE
Docker: Error response from daemon

### ISSUE THREAD

**Issue by NickAtGit** [Significant-Gravitas/Auto-GPT#3574]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

Follow the steps at: Set up with Docker (https://significant-gravitas.github.io/Auto-GPT/setup/)
At step 2 the error occurs.

### Current behavior 😯

Error: Error response from daemon: manifest for significantgravitas/auto-gpt:latest not found: manifest unknown: manifest unknown

### Expected behavior 🤔

No error

### Your prompt 📝

```yaml
None
```

### Your Logs 📒

AutoGPT % docker pull significantgravitas/auto-gpt

Using default tag: latest
Error response from daemon: manifest for significantgravitas/auto-gpt:latest not found: manifest unknown: manifest unknown

**Comment by k-boikov** [comment]
Duplicate https://github.com/Significant-Gravitas/Auto-GPT/issues/3403
