### ISSUE TITLE
bad choice of command "execute shell" instead of "google"

### ISSUE THREAD

**Issue by SimDamDev** [Significant-Gravitas/Auto-GPT#3577]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Master (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

input on start : 
I want Auto-GPT to: search the latest news on google, save on local file

### Current behavior 😯

it want to use "execute shell" to doing research on google

### Expected behavior 🤔

use "google" for doing research on google

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here. If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag # INCLUDED COMMAND 'send_tweet' IS DEPRICATED, AND WILL BE REMOVED IN THE NEXT STABLE RELEASE Base Twitter functionality (and more) is now covered by plugins: https://github.com/Significant-Gravitas/Auto-GPT-Plugins ## Changes to Docker configuration The workdir has been changed from /home/appuser to /app. Be sure to update any volume mounts accordingly.
WARNING:  You are running on `master` branch - this is not a supported branch.
Welcome back!  Would you like me to return to being AIGPT?
  Asking user via keyboard...
Continue with the last settings?
Name:  AIGPT
Role:  an autonomous agent that specializes in information gathering and language translation to assist in research and knowledge management tasks.
Goals: ['Conduct a thorough search on Google for the best practices of UI and UX and compile the information into a local file.', 'Create two versions of the file: one in French for human consumption and one in a format optimized for consumption by other AI systems.', 'Utilize advanced language translation capabilities to accurately translate the information into French.', 'Ensure that the file optimized for consumption by other AI systems is in a format that is easily readable and usable by other AI systems.', 'Provide a detailed report of the search process and the resulting files to the user for review and further action.']
API Budget: infinite
Continue (y/n): n
Welcome to Auto-GPT!  run with '--help' for more information.
Create an AI-Assistant:  input '--manual' to enter manual mode.
  Asking user via keyboard...
I want Auto-GPT to: search the latest news on google, save on local file
NewsGPT  has been created with the following details:
Name:  NewsGPT
Role:  an autonomous agent that searches the latest news on Google and saves them on a local file for easy access and reference.
Goals:
-  Conduct efficient and accurate searches on Google to retrieve the latest news articles.
-  Filter and select relevant news articles based on user-specified keywords and topics.
-  Save the selected news articles in a local file in a user-friendly format for easy access and reference.
-  Continuously update the local file with the latest news articles to ensure the user has access to the most up-to-date information.
-  Provide a user-friendly interface for the user to specify search criteria and access the saved news articles.
Using memory of type:  PineconeMemory
Using Browser:  chrome
 THOUGHTS:  I should start by searching for the latest news articles on Google.
REASONING:  My goal is to retrieve the latest news articles and save them in a local file for easy access and reference. Searching on Google is the best way to achieve this goal.
PLAN:
-  Use the 'execute_shell' command to open a web browser and navigate to Google.
-  Use the 'write_to_file' command to save the search results in a local file.
-  Use the 'search_files' command to retrieve the saved news articles.
CRITICISM:  I need to ensure that I am searching for relevant news articles and not just any articles that match my search criteria.
NEXT ACTION:  COMMAND = execute_shell ARGUMENTS = {'command_line': 'start chrome https://www.google.com'}
  Enter 'y' to authorise command, 'y -N' to run N continuous commands, 's' to run self-feedback commands'n' to exit program, or enter feedback for ...
  Asking user via keyboard...
Input:

**Comment by hhiggs1** [comment]
I also have the same issue of not being asked the AI Name.

2023-05-05 22:42:46,852 INFO Welcome to Auto-GPT!  run with '--help' for more information.
2023-05-05 22:42:47,140 INFO Create an AI-Assistant: input '--manual' to enter manual mode.
2023-05-05 22:42:47,404 INFO  Asking user via keyboard...

not sure why they are putting --help or manual in the response.

Can anyone help here?
