### ISSUE TITLE
The model gpt-4 does not exists

### ISSUE THREAD

**Issue by Xerizaf** [Significant-Gravitas/Auto-GPT#3584]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Master (branch)

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

Run properly

### Current behavior 😯

openai.error.InvalidRequestError: The model: `gpt-4` does not exist

### Expected behavior 🤔

To run properly

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by k-boikov** [comment]
In order to use GPT4 you need to apply here. https://openai.com/waitlist/gpt-4-api https://significant-gravitas.github.io/Auto-GPT/usage/****

**Comment by BartNetJS** [comment]
I have the same issue, but with a paid subscription and a valid key.
What can be the issue?
