### ISSUE TITLE
Raise APIError while 500 error is returned.

### ISSUE THREAD

**Issue by jung-hunsoo** [Significant-Gravitas/Auto-GPT#3607]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows Subsystem for Linux (WSL)

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

No specific conditions are requred to reproduce this issue.

It's just an unexpected behavior.

### Current behavior 😯

![image](https://user-images.githubusercontent.com/6870447/235403864-955d1219-0d79-41c0-ba04-dd3f462314e2.png)

### Expected behavior 🤔

Handle exception and continue to next job.

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

See the attached image above

**Comment by varunponda** [comment]
Hey @jung-hunsoo, This issue has already been reported #2553. Please feel free to follow that issue for updates and to add any additional information or comments there.

**Comment by anonhostpi** [comment]
Hmm... I'm not sure how the backoff #214 handles response codes, but it may be worth implementing a try...catch around OpenAI calls that log these errors, but also instruct the user to check http://status.openai.com/ or to check 3rd party down dectectors like https://downdetector.com/status/openai/ in the specific case of 401+ errors.

Most 401+ errors from the OpenAI module are tied to how the OpenAI servers handles the http requests

Maybe worth even logging different suggested solutions to the user depending on each response code:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
