### ISSUE TITLE
still thinking and not working

### ISSUE THREAD

**Issue by ewilner** [Significant-Gravitas/Auto-GPT#3609]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

It is still thinking and nothing came up yet for over 1 hour.

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by deeprathod** [comment]
Facing the same issue. Endless loop of Thinking.
