### ISSUE TITLE
Ability to point to private LLM deployments

### ISSUE THREAD

**Issue by vineetvermait** [Significant-Gravitas/Auto-GPT#3610]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Instead of charged plan of OpenAI, could we have a plugin/feature where a LLM model like Vicuna or some other model deployed on local/cloud could be used . Something similar to what invoke AI or Automatic1111 SD  web ui.

### Motivation 🔦

I want to bypass the chat GPT costing and use my own LLMs for the same

**Comment by Boostrix** [comment]
Please see: #2158

**Comment by MarkSchmidty** [comment]
Dupe of #25
