### ISSUE TITLE
window run: .\run.bat  error 

### ISSUE THREAD

**Issue by lishiyi1111** [Significant-Gravitas/Auto-GPT#3614]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

s/download/en_core_web_sm-3.4.0/en_core_web_sm-3.4.0-py3-none-any.whl
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)'))': /explosion/spacy-models/releases/download/en_core_web_sm-3.4.0/en_core_web_sm-3.4.0-py3-none-any.whl
ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /explosion/spacy-models/releases/download/en_core_web_sm-3.4.0/en_core_web_sm-3.4.0-py3-none-any.whl (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)')))

Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)'))) - skipping
Traceback (most recent call last):
  File "D:\Anaconda\envs\auto-gpt\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Anaconda\envs\auto-gpt\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Auto-GPT\Auto-GPT-stable-0.2.2\autogpt\__main__.py", line 2, in <module>
    import autogpt.cli
  File "D:\Auto-GPT\Auto-GPT-stable-0.2.2\autogpt\cli.py", line 2, in <module>
    import click
ModuleNotFoundError: No module named 'click'
请按任意键继续. . .

### Current behavior 😯

s/download/en_core_web_sm-3.4.0/en_core_web_sm-3.4.0-py3-none-any.whl
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)'))': /explosion/spacy-models/releases/download/en_core_web_sm-3.4.0/en_core_web_sm-3.4.0-py3-none-any.whl
ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /explosion/spacy-models/releases/download/en_core_web_sm-3.4.0/en_core_web_sm-3.4.0-py3-none-any.whl (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)')))

Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)'))) - skipping
Traceback (most recent call last):
  File "D:\Anaconda\envs\auto-gpt\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Anaconda\envs\auto-gpt\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Auto-GPT\Auto-GPT-stable-0.2.2\autogpt\__main__.py", line 2, in <module>
    import autogpt.cli
  File "D:\Auto-GPT\Auto-GPT-stable-0.2.2\autogpt\cli.py", line 2, in <module>
    import click
ModuleNotFoundError: No module named 'click'
请按任意键继续. . .

### Expected behavior 🤔

should download something

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by k-boikov** [comment]
Seems like you have an internet issue. Are you in China?

**Comment by lishiyi1111** [comment]
> 

Yes，thanks a lot for your reply, my internet is not stable, although I used vpn. Now it's working, but the download rate is so low.
