### ISSUE TITLE
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'speech.mpeg'

### ISSUE THREAD

**Issue by nekohacker591** [Significant-Gravitas/Auto-GPT#362]
### Duplicates

- [X] I have searched the existing issues

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by mdmrs** [comment]
f

**Comment by AviadDahan** [comment]
same here

**Comment by BillSchumacher** [comment]
If you're still have an issue please re-open.

**Comment by ezzyland** [comment]
hey brother, tech noob here. is the issue resolved? im trying to run autogpt with tts but i get this error. how do i fix this?
