### ISSUE TITLE
Im using version Merge pull request #2625 from Significant-Gravitas/stable-0.2.2 but I still cannott use my pinecone in the system as i get the following warning    - WARNING:  You are running on master branch - this is not a supported branch. 

### ISSUE THREAD

**Issue by deepaks005** [Significant-Gravitas/Auto-GPT#3626]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

Im using version Merge pull request #2625 from Significant-Gravitas/stable-0.2.2 
but I still cannot use my pinecone in the system as i get the following warning    - WARNING:  You are running on master branch - this is not a supported branch. 

### Current behavior 😯

Still using local cache

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by k-boikov** [comment]
That is a warning, not an error, what is the actual error?

**Comment by ether8unny** [comment]
git checkout -b stable-0.2.2

**Comment by deepaks005** [comment]
> That is a warning, not an error, what is the actual error?

WARNING:  You are running on `master` branch - this is not a supported branch

This is the warning 

I am using stable version 2.2 yet am getting this error 

This is from my VS code log 
2023-05-02 16:08:55,641 INFO WARNING:  You are running on `master` branch - this is not a supported branch.

**Comment by deepaks005** [comment]
> git checkout -b stable-0.2.2

I did this is what I am running
