### ISSUE TITLE
Issue with the API-Key

### ISSUE THREAD

**Issue by John-x75** [Significant-Gravitas/Auto-GPT#3636]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

I tried ./run.sh

but I just get this: 

Warning: The file 'auto-gpt.json' does not exist. Local memory would not be saved to a file.
Please set your OpenAI API key in .env or as an environment variable.
You can get your key from https://platform.openai.com/account/api-keys
Press any key to continue...

I already tried creating a new API Key and it still did not work.

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by ColbyLeeCode** [comment]
Check if you have a blank .env file in the autogpt folder, if so, delete it. I have found a blank .env file sometimes is created here which causes this error, although mine only seems to appear when using Docker, then when I go to run without Docker this blank .env file causes issues.

**Comment by Boostrix** [comment]
that would seem like something that could be easily detected in Python to show a corresponding warning to the user and optionally recreate the file ?

**Comment by WillDudley** [comment]
Same issue, Windows 11 with Docker Desktop. The only files in my `Auto-GPT` directory are `.env`, `.env.template`, `docker-compose`.  I followed the setup instructions at https://docs.agpt.co/setup/.

**Comment by WillDudley** [comment]
> Same issue, Windows 11 with Docker Desktop. The only files in my `Auto-GPT` directory are `.env`, `.env.template`, `docker-compose`. I followed the setup instructions at https://docs.agpt.co/setup/.

Update - It works [for me] using the terminal command provided in a terminal made by VSCode, instead of fiddling with the gui of Docker Desktop. May have been a path issue.

**Comment by ColbyLeeCode** [comment]
> Same issue, Windows 11 with Docker Desktop. The only files in my `Auto-GPT` directory are `.env`, `.env.template`, `docker-compose`. I followed the setup instructions at https://docs.agpt.co/setup/.

Just confirming the location I find the blank .env file:

Auto-GPT\autogpt\.env  <- This is always blank

Then there is another in Auto-GPT root that is the .env file that should be used.

**Comment by John-x75** [comment]
Rurns out, I simply had to type "export OPENAI_API_KEY=[my-openaikey]" and it just ran the ./run.sh command.

**Comment by Boostrix** [comment]
from a usability standpoint it would make sense to add some heuristics that detect the missing env file/key in combination with the environment variable not being set. At least to show some info to newcomers ?
