### ISSUE TITLE
Name a Price

### ISSUE THREAD

**Issue by johnisanerd** [Significant-Gravitas/Auto-GPT#3641]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

I'd like a feature where a user can name a price for what they're searching for.  This could be similar to the "continuous mode" feature, but it should be a "continuous up until this particular price".  So it can give the robot freedom to search for information to try to do something, up until a certain budget has been met.

### Motivation 🔦

I'd like to set more robots up to run, I'm afraid of them going off the rails and driving my bill up.

**Comment by Boostrix** [comment]
See #3466
