### ISSUE TITLE
Improve test coverage for Auto-GPT

### ISSUE THREAD

**Issue by slavakurilyak** [Significant-Gravitas/Auto-GPT#368]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

N/A

### Current behavior 😯

Auto-GPT has limited test coverage, which makes it difficult to ensure that changes to the codebase do not introduce new bugs or regressions. 

Given the [latest commit](https://github.com/Torantulino/Auto-GPT/commit/c6d90227fecec8acc1481c486a91337b07e8a820), testing is now part of all new pull requests.

### Expected behavior 🤔

By improving test coverage, we can ensure that the codebase is more robust and that future changes can be made with confidence.

### Your prompt 📝

N/A (since this issue is not related to a specific prompt)

**Comment by ntindle** [comment]
Wip
