### ISSUE TITLE
Unable to automatically generate AI Config based on user desire.

### ISSUE THREAD

**Issue by saimonsays1991** [Significant-Gravitas/Auto-GPT#3726]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

I entered this text I want Auto-GPT to: I want you to be the Best SEO manager for the site dargenta.com which is built on wix editor, and I am your helper, making the necessary changes to the site.

### Current behavior 😯

Unable to automatically generate AI Config based on user desire.  Falling back to manual mode.

### Expected behavior 🤔

Understand my desire?

### Your prompt 📝

```yaml
# Paste your prompt here
```
I want you to be the Best SEO manager for the site dargenta.com which is built on wix editor, and I am your helper, making the necessary changes to the site.

### Your Logs 📒

```log
<insert your logs here>
```
d

**Comment by arrenv** [comment]
@saimonsays1991 I tested your prompt on `stable` with GPT-3.5 and got the following result.

![image](https://user-images.githubusercontent.com/33682027/235883128-ec1e1df7-413c-4fb2-bf73-ed8ac961cc35.png)

Would you mind sharing a screenshot to demonstrate?

**Comment by k-boikov** [comment]
The initial prompt you entered was too complicated for the LLM to generate a general thoughts and plan to follow, change it or make it more simple and it should work.

**Comment by iT-Boyer** [comment]
on `stable` is OK. but the same issue on `master` ，
