### ISSUE TITLE
Error: unknown error: cannot find Chrome binary

### ISSUE THREAD

**Issue by necessities** [Significant-Gravitas/Auto-GPT#3738]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

Default behavior after fresh install of 3.0 release on windows 11 vm.

### Current behavior 😯

When the agent goes to browse a website it fails with this error:

SYSTEM:  Command browse_website returned: ('Error: unknown error: cannot find Chrome binary', None)

Then it continues to try other commands.

 THOUGHTS:  I was unable to browse the website due to an error.

### Expected behavior 🤔

Ability to browse website. 

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
2023-05-03 05:56:10,872 INFO  Asking user via keyboard...
2023-05-03 05:56:13,165 INFO -=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
2023-05-03 05:56:19,226 INFO SYSTEM:  Command browse_website returned: ('Error: unknown error: cannot find Chrome binary', None)
2023-05-03 05:56:39,207 INFO  THOUGHTS: I was unable to browse the website due to an error. I will try using the 'google' command to find 
```

**Comment by k-boikov** [comment]
Maybe check this https://github.com/Significant-Gravitas/Auto-GPT/issues/1517

**Comment by glasgowm148** [comment]
Same problems on MacOSX Silicon. Tried troubleshooting and making sure chrome was on path. No joy.

**Comment by glasgowm148** [comment]
Same issue on OSX/Silicon, Chrome is installed and added to my zsh path. I guess it's because it can't access the binary from within docker?

**Comment by glasgowm148** [comment]
Broken for me on MacOSX Silicon even with chrome installed and on my ZSH path. 

Creating an `.env` file with 
```
USE_WEB_BROWSER=firefox
```

solved the issue
