### ISSUE TITLE
New Ports Beyond OpenAI

### ISSUE THREAD

**Issue by XaviscoB** [Significant-Gravitas/Auto-GPT#3751]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

As you know/know the OpenAI API is limited and costs money to use it, this limits the range of users who can use Auto-GPT due to the cost of the API, I would like to suggest that support be placed for other types of API in addition to OpenAI, because yes there are free APIs that use ChatGPT as a model, there is even the uesleibros project, which provides an easy way to use other APIs for free that make ChatGPT available, being able to easily integrate with other applications is for free

I'll leave the link to the Project if you're interested in seeing it

https://github.com/uesleibros/OpenGPT

### Examples 🌈

[OpenGPT](https://github.com/uesleibros/OpenGPT)

### Motivation 🔦

I believe that this would bring greater performance to the project and more accessibility for people who cannot or cannot afford to pay for the OpenAI API, as is my case.

**Comment by Apollyon81** [comment]
Openai partnered with auto gpt to monetize this pay API idea, for now we have to wait for a no-pay way

**Comment by k-boikov** [comment]
AutoGPT is an open source project, and the OG developer never thought it will become so big. It was not really planned from the beginning to be multifunctional and universal LLM Agent. We are currently at version 0.something, aka really beta. The concern you have is currently been addressed among the core devs and a solution will eventually come. When and how - we still do not know. In the meantime, as I mentioned earlier, its an open source project - you can just try to contribute and help with PRs to push the project towards your goal.

**Comment by Boostrix** [comment]
See #2158 and #2777

**Comment by Boostrix** [comment]
well, we discussed dedicated labels for issues involving multiple/offline LLMs, not sure what happened to all of those requests - but meanwhile, I cannot even help labelling anymore: https://discord.com/channels/1092243196446249134/1115627061780938812/1115627067262902364
