### ISSUE TITLE
ChatGPT instead OpenAI KEY

### ISSUE THREAD

**Issue by IT-EXPRESS-Munich** [Significant-Gravitas/Auto-GPT#3767]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

I and thousands of other users would like to be able to use ChatGPT instead of the API, that would be possible with ChromeWebDriver and GO plugins/programming, the whole thing could be connected as a plugin. That would significantly reduce costs and further development would be significantly increased because you can then experiment more. you can take an example from whatsappGPT (not my project and also no advertising, only suggested for development improvement) https://github.com/danielgross/whatsapp-gpt

### Examples 🌈

https://github.com/danielgross/whatsapp-gpt
-Go Programming with ChromeWebDriver

### Motivation 🔦

-

**Comment by anonhostpi** [comment]
I would look into licensing before doing this.

I doubt that ChatGPT allows you to use their web portal like this. I'd also look into the licensing for WebDriver tech. Most WebDriver technologies are strictly for unit testing, and not automating.

**Comment by IT-EXPRESS-Munich** [comment]
> I would look into licensing before doing this.
> 
> I doubt that ChatGPT allows you to use their web portal like this. I'd also look into the licensing for WebDriver tech. Most WebDriver technologies are strictly for unit testing, and not automating.

webdriver shows a message like in the example whatsappgpt that chromedriver is controlled by automated software, chatgpt is accessed in the same way

**Comment by anonhostpi** [comment]
> webdriver shows a message like in the example whatsappgpt that chromedriver is controlled by automated software, chatgpt is accessed in the same way

That message tells the user that you are currently scraping. It doesn't prevent the user from actually doing it.

If scraping the web portal goes against OpenAI's ToS (which I suspect it probably does), this is not something developers should support.

Perhaps as a plugin, but even then, that's a liability risk.
