### ISSUE TITLE
Calculate [expression] command / plugin

### ISSUE THREAD

**Issue by Boostrix** [Significant-Gravitas/Auto-GPT#3775]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

For the time being, any time an agent needs to compute a calculation it needs to resort to CLI tools (which may be disabled) or to writing/executing custom Python code.

Given that calculations are such a common/useful thing, it would probably  make sense to come up with a dedicated plugin that adds a "do_calculation" command, based on handing that to a Python library like SymPy/

### Motivation 🔦

get rid of having to write custom python code or having to invoke platform specific CLI tools that may not be accessible for some users.

**Comment by Boostrix** [comment]
Plugin candidate, once the dust settles with #3652

**Comment by anonhostpi** [comment]
Not sure about this one, but I do think it brings up a good point about Inversion of Control. The commands written for this repository should be loosely coupled, so they can be hotswapped with other implementations.

**Comment by Boostrix** [comment]
on any *nix problem, there is zero problem obviously, because you inevitably have got access to stuff like bc and friends. But this being a cross-platform project ...

**Comment by anonhostpi** [comment]
Added this to discussion #3856
