### ISSUE TITLE
Chrome failed to start: exited abnormally.

### ISSUE THREAD

**Issue by pryadchenko** [Significant-Gravitas/Auto-GPT#3779]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Docker

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

I run docker according to manual via docker compose on MacOS. Use default config. Docker image is significantgravitas/auto-gpt:latest which corresponds to v.0.3.0

### Current behavior 😯

One of actions was `NEXT ACTION:  COMMAND = browse_website ARGUMENTS = {'url': 'https://pa...`
But it lead to the following error:
`SYSTEM:  Command browse_website returned: ('Error: unknown error: Chrome failed to start: exited abnormally.', None)`

error.log is empty

### Expected behavior 🤔

I guess AutoGPT enable brows websites.

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by cdelgadob** [comment]
I am having the same issue, but after that, the next action is using the `google` command:

```
SYSTEM:  Command browse_website returned: ('Error: unknown error: Chrome failed to start: exited abnormally.', None)
 THOUGHTS:  Since the browse_website command failed, I will use the google command to search for information on El Puerto de Santa Maria.
REASONING:  Google is a reliable source of information and can provide me with a wide range of sources to choose from.
PLAN:
-  Use the google command to search for information on El Puerto de Santa Maria
-  Use the information to provide accurate and up-to-date recommendations
-  Continuously learn and improve recommendations based on feedback and data sources
CRITICISM:  I need to make sure that I am using reliable sources and that the information I gather is accurate and up-to-date.
NEXT ACTION:  COMMAND = google ARGUMENTS = {'query': 'El Puerto de Santa Maria'}
SYSTEM:  Command google returned: [ { "title": "Puerto de Santa María, El -...
```

**Comment by martinst** [comment]
I am experiencing the exact same issue.

**Comment by Stooovie** [comment]
same on Ventura 13.3.1

**Comment by boris-lapouga** [comment]
Same issue. GPT4, docker-compose 2.17.3, MacOS Ventura 13.3.1 (a), M1 MX

**Comment by broadway01** [comment]
Same issue, GPT3/4, docker-compose 2.17.3, MacOS Ventura 13.2.1, M2 Pro

**Comment by wingsum93** [comment]
I am experiencing the exact same issue .
i am using the docker to run it.

**Comment by lreynes** [comment]
I'm having the same issue, Ventura 13.2.1, using docker.

**Comment by ferisjuan** [comment]
Same on M1 Pro Ventura 13.3.1, using docker

**Comment by ldallalio** [comment]
I used -b firefox and browse_website is working for me

**Comment by broadway01** [comment]
From what I can tell the platform required is linux/arm64 not amd64 and this is causing issues. I have switched to ceramicwhite/auto-gpt and it is working for me as it has the linux/arm64 platform.

**Comment by jjaskulowski** [comment]
+1 same issue
