### ISSUE TITLE
error when AutoGpt try to push generated code

### ISSUE THREAD

**Issue by AndrukhivAndriy** [Significant-Gravitas/Auto-GPT#3782]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

1. generate any html code and save as filename index.html
2. Push this file to github repo <reponame>
3. GITHUB_API_KEY, GITHUB_USERNAME -- are enabled in .env

### Current behavior 😯

error  Command execute_shell returned: STDOUT: b'' STDERR: b"/bin/sh:

### Expected behavior 🤔

Pushed code to GitHub repo

### Your prompt 📝

1. generate any html code and save as filename index.html
2. Push this file to github repo <reponame>

### Your Logs 📒

 Command execute_shell returned: STDOUT: b'' STDERR: b"/bin/sh:

**Comment by ftl-traveller** [comment]
PR #3811 should fix this issue once approved.
