### ISSUE TITLE
Message when running "python scripts/main.py"

### ISSUE THREAD

**Issue by freepik19** [Significant-Gravitas/Auto-GPT#3787]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Current behavior 😯

Directory does not exist message

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by Explorergt92** [comment]
use `python -m autogpt` instead

**Comment by k-boikov** [comment]
Please follow https://docs.agpt.co/setup/
