### ISSUE TITLE
 Where Does AutoGPT Save Created Text Files as the Folder Cannot Be Found?

### ISSUE THREAD

**Issue by Shangooriginal** [Significant-Gravitas/Auto-GPT#3806]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

AutoGPT creates txt file and supposedly saves it to a folder

### Expected behavior 🤔

There should be a folder where the txt file is stored and can be retrieved. But I cannot find this folder or the txt file created

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by IustinT** [comment]
/Auto-GPT/autogpt/auto_gpt_workspace

**Comment by Joshfindit** [comment]
If you are using Docker, you might not be mounting the right folder. In that case there would not be any local files as they would all be written in the container.

**Comment by anonhostpi** [comment]
> If you are using Docker, you might not be mounting the right folder. In that case there would not be any local files as they would all be written in the container.

I saw the GH issue/discussion for that this morning. What's the number for it again?
