### ISSUE TITLE
ImportError: No module named dotenv

### ISSUE THREAD

**Issue by ShadowStorm0** [Significant-Gravitas/Auto-GPT#3819]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

I ran `./run.sh --gpt4only`

### Current behavior 😯

I get this traceback,

`Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "autogpt/__init__.py", line 5, in <module>
    from dotenv import load_dotenv
ImportError: No module named dotenv`

### Expected behavior 🤔

Be able to proceed and run Auto-GPT

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "autogpt/__init__.py", line 5, in <module>
    from dotenv import load_dotenv
ImportError: No module named dotenv

**Comment by anonhostpi** [comment]
Well, that is going to be problem number 1:

![image](https://user-images.githubusercontent.com/130698314/236381315-65d17cfe-ef3a-4169-8d70-0e9bfafdde46.png)

Your not running that in python 3. Try using the `python3` command explicitly instead of `python`

**Comment by maveric** [comment]
What I've been doing is 
`alias python="python3"`

in the terminal session before I run agpt so it is only for that session and I can stick with my normal python for normal use.

**Comment by ShadowStorm0** [comment]
Thanks for the suggestions. 

@anonhostpi What do you mean by running the command explicitly?

@maveric I ran `alias python="python3"` in the same terminal as `./run.sh --gpt4only` but I'm still getting the same error. I do have python3 version `3.9.7` when I ran it in the terminal.

**Comment by ShadowStorm0** [comment]
in the `run.sh` file I changed python to `python3.10` and I get this new error

`
#!/bin/bash
python3.10 scripts/check_requirements.py requirements.txt
if [ $? -eq 1 ]
then
    echo Installing missing packages...
    pip install -r requirements.txt
fi
python3.10 -m autogpt $@
read -p "Press any key to continue..."`

**Comment by ShadowStorm0** [comment]
I fixed it by making a conda environment running python3.10
