### ISSUE TITLE
Incorrect github links

### ISSUE THREAD

**Issue by dominic-ks** [Significant-Gravitas/Auto-GPT#3828]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Docker

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

Run the docker-compose file from the `stable` branch with Redis configured incorrctly, e.g. using

```
  redis:
    image: "redis/redis-stack-server:latest"
    ports:
      - '6379:999999999999'
```

...in the docker-compose.yml file.

### Current behavior 😯

Auto-GPT will prompt for you to check for the setup instructions here:
 - https://github.com/Torantulino/Auto-GPT#redis-setup

Similarly a Pinecone misconfig will direct you here:
 - https://github.com/Torantulino/Auto-GPT#-pinecone-api-key-setup

Which appears to no longer be valid since the README was rearranged.

### Expected behavior 🤔

Use these links instead:

 - https://docs.agpt.co/configuration/memory/#redis-setup
 - https://docs.agpt.co/configuration/memory/#pinecone-api-key-setup

### Your prompt 📝

N/A

### Your Logs 📒

```FAILED TO CONNECT TO REDIS  Error 99 connecting to localhost:6379. Cannot assign requested address.
DOUBLE CHECK CONFIGURATION  Please ensure you have setup and configured Redis properly for use. You can check out https://github.com/Torantulino/Auto-GPT#redis-setup to ensure you've set up everything correctly.
```

**Comment by Boostrix** [comment]
over the last couple of days there were apparently a handful of docker related issues, it might make sense for some volunteers to step up and offer their help reviewing Docker related commits - and maybe get the post-commit hook to update the docker registry automatically ?

**Comment by dominic-ks** [comment]
@Boostrix I just happened to be running docker here, but this is presumably a generic issue.

**Comment by Qoyyuum** [comment]
Its fixed in latest stable branch. Closing issue.
