### ISSUE TITLE
Create Debug Code Challenge A

### ISSUE THREAD

**Issue by merwanehamadi** [Significant-Gravitas/Auto-GPT#3836]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Challenges are tasks Auto-GPT is not able to achieve. Challenges will help us improve Auto-GPT

We need your help to build these challenges.
# Debug Challenge 

take the work of this Pull Request https://github.com/Significant-Gravitas/Auto-GPT/pull/3804/files

and and uncomment # @pytest.mark.vcr. You will see that
```
client = docker.from_env()
```
in autogpt/commands/execute_code.py is now hanging. Because VCR somehow intercepts docker calls.
Find a solution for this:
I suggest to call docker.from_env() in another subprocess, because VCR doesn't intercept things that come from other subprocesses

DM me on discord : merwanehamadi

Join Auto-GPT's channel so we can talk about Auto-GPT: https://discord.gg/autogpt

**Comment by AndresCdo** [comment]
Ok, I'll try to check this.

**Comment by merwanehamadi** [comment]
@AndresCdo thanks, I will invite you to the debug code thread in Discord.
