### ISSUE TITLE
[Challenge Creation] Information Retrieval Challenge B

### ISSUE THREAD

**Issue by merwanehamadi** [Significant-Gravitas/Auto-GPT#3837]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

 We need you to create a test SLIGHTLY harder than the information retrieval challenge A.
1- Go to this file : tests/integration/challenges/information_retrieval/test_information_retrieval_challenge_a.py
2- Understand it. Run the test to see what it does.
3- Now copy paste this file and build a challenge slightly harder. (it's important to not make it too hard)

DM me on discord : merwanehamadi

Join Auto-GPT's channel so we can talk about Auto-GPT: https://discord.gg/autogpt

**Comment by anonhostpi** [comment]
May be worth to merge the efforts of this and #3936 under a challenge that gets information from a URI

This would expand the scope in a way that shouldn't affect the underlying tests too much.

Example URI types:

- `http://`
- `https://`
- `ftp://`
- `file:///`

**Comment by anonhostpi** [comment]
Of course #3936 also covers interacting with the http/https URIs, not just retrieval

**Comment by merwanehamadi** [comment]
@PortlandKyGuy any new on this one ?

**Comment by PortlandKyGuy** [comment]
I have the challenge defined. Just need to finish the test. Will have. PR in the next 48 hrs
