### ISSUE TITLE
[Challenge Creation] Memory Challenge C

### ISSUE THREAD

**Issue by merwanehamadi** [Significant-Gravitas/Auto-GPT#3838]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

We need you to create a test SLIGHTLY harder than the memory challenge B.
1- Go to this file : tests/integration/challenges/memory/test_memory_challenge_b.py
2- Understand it. Run the test to see what it does.
3- Now copy paste this file and build a challenge slightly harder. (it's important to not make it too hard)

DM me on discord : merwanehamadi

Join Auto-GPT's channel so we can talk about Auto-GPT: https://discord.gg/autogpt

**Comment by merwanehamadi** [comment]
@dschonholtz someone picked the spot for the memory challenge C, so you can can call it memory challenge D.

**Comment by anonhostpi** [comment]
Related: #3989
