### ISSUE TITLE
[Challenge Experience] Better wiki

### ISSUE THREAD

**Issue by merwanehamadi** [Significant-Gravitas/Auto-GPT#3839]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Challenges are tasks Auto-GPT is not able to achieve. Challenges will help us improve Auto-GPT

We need your help to build a better experience for people to browse challenges. by building a better wiki.

Once this PR https://github.com/Significant-Gravitas/Auto-GPT/pull/3764 is merged you will be able to see the challenges here https://docs.agpt.co/setup/ and make them look better and more appealing.

To do it. Update the .md located in the docs folder. 
**You will be able to see your changes py updating your Pull request and looking at Vercel in the Pull request**

DM me on discord : merwanehamadi

Join Auto-GPT's channel so we can talk about Auto-GPT: https://discord.gg/autogpt

**Comment by anonhostpi** [comment]
FTR, #3764 is merged

**Comment by merwanehamadi** [comment]
yes, we still need @jonathansheets517 to help us clean the wiki.

**Comment by merwanehamadi** [comment]
@jonathansheets517 how is the wiki looking, for challenges ?
