### ISSUE TITLE
["Fix Auto-GPT" challenges] Inform the community how to report Auto-GPT incorrect behavior.

### ISSUE THREAD

**Issue by merwanehamadi** [Significant-Gravitas/Auto-GPT#3841]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

We now have these logs:
![Screenshot 2023-05-05 at 6 01 19 AM](https://user-images.githubusercontent.com/9652976/236464537-e1e4e32a-e781-4fb2-9695-52994b9dc861.png)
As you can see they show you what happened to Auto-GPT at every cycle. They will help people understand why they're failing challenges, and help people that encounter issues report better issues.

We need your help to update our Issue template to make it crystal what needs to be done for people to put these logs as a zip.
People will also have to indicate to us at which cycle the agent is doing something wrong.
We will not accept logs that are beyond 10 cycles of Auto-GPT for now.

DM me on discord : merwanehamadi

Join Auto-GPT's channel so we can talk about Auto-GPT: https://discord.gg/autogpt

**Comment by cyrus-hawk** [comment]
I'm interested in this issue. Could I contribute? :thinking:

**Comment by Boostrix** [comment]
sure, best to discuss your plans here and/or on github.
Tell us if you'd like to be assigned to this!
Will send a ping to @merwanehamadi

**Comment by merwanehamadi** [comment]
> I'm interested in this issue. Could I contribute? 🤔

hello @cyrus-hawk, thanks for your help !

We have started using e2b for that: 

https://autogpt.e2b.dev/?view=logs&logFileID=337d34e0-5367-4849-a411-b8a82322fab1

@mlejva and his team helped us build something tailored to Auto-GPT. 

If you have other ideas please join us on https://discord.gg/autogpt !

Also I am sure @mlejva would love to know how we can improve this tool.
We also need to communicate more broadly on how to use this tool.

Our first step is to not need the debug mode anymore in order to generate the logs described above. This way anyone can generate these logs automatically. Then we need an easy way for people to upload them in this dashboard.

Again a lot of things happen on discord so please join us !

**Comment by mlejva** [comment]
Hey @cyrus-hawk, I'm one of the founders of https://e2b.dev and the dashboard we built for the Auto-GPT team.

Would love to learn more about your experience using https://autogpt.e2b.dev and how we could make it better for the folks like you. Please join our Discord https://discord.gg/U7KEcGErtQ or ping me on Auto-GPT Discord (my handle is mlejva)!
