### ISSUE TITLE
Log Self Feedback in logs/Debug folder

### ISSUE THREAD

**Issue by merwanehamadi** [Significant-Gravitas/Auto-GPT#3842]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Self feedback is triggered when the user types "s" as a user input.

We want to log within the logs/DEBUG folder
- what is the prompt asked to the LLM.
- What is the LLM answer.

This means you will add new files within each cycle of Auto-GPT:
![Screenshot 2023-05-05 at 7 32 57 AM](https://user-images.githubusercontent.com/9652976/236487749-4ee590cb-2803-4b00-9d7d-c748e8f4cb98.png)

DM me on discord : merwanehamadi

Join Auto-GPT's channel so we can talk about Auto-GPT: https://discord.gg/autogpt

**Comment by AndresCdo** [comment]
I'll try this.
