### ISSUE TITLE
Log User input in logs/Debug folder

### ISSUE THREAD

**Issue by merwanehamadi** [Significant-Gravitas/Auto-GPT#3843]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

We want to log the user input in the user input

This means you will add new files within each cycle of Auto-GPT, and the file will be named "N_user_input.txt" where N describes when the user_input happens within each cycle. Look at the LogCycleHandler class to understand how to build this.
![Screenshot 2023-05-05 at 7 32 57 AM](https://user-images.githubusercontent.com/9652976/236487749-4ee590cb-2803-4b00-9d7d-c748e8f4cb98.png)

DM me on discord : merwanehamadi

Join Auto-GPT's channel so we can talk about Auto-GPT: https://discord.gg/autogpt

**Comment by anonhostpi** [comment]
With #3867 being merged does this issue still need to be left open?

Also I would like to suggest that the efforts to record logs/history being merged in with the [efforts to save agent-state](https://gist.github.com/anonhostpi/97d4bb3e9535c92b8173fae704b76264#save-statecachinglogging-proposals).

Why keep state/history info in 2 different places?

**Comment by merwanehamadi** [comment]
thanks @AndresCdo
