### ISSUE TITLE
Fix Self Feedback being completely ignored

### ISSUE THREAD

**Issue by merwanehamadi** [Significant-Gravitas/Auto-GPT#3849]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

The Self feedback is triggered when someone puts s in the user input.

We ask openai if the agent's behavior makes sense and we receive a yes or some text that suggests the agent to change direction
Currently the self feedback is completely ignored by the agent, because it's not passed to the context.

# The scope of this issue is not to make self-feedback more relevant by changing the prompt, but just to FIX the self feedback.

**Comment by Boostrix** [comment]
Related: ##3680

**Comment by merwanehamadi** [comment]
closed thanks for your help @AbTrax
