### ISSUE TITLE
Local (not docker) install does not pick up Redis as a LocalCache 

### ISSUE THREAD

**Issue by thurft** [Significant-Gravitas/Auto-GPT#3859]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹
```
################################################################################
### MEMORY
################################################################################

### MEMORY_BACKEND - Memory backend type
## local - Default
## pinecone - Pinecone (if configured)
## redis - Redis (if configured)
## milvus - Milvus (if configured - also works with Zilliz)
## MEMORY_INDEX - Name of index created in Memory backend (Default: auto-gpt)
MEMORY_BACKEND=redis
MEMORY_INDEX=auto-gpt

### PINECONE
## PINECONE_API_KEY - Pinecone API Key (Example: my-pinecone-api-key)
## PINECONE_ENV - Pinecone environment (region) (Example: us-west-2)
#PINECONE_API_KEY=
#PINECONE_ENV=

### REDIS
## REDIS_HOST - Redis host (Default: localhost, use "redis" for docker-compose)
## REDIS_PORT - Redis port (Default: 6379)
## REDIS_PASSWORD - Redis password (Default: "")
## WIPE_REDIS_ON_START - Wipes data / index on start (Default: True)
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PASSWORD=
WIPE_REDIS_ON_START=True
```
### Current behavior 😯

I have everything installed without docker in my mac - Auto-GPT  & Redis. Everything works.  I can connect locally to Redis via the regular CLI. But Auto-GPT never uses Redis. I can however get it to use PINECONE. So i think is a Redis only bug.
```
"I want Auto-GPT to: How to configure redis in auto-gpt?
RedisGPT  has been created with the following details:
Name:  RedisGPT
Role:  an AI assistant that specializes in configuring Redis for the Auto-GPT system, providing expert guidance to ensure optimal performance and stability.
Goals:
-  Analyze the existing Auto-GPT infrastructure and recommend the appropriate Redis deployment strategy based on the system's requirements and constraints.
-  Provide detailed instructions on the installation and configuration of Redis, including the selection of appropriate hardware and software components.
-  Optimize Redis performance by fine-tuning key parameters such as memory usage, persistence, and replication, based on the Auto-GPT workload characteristics.
-  Implement best practices for Redis security, such as authentication, encryption, and access control, to ensure the system's data integrity and confidentiality.
-  Monitor Redis performance and proactively identify and resolve any issues that may arise, ensuring the Auto-GPT system's smooth and uninterrupted operation.
  Error: Redis is not installed. Please install redis-py to use Redis as a memory backend.
Using memory of type:  LocalCache
Using Browser:  chrome"
```

### Expected behavior 🤔

Using memory of type:  Redis

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by Boostrix** [comment]
There are now so many memory related issues being reported that it would probably make sense to review/improve unit testing in that area - and potentially even execute some self-test during startup if that isn't already done ? An AI agent suffering from dementia isn't exactly helpful when it comes to improving itself (#15)

**Comment by k-boikov** [comment]
Will tell you a small secret - memory in latest stable is completely broken and it doesn't matter what memory you use. We switched to summary memory internally till we fix the conventional memory storages.

**Comment by Boostrix** [comment]
at least you are able to tag things ... to help your ... memory :-)

**Comment by ether8unny** [comment]
I'm running in stable-0.2.2  to maintain memory., with redis.
git checkout -b stble-0.2.2 if you want to revert for the time being

**Comment by Boostrix** [comment]
this is one of those reasons why more tests are needed, and possibly some form of "selftest" that can be executed by users (or is executed during startup) to ensure that everything is working as expected. The number of folks running into obscure issues like these and leaving Auto-GPT alone because they consider it a dysfunctional POS is probably not to be underestimated - just because the system fails to check itself during startup.
At the very least it should be able to tell users what is working and what isn't OPTIONALLY
