### ISSUE TITLE
Challenges should be using the automatic AI Config generation

### ISSUE THREAD

**Issue by merwanehamadi** [Significant-Gravitas/Auto-GPT#3883]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Our challenges should use the default Auto-GPT mode. In the default mode, we generate the AI Config automatically.

pick one test, for example test_browse_website.and attempt to generate the AI Config automatically at the beginning of the test. You will need to define a prompt that makes the test pass.
replace the browser_agent located in tests/integration/agent_factory.py by this :
```
@pytest.fixture
def browser_agent(agent_test_config, memory_none: NoMemory, workspace: Workspace):
    
    
    command_registry = CommandRegistry()
    command_registry.import_commands("autogpt.commands.file_operations")
    command_registry.import_commands("autogpt.commands.web_selenium")
    command_registry.import_commands("autogpt.app")
    command_registry.import_commands("autogpt.commands.task_statuses")
    ai_config  = generate_aiconfig_automatic(user_desire)
    ai_config.command_registry = command_registry

    system_prompt = ai_config.construct_full_prompt()

    agent = Agent(
        ai_name="",
        memory=memory_none,
        full_message_history=[],
        command_registry=command_registry,
        config=ai_config,
        next_action_count=0,
        system_prompt=system_prompt,
        triggering_prompt=DEFAULT_TRIGGERING_PROMPT,
        workspace_directory=workspace.root,
    )

    return agent

```
pick the correct user_desire that makes the test pass.

Apply the same logic for all the tests located in the goal_oriented and challenges folders. Create a PR for each test so it's  easier to review.

**Comment by anonhostpi** [comment]
Related: #3907
