### ISSUE TITLE
Error: ARGUMENTS = string indices must be integers, not 'str'

### ISSUE THREAD

**Issue by VexyCats** [Significant-Gravitas/Auto-GPT#389]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Unsure, it randomly seems to produce this error. I've even given instructions that if the AI failed to parse the output then to reformat the input to a manner which the AI can parse. 

Warning: Failed to parse AI output, attempting to fix.
 If you see this warning frequently, it's likely that your prompt is confusing the AI. Try changing it up slightly.
Failed to fix ai output, telling the AI.
NEXT ACTION:  COMMAND = Error: ARGUMENTS = string indices must be integers, not 'str'
SYSTEM:  Command Error: returned: Unknown command Error:

### Current behavior 😯

Randomly it will return this error when given a prompt or running multiple times. 

### Expected behavior 🤔

Should not have a type error of uint or str. 

### Your prompt 📝

``Describe your AI's role:  For example, 'an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.'
Shopify and wordpress site finder is: Search the internet for a list of 100 shopify and wordpress websites that are popular and then use that list to perform extra validation that will be given to you once the list is finalized. CRITICAL! You may only respond in JSON format as described below. Go carefully and step by step. Do not output any additional instructions outside of the JSON format. Under no circumstances should your response deviate from valid JSON format.
Enter up to 5 goals for your AI:  For example: Increase net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously'
Enter nothing to load defaults, enter nothing when finished.
Goal 1: Search for 100 wordpress and shopify sites online that are popular and have high traffic.
Goal 2: Compile the list into a set of URLs
Goal 3: Try to find contact information for each of the websites
Goal 4: Ask for more instructions once the list has been compiled and saved as a .txt file
Goal 5:
Using memory of type: PineconeMemory
SHOPIFY AND WORDPRESS SITE FINDER THOUGHTS: I need to start by searching for popular Shopify and Wordpress websites. I can use Google search to find a list of the top websites.
REASONING: Searching Google for lists of popular Shopify and Wordpress sites is the best way to get a comprehensive list.
PLAN:
-  Use Google Search to search for lists of popular Shopify and Wordpress websites
-  Compile a list of websites and URLs
-  Locate contact information for each website
-  Await further instructions for additional validation
CRITICISM: I need to be efficient while searching for websites to make the best use of my resources.
NEXT ACTION:  COMMAND = google ARGUMENTS = {'input': 'popular Shopify Wordpress websites'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for Shopify and wordpress site finder...
Input:y
```

**Comment by Torantulino** [comment]
Is this being caused by the AI scraping Emojis from the web?

**Comment by Pwuts** [comment]
Possibly related: #232. Needs investigation.
