### ISSUE TITLE
Can't run Auto-GPT (error /bin/bash: ./run.sh: Operation not permitted)

### ISSUE THREAD

**Issue by RkitectMC** [Significant-Gravitas/Auto-GPT#3899]
### Discussed in https://github.com/Significant-Gravitas/Auto-GPT/discussions/3898

<div type='discussions-op-text'>

<sup>Originally posted by **RkitectMC** May  6, 2023</sup>
Hi, please can anyone help me?

I am getting the error /bin/bash: ./run.sh: Operation not permitted after agreeing the licences and then typing ./run.sh.  Have I done something wrong?</div>

**Comment by k-boikov** [comment]
Please reopen following the Bug report template.
