### ISSUE TITLE
Regression Test: Auto-GPT should always be able to build this simple contact form

### ISSUE THREAD

**Issue by merwanehamadi** [Significant-Gravitas/Auto-GPT#3901]
We need your help to build an ambitious regression test.

As suggested by @boostrix, one of the tasks Auto-GPT is able to perform right now is building a simple contact form:
https://github.com/Significant-Gravitas/Auto-GPT/issues/2775#issuecomment-1517703255

STEP 1: Create the same set of instructions and run this agent in a test.

STEP 2: Test whether the website is working (not easy)

@adam-peterson has created a php website using these instructions.
```
ai_name: PHP-GPT
ai_role: An AI agent that can take the defined goals and generate a PHP project that can accomplish them.
ai_goals:
  - All generated code should be valid PHP code with the .php file extension.
  - Read the contents of project.txt to understand the project requirements and deliverables.
  - Do not use any external libraries or frameworks.
  - Do not checkout any code from any source control system.
  - Do not attempt to configure any web-server or PHP interpreter.
  - Only write the project files and assume they work.
  ```

projects.txt
  ```
  Project Brief: Simple PHP Contact Form

Objective:
Create a simple PHP contact form that allows users to submit their name, email address, and message. The form should validate user input and send an email to the specified recipient address upon successful submission.

Requirements:

Frontend:
- Create an HTML form with the following input fields:
--Name (text input)
--Email (email input)
--Message (textarea)
- Include a submit button to submit the form.
- Add basic CSS styling to make the form visually appealing.

Backend:
- Create a PHP script to handle the form submission.
- Validate user input:
-- Ensure that all fields are filled out.
-- Validate the email address format.
-- Limit the message length to a reasonable value (e.g., 500 characters).
- If the validation fails, display an error message and return the user to the form with the submitted values pre-filled.
- If the validation is successful, send an email to a specified recipient address with the user's submitted information.
- Display a success message to the user after successful form submission.

Security:
- Implement basic security measures to protect against common vulnerabilities, such as:
-- Cross-Site Scripting (XSS): sanitize user input before displaying it on the page.
-- Email header injection: validate and sanitize email input before using it in email headers.

Deliverables:
- An HTML file (contact.html) containing the contact form and basic CSS styling.
- A PHP script (submit.php) to handle form submission, input validation, and email sending.
- A README file with instructions on how to set up and use the contact form.

Note: You can assume that the server has PHP and an email-sending function (e.g., mail()) correctly configured.
```

**Comment by Boostrix** [comment]
> STEP 2: Test whether the website is working (not easy)

should  be fairly doable, just ask GPT to generate a set of unit tests in Python for the project:

- check the paths/file names and file extensions involved
- files should exist, be valid PHP/HTML respectively
- when running an XPath expression on the HTML, the widgets and CSS styling must be found

Likewise for the backend.

If in doubt, create a set of unit tests that fire up a Python HTTPServer instance to actually "test" the website that way (again, I believe Selenium would be overkill)

**Comment by merwanehamadi** [comment]
yeah probably easier to do in python. 
I quoted adam in the post.

**Comment by Boostrix** [comment]
> I quoted adam in the post.
Once again, it's @adam-paterson :-)

**Comment by merwanehamadi** [comment]
@Boostrix I think adam needs to participate to the conversation for me to be able to assign him.

Do you know how to write challenges ?

**Comment by Boostrix** [comment]
understood, I think at least for starters, we're going to tinker around with adapting project.txt (its specs) to also produce the required pytest stubs based on the deliverables and specs and then take it from there.

**Comment by merwanehamadi** [comment]
@Boostrix yeah the challenges are all written in
tests/integration/challenges
you can copy the tests written there and adapt them for this challenge.
