### ISSUE TITLE
send_email fails

### ISSUE THREAD

**Issue by Djamchid** [Significant-Gravitas/Auto-GPT#3929]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

 $ git clone -b stable https://github.com/Significant-Gravitas/Auto-GPT.git
Cloning into 'Auto-GPT'...
remote: Enumerating objects: 9994, done.
remote: Counting objects: 100% (2763/2763), done.
remote: Compressing objects: 100% (464/464), done.
remote: Total 9994 (delta 2431), reused 2431 (delta 2293), pack-reused 7231
Receiving objects: 100% (9994/9994), 6.23 MiB | 13.45 MiB/s, done.
Resolving deltas: 100% (6876/6876), done.
(base) ubuntu ~ 21:47:22  ~/digiwatch-python/digiwatch_modelling/Djamchid_Perso/Auto-GPT  @stable 
  $ git clone -b stable https://github.com/Significant-Gravitas/Auto-GPT.git
fatal: could not create work tree dir 'Auto-GPT': No such file or directory
(base) ubuntu ~ 21:50:35  ~/digiwatch-python/digiwatch_modelling/Djamchid_Perso/Auto-GPT   
  $ cd ..
(base) ubuntu ~ 21:51:08  ~/digiwatch-python/digiwatch_modelling/Djamchid_Perso  @6-corriger-frequence-analyse-2 
  $ git clone -b stable https://github.com/Significant-Gravitas/Auto-GPT.git
Cloning into 'Auto-GPT'...
remote: Enumerating objects: 9994, done.
remote: Counting objects: 100% (2907/2907), done.
remote: Compressing objects: 100% (495/495), done.
remote: Total 9994 (delta 2573), reused 2542 (delta 2406), pack-reused 7087
Receiving objects: 100% (9994/9994), 6.22 MiB | 12.47 MiB/s, done.
Resolving deltas: 100% (6863/6863), done.
(base) ubuntu ~ 21:51:19  ~/digiwatch-python/digiwatch_modelling/Djamchid_Perso  @6-corriger-frequence-analyse-2 
  $ cd Auto-GPT/
(base) ubuntu ~ 21:51:36  ~/digiwatch-python/digiwatch_modelling/Djamchid_Perso/Auto-GPT  @stable 
  $ curl -L -o ./plugins/Auto-GPT-Plugins.zip https://github.com/Significant-Gravitas/Auto-GPT-Plugins/archive/refs/heads/master.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  255k  100  255k    0     0   591k      0 --:--:-- --:--:-- --:--:--     0
(base) ubuntu ~ 21:56:18  ~/digiwatch-python/digiwatch_modelling/Djamchid_Perso/Auto-GPT  @stable 
  $ curl -L -o ./plugins/Auto-GPT-Plugins.zip https://github.com/Significant-Gravitas/Auto-GPT-Plugins/archive/refs/heads/master.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  255k    0  255k    0     0   611k      0 --:--:-- --:--:-- --:--:--  611k
(base) ubuntu ~ 21:56:51  ~/digiwatch-python/digiwatch_modelling/Djamchid_Perso/Auto-GPT  @stable 
  $ ./run.sh
All packages are installed.
NEWS:  Welcome to Auto-GPT!
NEWS:  Below you'll find the latest Auto-GPT News and updates regarding features!
NEWS:  If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag.
NEWS:  
NEWS:  ::NEW BULLETIN::
NEWS:  
NEWS:  Website and Documentation Site 📰📖
NEWS:  Check out https://agpt.co, the official news & updates site for Auto-GPT!
NEWS:  The documentation also has a place here, at https://docs.agpt.co
NEWS:  
NEWS:  🚀 v0.3.0 Release 🚀
NEWS:  Over a week and 275 pull requests have passed since v0.2.2, and we are happy to announce
NEWS:  the release of v0.3.0! From now on, we will be focusing on major improvements rather
NEWS:  than bugfixes, as we feel stability has reached a reasonable level. Most remaining
NEWS:  issues relate to limitations in prompt generation and the memory system, which will be
NEWS:  the focus of our efforts for the next release.
NEWS:  
NEWS:  Highlights and notable changes in this release:
NEWS:  
NEWS:  Plugin support 🔌
NEWS:  Auto-GPT now has support for plugins! With plugins, you can extend Auto-GPT's abilities,
NEWS:  adding support for third-party services and more.
NEWS:  See https://github.com/Significant-Gravitas/Auto-GPT-Plugins for instructions and available plugins.
NEWS:  
NEWS:  Changes to Docker configuration 🐋
NEWS:  The workdir has been changed from /home/appuser to /app.
NEWS:  Be sure to update any volume mounts accordingly!
NEWS:  
NEWS:  ⚠️ Command `send_tweet` is DEPRECATED, and will be removed in v0.4.0 ⚠️
NEWS:  Twitter functionality (and more) is now covered by plugins, see [Plugin support 🔌]
NEWS:  
NEWS: Bulletin was updated! Press Enter to continue...
WARNING: Plugin AutoGPTBingSearch found. But not in the allowlist... Load? (y/n): 
WARNING: Plugin AutoGPTNewsSearch found. But not in the allowlist... Load? (y/n): 
WARNING: Plugin AutoGPTRandomValues found. But not in the allowlist... Load? (y/n): 
WARNING: Plugin AutoGPTSceneXPlugin found. But not in the allowlist... Load? (y/n): 
WARNING: Plugin AutoGPTTwitter found. But not in the allowlist... Load? (y/n): 
WARNING: Plugin AutoGPTWikipediaSearch found. But not in the allowlist... Load? (y/n): 
  
Plugins found: 1
--------------------
  Auto-GPT-Email-Plugin: 0.1.3 - Auto-GPT Email Plugin: Supercharge email management.
Welcome to Auto-GPT!  run with '--help' for more information.
Create an AI-Assistant:  input '--manual' to enter manual mode.
  Asking user via keyboard...
I want Auto-GPT to: send a test email
EmailGPT  has been created with the following details:
Name:  EmailGPT
Role:  an AI assistant that specializes in email communication and helps users send effective and professional emails with ease.
Goals: 
-  Compose and send test emails quickly and accurately, ensuring that all necessary information is included and that the email is free of errors.
-  Provide suggestions for subject lines, greetings, and closing statements to ensure that the email is professional and effective.
-  Offer guidance on email etiquette and best practices to help users communicate more effectively and build stronger relationships with their contacts.
-  Monitor email responses and provide insights on how to improve future emails based on recipient engagement and feedback.
-  Integrate with email management tools to streamline the email sending process and improve productivity.
Using memory of type:  LocalCache
Using Browser:  chrome
 THOUGHTS:  I think a good starting point would be to check for any new emails. This will give us an idea of any pending tasks or requests that need to be addressed.
REASONING:  Checking for new emails is a common starting point for many work-related tasks. It helps to prioritize tasks and ensures that important requests are not missed.
PLAN: 
-  Check for new emails using the 'read_emails' command
-  Prioritize tasks based on urgency and importance
-  Respond to emails as necessary
CRITICISM:  I need to ensure that I am checking for new emails regularly and responding to them in a timely manner. I should also be mindful of any potential spam or phishing emails that may require further investigation.
NEXT ACTION:  COMMAND = read_emails ARGUMENTS = {'imap_folder': 'inbox', 'imap_search_command': 'UNSEEN'}
  Enter 'y' to authorise command, 'y -N' to run N continuous commands, 's' to run self-feedback commands'n' to exit program, or enter feedback for ...
  Asking user via keyboard...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
SYSTEM:  Command read_emails returned: Error: 'utf-8' codec can't decode byte 0xe9 in position 39: invalid continuation byte
 THOUGHTS:  It seems like there was an error with the 'read_emails' command. Before we proceed, we should check if there are any issues with the email server or credentials.
REASONING:  It's important to ensure that the email server and credentials are working properly before attempting to read emails. This will help to avoid any potential errors or issues.
PLAN: 
-  Check the email server status
-  Verify the email credentials
-  Retry the 'read_emails' command
CRITICISM:  I need to ensure that I am using the correct email credentials and that the email server is functioning properly. I should also be mindful of any potential security issues that may arise from accessing emails.
NEXT ACTION:  COMMAND = google ARGUMENTS = {'query': 'How to check email server status and verify email credentials'}
  Enter 'y' to authorise command, 'y -N' to run N continuous commands, 's' to run self-feedback commands'n' to exit program, or enter feedback for ...
  Asking user via keyboard...
Input:n
  Exiting...
Press any key to continue...

### Current behavior 😯

NEXT ACTION:  COMMAND = read_emails ARGUMENTS = {'imap_folder': 'inbox', 'imap_search_command': 'UNSEEN'}
  Enter 'y' to authorise command, 'y -N' to run N continuous commands, 's' to run self-feedback commands'n' to exit program, or enter feedback for ...
  Asking user via keyboard...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
SYSTEM:  Command read_emails returned: Error: 'utf-8' codec can't decode byte 0xe9 in position 39: invalid continuation byte

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by Djamchid** [comment]
is this because my mails have accents like "é"?

**Comment by ppetermann** [comment]
this is because at least one of your mails is not utf-8 encoded.

this is a duplicate of: https://github.com/Significant-Gravitas/Auto-GPT-Plugins/issues/110

**Comment by miradnan** [comment]
If you are using GMail. Make sure to enable IMAP and turn on Less secure apps.

**Comment by Djamchid** [comment]
we should try and catch the exceptions instead of letting the program fail

Le sam. 13 mai 2023 à 16:46, Peter Petermann ***@***.***> a
écrit :

**Comment by sdelgadoc** [comment]
> we should try and catch the exceptions instead of letting the program fail

This behavior has been implemented in the following PR (https://github.com/Significant-Gravitas/Auto-GPT-Plugins/pull/139), and should fix the error that was identified in this issue.
