### ISSUE TITLE
Updated Install Instructions to include activation sequence

### ISSUE THREAD

**Issue by RGDub** [Significant-Gravitas/Auto-GPT#3939]
Install instructions need to be updated reflect that a virtual environment must be created, pip installation/update/upgrade verified, requirements.txt installed and then ./run.sh should be run . Sequence would be something like this: 

python3.11 -m venv venv
source venv/bin/activate
python -m pip install --upgrade pip
pip install -r requirements.txt
./run.sh

**Comment by brucemeek** [comment]
i made a pr for this

**Comment by lc0rp** [comment]
#4497 was closed. This is still in need of a PR.

**Comment by cyrus-hawk** [comment]
@lc0rp could I work on this? :thinking:
