### ISSUE TITLE
File references 

### ISSUE THREAD

**Issue by macd2** [Significant-Gravitas/Auto-GPT#3943]
The bot tries to constantly ready files that do not exist which than results in an error and death loop. 
would be great if the bot first checks the file_logger.txt if the referenced file is there and if not create it before referencing it.

**Comment by Limipa** [comment]
Same issue here. Running with Doccer. I have just started and don't find the files even my self. No folder "app" under "home" folder?!

**Comment by macd2** [comment]
its is not about that my issue is the bot itself is referencing file that do not exist like "read file XY.csv" but the file was never created in the first place.

**Comment by OmniKingOG** [comment]
> its is not about that my issue is the bot itself is referencing file that do not exist like "read file XY.csv" but the file was never created in the first place.

Its still a very complex system dont get me wrong but its far from being able to actually operate autonomously and do things on its own. for now id suggest the best way is finding ways to reword your prompts and instructions to be more simplfied and instructive like teaching a baby to walk. right now it can only be used for simple things and stuff and alot of the time you must verify that information over and over if possible to make sure its accurate.

**Comment by macd2** [comment]
> ine tun

thank you very  much for your explanation. I get what you are saying but there is a file called `file_logger.txt` it shouldn't be to difficult to make the bot restricted to this file list. In other words only when a file has been created hence it is in this list the bot is allowed to reference it? Or do I oversimplify?

**Comment by macd2** [comment]
> > its is not about that my issue is the bot itself is referencing file that do not exist like "read file XY.csv" but the file was never created in the first place.
> 
> Its still a very complex system dont get me wrong but its far from being able to actually operate autonomously and do things on its own. for now id suggest the best way is finding ways to reword your prompts and instructions to be more simplfied and instructive like teaching a baby to walk. right now it can only be used for simple things and stuff and alot of the time you must verify that information over and over if possible to make sure its accurate.

thank you very much for your explanation. I get what you are saying but there is a file called file_logger.txt it shouldn't be to difficult to make the bot restricted to this file list. In other words only when a file has been created hence it is in this list the bot is allowed to reference it? Or do I oversimplify?

**Comment by OmniKingOG** [comment]
> > > its is not about that my issue is the bot itself is referencing file that do not exist like "read file XY.csv" but the file was never created in the first place.
> > 
> > 
> > Its still a very complex system dont get me wrong but its far from being able to actually operate autonomously and do things on its own. for now id suggest the best way is finding ways to reword your prompts and instructions to be more simplfied and instructive like teaching a baby to walk. right now it can only be used for simple things and stuff and alot of the time you must verify that information over and over if possible to make sure its accurate.
> 
> thank you very much for your explanation. I get what you are saying but there is a file called file_logger.txt it shouldn't be to difficult to make the bot restricted to this file list. In other words only when a file has been created hence it is in this list the bot is allowed to reference it? Or do I oversimplify?

im not sure if a current way is implimented and i now also understand what your saying in detail more, id say try oversimplifying and see what results that can output. try directly making it keep up with the file before it makes a file operation to make sure such operation has not been made in the past and if it has to then locate the existing file based off the path provided for it in the file_logger.txt file. overtime though i belive it wouldnt work well as it would lose context of the meanings.

**Comment by macd2** [comment]
ok thanks! I`ll experiment a bit more and will post here if i find a solution.
