### ISSUE TITLE
Allow multiple commands at once

### ISSUE THREAD

**Issue by yangkyeongmo** [Significant-Gravitas/Auto-GPT#3945]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Although I'm working on it, I thought it would be nice to make an issue and maybe someone else better(and more time) on this repo could work on it.

Not all commands are costly. Some API calls like speaking could be expensive, but searching on internet, writing file, reading file or else are not. These commands could be done at once, and if it happens it'll save queries.

For example, if the bot wants to search about some information, it could simultaneously search about multiple topics.

To acheieve this, these changes should be done:
1. Allow bot to make more than one commands
2. Parse many commands from agent
3. Agent calls multiple commands at once, possibly using asynchronous calls
4. Mark cheap commands which can allow multiple calls

### Examples 🌈

Since bot is already told it should answer in json format, even though it was told command in answer should be in dictionary, sometimes its answer is in list format.

This is not an actual answer, it's how the answer would look like.
```json
{
    ...
    "command": [
        {"name": "command name", "args": {"arg name": "value"},
        {"name": "command name", "args": {"arg name": "value"},
        ...
    ],
    ...
}
```

**Comment by Boostrix** [comment]
See also: #1060
