### ISSUE TITLE
Control Auto GPT via Slack bot

### ISSUE THREAD

**Issue by ZiggerZZ** [Significant-Gravitas/Auto-GPT#3956]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Prompt and interact with Auto GPT through Slack bot interface.

### Examples 🌈

I implemented an MVP by starting a Flask server thread with Slack bot events in `autogpt/main.py` and replacing `clean_input()` by an input message from Slack and adding `slack_client.chat_postMessage()` to logging. I configured a Slack bot and used [ngrok](https://ngrok.com/) locally.

<img width="1264" alt="Screenshot 2023-05-07 at 11 27 09" src="https://user-images.githubusercontent.com/13183693/236683582-3eea957e-4c83-403b-bb81-0f6d8fd36faa.png">

### Motivation 🔦

By interacting with Auto-GPT via Slack rather then through the terminal it feels more like communicating with a real teammate.
Does this feature request fit the project, or you recommend to keep it as a fork?

**Comment by eyalk11** [comment]
Just notice that there is already plugin for discord. https://github.com/gravelBridge/AutoGPT-Discord/

**Comment by ZiggerZZ** [comment]
Thanks @eyalk11! I'll have a look have i can tweak the logic to put it into a plug-in
