### ISSUE TITLE
Log ai_settings.yaml in logs/DEBUG/[TIMESTAMP_AGENT_NAME]/001/ 0_ai_settings.yaml

### ISSUE THREAD

**Issue by merwanehamadi** [Significant-Gravitas/Auto-GPT#3960]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

if we put the ai_settings in the logs/DEBUG we will easily be able to reproduce people's bugs.
Log ai_settings.yaml in logs/DEBUG/[TIMESTAMP_AGENT_NAME]/001/ 0_ai_settings.yaml

todo:
in agent.py 
just before:
``` 
self.log_cycle_handler.log_cycle(
                self.config.ai_name,
                self.created_at,
                self.cycle_count,
                self.full_message_history,
                FULL_MESSAGE_HISTORY_FILE_NAME,
            )
```         
call self.log_cycle_handler but pass the ai_settings instead.

Make sure you test your changes by running python -m autogpt --debug

**Comment by Boostrix** [comment]
agreed regarding the usefulness, but that is a potential privacy issue, so people should explicitly be told what info is in there.
This is now also heavily overlapping with requirements to support multiple projects as per #3549 

The background here being, the requirements are very much overlapping and for devs/contributors to be able to reproduce a certain setup, it would obviously be helpful to just hand a certain folder over to agpt and tell it to treat it as its workspace, but also to look for its ai_settings.yaml file in it - at that point, we'd basically have multi-project support (via sub-directories) but also a capability to reproduce issues (as long as the yaml file doesn't have implicit assumptions about data in the workspace) - that being said, providing an option to also zip up the workspace itself would make sense to get more/better data that can be more easily reproduced
