### ISSUE TITLE
Docker: [Errno 101] Network is unreachable (How to troubleshoot?)

### ISSUE THREAD

**Issue by Slapbox** [Significant-Gravitas/Auto-GPT#3977]
Support note 
-------------
For others facing this issue:
- From this comment: https://github.com/Significant-Gravitas/Auto-GPT/issues/3977#issuecomment-1577022198
- The fix may be tweaking the environment that you're running in, but we're still determining. 
- If you encounter and fix the issue, drop a comment below so that we can gather more data. 
- Marking this as "needs more info"

Thanks, @lc0rp 

=== Orig Report ===
--------------------
I get this error:

```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff674dd8340>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
```

It hits max retries seemingly immediately and it says "Network is unreachable."

How can we debug the network connection within the Docker image?

**Comment by klsdjft** [comment]
same issue, when i use docker proxy.

"proxies":{
                "default":
                         {
                        "httpProxy": "http://127.0.0.1:7890",
                        "httpsProxy": "https://127.0.0.1:7890",
                        "noProxy":"localhost"
                         }
                   }

**Comment by anonhostpi** [comment]
Likely an issue with that proxy.

The "Errno 101" bit should clue you in. In Google Chrome this is the same error as ERR_CONNECTION_RESET
https://www.ionos.com/digitalguide/hosting/technical-matters/err-connection-reset/

This error happens during the client-server handshake. Meaning that the client detected a good handshake, but the server didn't send any data whatsoever back to the client other than the "FIN" packet which closes the connection.

Which probably means that the proxy you listed does not work.

**Comment by Slapbox** [comment]
@anonhostpi I'm a bit confused - am I supposed to be configuring some proxy settings that I overlooked in the setup? We don't list any proxy anywhere and it's not configured in Docker, but still we get the Errno 101.

**Comment by anonhostpi** [comment]
[@Slapbox's Error Log](https://github.com/Significant-Gravitas/Auto-GPT/files/11437006/attachment.txt)
[@Slapbox's .env](https://github.com/Significant-Gravitas/Auto-GPT/files/11437019/attachment.txt)

**Comment by anonhostpi** [comment]
@Slapbox recommend changing title, to make it a bit more likely to get support.

My recommendation: `Docker: [Errno 101] Network is unreachable`

I am not very familiar with how docker handles network connections

**Comment by Slapbox** [comment]
Thanks so much again for all of your help @anonhostpi!

**Comment by ntindle** [comment]
Proxys are not well supported right now. Feel free to open a PR to add better proxy support.

**Comment by ntindle** [comment]
Ah okay sorry, thought the second comment was yours

**Comment by anonhostpi** [comment]
> @ntindle but I'm not using a proxy - or at least I'm not intending to. Are you sure this is a proxy issue?

Removing the proxy label

Also #1010 had the same problem. It was closed, because maintainers originally thought that it was a rate limit error.

**Comment by Slapbox** [comment]
I did get it to work without Docker. It may be some problem with the Docker image configuration or its network configuration. The redis machine seems to start but the autogpt machine seems not to.

Some more details on how that all works (or is supposed to work) would be valuable to someone trying to troubleshoot.

**Comment by rendivs925** [comment]
just turn off your firewall
