### ISSUE TITLE
Python problem?

### ISSUE THREAD

**Issue by okohide** [Significant-Gravitas/Auto-GPT#3984]
Dear all,

I got these message when I ran Auto-GPT at the final step of installation.
Could you please tell me my Python 3 in Mac was not appropriate? 
"Missing packages:
beautifulsoup4, colorama, distro, openai, playsound, python-dotenv, pyyaml, readability-lxml, requests, tiktoken, gTTS, docker, duckduckgo-search, google-api-python-client, pinecone-client, redis, orjson, Pillow, selenium, webdriver-manager, jsonschema, tweepy, click, charset-normalizer, spacy, en-core-web-sm, coverage, flake8, numpy, pre-commit, black, isort, gitpython, auto-gpt-plugin-template, mkdocs, pymdown-extensions, openapi-python-client, pytest, asynctest, pytest-asyncio, pytest-benchmark, pytest-cov, pytest-integration, pytest-mock, vcrpy, pytest-recording
Installing missing packages...
./run.sh: line 6: pip: command not found
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/Users/hideakiokochi/Auto-GPT/autogpt/__init__.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'"

Thank you so much for your help.
hideaki

**Comment by FLAWING2016** [comment]
Do you intall pip correctly and add it to PATH?

**Comment by Concara3443** [comment]
> Do you intall pip correctly and add it to PATH?

I have the same problem, and pip is installed correctly (Version 23.0.1)

**Comment by COMMANDO2406** [comment]
You may need to add the path after installing pip, this seems to be the tutorial I used: https://www.alphr.com/pip-is-not-recognized-as-an-internal-or-external-command/

Hope this helps

**Comment by dron4ik86** [comment]
Same thing for me, my PATH looks good
