### ISSUE TITLE
Sometimes line breaks in PLAN shows as \n

### ISSUE THREAD

**Issue by nicmar** [Significant-Gravitas/Auto-GPT#399]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

I'm not sure how to reproduce it, i've had it running trying to make a crossword generator for a while.

### Current behavior 😯

The PLAN: output shows this:
-  Add a text entry box function for player input\n- Create a function to validate the user's input\n- Compare the user input to the correct answer and display the correct answer if necessary

### Expected behavior 🤔

It should show this.
- Add a text entry box function for player input
- Create a function to validate the user's input
- Compare the user input to the correct answer and display the correct answer if necessary

### Your prompt 📝

I can't find the last_run_ai_settings.yaml, however it seemed to remember my prompt from last time. I had some problems with the application crashing several times, before i got it working.

**Comment by nicmar** [comment]
Now I saw double backslashes like this in the output:

```
-  Create a function that generates the empty grid for the crossword.\\n- Place the words into the grid, ensuring that they don't overlap and fit within the grid dimensions.\\n- Once all the words are placed, fill in the empty spaces with random letters.\\n- Test the function by calling it and verifying that the generated crossword is correct.

```

Also i noticed it sometimes has an empty "-" in the end.

**Comment by Qoyyuum** [comment]
Hi @nicmar is this still a problem if you try the latest stable release?
