### ISSUE TITLE
Missing space and spelling correction in feedback from Auto-GPT

### ISSUE THREAD

**Issue by kristianjackson** [Significant-Gravitas/Auto-GPT#3992]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows Subsystem for Linux (WSL)

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

Any command that generates the following prompt:

Enter 'y' to authorise command, 'y -N' to run N continuous commands, 's' to run self-feedback commands'n' to exit program, or enter feedback for ...

### Current behavior 😯

There is a space missing after the 
's' to run self-feedback commands

and before the
'n' to exit program

Also, authorize is misspelled as authorise

### Expected behavior 🤔

Instead of:
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 's' to run self-feedback commands'n' to exit program, or enter feedback for ...

It should read:
Enter 'y' to authorize command, 'y -N' to run N continuous commands, 's' to run self-feedback commands 'n' to exit program, or enter feedback for ...

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by anonhostpi** [comment]
comma and a space
