### ISSUE TITLE
Dead loop in unknown command

### ISSUE THREAD

**Issue by PinkPanther-ny** [Significant-Gravitas/Auto-GPT#3994]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

It happens sometime, I let autogpt to analyze two repos, after reading some code, with expected analyze, reasoning, plans, it start dead loop.

### Current behavior 😯

CRITICISM:  constructive self-criticism
NEXT ACTION:  COMMAND = command name ARGUMENTS = {'arg name': 'value'}
SYSTEM:  Command command name returned: Unknown command 'command name'. Please refer to the 'COMMANDS' list for available commands and only respond in the specified JSON format.
 THOUGHTS:  thought
REASONING:  reasoning
PLAN: 
-  short bulleted
-  list that conveys
-  long-term plan
CRITICISM:  constructive self-criticism
NEXT ACTION:  COMMAND = command name ARGUMENTS = {'arg name': 'value'}
SYSTEM:  Command command name returned: Unknown command 'command name'. Please refer to the 'COMMANDS' list for available commands and only respond in the specified JSON format.
 THOUGHTS:  thought
REASONING:  reasoning
PLAN: 
-  short bulleted
-  list that conveys
-  long-term plan
CRITICISM:  constructive self-criticism
NEXT ACTION:  COMMAND = command name ARGUMENTS = {'arg name': 'value'}
SYSTEM:  Command command name returned: Unknown command 'command name'. Please refer to the 'COMMANDS' list for available commands and only respond in the specified JSON format.
 THOUGHTS:  thought
REASONING:  reasoning
PLAN: 
-  short bulleted
-  list that conveys
-  long-term plan
CRITICISM:  constructive self-criticism
NEXT ACTION:  COMMAND = command name ARGUMENTS = {'arg name': 'value'}
SYSTEM:  Command command name returned: Unknown command 'command name'. Please refer to the 'COMMANDS' list for available commands and only respond in the specified JSON format.
 THOUGHTS:  thought
REASONING:  reasoning
PLAN: 
-  short bulleted
-  list that conveys
-  long-term plan
CRITICISM:  constructive self-criticism
NEXT ACTION:  COMMAND = command name ARGUMENTS = {'arg name': 'value'}

### Expected behavior 🤔

It should find exist commands, choose to use them.

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by Boostrix** [comment]
see #3668

**Comment by georgezlei** [comment]
I ran into the same issue. 

<img width="1308" alt="image" src="https://github.com/Significant-Gravitas/Auto-GPT/assets/97066/6e2e150b-7435-4fdb-bfce-29f46523d296">
