### ISSUE TITLE
Improve web-crawling system

### ISSUE THREAD

**Issue by Torantulino** [Significant-Gravitas/Auto-GPT#4]
Auto-GPT should be able to see links on webpages it visits, as well as the existing GPT-3 powered summary, so that it can browse further than 1 page away from google.

**Comment by Torantulino** [comment]
This is currently majorly limiting Auto-GPT's capabilities.
It essentially is unable to reliably browse the web and frequently misses information even though it's visiting the correct URLs.

**Comment by Andythem23** [comment]
Maybe a different prompt will do it for GPT-3.5

**Comment by 0xcha05** [comment]
can you provide more context, please? 
I've tried "extract key information from this webpage text" and given it hackernews text, and it did a decent job.

**Comment by Torantulino** [comment]
## Current Implementation

Web browsing is currently handled in the following way:

```python
def browse_website(url):
    summary = get_text_summary(url)
    links = get_hyperlinks(url)

    # Limit links to 5
    if len(links) > 5:
        links = links[:5]

    result = f"""Website Content Summary: {summary}\n\nLinks: {links}"""

    return result

def get_text_summary(url):
    text = browse.scrape_text(url)
    summary = browse.summarize_text(text)
    return """ "Result" : """ + summary

def get_hyperlinks(url):
    link_list = browse.scrape_links(url)
    return link_list
``` 

Where `scrape_text` uses BeautifulSoup to extract the text contained within a webpage.

## The Problem

The `summarize_text` function feeds GPT3.5 this scraped text, and whilst gpt3.5 does a great job of summarising it, it doesn't know what we're specifically after.

This leads to instances where AutoGPT can be looking to find some news on CNN, and instead receives a summary of what CNN is.

### An Illustrated Example 

![image](https://user-images.githubusercontent.com/22963551/229337183-a40fe39f-e2d2-4467-a3c5-bf8330163695.png)
- Here, Auto-GPT is trying to browse a news site to find a technology related news story.
- They select https://www.theverge.com/tech, a screenshot from which can be seen below:



<img width="322" alt="2022-04-09_122409" src="https://user-images.githubusercontent.com/22963551/229337269-e4779dcf-689b-4585-9b62-350a9c6d8128.png">




- Even though there are clearly news stories contained within this page, the summary does not include them specifically, just mentions they are there.
- 
**Summary:**
> Website Content Summary: "Result" : The Tech subpage of The Verge provides news on hardware, apps, and technology from various companies including Google and Apple as well as smaller startups. It includes articles on various tech topics and links to the website's legal and privacy information.

**Comment by 0xcha05** [comment]
okay, thanks for the context. I'll try to see what I can do.

**Comment by 0xcha05** [comment]
tried to get it to work, but I don't have access to gpt-4 API, but with gpt-3.5-turbo, it works for some and doesn't for others even with strict prompting. but gpt-4 should be able to do it with strict prompting.

**Comment by djrba** [comment]
Might be easier to add 3rd party support for example: https://www.algolia.com/pricing/
If their API can do the heavy lifting, it will be easier, there are some oss plugins as well

**Comment by ryanpeach** [comment]
https://github.com/Torantulino/Auto-GPT/pull/121

**Comment by ThatXliner** [comment]
> Might be easier to add 3rd party support for example: https://www.algolia.com/pricing/
> If their API can do the heavy lifting, it will be easier, there are some oss plugins as well

https://github.com/neuml/txtai

**Comment by JohnnyIrvin** [comment]
@Torantulino I see that you're using BeautifulSoup for processing the content of the site. This won't handle data that has to be injected into a site via say JavaScript. I'm not sure exactly how, but some of the RESTful / GraphQL / etc calls could be helpful for summarizing a page.

We could also consider pulling the metadata from the page and using that to determine how to prompt the summarization. To be fair, I haven't looked at the prompting code yet and don't know if you're already doing this.

**Comment by Nnnsightnnn** [comment]
@Torantulino 

### What about bs4 (BeautifulSoup4)?  

`"""
This module is designed to scrape text and hyperlinks from a given URL, summarize the text,
and return a limited number of hyperlinks. It uses the requests library for making HTTP requests,
BeautifulSoup for parsing HTML, and a custom 'browse' module for text summarization.
"""

import requests
from bs4 import BeautifulSoup
import browse

def browse_website(url, max_links=5, retries=3):
    # Use a session object for connection pooling and better performance
    with requests.Session() as session:
        scraped_data = scrape_data(url, session, retries)
        summary = get_text_summary(scraped_data['text'])
        links = get_hyperlinks(scraped_data['links'], max_links)

    result = f"""Website Content Summary: {summary}\n\nLinks: {links}"""
    return result

def get_text_summary(text):
    # Use the custom 'browse' module to summarize the text
    summary = browse.summarize_text(text)
    return f' "Result" : {summary}'

def get_hyperlinks(links, max_links):
    # Limit the number of hyperlinks returned to the specified maximum
    return links[:max_links]

def scrape_data(url, session, retries):
    # Make requests to the specified URL and parse the HTML content
    for i in range(retries):
        try:
            response = session.get(url, headers={'User-Agent': 'Mozilla/5.0'})
            response.raise_for_status()
            soup = BeautifulSoup(response.text, 'html.parser')
            text = ' '.join([p.get_text() for p in soup.find_all('p')])
            links = [a.get('href') for a in soup.find_all('a')]
            return {'text': text, 'links': links}
        except requests.exceptions.RequestException as e:
            # Retry the request if an exception occurs, up to the specified retry limit
            if i == retries - 1:
                raise e
`

**Comment by JustinHinh** [comment]
This is the single biggest issue in facing with GPT3.5-turbo and Auto-GPT

It is not reliably able to go to a website and pull out and summarize key information.

My use case is going to a job posting and pulling out a summary to compare to my resume. This works be a game changer

**Comment by Nnnsightnnn** [comment]
I also modified above code to handle Javascript using Selenium.  

```
pip install selenium

```

```

"""
This module is designed to scrape text and hyperlinks from a given URL, summarize the text,
and return a limited number of hyperlinks. It uses the requests and Selenium libraries for making
HTTP requests, BeautifulSoup for parsing HTML, and a custom 'browse' module for text summarization.
"""

import requests
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
import browse

def browse_website(url, max_links=5, retries=3):
    # Use a session object for connection pooling and better performance
    with requests.Session() as session:
        scraped_data = scrape_data(url, session, retries)
        summary = get_text_summary(scraped_data['text'])
        links = get_hyperlinks(scraped_data['links'], max_links)

    result = f"""Website Content Summary: {summary}\n\nLinks: {links}"""
    return result

def get_text_summary(text):
    # Use the custom 'browse' module to summarize the text
    summary = browse.summarize_text(text)
    return f' "Result" : {summary}'

def get_hyperlinks(links, max_links):
    # Limit the number of hyperlinks returned to the specified maximum
    return links[:max_links]

def scrape_data(url, session, retries):
    # Make requests to the specified URL and parse the HTML content
    for i in range(retries):
        try:
            # Set up a headless Chrome browser
            chrome_options = Options()
            chrome_options.add_argument("--headless")
            driver = webdriver.Chrome(options=chrome_options)

            # Navigate to the URL and render the JavaScript content
            driver.get(url)
            html = driver.page_source

            # Parse the rendered HTML with BeautifulSoup
            soup = BeautifulSoup(html, 'html.parser')
            text = ' '.join([p.get_text() for p in soup.find_all('p')])
            links = [a.get('href') for a in soup.find_all('a')]

            driver.quit()
```

            return {'text': text, 'links': links}
        except Exception as e:
            # Retry the request if an exception occurs, up to the specified retry limit
            if i == retries - 1:
                raise e

**Comment by gigabit-eth** [comment]
Looking for feedback on https://github.com/Torantulino/Auto-GPT/pull/507, it's my first time making one of these.

**Comment by IsleOf** [comment]
Few tips for scraping here, use selenium with opencv, make sure to force scroll to bottom of the page to load everything.

**Comment by Nnnsightnnn** [comment]
Here's pull request for fix.  It utilizes Pyppteer to navigate JavaScript sites. Lots of adaptability and flexibility.  

[https://github.com/Torantulino/Auto-GPT/pull/508](https://github.com/Torantulino/Auto-GPT/pull/508)

**Comment by IsleOf** [comment]
Pix2struct to capture structure and plain ocr could give acceptable results if everything else fails .

**Comment by Nnnsightnnn** [comment]
Where are we at for logging into websites during web-crawling?

**Comment by IsleOf** [comment]
Selenium or pupetteer or similar for web ui logins would be optimal i guess imho.

**Comment by jheathco** [comment]
Mechanize would work well, although not functional with JS.

**Comment by Pwuts** [comment]
Selenium + Chromium + Firefox are now in `master`. Closing as completed! :)

**Comment by R00dNet** [comment]
how much flexibility do we have to configure default code to direct the AI where we want it to go and grab what we want along the way?
