### ISSUE TITLE
Where is the output of the current work in progress?

### ISSUE THREAD

**Issue by nicmar** [Significant-Gravitas/Auto-GPT#400]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

This isn't a feature request, but not a bug report either. Hope it's ok I post it here. :)

I've been running it for a while, to test on how to create a crossword puzzle game. However, i don't see any output at all in my Auto-GPT folder. There is an auto_gpt_workspace, but it's empty.

It has been working on it for several iterations, and it seems like it's correcting it's code etc. But is it writing something, and should I be able to see this somewhere? Or is it just keeping the code and everything in memory?

When does it end? Also if I set it to continuos mode, can i somehow break it and give input at some step?

Thanks for this great and super interesting application! :)

**Comment by nicmar** [comment]
Is there maybe some problem with write access, i just saw this problems with open_file and read_file.

`-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-=
SYSTEM:  Command open_file returned: Unknown command open_file
GAME MAKER THOUGHTS: I suggest that we implement the ability for the crossword generator to read in a list of words from a text file, rather than just having them hard-coded in the Python script. This will provide an additional layer of flexibility, allowing users to easily customize the crossword generation by using different word lists.
REASONING: Reading in a list of words from a text file will provide users with greater flexibility and customization over their crossword generation experience, as it is easier to modify a text file than hard-coded Python code.
PLAN:
-  Create a new function in the script that reads in a text file containing words that can be used in a crossword.\n- Modify the script to call this new function to retrieve the words.\n- Test the functionality to ensure that words are correctly read in and utilized in the crossword generation process.
CRITICISM: It is important to ensure that the text file is properly formatted and that the script can correctly parse it. Appropriate error handling should be implemented for potential errors reading in the text file.
NEXT ACTION:  COMMAND = read_file ARGUMENTS = {'file': '<path to file containing word list>'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for Game Maker...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-=
SYSTEM:  Command read_file returned: Error: [Errno 2] No such file or directory: 'auto_gpt_workspace/<path to file containing word list>'
| Thinking...`

**Comment by nicmar** [comment]
After giving this input and adding some words in the file, it seemed to read it successfully. But nothing else showed up in the folder other than my own file.

**Input:use the file words.txt in the path**

```
SYSTEM:  Human feedback: use the file words.txt in the path
GAME MAKER THOUGHTS: Now that we have the text file open, we need to create a new function to parse the file and extract the words for the crossword. We will use Python's built-in file handling methods to read in the file and extract the words. We then need to return these words so that they can be used by the crossword generator function.
REASONING: Creating a function dedicated to reading in and extracting words from the text file will make the code easier to read and modify, as its specific purpose is clearly defined. This also allows for error handling to be added explicitly at the function level.
PLAN:
-  Create a new function that reads in the text file and extracts the words.\\\\n- Use Python's built-in file handling methods to read in the file and extract the words.\\\\n- Return the words as a list or other data structure that can be used by the crossword generator.\\\\n- Test the new function by calling it and verifying that the returned words are correct.
CRITICISM: It is important to ensure that the function is correctly reading in and extracting the words from the file. Appropriate error handling should be implemented for potential issues, such as formatting errors in the text file.
NEXT ACTION:  COMMAND = read_file ARGUMENTS = {'file': 'words.txt'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for Game Maker...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-=
SYSTEM:  Command read_file returned: fish horse monkey donkey action banana apple pear

```

**Comment by aosan** [comment]
short term processing files are stored and used from auto_gpt_workspace. The final output file/s will be stored there, all the other processing files will be deleted.
A successful answer will output the response, but not if it's stopped. Using the` --continuous` flag will have the output, given a successful end of a job. Careful, it will take a long time and a lot of tokens, depending on the number and complexity of the objectives.

If you want to keep the processing files, I've had success with modifying `the first constrain in Auto-GPT/scripts/data/prompt.txt from:

1. ~4000 word limit for short term memory. Your short term memory is short, so immediately save important information to files.

to

1. ~4000 word limit for short term memory. Your short term memory is short, so immediately save important information to files. Do not delete the files.

I also modified the order of RESOURCES to:

RESOURCES:

1. Internet access for searches and new useful information gathering.
2. Long Term memory management.
3. File output.
4. GPT-3.5 powered Agents for delegation of simple tasks.

With this order of priorities, it looks at data it already searched and stored in files before asking GPT-3.5.

**Comment by Explorergt92** [comment]
@nicmar is this still an issue for you or can this be closed?

**Comment by Pwuts** [comment]
Closing as stale
