### ISSUE TITLE
chat.py line 203 should read "agent.config.prompt_generator" but instead has "agent.prompt_generator". Easy fix.

### ISSUE THREAD

**Issue by eliyah23rd** [Significant-Gravitas/Auto-GPT#4003]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of Auto-GPT are you using?

Master (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

Sorry about not filling on all the other fields but this is too simple.

Exception thrown because agent does not have a property prompt_generator.
Cfg has that property and config is a property of agent.

Bug in file autogpt/llm/chat.py

Lines for context (in case line numbers change)

```
            plugin_count = len(cfg.plugins)
            for i, plugin in enumerate(cfg.plugins):
                if not plugin.can_handle_on_planning():
                    continue
                plugin_response = plugin.on_planning(
                    agent.prompt_generator, current_context # <--- should read: agent.config.prompt_generator, current_context
                )
                if not plugin_response or plugin_response == "":
                    continue
                tokens_to_add = count_message_tokens(
                    [create_chat_message("system", plugin_response)], model
                )
                if current_tokens_used + tokens_to_add > send_token_limit:
                    logger.debug("Plugin response too long, skipping:", plugin_response)
                    logger.debug("Plugins remaining at stop:", plugin_count - i)
                    break
                current_context.append(create_chat_message("system", plugin_response))

```

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by TKasperczyk** [comment]
Good catch, created a PR GH-4011

**Comment by TKasperczyk** [comment]
Merged. The issue can be closed.

**Comment by eliyah23rd** [comment]
Thank you

**Comment by k-boikov** [comment]
Fixed with https://github.com/Significant-Gravitas/Auto-GPT/pull/4011
