### ISSUE TITLE
AutoGPT not using provided credentials in prompt for third left API’s 

### ISSUE THREAD

**Issue by jeffmercury** [Significant-Gravitas/Auto-GPT#4021]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

Provide credentials for the API’s you want the AI to use (continuous mode) 

### Current behavior 😯

I’m attempting to have it send emails via Postmarks email Api. I give it the credentials it needs to call the api. The bot calls the api, but never uses the credentials I  provide. It just puts a generic “your_token” when creating the scripts. I even gave it and email to use and it left that out as well. 

### Expected behavior 🤔

Provide the credentials the AI needs to call your desired API’s, the AI uses the credentials and executes the code correctly. 

### Your prompt 📝

```yaml
# AI, your purpose is to send an email to '[tesr@yahoo.com](mailto:test@yahoo.com)' with the message "Hello, how are you?" using the Postmark email API. Use the server token "My_token" and the from email '[test@test.com](mailto:test@test.com)'. To learn how to accomplish this, visit the following webpage: https://postmarkapp.com/send-email/python. Ensure that you set the server token to "My_token" during implementation.
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by remriel** [comment]
Yeah I'm also a little confused about how to feed it API keys. It doesn't seem to recognize them whether I set them as environment variables, put them in a text file, or use data_ingestion.py to preseed them

**Comment by jeffmercury** [comment]
Ideally we shouldn’t even need a folder to house our API creds. The AI should be able to utilize what’s provided in the prompt the user submits. I see there’s a plug-in for sending emails, but this limits the AI, we should be able to use whatever third party API we have access to. Im running my instance through docker as well.
