### ISSUE TITLE
PLEASE Add new bing chat!

### ISSUE THREAD

**Issue by yhyu13** [Significant-Gravitas/Auto-GPT#4022]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Add new chat like this repo does, you just need to fill in a bing chat cookie at the landing page www.bing.com/new
It's easy. Besides new bing is free, and it can search the web plus being backed by GPT4

https://github.com/binary-husky/gpt_academic/blob/master/docs/README_EN.md

### Motivation 🔦

To get a web capable GPT4 with no charge at all!

Plus, new bing can now send images with DALL-E

**Comment by suparious** [comment]
There is an experimental plugin for this available here:
 - https://github.com/gravelBridge/AutoGPT-BingAI
 -

**Comment by ntindle** [comment]
Note that doesn't quite replace the chat completions as that would break their tos and also needs more abstracted prompting.
