### ISSUE TITLE
Data_Ingestion.py Still used?

### ISSUE THREAD

**Issue by remriel** [Significant-Gravitas/Auto-GPT#4024]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

The documentation states this command will pre-seed everything in the workspace, but I find it is ingesting the entire autogpt folder, not just the workspace.

python data_ingestion.py --dir . --init

### Current behavior 😯

The documentation states this command will pre-seed everything in the workspace, but I find it is ingesting the entire autogpt folder, not just the workspace.

python data_ingestion.py --dir . --init

### Expected behavior 🤔

Pre-seed only workspace folder

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by khongminhtn** [comment]
Hello, this is because your --dir argument is "." which indicates that it should ingest the root of the folder. If you want to ingest the workspace, you would need to specify the correct path to the workspace.

The correct command line is:
python data_ingestion.py --dir ./autogpt/auto_gpt_workspace --init

**Comment by remriel** [comment]
Right, so the documentation is out of date. It says

"The DIR path is relative to the auto_gpt_workspace directory, so python data_ingestion.py --dir . --init will ingest everything in auto_gpt_workspace directory"

**Comment by suparious** [comment]
Specifically

[https://github.com/Significant-Gravitas/Auto-GPT/blob/master/docs/configuration/memory.md](https://github.com/Significant-Gravitas/Auto-GPT/blob/master/docs/configuration/memory.md)
