### ISSUE TITLE
Cannot run with neither Docker nor Git

### ISSUE THREAD

**Issue by bimg21** [Significant-Gravitas/Auto-GPT#4055]
Hey, I am  unable to run Auto-GPT with either of the options.

Running with Docker (sudo docker-compose build auto-gpt) results in:

`Err:1 http://deb.debian.org/debian bullseye InRelease
  Temporary failure resolving 'deb.debian.org'
Err:2 http://deb.debian.org/debian-security bullseye-security InRelease
  Temporary failure resolving 'deb.debian.org'
Err:3 http://deb.debian.org/debian bullseye-updates InRelease
  Temporary failure resolving 'deb.debian.org'
Reading package lists...
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://deb.debian.org/debian-security/dists/bullseye-security/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package chromium-driver
E: Unable to locate package firefox-esr
The command '/bin/sh -c apt-get update && apt-get install -y     chromium-driver firefox-esr     ca-certificates' returned a non-zero code: 100
ERROR: Service 'auto-gpt' failed to build : Build failed
`

Running with Docker (./run.sh) in:
`
./run.sh: line 2: python: command not found
./run.sh: line 8: python: command not found
Press any key to continue...`

Any help please?

**Comment by suparious** [comment]
Seems that your docker system has networking problems. Try the Hello World tutorials from the Docker documentation to get it working, then try Auto GPT once that is working.

**Comment by bimg21** [comment]
Still "Temporary failure resolving 'deb.debian.org'". Pinging deb.debian.org also doesn't work, although internet is working normally otherwise.

**Comment by dewasahu2003** [comment]
Hi 👋

- _**First Error**_ :Try a different mirror: If the above steps don't work, you can try using a different Debian mirror. In the Dockerfile, replace the line `deb.debian.org` with another Debian mirror, such as` ftp.us.debian.org`
- _**Second Error**_ : check if python is installed in your system use `sudo apt-get install python` if python is installed check your python  PATH environment variable

**Comment by bimg21** [comment]
Thanks for the reply.
First Error : The file "Dockerfile" in /Auto-GPT doesn't have "deb.debian.org", nor "mirror" in it. :-/
Second Error : Well. I've had Python 3.10.6 installed before. But when I did "sudo apt-get install python-is-python3" it installed it again. It still says Python 3.10.6, but running ./run.sh worked this time and Auto-GPT seems ready to work. Thanks for your guidance! :)

**Comment by bimg21** [comment]
However now I have different issue:

After starting aGPT for the first time and trying a prompt "python --version" it went to a loop:
`
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
  Executing file '/home/kravinec/Auto-GPT/autogpt/auto_gpt_workspace/version.py'
SYSTEM:  Command execute_python_file returned: Error: File '/home/kravinec/Auto-GPT/autogpt/auto_gpt_workspace/version.py' does not exist.
 THOUGHTS:  The 'execute_python_file' command failed because the file 'version.py' does not exist. I can use the 'write_to_file' command to create the 'version.py' file and write the 'python --version' command to it.
REASONING:  I will use the 'write_to_file' command to create the 'version.py' file and write the 'python --version' command to it.
PLAN: 
-  Use the 'write_to_file' command to create the 'version.py' file and write the 'python --version' command to it.
-  Use the 'execute_python_file' command to run the 'version.py' file and capture the output.
CRITICISM:  I need to ensure that the file is created correctly and that the 'python --version' command is written to it without errors.
NEXT ACTION:  COMMAND = write_to_file ARGUMENTS = {'filename': '/home/kravinec/Auto-GPT/autogpt/auto_gpt_workspace/version.py', 'text': "import os\nos.system('python --version')"}
  Enter 'y' to authorise command, 'y -N' to run N continuous commands, 's' to run self-feedback commands'n' to exit program, or enter feedback for ...
  Asking user via keyboard...`

I interrupted the loop with Ctrl+C and now I cannot run it again.
./run.sh --speak
```
All packages are installed.
Speak Mode:  ENABLED
```
                                                            ...and nothing happens. It just hangs.

`python -m autogpt `
                                                            ...same thing.
