### ISSUE TITLE
feat: speak mode without elevenlabs (text to speech, use system/os tts instead)

### ISSUE THREAD

**Issue by brg2** [Significant-Gravitas/Auto-GPT#4068]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Use operating system's own text-to-speech engine instead of elevenlabs

### Motivation 🔦

Expensive to use elevenlabs for tts over time
Remove reliance on 3rd party software to implement tts

**Comment by brett-garrison-adsk** [comment]
@ntindle 

> another issue

link?
