### ISSUE TITLE
Error 'command' object is not a dictionary

### ISSUE THREAD

**Issue by 0bvio** [Significant-Gravitas/Auto-GPT#4124]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

When the AI tries to do next action "COMMAND", then it keeps telling me 'command' object is not a dictionary and it fails to take it's actions.  It also fails on every Google search as well, it is likely Chrome is not installed on the default path but I do not know howw to fix these issues.

### Current behavior 😯

NEXT ACTION:  COMMAND = Error: ARGUMENTS = 'command' object is not a dictionary
  Enter 'y' to authorise command, 'y -N' to run N continuous commands, 's' to run self-feedback commands'n' to exit program, or enter feedback for ...
  Asking user via keyboard...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-=
SYSTEM:  Command Error: threw the following error: 'command' object is not a dictionary
You can read more here: https://docs.agpt.co/setup/#getting-an-api-key
The JSON object is invalid.
 THOUGHTS:  I can use the 'google' command to search for information on a specific topic and the 'browse_website' command to browse a specific website for information. I can also use the 'get_hyperlinks' command to get a list of hyperlinks on a webpage and the 'get_text_summary' command to get a summary of the text on a webpage.
REASONING:  I need to use the appropriate commands to search for information and browse websites as requested by the user.
PLAN:
-  Use the 'google' command to search for information on a specific topic.
-  Use the 'browse_website' command to browse a specific website for information.
-  Use the 'get_hyperlinks' command to get a list of hyperlinks on a webpage.
-  Use the 'get_text_summary' command to get a summary of the text on a webpage.
CRITICISM:  I need to be more proactive in understanding the user's intent and purpose to ensure that my actions align with their goals.
NEXT ACTION:  COMMAND = Error: ARGUMENTS = 'command' object is not a dictionary
  Enter 'y' to authorise command, 'y -N' to run N continuous commands, 's' to run self-feedback commands'n' to exit program, or enter feedback for ...
  Asking user via keyboard...
Input:

### Expected behavior 🤔

Should work to run commands and such.  Also, every attempt to Google fails, I believe because we need to install chrome on the default path?  I can't seem to get the AI to do this for me, it wants to Google instructions but can't and runs in a loop.

### Your prompt 📝

```yaml
# Paste your prompt here
```
No prompt, confirming y for AI taking actions produces the result.  Not sure how else to really describe this issue.

### Your Logs 📒

```log
<insert your logs here>
```
NEXT ACTION:  COMMAND = Error: ARGUMENTS = 'command' object is not a dictionary
  Enter 'y' to authorise command, 'y -N' to run N continuous commands, 's' to run self-feedback commands'n' to exit program, or enter feedback for ...
  Asking user via keyboard...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-=
SYSTEM:  Command Error: threw the following error: 'command' object is not a dictionary
You can read more here: https://docs.agpt.co/setup/#getting-an-api-key
The JSON object is invalid.
 THOUGHTS:  I can use the 'google' command to search for information on a specific topic and the 'browse_website' command to browse a specific website for information. I can also use the 'get_hyperlinks' command to get a list of hyperlinks on a webpage and the 'get_text_summary' command to get a summary of the text on a webpage.
REASONING:  I need to use the appropriate commands to search for information and browse websites as requested by the user.
PLAN:
-  Use the 'google' command to search for information on a specific topic.
-  Use the 'browse_website' command to browse a specific website for information.
-  Use the 'get_hyperlinks' command to get a list of hyperlinks on a webpage.
-  Use the 'get_text_summary' command to get a summary of the text on a webpage.
CRITICISM:  I need to be more proactive in understanding the user's intent and purpose to ensure that my actions align with their goals.
NEXT ACTION:  COMMAND = Error: ARGUMENTS = 'command' object is not a dictionary
  Enter 'y' to authorise command, 'y -N' to run N continuous commands, 's' to run self-feedback commands'n' to exit program, or enter feedback for ...
  Asking user via keyboard...
Input:

**Comment by Boostrix** [comment]
There's work in progress to do command/argument validation, see the PR section

**Comment by 0bvio** [comment]
> There's work in progress to do command/argument validation, see the PR section

Yeeeaaaahhh.... you've gotta realize some people are really new to GitHub and may not understand your special abbreviations and terminology.  I don't know what a PR section is.  Where are these sections you're referring to?  What is "Command/Argument Validation"?  I have more questions now than I did before, but I suppose that's the process of learning.  I am just saying it would be easier to infer this knowledge if you didn't obfuscate it with abbreviations and such.

**Comment by 0bvio** [comment]
I have changed all the settings in my .env.template file.  I then changed it to .env so it was considered an ENV file.  Then I ran AutoGPT for the first time.  Upon first run, I still am being told it is using a local cache or JSON file for memory instead of the Pinecone I configured.  It also does not seem to use firefox as I set in the settings, but continues to try to use Chrome and ends up failing web functions because of this.  How can I get AutoGPT to recognize the settings I have set for it?

**Comment by Yashvardhn** [comment]
i had the same issue, i deleted the auto_gpt_workspace folder and it fixed this issue for me

**Comment by dudemyguy** [comment]
@Yashvardhn when you say you had the same issue do you mean as the comment directly above or as the OP? Are you saying deleting the auto_gpt_workspace folder fixed the command not found error?

**Comment by Yashvardhn** [comment]
@dudemyguy yes, i got the command not found error when i launched autogpt second time, i created another api link for openAi and deleted the workspace folder.
I noticed the first command it will ask is to create the workspace directory, i could be wrong but it worked for me

**Comment by 0bvio** [comment]
I am still getting the issue.  I deleted the auto_gpt_workspace and still, almost every command fails and says something like this

`  Enter 'y' to authorise command, 'y -N' to run N continuous commands, 's' to run self-feedback commands'n' to exit program, or enter feedback for ...
  Asking user via keyboard...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-=
SYSTEM:  Command generate_document_outline returned: Unknown command 'generate_document_outline'. Please refer to the 'COMMANDS' list for available commands and only respond in the specified JSON format.`

**Comment by jwuliger** [comment]
I am also getting this error. It occurs when I run docker or on my local Windows machine.

**Comment by adrianfrost** [comment]
> Add quotes to openai key as in "....."

man, this just worked perfectly.

**Comment by Boostrix** [comment]
if so, that sounds like something that should be documented and ideally done at the env file level to document best practices ?
