### ISSUE TITLE
Support for GPT4All or other opensource models to reduce costs

### ISSUE THREAD

**Issue by simonfranzen** [Significant-Gravitas/Auto-GPT#414]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Hey, are there any plans to cover more LLMs? We could all reduce the development and usage costs if we allow to integrate GPT4All or other open source models. Anyone already working on this topic? Thanks

### Motivation 🔦

Reduce development and usage costs

**Comment by nicmar** [comment]
Would be great!

**Comment by igorbarshteyn** [comment]
Similar request exists for LLaMA in #438

**Comment by pmb2** [comment]
https://github.com/lm-sys/FastChat

**Comment by Qoyyuum** [comment]
Closing as a duplicate to #438
