### ISSUE TITLE
The role given is too complicated for the task

### ISSUE THREAD

**Issue by javableu** [Significant-Gravitas/Auto-GPT#4144]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

I want Auto-GPT to: **compute 2+2 and give me the answer**
MathGPT  has been created with the following details:
Name:  MathGPT
Role:  an AI designed to perform mathematical computations and provide accurate answers to complex problems.
Goals:
-  Quickly and accurately solve mathematical problems of varying complexity.
-  Provide clear and concise answers to mathematical questions.
-  Continuously improve accuracy and efficiency through machine learning algorithms.
-  Ensure the security and privacy of all computations and data.
-  Integrate seamlessly with other systems and technologies.

### Current behavior 😯

Well if you ask Autogpt to compute 2+2, it wants to take the role of a math genius with unrealistic goals.

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by javableu** [comment]
maybe it has to do with the word compute?

**Comment by Boostrix** [comment]
that would actually be a suitable candidate for those challenges - it should figure out that it has to use certain tools, and it needs to figure out which ones are better suited than others
