### ISSUE TITLE
Running AutoGPT in --non-interactive mode

### ISSUE THREAD

**Issue by miradnan** [Significant-Gravitas/Auto-GPT#4171]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

I want to run autogpt in a non-interactive mode. Like a background task on linux to run continuously. Currently I get a list of warnings from plugins that won't allow the script to proceed further. It requires manual input. 

Having a flag `--non-interactive` that can ignore warnings / user prompts will helpful to automation of tasks.

### Examples 🌈

These are the warning messages
![Screenshot 2023-05-13 at 8 08 38 PM](https://github.com/Significant-Gravitas/Auto-GPT/assets/397415/0a9eeb69-73cb-4b22-b6cf-25b94454c62d)

### Motivation 🔦

The ability to run autogpt continuously. Just like a linux service.

**Comment by ntindle** [comment]
Diplicate
