### ISSUE TITLE
Generating cassettes locally is not necessary

### ISSUE THREAD

**Issue by merwanehamadi** [Significant-Gravitas/Auto-GPT#4189]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

People waste time playing with the cassettes, but really the cassettes are only here to make tests quicker and cheaper.
When someone works on a challenge he doesn't need the cassettes because he keeps changing the prompt.

Obviously we should still be able to use the cassettes locally

There is actually no mode as we speak that is like new_episodes, except it doesn't record cassettes.
We need a solution

**Comment by Boostrix** [comment]
for starters, it might help to introduce to folks what "cassettes" refers to in the context of prompt engineering and unit testing
