### ISSUE TITLE
support ai chat

### ISSUE THREAD

**Issue by nekohacker591** [Significant-Gravitas/Auto-GPT#422]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

allow the ais to respond each other with support for diffrent prompts

### Examples 🌈

make ai 1 goku
make ai 2 vegeta

have a conversation between them

### Motivation 🔦

create a roleplay between 2 ais

**Comment by Qoyyuum** [comment]
I doubt this is in the scope for AutoGPT. Perhaps as a potential plugin, maybe.

**Comment by Pwuts** [comment]
Closing as out of scope. Please make this into a plugin! :)
