### ISSUE TITLE
Type Error in `autogpt/memory_management/summary_memory.py`

### ISSUE THREAD

**Issue by dewasahu2003** [Significant-Gravitas/Auto-GPT#4221]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Current behavior 😯

The return type of `update_running_summary` is str in function description 

### Expected behavior 🤔

- But `update_running_summary` is returning a `dict[str,str]` object 
- the same thing persist in the function documentation

**Comment by k-boikov** [comment]
True, but that should not cause an error?

**Comment by dewasahu2003** [comment]
Yeah
- But when i was debugging the code for issue #3846 ,this seems to add a little complexity while debugging
