### ISSUE TITLE
  Unable to automatically generate AI Config based on user desire (I searched..a lot)

### ISSUE THREAD

**Issue by chronuz11** [Significant-Gravitas/Auto-GPT#4241]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

Have Auto-GPT on 2 Computers. Both ran fine until 2 days ago. Won't do even any simple prompts like "Research AI" etc.
Havent changed anything locally. Clueless about what to do.
Help would be very much appreciated.

I have a paid OpenAI acc.

The only other "Issue"-thread says its connected to complicated command prompts
![error](https://github.com/Significant-Gravitas/Auto-GPT/assets/131885056/4bc06eb2-74c0-4e83-a0d5-7aba7633aa3e)

Maybe I am dumb...go easy on me 

### Current behavior 😯

Doesn't run the prompt, reverts to manual mode, fails again.

### Your prompt 📝

```yaml
# Research AI
# Research cats
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by Boostrix** [comment]
with that sort of priming, you'd probably  rather edit ai_settings.yml directly

**Comment by Boostrix** [comment]
try ai_settings.yml directly next - just to see if your OpenAI access is working

**Comment by cc46808** [comment]
I had this happen when setting `SMART_LLM_MODEL=gpt-4`. 
GPT-4 currently has a cap of 25 messages every 3 hours, even though I have a ChatGPT Plus Subscription.

Reverting back to `SMART_LLM_MODEL=gpt-3.5-turbo` worked.

**Comment by ValeraT1982** [comment]
Same issue on Windows :(

**Comment by TGANDTechnologies** [comment]
I am currently having this issue. reverting to 3.5 did not work for me though.
