### ISSUE TITLE
Challenges: New cases for  Information Retrieval 

### ISSUE THREAD

**Issue by rihp** [Significant-Gravitas/Auto-GPT#4244]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Trying to make some new challenges today
information retrieval: 

- Anthropic's new model token context window: 100k
- Founder of AutoGPT: Toran
- SpaceX Super Heavy First flight : 20 April 2023
- Twitter CEO as of May 2023: Linda Yaccarino
- Author of Generative Agents: Interactive Simulacra of Human Behavior : Park
- Does Milvius 2.3 support GPU acceleration? Yes
 

### Motivation 🔦

https://github.com/Significant-Gravitas/Auto-GPT/blob/master/docs/challenges/building_challenges.md

**Comment by rihp** [comment]
@Boostrix said on discord:
> regarding those challenges, if/when we can get that to work, we could use the same benchmarks for the next level, by asking for the relevant dates of these events 👍

**Comment by rihp** [comment]
Pr linked above has been updated with 6 more challenges

**Comment by Pwuts** [comment]
@rihp the linked PR is still a draft. Do you still intend to finish it? And does this issue have to stay open? :)
