### ISSUE TITLE
No module named 'pandas'

### ISSUE THREAD

**Issue by AlexDep** [Significant-Gravitas/Auto-GPT#4265]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

Prompt :

`python3 -m autogpt --gpt3only`

From that create an agent :

'Market research for bike trends"

### Current behavior 😯

![image](https://github.com/Significant-Gravitas/Auto-GPT/assets/29424527/49acf00f-89b9-4e52-a2e7-edb3b1ea6e4b)

![image](https://github.com/Significant-Gravitas/Auto-GPT/assets/29424527/a85a08b4-b768-409a-86e7-176fa0dd8041)

### Expected behavior 🤔

Should be able to use pandas if it tells that it install successfully

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by Devang-C** [comment]
> 

You need to first install pandas on your machine. You can do that by running the below command

`pip3 install pandas`

**Comment by k-boikov** [comment]
Python files are executed in a Docker container for security reasons, the shell popen commands are executed locally. That is pending rework. For now the best solution is to run everything in Docker.

**Comment by AlexDep** [comment]
I installed pandas in another terminal, and it didn't affect auto-GPT, restarted it and worked. 

Thanks.

**Comment by MLeall** [comment]
How exactly did you make it work? I'm using AutoGPT in a virtual environment (venv), and I suspect that it may be affecting it. I've tried to create instructions to install any necessary pip package directly in the main code of the script, but it didn't work. Do I need to create a Docker image with tons of pre-set packages?
