### ISSUE TITLE
Auto-GPT violates Google Custom Search API ToS

### ISSUE THREAD

**Issue by avelican** [Significant-Gravitas/Auto-GPT#4267]
Unfortunately, the Google Custom Search API may not be used by automated systems.

This means that any Auto-GPT user who uses this API is in violation of Google's ToS and putting their Google account at risk of termination.

https://developers.google.com/custom-search/terms
depends on this ToS
https://support.google.com/programmable-search/answer/1714300
which forbids using the API through automated systems.

As far as I can tell there is no workaround here, and the API should be removed from the project.
(If not, at the very least add a strong "proceed at your own risk" warning.)

**Comment by Boostrix** [comment]
Another good reason why we need to diversify away from SPOFs like openai, Google or even github.

Should probably generalize "search" and support a handful of services to provide alternatives and customization options.

If people do decide to ignore such TOS it should be due to their own conscious decision and not due to default settings used by the project

**Comment by gautamm20** [comment]
I don't think this is true. An API by definition means that it will be used by another script which by definition is "automated". I tried to read through the links and could not find this verbiage. Could you help point out the specific clauses you are referring to?

**Comment by Boostrix** [comment]
This is what gpt itself says "Prohibited activities: Google's terms may prohibit certain activities, such as scraping or automated querying of search results, storing or caching large amounts of data"

**Comment by gautamm20** [comment]
That has nothing to do with the API. That is for general scraping. Why
would Google release and support an API whose sole purpose is to return
search results through another platform?

Cheers,
Gautam

**Comment by EasternPA** [comment]
Would be nice if Whoogle had an API for searches. https://github.com/benbusby/whoogle-search
