### ISSUE TITLE
Autogpt never writes python code to python scripts despite being able to create and write to files

### ISSUE THREAD

**Issue by JetpackFandango** [Significant-Gravitas/Auto-GPT#427]
I'm using the gtp 3.5 only version if that makes a difference. For some reason despite being able to come up with code and evaluate it successfully it's never able to write that code to a python file. I know it has write access because it creates the base file and it even writes to it basic things like

""" Code for researching and compiling a list of 2023 slang words and definitions"""

# Define necessary functions here

But after it comes up with the code, it fails to ever write it to the file it meant to.

**Comment by jdohn15** [comment]
only after I've let mine run for quite some time it eventually makes a file, but for only some of the code it comes up with. It is odd how it chooses to make what it makes. Sometimes it makes stuff to never use again and it just sits there while auto-gpt goes off into its own little world for a while.

**Comment by Qoyyuum** [comment]
It can now write properly and execute the code inside a Docker container. Please pull latest stable release and give it a try. Closing issue.
