### ISSUE TITLE
Move test cassettes out of main repo

### ISSUE THREAD

**Issue by Pwuts** [Significant-Gravitas/Auto-GPT#4284]
### 🚨 Priority
Since this issue blocks progress on the challenge system, we would like to have a solution before 20 May 14:00 UTC (48h from now) if possible.

### Summary 💡

Running all of our tests in CI would cost up to $1 per run if it wasn't for VCR: a mechanism for caching API requests. They are stored in so-called cassette files, which currently live in the main repository.

Problems with this approach:
* it adds significant weight to the git history of the main repo, because cassettes are big chunks of data
* it can cause problems with CI when a PR changes the way a prompt is generated, causing the request to miss the cache and failing the test

### Desired solution
**Storing all of our cassettes outside of the main repository.**
We currently think the best option is to move them to a separate git repository, which can then be included as submodule or as a dependency in `requirements.txt`. Another option might be to store them in the GitHub Action Cache.

Requirements for a solution:
* must work with pull requests from the main repository
* must work with pull requests from forks
* must not add significant weight to the main repository
* should not cause a hassle when a developer switches between branches or is on a slightly outdated version of the main branch

### Preliminary todo list
- [ ] Change pytest configuration so it stores all cassettes under a separate directoy; one that does not contain code
- [ ] Pick a storage solution for the cassettes that can satisfy the requirements above
- [ ] Create a (draft) PR and link this issue
- [ ] Implement solution

### Motivation 🔦

We want to provide developers with a smooth and engaging development workflow, while also saving on API costs.

**Comment by BaseInfinity** [comment]
I may be interested but I'm also new (to the repo and VCR) so I figure asking more questions won't hurt whoever ends up picking this up:

Are we essentially moving [this directory of YAML files](https://github.com/Significant-Gravitas/Auto-GPT/tree/master/tests/integration/cassettes) to another repo and then including it as a submodule here?

Seems straight forward if that's the meat of this issue. I imagine we also want to tap into git hook scripts to ensure submodules are up to date when switching branches or running tests.

Also maybe including a helper script whenever we want to update the cassette files since not everyone is comfortable with git submodules (though maybe this last part isn't a requirement if we assume devs have Git submodule knowledge)

**Comment by Pwuts** [comment]
> Are we essentially moving [this directory of YAML files](https://github.com/Significant-Gravitas/Auto-GPT/tree/master/tests/integration/cassettes?rgh-link-date=2023-05-18T18%3A42%3A11Z) to another repo and then including it as a submodule here?

@BaseInfinity partially correct: there are multiple directories containing cassettes at the moment, nested in the `tests/` directory structure:
![image](https://github.com/Significant-Gravitas/Auto-GPT/assets/12185583/57149412-bed5-4b15-bd6f-c6f300b24bcd)
All of these folders have to be moved into one directory containing only cassettes, e.g. `tests/cassettes`, which can then be moved to a submodule.

**Comment by BaseInfinity** [comment]
So I think I understand the overall goal, had some questions after poking more in repo:
I found here we are running some Updating of VCR code, I'm guessing that will have to update the CI workflow as well?
https://github.com/Significant-Gravitas/Auto-GPT/blob/e2851dc73f3d148c97d54b3a9c710a854b0724b2/.github/workflows/ci.yml#L96-L105

Looking at the Pytest-vcr docs it looks like here's relevant code I'll need:
![image](https://github.com/Significant-Gravitas/Auto-GPT/assets/1424113/89d4bd62-320c-46e3-afb4-a9ab5f2814f9)

I noticed there are multiple `conftest.py` files:
![image](https://github.com/Significant-Gravitas/Auto-GPT/assets/1424113/a62d9516-142f-4a7e-85d8-4096e715b19f)

Do all three need to be updated? Just want to make sure I understand scope, thanks!

**Comment by Pwuts** [comment]
> Ahhh I see okay thank you for clarification. Is there a repo created for the Git submodules already? I'd lean towards that solution instead of GH Actions Cache if you want to be able to run these tests locally as well as in CI.

Not yet, but I can do that once it is the obvious next thing to do.

> I found here we are running some Updating of VCR code, I'm guessing that will have to update the CI workflow as well or is there a diff strategy with managing Cassettes in CI?

That code is the direct motivation for this issue: we want to auto-update cassettes from CI, to keep them up-to-date with the code, but we don't want the extra weight in the repo. Closing this issue means adjusting the CI workflow.

**Comment by BaseInfinity** [comment]
Cool I think I have plenty of information to at least get a Draft Pull of this going, thanks for the swift replies

**Comment by Pwuts** [comment]
Fixed by #4420 (which is based on #4294), thanks @BaseInfinity and @merwanehamadi!
