### ISSUE TITLE
File based objectives & finding the workspace

### ISSUE THREAD

**Issue by Boostrix** [Significant-Gravitas/Auto-GPT#4288]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

This is one of the most frequently asked questions on the forum, issue tracker and on Discord respectively.
This is literally being asked every day on github and discord:

We need to better document that it's sufficient to put a plain text file into the workspace and augment the goals to find/read that file.

For starters, the first step would be adapting the input prompt to explicitly say that such files can be put into the workspace.
Afterwards, we may want to provide an option to specify a file explicitly (possibly by opening a file picker or something like that)

It's also worth keeping in mind that people using containers without realizing how these work, will have a hard time locating the workspace - so we might want to consider exposing that in a cross-platform fashion (FTP, WebDAV or any other ideas ?)

For the time being, I would like the Windows and Mac OSX folks to comment, what would works best for them - since Linux/Unix folks usually know their stuff, so won't need much hand holding presumably ?

### Examples 🌈

- https://discord.com/channels/1092243196446249134/1092243196798582930/1108776832288968836

### Discord talks 🔦

https://discord.com/channels/1092243196446249134/1098217450425827468/1108811185970761778

https://discord.com/channels/1092243196446249134/1092275629602394184/1109204300225319042

**Comment by ashishnagar19** [comment]
could you explain what we can can do to improve this?
