### ISSUE TITLE
File is outside of working directory

### ISSUE THREAD

**Issue by Starchini47** [Significant-Gravitas/Auto-GPT#429]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

In my goals I am providing AutoGPT with a file path to a CSV file which i want it to analyze. 

### Current behavior 😯

When trying to access the file it returns the output of: 

The previous command failed because the file is located outside my working directory

### Expected behavior 🤔

It reads the CSV file and continues with the tasks that are set. 

### Your prompt 📝

```yaml
I want you to analyze the following CSV file "/Users/user1/Downloads/ai/Auto-GPT/auto_gpt_workspace/data.csv"
```

**Comment by TapusAggarwal** [comment]
In scripts\file_operations.py set working_directory var to your current working directory.

**Comment by jjonj** [comment]
I finally got it to work by simply telling it:
Detect .mkv files in the audio folder
(I made an audio folder in scripts\auto_gpt_workspace)

**Comment by Explorergt92** [comment]
@Starchini47 is this still an issue for you or can this be closed?
