### ISSUE TITLE
How to enable auto-GPT to pick up where it left off after connection failure?

### ISSUE THREAD

**Issue by cklose2000** [Significant-Gravitas/Auto-GPT#430]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Any thoughts on enabling auto-GPT to pick up where it left off after an error? It has done some noble work, but has never fully completed the tasks I've set for it before getting cut off by this kind of error:
  raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

**Comment by SirGunthix** [comment]
good Q i dont know yet but am curious. Bumping this thread in hope someone answers

**Comment by Electronik-FArts** [comment]
i am looking for the same issue. i constantly and i mean constantly get "Error communicating with OpenAI", here is a traceback for more details. this is annoying. 

Traceback (most recent call last):
  File "C:\Users\iliai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\iliai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\iliai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\iliai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\iliai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\iliai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\iliai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\iliai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\iliai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\iliai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\iliai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_requestor.py", line 516, in request_raw
    result = _thread_context.session.request(
  File "C:\Users\iliai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\iliai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\iliai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\AutoGPT\Auto-GPT\scripts\main.py", line 373, in <module>
    memory.add(memory_to_add)
  File "C:\AutoGPT\Auto-GPT\scripts\memory.py", line 35, in add
    vector = get_ada_embedding(data)
  File "C:\AutoGPT\Auto-GPT\scripts\memory.py", line 10, in get_ada_embedding
    return openai.Embedding.create(input=[text], model="text-embedding-ada-002")["data"][0]["embedding"]
  File "C:\Users\iliai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_resources\embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
  File "C:\Users\iliai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\iliai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_requestor.py", line 216, in request
    result = self.request_raw(
  File "C:\Users\iliai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_requestor.py", line 528, in request_raw
    raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by dysai1234** [comment]
this is really good feature that we can work on .

**Comment by marktellez** [comment]
it would need a database for starters. i noticed they tried to put in pinecone, but then pinecone block it.

local cache seems to vanish after a restart. the last command is saved, but the system isnt aware of the files it already saved.

i would propose a local database instead of something like pinecone to make it less brittle. sqlite runs on any platform. it could be a possibility.

**Comment by dysai1234** [comment]
Finally without pinecode I am stuck with pinecone error if you are working with sqllite I am happy to contribute

**Comment by BaltekLabs** [comment]
I have found a solution to this. You must save the whole interaction in a .txt in the /auto_gpt_workspace. It took some coaxing but I found the command to give it after a restart

Input: I have saved a log of our previous interactions at ./[your_file_name] , read the file and restore yourself to the stop point of the file. You will need to chunk the file in chunks of 6000 tokens.
SYSTEM:  Human feedback: I have saved a log of our previous interactions at ./gameDevRetore.txt , read the file and restore yourself to the stop point of the file. You will need to chunk the file in chunks of 6000 tokens.

If it reads the file without the chunking, it goes over the token limit. 
<img width="824" alt="restoreTraining" src="https://user-images.githubusercontent.com/16975634/231747276-1ff1eee2-b4b5-4bae-be1b-ea6007557e82.PNG">
<img width="825" alt="training3" src="https://user-images.githubusercontent.com/16975634/231747343-f9ded0e7-d3ff-4b99-ace0-85c2306aefc3.PNG">
<img width="818" alt="training4" src="https://user-images.githubusercontent.com/16975634/231747344-6a68f232-b7d8-4420-bece-00a7a4b972b8.PNG">
<img width="826" alt="training2" src="https://user-images.githubusercontent.com/16975634/231747346-8b5bda40-9e89-46e6-ace6-b7443447a8c1.PNG">

**Comment by joeflack4** [comment]
Restarting where it left of feels critical. I'm new to the codebase but if I have time and this isn't fixed this is the first thing I would try to contribute.
@marktellez Where is the local cache JSON stored? I'm only seeing outputs/data related to my agent stored in logs/activity.log.
@cklose2000 I would suggest changing the title to simply "How to enable Auto-GPT to pick up where it left off? ". I think by default we want agents to work this way; that you can end a session for whatever reason and then return where it left off.

**Comment by ram-sh** [comment]
> I think by default we want agents to work this way; that you can end a session for whatever reason and then return where it left off.

i couldn't agree more!! i'm trying to solve a complex problem using Auto-GPT and whenever it crash the task starts from the beginning for no good reason.

following @BaltekLabs [solution ](https://github.com/Significant-Gravitas/Auto-GPT/issues/430#issuecomment-1506816266) i wanted to add some code to Auto-GPT to do it, first question is if the `auto-gpt.json` has all the conversation in it or we need to dump the terminal text on each update to a txt file?

**Comment by ram-sh** [comment]
> following @BaltekLabs [solution ](https://github.com/Significant-Gravitas/Auto-GPT/issues/430#issuecomment-1506816266) i wanted to add some code to Auto-GPT to do it, first question is if the `auto-gpt.json` has all the conversation in it or we need to dump the terminal text on each update to a txt file?


can someone pls confirm the function below in `logs.py` is the best place to add an append command to an external text file for each terminal printout?

```
 def typewriter_log(
        self, title="", title_color="", content="", speak_text=False, level=logging.INFO
    ):
        if speak_text and CFG.speak_mode:
            say_text(f"{title}. {content}")

        if content:
            if isinstance(content, list):
                content = " ".join(content)
        else:
            content = ""

        self.typing_logger.log(
            level, content, extra={"title": title, "color": title_color}
        )

**Comment by itsDesTV** [comment]
> > I think by default we want agents to work this way; that you can end a session for whatever reason and then return where it left off.
> 
> i couldn't agree more!! i'm trying to solve a complex problem using Auto-GPT and whenever it crash the task starts from the beginning for no good reason.
> 
> following @BaltekLabs [solution ](https://github.com/Significant-Gravitas/Auto-GPT/issues/430#issuecomment-1506816266) i wanted to add some code to Auto-GPT to do it, first question is if the `auto-gpt.json` has all the conversation in it or we need to dump the terminal text on each update to a txt file?

All you have to do is go to the logs file and preseed the activity file. That will give you a different beginning every time, because if you just restart, then it does the same thing all over. But this will go at the task at a different angle in the beginning. Though giving it the activity log to read in the beginning will 100% get you back to where you want to go. But imo pre seeding will give the AI a better outlook of what to do next. I think that’s better because it’s AI. It’s sometimes dumb but won’t do something it knows isn’t worth it if it already has knowledge of failures it’s done in the past.

**Comment by joeflack4** [comment]
I agree with @itsDesTV. In theory at least I don't think it sounds complicated. I haven't come across an `auto-gpt.json` yet, but I think what itsDesTV (and I) are suggesting is that when you start a new session, before making the first call to the LLM (e.g. ChatGPT), we insert the entire prior `activity.log` history for that agent into the prompt.

**Comment by itsDesTV** [comment]
> I agree with @itsDesTV. In theory at least I don't think it sounds complicated. I haven't come across an `auto-gpt.json` yet, but I think what itsDesTV (and I) are suggesting is that when you start a new session, before making the first call to the LLM (e.g. ChatGPT), we insert the entire prior `activity.log` history for that agent into the prompt.

Yeah the one thing I have tried is setting a goal to “read the “activity.txt” (by directing it with the file path) and continue progress from there” and then goal number two would be “read 1.txt” that would have 2 or 3 tasks in it to do, then at the end it would say, once done with prior tasks, “read 2.txt”. I didn’t that a different time but not like this and it works. But you essentially could set a bunch of if/then command in your goals in those files. 

For how smart AI is, it honestly pisses me off sometimes lol. I make such good progress and then I try to replicate it and it just never works out. And to do what I truly want to do, it would cost so much :/ bc for Ai to truly be Ai, it needs to fail and learn and fail and learn just like us. That’s why we keep going at it and tweaking all our prompts. But the money it’s spending on us is our time!

**Comment by joeflack4** [comment]
@itsDesTV Splitting up the agent into multiple tasks sounds a lot like one of the major goals of [this issue](https://github.com/Significant-Gravitas/Auto-GPT/issues/3039#issue-1680089557), and I think some others as well. The thought is a hierarchy of agents, each with its own `ai_settings.yaml`.

I feel like at some point in the future, some implementation of an LLM will support the ability to get/set a "seed" for a session for replicability. Maybe they will be less powerful, less frequently versioned LLMs; who can say.

**Comment by itsDesTV** [comment]
@joeflack4 so you technically can now if you wanna look into this! I just haven’t dove into it because I simply want to see what I can make one agent do! I’ve already come to terms that only right now, 1 agent is for the most part is useful until it fails. But there HAS to be a way to make it understand. With that being said, multiple separate instances that work together is wild. And I’d they can make it communicate, that would be EVEN better. 

But here is the thread: https://github.com/Significant-Gravitas/Auto-GPT/discussions/3392#discussion-5136254

**Comment by Boostrix** [comment]
> With that being said, multiple separate instances that work together is wild. And if they can make it communicate, that would be EVEN better.

only in theory, the complexity is huge - you need to get the sequential approach working first, i.e. where the parent agent literally sleeps/waits for the sub-agent to finish its task, at most monitoring/observing its progress (think a stream/pipe or just a log file - comparing log messages to stated goals/objectives), with the option to "guide" a sub-agent (modify its goals/observe) or to terminate/restart an agent.
The other thing being, progress can be more than a  bunch of messages, it may be stuff on disk for instance (folders/files) - so you also need a way to "checkpoint" state of an agent. So that a sub-agent that is restarted may optionally reuse data from a previous invocation/instance.

I don't see any way to make this working and robust without first getting the sequential use-case right. Once you are talking about multiple agents, possibly working in async fashion, the complexity is getting huge - because at that point, you are literally in need of "manager agents" to carefully watch its agent/team of agents, or they will just clobber up your API bills ...

**Comment by AdinSoftic** [comment]
For me it looks like the whole AutoGPT architecture could need management agent that manages the other agents and the whole progress. 
That agent could take up where the progress was and feed the memory. It could be used to read the previous sessions.  

For the situations where the model gets stuck into "task loop" (because Task prioritization agent doesn't look at the memory and that Execution agent cannot influence the task queue), management agent could overlook the Task creation agent and step up if the task doesn't lead to our goal or if recognizes that he is repeating/getting into a lool.

@Boostrix we came to a similar conclusion. For reducing the bill, that agent could get the summaries instead of all the tiny details. But than again other model needs to make a summary (hard to get those bills down)

**Comment by Boostrix** [comment]
> But than again other model needs to make a summary (hard to get those bills down)

right, that is why it would be preferable to "checkpoint" state locally inside that agent's workspace, i.e. using shell scripts or at least /some/ meta info on disk that isn't going through the LLM to help with #3466

**Comment by eyalk11** [comment]
I missed this post, but I think as a first step, what I suggested https://github.com/Significant-Gravitas/Auto-GPT/issues/430 should be implemented. Pickle is the solution, and if there are multiple agents, then it complicates things, but not that much.

**Comment by Boostrix** [comment]
I think we need a draft PR to summarize the main ideas, collated from different issues/talks

**Comment by EggheadJr** [comment]
[EggheadJr](https://github.com/EggheadJr)
/
[How-to-enable-auto-GPT-to-pick-up-where-it-left-off-after-connection-failure-430](https://github.com/EggheadJr/How-to-enable-auto-GPT-to-pick-up-where-it-left-off-after-connection-failure-430)

**Comment by joeflack4** [comment]
@EggheadJr Thanks for that, Egghead. This looks kinda like a gist, but in markdown form.
I think implementation may be a little trickier than that when you actually start coding it, but I could be wrong? I stopped working on this because there was some related development going on very quickly, with a lot of different people, and architecture changing. I think they will address this while they address those other things, but I'm not sure.
