### ISSUE TITLE
ModuleNotFoundError: No module named 'pandas'

### ISSUE THREAD

**Issue by ikg91** [Significant-Gravitas/Auto-GPT#4323]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

Windows Subsystem for Linux Distributions:
Ubuntu (Default)
docker-desktop
Ubuntu-22.04
docker-desktop-data

Docker Compose version v2.17.3

Client:
 Cloud integration: v1.0.31
 Version:           23.0.5
 API version:       1.42
 Go version:        go1.19.8
 Git commit:        bc4487a
 Built:             Wed Apr 26 16:20:14 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.19.0 (106363)
 Engine:
  Version:          23.0.5
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.8
  Git commit:       94d3ad6
  Built:            Wed Apr 26 16:17:45 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.20
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.5
  GitCommit:        v1.1.5-0-gf19387a
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

docker pull significantgravitas/auto-gpt
docker-compose run --rm auto-gpt --gpt3only --continuous

I'm running Auto-GPT on docker. running auto GPT on continuous mode 
 after browsing for some time. it wrote a script that uses pandas, despite pandas being installed correctly, I kept getting the error shown before "ModuleNotFoundError: No module named 'pandas'"
I can run the script manually without any issues. 

the same error happens with other **Python packages as well.** 
 I've seen this issue before reported and I followed the steps but did not help. 
I've reviewed and these issues #3088 #3704 priorly and attempt to follow all the suggested fixes, but it did not fix it for me.
I tried running it on both master, stable 0.3 and 0.3.1 as well 

### Current behavior 😯

stuck in an infinite loop trying to install pandas. 

### Expected behavior 🤔

to be able to use python packages that are installed that are correctly installed

### Your prompt 📝

```yaml
# Paste your prompt here
```
find the names of 15 biotech or pharmaceutical companies, find all their drugs that are currently being developed but have not yet been approved by the FDA, access their clinical trials from their websites, and analyse their clinical trials to predict the probability of ones are more likely to be approved by the FDA, rank each drug and the reason behind the ranking, produce the final results in a single file

### Your Logs 📒

```log
<insert your logs here>
```
NEXT ACTION:  COMMAND = execute_python_file ARGUMENTS = {'filename': '/app/autogpt/auto_gpt_workspace/analysis.py'}
AUTHORISED COMMANDS LEFT: 0
  Executing file '/app/autogpt/auto_gpt_workspace/analysis.py'
SYSTEM:  Command execute_python_file returned: Error: Traceback (most recent call last): File "/app/autogpt/auto_gpt_workspace/analysis.py", line 1, in <module> import pandas as pd ModuleNotFoundError: No module named 'pandas'
 THOUGHTS:  I suggest using the 'append_to_file' command to install the pandas library required to execute the Python file that analyzes the current state of the market and identifies key drivers.
REASONING:  Installing the pandas library will allow us to execute the Python file that analyzes the current state of the market and identifies key drivers.
PLAN:
-  Use the 'append_to_file' command to install the pandas library required to execute the Python file that analyzes the current state of the market and identifies key drivers.
CRITICISM:  I need to ensure that the pandas library is installed correctly and that the Python file executes without errors.
NEXT ACTION:  COMMAND = append_to_file ARGUMENTS = {'filename': '/app/autogpt/auto_gpt_workspace/analysis.py', 'text': '\n!pip install pandas'}
AUTHORISED COMMANDS LEFT: 0

**Comment by ntindle** [comment]
All python execution commands happen within a docker container. Run within a container and install pandas by hand

**Comment by onemotime23** [comment]
I'am going in circles with this i have deleted everything in docker then use vs code to rebuild went in and added script in docker file # Install pandas 
RUN pip install --no-cache-dir pandas  then went and did a edit on the requirements.txt and added just the word (pandas) restarted using dev containers with docker launched i can see a rebuild in docker but still the joker cant find pandas ... So when you say do by hand can you please give some instructions !  Because pip install in any form is not working !
