### ISSUE TITLE
JSON related errors

### ISSUE THREAD

**Issue by theogtaco** [Significant-Gravitas/Auto-GPT#4332]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

im completely new to coding, and just heard of this cool concept and wanted to see what it was capable of. I asked autogpt to code me a game, with multiple classes, and each object is to be in its own .java file, where i can connect them together once im done and run it to see  if it works. I supplied the exact prompt i gave it below. if im screwing up  If theres more info i need to give to be able to show you what could be going wrong, please tell me. I've tried looking at every other problem related to mine, but I can't find the solution. Maybe is it because im using GPT-3 and not 4?

### Current behavior 😯

![image](https://github.com/Significant-Gravitas/Auto-GPT/assets/62676430/3a7608a9-5881-4698-bdb8-b626b1f80873)

it essentially just does this in an infinite loop.

### Expected behavior 🤔

effectively creates multiple .java files that i can simply copy onto an IDE and run the game.

### Your prompt 📝

```yaml
# Paste your prompt here
```
Create a Java program that replicates the game of Pong. The game should have dimensions of 1000 x 750 pixels. The score should be displayed at the top of the game window. Each object of the game, including the Pong game itself, should have its own Java file. All game objects should be subclasses of a general class called GameObject.The user should have a special ability to boost their speed three times faster than normal. This ability will be powered by a bar that indicates its duration. The power-up should last for a reasonable amount of time. Once depleted, it should take approximately 15 seconds to regenerate before the user can use the ability again. The user should be able to move up using the "W" key or the Up arrow, move down using the "S" key or the Down arrow, and activate the ability using the SPACE bar.There are two types of enemies: DumbEnemy and SmartEnemy. The DumbEnemy should operate similarly to a typical NPC in Pong, without complex trajectory calculations or prediction. The speed of the DumbEnemy should be customizable, increasing as the levels progress. The SmartEnemy should move faster, have slightly smarter trajectory tracking ability, and possess its own ability. The SmartEnemy's ability should have a cooldown of 20 seconds, and a power bar should indicate when the ability can be used again.The game should have 5 levels. To progress to the next level, the user must score 5 points before the enemy does. For the first four levels, use a DumbEnemy. Increase the DumbEnemy's speed by 10% with each level. On level 5, introduce the SmartEnemy with the described abilities. Display the level number in a corner of the screen.If the user loses on any level, the game should pause and offer an option to restart. If the user beats all 5 levels, the game should continue, increasing the difficulty until it becomes unplayable.Please include comments in the code indicating specific lines where the speed of the enemy and user can be customized according to preferences. 

### Your Logs 📒

```log
<insert your logs here>
```
  {
        "role": "system",
        "content": "The current time and date is Sat May 20 23:12:16 2023"
    },
    {
        "role": "system",
        "content": "This reminds you of these events from your past: \nI sent the command \"write_to_file\" with the arguments \"filename\" and \"text\" to create a file called \"plan.txt\" containing the game development plan. The plan includes creating classes for GameObject, Pong game, User, DumbEnemy, and SmartEnemy, implementing movement, collision detection, power-up and enemy abilities, score tracking, level progression, game over and restart functionality, testing and debugging, and creating a timeline for each task. Command write_to_file returned: File written to successfully. Now that we have a plan, let's start by creating the GameObject class. This class will serve as the parent class for all other game objects. Command write_to_file returned: File written to successfully. Now that we have the GameObject class, let's move on to creating the Pong game class. This class will handle the game logic and display."
    },
    {
        "role": "system",
        "content": "Command Error: threw the following error: Missing 'command' object in JSON"
    },
    {
        "role": "user",
        "content": "Determine which next command to use, and respond using the format specified above:"
    },
    {
        "role": "assistant",
        "content": "Based on our plan, the next step is to create the Pong game class. We can start by analyzing the code for the GameObject class to ensure we have a good understanding of how it works. \n\nCommand: analyze_code\nArguments: \"code\": \"<GameObject class code>\""
    },
    {
        "role": "system",
        "content": "Command Error: threw the following error: Missing 'command' object in JSON"
    },
    {
        "role": "user",
        "content": "Determine which next command to use, and respond using the format specified above:"
    },
    {
        "role": "assistant",
        "content": "Let's start by analyzing the code for the GameObject class to ensure we have a good understanding of how it works. \n\nCommand: analyze_code\nArguments: \"code\": \"<GameObject class code>\""
    },
    {
        "role": "system",
        "content": "Self feedback: As an AI Agent, your thought process, reasoning, and plan for creating a Java program that replicates the game of Pong are well-structured and detailed. You have provided clear instructions on the game's dimensions, score display, object classes, user controls, enemy types, power-ups, levels, and game over options. Your idea of customizing the speed of the enemy and user is also a good addition to the game's flexibility. However, you could improve your plan by adding more details on the game's graphics, sound effects, and user interface. You could also consider simplifying some of the game's features to make it more accessible to beginners or adding more challenges to make it more engaging for advanced players. Overall, your plan is well-thought-out and comprehensive, and with some minor improvements, it could lead to a successful implementation of the game of Pong in Java."
    },
    {
        "role": "system",
        "content": "Your remaining API budget is $7.946\n\n"
    },
    {
        "role": "user",
        "content": "Determine which next command to use, and respond using the format specified above:"
    }
]
2023-05-20 23:12:42,193 ERROR Error: The following AI output couldn't be converted to a JSON:
 Let's start by analyzing the code for the GameObject class to ensure we have a good understanding of how it works. 

Command: analyze_code
Arguments: "code": "<GameObject class code>"
2023-05-20 23:12:42,208 DEBUG  {}
2023-05-20 23:12:42,208 INFO NEXT ACTION:  COMMAND = self_feedback  ARGUMENTS = Missing 'command' object in JSON
2023-05-20 23:12:42,583 INFO  Enter 'y' to authorise command, 'y -N' to run N continuous commands, 's' to run self-feedback commands, 'n' to exit program, or enter feedback for ...
2023-05-20 23:12:42,583 INFO  Asking user via keyboard...

**Comment by Qoyyuum** [comment]
Closing issue as duplicate of #21
