### ISSUE TITLE
Run without Docker

### ISSUE THREAD

**Issue by gameuser1982** [Significant-Gravitas/Auto-GPT#4334]
`Due to security reasons, certain features (like Python execution) will by default be disabled when running without docker. So, even if you want to run the program outside a docker container, you currently still need docker to actually run scripts.`

I don't get it. How does a python script prevent itself from running outside of docker? 

Edit: Ah I see that it can't actually.

**Comment by Qoyyuum** [comment]
Since its not an issue, I'll close this.
