### ISSUE TITLE
autogpt.net - legit or clickbait?

### ISSUE THREAD

**Issue by robertlude** [Significant-Gravitas/Auto-GPT#4337]
Is the URL [autogpt.net](autogpt.net) affiliated with this project at all? They claim to be the "official" site but the discord link is different and there are no direct links to this project. i only ask because it feels fishy as heck and is the first google result when searching "autogpt"

**Comment by GoZippy** [comment]
You kinda answered your own question...

**Comment by robertlude** [comment]
I guess I'm more trying to raise awareness of this URL. I phrased it as a question on the off chance this was something I was misinterpreting before throwing any accusations out into the wild.

**Comment by rihp** [comment]
The official page of AutoGPT is https://agpt.co

**Comment by Torantulino** [comment]
Yep this page is unaffiliated with the project and is profiteering off of everyone's hard work selling dodgy things unfortunately.
