### ISSUE TITLE
Google search fails, no API key provided

### ISSUE THREAD

**Issue by AdamBullen** [Significant-Gravitas/Auto-GPT#4372]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of Auto-GPT are you using?

Master (branch)

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Agents

### Describe your issue.

I get:

    Command google returned: Error: <HttpError 400 when requesting https://customsearch.googleapis.com/customsearch/v1?q=trending+industries+and+products&cx=your-custom-search-engine-id&num=8&key=your-google-api-key&alt=json returned "API key not valid. Please pass a valid API key.". Details: "[{'message': 'API key not valid. Please pass a valid API key.', 'domain': 'global', 'reason': 'badRequest'}]">

For every search request; I don't have a google API key and.

### Upload Error Log Content

The error log is empty....

**Comment by Qoyyuum** [comment]
Hi @AdamBullen you didn't set up your Google API Key in your `.env` file. Please set one up and try again. If you find a problem, please raise a separate issue. Thanks!

**Comment by AdamBullen** [comment]
Why do I need an API key now? I didn't need one a little while back

**Comment by Qoyyuum** [comment]
@AdamBullen not sure when you've last tried but it has always been that when you need to browse with Google search, it needs the Google Search Engine ID and API Key. And the log you've provided shows that you need to provide a valid API key.

Here's instructions on how to: https://docs.agpt.co/configuration/search/#google-api-keys-configuration
