### ISSUE TITLE
UserWarning: parameter max_results is deprecated, use DDGS().text()   warnings.warn("parameter max_results is deprecated, use DDGS().text()")

### ISSUE THREAD

**Issue by jelleheijne1997** [Significant-Gravitas/Auto-GPT#4376]
When AutoGPT is trying to google something it gives the following error and returns an empty list: UserWarning: parameter max_results is deprecated, use DDGS().text()
  warnings.warn("parameter max_results is deprecated, use DDGS().text()")

**Comment by kinance** [comment]
The underlying duckduckgo_search package is deprecating the max_result, but it doesn't affect the function yet. There is a issue/question raised in their repo regarding this. Will need to wait for their suggestion. [DDGS how to set max_result like ddg()](https://github.com/deedy5/duckduckgo_search/issues/74)
