### ISSUE TITLE
AutoGPT overwrites same text file with each action instead of appending to the end.

### ISSUE THREAD

**Issue by johnjac-cisco** [Significant-Gravitas/Auto-GPT#4384]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Docker

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Challenges

### Describe your issue.

The task was to give a detailed explanation of something, and auto-gpt broke the task in to several "writing sections" but instead of appending each section to the text file, it over wrote each time
[activity.log](https://github.com/Significant-Gravitas/Auto-GPT/files/11556474/activity.log)

**Comment by Boostrix** [comment]
you can also tell it explicitly not to overwrite existing files - also see the update_file PR: #3643

**Comment by bishi3000** [comment]
There are quite a few ways to solve this issue. IMO the current implementation is quite prone to loosing the context of what it  is currently doing (or was just doing). 

If using simple files is the desired storage mechanism (as opposed to a document DB for example) then, maybe a scheme such as writing into a folder names by a session ID, or creating filenames with a session ID suffix, where the 'session ID' relates to the current task.

This would also help for cleanup of files afterwards

**Comment by W3Warp** [comment]
> There are quite a few ways to solve this issue. IMO the current implementation is quite prone to loosing the context of what it is currently doing (or was just doing).
> 
> If using simple files is the desired storage mechanism (as opposed to a document DB for example) then, maybe a scheme such as writing into a folder names by a session ID, or creating filenames with a session ID suffix, where the 'session ID' relates to the current task.
> 
> This would also help for cleanup of files afterwards

https://github.com/Significant-Gravitas/Auto-GPT/issues/3536#issue-1689587943

**Comment by Boostrix** [comment]
There is also the update_file PR which contains related discussions
