### ISSUE TITLE
I need to run commands outside docker

### ISSUE THREAD

**Issue by Kuchiriel** [Significant-Gravitas/Auto-GPT#4396]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Dears,

I need to run commands outside docker, I am using WSL2 and PowerShell, I was trying to tinker with the code, but I can´t find a way to change the behavior of forcing commands inside a docker container.

Thanks in advance

**Comment by Boostrix** [comment]
if you use ssh (or even telnet), the agent has now way of knowing where it is executing stuff

**Comment by ianbmacdonald** [comment]
It might be a good idea to describe the commands you are trying to run;  After all, it is a docker image, that you can build yourself, from any base image.  The default alpine based one is pretty skinny, for good reason to handle python only, but you can just create your own with the same tag and AGPT will use it.
