### ISSUE TITLE
Wrong implementation in json_fix_general.balance_braces

### ISSUE THREAD

**Issue by r1p71d3** [Significant-Gravitas/Auto-GPT#4408]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Other

### Describe your issue.

While working on my own project, I borrowed some of the JSON validation code and noticed that `json_fix_general.balance_braces` function has an issue. The second while loop meant to remove extra closed curly braces is implemented as such:

```python
    while close_braces_count > open_braces_count:
        json_string = json_string.rstrip("}")
        close_braces_count -= 1
```

This is not the right implementation because `.rstrip(sequence)` removes **all** the instances of the specified sequence that consequently appear at the end of the given string. Therefore, a JSON string like `'{"data": {"data": "content"}}}'` will become `'{"data": {"data": "content"'` instead of `'{"data": {"data": "content}}"'` after the very first iteration.

A quick fix for this would be to remove the second while loop and instead simply first remove all the '}' at the end of the string and then run the first while loop to balance them like this:

```python
def balance_braces(json_string: str) -> Optional[str]:
    """
    Balance the braces in a JSON string.

    Args:
        json_string (str): The JSON string.

    Returns:
        str: The JSON string with braces balanced.
    """

    json_string = json_string.rstrip("}")

    open_braces_count = json_string.count("{")
    close_braces_count = json_string.count("}")

    while open_braces_count > close_braces_count:
        json_string += "}"
        close_braces_count += 1

    with contextlib.suppress(json.JSONDecodeError):
        json.loads(json_string)
        return json_string
```

I believe this could be causing some issues with invalid JSONs. Since pull requests take a long time to be looked at, I'm not going to open one, but I hope someone can fix this directly in the next version.

**Comment by ntindle** [comment]
We are working on bug fix PRs and have a team that has been helping chip away at the old pr list. Would you mind sending this in? Cc: @k-boikov @Boostrix

**Comment by Boostrix** [comment]
We have patches related to fixing up Json processing circulating on discord, need to check if it's the same heuristic /fix

**Comment by r1p71d3** [comment]
Can't even commit this change because the mypy check fails:

```bash
autogpt/json_utils/json_fix_general.py:42: error: Missing return statement  [return]
Found 1 error in 1 file (checked 1 source file)
```

I guess it's because the `return` statement is inside the `with` statement, though this is how the method was implemented before too. The check was probably added after the json utils files were already pushed. So please fix these inconsistencies as well.
