### ISSUE TITLE
Refinement with sentiment analysis for autoGPT

### ISSUE THREAD

**Issue by howagain** [Significant-Gravitas/Auto-GPT#442]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Looking at Microsoft’s Jarvis and the improvement seen with refinement (where GPT is prompted after it’s response “did you do the last task correctly?”). Perhaps we could implement a refinement check before proceeding on a task, and use some sort of sentiment analysis from hugging face to then turn that into a Boolean of continue or refine. Then if it still fails after 3 or so retries it could ask a question back to the user for help where it got stuck. 

### Examples 🌈

Jarvis integration with hugging face https://github.com/microsoft/JARVIS

Paper on refinement technique: https://arxiv.org/pdf/2303.11366.pdf?utm_source=aibreakfast.beehiiv.com&utm_medium=referral&utm_campaign=why-every-company-will-use-chatgpt-s-retrieval

### Motivation 🔦

The goal would be to trade speed for accuracy in an automated fashion for difficult problems. Some tasks might require higher accuracy and this could be a way to improve the results without waiting for a more sophisticated model.

**Comment by nponeccop** [comment]
Speed **and cost** for accuracy. But I think before such extra features we should modularize the existing approach. E.g., the commands are entirely ad hoc as opposed to a dictionary of commands.
