### ISSUE TITLE
data_ingestion.py gives download_file is disabled error

### ISSUE THREAD

**Issue by cranyy** [Significant-Gravitas/Auto-GPT#4435]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Memory

### Describe your issue.

When trying to pre-seed using the example command provided in memory.md namely: python data_ingestion.py --dir DataFolder --init --overlap 100 --max_length 2000
Gives this error:

C:\Users\me\Auto-GPT>python data_ingestion.py --dir DataFolder --init --overlap 100 --max_length 2000 
 ←[0m Command 'download_file' is disabled: Error: You do not have user authorization to download files locally.
usage: data_ingestion.py [-h] (--file FILE | --dir DIR) [--init] [--overlap OVERLAP] [--max_length MAX_LENGTH]

I have changed the env to allow local file commands and still i get this error. What am I doing wrong?

**Comment by willmoura** [comment]
I'm getting the same error

**Comment by lampeight** [comment]
Also having this problem. Not able to ingest any data until this is fixed. Any update at all please?

**Comment by coolrazor007** [comment]
I can't use it either.  I even ran it from inside the Docker image.  I get this block of text:

`root@d8be9935886c:/app# python data_ingestion.py --dir ./autogpt/auto_gpt_workspace/ingest/ --init
  Command 'download_file' is disabled: Error: You do not have user authorization to download files locally.
Traceback (most recent call last):
  File "/app/data_ingestion.py", line 96, in <module>
    main()
  File "/app/data_ingestion.py", line 73, in main
    memory = get_memory(cfg, init=args.init)
  File "/app/autogpt/memory/vector/__init__.py", line 47, in get_memory
    memory = JSONFileMemory(cfg)
  File "/app/autogpt/singleton.py", line 15, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/app/autogpt/memory/vector/providers/json_file.py", line 32, in __init__
    workspace_path = Path(cfg.workspace_path)
  File "/usr/local/lib/python3.10/pathlib.py", line 960, in __new__
    self = cls._from_parts(args)
  File "/usr/local/lib/python3.10/pathlib.py", line 594, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/local/lib/python3.10/pathlib.py", line 578, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType`

**Comment by divineslight** [comment]
Same error, how to allow it?

**Comment by jimallen** [comment]
Same issue
