### ISSUE TITLE
Plain output should influence Logger

### ISSUE THREAD

**Issue by k-boikov** [Significant-Gravitas/Auto-GPT#4437]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

`plain_output` from Config is used to stop Spinner from spinning. See https://github.com/Significant-Gravitas/Auto-GPT/pull/4329 . It should also influence the typewriter log to not print in a typewriter style in order to save time. Currently Config is not used in Logger.

### Motivation 🔦

> Open an issue to apply this to typewriter text too

For the typing delay?

_Originally posted by @k-boikov in https://github.com/Significant-Gravitas/Auto-GPT/issues/4329#issuecomment-1564945787_

**Comment by merwanehamadi** [comment]
https://github.com/Significant-Gravitas/Auto-GPT/pull/4486
