### ISSUE TITLE
AutGPT-generated python scripts cannot open files in same folder

### ISSUE THREAD

**Issue by everspring-github** [Significant-Gravitas/Auto-GPT#4439]
I am running Auto-GPT locally with Docker. Commands like `read_file` can successfully read CSV files in `/autogpt/auto_gpt_workspace`, but python files written by autogpt in the same folder can never find the same CSV's and give the error:

```
Command execute_python_file returned: Error: Traceback (most recent call last): File "/app/autogpt/auto_gpt_workspace/generate_reports.py", line 27, in <module> main() File "/app/autogpt/auto_gpt_workspace/generate_reports.py", line 22, in main data = parse_data(file_path) File "/app/autogpt/auto_gpt_workspace/generate_reports.py", line 5, in parse_data with open(file_path, 'r') as file: FileNotFoundError: [Errno 2] No such file or directory: './my-csv.csv'
```

where in `generate_reports.py` it looks like:

```
file_path = "./my-csv.csv"
```

Running `list_files` command always sees the csv file. My `docker-compose.yml` looks like:

```
...

volumes:
      - ./auto_gpt_workspace:/app/autogpt/auto_gpt_workspace
      - ./data:/app/data

...
```

Any idea why the python files can't find the CSV files?

**Comment by Monty1122** [comment]
ive had a very similar problem - scripts created by autogpt cant be found

**Comment by NicksKnack** [comment]
One possible reason why the Python files can't find the CSV files is because the working directory of the Python interpreter might not match the directory where the CSV files are.

**Comment by everspring-github** [comment]
@NicksKnack I suspect you are correct. I tried changing the `WORKDIR` in my my `Dockerfile` from

```
# Set the entrypoint
ENTRYPOINT ["python", "-m", "autogpt", "--install-plugin-deps"]

# dev build -> include everything
FROM autogpt-base as autogpt-dev
RUN pip install --no-cache-dir -r requirements.txt
WORKDIR /app
ONBUILD COPY . ./

# release build -> include bare minimum
FROM autogpt-base as autogpt-release
RUN sed -i '/Items below this point will not be included in the Docker Image/,$d' requirements.txt && \
	pip install --no-cache-dir -r requirements.txt
WORKDIR /app
ONBUILD COPY autogpt/ ./autogpt
ONBUILD COPY scripts/ ./scripts
ONBUILD COPY plugins/ ./plugins

FROM autogpt-${BUILD_TYPE} AS auto-gpt
```

to

```
# Set the entrypoint
ENTRYPOINT ["python", "-m", "autogpt", "--install-plugin-deps"]

# dev build -> include everything
FROM autogpt-base as autogpt-dev
RUN pip install --no-cache-dir -r requirements.txt
WORKDIR /app/autogpt/auto_gpt_workspace
ONBUILD COPY . ./

# release build -> include bare minimum
FROM autogpt-base as autogpt-release
RUN sed -i '/Items below this point will not be included in the Docker Image/,$d' requirements.txt && \
	pip install --no-cache-dir -r requirements.txt
WORKDIR /app/autogpt/auto_gpt_workspace
ONBUILD COPY autogpt/ ./autogpt
ONBUILD COPY scripts/ ./scripts
ONBUILD COPY plugins/ ./plugins

FROM autogpt-${BUILD_TYPE} AS auto-gpt
```

But I get the same results. Has anyone else had this problem? It seems like it must be common

**Comment by ManzilS** [comment]
try 

``
import os

def main():
    current_directory = os.getcwd()
    print("Current working directory:", current_directory)

    files = os.listdir(current_directory)
    print("Files in current directory:", files)

    # Rest of your code
``

**Comment by erik-megarad** [comment]
I solved this by setting the `cwd` on shell commands to python. I'll make a PR at some point but I have other things I need to get to first.
