### ISSUE TITLE
Please double check that you have setup a PAID OpenAI API Account. (with Paid Account)

### ISSUE THREAD

**Issue by antoan** [Significant-Gravitas/Auto-GPT#4463]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of Auto-GPT are you using?
0.3.1
Stable (branch)

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

I have a paid account (GPT+) and still get this whenever I enter a query. I'm unable to use/get past this message - the app is unusable for me.  I have tried both GPT 4 and GPT3 models with the same result.

I have followed the config instructions and set my OpenAI key in the .env file.

I'm running autogpt with docker: sudo docker-compose run --rm auto-gpt
```

I want Auto-GPT to: Tell me the time in London UK
DOUBLE CHECK CONFIGURATION  Please double check that you have setup a PAID OpenAI API Account. You can read more here: https://docs.agpt.co/setup/#getting-an-api-key
```

**Comment by mengeroff** [comment]
same here

**Comment by MatrioxPlayZ** [comment]
you are supposed to pay for openai account, gpt+ does not count

**Comment by lc0rp** [comment]
The ChatGPT+ account is different from an Open AI API account. Go to https://platform.openai.com/signup, sign up, and enable billing.

**Comment by antoan** [comment]
my bad, much appreciated for clearing that up @lc0rp @MatrioxPlayZ
