### ISSUE TITLE
start_agent command no longer works

### ISSUE THREAD

**Issue by cranyy** [Significant-Gravitas/Auto-GPT#4465]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Master (branch)

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Agents

### Describe your issue.

SYSTEM:  Command start_agent returned: Error: Unknown chat model 'None'

Every time you ask the agent to create a sub_agent after the newest version it keeps giving me this None error. I tried defining it in the prompt but then it says "model gpt4/gpt-3.5-turbo is not defined". I tried hardcoding it in the app.py, and again same issue. 

So start_agent can no longer be used currently

**Comment by Klaudioz** [comment]
Getting the same:

```
NEXT ACTION:  COMMAND = start_agent ARGUMENTS = {'name': 'About Us Agent', 'task': 'Refine the language and suggest improvements for the About Us section', 'prompt': 'Please provide suggestions for improving the language and effectiveness of the About Us section.'}
  Enter 'y' to authorise command, 'y -N' to run N continuous commands, 's' to run self-feedback commands, 'n' to exit program, or enter feedback for TaskMaster...
  Asking user via keyboard...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
SYSTEM:  Command start_agent returned: Error: Unknown chat model 'None'
```

**Comment by MRiless** [comment]
Is there somewhere where i can set the default model so it doesnt give this? AutoGPT either forgets it, or its doesnt work at all for me either.

**Comment by lc0rp** [comment]
What are your .env settings for:
- SMART_LLM_MODEL
- FASE_LLM_MODEL
- EMBEDDING_MODEL

**Comment by cranyy** [comment]
The defaults:

# SMART_LLM_MODEL=gpt-4
# FAST_LLM_MODEL=gpt-3.5-turbo

### LLM MODEL SETTINGS

# FAST_TOKEN_LIMIT=4000
# SMART_TOKEN_LIMIT=8000

### EMBEDDINGS

# EMBEDDING_MODEL=text-embedding-ada-002
# EMBEDDING_TOKENIZER=cl100k_base
# EMBEDDING_TOKEN_LIMIT=8191

**Comment by ciavland** [comment]
Same Issue here...

**Comment by bjmolitor** [comment]
Same here...

**Comment by Naetmul** [comment]
Same here... I retried, but it then prompts:
`SYSTEM:  Command start_agent returned: Error: Unknown chat model 'text-davinci-002'`

**Comment by manavshark** [comment]
I'm having the same issue. It seams that there is no chat model argument in the start_agent command input, but when you give it an input without a chat model argument, it gives "Command start_agent returned: Error: Unknown chat model 'None'"

However, if you give it a chat model, it gives "Command start_agent returned: Error: start_agent() got an unexpected keyword argument 'chat_model'"

If anyone solves this, please provide some help :)

**Comment by wilocode** [comment]
Same here

**Comment by smirkingman** [comment]
Seems that it should be **model** and not **chat_model**

I fixed it by telling it: 
```
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 's' to run self-feedback commands, 'n' to exit program, or enter feedback
Asking user via keyboard...
Input:use model='gpt-3.5-turbo' instead of chat_model='gpt-3.5-turbo'
SYSTEM:  Human feedback: use model='gpt-3.5-turbo' instead of chat_model='gpt-3.5-turbo'
```
and it continued

**Comment by wilocode** [comment]
thanks! i'll try it tomorrow

**Comment by Laodeus** [comment]
working for me, thanks

**Comment by fckfizz** [comment]
worked for me, thanks

**Comment by domsca** [comment]
worked for me too, thanks

**Comment by Alexawy82** [comment]
worked for me as well, 
thanks.
would that be saved for future use , or we need to change something in the code ?

**Comment by maker2413** [comment]
I can confirm that the above suggestion unblocked me from this problem.

**Comment by battaglia01** [comment]
I'm getting 

"SYSTEM:  Command start_agent returned: Error: Cannot execute 'start_agent': unknown command. Do not try to use this command again."

Is this gone?
