### ISSUE TITLE
Long, mid and short-term Memory management

### ISSUE THREAD

**Issue by Wladastic** [Significant-Gravitas/Auto-GPT#4467]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Instead of just relying on encodings which just blurrs the memory, it would make much more sense to have commands ready for anything mid to longterm memory and have shortterm memory as the current context.

The longterm memory can be searched, while midterm memory is indexed by keywords.

Long and midterm are persistant. instead of killing autogpt each time, it should then remember what happened.
For that we could call the long and midterm on start and let the user approve if the context is correct.
Context and tasks are pretty well kept in the first party planner plugin already.

### Examples 🌈

Short Term:
current memory (messages list)

Mid Term:
get_midterm_index() -> ["google-what is autogpt?", "list_files_result"]

get_midterm_memory("google-what is autogpt?")
-> "I have researched what is autogpt and have found that autogpt...."

Long Term:
search_long_term("google-how to install autogpt")
-> another search-agent-GPT call receives a list of a "google-" list and returns them:
["google-what is autogpt?", "google-how is autogpt installed?"]

the search-agent-GPT evaluates which of the keys might fit and calls:
get_longterm_memory("google-how is autogpt installed?")

this can then be written to mid-term and short term.

This way we can make sure context is being held in Short-Term and messages will be written first to mid-term, then longterm chronologically.

### Motivation 🔦

Auto-GPT as of now has a horrible memory.
This way we could make it more human like.

**Comment by W3Warp** [comment]
Without even having read all you wrote (sry I will) I want to add. During these 5 weeks since I began using autogpt it's apparent that the problem isn't so much how much memory is available, what failed is the mechanism behind it. To begin with, a small portion of the STM has to be a server for context and reminders to dump data to LTM as well as the location of files saved. This is not working and therefore the STM will get full aka overwritten to the point that the agent no longer has any context for what it doing at this point I do not matter how much data you feed it if it cannot regain context. Auto-GPT can enter a chat mode of sorts where I will talk with you like you would talk to any other ChatGPT and at this stage, it will tell you absolutely everything it knows and doesn't get confused. I'm still unaware of how to trigger this is might be when AutoGPT crashes (almost) and "safeguards" if you will no longer function. The point being If we could have this known it would be so much easier to help find solutions.

**Comment by W3Warp** [comment]
https://github.com/users/W3Warp/projects/1?pane=issue&itemId=29513704

**Comment by ether8unny** [comment]
> Without even having read all you wrote (sry I will) I want to add. During these 5 weeks since I began using autogpt it's apparent that the problem isn't so much how much memory is available, what failed is the mechanism behind it. To begin with, a small portion of the STM has to be a server for context and reminders to dump data to LTM as well as the location of files saved. This is not working and therefore the STM will get full aka overwritten to the point that the agent no longer has any context for what it doing at this point I do not matter how much data you feed it if it cannot regain context. Auto-GPT can enter a chat mode of sorts where I will talk with you like you would talk to any other ChatGPT and at this stage, it will tell you absolutely everything it knows and doesn't get confused. I'm still unaware of how to trigger this is might be when AutoGPT crashes (almost) and "safeguards" if you will no longer function. The point being If we could have this known it would be so much easier to help find solutions.

to be totally transparent, the problem you're experienced is more of a symptom of the fact that we turned off memory and didn't really make a public announcement that we did.Memory has been 100% un useable since at some point along the 2.2 master line of things.

**Comment by W3Warp** [comment]
> > Without even having read all you wrote (sry I will) I want to add. During these 5 weeks since I began using autogpt it's apparent that the problem isn't so much how much memory is available, what failed is the mechanism behind it. To begin with, a small portion of the STM has to be a server for context and reminders to dump data to LTM as well as the location of files saved. This is not working and therefore the STM will get full aka overwritten to the point that the agent no longer has any context for what it doing at this point I do not matter how much data you feed it if it cannot regain context. Auto-GPT can enter a chat mode of sorts where I will talk with you like you would talk to any other ChatGPT and at this stage, it will tell you absolutely everything it knows and doesn't get confused. I'm still unaware of how to trigger this is might be when AutoGPT crashes (almost) and "safeguards" if you will no longer function. The point being If we could have this known it would be so much easier to help find solutions.
> 
> to be totally transparent, the problem you're experienced is more of a symptom of the fact that we turned off memory and didn't really make a public announcement that we did.Memory has been 100% un useable since at some point along the 2.2 master line of things.

I see, and thank you for letting us know. I wonder, however, what are these prompts that feed the memory on the session start about then? they started happening in 3.0 I believe along with the "self-feedback" future.
