### ISSUE TITLE
Command google returned: [] return nothing when using docker

### ISSUE THREAD

**Issue by PoolarBBear** [Significant-Gravitas/Auto-GPT#4493]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Commands

### Describe your issue.

When I deployed autogpt using docker, I found that all google commands did not return any content. However, when I tried to crul google.com in terminal of docker's container, I was able to return the content normally, which means I should be able to access google.com in the container. But the autogpt I deployed with git was able to run normally. The reason for switching from git to docker was because there were errors when running the. py file in the autogpt deployed with git. However, I noticed that someone had already raised the issue, so I switched to docker deployment, but found an issue with the command google.

### Upload Activity Log Content

the terminal of docker's container:

```
curl google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
```

# 
logs:

> 2023-05-31 18:23:34 NEXT ACTION:  COMMAND = google ARGUMENTS = {'query': 'impact of campus dating on socialist construction'}
> 2023-05-31 18:23:34   Enter 'y' to authorise command, 'y -N' to run N continuous commands, 's' to run self-feedback commands, 'n' to exit program, or enter feedback for ...
> 2023-05-31 18:23:34   Asking user via keyboard...
> 2023-05-31 18:23:38 Input:y
> 2023-05-31 18:23:38 -=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
> 2023-05-31 18:23:39 SYSTEM:  Command google returned: []
>  THOUGHTS:  Since we didn't find any relevant information on Google, let's try to analyze the issue ourselves. We can start by brainstorming the potential positive and negative effects of campus dating on socialist construction and society in general.
> 2023-05-31 18:24:10 REASONING:  If we can't find any relevant information on Google, we need to rely on our own analysis and critical thinking skills. By brainstorming the potential positive and negative effects of campus dating on socialist construction and society, we can identify the key issues and develop a more nuanced understanding of the topic.
> 2023-05-31 18:24:10 PLAN: 
> 2023-05-31 18:24:11 -  Brainstorm the potential positive and negative effects of campus dating on socialist construction and society
> 2023-05-31 18:24:11 -  Identify the key issues and develop a more nuanced understanding of the topic
> 2023-05-31 18:24:12 CRITICISM:  I need to make sure that I am considering a wide range of perspectives and not overlooking any important factors. I also need to be careful not to let my personal biases or assumptions influence my analysis.

### Upload Error Log Content

> 2023-05-31 18:23:39 SYSTEM:  Command google returned: []

_No response_

**Comment by kinance** [comment]
The underlying duckduckgo-search package that's in the docker image is deprecated. Could you try running the commands in the docker container? It's already fixed on master. The next release will not have this issue.
pip uninstall duckduckgo-search
pip install duckduckgo-search==3.0.2

**Comment by kinance** [comment]
Duplicates of #4350

**Comment by xiscoding** [comment]
I get pip is not found and python is not found when running the commands in the docker container. 

New to docker. 

The container is named auto-gpt redis_1 but it does not have the same packages as the auto-gpt image. The auto-gpt image has a container created when I run docker-compose run --rm auto-gpt but using the commands you recommended changes nothing there. 

any help is appreciated.

**Comment by erik-megarad** [comment]
`auto-gpt redis_1` is the container for redis and not auto-gpt

**Comment by kinance** [comment]
@xiscoding does it work now with the latest release version?

**Comment by sjnt1** [comment]
Having the same issue. Can someone explain in an easy way how to fix it? :)
