### ISSUE TITLE
GPT4ALL intergration

### ISSUE THREAD

**Issue by Omnikam1111** [Significant-Gravitas/Auto-GPT#4501]
This is a suggestion to create a Auto GPT version that can use GPT4ALL offline models. 
GPT4ALL is open source. free, and has an API so why not create a version of AutoGPT that uses it. No more fees paid to open AI 
and much more in line with the open source AI spirit
I use GPT4ALL , its a fantastic offline LLM chat bot with access to a vast amount of AI models. It would be wonderfull if these 2 wonderfull projects were combined

**Comment by kosirm** [comment]
Or https://github.com/aorumbayev/autogpt4all

**Comment by lc0rp** [comment]
Closing this. Linked to #25 

Other links of interest:
- https://github.com/aorumbayev/autogpt4all (inspiration)
- https://github.com/Significant-Gravitas/Auto-GPT/discussions/34 (discussion)
