### ISSUE TITLE
PINECONE_API_KEY and PINECONE_ENV is not found- what do I do?

### ISSUE THREAD

**Issue by mrmartech** [Significant-Gravitas/Auto-GPT#4504]
### ⚠️ Search for existing issues first ⚠️

- [ ] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

PINECONE_API_KEY and PINECONE_ENV is not found- what do I do?
I am in VS code following a tutorial here https://medium.com/the-generator/how-to-setup-auto-gpt-the-autonomous-gpt-4-ai-7ee6b82322ce

It says " Now, rename .env.template to .env and fill in your OPENAI_API_KEY and the PINECONE_API_KEY and PINECONE_ENV "

The first part I did no problem, the second part doesnt seem to exist 
![image](https://github.com/Significant-Gravitas/Auto-GPT/assets/73462993/97b6b6a1-e1ad-4059-9d46-9450d8c45012)

**Comment by Qoyyuum** [comment]
Please refer to the official docs instead. https://docs.agpt.co/setup/

And it has been removed to not use Pinecone. Please use Redis or Local memory.

**Comment by mrmartech** [comment]
Thank you!
