### ISSUE TITLE
ELEVENLABS from Docker setup still not resolved 

### ISSUE THREAD

**Issue by aymeric75** [Significant-Gravitas/Auto-GPT#4551]
### Which Operating System are you using?

Docker

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

When I do:
`
docker-compose run --rm auto-gpt --speak`

I get

```

Exception in thread Thread-1 (speak):
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/app/autogpt/speech/say.py", line 23, in speak
    success = voice_engine.say(text, voice_index)
  File "/app/autogpt/speech/base.py", line 33, in say
    return self._speech(text, voice_index)
  File "/app/autogpt/speech/eleven_labs.py", line 82, in _speech
    playsound("speech.mpeg", True)
  File "/usr/local/lib/python3.10/site-packages/playsound.py", line 91, in _playsoundNix
    import gi
ModuleNotFoundError: No module named 'gi'
```

This [Issue](https://github.com/Significant-Gravitas/Auto-GPT/issues/1697)  does not solve it.

m4vr0x almost solved the solution BUT :

"I assume this due to a missing sound interface in the docker container, which makes sense.
The next step would be to find a way to mount or link the host sound device inside the container..."

Any solution for this ?

Thanks a lot

**Comment by aymeric75** [comment]
Here is what I have tried so far:

1)  made a new image based on significantgravitas/auto-gpt but with added installed packaged (see last message [here](https://github.com/Significant-Gravitas/Auto-GPT/issues/1697)), I used this Dockerfile:
```

FROM significantgravitas/auto-gpt
RUN apt-get update && apt-get install -y gst123 && apt-get install -y gstreamer1.0-adapter-pulseeffects \
&& apt-get install -y gstreamer1.0-alsa && apt-get install -y pip && pip install playsound
```
and created the image like so:

`docker build -t autogptbis .`

2) then, from the autogpt folder (see setups intructions for Docker from the doc of autogpt), I ran:
`
docker-compose up --force-recreate auto-gpt`

in order to re-build the new autogpt image

But I get this output:
```

auto-gpt_1  | NEWS:  But to run the debugger challenge or other challenges using cassettes and VCR in docker, You will now need to `pip uninstall vcrpy` and `pip install -r requirements.txt` again.
auto-gpt_1  | NEWS:  This will install a new version of vcrpy that is compatible with running vcr in docker.
auto-gpt_1  | NEWS:  This workflow will be fixed as soon as the maintainer from VCRpy merges our changes.
auto-gpt_1  | NEWS:  
auto-gpt_1  | Welcome to Auto-GPT!  run with '--help' for more information.
auto-gpt_1  | Create an AI-Assistant:  input '--manual' to enter manual mode.
auto-gpt_1  |   Asking user via keyboard...
auto-gpt_1  | I want Auto-GPT to: 
auto-gpt_1  | Aborted!
autogpt_auto-gpt_1 exited with code 1
```

**Comment by Dar-Xs** [comment]
I think docker container can only use standard input & output, witch doesn't come with any sound device

i've got the same issue, maybe i have to try run python setup, so that this program can access system audio api, thus it can use my speaker.

Or if you are using MacBook, you can try select the sentences you want the machine to speak in terminal, then press `option` + `esc` to activate system TTS to read it for you

<img width="715" alt="image" src="https://github.com/Significant-Gravitas/Auto-GPT/assets/47471998/68e2d034-041f-4977-ba18-b474a2d3a72d">
<img width="537" alt="image" src="https://github.com/Significant-Gravitas/Auto-GPT/assets/47471998/4623fb2f-227e-407a-a764-4f1d94f889fb">
you can find related settings here
