### ISSUE TITLE
/usr/local/bin/python: No module named autogpt

### ISSUE THREAD

**Issue by newyorkthink** [Significant-Gravitas/Auto-GPT#4559]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

![image](https://github.com/Significant-Gravitas/Auto-GPT/assets/87791643/b917338d-298f-4d69-b251-b4e9f6079234)
![image](https://github.com/Significant-Gravitas/Auto-GPT/assets/87791643/8cea25d1-54d6-4d88-acdc-9c811c00ea24)

**Comment by erik-megarad** [comment]
The volume is wrong. It should be `- ./:/app` like in the default

**Comment by lihui123456** [comment]
请问解决了吗，我也遇到这个问题了
