### ISSUE TITLE
cannot locate files in workspace

### ISSUE THREAD

**Issue by nekohacker591** [Significant-Gravitas/Auto-GPT#456]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

ask the ai to look for files

### Current behavior 😯

cannot find the file said 
![image](https://user-images.githubusercontent.com/73713314/230702281-9d1ecc14-22c1-4c14-96ae-5596077856fc.png)

### Expected behavior 🤔

should find the file

### Your prompt 📝

```yaml
![image](https://user-images.githubusercontent.com/73713314/230702432-22c70308-7878-4f1a-a549-9c737f0504bd.png)

```

**Comment by GrzegorzKarczewski** [comment]
Look at your filenames. One is Receive.lua the other is Recieve.lua :)

**Comment by Explorergt92** [comment]
@nekohacker591 is this still an issue for you or can this be closed?
