### ISSUE TITLE
how to join the contributor team

### ISSUE THREAD

**Issue by PseudoProgrammer** [Significant-Gravitas/Auto-GPT#4583]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

how to join the contributor team

### Examples 🌈

how to join the contributor team

### Motivation 🔦

how to join the contributor team

**Comment by ScarletPan** [comment]
Hi, you can first join our [discord channel](https://discord.com/invite/autogpt) and share your brilliant ideas and discuss with other contributers.

**Comment by Boostrix** [comment]
Usually, you would get involved by getting a PR (pull request) reviewed and integrated.
At that point, you can collect your contributor badge - that way, you can access the various discord channels and github resources.

For suitable ideas, refer to: https://github.com/Significant-Gravitas/Auto-GPT/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

**Comment by PseudoProgrammer** [comment]
thanks for both answers
