### ISSUE TITLE
Scrapping webpages that do not exist.

### ISSUE THREAD

**Issue by umang299** [Significant-Gravitas/Auto-GPT#4584]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

I have tried using autogpt with openAI gpt-3.5 turbo. 

To summarize this issue, auto-gpt is failing to distinguish between valid and invalid links causing the agent to save random information that I has picked up from a webpage for analysis. Below I have listed an example.

### Examples 🌈

Task: Tell me how do I develop 4 weeks ML course for someone who has only basic understanding of python programming language. I want you to curate a plan to create a 4 week crash course to teach basics of machine learning. I want you to browse the internet, visit relevant websites and give me a plan.

It returned a fairly logical answer:
**Plan:**

- Use 'browse_website' command to visit relevant websites and gather information
- Use 'write_to_file' command to write a detailed plan for the 4-week crash course

followed by the below mentioned argument:

**ARGUMENTS** = {'url': 'https://www.edsurge.com/news/2019-06-17-how-to-teach-machine-learning-to-kids', 'question': 'What are the common machine learning algorithms?'}

The issue is the url mentioned in the argument doesn't exist and that autogpt somehow does not have the ability to differentiate between between valid and invalid urls for scrapping. Is this a known issue ? 
 

### Motivation 🔦

The feature that allows us to extract data from webpages  and perform any downstream task from it is very important. Any leads on how I can overcome this will be greatly appreciated. Thanks.

**Comment by Boostrix** [comment]
split up the task, let it research suitable websites first

**Comment by sagargulati** [comment]
The HTTP status of the website could achieve this, checking the DNS Records' existence, pinging the host or IP, and/or using managed Web Archive APIs. This could be easily integrating using a small script in local host to valid the response of the website you need to scrape.

**Comment by Boostrix** [comment]
We do have a bunch of related issues...

- https://github.com/Significant-Gravitas/Auto-GPT/issues/3444
- #4044

(will add more)

**Comment by gravelBridge** [comment]
> The HTTP status of the website could achieve this, checking the DNS Records' existence, pinging the host or IP, and/or using managed Web Archive APIs. This could be easily integrating using a small script in local host to valid the response of the website you need to scrape.

Yes I think this is the best solution, let's work on this.
