### ISSUE TITLE
Need a gradio UI interface to showcase the inputs and outputs

### ISSUE THREAD

**Issue by pearlmary** [Significant-Gravitas/Auto-GPT#4586]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Need a simple UI like gradio which will help to input responses see the output files instead of doing it in terminal.

**Comment by EncryptShawn** [comment]
Its not Gradio, its Nuxt, containerized and It's opensource and currently built on AutoGPT stable 0.4.0, perhaps that will do in the meantime.  But its a website, gui graphical interface with easy ability to provide inputs, view and interact with outputs and manage your autogpt workspace. 

https://github.com/neuronic-ai/autogpt-ui

**Comment by pearlmary** [comment]
Thank you for the update. 
It seems from the demo of autogpt-ui, should we provide the 5 goals also with "I want Auto-GPT to" statement/prompt?
Or can it take only the initial prompt from "I want auto-gpt to" and generate the 5 goals automatically as I can see in the command line. 
Just confused?
