### ISSUE TITLE
Thinking for too much time

### ISSUE THREAD

**Issue by SuperHack0328** [Significant-Gravitas/Auto-GPT#4593]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Other

### Describe your issue.

it show thingking for a long time and with this :
read more here: https://docs.agpt.co/setup/#getting-an-api-key
with `--debug`.he problem the persists try running it 
join the discord and ask there!thub issue or readme to double 

### Upload Activity Log Content

Using memory of type:  LocalCache Using Browser:  chrome

### Upload Error Log Content

read more here: https://docs.agpt.co/setup/#getting-an-api-key with `--debug`.he problem the persists try running it  join the discord and ask there!thub issue or readme to double

**Comment by lc0rp** [comment]
Do you have an openai API key configured?

**Comment by SuperHack0328** [comment]
i have
