### ISSUE TITLE
SYSTEM:  Command memory_del returned: Error: '>=' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by cometbus** [Significant-Gravitas/Auto-GPT#46]
SYSTEM:  Command memory_del returned: Error: '>=' not supported between instances of 'str' and 'int'

**Comment by Qoyyuum** [comment]
May not be relevant anymore since there have been enormous changes since. Please raise a new issue if you encounter this problem again, and include steps to help us reproduce this error.
