### ISSUE TITLE
[UX] Magic CLI with docker integration and bootstrapping capability

### ISSUE THREAD

**Issue by Pwuts** [Significant-Gravitas/Auto-GPT#4604]
## Background
There are a number of ways to run Auto-GPT, and some of them involve creating a directory structure and configuration files (such as the current way to set up Auto-GPT with docker). This is a bit of a hassle and can be made a lot easier.

## Proposal
* CLI creates necessary folders and files on startup when they don't exist yet
* CLI will try to run Auto-GPT in a docker container, with the appropriate volume mounts and other config
* CLI for running Auto-GPT with or without docker should be the same
* We ship an Auto-GPT package to Pypi which people can install and run easily (#2506)

## Example
(disclaimer: the exact output of commands may be different in practice. I'm just trying to sketch a concept.)
```console
$ pip install agpt
Successfully installed package agpt!
$ agpt
Working directory not specified...
$ agpt trial-project
Creating folder structure in trial-project... logs debug workspace ✅
Creating configuration files in trial-project...
Enter your API key to save it to the configuration: sk-************************************************
Created .env ✅
Starting Auto-GPT...

Welcome to Auto-GPT!
<MOTD>
...
```

**Comment by Dr33dM3** [comment]
Made a basic implemtation here: 
`import os
import sys
import shutil

# Function to create the necessary folders
def create_folders(project_path):
    folders = ['logs', 'debug', 'workspace']
    for folder in folders:
        folder_path = os.path.join(project_path, folder)
        os.makedirs(folder_path, exist_ok=True)
        print(f"Created folder: {folder_path} ✅")

# Function to create the configuration files
def create_config_files(project_path):
    api_key = input("Enter your API key to save it to the configuration: ")
    env_file_path = os.path.join(project_path, '.env')
    with open(env_file_path, 'w') as env_file:
        env_file.write(f"API_KEY={api_key}\n")
    print(f"Created .env file: {env_file_path} ✅")

# Function to start Auto-GPT
def start_auto_gpt(project_path):
    print("\nWelcome to Auto-GPT!")
    # Add Auto-GPT startup logic here

# Function to check if Docker is available
def is_docker_available():
    try:
        import docker
        return True
    except ImportError:
        return False

# Function to run Auto-GPT with Docker
def run_with_docker(project_path):
    if not is_docker_available():
        print("Docker is not available. Please run without Docker.")
        return

    docker_client = docker.from_env()
    volume_mounts = {
        project_path: {
            "bind": "/app",
            "mode": "rw"
        }
    }
    container = docker_client.containers.run(
        image='autogpt',
        volumes=volume_mounts,
        working_dir='/app',
        detach=True
    )
    print("Auto-GPT started in Docker container.")

# Entry point of the CLI
def main():
    # Check if a project name is provided
    if len(sys.argv) != 2:
        print("Usage: agpt <project_name>")
        return

    # Get the project name from command-line argument
    project_name = sys.argv[1]
    project_path = os.path.abspath(project_name)

    # Check if the project directory already exists
    if os.path.exists(project_path):
        print("Project directory already exists. Aborting.")
        return

    # Create the project directory
    os.makedirs(project_path)
    print(f"Created project directory: {project_path}")

    # Change the current working directory to the project directory
    os.chdir(project_path)

    # Create the necessary folders
    create_folders(project_path)

    # Create the configuration files
    create_config_files(project_path)

    # Check if Docker is available and run Auto-GPT with Docker if possible
    run_with_docker(project_path)

    # Start Auto-GPT
    start_auto_gpt(project_path)

# Run the CLI
if __name__ == "__main__":
    main()
`

**Comment by lc0rp** [comment]
Got some time off vacation to think about this. Initial thoughts below, comments welcome:

We kick off the workflow in ```cli.py``` just before ```run_auto_gpt()```

Prereq: Confirm CLI mode

### A. Add ```autogpt``` command to PATH during ```pip``` setup (pyproject.toml)

```
[options.entry_points]
console_scripts =
    autogpt = autogpt.cli:main
```
This reinforces the behavior that you can run ```autogpt``` from anywhere, not from within the ```Auto-GPT``` directory. 

> Do you think we should go even further and prohibit running within ```Auto-GPT/*```?

### B. Encourage ```pip install agpt```

Pseudocode:
- Check for the "autogpt" command  (```shutil.which("autogpt")```) - if it doesn't exist, this is likely a non-standard install
- If we're in continuous mode, test mode, or CI mode, display a notice encouraging the user to run "pip install agpt"
- Else, check if ```cwd() == ./Auto-GPT/``` and prompt the user if they'd like to run ```pip install -e .``` via ```subprocess.run```.

> Note, I'm keeping the command as ```autogpt``` to keep it closer to ```python -m autogpt```. I figured ```agpt``` might be a confusing change. Thoughts?

### C. Migrate legacy workspace_directory

> - Encourages people to specify a directory on CLI invocation
> - Moves the default directory to the user's $HOME

Pseudocode:
- If workspace_directory is not set:
    - Check for legacy workspace directory at ```Auto-GPT/auto_gpt_workspace``` OR ```Auto-GPT/autogpt/auto_gpt_workspace```
    - If found:
        - If we're in continuous mode, test mode, or CI mode display a warning about the upcoming deprecation of the old workspace directory
        - Else:
            - Ask the user if they want to migrate the directory
            - If yes:
                - Move the directory & set workspace_directory to the new path
            - Else:
                - Display deprecation message 
                - Set workspace_directory to legacy workspace_directory for now

- If workspace_directory is still not set:
    - If interactive, run the interactive setup - asking the user for the API key, working directory, etc
    - Else, run a non-interactive install - setting the default workspace directory to $HOME/auto_gpt_workspace

> Note, for this to work we probably need to move/copy .env, ai_settings.yaml and other yaml, and log files into the workspace_directory.
