### ISSUE TITLE
♾️ Tranfer off of openai to open source model (Possibly Vicuna/FastChat)

### ISSUE THREAD

**Issue by pmb2** [Significant-Gravitas/Auto-GPT#461]
### Summary 💡

I would love to see us get away from being dependent on openai's model.
We should train our own.

### Examples 🌈

https://github.com/lm-sys/FastChat

### Motivation 🔦

If they start tainting the models or take them from us..
No sense in waiting, we can make our own.

**Comment by russinet** [comment]
I think you severely underestimate the amount of sheer processing power and time required to train a model comparable to GPT-4, not to mention actually running it. There are a couple models such as GPT-J, Bloom, or LLama that you might want to take a look at, but don't expect anything near the quality of GPT-4.

**Comment by nponeccop** [comment]
The cross-model capability and/or ability to use weaker, more open and/or more tunable models as agents for GPT-4 would still be a good capability to have though. Delegate more, use GPT-4 for only the hardest tasks.

**Comment by erkkimon** [comment]
Also Open Assistant develops fast. I guess there will also be decentralized computing as an option soon. If the open locally run language models are not good enough today, they will be tomorrow.

**Comment by pmb2** [comment]
Yeah i just read about open assistant, I think we're doing better here in alot of areas, but there is alot to learn.
Things are moving quickly.

**Comment by Qoyyuum** [comment]
Closing this issue in favor of and duplicate to #567
