### ISSUE TITLE
Fix Migrating auto_gpt_workspace folder

### ISSUE THREAD

**Issue by ntindle** [Significant-Gravitas/Auto-GPT#4611]
*For the record:*
Instead of merging this I'd rather address the problem of the workspace folder wandering around. It's not supposed to be in `autogpt/`. That is the folder containing the program source and nothing else. It's not the first time that the workspace folder accidentally moved in there either; this has happened multiple times, usually caused by a relative reference to the workspace path being moved to a file that is one level deeper in `autogpt/`.

_Originally posted by @Pwuts in https://github.com/Significant-Gravitas/Auto-GPT/pull/4610#pullrequestreview-1466734677_

**Comment by Boostrix** [comment]
For the record, I have seen that being the case depending on the subdirectory from which I am starting the top level run script - the workspace seems to be set up beneath the cwd

**Comment by Pwuts** [comment]
This has been resolved in #5032
