### ISSUE TITLE
Updating API costs fails for Azure because model was renamed to `gpt-35-turbo`

### ISSUE THREAD

**Issue by ccdanpian** [Significant-Gravitas/Auto-GPT#4612]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Docker

### Which version of Auto-GPT are you using?

Stable (branch)

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Commands

### Describe your issue.

Version 0.4. I encountered an error while using the Azure API. However, after switching to the OpenAI API, it now runs properly. Additionally, the Azure API worked fine on version 0.3.1.

### Upload Error Log Content
![image](https://github.com/Significant-Gravitas/Auto-GPT/assets/130242490/ac01faa3-3066-401e-a70e-a7448c2ed671)

_No response_

**Comment by danpian230808** [comment]
I have also encountered the same issue. 
However, I have identified the problem from [#4445.](https://github.com/Significant-Gravitas/Auto-GPT/pull/4445) .
The reason for the problem is that the model name in Azure has been changed. modem name of gpt3.5 changed from "gpt-3.5-turbo" to "gpt-35-turbo". Therefore, in several related files in auto-gpt, the new model name needs to be listed.

Add gpt-35-turbo Cost information to autogpt/llm/modelsinfo.py, autogpt/llm/providers/openai.py, autogpt/llm/utils/token_counter.py

in these three files, the problem was solved by adding the following configurations respectively.
![图片](https://github.com/Significant-Gravitas/Auto-GPT/assets/135434848/15f789cc-8ffc-4447-9ded-54eee1044657)
![图片](https://github.com/Significant-Gravitas/Auto-GPT/assets/135434848/bdf6e21a-d709-4632-a436-7020a1f41054)
![图片](https://github.com/Significant-Gravitas/Auto-GPT/assets/135434848/3fb1996d-ebaa-4d18-b361-aa9deb67e00a)


This is the troublemaker
![图片](https://github.com/Significant-Gravitas/Auto-GPT/assets/135434848/1a250ad3-a3a9-4fdf-ad73-d5ddfc46ea0f)

**Comment by ccdanpian** [comment]
finally, problem solved.

**Comment by lc0rp** [comment]
@ccdanpian, @ddptt nice work finding the bug. It seems #4445 was closed suddenly.

If this is still an issue do you mind submitting a PR? Thanks!

**Comment by lc0rp** [comment]
Tracking #4607 here

**Comment by ajaxhe** [comment]
> I have also encountered the same issue. However, I have identified the problem from [#4445.](https://github.com/Significant-Gravitas/Auto-GPT/pull/4445) . The reason for the problem is that the model name in Azure has been changed. modem name of gpt3.5 changed from "gpt-3.5-turbo" to "gpt-35-turbo". Therefore, in several related files in auto-gpt, the new model name needs to be listed.
> 
> Add gpt-35-turbo Cost information to autogpt/llm/modelsinfo.py, autogpt/llm/providers/openai.py, autogpt/llm/utils/token_counter.py
> 
> in these three files, the problem was solved by adding the following configurations respectively.
> 
> autogpt/llm/providers/openai.py ![图片](https://user-images.githubusercontent.com/135434848/243976271-15f789cc-8ffc-4447-9ded-54eee1044657.png)
> 
> autogpt/llm/utils/token_counter.py ![图片](https://user-images.githubusercontent.com/135434848/243976454-bdf6e21a-d709-4632-a436-7020a1f41054.png)
> 
> autogpt/llm/modelsinfo.py ![图片](https://user-images.githubusercontent.com/135434848/243976993-3fb1996d-ebaa-4d18-b361-aa9deb67e00a.png)
> 
> This is the troublemaker ![图片](https://user-images.githubusercontent.com/135434848/243976057-1a250ad3-a3a9-4fdf-ad73-d5ddfc46ea0f.png)

However, after I modified it as suggested by [ddptt](https://github.com/ddptt),  the problem still existed when executing under mac.

I finally located the problem in line 72 of autogpt/llm/api_manager.py:
Replace:
self.update_cost(prompt_tokens, completion_tokens, model)
Change to:
self.update_cost(prompt_tokens, completion_tokens, response.model)
The problem is solved.

**Comment by ccdanpian** [comment]
@ajaxhe 
sorry first time i forgot this change. yesterday i have update the change in my branch fix-bug-#4612.

I need to make changes to these four places here before it's okay. Do you just need me to modify these areas?

**Comment by ccdanpian** [comment]
did more debugs, seems no need to add 'chat-gpt-35' in all three files.
after just add it in api_manager.py, and modify 'model' to 'response.model' or 'response["model"]' , auto-gpt can run correctly without this error.

But I still recommend adding the actual model name of azure in all the places where the deployment model name is configured.

![image](https://github.com/Significant-Gravitas/Auto-GPT/assets/130242490/a405e4a2-f3ea-470c-857b-02a66bf6939a)

**Comment by ajaxhe** [comment]
> @ajaxhe sorry first time i forgot this change. yesterday i have update the change in my branch fix-bug-#4612.
> 
> I need to make changes to these four places here before it's okay. Do you just need to modify self.update_cost?

@ccdanpian Yes, I think the other three changes are necessary, otherwise it would be impossible to calculate the token consumption.

After a brief look at the Azure-related configuration code, I think the 'response.model' configuration is also critical. In the Azure API, you only need to enter the deployment name, and the model parameter is not required, so it's important to get the model information from the response.

**Comment by ccdanpian** [comment]
I did a little research and it seems that the problem may be with the call to the model. Azure uses deployment ID because each person’s deployment ID is different, but when calculating costs, you must use the model name. However, in ver_0.4 when enabling Azure, the model name is not called. So if want to completely solve this problem,  may need to add the model name to the azure.ymal.

this is the model called in autogpt\llm\utils\__init__.py 
`    if cfg.use_azure:
        kwargs = {"deployment_id": cfg.get_azure_deployment_id_for_model(model)}
    else:
        kwargs = {"model": model}`

**I did the following verification and the Azure API worked correctly.”**
`        if not hasattr(response, "error"):
            logger.debug(f"Response: {response}")
            prompt_tokens = response.usage.prompt_tokens
            completion_tokens = response.usage.completion_tokens
            if deployment_id is not None:
                model="gpt-35-turbo"
            else:
                model=model
            self.update_cost(prompt_tokens, completion_tokens, model)`

**Comment by ajaxhe** [comment]
> I did a little research and it seems that the problem may be with the call to the model. Azure uses deployment ID because each person’s deployment ID is different, but when calculating costs, you must use the model name. However, in ver_0.4 when enabling Azure, the model name is not called. So if want to completely solve this problem, may need to add the model name to azure.ymal.
> 
> this is the model called in autogpt\llm\utils__init__.py ` if cfg.use_azure: kwargs = {"deployment_id": cfg.get_azure_deployment_id_for_model(model)} else: kwargs = {"model": model}`
> 
> I did the following verification in api_manager.py, and the Azure API worked correctly.
> 
> ```
>         if deployment_id is not None:
>             model="gpt-35-turbo"
>         else:
>             model=model
>         self.update_cost(prompt_tokens, completion_tokens, model)`
> ```
> 
> **or set the deployment ID on the Azure website to be consistent with the model name. Then in api_manager.py, use the deployment ID as the model name. I think this is the simplest solution. 😜** of course, the three files need to be modified at the same time.
> 
> ```
>         if deployment_id is not None:
>             model=deployment_id
>         else:
>             model=model
>         self.update_cost(prompt_tokens, completion_tokens, model)`
> ```

@ccdanpian You are right, considering that model name is a very critical parameter in autogpt and there are many places where this parameter is referenced, I would also recommend to assign values to the model parameter earlier (after Azure OpenAI model initialization) is done.

**Comment by ccdanpian** [comment]
I found another more simple way, just send the azure "deployment_id" with "model name" together, this way no need modify the other 3 files.
But there’s one thing to keep in mind: Azure’s token cost needs to be the same as OpenAI’s. It’s the same right now, but we don’t know if it will stay that way in the future.” 

autogpt\llm\utils__init__.py 

    if cfg.use_azure:
        kwargs = {"deployment_id": cfg.get_azure_deployment_id_for_model(model), "model": model}
    else:
        kwargs = {"model": model}
`

**Comment by ccdanpian** [comment]
@lc0rp This PR is really difficult to handle to me. I’m ready to give up. It always fails at codecov. The patch test coverage always is 0. It should be because there are no tests for the azure API in the test cases, and I can’t find where to add them. According to the project’s level of sophistication, it shouldn’t lack such test cases

**Comment by ccdanpian** [comment]
@ajaxhe could you help me review this PR? The modifications in this PR are as follows:
[https:github.com/Significant-Gravitas/Auto-GPT/pull/4663](url)
1. In autogpt\llm_init_.py, because there are two parameters related to the model in Azure: deployment id and model name, the code was modified to return both deployment id and model name instead of only deployment id.

2. In autogpt\llm\modelsinfo.py, azure model name was added.

**Comment by Pwuts** [comment]
Issue has been resolved according to this comment: https://github.com/Significant-Gravitas/Auto-GPT/pull/4690#issuecomment-1594129892
