### ISSUE TITLE
API insertation 

### ISSUE THREAD

**Issue by User-790** [Significant-Gravitas/Auto-GPT#4629]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

Where exactly is the .env.template file that we are to paste our API key into? After installing requirements and running the run.bat file, I have been getting this error`All packages are installed.
Please set your OpenAI API key in .env or as an environment variable.
You can get your key from https://platform.openai.com/account/api-keys` I have my API key I am just lost as to where to place it. 
Any advice?

**Comment by ccdanpian** [comment]
edit .env here:
![image](https://github.com/Significant-Gravitas/Auto-GPT/assets/130242490/728666cc-8f3e-4c34-8f94-b456c2edf384)

**Comment by ccdanpian** [comment]
input your key here:
![image](https://github.com/Significant-Gravitas/Auto-GPT/assets/130242490/72e52376-4a55-4743-95d5-719d6295950d)

**Comment by User-790** [comment]
Yes, but what is the file named?

**Comment by juancho-debug** [comment]
Yes i have the same problem , it seams that in the tutorials of the past version there is a env archive when you unzip the proyect . in this new release i haven`t found this one , i had changed in the  config.py the vairable  self.openai_api_key = os.getenv("  sk- ...  (my api key ) .    but it still doesn`t work .

**Comment by juancho-debug** [comment]
![Screenshot from 2023-06-09 17-32-43](https://github.com/Significant-Gravitas/Auto-GPT/assets/92512000/7ce28ed0-4192-47fa-867e-79bd4796fd4d)

**Comment by juancho-debug** [comment]
> Yes, but what is the file named?

Hi @User-790  i just watched this tutorial and in the first steps in the second 0:40  it tells to show hidden files , then you could find the .env.template    file in wich you should be able to see in line 72  where to put the api key  . 
![Screenshot from 2023-06-09 17-58-35](https://github.com/Significant-Gravitas/Auto-GPT/assets/92512000/c54a5d08-5ccd-438a-8359-37a8adbdd38b)
![Screenshot from 2023-06-09 18-00-41](https://github.com/Significant-Gravitas/Auto-GPT/assets/92512000/63da2ce7-c687-460d-be03-7987d7b6faf6)

**Comment by juancho-debug** [comment]
https://www.youtube.com/watch?v=OZr3nl04Fj0

**Comment by User-790** [comment]
Thanks a lot for your help! I'll check it out!
