### ISSUE TITLE
Selenium: Not connected to DevTools

### ISSUE THREAD

**Issue by merwanehamadi** [Significant-Gravitas/Auto-GPT#4644]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of Auto-GPT are you using?

Master (branch)

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Commands

### Describe your issue.

```
{
    "thoughts": {
        "text": "I will use the browse_website command to visit http://books.toscrape.com/catalogue/meditations_33/index.html and find the price of the book.",
        "reasoning": "The task requires me to visit a website and find the price of a book. The browse_website command is the most appropriate command for this task.",
        "plan": "- Use the browse_website command to visit the website\n- Find the price of the book\n- Write the price to a file named 'browse_website.txt'\n- Use the task_complete command to complete the task",
        "criticism": "I need to ensure that I am using the correct URL and question to find the price of the book.",
        "speak": "I will use the browse_website command to visit the website and find the price of the book."
    },
    "command": {
        "name": "browse_website",
        "args": {
            "url": "http://books.toscrape.com/catalogue/meditations_33/index.html",
            "question": "What is the price of the book?"
        }
    }
}
```

 "Command browse_website returned: Error: disconnected: not connected to DevTools"
 

 Full logs below: [20230610_151932_browse_website-.zip](https://github.com/Significant-Gravitas/Auto-GPT/files/11712760/20230610_151932_browse_website-.zip)

 the pipeline where it ran: https://github.com/merwanehamadi/Auto-GPT/actions/runs/5230642299/jobs/9444302953

**Comment by cmirdesouza** [comment]
As mentioned in the documentation, it can be broken because of development. Have you tested it in the stable branch for comparison? “Use stable, not master red_circle Download the latest stable release from here: https://github.com/Significant-Gravitas/Auto-GPT/releases/latest. The master branch is under heavy development and may often be in a broken state.”

**Comment by merwanehamadi** [comment]
yeah this happens in stable as well
