### ISSUE TITLE
eleven labs setup conflict in eleven_labs.py and config.py

### ISSUE THREAD

**Issue by Monty1122** [Significant-Gravitas/Auto-GPT#4656]
on 0.40 got this error running with --speak

AttributeError: 'Config' object has no attribute 'elevenlabs_voice_2_id'. Did you mean: 'elevenlabs_voice_id'?
File "/Users/david/Desktop/AI builds/Auto-GPT-latest/autogpt/speech/eleven_labs.py", line 43, in _setup

To resolve I modified the eleven_labs.py file and removed the lines related to elevenlabs_voice_2_id. T

This eliminated the AttributeError from occurring and then only uses a single voice ID attribute.

not sure if this is the best fix but it worked in case others have it

**Comment by gravelBridge** [comment]
Thanks for bringing this issue to our attention, @Monty1122. It seems like there's a conflict between the eleven_labs.py and config.py files, specifically with the attribute elevenlabs_voice_2_id.

Your workaround of modifying the eleven_labs.py file to remove the lines related to elevenlabs_voice_2_id is a good temporary solution. However, it might not be the best long-term fix as it could potentially limit the functionality of the program, especially if there are plans to use multiple voice IDs in the future.

We'll look into this issue and aim to provide a more permanent solution. It's possible that the attribute elevenlabs_voice_2_id was deprecated or renamed, and the eleven_labs.py file was not updated accordingly. We appreciate your patience and contribution to improving Auto-GPT.

In the meantime, if you encounter any other issues or have further suggestions, please don't hesitate to share them.
