### ISSUE TITLE
How do I alter the initial prompt of an ongoing Auto-GPT session. 

### ISSUE THREAD

**Issue by sam1am** [Significant-Gravitas/Auto-GPT#466]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

I want to re-prioritize tasks without losing progress. How can I re-program the bot as it is going? I can't find the prompt stored anywhere locally to modify. 

### Examples 🌈

n/a

### Motivation 🔦

I want to re-prioritize tasks without losing progress

**Comment by rowbot1** [comment]
I don't think you can currently

**Comment by Qoyyuum** [comment]
CTRL+C to terminate running program. Whatever was stored in memory when it was running can still be used in the next run. Closing issue.
