### ISSUE TITLE
During the execution of the code, there are certain instances when the value of max_token becomes None.

### ISSUE THREAD

**Issue by IBAS0742** [Significant-Gravitas/Auto-GPT#4674]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Other

### Describe your issue.

During the execution of the code, there are certain instances when the value of max_token becomes None.

![image](https://github.com/Significant-Gravitas/Auto-GPT/assets/19849088/1e1e9170-895a-42b9-a5c0-5d71c1530096)

Is it possible that this is a bug causing max_token to exceed 4097?

![image](https://github.com/Significant-Gravitas/Auto-GPT/assets/19849088/14f8111a-66a4-4af2-81ac-ba453612a40e)

**Comment by kinance** [comment]
Do you enable any plugins?

**Comment by IBAS0742** [comment]
> Do you enable any plugins?

I haven't modified the configuration of the plugin section, so it seems like I haven't configured any plugins. I also don't understand the code, so I didn't rashly make any modifications.

![image](https://github.com/Significant-Gravitas/Auto-GPT/assets/19849088/763e7270-3ceb-43cd-af9f-e05bdec0cedb)
