### ISSUE TITLE
32K custom url 

### ISSUE THREAD

**Issue by sffinx** [Significant-Gravitas/Auto-GPT#4675]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

 I have a custom GPT-4 API key that supports 32k, but it is not from OpenAI (so it also has a different base URL). How can I use it?

**Comment by theblazehen** [comment]
Set the environment variable `OPENAI_API_BASE`

**Comment by xihajun** [comment]
do you meant azure api

**Comment by sffinx** [comment]
> Set the environment variable `OPENAI_API_BASE`

And how can i set gpt-32k ? As model llm ?

**Comment by sffinx** [comment]
> do you meant azure api

No, it’s a custom api gpt 4
