### ISSUE TITLE
Can no longer copy+paste text in CMD or powershell

### ISSUE THREAD

**Issue by cranyy** [Significant-Gravitas/Auto-GPT#4681]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Other

### Describe your issue.

I just pulled the latest version and for some reason, I can no longer copy paste anything inside. I tried CMD and Powershell and always the same result. This happens on Windows

**Comment by ianbmacdonald** [comment]
Try pulling the stable branch instead of the latest if you want to file an issue.

`git clone -b stable https://github.com/Significant-Gravitas/Auto-GPT.git`

**Comment by cranyy** [comment]
Well I am on stable currently and I have the exact same issue. cant copy paste anything inside the CMD in Windows.

**Comment by muunkky** [comment]
Still having this problem on stable
