### ISSUE TITLE
Update from OpenAI

### ISSUE THREAD

**Issue by LanceLake** [Significant-Gravitas/Auto-GPT#4682]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

OpenAI Logo
We're excited to announce a few updates to the OpenAI developer platform.
GPT-3.5 Turbo
This model has been updated with a new version: gpt-3.5-turbo-0613 which is more steerable with the system message and includes a new capability: function calling. By describing functions in your prompts, the model can intelligently output a JSON object containing arguments to call these functions based on user input — perfect for integrating with other tools or APIs. Learn more in our function calling documentation.

Plus enjoy a 25% cost reduction for input tokens on GPT-3.5 Turbo (now $0.0015 per 1K input tokens), effective immediately.

Longer Context
We're also introducing gpt-3.5-turbo-16k. This model offers four times the context length of the 4k base model and is priced at $0.003 per 1K input tokens and $0.004 per 1K output tokens.

Model Transitioning
You can begin using the new gpt-3.5-turbo-0613 model today. On June 27th, the stable gpt-3.5-turbo will be automatically upgraded to this new version. If you need more time to transition, you can specify gpt-3.5-turbo-0301 to keep using the older version, which will remain available until September 13th as part of our upgrade and deprecation process.

—The OpenAI team

### Motivation 🔦

I would like to use these 2 modes.

**Comment by hunkim** [comment]
Most commands can be replaced by GPT functions, which will give us more accurate function calls and arguments. Wonderful!

**Comment by hunkim** [comment]
https://platform.openai.com/docs/guides/gpt/function-calling

```python
import openai
import json

# Example dummy function hard coded to return the same weather
# In production, this could be your backend API or an external API
def get_current_weather(location, unit="fahrenheit"):
    """Get the current weather in a given location"""
    weather_info = {
        "location": location,
        "temperature": "72",
        "unit": unit,
        "forecast": ["sunny", "windy"],
    }
    return json.dumps(weather_info)

# Step 1, send model the user query and what functions it has access to
def run_conversation():
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo-0613",
        messages=[{"role": "user", "content": "What's the weather like in Boston?"}],
        functions=[
            {
                "name": "get_current_weather",
                "description": "Get the current weather in a given location",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "location": {
                            "type": "string",
                            "description": "The city and state, e.g. San Francisco, CA",
                        },
                        "unit": {"type": "string", "enum": ["celsius", "fahrenheit"]},
                    },
                    "required": ["location"],
                },
            }
        ],
        function_call="auto",
    )

    message = response["choices"][0]["message"]

    # Step 2, check if the model wants to call a function
    if message.get("function_call"):
        function_name = message["function_call"]["name"]

        # Step 3, call the function
        # Note: the JSON response from the model may not be valid JSON
        function_response = get_current_weather(
            location=message.get("location"),
            unit=message.get("unit"),
        )

        # Step 4, send model the info on the function call and function response
        second_response = openai.ChatCompletion.create(
            model="gpt-3.5-turbo-0613",
            messages=[
                {"role": "user", "content": "What is the weather like in boston?"},
                message,
                {
                    "role": "function",
                    "name": function_name,
                    "content": function_response,
                },
            ],
        )
        return second_response

print(run_conversation())

```

**Comment by ianbmacdonald** [comment]
Same for: gpt-4-0613 is now available and adds a new capability: function calling. By describing functions in your prompts, the model can intelligently choose to output a JSON object containing arguments to call these functions based on user input — perfect for integrating with other tools or APIs. Learn more in our function calling documentation.

**Comment by clearsitedesigns** [comment]
Excited about this since this opens up using micro-tool-based python scripts. Has anyone compiled a list of the most used functions / or fail points in AGPT?

**Comment by brappier** [comment]
Follow me on twittr.

**Comment by hunkim** [comment]
Should we refactor commands using the GPT function call? @limerobot

**Comment by rodrigogs** [comment]
> Should we refactor commands using the GPT function call? @limerobot

I just dropped by to check if you guys were scrambling to get this ready soon. In my opinion, it could be the answer to AutoGPT's main issue, which is struggling to use its own features. Most times, my agents trip up on straightforward tasks like doing a "list_files" command.

**Comment by jonasdebeukelaer** [comment]
Yeah this feels like a must to implement.

One common pit fall I've noticed with my bot is that it will get stuck in a loop of not knowing how to call a command with correct args and arg types, and will start hallucinating more and more. I've added a couple tweaks on my version but still not perfect.

Would be happy to support this dev but I imagine discussions have prob started in the discord.

**Comment by brappier** [comment]
@jonasdebeukelaer  pls follow me and i will tell you how

**Comment by zachary-kaelan** [comment]
> Most commands can be replaced by GPT functions, which will give us more accurate function calls and arguments. Wonderful!

I wouldn't be surprised if OpenAI was thinking of projects like this while making that feature.

They already have examples for [knowledge retrieval](https://github.com/openai/openai-cookbook/blob/31a3a7b406eb452c9bb60e97902b55c25620b9d1/examples/How_to_call_functions_for_knowledge_retrieval.ipynb) and for [making SQL queries](https://github.com/openai/openai-cookbook/blob/31a3a7b406eb452c9bb60e97902b55c25620b9d1/examples/How_to_call_functions_with_chat_models.ipynb). Time to redo the prompts and commands system, I guess.
