### ISSUE TITLE
Exceeded token length of 4097 tokens (GPT-3.5)

### ISSUE THREAD

**Issue by johnsmithlon** [Significant-Gravitas/Auto-GPT#4696]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Commands

### Describe your issue.

I get the following error:

openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens. However, your messages resulted in 4263 tokens. Please reduce the length of the messages.

I am using the latest master branch.

Detailed error log is:

  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens. However, your messages resulted in 4263 tokens. Please reduce the length of the messages.

**Comment by Pwuts** [comment]
> Detailed error log is:

@johnsmithlon please post the full log. The snippet you included may look detailed, but tells us nothing.
