### ISSUE TITLE
Native GPT functions

### ISSUE THREAD

**Issue by ttmx** [Significant-Gravitas/Auto-GPT#4718]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

https://openai.com/blog/function-calling-and-other-api-updates
This blogpost seems to indicate a new functionality in GPT, which would allow the use of external to GPT functions to become more stable.

I do not know exactly how this project works, but seems worth mentioning and investigating.

**Comment by Boostrix** [comment]
It's work in progress
