### ISSUE TITLE
The program is frozen when executing speak.say_text(f"{title}. {content}").

### ISSUE THREAD

**Issue by bitcoin088** [Significant-Gravitas/Auto-GPT#473]
Hi, the program is working perfectly when I don't activate the --speak option. However, when I activated the --speak option, the program is frozen at 
speak.say_text(f"{title}. {content}").

On my elevenlabs account in the "history" I can see that the program sent the requests and I can listen to them. 
I have added "import pyttsx3" and tried to replace all the lines speak.say_text(XXX) by:
```
engine = pyttsx3.init()
engine.say("{title}. {content}")
engine.runAndWait()
```

Then the program works but the voice is horrible it does not say all the sentences.....

I am working under Ubuntu 20.04

**Comment by Qoyyuum** [comment]
This has been greatly improved in the current latest stable release. Please download the latest stable release and try again. Closing issue.
