### ISSUE TITLE
import requests ModuleNotFoundError: No module named 'requests'. Infinite loop

### ISSUE THREAD

**Issue by lmsanch** [Significant-Gravitas/Auto-GPT#4731]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of Auto-GPT are you using?

Stable (branch)

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

The code enters an infinite loop, indicating that the Python library requests is not installed, but when I do pip freeze in my virtual env, I get this:

```
requests==2.30.0
requests-oauthlib==1.3.1
rsa==4.9
selenium==4.1.4
shellingham==1.5.0.post1
six==1.16.0
smart-open==6.3.0
```

```
AUTHORISED COMMANDS LEFT: 57 
  Executing python file '/Users/luis/Documents/Auto-GPT/autogpt/auto_gpt_workspace/BoxOfficeGPT/executed_code/enron_script.py' in working directory '/Users/luis/Documents/Auto-GPT/autogpt/auto_gpt_workspace'
  Image 'python:3-alpine' found locally
SYSTEM:  Command execute_python_code returned: Traceback (most recent call last): File "/workspace/BoxOfficeGPT/executed_code/enron_script.py", line 1, in <module> import requests ModuleNotFoundError: No module named 'requests'
              
Aborted!
```
I dont know what's wrong

### Upload Activity Log Content

Normal activity log

### Upload Error Log Content

empty error log

**Comment by fosteman** [comment]
same here. in a loop, for some reason `execute_python_code ` is operating in a wrong environment. I have anaconda installed
