### ISSUE TITLE
Command read_file attempt from filename with https:/ in it

### ISSUE THREAD

**Issue by Bec-k** [Significant-Gravitas/Auto-GPT#4754]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Commands

### Describe your issue.
```
NEXT ACTION:  COMMAND = read_file ARGUMENTS = {'filename': '/var/local/my/Auto-GPT/autogpt/auto_gpt_workspace/https:/www.blabla.com/some-url-here'}
  Enter 'y' to authorise command, 'y -N' to run N continuous commands, 's' to run self-feedback commands, 'n' to exit program, or enter feedback for Bla bla researcher...
  Asking user via keyboard...
```

**Comment by denissabramovs** [comment]
Using pre-release tag `v0.4.1`

**Comment by denissabramovs** [comment]
Then it is getting this error:
```
SYSTEM:  Command read_file returned: Error: read_file /var/local/my/Auto-GPT/autogpt/auto_gpt_workspace/https:/www.blabla.com/some-url-here failed: no such file or directory
```
