### ISSUE TITLE
Stuck at website 

### ISSUE THREAD

**Issue by dysai1234** [Significant-Gravitas/Auto-GPT#476]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

When it uses the below command for  websites which are down it will wait a long time 

COMMAND = browse_website ARGUMENTS = {'url': 'https://www.niftyindices.com/nifty-indices/equity-indices/live-nifty-fifty/', 'question': 'What is the Nifty 50 index?'}

### Current behavior 😯

![image](https://user-images.githubusercontent.com/48354881/230715817-2445395b-3620-4406-b2dd-bfa85399c42f.png)

### Expected behavior 🤔

If it is stuck more thant some time we can ask it to move it to next one 

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by drnoi** [comment]
In prompt.txt update this line to add the timeout. websites that block will get passed after 10 seconds.

5. Browse Website: "browse_website", args: "url": "<url>", "question": "<what_you_want_to_find_on_website>", "timeout":10000
