### ISSUE TITLE
Warning, you do not have access to gpt-4

### ISSUE THREAD

**Issue by lillianfidler** [Significant-Gravitas/Auto-GPT#4765]
I get this warning at right upon starting the program with the following: 

Setting smart_11m_model to gpt-3.5 turbo

Is this anything that can be fixed or should I not worry about it.

Thank you!

**Comment by collijk** [comment]
Everyone with a paid api subscription should have GPT 4 access now.

**Comment by Stiofan** [comment]
I get this too and i have a paid API key

**Comment by PietMaree74** [comment]
Me too. I have a paid API key and can use GPT-4 through python. When i run ./sh rm --gpt4only i get the same warning message that it is setting smart_llm to gpt-3.5-turbo (I set it to gpt-4 in the .env file)

**Comment by Stiofan** [comment]
Currently openAI are only allowing access to GPT4 to users who have spent $1 via the GTP3 API (not even current paid users of chatGPT)

**Comment by mlevin2** [comment]
Huh? So I need to go spend $1 worth of usage on GPT3 before I can access the GPT4 API?
