### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by jalenarko** [Significant-Gravitas/Auto-GPT#4767]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Commands

### Describe your issue.

when i write .\run.bat and press enter it doesn`t work. It types likes everything is fine and then types: TypeError: 'type' object is not subscriptable

**Comment by collijk** [comment]
There is insufficient information here for us to help with your issue. Please submit your logs or a screenshot with your bug.
