### ISSUE TITLE
Add mypy everywhere to enforce type hints in the whole codebase

### ISSUE THREAD

**Issue by merwanehamadi** [Significant-Gravitas/Auto-GPT#4788]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

mypy.ini
```
[mypy]
follow_imports = skip
check_untyped_defs = True
disallow_untyped_defs = True
files = tests/challenges/**/*.py

[mypy-requests.*]
ignore_missing_imports = True
[mypy-yaml.*]
ignore_missing_imports = True
```

change this config to include more files and send a PR for this.
Do it steps by steps so you avoid big merge conflicts.

**Comment by abhinav700** [comment]
Can you assign this issue to me? i would love to work on it
