### ISSUE TITLE
Fast LLM is the only model used it appears. The smart LLM does not show up in any debug logs

### ISSUE THREAD

**Issue by NeonN3mesis** [Significant-Gravitas/Auto-GPT#4795]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

AI Model Limitations

### Describe your issue.

Setting Smart LLM to GPT-4 and Setting Fast LLM to GPT-3.5-Turbo only shows 3.5-turbo being used in the logs. Both should be used for different tasks correct? Or the option should be removed.

**Comment by erik-megarad** [comment]
This is as expected, currently. We aren't using the smart llm anywhere because gpt-4 is not widely available. We should probably update the docs

**Comment by Ludacon** [comment]
Seems like even without gpt4 support the fast/smart context switching could be used to leverage the larger 16k context gpt3.5 as a "smart" (or more expensive) llm and the normal turbo as the fast to utilize larger context without incurrring un needed cost for smaller task. 


also thank you for clarifying, I was going mad trying to figure out why it wasnt using the smart llm. 

So changing the fast llm to gpt4 is currently the way to use gpt4 correct?

**Comment by erik-megarad** [comment]
Yeah, since the fast llm is the only one used you can switch the fast llm to gpt-4 and it should work.

**Comment by lc0rp** [comment]
Workaround Use --gpt4only or --gpt3only selectors.
TODO: Update documentation

**Comment by Pwuts** [comment]
Fixed in #4899 :)
