### ISSUE TITLE
Request WIPE_WORKSPACE_ON_START

### ISSUE THREAD

**Issue by NeonN3mesis** [Significant-Gravitas/Auto-GPT#4804]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

a setting in the .env file, if set to TRUE would wipe the workspace when Auto-GPT is started

### Motivation 🔦

Save me time from having to clean it myself when running my own tests

**Comment by Boostrix** [comment]
To be honest, I am not in favor of actually deleting stuff - in my opinion it would be better to have a top level directory and then simply rename those as needed - we have related PRs to support a similar setup for having multiple yaml files and alternating between those.
