### ISSUE TITLE
"Thinking" forever

### ISSUE THREAD

**Issue by manfred0191** [Significant-Gravitas/Auto-GPT#4807]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows Subsystem for Linux (WSL)

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Installation and setup

### Describe your issue.

When I am running the example shown, the program says "Thinking" and that forever. There is nothing else going on. I already addressed this issue in discord, but no one answers my question.

**Comment by manfred0191** [comment]
Here are the activity.log and the logs from the DEBUG folder after running it with --debug

[activity.log](https://github.com/Significant-Gravitas/Auto-GPT/files/11879409/activity.log)
[debug_folder.zip](https://github.com/Significant-Gravitas/Auto-GPT/files/11879416/debug_folder.zip)

**Comment by lc0rp** [comment]
It turns out it was for lack of a paid OpenAI API key. Helped via Discord. Good luck!

**Comment by dinosaw** [comment]
Sorry for commenting on a closed issue, but is a **paid** OpenAI API key required? I ask because I'm getting the same issue, however I was under the impression that a user can get `X` amount of queries without a paid API key?

**Comment by copeugne** [comment]
> Sorry for commenting on a closed issue, but is a **paid** OpenAI API key required? I ask because I'm getting the same issue, however I was under the impression that a user can get `X` amount of queries without a paid API key?

All the API calls are paid iirc. So you can't make queries if you didn't top up.
