### ISSUE TITLE
AutoGPT writing to multiple workspaces depending on how it is ran

### ISSUE THREAD

**Issue by sulaimonao** [Significant-Gravitas/Auto-GPT#4821]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Documentation

### Describe your issue.

running AutoGPT with "docker-compose run --rm auto-gpt" doesn't continue previous prompts, but when i use  "./run.sh" i am prompted to continue prompts started with "run.sh".  I believe the workspace used is determined by how you run the program  "./run.sh" writes to /Users/akeemsulaimon/Documents/Auto-GPT/autogpt/workspace/auto_gpt_workspace and using  "docker-compose run --rm auto-gpt" writes to /Users/akeemsulaimon/Documents/Auto-GPT/auto_gpt_workspace 
<img width="1361" alt="Screen Shot 2023-06-26 at 5 38 57 PM" src="https://github.com/Significant-Gravitas/Auto-GPT/assets/16595684/7343d56b-cc3c-4b41-9c4b-0656cc8a0484">
<img width="562" alt="Screen Shot 2023-06-27 at 1 02 54 PM" src="https://github.com/Significant-Gravitas/Auto-GPT/assets/16595684/21d0acda-1d1d-4225-ae72-60d330699a3e">

**Comment by LanceLake** [comment]
I'm on windows 10 and I run it the same way. I noticed this behavior as well. Sometimes it uses the proper workspace, but then sometimes, it makes a new workspace under the autoGPT directory (even when I tell it specifically not to).

**Comment by Boostrix** [comment]
just to confirm, also saw different workspaces popping up

**Comment by sulaimonao** [comment]
> just to confirm, also saw different workspaces popping up 

Yes when I'm paying attention I'll see which workspace it is planning on saving files to
