### ISSUE TITLE
Agent unable to run python code written using write_to_file prompt

### ISSUE THREAD

**Issue by sulaimonao** [Significant-Gravitas/Auto-GPT#4822]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

During my prompt (write a rap song about coding in the style of Eminem), agent wrote some python codes (not sure why), but is unable to run/execute the file. Leads to a loop and then an error parsing json
<img width="1259" alt="Screen Shot 2023-06-27 at 1 51 43 PM" src="https://github.com/Significant-Gravitas/Auto-GPT/assets/16595684/710bead9-7b0b-4ce5-ba4f-f229b3e6c482">
<img width="690" alt="Screen Shot 2023-06-27 at 1 56 48 PM" src="https://github.com/Significant-Gravitas/Auto-GPT/assets/16595684/5c158628-8d47-42dd-abd3-f7291c98ee10">
<img width="1439" alt="Screen Shot 2023-06-27 at 12 56 45 PM" src="https://github.com/Significant-Gravitas/Auto-GPT/assets/16595684/841a518b-6e7e-41da-b950-2bdbabf912f8">
[Uploading activity.log…]()
[error.log](https://github.com/Significant-Gravitas/Auto-GPT/files/11887479/error.log)

**Comment by a1264113629** [comment]
AutoGPT runs Python scripts within a container. To use AutoGPT, you have two options: either install Docker (which allows AutoGPT to initiate a temporary container for script execution) or directly run AutoGPT inside a container. I prefer starting AutoGPT in an existing container that already has Python and common packages installed. This helps to save the execution time of AutoGPT.

**Comment by a1264113629** [comment]
AutoGPT runs Python scripts within a container. To use AutoGPT, you have two options: either install Docker (which allows AutoGPT to initiate a temporary container for script execution) or directly run AutoGPT inside a container. I prefer starting run.sh in an existing container that already has Python and common packages installed. This helps to save the execution time.

**Comment by a1264113629** [comment]
AutoGPT runs Python scripts within a container. To use AutoGPT, you have two options: either install Docker (which allows AutoGPT to initiate a temporary container for script execution) or directly run AutoGPT inside a container. I prefer starting run.sh in an existing container that already has Python and common packages installed. This also helps to save the execution time.

**Comment by sulaimonao** [comment]
> AutoGPT runs Python scripts within a container. To use AutoGPT, you have two options: either install Docker (which allows AutoGPT to initiate a temporary container for script execution) or directly run AutoGPT inside a container. I prefer starting run.sh in an existing container that already has Python and common packages installed. This also helps to save the execution time.

I have docker Installed not sure what the issue is , i can try running the run.sh file inside a container

**Comment by tomtom94** [comment]
Hello I am in the same case.

https://discord.com/channels/1092243196446249134/1092266131110236170/1123560112989163540

Auto-GPT isn't able to install python modules in the docker container they need to be used. Whatever how you run Auto-GPT with docker or with python straight.

We need to make a regex to find all the import in a file
https://github.com/Significant-Gravitas/Auto-GPT/pull/4847/files#diff-3a17cf79b7ab8e6b1ea66d34144971f6bb366c5638a666af493889d91f4cac5aR103

```
regex_imports = re.findall(r"import (.*(?=\n))", code)
```

We could also ask to GPT to make a Dockerfile ready to go, otherwise we need to compute one in Auto-GPT with a regex.

**Comment by gatepoet** [comment]
> I am touching the exact same part of the code, I am not sure we are talking about the same issue but myself I got the logs
> 
> ```
> Image 'python:3-alpine' found locally 
> SYSTEM: Command execute_python_code returned: Traceback (most recent call last): File "/workspace/FSGPT/executed_code/fibonacci.py", line 1, in <module> import openpyxl ModuleNotFoundError: No module named 'openpyxl'
> ```
> 
> First line Auto-GPT runs in a container `python:3-alpine` no worries about that. But then in the python code there is a line `import openpyxl` but this module needs to be installed and is not in `python:3-alpine` default docker image...
> 
> I have been trying to make a conversation on Discord https://discord.com/channels/1092243196446249134/1092266131110236170/1123560112989163540
> 
> Auto-GPT isn't able to install python modules in the docker container they need to be used. Whatever how you run Auto-GPT with docker or with python straight.
> 
> For me there are 2 alternatives:
> 
> * We could ask to GPT to make a `Dockerfile` ready to go and the `requirements.txt`,
> * Otherwise we need to compute one in Auto-GPT with a `regex`.
> 
> I have been trying to make a `regex` to find all the import in a file https://github.com/Significant-Gravitas/Auto-GPT/pull/4847/files#diff-3a17cf79b7ab8e6b1ea66d34144971f6bb366c5638a666af493889d91f4cac5aR103
> 
> ```
> regex_imports = re.findall(r"import (.*(?=\n))", code)
> ```
> 
> It's kind of working...

You might be onto another problem here, that seems to arise when executing python files from AutoGPT outside of docker and needing to install requirements. I was executing with both docker compose and devcontainer, and I was experience the same issue. In my case the problem was that AutoGPT didn't realize that it was in a container and tried to start a new one for the code execution.
