### ISSUE TITLE
Azure OpenAI setup fails with error AttributeError: 'ConfigSettings' object has no attribute 'get_azure_deployment_id_for_model'

### ISSUE THREAD

**Issue by FerranSalguero** [Significant-Gravitas/Auto-GPT#4838]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

Using Azure OpenAI, after setting up my goals it fails with the following error:
![Screenshot 2023-06-29 102025](https://github.com/Significant-Gravitas/Auto-GPT/assets/645489/ce8b9d3a-12e4-40a7-9960-7629a58d8c2f)

  File "/app/autogpt/llm/utils/__init__.py", line 144, in create_chat_completion
    ] = config.get_azure_deployment_id_for_model(model)
AttributeError: 'ConfigSettings' object has no attribute 'get_azure_deployment_id_for_model'

Checking the code it seems that ConfigSettings was rearched but this init still uses this function

**Comment by conver334** [comment]
I also meet this error in the same situation, windows, and after setting my goals.

I

**Comment by nithinkanil1** [comment]
+1

**Comment by jinwonkim93** [comment]
+1

**Comment by Mitrandir-main** [comment]
Has anyone solved it?

**Comment by jinwonkim93** [comment]
@Mitrandir-main this fix the problem https://github.com/Significant-Gravitas/Auto-GPT/pull/4875

**Comment by collijk** [comment]
This should be fixed with #4875 .  Please @ me if you're still having issues.
