### ISSUE TITLE
SingularGPT - Device automation and AI Mind 

### ISSUE THREAD

**Issue by abhiprojectz** [Significant-Gravitas/Auto-GPT#484]
Hello, 

SingularGPT is a open source project that aims to automate complex tasks such as device automation using the latest trending LLM models that is ChatGPT & GPT-4.

With 🚀 SingularGPT you can easily instruct your device such as your PC using Natural language, with built in logic processing.

[SingularGPT](SingularGPT)

For example:

Let's say you wish to accomplish any task on your device instead of writing automation scripts, then testing it further debugging it, playing around with co-ordinates.

**Query:** Hey, please click on the item with text "Document Writer" after that click on the image with path "image.png" after that scroll down and then find element that is top of text "File" , double left click it.
The SingularGPT will process it and does the task.

If anyone interested, kindly please give your suggestions!

**Comment by richbeales** [comment]
Please head over to the Discord to discuss this, and close this issue.
