### ISSUE TITLE
Command read_file returned: Error: 'NoneType' object has no attribute 'fast_llm_model'

### ISSUE THREAD

**Issue by TR1234567890** [Significant-Gravitas/Auto-GPT#4848]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Commands

### Describe your issue.

I repeat getting this error after read_file command.
NEXT ACTION:  COMMAND = read_file ARGUMENTS = {'filename': 'C:\\Users\\Administrator\\Desktop\\Auto-GPT-0.4.3\\autogpt\\workspace\\auto_gpt_workspace\\info.txt'}
  Enter 'y' to authorise command, 'y -N' to run N continuous commands, 's' to run self-feedback commands, 'n' to exit program, or enter feedback for InfoOrganizerGPT...
  Asking user via keyboard...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-=
  Text length: 5506 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 1 / 3 of length 2739 tokens
SYSTEM:  Command read_file returned: Error: 'NoneType' object has no attribute 'fast_llm_model'

**Comment by zulupalm98** [comment]
same error here
