### ISSUE TITLE
I keep typing python3 -m autogpt but it keeps saying that it doesn't have my API key

### ISSUE THREAD

**Issue by deweyj21** [Significant-Gravitas/Auto-GPT#4861]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Installation and setup

### Describe your issue.

I've installed autogpt
I've installed python
I have vscode with my api key inside of it
![Screen Shot 2023-07-01 at 6 34 51 PM](https://github.com/Significant-Gravitas/Auto-GPT/assets/138299453/36be5148-c9f2-45fa-ac0c-8c3e3ad894c3)
When I try to run I keep getting this message

**Comment by john-the-dev** [comment]
You need to put the api key in an .env file, which is a copy of .env.template. Then replace line 8 with your actual API key

**Comment by collijk** [comment]
Please see the setup instructions [here](https://docs.agpt.co/setup/#configuration) to make sure your api key is put in the right place.
