### ISSUE TITLE
Switch out OpenAI LLM Hosting provider for another backend

### ISSUE THREAD

**Issue by jamesdhope** [Significant-Gravitas/Auto-GPT#4873]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Allow a backend other than OpenAI.

### Examples 🌈

None seen,

### Motivation 🔦

OpenAI is not suitable for all backends.

**Comment by Boostrix** [comment]
this is one of the most frequently requested features, there's at least 20+ different issues/tickets about this - so you clearly did NOT search existing tickets.
