### ISSUE TITLE
GPT-4 is now widely available to paying API customers

### ISSUE THREAD

**Issue by thedreamakeem** [Significant-Gravitas/Auto-GPT#4898]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

AI Model Limitations

### Describe your issue.

GPT- 4 API is now available to all paying customers according to this OpenAI [tweet](https://twitter.com/OpenAI/status/1677029947544838144?t=OeqfciQNtWKOAq2u46peuw&s=19)  Non paying customers (or new customers using OpenAi API "trail") will be getting an error saying "the model Gpt-4 does not exist" until they've used up all of their trail money (at least for now).

According to Boostrix(Discord) "this may impact some of our default settings/preferences
<img width="580" alt="Screen Shot 2023-07-06 at 2 06 43 PM" src="https://github.com/Significant-Gravitas/Auto-GPT/assets/137110217/620e5c38-373a-41a7-8aab-8d4868908d9d">
"

**Comment by Pwuts** [comment]
GPT-4 was made the default model used by the agent in #4899 :)
