### ISSUE TITLE
What is the best system to test REST APIs ? 

### ISSUE THREAD

**Issue by merwanehamadi** [Significant-Gravitas/Auto-GPT#4911]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Hi,
In the context of our [Benchmark](https://github.com/Significant-Gravitas/Auto-GPT-Benchmarks), we want to test whether an agent is able to build an application.

A big part of building these applications is to expose an API, and we can probably start with REST APIs because it's very common and widely adopted.

This means we want to be able to KNOW whether a given agent has successfully built the REST API we defined using words.

To know this, we're going to build tests for each of the APIs we ask our agent to build.

So now we have this problem:  How do we industrialize the creation of REST APIs tests ?
I want to be clear here: we don't want to build REST APIs. This is the role of the agent. We want to test whether this REST API satisfies the requirements we wrote in english.

Here is how we will decide the best tool to use to industrialize our REST API testing suite: 
- no code to write these tests. Or as little code as possible !
- JSON based.
- easy to use
- easy to run
- easy to teach
- ideally, a tool many QA engineers or web developers already know.

Currently I am thinking of Postman. 

I would like to get more opinions on this topic.

I also would like to get other options and use this thread as an opportunity to connect with someone from the Postman team in order to understand if our use case makes sense.

### Examples 🌈

Here is what I am picturing: 
Step 1: the challenge creator (aka the person who writes the test of the REST API) goes on postman and creates a series of mocked requests/responses that define how the system should behave. For example in the case of a url shortener, we wil: 
- have a setup phase where we host a url in the web or in a sandbox. And this url should point to a certain content
- send the url to the URL shortener and get back a url
- get the shortened url and make sure it redirects to the original url.
Step 2: export these requests/responses as a POSTMAN collection.
Step 3: put this postman collection into our benchmark repo.
Step 4: push this to github and review.
Step 5: someone is now able to run this challenge: we ask an agent to build a url shortener, where for the agent to finish, run the postman collection and gives a score to the application that has been built based on whether the expected responses comply with a url shortener.

**Comment by talktotrey** [comment]
@merwanehamadi Great Idea!  I really like this as a testable solution to a "small build".  I have unsuccessfully tried to write code w/ GPT but my projects were probably too large and my coding knowledge too small.  This sounds reasonable.
