### ISSUE TITLE
Command browse_website returned: Error: summarize_text() missing 1 required positional argument: 'config'

### ISSUE THREAD

**Issue by NeonN3mesis** [Significant-Gravitas/Auto-GPT#4917]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Master (branch)

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Commands

### Describe your issue.

V0.4.4 pre release

Command browse_website returned: Error: summarize_text() missing 1 required positional argument: 'config'

Logs: https://autogpt.e2b.dev/?logFileID=907f001c-73a7-463a-9f3e-7b4efa283f4e&selectedLog=17

**Comment by Anti27** [comment]
same here in V0.4.3
Command read_file returned: Error: summarize_text() missing 1 required positional argument: 'config'

**Comment by ermanakar** [comment]
Same here on 

'
NEXT ACTION:  COMMAND = browse_website ARGUMENTS = {'url': 'https://www.reddit.com/r/NoSleep/', 'question': 'What are the top stories on the NoSleep subreddit?'}
  Enter 'y' to authorise command, 'y -N' to run N continuous commands, 's' to run self-feedback commands, 'n' to exit program, or enter feedback for HorrorStoryGPT...
  Asking user via keyboard...
Input:y -5
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
  Text length: 36920 characters
  Text length: 3892 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 1 / 3 of length 1965 tokens
  Text length: 1870 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 2 / 3 of length 1940 tokens
  Text length: 1840 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 3 / 3 of length 284 tokens
  Text length: 270 tokens
  Max chunk length: 3545 tokens
  Summarized 3 chunks
  Text length: 194 tokens
  Max chunk length: 3545 tokens
  Text length: 3912 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 1 / 3 of length 1950 tokens
  Text length: 1850 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 2 / 3 of length 1942 tokens
  Text length: 1846 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 3 / 3 of length 251 tokens
  Text length: 247 tokens
  Max chunk length: 3545 tokens
  Summarized 3 chunks
  Text length: 196 tokens
  Max chunk length: 3545 tokens
  Text length: 517 tokens
  Max chunk length: 3545 tokens
SYSTEM:  Command browse_website returned: Error: summarize_text() missing 1 required positional argument: 'config'
'

**Comment by Whizcraft** [comment]
I have the same thing with the same parameters:

-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-=
  Text length: 7834 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 1 / 5 of length 2521 tokens
  Text length: 2516 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 2 / 5 of length 2894 tokens
  Text length: 2894 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 3 / 5 of length 2197 tokens
  Text length: 2195 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 4 / 5 of length 2614 tokens
  Text length: 2588 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 5 / 5 of length 847 tokens
  Text length: 839 tokens
  Max chunk length: 3545 tokens
  Summarized 5 chunks
  Text length: 177 tokens
  Max chunk length: 3545 tokens
  Text length: 7782 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 1 / 4 of length 2588 tokens
  Text length: 2529 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 2 / 4 of length 2569 tokens
  Text length: 2530 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 3 / 4 of length 2584 tokens
  Text length: 2539 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 4 / 4 of length 343 tokens
  Text length: 326 tokens
  Max chunk length: 3545 tokens
  Summarized 4 chunks
  Text length: 229 tokens
  Max chunk length: 3545 tokens
  Text length: 7795 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 1 / 4 of length 2544 tokens
  Text length: 2509 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 2 / 4 of length 2612 tokens
  Text length: 2538 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 3 / 4 of length 2654 tokens
  Text length: 2618 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 4 / 4 of length 990 tokens
  Text length: 985 tokens
  Max chunk length: 3545 tokens
  Summarized 4 chunks
  Text length: 265 tokens
  Max chunk length: 3545 tokens
  Text length: 7773 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 1 / 4 of length 2614 tokens
  Text length: 2551 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 2 / 4 of length 2448 tokens
  Text length: 2430 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 3 / 4 of length 2632 tokens
  Text length: 2594 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 4 / 4 of length 905 tokens
  Text length: 888 tokens
  Max chunk length: 3545 tokens
  Summarized 4 chunks
  Text length: 332 tokens
  Max chunk length: 3545 tokens
  Text length: 7803 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 1 / 4 of length 2667 tokens
  Text length: 2633 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 2 / 4 of length 2533 tokens
  Text length: 2497 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 3 / 4 of length 2597 tokens
  Text length: 2556 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 4 / 4 of length 436 tokens
  Text length: 419 tokens
  Max chunk length: 3545 tokens
  Summarized 4 chunks
  Text length: 223 tokens
  Max chunk length: 3545 tokens
  Text length: 7778 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 1 / 4 of length 2682 tokens
  Text length: 2612 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 2 / 4 of length 2618 tokens
  Text length: 2587 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 3 / 4 of length 2619 tokens
  Text length: 2578 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 4 / 4 of length 572 tokens
  Text length: 569 tokens
  Max chunk length: 3545 tokens
  Summarized 4 chunks
  Text length: 183 tokens
  Max chunk length: 3545 tokens
  Text length: 7816 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 1 / 4 of length 2602 tokens
  Text length: 2570 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 2 / 4 of length 2517 tokens
  Text length: 2474 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 3 / 4 of length 2559 tokens
  Text length: 2524 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 4 / 4 of length 302 tokens
  Text length: 301 tokens
  Max chunk length: 3545 tokens
  Summarized 4 chunks
  Text length: 279 tokens
  Max chunk length: 3545 tokens
  Text length: 7805 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 1 / 4 of length 2676 tokens
  Text length: 2658 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 2 / 4 of length 2695 tokens
  Text length: 2634 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 3 / 4 of length 2560 tokens
  Text length: 2532 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 4 / 4 of length 655 tokens
  Text length: 652 tokens
  Max chunk length: 3545 tokens
  Summarized 4 chunks
  Text length: 247 tokens
  Max chunk length: 3545 tokens
  Text length: 7702 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 1 / 4 of length 2564 tokens
  Text length: 2503 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 2 / 4 of length 2525 tokens
  Text length: 2477 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 3 / 4 of length 2580 tokens
  Text length: 2541 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 4 / 4 of length 308 tokens
  Text length: 305 tokens
  Max chunk length: 3545 tokens
  Summarized 4 chunks
  Text length: 262 tokens
  Max chunk length: 3545 tokens
  Text length: 7774 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 1 / 4 of length 2546 tokens
  Text length: 2510 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 2 / 4 of length 2641 tokens
  Text length: 2602 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 3 / 4 of length 2577 tokens
  Text length: 2538 tokens
  Max chunk length: 3545 tokens
DOUBLE CHECK CONFIGURATION  Please double check that you have setup a PAID OpenAI API Account. You can read more here: https://docs.agpt.co/setup/#getting-an-api-key
  Summarizing chunk 4 / 4 of length 517 tokens
  Text length: 513 tokens
  Max chunk length: 3545 tokens
  Summarized 4 chunks
  Text length: 227 tokens
  Max chunk length: 3545 tokens
  Text length: 7831 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 1 / 4 of length 2611 tokens
  Text length: 2571 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 2 / 4 of length 2604 tokens
  Text length: 2552 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 3 / 4 of length 2613 tokens
  Text length: 2541 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 4 / 4 of length 202 tokens
  Text length: 201 tokens
  Max chunk length: 3545 tokens
  Summarized 4 chunks
  Text length: 208 tokens
  Max chunk length: 3545 tokens
  Text length: 7726 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 1 / 4 of length 2995 tokens
  Text length: 2969 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 2 / 4 of length 2477 tokens
  Text length: 2453 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 3 / 4 of length 2528 tokens
  Text length: 2479 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 4 / 4 of length 938 tokens
  Text length: 923 tokens
  Max chunk length: 3545 tokens
  Summarized 4 chunks
  Text length: 246 tokens
  Max chunk length: 3545 tokens
  Text length: 7721 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 1 / 4 of length 2562 tokens
  Text length: 2529 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 2 / 4 of length 2601 tokens
  Text length: 2544 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 3 / 4 of length 2577 tokens
  Text length: 2536 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 4 / 4 of length 398 tokens
  Text length: 385 tokens
  Max chunk length: 3545 tokens
  Summarized 4 chunks
  Text length: 286 tokens
  Max chunk length: 3545 tokens
  Text length: 7832 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 1 / 4 of length 2600 tokens
  Text length: 2576 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 2 / 4 of length 2606 tokens
  Text length: 2563 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 3 / 4 of length 2569 tokens
  Text length: 2538 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 4 / 4 of length 643 tokens
  Text length: 639 tokens
  Max chunk length: 3545 tokens
  Summarized 4 chunks
  Text length: 235 tokens
  Max chunk length: 3545 tokens
  Text length: 7751 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 1 / 4 of length 2590 tokens
  Text length: 2533 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 2 / 4 of length 2598 tokens
  Text length: 2549 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 3 / 4 of length 2588 tokens
  Text length: 2531 tokens
  Max chunk length: 3545 tokens
DOUBLE CHECK CONFIGURATION  Please double check that you have setup a PAID OpenAI API Account. You can read more here: https://docs.agpt.co/setup/#getting-an-api-key
  Summarizing chunk 4 / 4 of length 261 tokens
  Text length: 244 tokens
  Max chunk length: 3545 tokens
  Summarized 4 chunks
  Text length: 299 tokens
  Max chunk length: 3545 tokens
  Text length: 7722 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 1 / 4 of length 2573 tokens
  Text length: 2488 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 2 / 4 of length 2523 tokens
  Text length: 2493 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 3 / 4 of length 2607 tokens
  Text length: 2568 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 4 / 4 of length 292 tokens
  Text length: 284 tokens
  Max chunk length: 3545 tokens
  Summarized 4 chunks
  Text length: 314 tokens
  Max chunk length: 3545 tokens
  Text length: 7747 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 1 / 4 of length 2579 tokens
  Text length: 2535 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 2 / 4 of length 2563 tokens
  Text length: 2523 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 3 / 4 of length 2682 tokens
  Text length: 2635 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 4 / 4 of length 454 tokens
  Text length: 450 tokens
  Max chunk length: 3545 tokens
  Summarized 4 chunks
  Text length: 248 tokens
  Max chunk length: 3545 tokens
  Text length: 7757 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 1 / 4 of length 2567 tokens
  Text length: 2527 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 2 / 4 of length 2525 tokens
  Text length: 2434 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 3 / 4 of length 2559 tokens
  Text length: 2530 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 4 / 4 of length 654 tokens
  Text length: 651 tokens
  Max chunk length: 3545 tokens
  Summarized 4 chunks
  Text length: 282 tokens
  Max chunk length: 3545 tokens
  Text length: 7693 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 1 / 4 of length 2616 tokens
  Text length: 2556 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 2 / 4 of length 2580 tokens
  Text length: 2543 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 3 / 4 of length 2485 tokens
  Text length: 2426 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 4 / 4 of length 378 tokens
  Text length: 367 tokens
  Max chunk length: 3545 tokens
  Summarized 4 chunks
  Text length: 253 tokens
  Max chunk length: 3545 tokens
  Text length: 7737 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 1 / 4 of length 2547 tokens
  Text length: 2472 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 2 / 4 of length 2670 tokens
  Text length: 2610 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 3 / 4 of length 2534 tokens
  Text length: 2482 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 4 / 4 of length 538 tokens
  Text length: 525 tokens
  Max chunk length: 3545 tokens
  Summarized 4 chunks
  Text length: 208 tokens
  Max chunk length: 3545 tokens
  Text length: 7738 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 1 / 4 of length 2673 tokens
  Text length: 2622 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 2 / 4 of length 2570 tokens
  Text length: 2484 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 3 / 4 of length 2581 tokens
  Text length: 2514 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 4 / 4 of length 482 tokens
  Text length: 472 tokens
  Max chunk length: 3545 tokens
  Summarized 4 chunks
  Text length: 266 tokens
  Max chunk length: 3545 tokens
  Text length: 7882 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 1 / 4 of length 2479 tokens
  Text length: 2441 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 2 / 4 of length 2615 tokens
  Text length: 2579 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 3 / 4 of length 2625 tokens
  Text length: 2565 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 4 / 4 of length 511 tokens
  Text length: 504 tokens
  Max chunk length: 3545 tokens
  Summarized 4 chunks
  Text length: 267 tokens
  Max chunk length: 3545 tokens
  Text length: 7764 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 1 / 4 of length 2573 tokens
  Text length: 2530 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 2 / 4 of length 2574 tokens
  Text length: 2525 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 3 / 4 of length 2581 tokens
  Text length: 2525 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 4 / 4 of length 244 tokens
  Text length: 225 tokens
  Max chunk length: 3545 tokens
  Summarized 4 chunks
  Text length: 297 tokens
  Max chunk length: 3545 tokens
  Text length: 7753 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 1 / 4 of length 2583 tokens
  Text length: 2503 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 2 / 4 of length 2460 tokens
  Text length: 2375 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 3 / 4 of length 2574 tokens
  Text length: 2531 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 4 / 4 of length 380 tokens
  Text length: 371 tokens
  Max chunk length: 3545 tokens
  Summarized 4 chunks
  Text length: 286 tokens
  Max chunk length: 3545 tokens
  Text length: 7887 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 1 / 4 of length 2629 tokens
  Text length: 2562 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 2 / 4 of length 3076 tokens
  Text length: 3075 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 3 / 4 of length 3545 tokens
  Text length: 3233 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 4 / 4 of length 2474 tokens
  Text length: 2468 tokens
  Max chunk length: 3545 tokens
  Summarized 4 chunks
  Text length: 153 tokens
  Max chunk length: 3545 tokens
  Text length: 6006 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 1 / 2 of length 3148 tokens
  Text length: 3138 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 2 / 2 of length 3349 tokens
  Text length: 3340 tokens
  Max chunk length: 3545 tokens
  Summarized 2 chunks
  Text length: 56 tokens
  Max chunk length: 3545 tokens
SYSTEM:  Command read_file returned: Error: summarize_text() missing 1 required positional argument: 'config'

**Comment by WyldKnyght** [comment]
I'm using docker, 0.4.3, and getting the same error when autoGPT uses command  browse_website

Sample
  Text length: 24593 characters
  Text length: 5035 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 1 / 3 of length 2528 tokens
  Text length: 2419 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 2 / 3 of length 2509 tokens
  Text length: 2407 tokens
  Max chunk length: 3545 tokens
  Summarizing chunk 3 / 3 of length 309 tokens
  Text length: 304 tokens
  Max chunk length: 3545 tokens
  Summarized 3 chunks
SYSTEM:  Command browse_website returned: Error: summarize_text() missing 1 required positional argument: 'config'

**Comment by collijk** [comment]
Should be fixed in #4876 and released in 0.4.4
