### ISSUE TITLE
Support image_size for generate_image command

### ISSUE THREAD

**Issue by JeremyFabrikapp** [Significant-Gravitas/Auto-GPT#492]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Command Generate Image "generate_image" is a great addition. However the image size is hardcoded,
I propose the issue to make it controllable with an optional argument image_size.

Pitfalls : 

- Dalle has only 3 sizes "256x256", "512x512", "1024x1024".
- StableDiffusion works with multiple of 8 as valid size, but image may suffer loss of context > 512px.
- image_size argument should be optional and not make it more complicated to generate an image without specifying the size. 

### Examples 🌈

- Stable Diffusion Replica, size can be changed
https://replicate.com/stability-ai/stable-diffusion

- Dall-e API
https://platform.openai.com/docs/api-reference/images/create#images/create-size

### Motivation 🔦

This will help the user to generate an image at the needed size.

I will push a PR in that direction.

**Comment by edcohen08** [comment]
This can be closed by https://github.com/Significant-Gravitas/Auto-GPT/pull/1477 right?

**Comment by JeremyFabrikapp** [comment]
Yes @edcohen08 it's been implemented I'll close the issue !
