### ISSUE TITLE
Workflow diagram of AutoGPT

### ISSUE THREAD

**Issue by jayaffine** [Significant-Gravitas/Auto-GPT#4945]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Documentation

### Describe your issue.

I have been trying to understand the workflow of AutoGPT and the issue with many of the resources available is that they mix up the workflows of BabyAGI and AutoGPT.

A clear understanding of the logic will help not just me, but also a lot of AI enthusiasts.

**Comment by egavrev** [comment]
[jayaffine](https://github.com/jayaffine) Have you checked the last release notes, there is an updated flow diagram according to the last architecture update. https://github.com/Significant-Gravitas/Auto-GPT/issues/4770
it might be something that you are looking for [Planned Agent Workflow](https://whimsical.com/agent-workflow-v2-NmnTQ8R7sVo7M3S43XgXmZ)

**Comment by collijk** [comment]
This is the [existing agent flow](https://whimsical.com/agent-workflow-VAzeKcup3SR7awpNZJKTyK) agent flow and this is the [flow we're working on](https://whimsical.com/agent-workflow-v2-NmnTQ8R7sVo7M3S43XgXmZ).  We'll get the final version of the new workflow into public facing and more easily accessible documentation as we finish it up.

**Comment by chymian** [comment]
@collijk 
james, the links ar no longer working.
