### ISSUE TITLE
Fail embedding on Azure OpenAI

### ISSUE THREAD

**Issue by Lerty** [Significant-Gravitas/Auto-GPT#4974]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Agents

### Describe your issue.

Always stuck in screen like this after 1st web browering (Azure GPT is answering fine, but not sure Azure Embedding)
I checked deployment name, it's correct.

![image](https://github.com/Significant-Gravitas/Auto-GPT/assets/17094974/8d5df0ff-97d4-44c6-b441-65a5f758d6d1)

**Comment by SpeedxDevil** [comment]
Input 'exit' into the prompt and hit Enter to continue. The browse_website action will have failed but at least you can continue. I just experienced the same issue on Ubuntu 22.04 running in the latest docker image with Azure OpenAI.
