### ISSUE TITLE
execute_python_file fails to run on windows and the workspace folder is mounted read-only

### ISSUE THREAD

**Issue by sohrabsaran** [Significant-Gravitas/Auto-GPT#4975]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Commands

### Describe your issue.

I checkout Auto-GPT repository, switch to stable branch, and try to run it on my windows machine without using Docker.
But execute_python_file tries to execute non-existent code file.
Upon investigation, this is because the generated path has windows back-slash characters that need to be replaced with unix forward-slash characters instead.
In addition, the workspace folder is mounted read-only, the need for such caution is not clear, rather it limits the ability of the command run inside the docker image, from making any changes to the filesystem. This seems to be a severe limitation.

**Comment by eyalk11** [comment]
There is possibly related commit recently added. Did you try master? 
Anyway, was there a specific error?

**Comment by sohrabsaran** [comment]
> There is possibly related commit recently added. Did you try master? Anyway, was there a specific error?

updated the description of this bug and added a PR

**Comment by Pwuts** [comment]
This should be two separate issues:
1. execute_python_file fails to run on windows
2. the workspace folder is mounted read-only

**Comment by Pwuts** [comment]
Should be fixed in #4996
