### ISSUE TITLE
can't install packages 

### ISSUE THREAD

**Issue by DanielYedayev** [Significant-Gravitas/Auto-GPT#4978]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Other

### Describe your issue.

When i press run and it needs to download the plugins it won't do it. 

### Upload Error Log Content

![‏‏צילום מסך (1)](https://github.com/Significant-Gravitas/Auto-GPT/assets/109751426/3ac606de-1b0c-4784-afad-4379f5ea1fdc)
![‏‏צילום מסך (3)](https://github.com/Significant-Gravitas/Auto-GPT/assets/109751426/5bf1dda3-6745-431b-b311-d6063523c8d2)

**Comment by eyalk11** [comment]
You should run pip install -r requirments.txt
