### ISSUE TITLE
cannot join Discord Server

### ISSUE THREAD

**Issue by markcam1** [Significant-Gravitas/Auto-GPT#4991]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

I have not been able to join the discord server for more than a month. 
Message: Unable to accept invite. 

This is frustrating.

**Comment by ntindle** [comment]
What link are you using?

**Comment by SwordKnives** [comment]
If you are getting the server link by discord, it may have been expired

Here try this one:
https://discord.gg/autogpt

**Comment by markcam1** [comment]
> 

https://discord.com/invite/autogpt

**Comment by ntindle** [comment]
That works fine for me. Is there an error message you’re getting?

**Comment by markcam1** [comment]
![image](https://github.com/Significant-Gravitas/Auto-GPT/assets/32405690/64573734-2776-4897-89d7-ef27aa7724ad)

**Comment by markcam1** [comment]
> What link are you using?

Tried both:

- https://discord.com/invite/autogpt

- https://discord.gg/autogpt

Same message. Has anyone seen this before?

**Comment by ntindle** [comment]
What happens when you hit “join” anyway?

**Comment by markcam1** [comment]
> What happens when you hit “join” anyway?

Screen refreshes with the same message: 


![image](https://github.com/Significant-Gravitas/Auto-GPT/assets/32405690/87cb94a1-1777-4ff4-aa73-01b08e0cae01)

**Comment by ntindle** [comment]
Cannot replicate
