### ISSUE TITLE
Agency research instead of commands

### ISSUE THREAD

**Issue by thejerome1502** [Significant-Gravitas/Auto-GPT#503]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Replace Google Search by an agency (coop of agents) to search both Google and pinecone memory from a prompt sent by autogpt to this agency 

Uses multiple instances of a GPT-3.5 model to generate tags for each search engine (e.g., Pinecone and Google) based on the user prompt.
Uses the generated tags to query Pinecone database and Google Search API for the top results relevant to the user prompt.
Uses a GPT-3.5 summarization and organization model to identify the top 5 most relevant search results from Pinecone database and Google Search API, respectively.
Uses a GPT-3.5 summarization and organization model to summarize and organize the search results from Pinecone database and Google Search API in relevance to the user prompt.
Combines the summarized and organized search results from both sources using a GPT-3.5 model.
Outputs it to autogpt

**Comment by Boostrix** [comment]
my 2c: supporting multiple search engines does sound like a good idea, ideally those with an API and a way to return results in a suitable format like JSON/XML - also, being able to search headless without requiring a headless browser would be useful, just the equivalent of curl/wget (wrapped via Python) should suffice ideally
