### ISSUE TITLE
ChatGPT Auth Token

### ISSUE THREAD

**Issue by superfastisfast** [Significant-Gravitas/Auto-GPT#5082]
### Duplicates

- [x] I have searched the existing issues

### Summary 💡

**Its very easy to get [and free]**

### Examples 🌈

1. press `[F12]` or `[CTRL+SHIFT+I]` on your keyboard.
2. go to the applications tab in the `Developer Tools` window.
3. search for `__Secure-next-auth.session-token` copy it then paste it then paste it into the config.

### Motivation 🔦

Its fairly easy to implement too! [right?]

**Comment by jojo2massol** [comment]
Duplicate #3767 isn't it ?

**Comment by ntindle** [comment]
Duplicate
