### ISSUE TITLE
I'm stuck in the installation process,need help!!

### ISSUE THREAD

**Issue by isaac-gonzo** [Significant-Gravitas/Auto-GPT#5097]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

Its not finding the file. 

### Upload Error Log Content

(auto-gpt) PS C:\Users\mmg08\OneDrive\Desktop\AutoGPT> pip install -r requirements.txt
Collecting en-core-web-sm@ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.5.0/en_core_web_sm-3.5.0-py3-none-any.whl (from -r requirements.txt (line 30))
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.5.0/en_core_web_sm-3.5.0-py3-none-any.whl (12.8 MB)
     -------------------------- 12.8/12.8 MB 2.2 MB/s eta 0:00:00
Collecting auto-gpt-plugin-template@ git+https://github.com/Significant-Gravitas/Auto-GPT-Plugin-Template@0.1.0 (from -r requirements.txt (line 47))
  Cloning https://github.com/Significant-Gravitas/Auto-GPT-Plugin-Template (to revision 0.1.0) to c:\users\mmg08\appdata\local\temp\pip-install-h1bfzp8s\auto-gpt-plugin-template_08c3d07f855b417489b340486796a6fc
  ERROR: Error [WinError 2] The system cannot find the file specified while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

**Comment by SwordKnives** [comment]
Looking at the error, did you download git in your Windows?

Download git for Windows here: https://git-scm.com/download/win

**Comment by isaac-gonzo** [comment]
shit thank you i got it done.
