### ISSUE TITLE
\' in JS code breaks the JSON string decoder

### ISSUE THREAD

**Issue by MileyHollenberg** [Significant-Gravitas/Auto-GPT#511]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

AI Name: GameDev-GPT

Describe your AI's role:  For example, 'an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.'
GameDev-GPT is: A game developer able to create browser games with HTML, Javascript and CSS. They use basic graphics and are focused on games played in Firefox on a desktop computer

Enter up to 5 goals for your AI:  For example: Increase net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously'
Enter nothing to load defaults, enter nothing when finished.
Goal 1: Create a game design document for a game of Pong
Goal 2: Write the code for the game
Goal 3: Add unit tests to validate that the code is working
Goal 4: Write all the files to disk
Goal 5: Shutdown when complete

### Current behavior 😯

The reason it's failing is because it's trying to set the `fillStyle` of the context to `\'white\'` which has a single backslash to it in the output already but fails to get parsed by standard JSON parsers. It should be `'white'` in this context (the code itself is encapsulated between double quotes and thus unaffected by single quotes, yet GPT-4 still added the back-tick most likely due to it recognizing that strings within strings wouldn't work in most cases).

Current full output that broke the system:

`{ "thoughts": { "text": "Now that I have defined the game environment and variables, I can start writing the code to update the ball and paddles. This will involve combining the draw and update functions for the ball and paddles so that they canbe updated on each frame. I will also need to add collision detection to ensure that the ball bounces off the paddles and walls as intended.", "reasoning": "By combining the draw and update functions into a single function for each object, I can simplify the code and better manage the game state. Adding collision detection is crucial to ensure that the gameplay is accurate and consistent.", "plan": "- Combine the ball and paddle draw and update functions\n- Add collision detection for paddles and walls\n- Test the game mechanics thoroughly", "criticism": "I should be careful to test each addition thoroughly to make sure that they are working as intended. I should also be aware of potential issues that may arise from combining the draw and update functions and plan accordingly.", "speak": "Now it's time to update the ball and paddles in the game environment. I'll combine the draw and update functions for each object and add collision detection to ensure that the gameplay isaccurate. I'll be sure to thoroughly test each addition as I go." }, "command": { "name":"write_to_file", "args": { "file":"pong_code.js", "text": "// Pong Game Code\n\n// Global variables\nvar canvas = document.getElementById('game-canvas');\nvarcontext = canvas.getContext('2d');\n\nvar ball = {\n x: canvas.width/2,\n y: canvas.height/2,\n dx: 5,\n dy: 5,\n radius: 10\n};\nvar paddle1 = {\n x: 50,\n y: canvas.height/2 - 70,\n width: 10,\n height: 140,\n dy: 0\n};\nvar paddle2 = {\n x: canvas.width - 60,\n y: canvas.height/2 - 70,\n width: 10,\n height: 140,\n dy: 0\n};\n\n// Ball functions\nfunction updateBall(){\n ball.x += ball.dx;\n ball.y += ball.dy;\n // Check for wall collisions\n if(ball.y + ball.radius > canvas.height || ball.y - ball.radius < 0){\n ball.dy = - ball.dy;\n }\n // Check for paddle collisions\n if(ball.x + ball.radius > paddle2.x && ball.y > paddle2.y && ball.y < paddle2.y + paddle2.height || ball.x - ball.radius < paddle1.x + paddle1.width && ball.y> paddle1.y && ball.y < paddle1.y + paddle1.height){\n ball.dx = - ball.dx;\n }\n}\n\nfunction drawBall(){\n context.beginPath();\n context.arc(ball.x, ball.y, ball.radius, 0, Math.PI*2);\n context.fillStyle = \\'white\\';\n context.fill();\n context.closePath();\n}\n\n// Paddle functions\nfunction updatePaddle1(){\n paddle1.y += paddle1.dy;\n // Check for wall collisions\n if(paddle1.y + paddle1.height > canvas.height || paddle1.y < 0){\n paddle1.dy = - paddle1.dy;\n }\n}\n\nfunction updatePaddle2(){\n paddle2.y += paddle2.dy;\n // Check for wall collisions\n if(paddle2.y + paddle2.height > canvas.height || paddle2.y < 0){\n paddle2.dy = - paddle2.dy;\n }\n}\n\nfunction drawPaddle1(){\n context.beginPath();\n context.rect(paddle1.x, paddle1.y, paddle1.width, paddle1.height);\n context.fillStyle = \'white\';\n context.fill();\n context.closePath();\n}\n\nfunction drawPaddle2(){\n context.beginPath();\n context.rect(paddle2.x, paddle2.y, paddle2.width, paddle2.height);\n context.fillStyle = \\'white\\';\n context.fill();\n context.closePath();\n}\n\n// Main function\nfunction mainLoop(){\n context.clearRect(0, 0, canvas.width, canvas.height);\n updateBall();\n updatePaddle1();\n updatePaddle2();\n drawBall();\n drawPaddle1();\n drawPaddle2();\n}\n\n// Event Listeners\ndocument.addEventListener('keydown', function(event) {\n // Listening for keyboard inputs here\n});\n" } } }`

There are 3 instances where `\'white\'` is being used, changing those to `'white'` fixes the JSON issue. 

### Expected behavior 🤔

That GPT-4 doesn't output invalid JSON data when writing code.

There's two ways I see this could be fixed, one would be by adjusting the input prompt to tell it not to add a `\` character to single quotes. The other way would be to add an extra step for when the JSON decoding fails to check and see if there may be instances of `\'` and resolve them (potentially ask the user as well to be sure this could be the fix for the current output)

### Your prompt 📝

All prompts used written above, using commit `7e108d8ab37d828c3d7b129399d8d9927154f801` which is the latest at this point in time for me.

**Comment by Qoyyuum** [comment]
Hi @MileyHollenberg can you try again with the latest stable release and see if the issue is fixed? Interesting case here.

**Comment by lc0rp** [comment]
Merging *most* JSON issues here: #1407
