### ISSUE TITLE
PLAN: Never uses generate_image, even though IMAGE_PROVIDER is set to dalle

### ISSUE THREAD

**Issue by dmoham1476** [Significant-Gravitas/Auto-GPT#5135]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of Auto-GPT are you using?

Stable (branch)

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

Generate an image of a cat using generate_image

This always goes to web_search and never goes to generate_image

My .env file
## IMAGE_PROVIDER - Image provider (Default: dalle)
IMAGE_PROVIDER=dalle

## IMAGE_SIZE - Image size (Default: 256)
IMAGE_SIZE=256

**Comment by Blogbotana** [comment]
Man, the same problem. 
![image](https://github.com/Significant-Gravitas/Auto-GPT/assets/69924139/925e807a-2f6f-4022-b55f-74a7283aa481)
I wrote to his cinfiguration use this command and it's invalid

**Comment by dmoham1476** [comment]
https://github.com/Significant-Gravitas/Auto-GPT/pull/5137 - This should
help

**Comment by Pwuts** [comment]
Should be fixed by #5137

**Comment by nawed2611** [comment]
Anyone still facing this issue?

**Comment by Blogbotana** [comment]
> Anyone still facing this issue?

Yes, you need to see other issue https://github.com/Significant-Gravitas/Auto-GPT/pull/5137
