### ISSUE TITLE
no exe in releases

### ISSUE THREAD

**Issue by kittenvr** [Significant-Gravitas/Auto-GPT#5138]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

where do i get exe?

**Comment by Git-Discord** [comment]
bentlybro: there currently isnt a .exe for AutoGPT, id suggest checking out https://docs.agpt.co/setup/ as that has the full setup guide

 - Posted By bentlybro Using The Git-Discord Bot From The AutoGPT Discord

**Comment by Ryoko-hyrosue** [comment]
double click the run.bat to install and run autoGPT, it will ask you to input API key and how many rounds you would like to run the  script.

**Comment by Bentlybro** [comment]
test

**Comment by Git-Discord** [comment]
test
