### ISSUE TITLE
When crawling the net, parse pdf documents as well

### ISSUE THREAD

**Issue by sanesanyo** [Significant-Gravitas/Auto-GPT#514]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

When crawling the web to do market research, a lot of links are sometimes just pdf documents. It would be great if Auto GPT had an inherent ability to parse those pdfs & feed the text for GPT4 to analyse.

### Examples 🌈

- Research on investing in Emerging Markets in 2023 --> The first few hits on Google Search are pdf documents. Auto GPT fails to parse them.

### Motivation 🔦

This way Auto GPT can do the market research task far better than it currently can.

**Comment by Boostrix** [comment]
this would probably be a plugin to use a python pdf parsing library analogous to pdf2text (not sure how to mark/label the issue or if I am lacking permissions to do so)

**Comment by anonhostpi** [comment]
Agreed with @Boostrix on this one. PDF parsing is an extraneous task, and isn't as straightforward as it ought to be. It would be better to assign that to developers who are skilled in PDF parsing.
