### ISSUE TITLE
Incorrect API key provided: your-ope*******-key. 

### ISSUE THREAD

**Issue by dudelama** [Significant-Gravitas/Auto-GPT#52]
openai.error.AuthenticationError: Incorrect API key provided: your-ope*******-key. You can find your API key at https://platform.openai.com/account/api-keys.

**Comment by dudelama** [comment]
Getting the above error even though i have a valid API Key, not sure how to check this.

**Comment by dudelama** [comment]
Only workd with GPT - 4 ?

**Comment by Torantulino** [comment]
Please try the following steps for me and report back:

- [ ] Ensure you have a file in the root project directory called ".env". 

- [ ] Ensure it contains your OpenAI key

**Comment by dudelama** [comment]
Yes, I have correctly added this to .env

**Comment by bowu** [comment]
I have the same problem. BTW, I have access to GPT4 APIs.

**Comment by sanity** [comment]
I had the same problem. Turned out I had an old key in my `OPENAI_KEY` environment variable which appears to override whatever is in `.env`.

**Comment by dudelama** [comment]
![image](https://user-images.githubusercontent.com/128497414/229513829-6d660d04-ba00-4444-b5e2-5f3cabd94150.png)
Added correctly

**Comment by dudelama** [comment]
Invalid key error, not able to proceed further, rest all seems working fine.
![image](https://user-images.githubusercontent.com/128497414/229514675-694ff6ab-157b-46f2-81c0-726ac63a0724.png)

**Comment by cvinker** [comment]
![image](https://user-images.githubusercontent.com/13070943/229519835-18c7a606-d5b4-4dc8-b405-bebc5e6a9302.png)
Same issue as @dudelama

**Comment by dudelama** [comment]
This issue is resolved, the ensure you add the key within the ' ', alternatively add a keys.py and add the same what you added in the .py. What a silly mistake i have made.

**Comment by ZeyadKm** [comment]
> This issue is resolved, the ensure you add the key within the ' ', alternatively add a keys.py and add the same what you added in the .py. What a silly mistake i have made.

Same issue but I don't understand. Elaborate please?

**Comment by The-Amazing-Coder** [comment]
he said add your api key as you did in .env as whatever it was is script.py and main.py

**Comment by The-Amazing-Coder** [comment]
> This issue is resolved, the ensure you add the key within the ' ', alternatively add a keys.py and add the same what you added in the .py. What a silly mistake i have made.

what do you mean by that

**Comment by richbeales** [comment]
closing as OP indicates it's resolved
