### ISSUE TITLE
Warning, you do not have access to gpt-4

### ISSUE THREAD

**Issue by mlevin2** [Significant-Gravitas/Auto-GPT#5207]
Someone closed issue #4765, but I don't think it is actually resolved. I can't seem to get past it.

**Comment by Bentlybro** [comment]
according to [openai](https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4) "On July 6, 2023, we gave access to the GPT-4 API (8k) to all API users who have made a successful payment of $1 or more. We plan to open up access to all developers soon, and then start raising rate-limits after that depending on compute availability."
