### ISSUE TITLE
agent protocol not found while pip installation

### ISSUE THREAD

**Issue by IAMSHIVATRIPATHI** [Significant-Gravitas/Auto-GPT#5244]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

ERROR: Could not find a version that satisfies the requirement agent-protocol>=0.1.1 (from versions: none)
ERROR: No matching distribution found for agent-protocol>=0.1.1

everytime this happens while other package are installed sucessfully
its manual intallation is not available on pypi

**Comment by seba90** [comment]
https://github.com/AI-Engineers-Foundation/agent-protocol/issues/61#issuecomment-1722311767

Its already reported in their GitHub project. 
Lets see how long it will take until they reupload the packages again.
Maybe the proposed workaround will work for you.

**Comment by IAMSHIVATRIPATHI** [comment]
Where is the workaround

**Comment by Swiftyos** [comment]
Hi,
Thank you for reporting this.
I've just pushed a fix fort: https://github.com/Significant-Gravitas/Auto-GPT/commit/6d5f93038b307c4805071be82d5ef0222c3b6450

**Comment by IAMSHIVATRIPATHI** [comment]
> [AI-Engineers-Foundation/agent-protocol#61 (comment)](https://github.com/AI-Engineers-Foundation/agent-protocol/issues/61#issuecomment-1722311767)
> 
> Its already reported in their GitHub project. Lets see how long it will take until they reupload the packages again. Maybe the proposed workaround will work for you.

thanks

**Comment by IAMSHIVATRIPATHI** [comment]
> Hi, Thank you for reporting this. I've just pushed a fix fort: [6d5f930](https://github.com/Significant-Gravitas/Auto-GPT/commit/6d5f93038b307c4805071be82d5ef0222c3b6450)

thanks
