### ISSUE TITLE
Auto-GPT ERROR:  No matching distribution found for agent-protocol>=0.1.1

### ISSUE THREAD

**Issue by LeBob1** [Significant-Gravitas/Auto-GPT#5245]
I dont know what i should do. I followed all the steps from the guide. plz help me
The error:  ERROR: Could not find a version that satisfies the requirement agent-protocol>=0.1.1 (from versions: none)
ERROR: No matching distribution found for agent-protocol>=0.1.1

**Comment by leopck** [comment]
same thing here is happening, i think agent-protocol has been removed from pypi, looking at their website they seem to indicate agent-protocol-client but none of them exist:
https://pypi.org/project/agent-protocol-client/0.2.2/
https://pypi.org/project/agent-protocol/

Something is wrong there but i guess we can built this ourselves....

**Comment by leopck** [comment]
Linking the issue on this: https://github.com/AI-Engineers-Foundation/agent-protocol/issues/61

**Comment by Swiftyos** [comment]
Fixed it: https://github.com/Significant-Gravitas/Auto-GPT/commit/6d5f93038b307c4805071be82d5ef0222c3b6450

**Comment by tomtom94** [comment]
In Node.js this mess wouldn't ever have happened ! 

Who should we blame ? pip3 ? python3 ?

**Comment by tomtom94** [comment]
Hi, do we have a crisis unit working on it somewhere ?

@Swiftyos you made a commit straight on master branch ? why not a release ?
