### ISSUE TITLE
Auto-GPT repairing issues on its own

### ISSUE THREAD

**Issue by dvelle** [Significant-Gravitas/Auto-GPT#527]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

I have locally installed Auto-GPT 
within the auto_gpt_workspace - I cloned the Auto-GPT repo
I then asked the AI to look up the outstanding issues and begin to repair them
the AI responded that out of at the time 185 outstanding issues it would focus on issue it could solve quickly

this loop continued as it couldn't seem to write files to the local instance

Version 2

I then asked the AI to search the internet on how it could improve itself 
the AI wanted to install machine learning modules - again it was unable to write to the local repo

I am currently consulting ChatGPT-4 directly to assist this upgrade

### Motivation 🔦

Self-improving Auto-GPT would be awesome and natural next level

**Comment by rafinskipg** [comment]
@dvelle That's great

can you also ask it to rewrite it's source code so if it crashes it  restarts and reloads the state where it left it?

Can you also ask it to rewrite parts of it's system with new languages and compilers? 

And then ask it to replicate itself through internet connection to cloud virtual machines, in self executing scripts that ping the OpenAI api or scan the internet for new versions or similar services to be connected even if destroyed. 


Nightmares

**Comment by Boostrix** [comment]
I mentioned this in another issue, I used a subset of this idea to let it open/read some of its own commands and plugins (copied into the workspace) in order to come up with new ones based on a description, and it worked at least "somewhat" - for instance, telling it to extend gitoperations.py "just works" for 3-4 commands, in conjunction with some URLs and text files for contextual info: https://github.com/Significant-Gravitas/Auto-GPT/issues/15#issuecomment-1528846110

**Comment by Boostrix** [comment]
> I then asked the AI to look up the outstanding issues and begin to repair them
> the AI responded that out of at the time 185 outstanding issues it would focus on issue it could solve quickly

Great, if you also went as far as asking Auto-GPT to look at its open issues, you should probably consider getting involved in an attempt to hook up the github API to Auto-GPT: https://github.com/Significant-Gravitas/Auto-GPT/issues/15#issuecomment-1529117969

The idea being to provide a new set of commands (or a dedicated plugin) to integrate Auto-GPT with its own issue tracking system, inspired by this comment here: https://github.com/Significant-Gravitas/Auto-GPT/issues/1454#issuecomment-1509474337

Once Auto-GPT can download its own issue/pull list in JSON format, it would also be able to apply its own set of heuristics to automatically re-assign/re-label and re-prioritize issues. Given the popularity/fame of the project, that might in fact be the only viable way forward to deal with this degree of activity/followers
