### ISSUE TITLE
Pinecone Initializing

### ISSUE THREAD

**Issue by ItsReversePlays** [Significant-Gravitas/Auto-GPT#529]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

I created a pinecone account and added the API into the script and it automatically generated an index in pinecone but it says that it is initializing. How long will this take? I dont think it is working because it is still in this state. Thanks!

### Current behavior 😯

Not working

### Expected behavior 🤔

active api

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by jonsparks** [comment]
Pinecone isn't affiliated with this project. You will need to contact their support for any service issues.

**Comment by Jefferydo** [comment]
There's a related bug this afternoon
https://status.pinecone.io/

**Comment by kanosy88** [comment]
They are currently investigating an issue in the northamerica-northeast1-gcp region in which some customers are experiencing slow index initialization times.

**Comment by joshyorko** [comment]
Experiencing the same here

**Comment by ItsReversePlays** [comment]
> They are currently investigating an issue in the northamerica-northeast1-gcp region in which some customers are experiencing slow index initialization times.

well they are pretty slow haha

**Comment by james-coder** [comment]
Can someone please ask AutoGPT to modify itself so it's not just hanging forever and displays some sort of feedback to the user when Pinecone is slow to initialize? (I didn't get any feedback when I started AutoGPT, I only say "Initializing..." on their web interface.)

**Comment by ItsReversePlays** [comment]
> Can someone please ask AutoGPT to modify itself so it's not just hanging forever and displays some sort of feedback to the user when Pinecone is slow to initialize? (I didn't get any feedback when I started AutoGPT, I only say "Initializing..." on their web interface.)

The service is slow to initialize rn so we just cant use pinecone until its initialized I believe.

**Comment by sausage4mash** [comment]
still not Initializing 9hrs later :(  northamerica-northeast1-gcp   can i uninstall and select a different region ?

**Comment by englishdz** [comment]
The same issue... stuck at the "Initializing" stage. Is there an alternative solution to make Auto-GPT function properly?

**Comment by sausage4mash** [comment]
it's now saying ScalingUpPodSize  but also stuck

**Comment by EnricoBeltramo** [comment]
Same issue. Isn't possible to use alternatives to Pinecone?

**Comment by Qoyyuum** [comment]
In the current stable release, if Pinecone is not usable, you can switch to using Redis or Local memory. Configurable in `.env` file. Closing issue as no longer relevant. Please create a new one if a different symptom presents itself.
