### ISSUE TITLE
Unknown commands

### ISSUE THREAD

**Issue by SethReed98** [Significant-Gravitas/Auto-GPT#530]
tasking autoGPT with a coding project of any complexity isn't working because many commands result in 'Unknown command' for me. for example I can't create a directory or execute any terminal commands:
SYSTEM:  Command execute_command returned: Unknown command execute_command
SYSTEM:  Command create_directory returned: Unknown command create_directory

I'm still new to this but I followed the installation instructions exactly and I can't figure this problem out.

**Comment by Scn64** [comment]
Yeah, I've noticed the same. Sometimes it works. Sometimes is gives a blank command or just completely makes up a command that doesn't exist in prompt.txt

**Comment by krystian-ai** [comment]
I go the same:
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
SYSTEM:  Command run_commands returned: Unknown command 'run_commands'. Please refer to the 'COMMANDS' list for available commands and only respond in the specified JSON format.

any hints?

**Comment by InitusJames** [comment]
same issue here.

SYSTEM: Command run_commands returned: Unknown command 'run_commands'. Please refer to the 'COMMANDS' list for available commands and only respond in the specified JSON format.

**Comment by sjnt1** [comment]
Bump! Any fix for this?

**Comment by krystian-ai** [comment]
I just used a stable branch and had no problems anymore.

**Comment by blem5000** [comment]
It doesn't work in v0.2.1

**Comment by PWSys** [comment]
Same issue with v0.2.1

**Comment by Snowblaze** [comment]
Bump

**Comment by JeffJassky** [comment]
Same - in my case, coming across it trying to use curl for an API call:

`SYSTEM:  Command curl returned: Unknown command 'curl'. Please refer to the 'COMMANDS' list for available commands and only respond in the specified JSON format.`

**Comment by robgarcav** [comment]
To make it work just set to True the "EXECUTE_LOCAL_COMMANDS" parameter at line 5 of .env file. 
That made master version work for me.

**Comment by ivan-vilches** [comment]
> To make it work just set to True the "EXECUTE_LOCAL_COMMANDS" parameter at line 5 of .env file. That made master version work for me.

worked thanks !!!

**Comment by codingchild2424** [comment]
> To make it work just set to True the "EXECUTE_LOCAL_COMMANDS" parameter at line 5 of .env file. That made master version work for me.

It works! Thanks!

**Comment by coon-126** [comment]
> To make it work just set to True the "EXECUTE_LOCAL_COMMANDS" parameter at line 5 of .env file. That made master version work for me.

Ty you solve the problem :)
