### ISSUE TITLE
Getting enter api key error when I already did 

### ISSUE THREAD

**Issue by SparkAladdin** [Significant-Gravitas/Auto-GPT#535]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

python3 scripts/main.py --continuous 

### Current behavior 😯

if not cfg.pinecone_api_key or not cfg.pinecone_region: raise Exception("Please provide pinecone_api_key and pinecone_region")
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Exception: Please provide pinecone_api_key and pinecone_region 

### Expected behavior 🤔

AUTOgpt running in continuous mode 

### Your prompt 📝

```yaml
# Paste your prompt here
```

(im using mac btw)

**Comment by richbeales** [comment]
type 'cat .env' and see what happens.

**Comment by SparkAladdin** [comment]
> type 'cat .env' and see what happens.

didn't work, am I supposed to type this in terminal? cause I tired that and it said no such file

**Comment by richbeales** [comment]
That's your problem then, the .env file needs to exist.
In a terminal, type

cp .env.template .env

Then edit your .env file to include your api keys/etc.

**Comment by richbeales** [comment]
The alternative is using something like VSCode to view/edit the files in the directory

typing

code .

in a terminal (once VSCode is installed) will allow you to see and edit all the files

**Comment by SparkAladdin** [comment]
> That's your problem then, the .env file needs to exist. In a terminal, type
> 
> `cp .env.template .env`
> 
> Then edit your .env file to include your api keys/etc.



> That's your problem then, the .env file needs to exist. In a terminal, type
> 
> `cp .env.template .env`
> 
> Then edit your .env file to include your api keys/etc.

This worked finally.

**Comment by Explorergt92** [comment]
@SparkAladdin is this still an issue for you or can this be closed?

**Comment by Qoyyuum** [comment]
Issue no longer relevant. Please use latest stable release. Closing issue.
