### ISSUE TITLE
401 error. API key for pinecone does not work

### ISSUE THREAD

**Issue by dreiscm** [Significant-Gravitas/Auto-GPT#541]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Hello. I installed AutoGPT following the github instructions, But i am getting the erro 401, massage as follows:
pinecone.core.client.exceptions.UnauthorizedException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({‘www-authenticate’: ‘API key is missing or invalid for the environment “northamerica-northeast1-gcp”. Check that the correct environment is specified.’, ‘content-length’: ‘129’, ‘date’: ‘Sat, 08 Apr 2023 17:16:09 GMT’, ‘server’: ‘envoy’})
HTTP response body: API key is missing or invalid for the environment “northamerica-northeast1-gcp”. Check that the correct environment is specified.

I am not the biggest expert in python, but i did the adjusts according to the github to set all the needed API keys, and also gave a look in memory.py to see if i found the problem there, but i could not solve it at all. I anyone here can help me, i will appreciate it.

### Current behavior 😯

asks if i want to create a new identity or keep the old one, but anyway it does not work in the end

### Expected behavior 🤔

the model should function

**Comment by tylerjkline** [comment]
Pinecone is not working for me either, even after paying for a key. @Torantulino why would you introduce this into your code when it worked fine before this? It's completely unstable and makes your project unusable.

**Comment by mkcastro** [comment]
Same here. I tried creating a new index on pinecone, but they seem to be having some issues on their own.

**Comment by richpav** [comment]
If you're using git you can roll back to a version before pincone was added:

git reset --hard 51e293f

I'm not sure which is better, git reset or git revert.

On MacOS I had to re-run the pip requirements because docker and googlesearch-python weren't playing together well.

pip install -r requirements-alternative.txt
pip install -r requirements.txt

**Comment by TheVexy** [comment]
Remember that you have to create an index on Pinecone. 
Click on create index and use 1536 for the dimension. Once you index it's created copy it's Environment and put it in PINECONE_ENV=us-west4-gcp (in my case)

**Comment by piyush-bhatt** [comment]
I'm in the same region (northamerica-northeast1-gcp) and was facing the same issue. However, I rotated my API keys and it worked after a couple of retries. No need to create any index manually.

**Comment by Explorergt92** [comment]
@dreiscm is this still an issue for you or can this be closed?
