### ISSUE TITLE
I am not able to pass this issue when trying to run python scripts/main.py --gpt3only                                           

### ISSUE THREAD

**Issue by kalizak** [Significant-Gravitas/Auto-GPT#544]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

I get this error from Terminal 

  File "scripts/main.py", line 31
    speak.say_text(f"{title}. {content}")

Anyone please? 
Thanks in advanced
                                       ^

### Current behavior 😯

  File "scripts/main.py", line 31
    speak.say_text(f"{title}. {content}"

### Expected behavior 🤔

Run  file smoothly

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by ZhangHanwen96** [comment]
Are you sure ` python scripts/main.py --gpt3only` is the command you ran?
