### ISSUE TITLE
JSON validation w/retry

### ISSUE THREAD

**Issue by meesterdude** [Significant-Gravitas/Auto-GPT#547]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

parse response for JSON and provide corrective prompt to fix

**Comment by p-i-** [comment]
Community effort to sort out this JSON fail once and for all at https://github.com/Torantulino/Auto-GPT/issues/1407

We have 17 open PRs for fixing this, and the merge-team are stacked.

**Comment by Pwuts** [comment]
Closing as one of many duplicates; superseded by #1407
