### ISSUE TITLE
Not signing in with codespaces

### ISSUE THREAD

**Issue by mdabir1203** [Significant-Gravitas/Auto-GPT#5530]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Devcontainer / Codespace

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

FLutter client doesn't allow you to sign in . There are two cases :

Case 1: **github signin** : It doesn't open

Case 2: **Google Signin** : redirect uri mismatch
<img width="1378" alt="image" src="https://github.com/Significant-Gravitas/AutoGPT/assets/66947064/7078cddf-9ee6-4b27-985d-f77c1582809b">

### Upload Activity Log Content

<img width="858" alt="image" src="https://github.com/Significant-Gravitas/AutoGPT/assets/66947064/0077f88c-f970-4edc-9fa5-7eb97158d51a">

**Comment by jihun-im** [comment]
Accessing `http://localhost:8000` not `http://0.0.0.0:8000` solved the problem in my case
