### ISSUE TITLE
Speak mode error

### ISSUE THREAD

**Issue by VegarBere** [Significant-Gravitas/Auto-GPT#558]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

$  Auto-GPT git:(master) ✗ python3 scripts/main.py --speak

Speak Mode:  ENABLED
Traceback (most recent call last):
  File "/Users/vegarberentsen/Auto-GPT/scripts/main.py", line 275, in <module>
    prompt = construct_prompt()
             ^^^^^^^^^^^^^^^^^^
  File "/Users/vegarberentsen/Auto-GPT/scripts/main.py", line 164, in construct_prompt
    print_to_console(
  File "/Users/vegarberentsen/Auto-GPT/scripts/main.py", line 30, in print_to_console
    speak.say_text(f"{title}. {content}")
  File "/Users/vegarberentsen/Auto-GPT/scripts/speak.py", line 45, in say_text
    success = eleven_labs_speech(text, voice_index)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vegarberentsen/Auto-GPT/scripts/speak.py", line 27, in eleven_labs_speech
    playsound("speech.mpeg")
  File "/opt/homebrew/lib/python3.11/site-packages/playsound.py", line 55, in _playsoundOSX
    from AppKit     import NSSound
ModuleNotFoundError: No module named 'AppKit'

### Current behavior 😯

error

### Expected behavior 🤔

should speak & start

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by richbeales** [comment]
Looks like your python distro is missing PyObjC try

pip3 install -U PyObjC

**Comment by RapahelS** [comment]
I had the same error and this worked. Thanks. Consider adding this to the requierements.txt?

**Comment by skynet01** [comment]
Hmm installing PyObjC dependency did not fix it for me (shows dependency installed successfully). I am on Silicon M1 Mac if that makes any difference.

**Comment by ylluminate** [comment]
Not a bad idea. `say` could be a better option for macOS users and simplify things slightly.

**Comment by karolgileta** [comment]
I still get this error, even after installing the libraries mentioned above.

Looks like these are different files than above. Anybody had any luck with this?

karolgileta@Karols-MacBook-Pro Auto-GPT-master % python -m autogpt --speak 
Weaviate not installed. Skipping import.
Speak Mode:  ENABLED
Welcome to Auto-GPT!  Enter the name of your AI and its role below. Entering nothing will load defaults.
Name your AI:  For example, 'Entrepreneur-GPT'
AI Name: Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/karolgileta/Documents/Coding/AutoGPT/Auto-GPT-master/autogpt/speech/say.py", line 34, in speak
    success = VOICE_ENGINE.say(text, voice_index)
  File "/Users/karolgileta/Documents/Coding/AutoGPT/Auto-GPT-master/autogpt/speech/base.py", line 33, in say
    return self._speech(text, voice_index)
  File "/Users/karolgileta/Documents/Coding/AutoGPT/Auto-GPT-master/autogpt/speech/eleven_labs.py", line 80, in _speech
    playsound("speech.mpeg", True)
  File "/Users/karolgileta/Library/Python/3.9/lib/python/site-packages/playsound.py", line 55, in _playsoundOSX
    from AppKit     import NSSound
ModuleNotFoundError: No module named 'AppKit'

**Comment by ylluminate** [comment]
It's worth noting that Apple's `say` command can use multiple voices which should be definable within the configuration file. To use such voices you simply use the `-v` argument, eg:
```
say -v Alex "This is voice one"
say -v "Samantha" "This is voice two"
```
man page:
```
SAY(1)                     Speech Synthesis Manager                     SAY(1)


NAME
       say - Convert text to audible speech

SYNOPSIS
           say [-v voice] [-r rate] [-o outfile [audio format options] | -n name:port | -a device] [-f file | string ...]

DESCRIPTION
       This tool uses the Speech Synthesis manager to convert input text to
       audible speech and either play it through the sound output device
       chosen in System Preferences or save it to an AIFF file.

OPTIONS
       string
           Specify the text to speak on the command line. This can consist of
           multiple arguments, which are considered to be separated by spaces.

       -f file, --input-file=file
           Specify a file to be spoken. If file is - or neither this parameter
           nor a message is specified, read from standard input.

       -v voice, --voice=voice
           Specify the voice to be used. Default is the voice selected in
           System Preferences. To obtain a list of voices installed in the
           system, specify '?' as the voice name.

       -r rate, --rate=rate
           Speech rate to be used, in words per minute.

       -o out.aiff, --output-file=file
           Specify the path for an audio file to be written. AIFF is the
           default and should be supported for most voices, but some voices
           support many more file formats.

       -n name, --network-send=name
       -n name:port, --network-send=name:port
       -n :port, --network-send=:port
       -n :, --network-send=:
           Specify a service name (default "AUNetSend") and/or IP port to be
           used for redirecting the speech output through AUNetSend.

       -a ID, --audio-device=ID
       -a name, --audio-device=name
           Specify, by ID or name prefix, an audio device to be used to play
           the audio. To obtain a list of audio output devices, specify '?' as
           the device name.

       --progress
           Display a progress meter during synthesis.

       -i, --interactive, --interactive=markup
           Print the text line by line during synthesis, highlighting words as
           they are spoken. Markup can be one of

           o   A terminfo capability as described in terminfo(5), e.g. bold,
               smul, setaf 1.

           o   A color name, one of black, red, green, yellow, blue, magenta,
               cyan, or white.

           o   A foreground and background color from the above list,
               separated by a slash, e.g. green/black. If the foreground color
               is omitted, only the background color is set.

           If markup is not specified, it defaults to smso, i.e. reverse
           video.

       If the input is a TTY, text is spoken line by line, and the output
       file, if specified, will only contain audio for the last line of the
       input.  Otherwise, text is spoken all at once.

AUDIO FORMATS
       Starting in MacOS X 10.6, file formats other than AIFF may be
       specified, although not all third party synthesizers may initially
       support them. In simple cases, the file format can be inferred from the
       extension, although generally some of the options below are required
       for finer grained control:

       --file-format=format
           The format of the file to write (AIFF, caff, m4af, WAVE).
           Generally, it's easier to specify a suitable file extension for the
           output file. To obtain a list of writable file formats, specify '?'
           as the format name.

       --data-format=format
           The format of the audio data to be stored. Formats other than
           linear PCM are specified by giving their format identifiers (aac,
           alac). Linear PCM formats are specified as a sequence of:

           Endianness (optional)
               One of BE (big endian) or LE (little endian). Default is native
               endianness.

           Data type
               One of F (float), I (integer), or, rarely, UI (unsigned
               integer).

           Sample size
               One of 8, 16, 24, 32, 64.

           Most available file formats only support a subset of these sample
           formats.

           To obtain a list of audio data formats for a file format specified
           explicitly or by file name, specify '?' as the format name.

           The format identifier optionally can be followed by @samplerate and
           /hexflags for the format.

       --channels=channels
           The number of channels. This will generally be of limited use, as
           most speech synthesizers produce mono audio only.

       --bit-rate=rate
           The bit rate for formats like AAC. To obtain a list of valid bit
           rates, specify '?' as the rate. In practice, not all of these bit
           rates will be available for a given format.

       --quality=quality
           The audio converter quality level between 0 (lowest) and 127
           (highest).

ERRORS
       say returns 0 if the text was spoken successfully, otherwise non-zero.
       Diagnostic messages will be printed to standard error.

EXAMPLES
          say Hello, World
          say -v Alex -o hi -f hello_world.txt
          say --interactive=/green spending each day the color of the leaves
          say -o hi.aac 'Hello, [[slnc 200]] World'
          say -o hi.m4a --data-format=alac Hello, World.
          say -o hi.caf --data-format=LEF32@8000 Hello, World

          say -v '?'
          say --file-format=?
          say --file-format=caff --data-format=?
          say -o hi.m4a --bit-rate=?

SEE ALSO
       "Speech Synthesis Programming Guide"

1.0                               2020-08-13                            SAY(1)
```

**Comment by steelliberty** [comment]
I have the same issue .. It is trying to import AppKit as a module when appkit is correct and availabie. What is the solution?

**Comment by CamiloB** [comment]
> Hmm installing PyObjC dependency did not fix it for me (shows dependency installed successfully). I am on Silicon M1 Mac if that makes any difference.
> 
> update: if you tried installing Appkit separately that will break the above so you have to run to fix it
> 
> ```
> pip3 uninstall appkit
> pip3 install --upgrade --force-reinstall PyObjC PyObjC-core
> ```
> 
> also maybe on a mac we could just use the "say" command (has many voices too and you can install others yourself) and bypass the whole speech API? :)

This work form macbook pro m1 pro chip whit 13.3.1 ventura

**Comment by sovattha** [comment]
> 

Worked like a charm on my Mac book pro, Ventura 13.2.1.

**Comment by speaktoarpit** [comment]
works for me as well - Mac OS 10.15.7

**Comment by steelliberty** [comment]
Thank you -- works!!
