### ISSUE TITLE
Auto-discover new capabilities via API's and dynamic run-times.

### ISSUE THREAD

**Issue by MatShep** [Significant-Gravitas/Auto-GPT#56]
Create a new command to dynamically expand capabilities.

1. Identify a capability gap. e.g. if current weather/stock prices cannot be obtained from current Auto-GPT capabilities 
2. Provide a static list of known API libraries (or discover via google search).
3. Find an API for the required capability.
4. Create a python command in-memory to call the discovered API schema.
5. Call a sub-agent to impersonate the in-memory API python command.
6. Ask the sub-agent to return a response for the new capability.

Some example API libraries:
- https://api.publicapis.org/entries
- https://api.m3o.com/v1/app/List
- https://github.com/public-apis/public-apis
- https://developers.google.com/apis-explorer
- https://learn.microsoft.com/en-us/python/api/?view=azure-python
- https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/index.html

**Comment by Pwuts** [comment]
This is a great idea for a plugin. We're expecting to ship plugin support at the end of the week. :)

**Comment by Pwuts** [comment]
@BillSchumacher what do you think, plugin or core?

**Comment by Boostrix** [comment]
FWIW, I would also be interested in discussing this a little more, in fact I started experiments related to this, asking a bunch of agents to recursively write a program, which involved "discovering" the github docs/API to pull this off: https://github.com/Significant-Gravitas/Auto-GPT/issues/15#issuecomment-1533346355

The idea was to traverse this project's open github pull requests and identitfy those that have no conflicts and that also aren't touching any files touched by other open PRs: https://github.com/Significant-Gravitas/Auto-GPT/issues/15#issuecomment-1529858630

**Comment by Boostrix** [comment]
This would actually help also in the context of #5536
