### ISSUE TITLE
i run the "python scripts/main.py --gpt3only" and its started i gave it a name and i give it a role and 1 or 3 goals but it give me this error ""

### ISSUE THREAD

**Issue by scrawnyether5669** [Significant-Gravitas/Auto-GPT#578]

**Comment by scrawnyether5669** [comment]
![Capture11](https://user-images.githubusercontent.com/117683751/230766614-bb8c330b-2699-484b-a2cb-00959e07b67d.PNG)

**Comment by scrawnyether5669** [comment]
![Capture12](https://user-images.githubusercontent.com/117683751/230766623-e352c687-6690-4e5f-b08e-ed065943d860.PNG)

**Comment by keenborder786** [comment]
Hello did you downloaded all of the packages using:
```
pip install -r requriements.txt
```

**Comment by scrawnyether5669** [comment]
lol nvm i thought openai api keys are free to use, that was the problem do you any free APIs for LLMs? or how to use alpaca 7b model with an api key?

**Comment by DrBehns** [comment]
I'm still having this problem, and yes. I downloaded them

**Comment by Qoyyuum** [comment]
@scrawnyether5669 please use the latest stable release and ensure that you've entered your Pinecone API Key and region in the `.env` file. Thanks. Closing issue.
