### ISSUE TITLE
ModuleNotFoundError: No module named 'memory'

### ISSUE THREAD

**Issue by imlucif3r** [Significant-Gravitas/Auto-GPT#581]
### Duplicates

- [x] I have searched the existing issues

### Steps to reproduce 🕹

Updated with latest commit files 
unable to start execution 

### Current behavior 😯

![image](https://user-images.githubusercontent.com/29899867/230767353-44288261-0398-45a0-8d90-0872590a2ce8.png)

### Expected behavior 🤔

Should have started with AI promt for name,desription and goals

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by ommirkute** [comment]
You must first install the package before you can use it in your code. Run the following command to install the package and its dependencies.

**pip install memory**

**Comment by richbeales** [comment]
It's not a pip package, it's a local package (i.e. a folder).  It's as if your working directory is wrong, so the relative import isn't working.

Check you're running the latest code by doing a 'git pull'. 
Check you have a folder called 'memory' under 'scripts/'
