### ISSUE TITLE
New command: extract transcription from YouTube videos using Whisper

### ISSUE THREAD

**Issue by EugeneVanchugov** [Significant-Gravitas/Auto-GPT#587]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

The command should work in conjunction with the web search. Maybe new command should be added, for example "youtubeSearch".

The proposed command takes a video from YouTube and uses OpenAI Whisper to extract a transcription. 
A resulting transcription then used in a summarization and being stored in a long-term memory for later usage.

It is possible to use an OpenAI API or a local instance of Whisper in order to keep expenses low.
There is also Google Cloud Speech-To-Text API, that does pretty much the same thing.

### Motivation 🔦

YouTube has lots of information encoded in audio, such as podcasts, lectures, interviews, etc that are not present in a text form anywhere else. 

Usage of this command is not limited only with YouTube videos, but with any speech sources. 
In the future, it might be used for transcribing an active video/audio stream in real time by a distinct agent.

**Comment by IsleOf** [comment]
For existing transcriptions you can try this:

https://github.com/bernorieder/youtube-transcript-scraper

**Comment by Pwuts** [comment]
This would be perfect as a plugin! :)

Plugin support (#757) is expected to ship at the end of this week. Stay tuned.
