### ISSUE TITLE
Not Recognizing Pinecone API or Region within Docker Container

### ISSUE THREAD

**Issue by joshgoldfla** [Significant-Gravitas/Auto-GPT#591]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Try running this repository within a docker container

### Current behavior 😯

I get this error..

PS C:\Users\jgold\desktop> docker run -it -e PINECONE_API_KEY="XXXXXXX" -e PINECONE_REGION="XXXXX" my-auto-gpt-image
root@e48413f03ddd:/app/Auto-GPT# python3 scripts/main.py
Welcome back!  Would you like me to return to being Entrepreneur-GPT?
Continue with the last settings?
Name:  Entrepreneur-GPT
Role:  an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.
Goals: ['Increase net worth.', 'Develop and manage multiple businesses autonomously.', 'Play to your strengths as a Large Language Model.']
Continue (y/n): y
Traceback (most recent call last):
  File "/app/Auto-GPT/scripts/main.py", line 285, in <module>
    if not cfg.pinecone_api_key or not cfg.pinecone_region: raise Exception("Please provide pinecone_api_key and pinecone_region")
Exception: Please provide pinecone_api_key and pinecone_region

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by joshgoldfla** [comment]
Just to add. If I run on my local, it works fine

**Comment by suensummit** [comment]
Do you have `.env` file inside your image which contains empty `pinecone_api_key` and `pinecone_region` variables?

**Comment by joshgoldfla** [comment]
> Do you have `.env` file inside your image which contains empty `pinecone_api_key` and `pinecone_region` variables?

Yes .env does and this is my docker file currently...

FROM python:3.11

WORKDIR /app
COPY scripts/ /app

# Copy the .env file into the container
COPY ./.env ./.env

RUN pip install -r requirements.txt

CMD ["python", "main.py"]


Ive also added this to the main.py

from dotenv import load_dotenv
import os

load_dotenv()

pinecone_api_key = os.getenv("PINECONE_API_KEY")
pinecone_region = os.getenv("PINECONE_REGION")

# Rest of your code...


Any other suggestions?

**Comment by suensummit** [comment]
Remove these two lines in your .env file if you are going to use -e to pass your environment variables.

**Comment by joshgoldfla** [comment]
i've tried using without -e and still same error.  

I used this...docker run -it -v C:\Users\jgold\Desktop\my-data:/app/data my-auto-gpt-image

**Comment by suensummit** [comment]
I guess it might relates: https://github.com/Torantulino/Auto-GPT/pull/455
as in the current version of dockerfile `COPY scripts/ /app` does not copy the `requirements.txt` into the container.

**Comment by joshgoldfla** [comment]
i tried that and still same error when running main.py

WORKDIR /app
COPY scripts/ /app
COPY requirements.txt /app

RUN pip install -r requirements.txt

**Comment by joshgoldfla** [comment]
Traceback (most recent call last):
  File "/app/Auto-GPT/scripts/main.py", line 285, in <module>
    if not cfg.pinecone_api_key or not cfg.pinecone_region: raise Exception("Please provide pinecone_api_key and pinecone_region")
Exception: Please provide pinecone_api_key and pinecone_region
root@160221e16b4e:/app/Auto-GPT#

**Comment by suensummit** [comment]
> Traceback (most recent call last): File "/app/Auto-GPT/scripts/main.py", line 285, in if not cfg.pinecone_api_key or not cfg.pinecone_region: raise Exception("Please provide pinecone_api_key and pinecone_region") Exception: Please provide pinecone_api_key and pinecone_region root@160221e16b4e:/app/Auto-GPT#

It seems your `Auto-GPT` scripts are outdated?

**Comment by joshgoldfla** [comment]
I tried updating as suggested above.  I updated the 3 python scripts with the suggested code and i still am receiving the same error.  Any other suggestions?

**Comment by Pwuts** [comment]
Closing as stale. Please try again with the newest version and reopen if the problem persists.
