### ISSUE TITLE
Extraction error

### ISSUE THREAD

**Issue by MasterBuZ** [Significant-Gravitas/Auto-GPT#597]
Hey guys I'm having this error is their a fix?:
 WARNING: Failed to write executable - trying to use .deleteme logic
ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'C:\\Python310\\Scripts\\wsdump.exe' -> 'C:\\Python310\\Scripts\\wsdump.exe.deleteme'

WARNING: You are using pip version 21.2.3; however, version 23.0.1 is available.
You should consider upgrading via the 'C:\Python310\python.exe -m pip install --upgrade pip' command.

**Comment by richbeales** [comment]
https://stackoverflow.com/questions/66322049/could-not-install-packages-due-to-an-oserror-winerror-2-no-such-file-or-direc

run pip as administrator or append --user

**Comment by MasterBuZ** [comment]
FIXED thank you!
