### ISSUE TITLE
python scripts/main.py does nothing

### ISSUE THREAD

**Issue by Dagever** [Significant-Gravitas/Auto-GPT#598]
I have no idea what is wrong, installed all the requirements and edited the .env file with my api keys but when I write python scripts/main.py in the cmd I get nothing 

![image](https://user-images.githubusercontent.com/126493097/230780340-7b6718e8-c9fb-46d2-beb9-aadd7899a4f5.png)

Also my .env file 
![image](https://user-images.githubusercontent.com/126493097/230780428-4f7e9aeb-3f37-42b6-8546-51db0ce2994e.png)

At first it was without "", now it is with them and still nothing

**Comment by richbeales** [comment]
What version of python do you have installed?

**Comment by Dagever** [comment]
The latest one, 3.11.3

**Comment by GrzegorzKarczewski** [comment]
pip install -r requirements.txt

**Comment by weareturnone** [comment]
Try 

Python3 main.py

**Comment by Slamsneider** [comment]
No "quotes" !

**Comment by bigsk1** [comment]
> Try
> 
> Python3 main.py

this is what I have to use also

**Comment by SebastianSala** [comment]
Had this error. Uninstalled latest version of Python and installed 3.10, then it worked.

**Comment by richbeales** [comment]
can this be closed?

**Comment by Qoyyuum** [comment]
Issue no longer relevant. Please use stable release and follow the new README as a guide and try again with `python -m autogpt`.
