### ISSUE TITLE
 Command read_file returned: Error: 'charmap' codec can't decode byte 0x8f in position 5482: character maps to <undefined>

### ISSUE THREAD

**Issue by snaky-ru** [Significant-Gravitas/Auto-GPT#600]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

1. Put the file README.md from the Auto-GPT project to working directory.
2. Ask Auto-GPT to read it.

### Current behavior 😯

An error  Command read_file returned: Error: 'charmap' codec can't decode byte 0x8f in position 5482: character maps to <undefined> will be printed in the console window.

### Expected behavior 🤔

The file has to be readed as expected.

**Comment by snaky-ru** [comment]
We probably should detect the file encoding before reading it

**Comment by gx-7** [comment]
I fixed this issued by adding the parameter encoding = UTF-8 for each call open() methods used in the project.
You can set it by default too.

**Comment by snaky-ru** [comment]
> I fixed this issue by adding the parameter encoding = UTF-8 for each call open() methods used in the project. You can set it by default too.

True, but what if file has another encoding?

**Comment by Pwuts** [comment]
Closing as stale. Please reopen if still a problem.

**Comment by V4mpyr** [comment]
> d

How do you set this as default? Mine is having issues reading PDF and Docx. Would love to get rid of this issue.
