### ISSUE TITLE
Non-Atomic label for PRs

### ISSUE THREAD

**Issue by nponeccop** [Significant-Gravitas/Auto-GPT#609]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

There are many PRs where people do several things at once. So it would be nice to mark them all as Non-Atomic for you to see the remaining issues better.

### Examples 🌈

#605 #603

### Motivation 🔦

I want to improve the efficiency of @Torantulino in merging the essential PRs while leaving digging bad quality PRs for other people.

**Comment by richbeales** [comment]
I discussed this earlier with @Torantulino currently the github repo is a personal one, so there's no way of doing granular permissions without converting to an organisation account.
Currently contributor role is all-or-nothing regarding write access, which he is (rightly) quite nervous about giving out to randomers on the internet.

**Comment by nponeccop** [comment]
Well, he could use the labels by himself. Are org repos free?

**Comment by richbeales** [comment]
indeed he could, but I think the project will need more hands to help out, especially at the current rate of growth.
Yes, I believe they're free.
