### ISSUE TITLE
poetry start agent hangs - issue in ubuntu

### ISSUE THREAD

**Issue by shuther** [Significant-Gravitas/Auto-GPT#6090]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

While starting the agent, poetry hanged while it installed the package - stuck in pending
 ```
./run agent start AgentName
```

>  • Installing attrs (23.1.0): Pending...
>   • Installing frozenlist (1.4.0): Pending...
>   • Installing idna (3.4): Pending...
>   • Installing multidict (6.0.4): Pending...
>   • Installing six (1.16.0): Pending...

I was able to trace the issue from [Poetry github issue](https://github.com/python-poetry/poetry/issues/1917), it relates to keyring/ubuntu

### Workaround:
execute first
```
export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring
```

**Comment by arturtoshev** [comment]
As [I already replied in the issue you linked above](https://github.com/python-poetry/poetry/issues/1917#issuecomment-1770241003), I ran into `poetry install` getting stuck halfway through. What I found to solve the problem for me was clearing the cache:

```
curl -sSL https://install.python-poetry.org | python3 - --uninstall  # uninstall poetry
rm -r $HOME/.cache/pypoetry  # clear cache
curl -sSL https://install.python-poetry.org | python3 -  # install latest release
```
