### ISSUE TITLE
win 10 error on pip install -r requirements.txt

### ISSUE THREAD

**Issue by pleabargain** [Significant-Gravitas/Auto-GPT#62]
ERROR: Could not find a version that satisfies the requirement pywin32==227; sys_platform == "win32" (from docker) (from versions: 302, 303, 304, 305, 306)
ERROR: No matching distribution found for pywin32==227; sys_platform == "win32"

**Comment by AndresCdo** [comment]
I think you need to use pypiwin32 instead.

`pip install pypiwin32`

**Comment by Torantulino** [comment]
Related?: https://github.com/docker/docker-py/issues/2033

**Comment by Emilot** [comment]
it has been fixed in docker-py: https://github.com/docker/docker-py/issues/2967

**Comment by Torantulino** [comment]
Try uninstalling both docker-py and docker, then reinstalling JUST docker.

**Comment by Playerrrrr** [comment]
same error, will try does it have to be specifically the pywin32-227 version?

**Comment by XOCODE-OP** [comment]
whenever I install pip requirement files it never works when it has version numbers on windows. So I just took out all the version numbers and its still working.

**Comment by Emilot** [comment]
solved with current requirements.txt...

Thanx!

**Comment by Playerrrrr** [comment]
> solved with current requirements.txt...
> 
> Thanx!

WDYM? Can you share the solution?

**Comment by Emilot** [comment]
Take a look to the current requirements file in the repo. Download it again and run the same command.
