### ISSUE TITLE
API rate limit error

### ISSUE THREAD

**Issue by 2yinfotech** [Significant-Gravitas/Auto-GPT#622]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

<img width="1470" alt="Screenshot 2023-04-10 at 2 29 23 AM" src="https://user-images.githubusercontent.com/112082193/230796359-ca0c659e-34b8-446a-8598-62f2c3d90029.png">

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by jangofett890** [comment]
You need to add a credit/debit card to your API profile.

**Comment by ericytsang** [comment]
yeah as y'all know, this error has something to do with OpenAI and ChatGPT 😄 
![image](https://user-images.githubusercontent.com/5971684/230800432-48f44665-ccd2-4952-9b78-16d45984e4df.png)

i had to do the steps in this order:
1. upgrade to a paid account: https://platform.openai.com/account/billing/overview
    - ChatGPT+ != paid account. i already had ChatGPT+, but I needed up upgrade to paid account
3. add a payment method: https://platform.openai.com/account/billing/payment-methods
4. (optional) set my usage limits: https://platform.openai.com/account/billing/limits
5. create a new API key: https://platform.openai.com/account/api-keys
    - (old API key did not work, i guess it was not update with my payment information automatically)
6. replace the value for the `autogpt/.env` files's `OPENAI_API_KEY`.
