### ISSUE TITLE
Windows Issue #01 - Control + C not working

### ISSUE THREAD

**Issue by userbox020** [Significant-Gravitas/Auto-GPT#632]
### Duplicates

- [X] I have searched the existing issues

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by userbox020** [comment]
Hello, does mac users have same problem?

**Comment by KewkLW** [comment]
Did you try turning it off and back on again?

**Comment by userbox020** [comment]
> Did you try turning it off and back on again?

The main goal its to use system output errors so we can stop the AI even if it duplicates on different threads or instances. If I just turn off and back on of course will shutdown, but will not kill all the child process.

**Comment by Pwuts** [comment]
I can't tell what the problem is. If this issue is still relevant, please reopen and provide more information. The issue form is there for a reason.
