### ISSUE TITLE
Output in Visual Studio Code is very confusing

### ISSUE THREAD

**Issue by barbsblc** [Significant-Gravitas/Auto-GPT#635]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Try to run goals on Visual Studio Code.

### Current behavior 😯

Completely confusing because it writes on top of what was written before.

The outputs on Visual Studio Code are very confusing. I don't know why it goes to the top of the page when thinking and then it starts writing on top of what was written before and I can't understand anything. I tried to use Git Batch but they keep saying that I need to provide the Pinecone key and region, which I did. And all of this doesn't work directly on the computer's CMD. 

### Expected behavior 🤔

It should write line by line going down, not going up the page.

### Your prompt 📝

FluentWay Assistant is: Help an ESL tutor who teaches one-on-one online lessons to adults Brazilian increase her profits.
Enter up to 5 goals for your AI:  For example: Increase net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously'
Enter nothing to load defaults, enter nothing when finished.
Goal 1: Summarize the news about Brazil and the world. Search in Portuguese for better results and also search on Brazilian websites.
Goal 2: Suggest the best social media platform for me to post. My target audience is adults who are 30 to 40 years old, and work in large companies in positions of management or senior analysts. 
Goal 3: Help me prepare my lessons by analyzing my private files. Tell me how we could do this.

**Comment by richbeales** [comment]
What behaviour do you see when trying to run it at a command prompt?

**Comment by Pwuts** [comment]
Closing since OP doesn't respond
