### ISSUE TITLE
Not recognizing my OpenAI API

### ISSUE THREAD

**Issue by timkite76** [Significant-Gravitas/Auto-GPT#644]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

I input my OpenAI API key in the .env but when I run main.py, i can set up the agent, set 5 goals, but then it throws off the following error:

openai.error.AuthenticationError: Incorrect API key provided: sk-dLjLf***************************************PcFj. You can find your API key at https://platform.openai.com/account/api-keys.
 
I have tried several new openai api keys - all with the same result

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by richbeales** [comment]
Have you set up billing on your OpenAI account?

**Comment by onekum** [comment]
I'd like to say that I'm having the same issue and I have set up billing.

**Comment by richbeales** [comment]
Do you have quotes around the key in .env ?  (If so try removing)

**Comment by onekum** [comment]
No quotes.

![1311502041002](https://user-images.githubusercontent.com/55006697/230843353-5b8e89e0-0c5e-45f2-8d79-f88f21fbb6f0.png)

**Comment by DevangRadadiya** [comment]
try this command maybe it will help you to cache: pip cache purge

**Comment by aosan** [comment]
a quick way to validate the API key you use in .env is by running:

`curl -X GET https://api.openai.com/v1/models -H "Authorization: Bearer sk-kufw3eq_YOUR_API_KEY_asdqe23adg"`

if successful, it will return what models are available to your subscription.

**Comment by onekum** [comment]
> try this command maybe it will help you to cache: pip cache purge

I don't think this did anything for me, unfortunately.

> a quick way to validate the API key you use in .env is by running:
> 
> `curl -X GET https://api.openai.com/v1/models -H "Authorization: Bearer sk-kufw3eq_YOUR_API_KEY_asdqe23adg"`
> 
> if successful, it will return what models are available to your subscription.

I put in the key I'm using in my `.env` and the command successfully returns with all of the models available to my account. This suggests that it may be an issue with the script.

Can other people with the same issue chime in?

**Comment by aosan** [comment]
OK, we've established your API key is fine.

What version of Python are you running?

`python3 --version`

What version of openai is installed?

`pip3 show openai`

**Comment by onekum** [comment]
> What version of Python are you running?
```
$ python3 --version
Python 3.10.10
```
> What version of openai is installed?
```
$ pip3 show openai
Name: openai
Version: 0.27.2
Summary: Python client library for the OpenAI API
Home-page: https://github.com/openai/openai-python
Author: OpenAI
Author-email: support@openai.com
License: 
Location: /home/****/.local/lib/python3.10/site-packages
Requires: aiohttp, requests, tqdm
Required-by:
```

**Comment by aosan** [comment]
Fairly recent Python release, recent openai. Latest openai is 0.72.4, but I'm on 0.72.2 too, without any errors.
Did you try with the latest pull from master? Maybe try to install again to make sure you've pulled all dependencies? The app is not very modular at the moment, error handling is minimal.

**Comment by onekum** [comment]
I reran `pip install -r requirements.txt` after pulling the repo from master (no changes or updates from each command). I also tried rerunning the script after the fact and got the same error. Pretty illusive.

**Comment by aosan** [comment]
@onekum try `strace python scripts/main.py`  plus any other arguments you use and see what rabbit trails turn out ugly

**Comment by timkite76** [comment]
> Have you set up billing on your OpenAI account?

yeah - been set up for awhile.

**Comment by onekum** [comment]
> try strace python scripts/main.py plus any other arguments you use and see what rabbit trails turn out ugly

I ran `strace python scripts/main.py` and got its output. I've never used `strace` before, so I really don't know what to look for. The log is below if you're interested.

[strace_output.txt](https://github.com/Torantulino/Auto-GPT/files/11191082/strace_output.txt)

**Comment by aosan** [comment]
@onekum strace lets you know see all the system calls made at execution, useful options can be found in the manual.

It appears only the pinecode API are read from .env in the strace and you've got an "write(2, "openai.error.AuthenticationError"..., 190) = 190" It worked when you tried calling the API with your API directly, so the app is not picking it up correctly.

just to rule out any environment issues, please try carefully with a `git reset --hard origin/master` and create .env again with only the minimal values like LLM_MODEL (try with both GPT-4 and 3.5), OPENAI and REDIS/PINECODE configurations. See if you get the same errors. If you do, try again but enable strace with:

`strace -o strace_output.log -f -e trace=file -s 256 python scripts/main.py`

Usually, it is not ideal to put strace logs in public, hence my suggestion to take it to Discord and then DM based ping-pong.
I'll come back in about 16h, best of luck until then :wink:

**Comment by onekum** [comment]
Noted; I made sure there wasn't any personal information in the strace log. I'll do what you suggested, thanks.

**Comment by timkite76** [comment]
This seems ot have resolved itself for me.  My guess is it was some issue on the OpenAI key

**Comment by r3chn3r** [comment]
A lot of folks forget to rename the file and get the same error.

**Comment by onekum** [comment]
> @onekum got it working?

Like timkite76, it seems to have resolve itself. I didn't do anything in particular on my system to resolve it, though, so I'd be hard pressed to tell what the issue was. I did do the hard git reset, but that was yesterday and it still didn't work after the fact, so I have no idea why it works now.

**Comment by azapata13** [comment]
Check the .sourcery file and erase (.env) under : 
ignore: # A list of paths or files which Sourcery will ignore.

:)
