### ISSUE TITLE
linebreaks sometimes not resolved properly

### ISSUE THREAD

**Issue by Wladastic** [Significant-Gravitas/Auto-GPT#652]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Let Auto-GPT write code into a file.

### Current behavior 😯

Sometimes the linebreaks are resolved correctly.

Sometimes I get this:
```
import game\nimport unittest\n\n\nclass GameTest(unittest.TestCase):\n\n    def test_main_character_added(self):\n        pass\n    \n    def test_event_listeners(self):\n        pass\n    \n    def test_animation_running(self):\n        pass
```

### Expected behavior 🤔

Make Auto-gpt recognize broken line breaks and make it run a command to clean those up.

### Your prompt 📝

ai_goals:
- create a website that hosts a three.js game
- design and develop the game using three.js
- ensure the website is responsive and user-friendly
- make the game interactive and engaging for players
- provide a simple way for the owner to update the game or website content
ai_name: Neo
ai_role: an AI designed to write code that creates a website hosting a three.js game, develops the game, and ensures the website is responsive and user-friendly. The AI will also make the game interactive and engaging for players, and provide a simple way for the owner to update the game or website content as needed. Write a Python script to create a website that hosts a three.js game, ensuring it follows the specified goals.

**Comment by chriscarrollsmith** [comment]
Had the same issue.

**Comment by Pwuts** [comment]
This is a problem with the output of the LLM. Sometimes it just does dumb things. Nothing we can do about that but wait for better LLMs to become available.
