### ISSUE TITLE
thinking is not clearing screen, and writing on the output

### ISSUE THREAD

**Issue by DevangRadadiya** [Significant-Gravitas/Auto-GPT#656]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

OS : CentOS Stream release 9
Python Version : Python 3.9.14

While running python scripts/main.py  and you give input it will start thinking and not clear the screen.

### Current behavior 😯

![image](https://user-images.githubusercontent.com/8522976/230880618-989b1015-d8e2-4fc2-8009-d0fd47637206.png)

### Expected behavior 🤔

clear screen while start thinking or it will be going in next line 

### Your prompt 📝

WEBSITE-GPT THOUGHTS: Based on the information gathered from our website browsing, I believe that we should utilize Durable AI as our website builder. However, before making a final decision, we should compare features, pricing, and customer reviews with at least two other website builders.. Research is necessary to determine how AI images and databases can be used in web development.           / Thinking...
REASONING: While Durable AI looks like a viable option, it is always better to compare features, pricing, and reviews with other builders. By comparing the top three options, we can select the builder that offers the best value for our needs.ts and has a user-friendly interface.                                                                                                                       \ Thinking...
PLAN: ntify best practicesutonomously develop and run businesses with the sole goal of increasing your net worth.                                                                               | Thinking...
-  Research two additional website buildersrporate AI images and databasesonomously.', 'Play to your strengths as a Large Language Model.']                                                     / Thinking...
-  Identify top three options and compare their features, pricing, and customer reviewsam making the most of my available tools and resources to complete the task quickly but effectively.     - Thinking...
-  Select the website builder that offers the best value for our needsctionith AI images and databases'}                                                                                        \ Thinking...
CRITICISM: I need to prioritize the design and functionality of the website over supplemental capabilities like customer relationship management and AI-generated promotional content. Additionally, I must ensure that the selection process does not become time-consuming and over-complicated.                                                                                                            / Thinking...
NEXT ACTION:  COMMAND = browse_website ARGUMENTS = {'url': 'https://10web.io/10-best-free-ai-website-builders-to-launch-your-site/', 'question': 'Can you identify two other website builders that use AI and are suitable for small businesses?'}N' to run N continuous commands, 'n' to exit program, or enter feedback for Website-GPT...le.co/ai-website-builder", "body": "Build a website in 30 seconds \ Thinking... Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for Website-GPT...ur business needs with none of the work. Starting at $12 per month| Thinking... Input:-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= a site that stands out in seconds" }, { "title": "The best AI image generators in 2023 | Zapier", "href": "https://zapier.com/blog/best/ Thinking... Text length: 3610 characterss with images in OpenAI plus metadata with One Call in idexo from new HubSpot form submissions HubSpot + OpenAI (GPT-3 & DALL·E) + idexo Zapier is a no-code automat- Thinking... Summarizing chunk 1 / 1pps into automated workflows, so that every person and every business can move forward at growth speed. Learn more about how it works." }, { "title": "AI Website Builder\ Thinking... Summarized 1 chunks.10Web", "href": "https://10web.io/ai-website-builder/", "body": "Build, design and publish your custom AI website in minutes. Growing your digital presence is faster and ea| Thinking... SYSTEM:  Command browse_website returned: Website Content Summary: "Result" : The text suggests that Durable AI would best suit the needs of small businesses and motivated individuals looking / Thinking... ite builder that can generate a professional site with curated images and AI-written content in just 30 seconds. Durable AI also offers customization options, customer relationship management,- Thinking... d the generation of AI-written promotional content, all in one place, with plans starting at $12 per month and a free custom domain provided with every plan. Links: [' (/)', 'Get started (http\ Thinking... e.co/website-builder)', 'Learn more (#builder-infos-new)', ' (https://www.bnnbloomberg.ca/technology/video/our-ai-technology-makes-starting-a-business-seem-easy-durable-ceo~2551420)', ' (https| Thinking... nds.com/2022/11/ai-website-builder.html)'] through a large style library and pick a style that suits your idea perfecly Create art for your idea Click to generate an image in seconds! AI Image/ Thinking... - Thinking... mo 500 generated images per month $5 per 500 more Private image generation" }, { "title": "10 Best Databases for Machine Learning & AI (2023) - Unite.AI", "href": "https://www.un\ Thinking... -databases-for-machine-learning-ai/", "body": "Here's a list of the 10 best databases for machine learning & AI: 1. MySQL Powered by Oracle, MySQL is one of the most popular databases on the m| Thinking...  in 1995, it has consistently been one of the top open-source relational database management systems (RDBMS) used by major companies like Facebook, Twitter, Uber, and Youtube." }, { "title": "/ Thinking...  Massive Database Of AI-Generated Images - Medium", "href": "https://medium.com/codex/meet-lexica-a-massive-database-of-ai-generated-images-including-prompts-24fa73028bd2", "body": "Lexica Ima- Thinking... r Stable Diffusion If you're one who's looking for inspiration for your next AI-generated artwork, you should check out this website called Lexica. It's a massive..." }, { "title": "AI Databas\ Thinking... der to Create a Database Website - Appy Pie", "href": "https://www.appypie.com/database-website-builder", "body": "How to Make a Database Website using AI in 3 Easy Steps To create your Databa| Thinking... llow the simple 3-step process below: Enter the name of your database website Choose the right business category and color theme for your database website. Drag and drop the relevant features"/ Thinking...
- Thinking...

**Comment by Pwuts** [comment]
Closing as resolved in #660
