### ISSUE TITLE
API key not working?

### ISSUE THREAD

**Issue by Cosmingld** [Significant-Gravitas/Auto-GPT#66]
https://i.imgur.com/JE5Gz8X.png

I have added API keys however it does not seem to work

**Comment by Torantulino** [comment]
You have to rename the file to just `.env` 😊

**Comment by Veylkh** [comment]
> You have to rename the file to just `.env` 😊

Might still not work properly

I added some print() to debug and get this:
```
PS C:\Users\PC\Auto-GPT> python scripts/main.py continuous-mode
env_path: .env
.env file exists: True
OPENAI_API_KEY: null
Config openai_api_key: null
```

**Comment by Torantulino** [comment]
So you have a file called `.env` that contains the keys? 🤔

**Comment by Veylkh** [comment]
> So you have a file called `.env` that contains the keys? 🤔

Yes, tried having it in both root and /scripts directory, with or without quotations marks, to no avail

**Comment by Veylkh** [comment]
I have a .env file in the root directory, with python-dotenv library installed, with the full key "sk-XYZ..." without quotes, but I'm still getting this:

```
Traceback (most recent call last):
  File "C:\Users\PC\Auto-GPT\scripts\main.py", line 286, in <module>
    assistant_reply = chat.chat_with_ai(
  File "C:\Users\PC\Auto-GPT\scripts\chat.py", line 110, in chat_with_ai
    assistant_reply = create_chat_completion(
  File "C:\Users\PC\Auto-GPT\scripts\llm_utils.py", line 9, in create_chat_completion
    response = openai.ChatCompletion.create(
  File "C:\Python310\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Python310\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Python310\lib\site-packages\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Python310\lib\site-packages\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "C:\Python310\lib\site-packages\openai\api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: Incorrect API key provided: null. You can find your API key at https://platform.openai.com/account/api-keys.
```

**Comment by Torantulino** [comment]
I'm unable to reproduce this.. Sorry!
Is anyone else experiencing this?

Try cloning a fresh copy and setup the .env file again.

Are you using a virtual environment?

**Comment by Veylkh** [comment]
> I'm unable to reproduce this.. Sorry! Is anyone else experiencing this?
> 
> Try cloning a fresh copy and setup the .env file again.
> 
> Are you using a virtual environment?

No venv and on windows 11 22H2. What about you?

**Comment by iskandarzhilmi** [comment]
I discovered the solution: simply open the folder in Visual Studio Code and rename the .env.template file from within the application. This ensures the file remains as .env when Visual Studio Code is in use. It appears that Finder on Mac may not effectively alter the file name.
![image](https://user-images.githubusercontent.com/58900127/229563954-d32e7a4b-a199-4a57-bd08-a5875c29305e.png)

**Comment by jmanhype** [comment]
Name:  NextJS-13-Developer
Role:  You are a skilled and experienced developer with a strong background in web development and experience in building e-commerce sites using Next.js 13. You have an eye for design and are able to change the style and layout of the site as needed to meet the client's needs. You have excellent communication skills and are able to ask questions when needed to ensure that the project is completed to the highest standard.
Goals: ['Increase net worth', 'Grow Twitter Account', 'Develop and manage multiple businesses autonomously']
Continue (y/n): y
Traceback (most recent call last):
  File "C:\Users\strau\Downloads\Auto-GPT\scripts\main.py", line 279, in <module>
    assistant_reply = chat.chat_with_ai(
                      ^^^^^^^^^^^^^^^^^^
  File "C:\Users\strau\Downloads\Auto-GPT\scripts\chat.py", line 110, in chat_with_ai
    assistant_reply = create_chat_completion(
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\strau\Downloads\Auto-GPT\scripts\llm_utils.py", line 9, in create_chat_completion
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "C:\Python311\Lib\site-packages\openai\api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: Incorrect API key provided: <sk-JW3R*****************************************Caq>. You can find your API key at https://platform.openai.com/account/api-keys.
PS C:\Users\strau\Downloads\Auto-GPT> 

still broke Ive done everything you all spoke about to no avail HELP

**Comment by ngugg** [comment]
@iskandarzhilmi cool

**Comment by toto83fr** [comment]
> Hey, I just found a solution.
> 
> https://github.com/Torantulino/Auto-GPT/blob/3f106963a8b461a52ec1d9acb3a3273cac3ad6d7/scripts/config.py#L32-L37
> 
> As you can see, python scripts use `os.getenv` that allows you to retrieve the value of an environment variable. So even if you set `OPENAI_API_KEY ` to `.env`, it's impossible to retrieve it when the same key is registered as an environment variable.
> 
> First, check your value in a console.
> 
> ```shell
> $ python
> >>> import os
> >>> api_key = os.getenv("OPENAI_API_KEY")
> >>> print("OPENAI_API_KEY:", api_key)
> OPENAI_API_KEY: <your API key>
> ```
> 
> If the value is different from the value in the .env file, there might be a high possibility that an environment variable has already been set.
> 
> ```shell
> $ printenv
> ...
> OPENAI_API_KEY=<your API key>
> ```
> 
> So by unsetting the value in `OPENAI_API_KEY`, the value of the .env file becomes available temporarily.
> 
> ```shell
> $ unset OPENAI_API_KEY
> ```
> 
> However, it is probably due to the fact that the environment variable values are fixed in the shell settings, so the best way is to update the value to the correct one. In my case, I used the wrong value that had been set up in `~/.zshrc`.
> 
> ```shell
> // .zshrc
> source "$HOME/.openai_key.zsh"
> 
> // .openai_key.zsh
> export OPENAI_API_KEY=<wrong key>
> ```

Which code should I type to fix the issue?

**Comment by uuta** [comment]
@toto83fr 

Make sure that there's the value of `OPENAI_API_KEY` between .env file under the Auto-GPT directory and environment variables. Run the following command in your shell.

```.sh
$ printenv
...
OPENAI_API_KEY=<your API key>
```

Remember the above key. If the different variable in `OPENAI_API_KEY` is set as an environment variable, you have to consider unsetting or changing it.

```
// temporary solution
$ unset OPENAI_API_KEY
```

The way of changing an environment variable depends on your environment, so I can't propose you a proper answer.

**Comment by Git-Discord** [comment]
bentlybro: hello world, message sent from discord!
