### ISSUE TITLE
Getting an error everytime i give human feeback on Auto GPT

### ISSUE THREAD

**Issue by TJ0110** [Significant-Gravitas/Auto-GPT#671]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

![image](https://user-images.githubusercontent.com/108982112/230901597-f8e7e7ec-0f6b-4f9d-98af-9fbc1fc11af1.png)

### Current behavior 😯

Instead of behaving like a normal script to add information to the GPT module it gives an error

**Comment by blankster** [comment]
I share the same fate

**Comment by onekum** [comment]
This is an issue with the model, I believe, and it's more common with `GPT-3.5`. Getting human feedback breaks it much of the time. For the time being, it's best to try to get the AI to run as autonomously as possible.

**Comment by Wladastic** [comment]
I wrote a fix for that.
My code is messy though. Feel free to checkout the pullrequest.
https://github.com/Torantulino/Auto-GPT/pull/697

**Comment by Vwing** [comment]
If you tell it "only respond in JSON" in your human feedback, it works every time (that I've tried it). Makes me think the fix could be as simple as appending that to every human feedback message.

**Comment by Slowly-Grokking** [comment]
> If you tell it "only respond in JSON" in your human feedback, it works every time (that I've tried it). Makes me think the fix could be as simple as appending that to every human feedback message.

Every time human feedback is given it returns "invalid JSON" though, so you're not having the same problem as everyone else.

**Comment by TheAIAdopter** [comment]
Same problem here.

**Comment by Pwuts** [comment]
Closing as this is a problem with the LLM, not with Auto-GPT
