### ISSUE TITLE
Incorrect placement of cfg = Config() on line 290 of main.py

### ISSUE THREAD

**Issue by garythebat** [Significant-Gravitas/Auto-GPT#679]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

I was getting the following error:

"File "C:\Users\gary\Auto-GPT\scripts\main.py", line 290, in <module>
    check_openai_api_key()
  File "C:\Users\gary\Auto-GPT\scripts\main.py", line 22, in check_openai_api_key
    if not cfg.openai_api_key:
           ^^^
NameError: name 'cfg' is not defined"

I solved it by moving cfg = Config() to line 290  

# TODO: fill in llm values here
cfg = Config()
check_openai_api_key()
parse_arguments()

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by blankster** [comment]
Already fixed in 7547d9bfb161fac31400f7aa3acb8f14e139ee39
