### ISSUE TITLE
Invalid Syntax (line 43 main.py)

### ISSUE THREAD

**Issue by petragom** [Significant-Gravitas/Auto-GPT#682]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

I cloned the github directory and changed the .env file. When I try to run main.py I get an error and it stops. I didn't change anything in that file. (in case it changes the layout, the arrow is under the last ")

I'm using an iMac Intel

### Current behavior 😯

Me@MyMac Auto-GPT % python scripts/main.py --gpt3only
  File "scripts/main.py", line 43
    speak.say_text(f"{title}. {content}")
                                                            ^
SyntaxError: invalid syntax

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by ylluminate** [comment]
Having similar problem here, however this particular problem is from using an old python:
```
$ python --version
Python 2.7.18
```
If I modify to use the appropriate python 3:
```
$ python3 --version                                                                                                         
Python 3.11.3
```

I still have this:
```
Traceback (most recent call last):
  File "~/dev/Auto-GPT/scripts/main.py", line 3, in <module>
    import commands as cmd
  File "~/dev/Auto-GPT/scripts/commands.py", line 1, in <module>
    import browse
  File "~/dev/Auto-GPT/scripts/browse.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by Torantulino** [comment]
Have you installed `requests`? @ylluminate 

Remember to install the requirements file:

`pip install -r requirements.txt`

**Comment by petragom** [comment]
Yes, I installed the requests

**Comment by ylluminate** [comment]
Lol, I did, but I inadvertently ran `python` (copy-paste-brain) sans `python3`. Now with `python3` it's working.

**Comment by Wuksh** [comment]
> Lol, I did, but I inadvertently ran `python` (copy-paste-brain) sans `python3`. Now with `python3` it's working.
> 
> I think we need to help macOS users by mentioning `python3` vs `python` since it's the status quo for Homebrew and MacPorts it seems generally:
> 
> ```
> python3 -m pip install -r requirements.txt
> ```

Thank you <3
