### ISSUE TITLE
 AttributeError: module 'chat' has no attribute 'chat_with_ai'

### ISSUE THREAD

**Issue by Aopenz** [Significant-Gravitas/Auto-GPT#683]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

when i use GPT3.5 Only Mode...

 @Torantulin

### Current behavior 😯

when i use GPT3.5 Only Mode...
/Auto-GPT/scripts/main.py", line 318, in
assistant_reply = chat.chat_with_ai(
^^^^^^^^^^^^^^^^^
AttributeError: module 'chat' has no attribute 'chat_with_ai'

### Expected behavior 🤔

nothing

### Your prompt 📝

```yaml
# Paste your prompt here
````

**Comment by Torantulino** [comment]
Likely related #684

**Comment by Aopenz** [comment]
@Torantulino tested the method #676, but it did not solve

**Comment by Aopenz** [comment]
I tested the update of the master file 5 minutes ago, but it still reports the same error @Torantulino

**Comment by Torantulino** [comment]
Taking a look

**Comment by Torantulino** [comment]
How about now?
Did #695 fix this?

**Comment by Aopenz** [comment]
Traceback (most recent call last):
  File "/Users/Allen/Auto-GPT/scripts/main.py", line 318, in <module>
    assistant_reply = chat.chat_with_ai(
                      ^^^^^^^^^^^^^^^^^^
  File "/Users/Allen/Auto-GPT/scripts/chat.py", line 74, in chat_with_ai
    if cfg.debug_mode:
       ^^^^^^^^^^^^^^
AttributeError: 'Config' object has no attribute 'debug_mode'. Did you mean: 'set_debug_mode'?
@Torantulino

**Comment by blankster** [comment]
I can confirm @Aopenz and face the same problem even after 4d42e14d3d3db3c64f1df0a425f5c3460bc82a56

**Comment by Aopenz** [comment]
Retried as per #695 and the problem is solved, thanks. @Torantulino @blankster

**Comment by blankster** [comment]
@Aopenz I needed to do a 

`git reset --hard origin/master`

but then it worked.
