### ISSUE TITLE
Local Stable Diffusion as image provider

### ISSUE THREAD

**Issue by Artemonim** [Significant-Gravitas/Auto-GPT#708]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

I can run Stable Diffusion on my local machine and use it through the [Stable Diffusion WebUI](https://github.com/AUTOMATIC1111/stable-diffusion-webui). It would be great to be able to use this to generate an image in Auto-GPT instead of Dalle or Huggingface API.

### Examples 🌈

Set the global goal "Portrait of a girl in a garden"
Goal 1: Come up with a description of a girl in a garden
Goal 2: Format it to the Stable Diffusion prompt format
Goal 3: Submit the request to the locally running instance of Stable Diffusion, wait for the response
Goal 4: Show the result to the user.

### Motivation 🔦

- Possibility of more fine-tuning Stable Diffusion.
- If the local GPU is faster than the public one, Auto-GPT will be faster.
- Fewer dependencies on services that do not belong to the Auto-GPT user.

**Comment by Artemonim** [comment]
I need a workflow where Auto-GPT will only affect prompt and negaive prompt, and all other settings will be preset manually. I admit that Auto-GPT can guess the other parameters from the Internet guides, but I doubt the quality of the result.

**Comment by vandervoortj** [comment]
> I think having the option of additional access to local models to save on API calls is an excellent value add.

In my testing of a local fork of babyagi I have, Vicuna makes for a valid substitute for gpt-3.5-turbo.

**Comment by Artemonim** [comment]
> Create a Long Time Storage

Shouldn't we use Pinnacle for something like this? (but I haven't figured out how to do it yet)

**Comment by AsaTyr2018** [comment]
i perfer a local longtime storage since its faster in access then a remote. DSGvO also in mind ^^

**Comment by Qoyyuum** [comment]
Stable Diffusion is already implemented. Please use the latest stable release and try again. Thanks.
