### ISSUE TITLE
Is vision functionality already supported / integrated via its use of GPT-4?

### ISSUE THREAD

**Issue by ylluminate** [Significant-Gravitas/Auto-GPT#710]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

I'm not yet clear as to whether GPT-4 in context of this system is utilizing the vision functionality to analyze graphics, schematics and data, etc. It seems to be missing large portions of information and seems to have an inability to make inferences based on such that should exist when asking it to reviews specific websites or images.

I'm hoping that you might be able to clarify this or help us to understand how we could ensure that it does do this if available already.

**Comment by Dr33dM3** [comment]
you should close this issue and make a disscussion on the github repo it is not using vision functionality for your information. It can't as openai api for gpt-4 doesn't support visual input.

**Comment by ylluminate** [comment]
> you should close this issue and make a disscussion on the github repo as it is not using vision functionality. It can't as openai api for gpt-4 doesn't support visual input.

Here you go: https://github.com/Torantulino/Auto-GPT/discussions/832
