### ISSUE TITLE
Question on ChatGPT API version

### ISSUE THREAD

**Issue by innerop** [Significant-Gravitas/Auto-GPT#721]
Can I use this with ChatGPT3.5 API?

OpenAI is very slow to grant some of us API key for v4, and no idea how long it will take them to release it to everyone.

**Comment by Timmytim1976** [comment]
> Can I use this with ChatGPT3.5 API?
> 
> OpenAI is very slow to grant some of us API key for v4, and no idea how long it will take them to release it to everyone.

Yes this works with ChatGPT 3.5. If you don't have access to the GPT4 api, this mode will allow you to use Auto-GPT!" Just start Auto-GPT with "python scripts/main.py --gpt3only"
