### ISSUE TITLE
Suggestion: Add a batch script to launch Autogpt program with a double-click

### ISSUE THREAD

**Issue by gmirsky2** [Significant-Gravitas/Auto-GPT#722]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

# Batch Script to Launch AutoGPT

This batch script allows you to launch AutoGPT with a double-click on Windows.

This automates the process of running a Python script on Windows.
It searches for the installed Python interpreter and executes the script if it exists in the same directory as the batch file. 
It Finds the installed Python interpreter automatically, reducing the need for manual configuration. 
It Executes the script if it exists in the same directory as the batch file, making it easier to manage the script files.

Confirmed working on my system with the following specifications:

- **OS Name:** Microsoft Windows 10 Pro
- **OS Version:** 10.0.19044 N/A Build 19044
- **OS Manufacturer:** Microsoft Corporation
- **OS Configuration:** Standalone Workstation
- **OS Build Type:** Multiprocessor Free
- **System Type:** x64-based PC
- **BIOS Version:** American Megatrends Inc. L3.24, 6/4/2019
- **System Locale:** en-us;English (United States)
- **Processor(s):** AMD64 Family 23 Model 8 Stepping 2 AuthenticAMD ~3700 Mhz
- **Total RAM Memory:** 32GB
- **Graphics:** NVIDIA GeForce GTX 1660 Ti
- **Total GPU Memory:** 6GB

_The script assumes that the Python executable is in the system path. If the Python executable is not in the path, the script will not be able to find it._

_The script assumes that the main Python script is in the same directory as the batch file. If the main script is located in a different directory, the script will not be able to find it._

### Examples 🌈

this is located in `\Auto-GPT-master\run.bat`

[run.bat]
```
@echo off

setlocal

set "python_exe="
for %%a in (python.exe python3.exe python3.8.exe python3.9.exe python3.10.exe python3.11.exe) do (
    for /f "tokens=*" %%b in ('where %%a 2^>nul') do set "python_exe=%%b"
    if defined python_exe goto :found
)

:found
if not defined python_exe goto error

if not exist "scripts\main.py" goto error

pushd "%~dp0"
if "%OS%"=="Windows_NT" (
    start "" "%python_exe%" "scripts\main.py"
) else (
    "%python_exe%" "scripts\main.py"
)
popd

endlocal
exit /b 0

:error
echo Error: Python interpreter or script not found.
echo Please install Python 3.x and ensure that the main script exists in the same directory as this batch file.
exit /b 1
```
GPT3.5 Only Mode:  ENABLED
```
pushd "%~dp0"
if "%OS%"=="Windows_NT" (
    start "" "%python_exe%" "scripts\main.py" --gpt3only
) else (
    "%python_exe%" "scripts\main.py" --gpt3only
)
popd
```

I also added the following line to the top of your main.py script:
```
import ctypes
ctypes.windll.kernel32.SetConsoleTitleW("Torantulino/Auto-GPT")
```
This will use the Windows API to set the console window title to `"Torantulino/Auto-GPT"`.

### Motivation 🔦

As a lazy person, I find it exhausting to have to type out commands every time I want to use the AutoGPT program. The physical exertion required to lift my fingers and press keys on the keyboard is simply too much to bear. :weary: I yearn for a world where I can generate text effortlessly, without having to expend any energy whatsoever. That's why I created this batch script - to save my precious finger muscles from unnecessary strain. :muscle: I believe that all users of AutoGPT should have the option to launch the program with a simple double-click, so that we can conserve our energy for more important tasks, like breathing and blinking. :sunglasses:

**Comment by LericDax** [comment]
This would be a helpful addition for introducing the tool to larger audiences and adding convenience.

**Comment by Pwuts** [comment]
Closing as stale
