### ISSUE TITLE
No uniform output file location

### ISSUE THREAD

**Issue by drbree82** [Significant-Gravitas/Auto-GPT#730]
I asked AutoGPT to rewrite Autogpt to work with Vicuna instead of OpenAI API.
I asked it to create a folder and put the output in there. I also asked it to make the code executable using python.
It created the folder and a bunch of files in there, it generated an instruction text file, but it didn't create a main.py or an exe file to actually run the script.
The instruction file also seems to be AutoGPT instructing itself, not actual instructions for the user.

Sorry if the issue isn't well written, I'm just on a chromebook now. If @Torantulino wants any code samples or tree output, let me know. I can also line up a remote session over your choice of video conference tool if need be.

**Comment by halfprice06** [comment]
This is pretty much expected behavior at this stage of the project lol.
