### ISSUE TITLE
Long-term memory via vector database

### ISSUE THREAD

**Issue by engma-linguistics** [Significant-Gravitas/Auto-GPT#74]
https://www.mlq.ai/gpt-4-pinecone-website-ai-assistant/

Using a vector database like Pinecone, a user ought be able to store memory for the 'bot and query it as needed.

**Comment by jantic** [comment]
GREAT idea.  Reason why this is great to clarify for others:  It'll make much more efficient use of limited context window when calling GPT to restrict what's loaded into there from long term memory to be stuff that is likely most relevant. And it'll allow for pretty much indefinite length of long term memory that can be used. Think of this as an "associative memory", where the association comes from figuring out what in long term memory is closest in conceptual space compared to the current context.

**Comment by ryanpeach** [comment]
Seconded. I think this is a must.

**Comment by dschonholtz** [comment]
I have a PR for this see https://github.com/Torantulino/Auto-GPT/pull/122

**Comment by ResourceHog** [comment]
Found this open source vector db https://github.com/spotify/annoy , thoughts?

**Comment by StableInquest** [comment]
#769

**Comment by chyezh** [comment]
> also this, https://github.com/milvus-io/milvus

i have a PR for this, #801

**Comment by richbeales** [comment]
implemented
