### ISSUE TITLE
Add `1/0` as alternative to `y/n`

### ISSUE THREAD

**Issue by Artemonim** [Significant-Gravitas/Auto-GPT#753]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Add `1/0` as alternative to `y/n`

### Examples 🌈

So in
`Continue (y/n)` and `Enter \'y\' to authorise command, \'y -N\' to run N continuous commands, \'n\' to exit program`
we can use
`Continue (1/0)` and `Enter \'1\' to authorise command, \'1 -N\' to run N continuous commands, \'0\' to exit program`

### Motivation 🔦

A user can communicate with Auto-GPT in a language other than English that does not contain the letters `y`, `n`. In this case, the user have to change the keyboard layout between simple and text response to English and back. The numbers are (most likely) the same in any layout.

**Comment by edcohen08** [comment]
Have pr #3178
