### ISSUE TITLE
NEXT ACTION:  COMMAND = write_to_file ARGUMENTS = {'file': 'catjokes.txt'} SYSTEM:  Command write_to_file returned: Error: 'text'

### ISSUE THREAD

**Issue by drbree82** [Significant-Gravitas/Auto-GPT#756]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Run main.py

Set goal of writing 20 jokes

set goal 'Save jokes to a txt file' (I used catjokes.txt)

set goal stop

### Current behavior 😯

`SYSTEM:  Command write_to_file returned: Error: 'text'
CATJOKER THOUGHTS: I will create 20 witty and funny original cat jokes using the inspiration and ideas from the previous browse_website command results and the popular cat jokes and memes on the internet. I will then use the 'write_to_file' command to store these jokes for future use.
REASONING: Since the previous browse_website command returned a collection of 60 cat memes, it served as a source of inspiration for me to create some original content. The web is abundant in cat memes, and combining the popular jokes with my own unique style and perspective can potentially result in original and enjoyable content for others to enjoy. The jokes I have written must be stored in a file for future use
PLAN: 
-  Write 20 witty and funny original cat jokes using the inspiration and ideas from the previous browse_website command results and the popular cat jokes and memes on the internet.\\n- Save the 20 original jokes using the 'write_to_file' command.
CRITICISM: I must ensure that the jokes I write are original, creative, and witty, and that they will not offend anybody's sensibilities. Additionally, I must make sure that the file is stored in the correct directory with a suitable naming convention, so I am able to access and use the jokes in future.
NEXT ACTION:  COMMAND = write_to_file ARGUMENTS = {'file': 'cat_jokes.txt'}
SYSTEM:  Command write_to_file returned: Error: 'text'
CATJOKER THOUGHTS: From the search results, I found some credible web pages with popular cat jokes and memes. I will use them to generate some original cat jokes. I can use the 'write_to_file' command to save my jokes to a file.
REASONING: The previous search has generated some good sources of cat jokes and memes. I can explore the web pages and collect some ideas to create original cat jokes. Once I have created valuable content, it's necessary to store it using the 'write_to_file' command to use it later on.
PLAN: 
-  Explore websites and copy down popular cat jokes and memes\n- Write 20 cat jokes by modifying and improving popular cat jokes \n- Use 'write_to_file' command to save the 20 original cat jokes\\n
CRITICISM: I must ensure that the jokes are funny, creative and original so that people can enjoy them. I must store the file in a safe directory to avoid losing the jokes.
NEXT ACTION:  COMMAND = write_to_file ARGUMENTS = {'file': 'catjokes.txt'}
SYSTEM:  Command write_to_file returned: Error: 'text'`

The  response is always "NEXT ACTION:  COMMAND = write_to_file ARGUMENTS = {'file': 'catjokes.txt'}
SYSTEM:  Command write_to_file returned: Error: 'text'"

### Expected behavior 🤔

Not sure, but probably not an error

### Your prompt 📝

```yaml
ai_goals:
- write 20 cat jokes
- save them to catjokes.txt
- stop
ai_name: catjoker
ai_role: making cat jokes

```

**Comment by BillSchumacher** [comment]
Looks like it's missing the argument with the contents, try giving it some feedback.
