### ISSUE TITLE
"str is not valid UTF-8: surrogates not allowed" after "y -10" command

### ISSUE THREAD

**Issue by coolk8** [Significant-Gravitas/Auto-GPT#778]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

1. Run Auto-GPT as Docker image via VS Code.
2. Provide goals for Auto-GPT.
3. Write "y" command few times.
4. Write "y -10" command few times.
5. Suddenly Auto-GPT fails after another "y -10" command
6. Auto-GPT terminated

### Current behavior 😯

```txt
NEXT ACTION:  COMMAND = start_agent ARGUMENTS = {'name': 'DiplomacyChallengeSolver', 'task': 'placeholder'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for Peacemaker-AI...
Input:y -10

**Traceback (most recent call last):
  File "/app/main.py", line 406, in <module>
    memory.add(memory_to_add)
  File "/app/memory/local.py", line 64, in add
    out = orjson.dumps(
          ^^^^^^^^^^^^^
TypeError: str is not valid UTF-8: surrogates not allowed**
```

### Expected behavior 🤔

1. No exception after "y -10" command
2. Workaround for this type of exception to prevent Auto-GPT from termination

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Pwuts** [comment]
Is this still an issue with the latest version?

**Comment by NeKum** [comment]
I have the same problem

**Comment by ZaynJarvis** [comment]
same here, after typing `y`

**Comment by Pwuts** [comment]
Can one of you add a `pprint` to dump the content of `self.data` on line 89 here, reproduce the issue, and post the output?
https://github.com/Significant-Gravitas/Auto-GPT/blob/14d3ecaae75a80f03cd118b5767e1c6affb4e3cc/autogpt/memory/local.py#L88-L89

**Comment by ZaynJarvis** [comment]
> Can one of you add a `pprint` to dump the content of `self.data` on line 89 here, reproduce the issue, and post the output?
> 
> https://github.com/Significant-Gravitas/Auto-GPT/blob/14d3ecaae75a80f03cd118b5767e1c6affb4e3cc/autogpt/memory/local.py#L88-L89

trying to reproduce error, I didn't find a pattern that will 100% trigger the issue

**Comment by ido777** [comment]
I have a fix for this (+ test), however, I never committed to the repo, so I luck some instructions.
Here is what I need
1) How do I get permission to push a new branch to the repo?
2) Which branch should I rebase from, and to which branch should I open the pull request?

**Comment by Nikoxes70** [comment]
On a macOS my solution was to grant a Full Disk Access from the terminal.app
Go to "System Settings" -> "Privacy & Security" -> "Full Disk Access", 
press the plus icon and add the Terminal.app to the list.
