### ISSUE TITLE
variable 'assistant_thoughts_reasoning' referenced before assignment

### ISSUE THREAD

**Issue by 0xech0** [Significant-Gravitas/Auto-GPT#78]
After getting it installed (i think) correctly, i'm now getting this response for any goal used:

....scripts/main.py", line 81, in print_assistant_thoughts assistant_thoughts_reasoning) UnboundLocalError: local variable 'assistant_thoughts_reasoning' referenced before assignment
Warning: Failed to parse AI output, attempting to fix.

**Comment by PhilipAD** [comment]
I moved the below exception in main.py to the bottom and it works fine
```
  except Exception as e:
                    assistant_thoughts_text = "The AI's response was unreadable."
# Speak the assistant's thoughts
```
