### ISSUE TITLE
Prompt Seeder - After setting up roal and goals, generate a seed prompt

### ISSUE THREAD

**Issue by Wladastic** [Significant-Gravitas/Auto-GPT#785]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Right now Auto-GPT does not provide any feedback on the goals and role etc.

To make sure it understood the assignment, it would be much better for it to reinterpret the prompt.

That way it's more of a dialogue than just an assignment that get's never updated.

Also adding another prompt command "reevaluate_assignment" or something would be great then.

### Examples 🌈

I already instructed Auto-GPT to build such a script,
it didn't finish and started doing that weird gpt-2 clone and tryint to execute gpt-2 training.

But this script kindda made sense:

``` analyze_code.py
import yaml
from typing import List

def analyze_code(code: str) -> List[str]:
    try:
        with open('ai_settings.yaml', 'r') as file:
            ai_settings = yaml.safe_load(file)
            current_goals_dict = ai_settings['ai_goals']
            current_goals = list(current_goals_dict.values())
    except FileNotFoundError:
        return ['Error: ai_settings.yaml file not found.']
    except yaml.YAMLError:
        return ['Error: ai_settings.yaml file is not valid YAML.']
    
    try:
        with open('new_goals.txt', 'r') as file:
            new_goals = [goal.strip() for goal in file.readlines()]
    except FileNotFoundError:
        return ['Error: new_goals.txt file not found.']
    
    revised_goals = list(set(current_goals) | set(new_goals))
    
    revised_goals_dict = {'goal'+str(i): goal for i, goal in enumerate(revised_goals)}
    ai_settings['ai_goals'] = revised_goals_dict
    
    try:
        with open('ai_settings.yaml', 'w') as file:
            yaml.dump(ai_settings, file)
            return ['Updated goals:'] + revised_goals
    except:
        return ['Error: failed to write to ai_settings.yaml file.']
```

**Comment by lc0rp** [comment]
Interesting. I'm not sure how to categorize this - should we add it to the discussion board as an idea? Also, have you made any progress on a draft PR/proposal?

Since this was initially opened, AutoGPT has undergone some modifications, and new plugins like the planner may have similar features. Do you think it's worth keeping this open?
