### ISSUE TITLE
AutoGTP tries to load Website with load_file command

### ISSUE THREAD

**Issue by thepok** [Significant-Gravitas/Auto-GPT#791]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

After it googled, it tried to open wikipedia this way...

NEXT ACTION:  COMMAND = read_file ARGUMENTS = {'file': 'https://en.wikipedia.org/wiki/Dyson_sphere'}

### Your prompt 📝

ai_goals:
- write a novel story with about 20 pages about a dyson sphare
ai_name: NovelAI
ai_role: an AI designed to write scifi novels

**Comment by Pwuts** [comment]
The LLM can occasionally hallucinate or do dumb things. Not a direct issue with Auto-GPT.

**Comment by Qoyyuum** [comment]
Hi @thepok since its not an issue of Auto-GPT, I'll close this issue. The repo has made several more changes since this issue was last opened. Can you try again and perhaps add the log file for dev's reference? Thanks.
