### ISSUE TITLE
windows error while running my local latest version 

### ISSUE THREAD

**Issue by maljefairi** [Significant-Gravitas/Auto-GPT#809]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Using memory of type: LocalCache
Traceback (most recent call last):
  File "C:\Users\nethe\OneDrive\Desktop\Auto-GPT-master\scripts\main.py", line 321, in <module>
    assistant_reply = chat.chat_with_ai(
                      ^^^^^^^^^^^^^^^^^^
  File "C:\Users\nethe\OneDrive\Desktop\Auto-GPT-master\scripts\chat.py", line 67, in chat_with_ai
    if cfg.debug:
       ^^^^^^^^^
AttributeError: 'Config' object has no attribute 'debug'

### Current behavior 😯

the script asks me for the goals then stops and show this error

### Expected behavior 🤔

to run the script

### Your prompt 📝

```yaml
# Paste your prompt here
```

PS C:\Users\nethe\OneDrive\Desktop\Auto-GPT-master\scripts> python main.py --continuous
Continuous Mode:  ENABLED
WARNING:  Continuous mode is not recommended. It is potentially dangerous and may cause your AI to run forever or carry out actions you would not usually authorise. Use at your own risk.
Welcome back!  Would you like me to return to being huggingface backup keeper?
Continue with the last settings?
Name:  huggingface backup keeper
Role:  Develop and run a Python script to backup huggingface models locally
Goals: ['Find and download the best script to save huggingface models to Z:\\hfmodels\\models1', 'read them then Write a better backup script based on research', 'Name the new script besthf.py', 'Ensure the script is running smoothly and continuously update it', 'Exit']
Continue (y/n): y
Using memory of type: LocalCache
Traceback (most recent call last):
  File "C:\Users\nethe\OneDrive\Desktop\Auto-GPT-master\scripts\main.py", line 321, in <module>
    assistant_reply = chat.chat_with_ai(
                      ^^^^^^^^^^^^^^^^^^
  File "C:\Users\nethe\OneDrive\Desktop\Auto-GPT-master\scripts\chat.py", line 67, in chat_with_ai
    if cfg.debug:
       ^^^^^^^^^
A

**Comment by tlnet1981** [comment]
same here

**Comment by Cralins** [comment]
https://github.com/Torantulino/Auto-GPT/issues/803 already saloved

**Comment by maljefairi** [comment]
i downloaded the latest version again and it was not fixed

**Comment by Cralins** [comment]
> i downloaded the latest version again and it was not fixed

Read the post man u need to manualy chnage in the code
