### ISSUE TITLE
stuck at thinking

### ISSUE THREAD

**Issue by gibson06** [Significant-Gravitas/Auto-GPT#819]
### Duplicates

- [X] I have searched the existing issues

**Comment by PedzacyKapec** [comment]
Same here

**Comment by SamPink** [comment]
I get this often too. Auto-gpt gets distracted from its goals and just keeps researching things

**Comment by mousberg** [comment]
Same issue here, anyone has managed to solve?

**Comment by AdalWay** [comment]
same here

**Comment by cashijo-vs** [comment]
@mousberg free trial account of what? where did you update your billing information and payment method?

**Comment by mousberg** [comment]
> @mousberg free trial account of what? where did you update your billing information and payment method?

on the OpenAI API website. follow the "OpenAI API Keys Configuration" section on the tutorial

**Comment by HCLIF** [comment]
Was able to fix it by adding a payment method to OpenAI's API website https://platform.openai.com/account/billing/overview hope this helps

**Comment by cashijo-vs** [comment]
> > @mousberg free trial account of what? where did you update your billing information and payment method?
> 
Yes, this worked for me. Thank you.

**Comment by cashijo-vs** [comment]
> on the OpenAI API website. follow the "OpenAI API Keys Configuration" section on the tutorial
Thanks, this worked.

**Comment by cashijo-vs** [comment]
> > @mousberg free trial account of what? where did you update your billing information and payment method?
> 
> on the OpenAI API website. follow the "OpenAI API Keys Configuration" section on the tutorial

Thanks, this worked.

**Comment by Hoerli1337** [comment]
> Was able to fix it by adding a payment method to OpenAI's API website https://platform.openai.com/account/billing/overview hope this helps

I do not have a credit card. Are there other possibilities?
