### ISSUE TITLE
option to support other languages [Feature request]

### ISSUE THREAD

**Issue by xpghard** [Significant-Gravitas/Auto-GPT#82]
option to add a translation file, or the user can use the api from https://www.deepl.com/
I would be happy to assist in making an entire file of translations into other languages.

**Comment by xpghard** [comment]
> Please tell me how to keep the AI's thoughts in English and translate only the output?

The openai itself works in different languages. I was more concerned with adding options on the code side.

**Comment by Qoyyuum** [comment]
Closing this issue as a duplicate and in favor of #1563
