### ISSUE TITLE
Save state / continue later

### ISSUE THREAD

**Issue by TheAIAdopter** [Significant-Gravitas/Auto-GPT#822]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

I searched and couldn't find anything similar while i'm pretty sure it been requested before, I appologize in advance if i'm duplicating
Would be great to have a way to restart where it left when there is an issue.  I couldn't find howe to do this

### Motivation 🔦

Would be time saver to be able to restart where it left. Almost every long project i tried failed before it finished

**Comment by psvensson** [comment]
I second this. There's a PR for caching and essentially memofying already sent requests to the GPT API, but it would also be nice if we could choose when/if to erase the Pinecone data (and the Redis erase would be nice to have as a separate command or CLi flag too)

**Comment by TheAIAdopter** [comment]
> I second this. There's a PR for caching and essentially memofying already sent requests to the GPT API, but it would also be nice if we could choose when/if to erase the Pinecone data (and the Redis erase would be nice to have as a separate command or CLi flag too)

Can you please point me to some info about that? I would really like to be able to do something like that.  what can be done exactly with this PR?   sorry i'm new to this and i'm on a learning curve....

**Comment by hanskraut31312312** [comment]
My project always exit or crash before finishing. They are longer. It is impossible for me to get smth done in 1 day. I think a system where Auto GPT writes down issues milestones and priority sorts in 3 txt files and then always every 30 minutes sorts and reads them would maybe help for longer projects. Even if AutoGPT loses some progress at least he can continue!

**Comment by Stunspot** [comment]
I have yet to see auto-gpt successfully complete anything. I've seen it claim to, but it always falls over at the end and never writes anything to disk. I'm pretty annoyed at the compute money I spent.

**Comment by Stunspot** [comment]
Oh I can get it to do all kinds of crap, I just can't make it write a file to disk that isn't some kind of hallucination.

**Comment by Boostrix** [comment]
> I can make autogpt do simple tasks, more complex tasks have thus far ended in donothing loops, or had charmap encoding issues.
[...]
> If anyone has completed complex tasks, they must have fixed bugs like the do_nothing loop without sharing them, or they are not sharing their prompting/goal crafting strategy that is yielded them good results.

That is why I suggested elsewhere (https://github.com/Significant-Gravitas/Auto-GPT/issues/1359#issuecomment-1528955732) to create new directories as part of the project so that the community can share working/non-working "ai_settings.yaml" files to see/compare results.

Some of the things that I could make it complete with little effort were:
- create a directory named FOO, use this as the working directory
- create a new file named FOO/main.cc to compute the first 1024 prime numbers
- create the corresponding FOO/CMakeLists.txt file for cmake including unit tests 
- run/test the program, exit if successful
