### ISSUE TITLE
More clarity on Redis storage, retention between sessions and argument for clearing for new topics

### ISSUE THREAD

**Issue by ylluminate** [Significant-Gravitas/Auto-GPT#831]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Currently the Redis functionality is not "crystal clear" insomuch that while I have the impression that it can be used to retain knowledge acquired between Auto-GPT program/script executions in order to establish some level of associative cross pollination between sessions, but whether or not it actually does and/or uses this is not clear.

Could we have some additional information and clarity on this topic?

Also, if it does utilize and work together with this, could we, instead of having a .env configuration variable, have in its place a command line argument or simply use the session name as a key generator to retain associativity? 

For example, if want to retain memory associations, maybe a convention such as this could be done: For the name, if we have "Entrepreneur-GPT" then any future names, even with different roles and goals but with the same "Entrepreneur-GPT" name could have a memory index keyed to that name numerically through a simple algorithm that will use that to associatively operate. Or, to make it more flexible perhaps use "Entrepreneur-GPT" and then use a sub name to clarify intention or associations such as "Entrepreneur-GPT_first-run" or even have an additional prompt asking for subtask name.

If this is all just too complex for the current goals or intentions, perhaps a simple command line argument is appropriate of `--clear-memory` instead of having a `WIPE_REDIS_ON_START` within the .env.

Please let me know if this is clear or if further discussion is needed.

### Motivation 🔦

The goal is to retain or leverage multiple sessions knowledge acquisition in an associative and amplifying way, but while retaining proper context isolated to related "dives" into the topic or goal.

**Comment by ylluminate** [comment]
On further investigation, it appears that `MEMORY_INDEX=whatever` could or perhaps should be modified each time to the name of the actual project that's being created. So instead of `whatever` it could or should say `MySession-GPT-Name` or such instead and changed each time associations need to be changed. If this is the case, perhaps a command line argument for setting the name should be used instead of having an in-script prompt. Thus run this with:
```
python3 scripts/main.py --name MySession-GPT-Name --speak
```
This would subsequently have the following effect:
1. Start a new session vs offering to resume, unless name is the same and then it would indeed resume.
2. Name the session/experience the name given.
3. Assign `MEMORY_INDEX` to this name for isolation.

Does this make sense?

**Comment by hanskraut31312312** [comment]
"Error creating Redis search index:  Index already exists
Using memory of type: RedisMemory" 

this happened ever since i installed redis. Does it hurt stuff? Should I uninstall docker and redis and wait until a fix is here and use the other systems? Since it never uses pinecone or local cache it seems when i have redis


There can only be one "MEMORY_INDEX" so if you have multible AutoGPT projects it seems to be impossible to save each under "memory_index"= (new unique value for each autoGPT folder)
