### ISSUE TITLE
Auto-GPT GUI - Official Repository

### ISSUE THREAD

**Issue by thecookingsenpai** [Significant-Gravitas/Auto-GPT#843]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

I am doing a GUI for AutoGPT currently publishing it on [https://github.com/thecookingsenpai/autogpt-gui](this repo).

Should I pull request it into Auto-GPT code (as it is basically a folder within Auto-GPT directory) or continue standalone (as it is in another programming language and is maintained by different devs)? 

If I should continue standalone, if it is useful, I am fine with linking it here.

NOTE: The GUI is work in progress, as it says in the repo I plan to finish it by at max 5 days so please don't consider it like working, you are free to test anything you want but nothing will work right now

ALSO NOTE: The purpose of this Issue is to understand which is the best course of action to continue with this project and to understand if it is considered useful and in which form it is most useful. Any other possible purpose is NOT the intended one

### Examples 🌈

https://github.com/thecookingsenpai/autogpt-gui

### Motivation 🔦

Accessibility

**Comment by james431987** [comment]
I for one would love a gui

**Comment by richbeales** [comment]
I agree, I think this should stay in a separate repo, personally.
How does it interface with AutoGPT?

**Comment by thecookingsenpai** [comment]
> I agree, I think this should stay in a separate repo, personally.
> 
> How does it interface with AutoGPT?

Quite brute force lol I mean it uses (or to better say at the moment I am using ) child_process and the yaml configuration file and then works with stdio basically 

Feel free to check the repo next days to see it implemented :)

**Comment by thecookingsenpai** [comment]
Just a brief update, Alpha Version is released.
Tested with continuous mode, debug mode, saving file to output and simple tasks

Issues are welcomed 

[](https://github.com/thecookingsenpai/autogpt-gui)

**Comment by amauryfischer** [comment]
already made one here  with some upvotes : 
https://github.com/Torantulino/Auto-GPT/pull/322
@richbeales any thoughts on this ?

**Comment by hanskraut31312312** [comment]
> ### Duplicates
> * [x]  I have searched the existing issues
> 
> ### Summary 💡
> I am doing a GUI for AutoGPT currently publishing it on [https://github.com/thecookingsenpai/autogpt-gui](this repo).
> 
> Should I pull request it into Auto-GPT code (as it is basically a folder within Auto-GPT directory) or continue standalone (as it is in another programming language and is maintained by different devs)?
> 
> If I should continue standalone, if it is useful, I am fine with linking it here.
> 
> NOTE: The GUI is work in progress, as it says in the repo I plan to finish it by at max 5 days so please don't consider it like working, you are free to test anything you want but nothing will work right now
> 
> ALSO NOTE: The purpose of this Issue is to understand which is the best course of action to continue with this project and to understand if it is considered useful and in which form it is most useful. Any other possible purpose is NOT the intended one
> 
> ### Examples 🌈
> https://github.com/thecookingsenpai/autogpt-gui
> 
> ### Motivation 🔦
> Accessibility

Would be awesome to get more customizability

**Comment by Pwuts** [comment]
Make it into a plugin! #757 (expected to drop at the end of this week) :)
