### ISSUE TITLE
Openai API key 3.5

### ISSUE THREAD

**Issue by kingofkillers91** [Significant-Gravitas/Auto-GPT#848]
Hi, can i use my Openai APi key 3.5 for Auto-GPT or do i have to use API Key 4.0?
Thanks

**Comment by richbeales** [comment]
You can use the command line option --gpt3only

**Comment by kingofkillers91** [comment]
what happens if i don't use the --gpt3only?

**Comment by richbeales** [comment]
You're likely to see 'api key not valid' (or similar - i can't recall the exact text)

**Comment by kingofkillers91** [comment]
Thank you, so i won't be able to use the full potential of autogpt with my 3.5 api key right?

**Comment by Pwuts** [comment]
Nope.
