### ISSUE TITLE
Command execute_python_file returned: Error: Invalid file type. Only .py files are allowed.

### ISSUE THREAD

**Issue by claytondukes** [Significant-Gravitas/Auto-GPT#859]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

ask it anything that would require script creation.

In my case, I was trying to extract audio from a video, create a transcript, then replace that audio.

### Current behavior 😯

It still tries to create and run shell scripts.

```
Executing file 'bash_script.sh' in workspace 'auto_gpt_workspace'
SYSTEM:  Command execute_python_file returned: Error: Invalid file type. Only .py files are allowed.
```

### Expected behavior 🤔

Either be capable of running shell scripts, or accept the fact that I told it to write scripts using only python

### Your prompt 📝

This is, of course, after many retries. So it could probably be optimized. Some things are added because it would do stuff like not find ffmpeg and then try to install it using brew.

```yaml
ai_goals:
- Assume you are running on a Mac M1
- assume shell is zshrc
- Assume homebrew is already installed at /opt/homebrew
- Assume ffmpeg is already installed and available at /opt/homebrew/bin/ffmpeg
- use python3 located at /opt/homebrew/bin/python3 for scripts
- use "/opt/homebrew/bin/brew install" if needed
- use "/opt/homebrew/bin/pip3 install" if needed
- all scripts created must be python3, no shell scripts
- save all scripts you create to outputs/
- Using the captions file at inputs/captions.sbv
- Remove the audio from the video
- Rewrite the captions to a more professional tone used for training videos
- create a voiceover from the captions using elevenlabs.io
- for elevenlabs, use the existing ELEVENLABS_API_KEY environment variable
- for elevenlabs, use voice_id "EXAVITQu4va4xN1DfMCL"
- for elevenlabs, documentation for text-to-speach is located at https://api.elevenlabs.io/docs#/text-to-speech
- remove the current audio from the video located at inputs/video.mp4
- Add created voiceover to the video
- save all work to outputs/
```

**Comment by SuperYeti** [comment]
I was having a sort of similar issue where GPT was trying to use execute_python_file with python code. I extended it so there is now a execute_python_code method that creates a local python file and then executes it. I also made some updates to the prompt and have been having better success with GPT-3.5 now. 

https://github.com/Torantulino/Auto-GPT/pull/908

**Comment by Pwuts** [comment]
This is a problem with the LLM, not with Auto-GPT.

**Comment by aicayzer** [comment]
You need to enable the following in the `.env` file:
```
## EXECUTE_LOCAL_COMMANDS - Allow local command execution (Default: False)
## RESTRICT_TO_WORKSPACE - Restrict file operations to workspace ./auto_gpt_workspace (Default: True)
EXECUTE_LOCAL_COMMANDS=True
# RESTRICT_TO_WORKSPACE=False 
```
if you want, you can also allow commands beyond your workspace by removing that commented out line too

**Comment by Pwuts** [comment]
@johanisk please post a log. Without a log, debugging is impossible.
