### ISSUE TITLE
Import Agent from file is broken

### ISSUE THREAD

**Issue by Torantulino** [Significant-Gravitas/Auto-GPT#8606]
We have multiple user reports of not being able to import an Agent, and I'm getting the same behaviour on my end.

[import_agent_json_bug.mp4](https://uploads.linear.app/a47946b5-12cd-4b3d-8822-df04c855879f/d2d7a173-1b35-4e27-8d69-3b8bf57c2f90/c8257ad2-dbf7-4454-bb78-e488bf0f3779?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2E0Nzk0NmI1LTEyY2QtNGIzZC04ODIyLWRmMDRjODU1ODc5Zi9kMmQ3YTE3My0xYjM1LTRlMjctOGQ2OS0zYjhiZjU3YzJmOTAvYzgyNTdhZDItZGJmNy00NDU0LWJiNzgtZTQ4OGJmMGYzNzc5IiwiaWF0IjoxNzMxMzI2NTc0LCJleHAiOjMzMzAxODg2NTc0fQ.Oj_vNm0YMDyIoA597Ezd2qwopJno979spLWdW4OhXGY)

This is pretty important as it means self-host users can't use the marketplace at all, likely that a significant portion of people are effected by this one.

**Comment by csshirri** [comment]
+1 couldn't import agent either

**Comment by Torantulino** [comment]
This is now fixed! 

Give it another try.

You'll need to re-download the agents from https://platform.agpt.co/marketplace as any JSON files you've downloaded before now had that above issue.
