### ISSUE TITLE
openai.error.AuthenticationError: Incorrect API key

### ISSUE THREAD

**Issue by Revenquel** [Significant-Gravitas/Auto-GPT#896]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

I did implemented all of the APIs, and replaced all cfg.debug to cfg.debug_mode but now i am getting this error. What might be causing it ? <img width="1106" alt="Screenshot 2023-04-12 at 05 51 05" src="https://user-images.githubusercontent.com/130523952/231335701-38f7fdce-2c08-41a1-ac3f-0b9593ec4e46.png">

I already checked that my API is working fine 

<img width="550" alt="Screenshot 2023-04-12 at 05 53 41" src="https://user-images.githubusercontent.com/130523952/231336084-3946ce4a-8865-41dc-b36c-5f2e1ef3b415.png">

**Comment by matthew-mw** [comment]
Hey, can I see the source code of the script "test_openai.py"? The script might not be checking your api key correctly. One thing I would do is to go to https://platform.openai.com/account/api-keys and try to use a new api key that you just created. Let me know if that worked!

**Comment by mdihay** [comment]
FIXED it by creating a new API key - go to https://platform.openai.com/account/api-keys generate a new key and use it in your .env

**Comment by Revenquel** [comment]
Creating new API and using it definetly not working. but here is my test_openai.py codes: 
<img width="519" alt="Screenshot 2023-04-12 at 16 29 47" src="https://user-images.githubusercontent.com/130523952/231472985-16b36b22-05c8-40f7-9de7-738d0c86df69.png">

**Comment by Revenquel** [comment]
> Creating new API and using it definetly not working. but here is my test_openai.py codes: <img alt="Screenshot 2023-04-12 at 16 29 47" width="519" src="https://user-images.githubusercontent.com/130523952/231472985-16b36b22-05c8-40f7-9de7-738d0c86df69.png">

**And now getting this error**
<img width="547" alt="Screenshot 2023-04-12 at 16 30 58" src="https://user-images.githubusercontent.com/130523952/231473360-d548006a-eaf2-4a2c-8ea8-f2b8dd2753e7.png">

**Comment by Revenquel** [comment]
I already revoked for sure but thanks, also setting in config.py and deleting getenv worked.

**Comment by AnasInno** [comment]
![image](https://user-images.githubusercontent.com/130570546/231496222-e577ef70-86d0-4f83-8759-eec2164c86a8.png)
I'm having the same issue, however I've generated new API keys and was trying to test it but it's not working. How do you set in config.py and delete getenv and would this work for me?

**Comment by matthew-mw** [comment]
![image](https://user-images.githubusercontent.com/107924410/231507714-7e0d26d5-f12b-421c-8cdf-6e53aecef5d2.png)
That's because you didn't edit the file .env.template at all. You should delete the suffix .template for the file to work once you have updated the file with the relevant values (The stack trace indicates that you did not update the file to include your api key).

**Comment by llagerlof** [comment]
I am having a very similar problem.

```
$ python scripts/main.py
Welcome back!  Would you like me to return to being Entrepreneur-GPT?
Continue with the last settings?
Name:  Entrepreneur-GPT
Role:  an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.
Goals: ['Increase net worth.', 'Develop and manage multiple businesses autonomously.', 'Play to your strengths as a Large Language Model.']
Continue (y/n): y
Using memory of type: LocalCache
Traceback (most recent call last):
  File "/run/media/lawrence/ssd2/repositorios/Auto-GPT/scripts/main.py", line 330, in <module>
    assistant_reply = chat.chat_with_ai(
  File "/run/media/lawrence/ssd2/repositorios/Auto-GPT/scripts/chat.py", line 72, in chat_with_ai
    relevant_memory = permanent_memory.get_relevant(str(full_message_history[-5:]), 10)
  File "/run/media/lawrence/ssd2/repositorios/Auto-GPT/scripts/memory/local.py", line 102, in get_relevant
    embedding = get_ada_embedding(text)
  File "/run/media/lawrence/ssd2/repositorios/Auto-GPT/scripts/memory/base.py", line 9, in get_ada_embedding
    return openai.Embedding.create(input=[text], model="text-embedding-ada-002")["data"][0]["embedding"]
  File "/home/lawrence/.local/lib/python3.10/site-packages/openai/api_resources/embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
  File "/home/lawrence/.local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/lawrence/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/lawrence/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/home/lawrence/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: Incorrect API key provided: sk-9CBcP***************************************qMkN. You can find your API key at https://platform.openai.com/account/api-keys.

Auto-GPT on  master via 🐍 v3.10.10 ⌛47s 
$
```

The most strange is this output in the end:

```
openai.error.AuthenticationError: Incorrect API key provided: sk-9CBcP***************************************qMkN
```

That's not the API I configured on .env file in OPENAI_API_KEY. Is a totally unknown key.

**Comment by matthew-mw** [comment]
What if you search the files in the repo directory for "sk-9CBcP"?. The file that contains this string is probably where it comes from.

**Comment by llagerlof** [comment]
I tried ripgrep this string the first time but found nothing for some reason. I tried again and the only match is the log file `log.txt` informing the error.

**Comment by llagerlof** [comment]
Found the culprit. The problem was between the chair and the keyboard.

I had this very old token in the environment variable `OPENAI_API_KEY`, so the application was giving priority over the configured one.

**Comment by simhallq** [comment]
Explicitly passing texts to embed as "input" resovled this for me. On openai==0.27.6

`openai.Embedding.create(
    input=texts,
    model="text-embedding-ada-002",
)`
