### ISSUE TITLE
execute_python_file returned: Error: Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.')

### ISSUE THREAD

**Issue by rogeriosmorais** [Significant-Gravitas/Auto-GPT#92]
Executing file 'test_environment.py' in workspace 'auto_gpt_workspace'
←[33mSYSTEM:  ←[0mCommand execute_python_file returned: Error: Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.')

**Comment by chriscolisse** [comment]
I had that problem too. Make sure you have docker desktop installed and running

**Comment by kaneda2004** [comment]
Additionally... I too had this problem.
I had docker desktop installed & running -- my issue... WSL or Docker apparently can't interact with filesystems on 8tb drives... 
I have an 8tb EXFAT volume that is invisible to WSL / Docker. Having moved the project to a different volume, it now works as expected.

**Comment by sjnt1** [comment]
Any fix for this without having to install docker?

**Comment by p-i-** [comment]
If anyone still gets this problem, comment and will reopen!

**Comment by JTemmink** [comment]
I'm running autogpt 2.0 stable and got the same message while autogpt after it confirmed the file was there

Executing file 'login_script.py' in workspace 'C:\Auto-GPT\autogpt\auto_gpt_workspace'
SYSTEM:  Command execute_python_file returned: Error: Error while fetching server API version: (2, 'CreateFile', 'Het systeem kan het opgegeven bestand niet vinden.'

**Comment by thundr101** [comment]
Hi - I am seeing this when running AutoGPT 2.0 stable - confirmed file is in the correct location:

Executing file 'save_powerpoint.py' in workspace 'D:\AutoGPT\Auto-GPT\autogpt\auto_gpt_workspace'
SYSTEM:  Command execute_python_file returned: Error: Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.')

**Comment by juanfradb** [comment]
Same here

**Comment by RauKevin** [comment]
Same here

**Comment by i2like** [comment]
Same!

**Comment by BonzBit** [comment]
Same

**Comment by CodyM0RGAN** [comment]
Same

**Comment by mobilbear** [comment]
same here, and i appreciate for no docker solution
