### ISSUE TITLE
stuck in a loop created by itself

### ISSUE THREAD

**Issue by seczoid** [Significant-Gravitas/Auto-GPT#920]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

you ask it to do a fairly complex task and it will be stuck in a loop created by itself

for example:
NEXT ACTION:  COMMAND = make_directory ARGUMENTS = {'directory_name': 'some_research_topic'}
SYSTEM:  Command make_directory returned: Unknown command 'make_directory'. Please refer to the 'COMMANDS' list for availabe commands and only respond in the specified JSON format.

then it will move away from that and again come back the the same spot. 

another observation: it will just ignore the error and assume that specifc task is completed and take actions based on that assumption

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by farrimus** [comment]
The command make_directory is not a part of the programming. The program can append to directories but not make new ones. what was your original instruction for the program?

**Comment by Pwuts** [comment]
Closing as stale & model limitation
