### ISSUE TITLE
Pinecone memory is reset every session

### ISSUE THREAD

**Issue by cosmicr** [Significant-Gravitas/Auto-GPT#924]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

I thought it was meant to have persistent memory between sessions?

Set your config to use pinecone instead of local.

### Current behavior 😯

I notice that every time I restart the pinecone index is reset.

I've also noticed that the vectors created have no namespace?

### Expected behavior 🤔

pinecone index is not reset

### Your prompt 📝

any prompt.

**Comment by Nickonomic** [comment]
"Set your config to use pinecone instead of local.".
How is it done? Although I've set up pinecode keys (and they work on tests), it is always localcache for me.

**Comment by toptracerpeter** [comment]
There is a new environment variable that is not yet documenteted in the README, which is called MEMORY_BACKEND which is defined here; https://github.com/Torantulino/Auto-GPT/blob/master/scripts/config.py

If you set MEMORY_BACKEND=pinecone it should work

**Comment by AsgardStudios** [comment]
@toptracerpeter  I did that, but it produced an error. Do I have to tell it about MEMORY_BACKEND=pinecone somewhere else as well?

**Comment by achimstruve** [comment]
I have the same issue as @AsgardStudios and @Nickonomic .
I set the Pinecone `PINECONE_API_KEY` and `PINECONE_ENV`. Also I set `MEMORY_BACKEND=pinecone`, but still it wants to work only with redis. I shut down redis by removing the corresponding docker container to force it using pinecone, but it didn't help either. Has anyone a suggestion on how to use pinecone over redis considering the already set parameters?

**Comment by cosmicr** [comment]
Yeah, I had to set it in the `config.py` file. Sorry I should have mentioned that. It seems to ignore the ENV variable.

Anyway, I think the problem is that it sets the index to 0 every new session, therefore overwriting any existing indexes.

Here is the code I think:
https://github.com/Torantulino/Auto-GPT/blob/a0f900f2dabd114f80d5e96ecc6269a744dfc99a/scripts/memory/pinecone.py#L19

**Comment by achimstruve** [comment]
Thanks for this!

Now it works for me after I restarted my computer anyways :D

**Comment by perrosnk** [comment]
I am having the same issue with autogpt 0.2.2. Everytime i start it the pinecone db is reset. Any solutions?
