### ISSUE TITLE
ModuleNotFoundError: No module named 'openai'

### ISSUE THREAD

**Issue by bierlingm** [Significant-Gravitas/Auto-GPT#925]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

1. Clone the repo
2. Enter an OpenAI API key in the .env.template file
3. Duplicate the .env.template file as .env
4. Execute `pip install -r requirements.txt`
5. Execute `python scripts/main.py`

### Current behavior 😯

Error message appears:

`Traceback (most recent call last):
  File "/Users/moritzbierling/Code/Auto-GPT/scripts/main.py", line 3, in <module>
    import commands as cmd
  File "/Users/moritzbierling/Code/Auto-GPT/scripts/commands.py", line 1, in <module>
    import browse
  File "/Users/moritzbierling/Code/Auto-GPT/scripts/browse.py", line 3, in <module>
    from config import Config
  File "/Users/moritzbierling/Code/Auto-GPT/scripts/config.py", line 3, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'`

### Expected behavior 🤔

The agent should start running.

### Your prompt 📝

(Didn't get to prompting)

**Comment by richbeales** [comment]
Check whether pip install actually worked, it might have errored (either run as administrator, or run with --user )

**Comment by bierlingm** [comment]
It says requirements are all already satisfied (for all).

Sample:
`Requirement already satisfied: loguru>=0.5.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pinecone-client==2.2.1->-r requirements.txt (line 14)) (0.7.0)
Requirement already satisfied: typing-extensions>=3.7.4 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pinecone-client==2.2.1->-r requirements.txt (line 14)) (4.4.0)
Requirement already satisfied: dnspython>=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pinecone-client==2.2.1->-r requirements.txt (line 14)) (2.3.0)`

**Comment by YluHuu** [comment]
Check your virtual environment

**Comment by bierlingm** [comment]
Sorry if it's not obvious to me how to do that, but could you be so kind and suggest how to do that? Thanks!

**Comment by YluHuu** [comment]
Maybe you have all your libraries installed in one environment, but when you run your project in another environment, this problem arises. Of course, this is just a guess on my part, but hopefully it will be useful for you

**Comment by bierlingm** [comment]
Ah, right, thank you!

**Comment by bingcheng45** [comment]
just installed as well, facing the same issue

**Comment by YluHuu** [comment]
Maybe you can try my methond.

**Comment by bingcheng45** [comment]
> Maybe you can try my methond.

i didn't quite understand this but my issue have been resolved now thank you!

**Comment by ErickAirship** [comment]
> > Maybe you can try my methond.
> 
> i didn't quite understand this but my issue have been resolved now thank you!

Would you mind sharing how you solved it? Thanks.

**Comment by bingcheng45** [comment]
> 

check out my earlier replies where this worked for me 
resolved by running this instead:
`python3 -m pip install -r requirements.txt`

> > > Maybe you can try my methond.
> > 
> > 
> > i didn't quite understand this but my issue have been resolved now thank you!
> 
> Would you mind sharing how you solved it? Thanks.

**Comment by Pwuts** [comment]
Closing as seems resolved

**Comment by komodor8** [comment]
I edited the file `run.sh `
from
`python -m autogpt $@`
to 
`python3 -m autogpt $@`
and it worked for me
