### ISSUE TITLE
Bureaucrats wanted: defect tracking

### ISSUE THREAD

**Issue by nponeccop** [Significant-Gravitas/Auto-GPT#926]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Disclaimer: this is my personal position and not the official maintainer's position, so take the "corporate we" below as a figure of speech.

I would like someone (could be several persons) to do the following:

- Create an issue
- Add there a list of current defects, with PRs fixing them if any, in a simple format. Look for my "batches" for inspiration. This is an example:

If there are duplicates, choose one primary issue and put the duplicate issues along the PRs in the second-level lists. We can tell PRs from issues by the icons.

Note that you must be able to tell a defect from non-defect (in a necessarily subjective way). For example:

- Something that is caused by flaky GPT response (e.g. not answering in JSON, not giving proper instructions to agents and so on) is a prompt engineering defect. Those should not be considered genuine defect for the purpose of this issue, as they are hard to fix and require benchmarking that we don't currently have handy
- Something that adds a new thing is not a defect. E.g. we had logging. If the logging is not broken and works as it's planned during its creation, then it's not a defect
- Something that causes a stack trace is always a defect. Ideally, we should only have error messages, and the traces will be shown only in the debug mode. This will greatly improve the UX for the non-technical users, while imposing a moderate reproduction hassle on developers. With Auto-GPT being a pop star this is essential. I'm not a Pythoner so I ask if this is implementable at all (e.g. in JS you can display the error stack trace in the catch handler at will)
- Something that makes AutoGPT unusable for a layperson is a defect as long as it doesn't require a major overhaul (e.g. Ctrl-C displaying a stacktrace would be considered as a defect)

This doesn't require an approval to anyone, and it shouldn't be intrusive. Try doing a small list and if people don't start screaming on you go on. Work with complaints on your own too, when people say that this is defect and this is not (they certainly will, it's what people do). This is the right way to silently contribute, as the main team don't have time to review and approve all the activities.

### Examples 🌈

Hi all,

This is the current list of defects as defined by @nponeccop in #...

- #803 
  - #804 
  - #696 

### Motivation 🔦

With the now infamous `debug_mode` breakage, we need to figure out the current list of defects, and merge fixes for defects first. So, it's important to classify the current issues and figure out the list of the priority PRs to merge before the "batches" process.

Note that the batches process is prioritized by the PR number, so once your PR is valid (e.g. reviewed to be clean and mergeable), and got into a batch, and is not a big feature, you can be sure that it will be merged in this batch as long as you fix the conflicts. This is IMO an important motivation for the PR authors, that we essentially will merge all old small good PRs in the FIFO order.

**Comment by GrzegorzKarczewski** [comment]
> Consider before investing time on this, but maybe: If you could explain it super simply I can collect things and post it somewhere. Not familiar little exp. Probably not qualified.

I used GPT4 to understand this also. Here is summary : 

The author is suggesting someone take on the task of creating an issue and compiling a list of current defects in AutoGPT, prioritizing them for fixing, and distinguishing them from non-defect issues. The goal is to help prioritize the merging of defect-fixing PRs (Pull Requests) before other "batches" of changes. By listing and classifying defects, the team can better understand which PRs should be merged first to improve the software's overall functionality. This will also motivate contributors, as they can be assured that their PRs will be merged in a timely manner once they are reviewed and deemed clean and mergeable.

**Comment by p-i-** [comment]
Please message me pi#8377 on Discord if you're able and willing to involve at this level!

**Comment by JuroOravec** [comment]
Just found out about Auto-GPT an hour ago. Keen to learn how it works / how to use it. I'll give it a few hours tomorrow (I'm in CEST) to see what issues and PRs there are, and see where it goes.
