### ISSUE TITLE
I was following the instruction but when everything was set up the python scripts/main.py seems does nothing

### ISSUE THREAD

**Issue by EidosL** [Significant-Gravitas/Auto-GPT#939]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

set up everything then use python scripts/main.py and nothing happens

### Current behavior 😯

![image](https://user-images.githubusercontent.com/70374652/231433063-607c853d-a103-4b22-9fe0-8a9d8ac1243b.png)
it sort of just does nothing

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by variety754** [comment]
Same, not responding to y/n, just nothing

**Comment by richbeales** [comment]
@nissan62 your issue will be resolved by taking the latest version of the code from git (git pull)

@EidosL are you sure you're running the right Python (you may have more than 1 python runtime installed).

**Comment by Pwuts** [comment]
Closing as stale. If you have further problems, ask for help in the Discord or in the Discussions here on GitHub.
