### ISSUE TITLE
Only gpt-3.5 being used, without using --gpt3only modifier

### ISSUE THREAD

**Issue by fatinmatvey** [Significant-Gravitas/Auto-GPT#942]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Run python scripts/main.py with OpenAI api key that supports gp4 usage in env 

### Current behavior 😯

Judging by my USAGE page on Open AI, AutoGPT is only making use of gpt-3.5-turbo-0301 and text-embedding-ada-002-v2

### Expected behavior 🤔

AutoGPT should use gpt-4 model 

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by richbeales** [comment]
I have also seen this, I'm not sure on a cause, yet.

**Comment by rbourdon** [comment]
It's hardcoded to use `fast_llm_model` for everything except the `write_tests`, `evaluate_code` and `improve_code` commands. (see https://github.com/Torantulino/Auto-GPT/blob/master/scripts/chat.py#L66 for example)

**Comment by GerardCB** [comment]
Maybe GPT 4 (or ` smart_llm_model`) should be used by default when choosing the command to use next, which should not use many tokens but is the core of AutoGPT. Oftentimes GPT 3.5 fails to select the appropriate command given the agent's thoughts.

**Comment by edcohen08** [comment]
definitely want more input on this #2621 and if it's a good direction need to add tests

**Comment by KayLuke** [comment]
See #3144 proposed fix.
