### ISSUE TITLE
Any plan to support chatglm models？

### ISSUE THREAD

**Issue by wxbty** [Significant-Gravitas/Auto-GPT#945]
### Duplicates

- [X] I have searched the existing issues

**Comment by james431987** [comment]
https://www.youtube.com/watch?v=fGpXj4bl5LI

I can't imagine autoGPT not allowing for the ability to use a model that can run on consumer-grade electronics.
Cool to know that chatglm is the best one for the job right now.

maybe OpenAI can implement a GPT-light version.

**Comment by Pwuts** [comment]
Closing as duplicate of #25, please add to that issue! :)

**Comment by sunshinecf** [comment]
Want to access chatGlm,You solved it
