### ISSUE TITLE
Limit Continuous to Set Time?

### ISSUE THREAD

**Issue by Nrddy** [Significant-Gravitas/Auto-GPT#954]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

can you add a variable that would limit HOW long it can run continuously before it needs the next human prompt? that way its does end up a run away train.

**Comment by sudoshi** [comment]
I had a similar idea.  Set a continuous run time (1h, 2h, 4-6h), after which the human trainer is presented with all the questions it needs a human to answer to proceed.  I noticed if you let it run without supervision for too long, it dead-ends in a loop or hallucinates.

**Comment by rbfussell** [comment]
As well a user input break.    It sucks if it gets stuck doing something broken and you can't really stop it.   Unless I am missing somehting.   Sucks to come back to nothing_done a hundred times.

**Comment by p-i-** [comment]
Probably better to limit it to N steps (where each step is an OpenAI API call to their LLM)

**Comment by Pwuts** [comment]
Closing as resolved; it's possible to allow e.g. 100 autonomous steps with `y -100`.
