### ISSUE TITLE
Add support for poe api?

### ISSUE THREAD

**Issue by User1231300** [Significant-Gravitas/Auto-GPT#97]
For us poor people (or italian, or both).

https://github.com/ading2210/poe-api
https://github.com/vaibhavk97/Poe

**Comment by Qoyyuum** [comment]
Could be set up as an AutoGPT Plugin for anyone interested to use on top of AutoGPT. https://github.com/Significant-Gravitas/Auto-GPT-Plugins

**Comment by Pwuts** [comment]
This is a great idea for a plugin! We're expecting to ship plugin support (#757) at the end of the week.

**Comment by ntindle** [comment]
Closed in favor of  Significant-Gravitas/Auto-GPT-Plugins#19

**Comment by Godoleyas** [comment]
I live in Ethiopia and I am not even allowed to make an OpenAI account let alone pay for it. I tried to add poe.com plugin myself and it's too complicated for me 😭
