### ISSUE TITLE
Hugging Face Integration

### ISSUE THREAD

**Issue by juanfradb** [Significant-Gravitas/Auto-GPT#984]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

It would be great if it could integrate with Hugging Face API like Hugging GPT and have the capacity to do a lot more things.

**Comment by GerardCB** [comment]
This should be easy to implement -specially now that we can get inspiration from [Jarvis](https://github.com/microsoft/JARVIS)- and could benefit AutoGPT a lot!
