### ISSUE TITLE
Massage about Pinecone initializing

### ISSUE THREAD

**Issue by Artemonim** [Significant-Gravitas/Auto-GPT#987]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Add a message like: "Connecting Pinecone. This may take some time..."

### Motivation 🔦

At this point, if the Pinecone index setup takes a noticeable amount of time, the console just stops. It is necessary to notify the user that the index is being configured now and this may take some time.

**Comment by Ashutoshkataria19** [comment]
I have created a pull request.
987: Message about Pinecone initializing

**Comment by Artemonim** [comment]
> #987

#1194 👀

**Comment by Artemonim** [comment]
> Have I done something wrong while tagging or naming? As this is my first pull request so please tell me my mistakes.

You just give the issue ID instead of your PR ID
Also you should write `fix #987` or `close #987` to your PR, so when your PR will be merged this issue will be closed automatically.

**Comment by Ashutoshkataria19** [comment]
I want help with this pull request #1194 
I have directly used `print()` to fix this solution in pinecone.py, which is not the right solution to this problem.
also don't know about the logger.py at that time, but now after reading it, I have three approaches to this problem which I have commented on the same pull request.
so can you please help me?
