### ISSUE TITLE
Cyrillic characters are broken when writing to log.txt

### ISSUE THREAD

**Issue by Artemonim** [Significant-Gravitas/Auto-GPT#995]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

```bash
21:35:19,514 AutoGPT INFO Error: Invalid JSON in assistant thoughts
: ������� �� �����������! ��, � ������ �������� ��������� � ������� Markdown, � � �������, ��� ������ �������� ����������� � ��������� ����. ��� ��������� ����������� � ������ � ���� ������������ ���������� ���� Markdown � ����������� `![](link-to-image)`. ������� �� ���������!
```
Russian: "Спасибо за напоминание! Да, я должен написать результат в формате Markdown, и я осознаю, что нельзя добавить изображения в текстовый файл. Для включения изображения в статью я могу использовать встроенный язык Markdown с синтаксисом `![](link-to-image)`. Спасибо за подсказку!"

English: "Thanks for the reminder! Yes, I have to write the result in Markdown format, and I realize that I can't add images to a text file. I can use the built-in Markdown language with the syntax `![](link-to-image)` to include the image in the article. Thanks for the tip!"

### So what happens?

In most cases Cyrillic characters are converted to the Unicode Escape format. If for some reason (for example #994) they were not encoded in Unicode Escape - they will not be displayed correctly in the log.

**Comment by Pwuts** [comment]
Related: #232
